declare @tabesqueleto table (ID INT IDENTITY(1,1), ESQUELETO VARCHAR(50))

insert into @tabesqueleto (ESQUELETO) values ('BERMUDA TECIDO QUADRILE')
insert into @tabesqueleto (ESQUELETO) values ('M/C WAFFLE')


--insert into @tabesqueleto (ESQUELETO) values ('PIJAMA M/L E CALÇA MEIA MALHA LIC')
--insert into @tabesqueleto (ESQUELETO) values ('CALCINHA POLIAMIDA BIQUINI CLASSIC TEX DILADY')
--insert into @tabesqueleto (ESQUELETO) values ('CALCINHA POLIAMIDA BIQUINI BASIC TEX DILADY')


DECLARE @ULTIMO_CODIGO INT, @codigo varchar(6)
SELECT @ULTIMO_CODIGO = CAST(max(codigo) AS INT) from CAEDU_LISTA_COMBO

SELECT @codigo = FORMAT(id + @ULTIMO_CODIGO,'000000')
FROM @tabesqueleto a

IF NOT EXISTS(SELECT 1 FROM CAEDU_DOMINIO_COMBOS WHERE COD_DOMINIO = '026')
BEGIN
	INSERT INTO CAEDU_DOMINIO_COMBOS VALUES ('026','ESQUELETO','CADASTRO DE ESQUELETO PLANEJAMENTO')
END

insert into CAEDU_LISTA_COMBO (codigo,descricao,id_dominio,desc_dominio,ERP_CUPS_DESCRICAO_IMPORTACAO)
select FORMAT(id + @ULTIMO_CODIGO,'000000') as codigo,
a.ESQUELETO as descricao,
'026' id_dominio,
'ESQUELETO' desc_dominio,
a.ESQUELETO as ERP_CUPS_DESCRICAO_IMPORTACAO
from @tabesqueleto a

UPDATE SEQUENCIAIS SET SEQUENCIA = @codigo WHERE TABELA_COLUNA = 'CAEDU_LISTA_COMBO.CODIGO'

/* PROVA DOS NOVE
-- RODE PRA VER SE ATUALIZOU CERTINHO --

select max(codigo) from caedu_lista_combo
SELECT * FROM SEQUENCIAIS WHERE TABELA_COLUNA LIKE 'CAEDU_LISTA%'
SELECT CODIGO,descricao as ESQUELETO FROM CAEDU_LISTA_COMBO WHERE id_dominio = '026' order by codigo

produtos

UPDATE PRODUTOS SET ERP_COD_ESQUELETO='XXX', ERP_DESC_ESQUELETO='XXX' WHERE PRODUTO='XXX'

select * 
from caedu_lista_combo where id_dominio='026' 
and descricao in
('BEIRA RIO MOLECA'
,'BEIRA RIO BEIRA RIO'
,'BEIRA RIO MODARE'
,'BEIRA RIO VIZZANO'
,'BEIRA RIO ACTVITTA'
,'GRENDENE IPANEMA'
,'GRENDENE ZAXY'
,'GRENDENE GRENDHA'
,'RR SHOES VIAUNO'
,'GRENDENE RIDER'
,'GRENDENE CARTAGO'
,'GRENDENE MORMAII'
,'BEIRA RIO MOLEKINHA'
,'GRENDENE ZAXY NINA'
,'GRENDENE GREND KIDS'
,'BEIRA RIO MOLEKINHO'
,'GRENDENE CARTAGO'
,'GRENDENE RIDER')

UPDATE PRODUTOS SET ERP_COD_ESQUELETO='XXX', ERP_DESC_ESQUELETO='XXX' WHERE PRODUTO='XXX';
*/
