SELECT RTRIM(A.ROMANEIO_PRODUTO)                        AS CodigoPedido
    , RTRIM(A.NUMERO_NF_TRANSFERENCIA)                 AS NotaFiscal
    , RTRIM(A.CHAVE_NFE)                               AS ChaveNfe
    , RTRIM(A.SERIE_NF_ENTRADA)                        AS Serie
    , RTRIM(CONVERT(DATE,A.EMISSAO))                   AS Emissao
    , FN.CLIFOR        AS CodigoFornecedorErp
    , CASE WHEN FN.CLIFOR IS NULL THEN 0 ELSE 1 END AS ValidFornecedor
    , ISNULL(FP.PEDIDO,FP.ITEM_CAEDU )                   Pedido
    , CASE 
    WHEN   MAX(ISNULL(TAB1.IMPORTADOS,0)) > 0 
    THEN 'T' ELSE 'TI'  END             AS TipoEntrada
    , (   SELECT RTRIM(ROMANEIO_PRODUTO)           AS CodigoPedido
        , RTRIM(PRODUTO)         AS Produto
        , RTRIM(QUANTIDADE)     AS Quantidade
        , NULL         AS Custo
        , NULL         AS Desconto
        , NULL         AS ValorTotal
    FROM
        (
        SELECT CP.ROMANEIO_PRODUTO
        , CP.PRODUTO
        , CP.QTDE_ENTRADA AS QUANTIDADE 
        FROM LOJA_ENTRADAS_PRODUTO CP  (NOLOCK)
        JOIN PRODUTOS_BARRA C  (NOLOCK) 
            ON C.PRODUTO = CP.PRODUTO 
        AND C.COR_PRODUTO = CP.COR_PRODUTO
        JOIN LOJA_ENTRADAS  (NOLOCK) D  ON D.ROMANEIO_PRODUTO = CP.ROMANEIO_PRODUTO 
                AND D.FILIAL = CP.FILIAL
        WHERE CP.ROMANEIO_PRODUTO = A.ROMANEIO_PRODUTO
        AND CP.FILIAL  = A.FILIAL
        GROUP BY CP.ROMANEIO_PRODUTO
        , CP.PRODUTO
        , CP.QTDE_ENTRADA
        ) p
        WHERE QUANTIDADE > 0 FOR JSON PATH ) as RecebimentoItens,
        MAX(ISNULL(TAB1.IMPORTADOS,0)) AS IMPORTADOS,
        max(fp.item_caedu) AS item_caedu 
    FROM LOJA_ENTRADAS A  (NOLOCK)
    JOIN LOJA_ENTRADAS_PRODUTO P   (NOLOCK)
    ON A.ROMANEIO_PRODUTO = P.ROMANEIO_PRODUTO 
    AND A.FILIAL = P.FILIAL
    LEFT JOIN FATURAMENTO_PROD FP (NOLOCK)
    ON FP.FILIAL = A.FILIAL_ORIGEM
    AND FP.NF_SAIDA = A.NUMERO_NF_TRANSFERENCIA
    AND FP.PRODUTO = P.PRODUTO
    AND FP.COR_PRODUTO = P.COR_PRODUTO
LEFT JOIN  ( SELECT E.PEDIDO
    , CP.ERP_CUPS_SEGMENTO
    , CP.FILIAL_A_ENTREGAR
    , CP.FORNECEDOR
    , F.ERP_IMPORTADORA
    , XX.PEDIDO_TRANSFERENCIA
    , E.NOME_CLIFOR
    FROM (
        SELECT ctn.[NOME_CLIFOR], 
        [NF_ENTRADA],[SERIE_NF_ENTRADA], 
        [FILIAL_ENTRADA], [FILIAL],[SERIE_NF],
        [NF_SAIDA], [DATA], [PEDIDO_TRANSFERENCIA]
        , ccf.CLIFOR 
        FROM CSM_TRANSITO_NOTAS CTN 
        inner join cadastro_cli_for ccf ON ccf.NOME_CLIFOR=ctn.nome_clifor
        WHERE 
        CTN.PEDIDO_TRANSFERENCIA IN (
        SELECT isnull(C.PEDIDO, c.item_caedu) AS PEDIDO
        FROM LOJA_ENTRADAS A
        INNER JOIN LOJA_ENTRADAS_PRODUTO B ON B.ROMANEIO_PRODUTO = A.ROMANEIO_PRODUTO  
        INNER JOIN FATURAMENTO_PROD C ON C.FILIAL=A.FILIAL_ORIGEM 
                AND C.NF_SAIDA=A.NUMERO_NF_TRANSFERENCIA 
                AND C.SERIE_NF=A.SERIE_NF_ENTRADA
                AND C.PRODUTO=B.PRODUTO
                AND C.COR_PRODUTO=B.COR_PRODUTO)) XX
        INNER JOIN ESTOQUE_PROD_ENT E ON E.NF_ENTRADA = XX.NF_ENTRADA 
                AND E.SERIE_NF_ENTRADA=XX.SERIE_NF_ENTRADA
                AND E.NOME_CLIFOR = XX.NOME_CLIFOR
        INNER JOIN COMPRAS CP ON CP.PEDIDO = E.PEDIDO
        INNER JOIN FORNECEDORES F ON F.FORNECEDOR = CP.FORNECEDOR
        WHERE F.ERP_IMPORTADORA = 0 
    ) Z
ON Z.PEDIDO_TRANSFERENCIA = isnull(fp.item_caedu, FP.PEDIDO)
LEFT JOIN FILIAIS F  (NOLOCK) ON F.FILIAL = A.FILIAL_ORIGEM
LEFT JOIN ( SELECT T2.CHAVE_NFE, COUNT(*) AS IMPORTADOS 
    FROM FATURAMENTO_PROD T1 
    INNER JOIN FATURAMENTO T2 
    ON T2.NF_SAIDA = T1.NF_SAIDA AND T2.SERIE_NF = T1.SERIE_NF AND T2.FILIAL = T1.FILIAL
    INNER JOIN PRODUTOS T3 ON T3.PRODUTO = T1.PRODUTO
    INNER JOIN FORNECEDORES T4 ON T4.FORNECEDOR = T3.FABRICANTE
    WHERE  T4.ERP_IMPORTADORA = 1 
    GROUP BY T2.CHAVE_NFE) TAB1 ON TAB1.CHAVE_NFE = A.CHAVE_NFE 
LEFT JOIN FORNECEDORES FN  (NOLOCK) ON FN.FORNECEDOR = Z.NOME_CLIFOR
WHERE ENTRADA_ENCERRADA = 0
    AND A.FILIAL = 'CD - SP - SAO ROQUE'
GROUP BY A.ROMANEIO_PRODUTO
    , A.EMISSAO
    , A.CHAVE_NFe
    , A.NUMERO_NF_TRANSFERENCIA
    , A.SERIE_NF_ENTRADA
    , A.FORNECEDOR
    , F.COD_FILIAL
    , A.FILIAL
    , FP.PEDIDO 
    ,FN.CLIFOR
    ,fp.item_caedu
ORDER BY A.EMISSAO DESC
