USE [CAEDU]
GO

/****** Object:  View [dbo].[CGP_VW_DADOS_CLUSTER_PEDIDOS]    Script Date: 30/12/2024 15:05:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE OR ALTER VIEW [dbo].[CGP_VW_DADOS_CLUSTER_PEDIDOS] AS

SELECT DISTINCT       
	   'N' AS ISPROCCESSED 
	   ,LTRIM(RTRIM(C.PEDIDO)) AS NUMERO_PEDIDO
	   ,CASE WHEN LTRIM(RTRIM(SUBSTRING(CP.PACKS,1,25))) = '' THEN 'X' ELSE LTRIM(RTRIM(SUBSTRING(CP.PACKS,1,25))) END AS NUMERO_PACK
	   ,LTRIM(RTRIM(P.PRODUTO)) AS CODIGO_PRODUTO		   
	   --,CASE WHEN RTRIM(LTRIM(C.FORNECEDOR)) = 'KOMPORT' 
	   ,CASE WHEN CHARINDEX(RTRIM(LTRIM(C.FORNECEDOR)), 'HARPIA IMPORTADORA E DIST|KOMPORT')>0 /*IDENTIFICA SE É IMPORTADO*/
	       THEN (SELECT VALOR_ATUAL FROM PARAMETROS P WITH (NOLOCK) WHERE P.PARAMETRO = 'UNOUS_CLUSTER_IMPORTADO') 
		   ELSE (SELECT VALOR_ATUAL FROM PARAMETROS P WITH (NOLOCK) WHERE P.PARAMETRO = 'UNOUS_CLUSTER_NACIONAL') 
		END AS CLUSTERCODE 
	   --,CASE WHEN RTRIM(LTRIM(C.FORNECEDOR)) = 'KOMPORT' 
	   ,CASE WHEN CHARINDEX(RTRIM(LTRIM(C.FORNECEDOR)), 'HARPIA IMPORTADORA E DIST|KOMPORT')>0 /*IDENTIFICA SE É IMPORTADO*/
	       THEN (SELECT VALOR_ATUAL FROM PARAMETROS P WITH (NOLOCK) WHERE P.PARAMETRO = 'UNOUS_QUADRANTE_IMPORTADO')
		   ELSE (SELECT VALOR_ATUAL FROM PARAMETROS P WITH (NOLOCK) WHERE P.PARAMETRO = 'UNOUS_QUADRANTE_NACIONAL') 
		END AS QUADRANTCODE
	   ,CP.ENTREGA 
  FROM CAEDU.DBO.COMPRAS C WITH (NOLOCK)
       INNER JOIN CAEDU.DBO.COMPRAS_PRODUTO CP WITH (NOLOCK)
	           ON C.PEDIDO       = CP.PEDIDO
       INNER JOIN CAEDU.DBO.PRODUTOS P WITH (NOLOCK)
		       ON P.PRODUTO      = CP.PRODUTO
WHERE 1 = 1 
  AND CP.ENTREGA >= GETDATE() - 40
  AND  DATEDIFF(MINUTE, ERP_UNOUS_DATA_ENVIO , GETDATE()) < 15 

  UNION 
  
  SELECT DISTINCT       
	    'N' AS ISPROCCESSED 
		,(select TOP 1 VALOR_ATUAL from PARAMETROS where PARAMETRO = 'UNOUS_COD_CD_DISTRIBUICAO') AS NUMERO_PEDIDO
       -- ,ISNULL(ED.PACK, 'A') AS NUMERO_PACK
		,CASE WHEN ED.PACK IS NULL OR ED.PACK = '' THEN 'A' ELSE ED.PACK END AS NUMERO_PACK
	    ,LTRIM(RTRIM(ED.PRODUTO)) AS CODIGO_PRODUTO 	   
	   ,CASE WHEN PROP.VALOR_PROPRIEDADE = 'SIM'
	              THEN (SELECT VALOR_ATUAL FROM PARAMETROS P WITH (NOLOCK) WHERE P.PARAMETRO = 'UNOUS_CLUSTER_NACIONAL')
		     WHEN PROP.VALOR_PROPRIEDADE <> 'SIM'
	              THEN (SELECT VALOR_ATUAL FROM PARAMETROS P WITH (NOLOCK) WHERE P.PARAMETRO = 'UNOUS_CLUSTER_IMPORTADO')			 
		END AS CLUSTERCODE 
	   ,CASE WHEN PROP.VALOR_PROPRIEDADE = 'SIM' 
	              THEN (SELECT VALOR_ATUAL FROM PARAMETROS P WITH (NOLOCK) WHERE P.PARAMETRO = 'UNOUS_QUADRANTE_NACIONAL')	   
		    WHEN PROP.VALOR_PROPRIEDADE <> 'SIM' 
			      THEN (SELECT VALOR_ATUAL FROM PARAMETROS P WITH (NOLOCK) WHERE P.PARAMETRO = 'UNOUS_QUADRANTE_IMPORTADO')
		END AS QUADRANTCODE
		,GETDATE() AS ENTREGA
    FROM [CAEDU].[DBO].VW_DITRIBUICAO ED WITH (NOLOCK)			 
	     INNER JOIN [CAEDU].[DBO].PRODUTOS P WITH (NOLOCK) 
		         ON P.PRODUTO = ED.PRODUTO               
         INNER JOIN PROP_PRODUTOS PROP
	             ON PROP.PRODUTO = P.PRODUTO
			    AND PROPRIEDADE ='00108' 
                		




GO


