SELECT    
dbo.COMPRAS_PRODUTO.PEDIDO,
dbo.COMPRAS.ERP_CUPS_SEGMENTO,
dbo.COMPRAS.FORNECEDOR,
dbo.COMPRAS.CADASTRAMENTO,
dbo.PRODUTOS.REFER_FABRICANTE,
dbo.PRODUTOS.ERP_GRUPO_MERCADORIA,
dbo.COMPRAS.REQUERIDO_POR,
dbo.COMPRAS.TIPO_COMPRA,
dbo.COMPRAS_PRODUTO.PRODUTO,
dbo.COMPRAS_PRODUTO.COR_PRODUTO,
dbo.PRODUTOS.GRIFFE,
dbo.PRODUTOS.GRIFFE,
dbo.PRODUTOS.LINHA,
dbo.PRODUTOS.GRUPO_PRODUTO,
dbo.PRODUTOS.SUBGRUPO_PRODUTO,
dbo.PRODUTOS.CLASSIF_FISCAL,
dbo.PRODUTOS.DESC_PRODUTO,
dbo.PRODUTOS.TIPO_PRODUTO,
dbo.PRODUTOS.COLECAO,
dbo.PRODUTOS.FATOR_P,
dbo.COMPRAS.OBS,
dbo.COMPRAS_PRODUTO.ENTREGA,
dbo.COMPRAS_PRODUTO.LIMITE_ENTREGA,
dbo.COND_ENT_PGTOS.DESC_COND_PGTO,
dbo.COMPRAS_PRODUTO.CUSTO1,
dbo.PRODUTOS_PRECOS.PRECO1,
dbo.COMPRAS_PRODUTO.QTDE_ORIGINAL,
dbo.COMPRAS_PRODUTO.QTDE_CANCELADA,
dbo.COMPRAS_PRODUTO.QTDE_ENTREGUE,
dbo.COMPRAS_PRODUTO.QTDE_ENTREGAR,
dbo.COLECOES.DESC_COLECAO,
dbo.PRODUTOS_CATEGORIA.CATEGORIA_PRODUTO,
dbo.PRODUTOS.TRIBUT_ORIGEM,
dbo.COMPRAS.FILIAL_A_ENTREGAR,
dbo.PRODUTOS.ERP_DESC_LICENCIADO AS LICENCIADOR,
dbo.cadastro_cli_for.UF,
dbo.COMPRAS.ERP_CAB_COD_CABIDE,
dbo.COMPRAS.ERP_CAB_QTDPECAS,
dbo.COMPRAS.ERP_CAB_STATUS,
dbo.COMPRAS.ERP_CAB_DATA_ENVIO,
dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.QTDE as Total_PACK
, CASE COMPRAS.ERP_CAB_COD_BOLACHA
       WHEN 'E1'     THEN '1 ALARME'                
       WHEN 'E2'     THEN '2 ALARMES'               
       WHEN ''     THEN 'NENHUM'               
       ELSE ''
END  AS 'QTD ALARME'
, CASE COMPRAS.ERP_CAB_OPCAO
       WHEN '1'     THEN 'NENHUM'                
       WHEN '2'     THEN 'SÓ CABIDE'               
       WHEN '3'     THEN 'SÓ ALARME'               
       WHEN '4'     THEN 'CABIDE+ALARME'
       ELSE ''
END  AS 'OPCAO_CABIDE'
, CASE dbo.COMPRAS.STATUS_COMPRA
       WHEN '01'     THEN 'APROVADO'                
       WHEN '02'     THEN 'EM ESTUDO'               
       WHEN '03'     THEN 'REPROVADO'               
       WHEN '04'     THEN 'AGUARDANDO SENHA'
       ELSE ''
END  AS 'STATUS_PEDIDO'
,ISNULL((SELECT TOP 1 ISNULL(VALOR_PROPRIEDADE,'') AS VALOR_PROPRIEDADE
FROM PROP_PRODUTOS WHERE PROPRIEDADE = '00114' AND PRODUTO = COMPRAS_PRODUTO.PRODUTO),'') AS CAMPANHA_CARTAO
,(select min(emissao) from ESTOQUE_PROD_ENT where pedido = dbo.COMPRAS.pedido) as DATA_RECEBIMENTO
,(select top 1 DESC_COR_PRODUTO from dbo.PRODUTO_CORES where cor = dbo.COMPRAS_PRODUTO.COR_PRODUTO and PRODUTO = dbo.COMPRAS_PRODUTO.PRODUTO) as DESC_COR
,COALESCE(CAST(id_modelagem AS CHAR(5)),'')  AS "ID MODELAGEM"
,COALESCE(ERP_TEMA_LICENCIADO, '') AS "LICENCIADO"
,case produtos.CONTINUIDADE
when 1 THEN 'CONTINUO'
when 2 THEN 'SEMI-CONTINUO'
when 3 THEN 'DESCONTINUO'
else ''
end as CONTINUO,
ISNULL((SELECT TOP 1 ISNULL(VALOR_PROPRIEDADE,'') AS VALOR_PROPRIEDADE
       FROM PROP_COMPRAS WHERE PROPRIEDADE = '00093' AND PEDIDO = COMPRAS.PEDIDO),'') AS BONIFICACAO,
ISNULL((SELECT TOP 1 ISNULL(VALOR_PROPRIEDADE,'') AS VALOR_PROPRIEDADE
       FROM PROP_COMPRAS WHERE PROPRIEDADE = '00095' AND PEDIDO = COMPRAS.PEDIDO),'') AS PRONTA_ENTREGA,
 
CGP_UNOUS_ENVIAR_TODAS_LOJAS_PEDIDO = ISNULL((select VALOR_PROPRIEDADE from PROP_COMPRAS where propriedade = '00106' AND PEDIDO = COMPRAS.PEDIDO),'NÃO'),
CGP_UNOUS_ALOCAR_PRODUTO = ISNULL((SELECT VALOR_PROPRIEDADE FROM PROP_PRODUTOS WHERE PROPRIEDADE = '00108' AND PRODUTO = PRODUTOS.PRODUTO),'NÃO'),
ISNULL((SELECT TOP 1 ISNULL(VALOR_PROPRIEDADE,'') AS VALOR_PROPRIEDADE
       FROM PROP_COMPRAS WHERE PROPRIEDADE = '00111' AND PEDIDO = COMPRAS.PEDIDO),'') AS DATA_ORIGINAL,
ISNULL((SELECT TOP 1 ISNULL(VALOR_PROPRIEDADE,'') AS VALOR_PROPRIEDADE
       FROM PROP_COMPRAS WHERE PROPRIEDADE = '00112' AND PEDIDO = COMPRAS.PEDIDO),'') AS JUSTIFICATIVA,
ISNULL((SELECT TOP 1 ISNULL(VALOR_PROPRIEDADE,'') AS VALOR_PROPRIEDADE
       FROM PROP_COMPRAS WHERE PROPRIEDADE = '00110' AND PEDIDO = COMPRAS.PEDIDO),'') AS E_COMMERCE
,DBO.PRODUTOS.ERP_FT_DESC_CLASSIFICACAO AS CLASSIFICACAO, compras.DESCONTO
,dbo.PRODUTOS.ERP_CUPS_EVENTO
,(select top 1 DESCRICAO from dbo.CAEDU_LISTA_COMBO where codigo = dbo.PRODUTOS.ERP_CUPS_EVENTO) as DESC_EVENTO
,COMPRAS.ERP_MES_NA_LOJA
FROM         dbo.COMPRAS_PRODUTO INNER JOIN
                      dbo.PRODUTOS ON dbo.COMPRAS_PRODUTO.PRODUTO = dbo.PRODUTOS.PRODUTO INNER JOIN
                      dbo.PRODUTOS_PRECOS ON dbo.PRODUTOS.PRODUTO = dbo.PRODUTOS_PRECOS.PRODUTO INNER JOIN
                      dbo.COLECOES ON DBO.COLECOES.COLECAO = DBO.PRODUTOS.COLECAO INNER JOIN
                      dbo.COMPRAS ON dbo.COMPRAS_PRODUTO.PEDIDO = dbo.COMPRAS.PEDIDO INNER JOIN
                      dbo.PRODUTOS_CATEGORIA  ON dbo.PRODUTOS.COD_CATEGORIA    = dbo.PRODUTOS_CATEGORIA.COD_CATEGORIA INNER JOIN
                      dbo.COND_ENT_PGTOS ON dbo.COMPRAS.CONDICAO_PGTO = dbo.COND_ENT_PGTOS.CONDICAO_PGTO
INNER JOIN dbo.cadastro_cli_for on compras.fornecedor=cadastro_cli_for.nome_clifor
INNER JOIN  dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL ON dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.PEDIDO = dbo.COMPRAS_PRODUTO.PEDIDO
LEFT    JOIN  dbo.PRODUTOS_PRECOS prc_at   ON dbo.PRODUTOS.PRODUTO          = prc_at.PRODUTO and prc_at.CODIGO_TAB_PRECO = 'AT'
LEFT    JOIN  dbo.PRODUTOS_PRECOS prc_va   ON dbo.PRODUTOS.PRODUTO          = prc_va.PRODUTO and prc_va.CODIGO_TAB_PRECO = 'VA'
 
                 
WHERE (dbo.PRODUTOS_PRECOS.CODIGO_TAB_PRECO = '01') AND (dbo.COMPRAS_PRODUTO.ENTREGA > 43466) AND (dbo.PRODUTOS.GRIFFE = 'INFANTIL')