
--00000264

DECLARE @DISTRIBUICAO VARCHAR(8)
SET @DISTRIBUICAO = '00000187'

SELECT * FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS 
WHERE DISTRIBUICAO = @DISTRIBUICAO

SELECT * FROM VENDAS
WHERE PEDIDO IN (SELECT VENDA FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS WHERE DISTRIBUICAO = @DISTRIBUICAO) ;

SELECT * FROM VENDAS_PRODUTO
WHERE PEDIDO IN (SELECT VENDA FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS WHERE DISTRIBUICAO = @DISTRIBUICAO) ;


SELECT * FROM FATURAMENTO_CAIXAS
WHERE CAIXA IN (SELECT CAIXA FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS WHERE DISTRIBUICAO = @DISTRIBUICAO) ;

SELECT * FROM CAEDU_RESERVA_AUTOMATICA_WMS WHERE DISTRIBUICAO = @DISTRIBUICAO ;

SELECT * 
FROM VENDAS_PROD_EMBALADO
WHERE CAIXA IN (
SELECT CAIXA FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS WHERE DISTRIBUICAO = @DISTRIBUICAO) ;



select * from vendas_prod_embalado where pedido in (
select venda from CAEDU_RESERVA_AUTOMATICA_PACK_WMS  where distribuicao = '00000187')




