/*
00000993
00000988
00000971
*/
DECLARE @DISTRIBUICAO VARCHAR(8)
SET @DISTRIBUICAO = '00000997'

--SELECT * FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS 
--WHERE DISTRIBUICAO = @DISTRIBUICAO

DELETE VENDAS 
--SELECT * FROM VENDAS
WHERE PEDIDO IN (SELECT VENDA FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS WHERE DISTRIBUICAO = @DISTRIBUICAO) ;

DELETE VENDAS 
--SELECT * FROM VENDAS_PRODUTO
WHERE PEDIDO IN (SELECT VENDA FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS WHERE DISTRIBUICAO = @DISTRIBUICAO) ;


DELETE FROM FATURAMENTO_CAIXAS
WHERE CAIXA IN (SELECT CAIXA FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS WHERE DISTRIBUICAO = @DISTRIBUICAO) ;

DELETE FROM CAEDU_RESERVA_AUTOMATICA_WMS WHERE DISTRIBUICAO = @DISTRIBUICAO ;

DELETE
FROM VENDAS_PROD_EMBALADO
WHERE CAIXA IN (
SELECT CAIXA FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS WHERE DISTRIBUICAO = @DISTRIBUICAO) ;


UPDATE CAEDU_RESERVA_AUTOMATICA_PACK_WMS 
SET GERADO = 0
WHERE DISTRIBUICAO = @DISTRIBUICAO

--DELETE CAEDU_RESERVA_AUTOMATICA_PACK_WMS 
--WHERE DISTRIBUICAO = @DISTRIBUICAO

/*
exclusao da distribuicao nas tabelas da PDA 
*/

--DELETE FROM PDA_WMS_TB_DISTRIBUICAO WHERE DISTRIBUICAO = @DISTRIBUICAO


--DELETE FROM PDA_WMS_TB_RESERVA_DISTRIBUICAO WHERE DISTRIBUICAO = @DISTRIBUICAO


--DELETE FROM PDA_WMS_STATUS_DISTRIBUICAO WHERE DISTRIBUICAO = @DISTRIBUICAO




/*
SELECT * FROM VENDAS_PROD_EMBALADO WHERE CAIXA
IN (SELECT CAIXA FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS WHERE DISTRIBUICAO = '00000250'
) 

SELECT * FROM FATURAMENTO_PROD WHERE CAIXA
IN (SELECT CAIXA FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS WHERE DISTRIBUICAO = '00000250'
) 

*/


--SELECT * FROM PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE WHERE PRODUTO = 'C8010057'