
ALTER TABLE TB_MINUTA
ALTER COLUMN NF_SAIDA VARCHAR(15)
GO
ALTER TABLE TB_MINUTA
ALTER COLUMN  SERIE_NF VARCHAR(6)
GO
ALTER TABLE TB_MINUTA 
ADD DATA_MOV DATETIME NOT NULL CONSTRAINT DF_TB_MINUTA_DATAMOV DEFAULT (GETDATE())
GO
