ALTER TABLE CAE_MENSAGEM_ETIQUETA
ALTER COLUMN DESCRI_MSG VARCHAR(50)
GO

UPDATE CAE_MENSAGEM_ETIQUETA 
SET DESCRI_MSG = 'TROCA APENAS COM ETIQUETA E CUPOM FISCAL' 
WHERE CODIGO_MSG=2
GO

select * from CAE_MENSAGEM_ETIQUETA

