ALTER TABLE FILIAIS 
ADD ERP_EXCLUI_DA_MEDIA_PONDERADA BIT NOT NULL DEFAULT (0)
GO

UPDATE FILIAIS 
SET ERP_EXCLUI_DA_MEDIA_PONDERADA = 1
WHERE FILIAL IN 
('TRANSPORTADORA CAEDU','CD EMBU', 'CELOTE', 'CD VAREJO','CONTROLE DE QUALIDADE', 'DIVERGENCIA', 'JAU', 'TATUAPE', 'BAURU', 'RIO PRETO', 'MATRIZ',
'CD ARAQUARI','CD ARAUARI','CD BARRA VELHA','CD CAJAMAR','CD NAVEGANTES','CD REGIS','ARAQUARI CQ','NAVEGANTES CQ','REJEITADO CQ','BARRA VELHA - CQ','CAJAMAR - CQ')
GO






