--select * from propriedade
DECLARE @TABEXCECOES TABLE (FILIAL VARCHAR(25))
INSERT INTO @TABEXCECOES VALUES 
('AMOSTRA CD REGIS'),
('AMOSTRA PIRAJA'),
('AMOSTRA TIJUCO'),
('ARAQUARI CQ'),
('BARRA VELHA - CQ'),
('BAURU'),
('CAJAMAR - CQ'),
('CD ARAQUARI'),
('CD ARAUARI'),
('CD BARRA VELHA'),
('CD BARRA VELHA - W10'),
('CD BARRA VELHA - W20'),
('CD CAJAMAR'),
('CD CAJAMAR - W10'),
('CD CAJAMAR - W20'),
('CD CAJAMAR FALTA IMP'),
('CD CAJAMAR FALTA IMP ATC'),
('CD CAJAMAR SINISTRO'),
('CD EMBU'),
('CD NAVEGANTES'),
('CD NAVEGANTES - W10'),
('CD NAVEGANTES - W20'),
('CD REGIS'),
('CD VAREJO'),
('CELOTE'),
('CONTROLE DE QUALIDADE'),
('DIVERGENCIA'),
('JAU'),
('MATRIZ'),
('NAVEGANTES CQ'),
('REJEITADO - CD CAJAMAR'),
('REJEITADO CQ'),
('RIO PRETO'),
('TATUAPE'),
('TRANSPORTADORA CAEDU'),
('VENDA ATACADO'),
('VENDA ATACADO SC')

select * 
--UPDATE A SET VALOR_PROPRIEDADE='NÃO'
from prop_filiais A 
--INNER JOIN @TABEXCECOES B ON B.FILIAL = A.FILIAL
where propriedade='00117'
--INSERT INTO PROP_FILIAIS
--select '00117' AS PROPRIEDADE, FILIAL, 
--		1 AS ITEM_PROPRIEDADE, 'SIM' AS VALOR_PROPRIEDADE,
--		GETDATE() AS DATA_PARA_TRANSFERENCIA, NULL AS CHECKSUM_ORIGEM
--FROM FILIAIS
--WHERE FILIAL<>'CD CAJAMAR'