update produtos set grupo_produto='COMM 4', subgrupo_produto = 'C 4' where produto = 'A3020029'
update produtos set grupo_produto='COMM 4', subgrupo_produto = 'C 4' where produto = 'A3020029'
update produtos set grupo_produto='COMM 4', subgrupo_produto = 'C 4' where produto = 'A3020030'
update produtos set grupo_produto='COMM 4', subgrupo_produto = 'C 4' where produto = 'A3020030'
update produtos set grupo_produto='COMM 4', subgrupo_produto = 'C 4' where produto = 'A3020031'
update produtos set grupo_produto='COMM 4', subgrupo_produto = 'C 4' where produto = 'A3020031'
update produtos set grupo_produto='COMM 4', subgrupo_produto = 'C 4' where produto = 'A3020032'
update produtos set grupo_produto='COMM 4', subgrupo_produto = 'C 4' where produto = 'A3020032'
update produtos set grupo_produto='COMM 4', subgrupo_produto = 'C 4' where produto = 'A3020033'
update produtos set grupo_produto='COMM 4', subgrupo_produto = 'C 4' where produto = 'A3020033'
update produtos set grupo_produto='MESA 5', subgrupo_produto = 'MESA 5 SUP' where produto = 'N6010015'
update produtos set grupo_produto='MESA 5', subgrupo_produto = 'MESA 5 SUP' where produto = 'N6010016'
update produtos set grupo_produto='MESA 5', subgrupo_produto = 'MESA 5 SUP' where produto = 'N6010017'
update produtos set grupo_produto='MESA 5', subgrupo_produto = 'MESA 5 SUP' where produto = 'N6010018'
update produtos set grupo_produto='INV MESA 4', subgrupo_produto = 'MESA 4 INF' where produto = 'N5020004'
update produtos set grupo_produto='INV MESA 4', subgrupo_produto = 'MESA 4 INF' where produto = 'N5020005'
update produtos set grupo_produto='INV MESA 4', subgrupo_produto = 'MESA 4 INF' where produto = 'N5020003'
update produtos set grupo_produto='INV MESA 4', subgrupo_produto = 'MESA 4 INF' where produto = 'N5020006'
update produtos set grupo_produto='INV MESA 4', subgrupo_produto = 'MESA 4 INF' where produto = 'N5020007'
update produtos set grupo_produto='MESA 5', subgrupo_produto = 'MESA 5 SUP' where produto = 'N6010019'
update produtos set grupo_produto='MESA 5', subgrupo_produto = 'MESA 5 SUP' where produto = 'N6010003'
update produtos set grupo_produto='MESA 5', subgrupo_produto = 'MESA 5 SUP' where produto = 'N6010005'
update produtos set grupo_produto='MESA 5', subgrupo_produto = 'MESA 5 SUP' where produto = 'N6010006'
update produtos set grupo_produto='MESA 5', subgrupo_produto = 'MESA 5 SUP' where produto = 'N6010007'
update produtos set grupo_produto='MESA 5', subgrupo_produto = 'MESA 5 SUP' where produto = 'N6010011'
update produtos set grupo_produto='MESA 5', subgrupo_produto = 'MESA 5 SUP' where produto = 'N6010012'
update produtos set grupo_produto='MESA 5', subgrupo_produto = 'MESA 5 SUP' where produto = 'N6010013'
update produtos set grupo_produto='COMM 5', subgrupo_produto = 'C 5' where produto = 'P7010004'
update produtos set grupo_produto='COMM 5', subgrupo_produto = 'C 5' where produto = 'P7010005'
update produtos set grupo_produto='COMM 5', subgrupo_produto = 'C 5' where produto = 'P7010006'
update produtos set grupo_produto='COMM 5', subgrupo_produto = 'C 5' where produto = 'P7010007'
update produtos set grupo_produto='COMM 5', subgrupo_produto = 'C 5' where produto = 'P7010008'
