SET NOCOUNT ON
DECLARE @TABPROD TABLE (ID INT IDENTITY, PRODUTO VARCHAR(12), FATOR_P INT, PROP_FATOR VARCHAR(5))

INSERT INTO @TABPROD (PRODUTO,FATOR_P,PROP_FATOR)

SELECT P.PRODUTO, 
P.FATOR_P, 
PROP_FATOR = CASE
				WHEN P.FATOR_P < 3 THEN 'P1/P2'
				WHEN P.FATOR_P > 2 THEN 'P3/P4'
				ELSE 'N/A'
			 END
FROM PRODUTOS P
INNER JOIN (
SELECT 	GRIFFE
		,LINHA
		,GRUPO_PRODUTO
		,SUBGRUPO_PRODUTO
FROM CAE_PRODUTOS_FATOR_P 
WHERE ISNULL(UNOUS_NIVEL,'')='FATOR_P' 
GROUP BY GRIFFE,LINHA,GRUPO_PRODUTO,SUBGRUPO_PRODUTO) H 
		ON H.GRIFFE = P.GRIFFE AND H.LINHA = P.LINHA 
			AND H.GRUPO_PRODUTO=P.GRUPO_PRODUTO AND H.SUBGRUPO_PRODUTO=P.SUBGRUPO_PRODUTO
WHERE P.PRODUTO IN (select P.PRODUTO 
					from produtos p
					inner join (select griffe, linha, grupo_produto, subgrupo_produto, max(cp.UNOUS_NIVEL) as UNOUS_NIVEL
					from CAE_PRODUTOS_FATOR_P cp 
					group by griffe, linha, grupo_produto, subgrupo_produto ) as cpp 
					on cpp.GRIFFE=p.GRIFFE and cpp.linha = p.linha 
					and cpp.grupo_produto = p.GRUPO_PRODUTO and cpp.SUBGRUPO_PRODUTO = p.SUBGRUPO_PRODUTO
					inner join prop_produtos pp on pp.PRODUTO=p.PRODUTO and pp.PROPRIEDADE='00107'
					where cpp.UNOUS_NIVEL='FATOR_P' and pp.VALOR_PROPRIEDADE='N/A')
	AND ISNULL(P.FATOR_P,0)>0


DECLARE @I INT, @TOT INT, @INS INT, @UPD INT

SELECT @I=MIN(ID), @TOT = MAX(ID) 
FROM @TABPROD

SET @INS = 0
SET @UPD = 0

DECLARE @PRODUTO VARCHAR(12), @PROP_FATOR VARCHAR(5)

WHILE @I<=@TOT
BEGIN
	SELECT @PRODUTO = PRODUTO, @PROP_FATOR = PROP_FATOR 
	FROM @TABPROD WHERE ID=@I

	IF EXISTS(SELECT 1 FROM PROP_PRODUTOS WHERE PRODUTO = @PRODUTO AND PROPRIEDADE = '00107')
	BEGIN
		UPDATE PROP_PRODUTOS 
		SET VALOR_PROPRIEDADE = @PROP_FATOR
		WHERE PROPRIEDADE = '00107' AND PRODUTO=@PRODUTO

		SET @UPD = @UPD + 1
	END
	ELSE
	BEGIN
		INSERT INTO PROP_PRODUTOS (PROPRIEDADE,PRODUTO,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) 
		VALUES ('00107', @PRODUTO, 1,@PROP_FATOR,GETDATE())

		SET @INS = @INS + 1

	END

	SET @I=@I+1
	/*ATUALIZA ESTATITISCA DE 100 EM 100*/
	IF (@I % 1000) = 0
	BEGIN
		PRINT @I
	END
END
SET NOCOUNT OFF
SELECT 'FORAM INSERIDOS '+CONVERT(varchar,@INS)+' E ATUALIZADOS '+CONVERT(varchar,@UPD)

--SELECT * FROM PROP_PRODUTOS WHERE PROPRIEDADE='00107' and valor_propriedade='N/A'