DECLARE @PEDIDOS TABLE (
PEDIDO VARCHAR(8), ID INT IDENTITY(1,1))

DECLARE @PEDIDO VARCHAR(8)
DECLARE @I INT = 1

INSERT INTO @PEDIDOS (PEDIDO) 
select	c.pedido
/* 
		c.fornecedor, 
		c.filial_a_entregar, 
		c.filial_cobranca, 
		c.filial_a_faturar,
		CAST(C.TOT_QTDE_ORIGINAL AS INT) TOT_QTDE_ORIGINAL,
		CAST(C.TOT_QTDE_ENTREGAR AS INT) TOT_QTDE_ENTREGAR,
		P.ENTREGA, 
		P.LIMITE_ENTREGA
*/
from compras c 
INNER JOIN (SELECT DISTINCT PEDIDO, ENTREGA, LIMITE_ENTREGA 
			FROM COMPRAS_PRODUTO CP ) P 
	ON P.PEDIDO = C.PEDIDO
where c.TOT_QTDE_ENTREGAR>0 
AND c.FILIAL_A_ENTREGAR='CD REGIS'
AND c.pedido not in 
(select pedido from COMPRAS_PROD_CANCELADA)
AND P.LIMITE_ENTREGA > '20190112'
ORDER BY P.LIMITE_ENTREGA ASC

DECLARE @TOT INT
SELECT @TOT = MAX(ID) 
FROM @PEDIDOS

WHILE @I<=@TOT
BEGIN
	
	SELECT @PEDIDO = PEDIDO 
	FROM @PEDIDOS 
	WHERE ID=@I

	UPDATE COMPRAS
	SET FILIAL_A_ENTREGAR = 'CD CAJAMAR', 
		FILIAL_A_FATURAR='CD CAJAMAR', 
		FILIAL_COBRANCA='MATRIZ', 
		RATEIO_FILIAL = '000111'
	WHERE PEDIDO = @PEDIDO

	IF @@ERROR=0
	BEGIN
		PRINT CONVERT(VARCHAR,@I)+' - '+@PEDIDO+' ATUALIZADO COM SUCESSO!'
	END
	ELSE
	BEGIN
		PRINT CONVERT(VARCHAR,@I)+' - '+@PEDIDO+' COM ERRO DE UPDATE'
	END

	SET @I = @I + 1

END
