----update produtos_precos 
----set preco1 = 9.65
----where CODIGO_TAB_PRECO in ('00','02') and 


DECLARE @CUSTO NUMERIC(15,2)
SET @CUSTO=9.65
update compras_produto
set custo1 = @CUSTO, VALOR_ORIGINAL=(QTDE_ORIGINAL*@CUSTO), VALOR_ENTREGAR=(QTDE_ENTREGAR*@CUSTO),VALOR_ENTREGUE=(QTDE_ENTREGUE*@CUSTO)
WHERE PEDIDO='175752'



SELECT * FROM COMPRAS WHERE PEDIDO = '175752'

select * from COMPRAS_PRODUTO
--update compras_produto set
--custo1 = 9.65
--VALOR_ORIGINAL = 
--DECLARE @CUSTO NUMERIC(15,2)
--SET @CUSTO=9.65
--update compras_produto
--set custo1 = @CUSTO, VALOR_ORIGINAL=(QTDE_ORIGINAL*@CUSTO), VALOR_ENTREGAR=(QTDE_ENTREGAR*@CUSTO),VALOR_ENTREGUE=(QTDE_ENTREGUE*@CUSTO)
where 
produto in (
'M2030004'
,'M2030004'
,'M2030006'
,'M2030005'
,'M2030008'
,'M2030007'
,'M2030011'
,'M2030011'
,'M2030011')



UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '175752'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '175753'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '175754'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '176274'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '175755'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '175756'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '175757'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '176275'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '175758'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '175759'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '175760'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '176279'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '175761'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '175762'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '175763'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '176281'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '175764'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '175765'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '175766'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '176278'
UPDATE COMPRAS_PRODUTO set custo1 = 9.65, VALOR_ORIGINAL=(QTDE_ORIGINAL*9.65), VALOR_ENTREGAR=(QTDE_ENTREGAR*9.65),VALOR_ENTREGUE=(QTDE_ENTREGUE*9.65) WHERE PEDIDO = '175776'


UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '175752'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '175753'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '175754'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '176274'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '175755'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '175756'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '175757'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '176275'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '175758'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '175759'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '175760'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '176279'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '175761'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '175762'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '175763'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '176281'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '175764'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '175765'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '175766'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '176278'
UPDATE A SET TOT_VALOR_ORIGINAL = (B.VALOR_ORIGINAL), TOT_VALOR_ENTREGAR = (B.VALOR_ENTREGAR) FROM COMPRAS A INNER JOIN  COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO WHERE A.PEDIDO = '175776'


