
SELECT * 
--UPDATE CLB SET COMPOSICAO_LINX = TAB1.COMPOSICAO, COMPOSICAO_FT = TAB1.COMPOSICAO_FT1
FROM CAEDU_LISTA_COMBO CLB
INNER JOIN 
 (select A.CODIGO,
COMPOSICAO = (SELECT TOP 1 COMPOSICAO 
					FROM MATERIAIS_COMPOSICAO WHERE DESC_COMPOSICAO = A.descricao),
COMPOSICAO_FT1 = (SELECT TOP 1 CODIGO 
					FROM CGP_FICHA_TECNICA_ITENS WHERE DESCRICAO = A.descricao AND CODIGO_FT='0005')
from CAEDU_LISTA_COMBO a 
where id_dominio='005'
) AS TAB1 ON TAB1.CODIGO = CLB.CODIGO

