--declare @tabevento table (descricao varchar(70) null)
--insert into @tabevento values ('ALTO VERÃO')
--insert into @tabevento values ('CAMPANHA CARTÃO CAEDU')
--insert into @tabevento values ('CARNAVAL')
--insert into @tabevento values ('PERMANENTE')
--insert into @tabevento values ('DIA DA MULHER')
--insert into @tabevento values ('DIA DAS CRIANÇAS')
--insert into @tabevento values ('DIA DAS MÃES')
--insert into @tabevento values ('DIA DOS NAMORADOS')
--insert into @tabevento values ('DIA DOS PAIS')
--insert into @tabevento values ('DIA INTERNACIONAL DA MULHER')
--insert into @tabevento values ('ESPECIAL CALÇADOS')
--insert into @tabevento values ('ESPECIAL ESPORTIVO')
--insert into @tabevento values ('ESPECIAL JEANS')
--insert into @tabevento values ('ESPECIAL LINGERIE')
--insert into @tabevento values ('ESPECIAL MODA PRAIA')
--insert into @tabevento values ('ESPECIAL PERSONAGENS')
--insert into @tabevento values ('LANÇAMENTO OUT/INV')
--insert into @tabevento values ('LANÇAMENTO PRIM/VER')
--insert into @tabevento values ('LIQUIDA LEVA TUDO')
--insert into @tabevento values ('NATAL')
--insert into @tabevento values ('PREVIEW OUT/INV')
--insert into @tabevento values ('PREVIEW PRIM/VER')
--insert into @tabevento values ('OUT/INV 23')
--insert into @tabevento values ('OUT/INV 24')
--insert into @tabevento values ('OUT/INV 25')
--insert into @tabevento values ('OUT/INV 26')
--insert into @tabevento values ('OUT/INV 27')
--insert into @tabevento values ('OUT/INV 28')
--insert into @tabevento values ('OUT/INV 29')
--insert into @tabevento values ('OUT/INV 30')
--insert into @tabevento values ('PRI/VER 23/24')
--insert into @tabevento values ('PRI/VER 24/25')
--insert into @tabevento values ('PRI/VER 25/26')
--insert into @tabevento values ('PRI/VER 26/27')
--insert into @tabevento values ('PRI/VER 27/28')
--insert into @tabevento values ('PRI/VER 28/29')
--insert into @tabevento values ('PRI/VER 29/30')


--select * 
--from @tabevento a 
--where descricao not in (select descricao from CAEDU_LISTA_COMBO
--				where id_dominio = '001' )

declare @tabcolecao table (descricao varchar(50) null, codigo varchar(6) NULL)
insert into @tabcolecao values ('OUT/INV 23','OUIN23')
insert into @tabcolecao values ('OUT/INV 24','OUIN24')
insert into @tabcolecao values ('OUT/INV 25','OUIN25')
insert into @tabcolecao values ('OUT/INV 26','OUIN26')
insert into @tabcolecao values ('OUT/INV 27','OUIN27')
insert into @tabcolecao values ('OUT/INV 28','OUIN28')
insert into @tabcolecao values ('OUT/INV 29','OUIN29')
insert into @tabcolecao values ('OUT/INV 30','OUIN30')
insert into @tabcolecao values ('OUT/INV 31','OUIN31')
insert into @tabcolecao values ('OUT/INV 32','OUIN32')
insert into @tabcolecao values ('OUT/INV 33','OUIN33')
insert into @tabcolecao values ('OUT/INV 34','OUIN34')
insert into @tabcolecao values ('PRI/VER  23/24','PV2324')
insert into @tabcolecao values ('PRI/VER  24/25','PV2425')
insert into @tabcolecao values ('PRI/VER  25/26','PV2526')
insert into @tabcolecao values ('PRI/VER  26/27','PV2627')
insert into @tabcolecao values ('PRI/VER  27/28','PV2728')
insert into @tabcolecao values ('PRI/VER  28/29','PV2829')
insert into @tabcolecao values ('PRI/VER  29/30','PV2930')
insert into @tabcolecao values ('PRI/VER  30/31','PV3031')

SELECT * FROM @tabcolecao 
WHERE descricao NOT IN (
SELECT DESC_COLECAO
FROM COLECOES
)
