SELECT  b.local_log
,NOME_CLIFOR
,CLIFOR
,CGC_CPF
,RAZAO_SOCIAL
,PJ_PF
,RG_IE
,CEP
,ENDERECO
,BAIRRO
,CIDADE
,UF
,PAIS
,COBRANCA_ENDERECO
,COBRANCA_CIDADE
,COBRANCA_BAIRRO
,COBRANCA_UF
,COBRANCA_CEP
,ENTREGA_ENDERECO
,ENTREGA_CIDADE
,ENTREGA_UF
,ENTREGA_BAIRRO
,ENTREGA_CEP
,INATIVO
,ENTREGA_PAIS
,COBRANCA_PAIS
,NUMERO
,COMPLEMENTO
,COBRANCA_NUMERO
,COBRANCA_COMPLEMENTO
,ENTREGA_NUMERO
,ENTREGA_COMPLEMENTO
,COD_MUNICIPIO_IBGE
,COD_MUNICIPIO_IBGE_ENTREGA
,COD_MUNICIPIO_IBGE_COBRANCA
FROM CADASTRO_CLI_FOR A  
left join CADCEP b on b.CEP8_LOG = a.CEP
 WHERE (ISNULL(A.COD_MUNICIPIO_IBGE,'') = ''
     OR   ISNULL(A.COD_MUNICIPIO_IBGE_ENTREGA,'') = ''   
     OR   ISNULL(A.COD_MUNICIPIO_IBGE_COBRANCA,'') = '' )
     AND (A.UF <> 'EX')
--and local_log is not null

select * from cadastro_cli_for where isnull(PAIS ,'') = ''


--select * from LCF_LX_MUNICIPIO where DESC_MUNICIPIO like 'seropedica%'


--select * from CADCEP where CEP8_LOG like '%7007391%'  
--70040-912