
/* ---> INCLUSAO DE GRIFFE FEMININO1
INSERT INTO DBO.PRODUTOS_GRIFFES
(GRIFFE,LICENCIADO,ROYALTIES,LICENCIADOR,Data_para_transferencia,
COD_GRIFFE,INATIVO,RECEBIMENTO,VALOR_MINIMO_PEDIDO,RATEIO_CENTRO_CUSTO,
RATEIO_FILIAL,ERP_CUPS_DESCRICAO_IMPORTACAO, COD_ZANTHUS, ID_ZANTHUS)
SELECT 'FEMININO1' GRIFFE,LICENCIADO,ROYALTIES,LICENCIADOR,GETDATE() Data_para_transferencia,
'15' AS COD_GRIFFE,INATIVO,RECEBIMENTO,VALOR_MINIMO_PEDIDO,RATEIO_CENTRO_CUSTO,
RATEIO_FILIAL,'FEMININO1' ERP_CUPS_DESCRICAO_IMPORTACAO, COD_ZANTHUS, ID_ZANTHUS 
FROM DBO.PRODUTOS_GRIFFES WHERE GRIFFE='FEMININO'*/

/* -->  CADASTRO LINHA CASUAL1
insert into PRODUTOS_LINHAS
(LINHA,Data_para_transferencia,COD_LINHA,INATIVO,ERP_CUPS_DESCRICAO_IMPORTACAO)

select 'CASUAL1' LINHA,Data_para_transferencia,'80' COD_LINHA,INATIVO,
	'CASUAL1' ERP_CUPS_DESCRICAO_IMPORTACAO 
from PRODUTOS_LINHAS
where LINHA like 'casual'*/

INSERT INTO dbo.PRODUTOS_GRUPO 
(GRUPO_PRODUTO,CODIGO_GRUPO,Data_para_transferencia,VARIA_TEMPO_TAMANHO,
FECHA_CM_AJUSTE_INFLACAO,INATIVO)

SELECT 'TOP TECIDO1' GRUPO_PRODUTO,'V9' CODIGO_GRUPO,Data_para_transferencia,VARIA_TEMPO_TAMANHO,
FECHA_CM_AJUSTE_INFLACAO,INATIVO 
FROM PRODUTOS_GRUPO WHERE GRUPO_PRODUTO='TOP TECIDO'


INSERT INTO dbo.PRODUTOS_SUBGRUPO
(GRUPO_PRODUTO, SUBGRUPO_PRODUTO, CODIGO_SUBGRUPO, CODIGO_SEQUENCIAL, NUMERO_PARTES_PRODUTO,
PARTES_DO_PRODUTO, PARTES_DO_PRODUTO_COM_DROP, Data_para_transferencia, GIRO_ENTREGA,
OP_POR_COR, OP_QTDE_MAXIMA, OP_QTDE_MINIMA, PERC_COMISSAO, ACEITA_ENCOMENDA, 
DIAS_GARANTIA_LOJA, DIAS_GARANTIA_FABRICANTE, INATIVO, COD_ZANTHUS, ID_ZANTHUS)
select TOP 1
'TOP TECIDO1' GRUPO_PRODUTO, 'M/L1' SUBGRUPO_PRODUTO, '26' CODIGO_SUBGRUPO, 
'0000' CODIGO_SEQUENCIAL, NUMERO_PARTES_PRODUTO,
PARTES_DO_PRODUTO, PARTES_DO_PRODUTO_COM_DROP, Data_para_transferencia, GIRO_ENTREGA,
OP_POR_COR, OP_QTDE_MAXIMA, OP_QTDE_MINIMA, PERC_COMISSAO, ACEITA_ENCOMENDA, 
DIAS_GARANTIA_LOJA, DIAS_GARANTIA_FABRICANTE, INATIVO, COD_ZANTHUS, ID_ZANTHUS
from dbo.PRODUTOS_SUBGRUPO where GRUPO_PRODUTO='TOP TECIDO'
