select * from INFO_LOJAS WHERE loja like '%MOCA%'

select * FROM TABELAS_PRECO WHERE TABELA like '%MOCA%'

INSERT INTO INFO_LOJAS 
VALUES ('192.168.39.10','PRACA DA MOCA','000173','A3','CAEDU','VENDA_PRACA_MOCA',1,NULL,'PRM','SQL_Latin1_General_CP1_CI_AS')

SELECT * FROM FILIAIS WHERE FILIAL = 'PRACA DA MOCA'