CREATE PROCEDURE dbo.CGP_TRANSFERE_VENDA_ATACADO_NAVEGANTES 
@NF_NUMERO VARCHAR(15)
AS 
BEGIN
	SET NOCOUNT ON;


	DECLARE @NF_ENTRADA VARCHAR(15), @NOME_CLIFOR VARCHAR(25), @SERIE_NF_ENTRADA VARCHAR(6)
	DECLARE @FILIAL_ENTRADA VARCHAR(25), @I INT, @TOT INT, @LISTAPROD VARCHAR(MAX)
	DECLARE @CODIGO_BARRA VARCHAR(25), @QTD VARCHAR(6), @TAMANHO INT
	DECLARE @TAB_SKU TABLE (ID INT IDENTITY(1,1), CODIGO_BARRA VARCHAR(25),QTD INT)


	INSERT INTO @TAB_SKU (CODIGO_BARRA, QTD)
	
	SELECT 
		ISNULL(CODIGO_BARRA,'') AS CODIGO_BARRA, QTD
		FROM (
	select produto,COR_PRODUTO,filial,estoque,es1,es2,es3,es4,es5,es6,es7,es8,
			es9,es10, es11, es12, es13, es14, es15, es16    
	from estoque_produtos where estoque <> 0 and  filial = 'VENDA ATACADO SC' AND produto in 
	(	select B.PRODUTO
		from ESTOQUE_PROD_ENT a
		inner join ESTOQUE_PROD1_ENT b on b.ROMANEIO_PRODUTO = a.ROMANEIO_PRODUTO and b.FILIAL = a.FILIAL
		where NF_ENTRADA = @NF_NUMERO and NOME_CLIFOR='KOMPORT' and a.FILIAL='VENDA ATACADO SC'
		GROUP BY B.PRODUTO )

		) as p
		unpivot
		(qtd for POSICAO IN (es1, es2, es3, es4, es5, es6, es7, es8, es9, es10, es11, es12, es13, es14, es15, es16)
		) AS unp
		LEFT JOIN
			PRODUTOS_BARRA b 
				on b.PRODUTO = unp.PRODUTO and b.COR_PRODUTO = unp.COR_PRODUTO and b.TAMANHO = CAST(SUBSTRING(POSICAO,3,2) AS INT) 
		WHERE QTD>0
		ORDER BY unp.PRODUTO, unp.COR_PRODUTO

	--SELECT * FROM @TAB_SKU
	SET @LISTAPROD = ''
	SELECT @I = MIN(ID), @TOT = MAX(ID)
	FROM @TAB_SKU

	WHILE @I <= @TOT
	BEGIN
		SELECT @CODIGO_BARRA = CODIGO_BARRA, @QTD = CONVERT(VARCHAR,QTD)
		FROM @TAB_SKU WHERE ID = @I

		SET	@LISTAPROD = @LISTAPROD + RTRIM(LTRIM(@CODIGO_BARRA)) + ';' + @QTD + '|'

		SET @I = @I + 1
	END

	SET @TAMANHO = LEN(@LISTAPROD)
	IF @TAMANHO > 0
	BEGIN
		SET @LISTAPROD = LEFT(@LISTAPROD, @TAMANHO-1)

		EXEC CGP_MOVIMENTA_ESTOQUE_FILIAIS 
			'VENDA ATACADO SC', 
			'CD NAVEGANTES', 
			@LISTAPROD, 
			@TRANSFERIDO=0
	END

END 

GO

