/* 
* FX_CSM_GERA_KARDEX_CM(?tcFilial,?tcProduto,?tcData1,?tcData2)
* 
*/
SELECT 
	FILIAL,
	PRODUTO,
	COR_PRODUTO,
	ITEM_COMPOSICAO,
	DESC_ITEM_COMPOSICAO,
	CAST(DATA_MOV AS date) DATA_MOV,
	DOC,
	OP_PED_ROMAN,
	SERIE_NF,
	QTDE,
	CUSTO_MEDIO_UNITARIO,
	VALOR_CUSTO,
	COD_CUSTO_MEDIO,
	COD_TRANSACAO,
	TIPO_OPERACAO,
	CHAVE_NFE
FROM FX_CSM_GERA_KARDEX_CM('LOJA VIRTUAL SAO ROQUE','06150203','20251101','20260120')
ORDER BY PRODUTO, DATA_MOV, ITEM_COMPOSICAO, DOC
