update CM_ITEM_COMPOSICAO
set [FATOR_EST_PROPRIO]=0, [FATOR_EST_COM_TERCEIRO]= -1
where ITEM_COMPOSICAO='304';

update CM_ITEM_COMPOSICAO
set [FATOR_EST_PROPRIO]=1 
where ITEM_COMPOSICAO='OENT';

update CM_ITEM_COMPOSICAO
set [COMPOE_CUSTO_MEDIO]=0 
where ITEM_COMPOSICAO='030';
