select GRADE, TAMANHOS_DIGITADOS,
 case when CHARINDEX('.', RTRIM(TAMANHO_1))>0 OR ISNULL(TAMANHO_1,'')='' THEN 0 ELSE 1  END AS T1 
,case when CHARINDEX('.', RTRIM(TAMANHO_2))>0 OR ISNULL(TAMANHO_2,'')='' THEN 0 ELSE 1  END AS T2 
,case when CHARINDEX('.', RTRIM(TAMANHO_3))>0 OR ISNULL(TAMANHO_3,'')='' THEN 0 ELSE 1  END AS T3 
,case when CHARINDEX('.', RTRIM(TAMANHO_4))>0 OR ISNULL(TAMANHO_4,'')='' THEN 0 ELSE 1  END AS T4 
,case when CHARINDEX('.', RTRIM(TAMANHO_5))>0 OR ISNULL(TAMANHO_5,'')='' THEN 0 ELSE 1  END AS T5 
,case when CHARINDEX('.', RTRIM(TAMANHO_6))>0 OR ISNULL(TAMANHO_6,'')='' THEN 0 ELSE 1  END AS T6 
,case when CHARINDEX('.', RTRIM(TAMANHO_7))>0 OR ISNULL(TAMANHO_7,'')='' THEN 0 ELSE 1  END AS T7 
,case when CHARINDEX('.', RTRIM(TAMANHO_8))>0 OR ISNULL(TAMANHO_8,'')='' THEN 0 ELSE 1  END AS T8 
,case when CHARINDEX('.', RTRIM(TAMANHO_9))>0 OR ISNULL(TAMANHO_9,'')='' THEN 0 ELSE 1  END AS T9 
,case when CHARINDEX('.', RTRIM(TAMANHO_10))>0 OR ISNULL(TAMANHO_10,'')='' THEN 0 ELSE 1  END AS T10 
,case when CHARINDEX('.', RTRIM(TAMANHO_11))>0 OR ISNULL(TAMANHO_11,'')='' THEN 0 ELSE 1  END AS T11 
,case when CHARINDEX('.', RTRIM(TAMANHO_12))>0 OR ISNULL(TAMANHO_12,'')='' THEN 0 ELSE 1  END AS T12 
,case when CHARINDEX('.', RTRIM(TAMANHO_13))>0 OR ISNULL(TAMANHO_13,'')='' THEN 0 ELSE 1  END AS T13 
,case when CHARINDEX('.', RTRIM(TAMANHO_14))>0 OR ISNULL(TAMANHO_14,'')='' THEN 0 ELSE 1  END AS T14 
,case when CHARINDEX('.', RTRIM(TAMANHO_15))>0 OR ISNULL(TAMANHO_15,'')='' THEN 0 ELSE 1  END AS T15 
,case when CHARINDEX('.', RTRIM(TAMANHO_16))>0 OR ISNULL(TAMANHO_16,'')='' THEN 0 ELSE 1  END AS T16 
,tamanho_1, tamanho_2, tamanho_3, tamanho_4, tamanho_5, tamanho_6, tamanho_7, tamanho_8, 
tamanho_9, tamanho_10, tamanho_11, tamanho_12, tamanho_13, tamanho_14, tamanho_15, tamanho_16
from PRODUTOS_TAMANHOS 


select E.PRODUTO, COR_PRODUTO, P.GRADE, FILIAL,
ESTOQUE, ES1, ES2, ES3, ES4, ES5, ES6, ES7, ES8, ES9, ES10, ES11, ES12, ES13, ES14, ES15, ES16
from estoque_produtos E
INNER JOIN PRODUTOS P ON P.PRODUTO=E.PRODUTO
where filial='VICENTE DE CARVALHO'
AND ((ES1<>0) OR (ES2<>0) OR (ES3<>0) OR (ES4<>0) OR (ES5<>0) OR (ES6<>0) 
		OR (ES7<>0) OR (ES8<>0) OR (ES9<>0) OR (ES10<>0) OR (ES11<>0) OR (ES12<>0) 
		OR (ES13<>0) OR (ES14<>0) OR (ES15<>0) OR (ES16<>0))
and E.PRODUTO = '47050198'



