select 
EP.ESTOQUE AS [STK VENDA ATACADO BARRA VELHA],
EPB.ESTOQUE AS [STK CD BARRA VELHA], 
A.PEDIDO,  
A.CODIGO_TAB_PRECO,
A.TIPO,
A.CONDICAO_PGTO,
A.FILIAL,
A.CLIENTE_ATACADO,
A.TRANSPORTADORA,
A.MOEDA,
A.EMISSAO,
A.CADASTRAMENTO,
A.TOT_QTDE_ORIGINAL,
A.TOT_QTDE_ENTREGUE,
A.TOT_QTDE_EMBALADA,
A.TOT_QTDE_DEVOLVIDA,
A.TOT_QTDE_ENTREGAR,
A.TOT_VALOR_ORIGINAL,
A.APROVACAO,
A.CONFERIDO,
A.CONFERIDO_POR,
A.TIPO_FRETE,
A.NATUREZA_SAIDA,
A.VALOR_SUB_ITENS,
B.PRODUTO,
B.COR_PRODUTO,
B.ENTREGA,
B.LIMITE_ENTREGA,
B.STATUS_VENDA_ATUAL,
B.QTDE_ORIGINAL,
B.QTDE_EMBALADA,
B.QTDE_ENTREGAR,
B.QTDE_ENTREGUE, 
B.PRECO1,
B.VALOR_ORIGINAL,
B.VO1,B.VO2,B.VO3,B.VO4,B.VO5,B.VO6,B.VO7,B.VO8,B.VO9,B.VO10,
B.VO11,B.VO12,B.VO13,B.VO14,B.VO15,B.VO16,
B.VE1,B.VE2,B.VE3,B.VE4,B.VE5,B.VE6,B.VE7,B.VE8,B.VE9,B.VE10,
B.VE11,B.VE12,B.VE13,B.VE14,B.VE15,B.VE16, B.QTDE_LIQUIDA,
B.VALOR_LIQUIDO
from vendas A

INNER JOIN VENDAS_PRODUTO B 
	ON B.PEDIDO=A.PEDIDO

LEFT JOIN ESTOQUE_PRODUTOS EP
	ON EP.FILIAL=A.FILIAL 
	AND EP.PRODUTO=B.PRODUTO 
	AND EP.COR_PRODUTO=B.COR_PRODUTO

LEFT JOIN ESTOQUE_PRODUTOS EPB
	ON EPB.FILIAL='CD BARRA VELHA' 
	AND EPB.PRODUTO=B.PRODUTO 
	AND EPB.COR_PRODUTO=B.COR_PRODUTO

where A.filial = 'VENDA ATACADO BARRA VELHA'
AND (EP.ESTOQUE IS NOT NULL AND EPB.ESTOQUE IS NOT NULL)
AND B.PRODUTO NOT IN (
SELECT PRODUTO FROM 
FATURAMENTO_PROD FP 
INNER JOIN FATURAMENTO F 
	ON F.NF_SAIDA=FP.NF_SAIDA 
	AND F.FILIAL=FP.FILIAL AND F.SERIE_NF=FP.SERIE_NF
WHERE F.FILIAL='VENDA ATACADO BARRA VELHA'
)
