declare @hierarquias table (
griffe varchar(25), 
linha varchar(25), 
grupo_produto varchar(25),
subgrupo_produto  varchar(25)
)

insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','FEMININO','BOTA','BOTA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','FEMININO','SANDALIA BAIXA','PAPETE')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','FEMININO','SANDALIA BAIXA','RASTEIRA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','FEMININO','SANDALIA SALTO','SANDALIA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','FEMININO','SAPATILHA','SAPATILHA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','FEMININO','SCARPIN','SCARPIN')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','FEMININO','TENIS','TENIS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','INFANTIL NAS','BOTA','BABY')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','INFANTIL NAS','BOTA','KIDS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','INFANTIL NAS','CHINELO','BABY')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','INFANTIL NAS','CHINELO','KIDS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','INFANTIL NAS','SANDALIA','BABY')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','INFANTIL NAS','SANDALIA','KIDS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','INFANTIL NAS','TENIS','BABY')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','INFANTIL NAS','TENIS','KIDS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','INFANTIL NOS','BOTA','BABY')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','INFANTIL NOS','BOTA','KIDS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','INFANTIL NOS','CHINELO','BABY')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','INFANTIL NOS','CHINELO','KIDS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','INFANTIL NOS','SANDALIA','BABY')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','INFANTIL NOS','SANDALIA','KIDS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','INFANTIL NOS','TENIS','BABY')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','INFANTIL NOS','TENIS','KIDS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','MASCULINO','TENIS','TENIS CASUAL')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('CALCADOS','MASCULINO','TENIS','TENIS ESPORTIVO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','BASICO','BOTTOM PROGRAMA','BOTTOM MALHA LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','BASICO','INTEIRO PROGRAMA','INTEIRO MALHA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','BASICO','INVERNO BOTTOM','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','BASICO','INVERNO TOP','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','BASICO','INVERNO TOP PROGRAMA','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','BASICO','INVERNO TOP PROGRAMA','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','BASICO','TOP PROGRAMA','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','BASICO','TOP PROGRAMA','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','BOTTOM','BOTTOM MALHA CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','BOTTOM','BOTTOM MALHA LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','BOTTOM','BOTTOM TECIDO CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','BOTTOM','BOTTOM TECIDO LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','BOTTOM PROGRAMA','BOTTOM MALHA LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','BOTTOM PROGRAMA','BOTTOM TECIDO LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','INTEIRO','INTEIRO MALHA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','INTEIRO','INTEIRO TECIDO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','INTEIRO PROGRAMA','INTEIRO MALHA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','INVERNO BOTTOM','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','INVERNO TOP','TOP MALHA JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','INVERNO TOP','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','INVERNO TOP','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','INVERNO TOP','TOP TECIDO JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','INVERNO TOP','TOP TRICO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','INVERNO TOP PROGRAMA','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','INVERNO TOP PROGRAMA','TOP TRICO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','TOP','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','TOP','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','TOP','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','TOP','TOP TECIDO M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','TOP','TOP TECIDO M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','TOP','TOP TECIDO S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','TOP','TOP TRICO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','TOP PROGRAMA','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','TOP PROGRAMA','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','CONTEMPORANEO','TOP PROGRAMA','TOP TECIDO M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','ESPORTE','BOTTOM','BOTTOM MALHA GINAST CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','ESPORTE','BOTTOM','BOTTOM MALHA LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','ESPORTE','BOTTOM PROGRAMA','BOTTOM MALHA CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','ESPORTE','BOTTOM PROGRAMA','BOTTOM MALHA LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','ESPORTE','BOTTOM PROGRAMA','BOTTOM TECIDO CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','ESPORTE','INVERNO BOTTOM PROGRAMA','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','ESPORTE','INVERNO INTEIRO','INTEIRO MALHA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','ESPORTE','INVERNO TOP','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','ESPORTE','INVERNO TOP PROGRAMA','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','ESPORTE','INVERNO TOP PROGRAMA','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','ESPORTE','TOP','TOP MALHA GINASTICA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','ESPORTE','TOP','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','ESPORTE','TOP','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','ESPORTE','TOP PROGRAMA','TOP MALHA GINASTICA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','ESPORTE','TOP PROGRAMA','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','ESPORTE','TOP PROGRAMA','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','BOTTOM','BOTTOM MALHA CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','BOTTOM','BOTTOM MALHA LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','BOTTOM','BOTTOM TECIDO CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','BOTTOM','BOTTOM TECIDO LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','BOTTOM PROGRAMA','BOTTOM MALHA CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','INTEIRO','INTEIRO MALHA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','INTEIRO','INTEIRO TECIDO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','INTEIRO PROGRAMA','INTEIRO MALHA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','INVERNO BOTTOM PROGRAMA','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','INVERNO TOP','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','INVERNO TOP','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','INVERNO TOP','TOP MOLETOM LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','INVERNO TOP','TOP TECIDO JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','INVERNO TOP','TOP TECIDO M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','INVERNO TOP','TOP TRICO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','INVERNO TOP PROGRAMA','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','INVERNO TOP PROGRAMA','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','INVERNO TOP PROGRAMA','TOP MOLETOM LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','INVERNO TOP PROGRAMA','TOP TRICO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','TOP','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','TOP','TOP MALHA M/C LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','TOP','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','TOP','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','TOP','TOP MALHA S/M LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','TOP','TOP TECIDO M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','TOP','TOP TECIDO M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','TOP','TOP TECIDO S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','TOP','TOP TRICO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','TOP PROGRAMA','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','TOP PROGRAMA','TOP MALHA M/C LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','JOVEM','TOP PROGRAMA','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','BOTTOM','BOTTOM MALHA CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','BOTTOM','BOTTOM MALHA LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','BOTTOM','BOTTOM TECIDO CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','BOTTOM','BOTTOM TECIDO LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','BOTTOM PROGRAMA','BOTTOM MALHA LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','INTEIRO','INTEIRO MALHA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','INTEIRO','INTEIRO TECIDO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','INTEIRO PROGRAMA','INTEIRO MALHA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','INVERNO BOTTOM PROGRAMA','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','INVERNO TOP','TOP MALHA JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','INVERNO TOP','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','INVERNO TOP','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','INVERNO TOP','TOP TECIDO JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','INVERNO TOP','TOP TRICO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','INVERNO TOP PROGRAMA','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','INVERNO TOP PROGRAMA','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','INVERNO TOP PROGRAMA','TOP TRICO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','TOP','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','TOP','TOP MALHA M/C LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','TOP','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','TOP','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','TOP','TOP TECIDO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','TOP','TOP TRICO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','TOP PROGRAMA','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('FEMININO','PLUS','TOP PROGRAMA','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','BOTTOM','BOTTOM MALHA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','BOTTOM PROGRAMA','BOTTOM MALHA LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','INTEIRO','CONJUNTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','INTEIRO','CONJUNTO LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','INTEIRO','INTEIRO BB')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','INTEIRO','VESTIDO/MACAQUINHO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','INTEIRO','VESTIDO/MACAQUINHO LICENC')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','INVERNO BOTTOM','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','INVERNO BOTTOM PROGRAMA','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','INVERNO INTEIRO','CONJUNTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','INVERNO INTEIRO','CONJUNTO LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','INVERNO INTEIRO','INTEIRO BB')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','INVERNO INTEIRO PROGRAMA','CONJUNTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','INVERNO TOP','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','INVERNO TOP','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','INVERNO TOP','TOP MOLETOM LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','INVERNO TOP','TOP TECIDO JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','INVERNO TOP','TOP TRICO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','INVERNO TOP PROGRAMA','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','INVERNO TOP PROGRAMA','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','TOP','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','TOP','TOP MALHA M/C LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NAS','TOP','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','BOTTOM','BOTTOM MALHA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','INTEIRO','CONJUNTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','INTEIRO','CONJUNTO/MACAQ LICENC')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','INTEIRO','INTEIRO BB')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','INVERNO BOTTOM','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','INVERNO BOTTOM PROGRAMA','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','INVERNO INTEIRO','CONJUNTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','INVERNO INTEIRO','CONJUNTO LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','INVERNO INTEIRO','INTEIRO BB')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','INVERNO INTEIRO PROGRAMA','CONJUNTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','INVERNO TOP','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','INVERNO TOP','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','INVERNO TOP','TOP MOLETOM LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','INVERNO TOP','TOP TECIDO JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','INVERNO TOP PROGRAMA','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','INVERNO TOP PROGRAMA','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','TOP','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','TOP','TOP MALHA M/C LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','TOP','TOP MALHA POLO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','TOP','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','1/3 NOS','TOP','TOP TECIDO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NAS','BOTTOM','BOTTOM MALHA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NAS','BOTTOM PROGRAMA','BOTTOM MALHA LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NAS','INTEIRO','CONJ/ VEST/ MACAQ')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NAS','INVERNO BOTTOM','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NAS','INVERNO BOTTOM PROGRAMA','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NAS','INVERNO TOP','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NAS','INVERNO TOP','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NAS','INVERNO TOP','TOP MOLETOM LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NAS','INVERNO TOP','TOP TECIDO JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NAS','INVERNO TOP','TOP TRICO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NAS','INVERNO TOP PROGRAMA','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NAS','INVERNO TOP PROGRAMA','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NAS','TOP','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NAS','TOP','TOP MALHA M/C LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NAS','TOP','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NAS','TOP PROGRAMA','TOP MALHA M/C LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NOS','BOTTOM','BOTTOM MALHA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NOS','INVERNO BOTTOM','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NOS','INVERNO BOTTOM PROGRAMA','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NOS','INVERNO TOP','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NOS','INVERNO TOP','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NOS','INVERNO TOP','TOP MOLETOM LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NOS','INVERNO TOP','TOP TECIDO JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NOS','INVERNO TOP PROGRAMA','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NOS','TOP','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NOS','TOP','TOP MALHA M/C LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NOS','TOP','TOP MALHA POLO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NOS','TOP','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NOS','TOP','TOP TECIDO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','10/16 NOS','TOP PROGRAMA','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','BOTTOM','BOTTOM MALHA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','BOTTOM PROGRAMA','BOTTOM MALHA LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','INTEIRO','CONJUNTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','INTEIRO','CONJUNTO LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','INTEIRO','VESTIDO/MACAQUINHO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','INTEIRO','VESTIDO/MACAQUINHO LICENC')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','INTEIRO PROGRAMA','CONJUNTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','INVERNO BOTTOM','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','INVERNO BOTTOM PROGRAMA','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','INVERNO BOTTOM PROGRAMA','BOTTOM MOLETOM LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','INVERNO INTEIRO','CONJUNTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','INVERNO INTEIRO','CONJUNTO LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','INVERNO INTEIRO PROGRAMA','CONJUNTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','INVERNO TOP','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','INVERNO TOP','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','INVERNO TOP','TOP MOLETOM LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','INVERNO TOP','TOP TECIDO JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','INVERNO TOP','TOP TRICO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','INVERNO TOP PROGRAMA','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','INVERNO TOP PROGRAMA','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','INVERNO TOP PROGRAMA','TOP MOLETOM LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','TOP','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','TOP','TOP MALHA M/C LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','TOP','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NAS','TOP PROGRAMA','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','BOTTOM','BOTTOM MALHA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','INTEIRO','CONJUNTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','INTEIRO','CONJUNTO/MACAQ LICENC')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','INTEIRO PROGRAMA','CONJUNTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','INVERNO BOTTOM','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','INVERNO BOTTOM PROGRAMA','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','INVERNO BOTTOM PROGRAMA','BOTTOM MOLETOM LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','INVERNO INTEIRO','CONJUNTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','INVERNO INTEIRO','CONJUNTO LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','INVERNO INTEIRO PROGRAMA','CONJUNTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','INVERNO TOP','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','INVERNO TOP','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','INVERNO TOP','TOP MOLETOM LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','INVERNO TOP','TOP TECIDO JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','INVERNO TOP PROGRAMA','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','INVERNO TOP PROGRAMA','TOP MALHA M/L LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','INVERNO TOP PROGRAMA','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','INVERNO TOP PROGRAMA','TOP MOLETOM LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','TOP','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','TOP','TOP MALHA M/C LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','TOP','TOP MALHA POLO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','TOP','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','TOP','TOP TECIDO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('INFANTIL','4/8 NOS','TOP PROGRAMA','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','FEMININO','BOTTOM AREA JNS','BOTTOM JEANS CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','FEMININO','BOTTOM AREA JNS','BOTTOM JEANS LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','FEMININO','BOTTOM AREA JNS','BOTTOM JEANS LONGO MARCAS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','FEMININO','BOTTOM COLECAO','BOTTOM JEANS CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','FEMININO','BOTTOM COLECAO','BOTTOM JEANS CURTO PLUS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','FEMININO','BOTTOM COLECAO','BOTTOM JEANS LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','FEMININO','BOTTOM COLECAO','BOTTOM JEANS LONGO PLUS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','FEMININO','BOTTOM PROGRAMA AREA JNS','BOTTOM JEANS CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','FEMININO','BOTTOM PROGRAMA AREA JNS','BOTTOM JEANS LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','FEMININO','BOTTOM PROGRAMA COLECAO','BOTTOM JEANS CURTO PLUS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','FEMININO','BOTTOM PROGRAMA COLECAO','BOTTOM JEANS LONGO PLUS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','FEMININO','INTEIRO AREA JNS','INTEIRO JEANS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','FEMININO','INTEIRO COLECAO','INTEIRO JEANS PLUS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','FEMININO','INVERNO TOP AREA JNS','TOP JEANS JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','FEMININO','INVERNO TOP COLECAO','TOP JEANS JAQUETA PLUS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','FEMININO','TOP AREA JNS','TOP JEANS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NAS','1/3 NAS','BOTTOM JNS CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NAS','1/3 NAS','BOTTOM JNS LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NAS','1/3 NAS','INTEIRO JNS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NAS','1/3 NAS','INVERNO TOP JNS JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NAS','10/16 NAS','BOTTOM JNS CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NAS','10/16 NAS','BOTTOM JNS LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NAS','10/16 NAS','INTEIRO JNS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NAS','10/16 NAS','INVERNO TOP JNS JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NAS','10/16 NAS','TOP JNS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NAS','4/8 NAS','BOTTOM JNS CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NAS','4/8 NAS','BOTTOM JNS LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NAS','4/8 NAS','INTEIRO JNS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NAS','4/8 NAS','INVERNO TOP JNS JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NAS','4/8 NAS','TOP JNS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NOS','1/3 NOS','BOTTOM JNS CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NOS','1/3 NOS','BOTTOM JNS LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NOS','1/3 NOS','INTEIRO JNS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NOS','1/3 NOS','INVERNO TOP JNS JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NOS','10/16 NOS','BOTTOM JNS CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NOS','10/16 NOS','BOTTOM JNS LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NOS','10/16 NOS','BOTTOM PROG JNS LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NOS','10/16 NOS','INVERNO TOP JNS JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NOS','4/8 NOS','BOTTOM JNS CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NOS','4/8 NOS','BOTTOM JNS LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NOS','4/8 NOS','BOTTOM PROG JNS LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NOS','4/8 NOS','INTEIRO JNS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NOS','4/8 NOS','INVERNO TOP JNS JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','INFANTIL NOS','4/8 NOS','TOP JNS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','MASCULINO','BOTTOM AREA JNS','BOTTOM JEANS CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','MASCULINO','BOTTOM AREA JNS','BOTTOM JEANS CURTO MARCAS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','MASCULINO','BOTTOM AREA JNS','BOTTOM JEANS LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','MASCULINO','BOTTOM AREA JNS','BOTTOM JEANS LONGO MARCAS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','MASCULINO','BOTTOM COLECAO','BOTTOM JEANS CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','MASCULINO','BOTTOM COLECAO','BOTTOM JEANS CURTO PLUS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','MASCULINO','BOTTOM COLECAO','BOTTOM JEANS LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','MASCULINO','BOTTOM COLECAO','BOTTOM JEANS LONGO PLUS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','MASCULINO','BOTTOM PROGRAMA AREA JNS','BOTTOM JEANS CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','MASCULINO','BOTTOM PROGRAMA AREA JNS','BOTTOM JEANS LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','MASCULINO','INVERNO TOP AREA JNS','TOP JEANS JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','MASCULINO','TOP AREA JNS','TOP JEANS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('JEANS','MASCULINO','TOP COLECAO','TOP JEANS PLUS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','BASICO','BOTTOM PROGRAMA','BOTTOM MALHA CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','BASICO','INVERNO BOTTOM PROGRAMA','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','BASICO','INVERNO TOP PROGRAMA','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','BASICO','TOP PROGRAMA','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','BASICO','TOP PROGRAMA','TOP MALHA POLO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','CONTEMPORANEO','BOTTOM','BOTTOM TECIDO CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','CONTEMPORANEO','BOTTOM','BOTTOM TECIDO LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','CONTEMPORANEO','INVERNO TOP','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','CONTEMPORANEO','INVERNO TOP','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','CONTEMPORANEO','INVERNO TOP','TOP TECIDO JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','CONTEMPORANEO','INVERNO TOP','TOP TRICO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','CONTEMPORANEO','INVERNO TOP PROGRAMA','TOP TECIDO JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','CONTEMPORANEO','INVERNO TOP PROGRAMA','TOP TRICO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','CONTEMPORANEO','TOP','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','CONTEMPORANEO','TOP','TOP MALHA POLO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','CONTEMPORANEO','TOP','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','CONTEMPORANEO','TOP','TOP TECIDO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','CONTEMPORANEO','TOP PROGRAMA','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','CONTEMPORANEO','TOP PROGRAMA','TOP MALHA POLO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','ESPORTE','BOTTOM','BOTTOM MALHA CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','ESPORTE','BOTTOM','BOTTOM TECIDO CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','ESPORTE','BOTTOM','BOTTOM TECIDO LONGO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','ESPORTE','BOTTOM PROGRAMA','BOTTOM TECIDO CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','ESPORTE','INVERNO BOTTOM','BOTTOM HELANCA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','ESPORTE','INVERNO BOTTOM PROGRAMA','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','ESPORTE','INVERNO TOP','TOP HELANCA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','ESPORTE','INVERNO TOP PROGRAMA','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','ESPORTE','TOP','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','ESPORTE','TOP','TOP MALHA POLO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','ESPORTE','TOP','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','ESPORTE','TOP PROGRAMA','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','ESPORTE','TOP PROGRAMA','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','JOVEM','BOTTOM','BOTTOM MALHA CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','JOVEM','INVERNO BOTTOM','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','JOVEM','INVERNO BOTTOM PROGRAMA','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','JOVEM','INVERNO TOP','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','JOVEM','INVERNO TOP','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','JOVEM','INVERNO TOP','TOP TECIDO JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','JOVEM','INVERNO TOP','TOP TECIDO M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','JOVEM','INVERNO TOP PROGRAMA','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','JOVEM','INVERNO TOP PROGRAMA','TOP MOLETOM LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','JOVEM','TOP','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','JOVEM','TOP','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','JOVEM','TOP','TOP TECIDO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','JOVEM','TOP PROGRAMA','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','JOVEM','TOP PROGRAMA','TOP MALHA M/C LICENCIADO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','JOVEM','TOP PROGRAMA','TOP MALHA M/C MARCAS')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','PLUS','BOTTOM','BOTTOM MALHA CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','PLUS','BOTTOM','BOTTOM TECIDO CURTO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','PLUS','INVERNO BOTTOM PROGRAMA','BOTTOM MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','PLUS','INVERNO TOP','TOP MALHA M/L')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','PLUS','INVERNO TOP','TOP MOLETOM')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','PLUS','INVERNO TOP','TOP TECIDO JAQUETA')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','PLUS','TOP','TOP MALHA M/C')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','PLUS','TOP','TOP MALHA POLO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','PLUS','TOP','TOP MALHA S/M')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','PLUS','TOP','TOP TECIDO')
insert into @hierarquias (griffe, linha, grupo_produto,subgrupo_produto) values ('MASCULINO','PLUS','TOP PROGRAMA','TOP MALHA M/C')

;WITH BASE (griffe, linha, grupo_produto,subgrupo_produto,UNOUS_NIVEL)
AS (
select a.*, max(b.UNOUS_NIVEL) as UNOUS_NIVEL
from @hierarquias a
left join CAE_PRODUTOS_FATOR_P b 
			on b.griffe = a.griffe and  b.linha = a.linha 
				and b.grupo_produto = a.grupo_produto and b.SUBGRUPO_PRODUTO=a.subgrupo_produto
group by a.griffe, a.linha, a.grupo_produto, a.subgrupo_produto)

SELECT a.*, p.PRODUTO, p.DESC_PRODUTO, p.INATIVO, p.DATA_CADASTRAMENTO, pp.VALOR_PROPRIEDADE 
FROM BASE A
INNER JOIN PRODUTOS P 
			ON p.griffe = a.griffe and  p.linha = a.linha 
				and p.grupo_produto = a.grupo_produto and p.SUBGRUPO_PRODUTO=a.subgrupo_produto
INNER JOIN PROP_PRODUTOS pp on pp.PRODUTO = p.PRODUTO and pp.PROPRIEDADE='00105'
where p.INATIVO=0
order by a.griffe, a.linha, a.grupo_produto, a.subgrupo_produto, p.PRODUTO


