select t1.*
from (select *,
SUBSTRING(REPLACE(EMISSAO_FAT_GER,'/','') ,5,4)+
SUBSTRING(REPLACE(EMISSAO_FAT_GER,'/','') ,3,2)+
SUBSTRING(REPLACE(EMISSAO_FAT_GER,'/','') ,1,2) as datachar
from CGP_SYNCHRO4ME_TOTAL_SEM_CFOP SCFOP
WHERE SIS_CODIGO = 'LINX') as t1
where t1.datachar>'20230430' and t1.datachar<'20230601'


select a.pedido,ERP_CUPS_PROCESSO_CCF_CCA, ERP_CUPS_CHEGADA_PORTO, ENTREGA, LIMITE_ENTREGA
from compras a
inner join COMPRAS_PRODUTO b on b.PEDIDO=a.PEDIDO
where a.ERP_CUPS_PROCESSO_CCF_CCA in ('0127/19','0128/19')
