/* CONSULTA TIPO_COMPRA */
SELECT LTRIM(RTRIM(TIPO_COMPRA)) AS TIPO_COMPRA
FROM COMPRAS_TIPOS  (NOLOCK)
WHERE INDICA_COMPRA_PRODUTO=1
ORDER BY 1

/* CONSULTA CLUSTER UNOUS */
SELECT LTRIM(RTRIM(DESCRICAO)) AS CLUSTER_UNOUS
FROM CAEDU_LISTA_COMBO  (NOLOCK)
WHERE ID_DOMINIO='025'
ORDER BY 1

/* CONSULTA MES NAS LOJAS*/
SET LANGUAGE Portuguese;
;WITH MESES AS (
    SELECT 1 AS NUM_MES
    UNION ALL
    SELECT NUM_MES + 1
    FROM MESES
    WHERE NUM_MES < 12
)
SELECT 'NECESSIDAD' AS NOME_MES, 0 AS NUM_MES
UNION
SELECT 
    UPPER(DATENAME(MONTH, DATEADD(MONTH, NUM_MES - 1, 0))) AS NOME_MES,
    NUM_MES
FROM MESES
ORDER BY NUM_MES;

-- OU ASSIM

SELECT NUM_MES, NOME_MES
FROM (VALUES
    ('NECESSIDAD',0),
    ('JANEIRO',1),
    ('FEVEREIRO',2),
    ('MARÇO',3),
    ('ABRIL',4),
    ('MAIO',5),
    ('JUNHO',6),
    ('JULHO',7),
    ('AGOSTO',8),
    ('SETEMBRO',9),
    ('OUTUBRO',10),
    ('NOVEMBRO',11),
    ('DEZEMBRO',12)
) AS MESES(NOME_MES,NUM_MES)
ORDER BY NUM_MES;
