select		F.FILIAL
			,A.CGC_CPF
			,EST.ESTOQUE
			,A.INATIVO
			,CASE 
			WHEN EXISTS (SELECT TOP 1 CODIGO_FILIAL FROM LOJA_VENDA WHERE CODIGO_FILIAL = A.CLIFOR) THEN 'LOJA FISICA'
			ELSE 'OUTROS'
			END AS TIPO,
			CASE 
			WHEN F.FILIAL LIKE 'CD%' THEN CAST(1 AS BIT) 
			WHEN F.FILIAL LIKE '%AMOSTRA%' THEN CAST(1 AS BIT) 
			WHEN F.FILIAL LIKE 'POS INAUGURACAO%' THEN CAST(1 AS BIT) 
			WHEN F.FILIAL LIKE 'CONTROLE DE QUALIDADE%' THEN CAST(1 AS BIT)
			WHEN F.FILIAL LIKE '%CQ%' THEN CAST(1 AS BIT)			
			WHEN F.FILIAL LIKE '%REJEITADO%' THEN CAST(1 AS BIT) 
			ELSE CAST(0 AS BIT) 
			END AS CD
FROM FILIAIS F
INNER JOIN CADASTRO_CLI_FOR A ON A.CLIFOR = F.COD_FILIAL 
LEFT JOIN (SELECT FILIAL,SUM(ESTOQUE) AS ESTOQUE
FROM ESTOQUE_PRODUTOS
GROUP BY FILIAL
) EST
	ON EST.FILIAL = F.FILIAL
WHERE 1=1 AND F.EMPRESA=1
order by 2,1



