select A.PRODUTO,A.COR_PRODUTO,A.FILIAL,
A.ULTIMA_ENTRADA, A.DISPONIVEL, A.ESTOQUE, A.EMBALADO, A.TRANSITO,
A.ES1, A.ES2, A.ES3, A.ES4, A.ES5, A.ES6, A.ES7, A.ES8, A.ES9,
A.ES10, A.ES11, A.ES12, A.ES13, A.ES14, A.ES15, A.ES16,
A.TIPO_PRODUTO, A.DESC_PRODUTO, A.DESC_COR_PRODUTO,
A.GRIFFE, A.LINHA, A.GRUPO_PRODUTO, A.SUBGRUPO_PRODUTO,
A.COLECAO, A.GRADE, A.FABRICANTE, A.REFER_FABRICANTE, A.CUSTO_MEDIO1, A.ULTIMO_CUSTO1, 
A.EMB1, A.EMB2, A.EMB3, A.EMB4, A.EMB5, A.EMB6, A.EMB7, A.EMB8, A.EMB9,
A.EMB10, A.EMB11, A.EMB12, A.EMB13, A.EMB14, A.EMB15, A.EMB16,
A.EN1, A.EN2, A.EN3, A.EN4, A.EN5, A.EN6, A.EN7, A.EN8, A.EN9,
A.EN10, A.EN11, A.EN12, A.EN13, A.EN14, A.EN15, A.EN16,
A.CATEGORIA_PRODUTO, A.SUBCATEGORIA_PRODUTO
from W_ESTOQUE_PRODUTOS_00 A 