--exec sp_executesql N'
--/* lx005102csm  CursorAdapter: cur_v_entradas_00_prod1_ent_compl(Alias: v_entradas_00_prod1_ent_compl)  */

SELECT ENTRADAS.NOME_CLIFOR, ENTRADAS.NF_ENTRADA, ENTRADAS.SERIE_NF_ENTRADA, ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO, 
ESTOQUE_PROD1_ENT.FILIAL, ESTOQUE_PROD1_ENT.ITEM_IMPRESSAO, ESTOQUE_PROD1_ENT.PRODUTO, ESTOQUE_PROD1_ENT.COR_PRODUTO, 
ESTOQUE_PROD1_ENT.TAREFA, ESTOQUE_PROD1_ENT.ORDEM_PRODUCAO, CONVERT(NUMERIC(16, 2), 0) AS CUSTO_MOEDA1, 
CONVERT(NUMERIC(16, 2), 0) AS CUSTO_MOEDA2, CONVERT(NUMERIC(16, 2), 0) AS CUSTO_MOEDA3, CONVERT(NUMERIC(16, 2), 0) AS CUSTO_MOEDA4, 
CONVERT(NUMERIC(16, 2), 0) AS CUSTO_CHEIO1, CONVERT(NUMERIC(16, 2), 0) AS CUSTO_CHEIO2, CONVERT(NUMERIC(16, 2), 0) AS CUSTO_CHEIO3, 
CONVERT(NUMERIC(16, 2), 0) AS CUSTO_CHEIO4, ESTOQUE_PROD1_ENT.SEGUNDA_QUALIDADE, ESTOQUE_PROD1_ENT.DATA_CUSTO, 
ESTOQUE_PROD1_ENT.MATA_SALDO_PEDIDO, ESTOQUE_PROD1_ENT.PEDIDO_VENDA, ESTOQUE_PROD1_ENT.PEDIDO_VENDA_ENTREGA, 
ESTOQUE_PROD1_ENT.PEDIDO_VENDA_ITEM, ESTOQUE_PROD_ENT.PEDIDO, ESTOQUE_PROD_ENT.ENTREGA_PEDIDO, PRODUTOS.CLASSIF_FISCAL, 
PRODUTOS.DESC_PRODUTO, PRODUTOS.DESC_PROD_NF, PRODUTOS.UNIDADE, PRODUTOS.REFER_FABRICANTE, PRODUTOS.GRADE, PRODUTOS.VARIA_CUSTO_COR, 
PRODUTOS.VARIA_CUSTO_TAM, PRODUTOS.VARIA_PRECO_COR, PRODUTOS.VARIA_PRECO_TAM, PRODUTOS.PONTEIRO_PRECO_TAM, PRODUTOS.TRIBUT_ICMS, 
PRODUTOS.TRIBUT_ORIGEM, PRODUTOS.CONTA_CONTABIL, ISNULL(PRODUTOS_INDICADOR_CFOP.INDICADOR_CFOP, 
(CASE WHEN ISNULL(FILIAIS.INDICA_CFOP_SOMENTE_REVENDA, 0) = 1 
AND PRODUTOS.INDICADOR_CFOP = 10 THEN 11 ELSE PRODUTOS.INDICADOR_CFOP END )) AS INDICADOR_CFOP, 
PRODUTO_CORES.DESC_COR_PRODUTO, PRODUTO_CORES.COR_FABRICANTE, CONVERT(VARCHAR(15), NULL) AS RATEIO_CENTRO_CUSTO, 
CONVERT(VARCHAR(40), NULL) AS DESC_RATEIO_CENTRO_CUSTO, CONVERT(VARCHAR(15), '''') AS RATEIO_FILIAL, CONVERT(VARCHAR(40), '''') AS DESC_RATEIO_FILIAL, 
ESTOQUE_PROD1_ENT.COMISSAO, ESTOQUE_PROD1_ENT.COMISSAO_GERENTE, ESTOQUE_PROD1_ENT.COD_REPRESENTANTE, ESTOQUE_PROD1_ENT.COD_REPRESENTANTE_GERENTE, 
ISNULL(COMPRAS.COMPRIMENTO_DE_ROLOS, 0.00) AS COMPRIMENTO_DE_ROLOS, ESTOQUE_PROD1_ENT.VALOR AS VALOR_COMPLEMENTO , 
ENTRADAS.AGRUPAMENTO_ITENS ,ESTOQUE_PROD1_ENT.QTDE,ESTOQUE_PROD1_ENT.EN_1,ESTOQUE_PROD1_ENT.EN_2,ESTOQUE_PROD1_ENT.EN_3,ESTOQUE_PROD1_ENT.EN_4,
ESTOQUE_PROD1_ENT.EN_5,ESTOQUE_PROD1_ENT.EN_6,ESTOQUE_PROD1_ENT.EN_7,ESTOQUE_PROD1_ENT.EN_8,ESTOQUE_PROD1_ENT.EN_9,
ESTOQUE_PROD1_ENT.EN_10,ESTOQUE_PROD1_ENT.EN_11,ESTOQUE_PROD1_ENT.EN_12,ESTOQUE_PROD1_ENT.EN_13,ESTOQUE_PROD1_ENT.EN_14,ESTOQUE_PROD1_ENT.EN_15,
ESTOQUE_PROD1_ENT.EN_16,ESTOQUE_PROD1_ENT.EN_17,ESTOQUE_PROD1_ENT.EN_18,ESTOQUE_PROD1_ENT.EN_19,ESTOQUE_PROD1_ENT.EN_20,
ESTOQUE_PROD1_ENT.EN_21,ESTOQUE_PROD1_ENT.EN_22,ESTOQUE_PROD1_ENT.EN_23,ESTOQUE_PROD1_ENT.EN_24,ESTOQUE_PROD1_ENT.EN_25,
ESTOQUE_PROD1_ENT.EN_26,ESTOQUE_PROD1_ENT.EN_27,ESTOQUE_PROD1_ENT.EN_28,ESTOQUE_PROD1_ENT.EN_29,ESTOQUE_PROD1_ENT.EN_30,
ESTOQUE_PROD1_ENT.EN_31,ESTOQUE_PROD1_ENT.EN_32,ESTOQUE_PROD1_ENT.EN_33,ESTOQUE_PROD1_ENT.EN_34,ESTOQUE_PROD1_ENT.EN_35,
ESTOQUE_PROD1_ENT.EN_36,ESTOQUE_PROD1_ENT.EN_37,ESTOQUE_PROD1_ENT.EN_38,ESTOQUE_PROD1_ENT.EN_39,ESTOQUE_PROD1_ENT.EN_40,
ESTOQUE_PROD1_ENT.EN_41,ESTOQUE_PROD1_ENT.EN_42,ESTOQUE_PROD1_ENT.EN_43,ESTOQUE_PROD1_ENT.EN_44,ESTOQUE_PROD1_ENT.EN_45,
ESTOQUE_PROD1_ENT.EN_46,ESTOQUE_PROD1_ENT.EN_47,ESTOQUE_PROD1_ENT.EN_48, ENTRADAS_ITEM.SUB_ITEM_TAMANHO, PRODUTOS.ID_CEST_NCM, 
TABELA_LX_CEST.DESCRICAO, TABELA_LX_CEST.CODIGO_CEST 
FROM ESTOQUE_PROD1_ENT  
INNER JOIN ESTOQUE_PROD_ENT   
	ON ESTOQUE_PROD1_ENT.FILIAL = ESTOQUE_PROD_ENT.FILIAL   AND ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO  
INNER JOIN ENTRADAS   
	ON ENTRADAS.NOME_CLIFOR = ESTOQUE_PROD_ENT.NOME_CLIFOR AND ENTRADAS.NF_ENTRADA = ESTOQUE_PROD_ENT.NF_ENTRADA  
	AND ENTRADAS.SERIE_NF_ENTRADA = ESTOQUE_PROD_ENT.SERIE_NF_ENTRADA 
INNER JOIN PRODUTOS 
	ON ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
INNER JOIN PRODUTO_CORES  
	ON ESTOQUE_PROD1_ENT.PRODUTO = PRODUTO_CORES.PRODUTO AND ESTOQUE_PROD1_ENT.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO 
INNER JOIN FILIAIS 
	ON FILIAIS.FILIAL = 'CD NAVEGANTES' 
LEFT JOIN PRODUTOS_INDICADOR_CFOP 
		ON ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS_INDICADOR_CFOP.PRODUTO AND PRODUTOS_INDICADOR_CFOP.FILIAL = FILIAIS.FILIAL 
LEFT JOIN COMPRAS 
	ON ESTOQUE_PROD_ENT.PEDIDO = COMPRAS.PEDIDO  
LEFT JOIN ENTRADAS_ITEM  
	ON ENTRADAS.NF_ENTRADA = ENTRADAS_ITEM.NF_ENTRADA AND ENTRADAS.SERIE_NF_ENTRADA = ENTRADAS_ITEM.SERIE_NF_ENTRADA 
		AND ENTRADAS.NOME_CLIFOR = ENTRADAS_ITEM.NOME_CLIFOR AND ENTRADAS_ITEM.ITEM_IMPRESSAO=ESTOQUE_PROD1_ENT.ITEM_IMPRESSAO 
LEFT JOIN CEST_NCM LISTA_CEST_NCM ON PRODUTOS.ID_CEST_NCM = LISTA_CEST_NCM.ID LEFT JOIN TABELA_LX_CEST 
	ON LISTA_CEST_NCM.ID_CEST = TABELA_LX_CEST.ID  
WHERE  
	entradas.empresa = 1 
	and  estoque_prod_ent.nome_clifor = 'KOMPORT'  
	and Entradas.FILIAL = 'CD NAVEGANTES'  
	and Entradas.Nota_Complementar = 0  
	and (Entradas.NF_ENTRADA_PROPRIA = 1 
	and ((Entradas.STATUS_NFE = 3 AND Entradas.tipo_emissao_nfe = '4' and Entradas.log_status_nfe = 0) 									 
	OR (Entradas.STATUS_NFE = 1 AND Entradas.tipo_emissao_nfe = '5' and Entradas.log_status_nfe = 0) 									 
	OR (Entradas.STATUS_NFE IN (5,6))) 	
	or Entradas.NF_ENTRADA_PROPRIA = 0)  
	--and Entradas.SERIE_NF = '3'  
	and entradas.recebimento >= '20170101' 
	and entradas.recebimento <= '20201231'

	--,N'@P1 varchar(13),@P2 int,@P3 varchar(7),@P4 varchar(13),@P5 varchar(1)','CD NAVEGANTES',1,'KOMPORT','CD NAVEGANTES','3'