select NOME_CLIFOR, LEN(NOME_CLIFOR) AS TAMANHO1, LEN(RTRIM(LTRIM(NOME_CLIFOR))) AS TAMANHO2, 
LEN(NOME_CLIFOR) - LEN(REPLACE(NOME_CLIFOR,' ','')) AS ESPACOS,  LEN(NOME_CLIFOR) - LEN(REPLACE(NOME_CLIFOR,CHAR(9),'')) AS TABS 
from cadastro_cli_for 
where NOME_CLIFOR like '%KAPPES%'


/*
FROM TABELA AS B
INNER JOIN TAB A ON REPLACE(A.NOME_CLIFOR,CHAR(9),'') = REPLACE(B.NOME_CLIFOR,CHAR(9),'') */


