select fii.taxa_imposto, fi.*
--update fi set ID_EXCECAO_IMPOSTO='3969'
--update fii set TAXA_IMPOSTO=4, VALOR_IMPOSTO=(BASE_IMPOSTO * 0.04), VALOR_IMPOSTO_CALCULADO=(BASE_IMPOSTO * 0.04)
from FATURAMENTO f
inner join FATURAMENTO_ITEM fi 
on fi.FILIAL=f.FILIAL 
	and fi.NF_SAIDA=f.NF_SAIDA and fi.SERIE_NF=f.SERIE_NF
inner join FATURAMENTO_IMPOSTO fii 
on fii.NF_SAIDA=fi.NF_SAIDA and fii.SERIE_NF=fi.SERIE_NF and fii.FILIAL=fi.FILIAL 
	and fii.ITEM_IMPRESSAO=fi.ITEM_IMPRESSAO and fii.SUB_ITEM_TAMANHO=fi.SUB_ITEM_TAMANHO
and fii.ID_IMPOSTO=1
inner join PRODUTOS p on p.PRODUTO = fi.CODIGO_ITEM
where f.NF_SAIDA in ('000084579','000084576') and f.FILIAL = 'cd cajamar' 
--and fi.ID_EXCECAO_IMPOSTO='3969'
--and p.TRIBUT_ORIGEM=5
AND fii.TAXA_IMPOSTO=0

--NF_SAIDA, SERIE_NF, FILIAL, ITEM_IMPRESSAO, SUB_ITEM_TAMANHO, ID_IMPOSTO
--NF_SAIDA, SERIE_NF, FILIAL, ITEM_IMPRESSAO, SUB_ITEM_TAMANHO