select * from loja_entradas where FILIAL_ORIGEM = 'SANTOS - GONZAGA'
AND ROMANEIO_NF_SAIDA IN ('000004625')
ORDER BY NUMERO_NF_TRANSFERENCIA


select ep.filial, EP.PRODUTO, ep.COR_PRODUTO, ep.DATA_AJUSTE,  le.EMISSAO, le.DATA_SAIDA, le.ROMANEIO_NF_SAIDA, le.FILIAL_ORIGEM
--UPDATE EP SET DATA_AJUSTE = le.EMISSAO
from LOJA_ENTRADAS_PRODUTO LP 
INNER JOIN LOJA_ENTRADAS LE 
		ON LE.FILIAL=LP.FILIAL AND  LE.ROMANEIO_PRODUTO=LP.ROMANEIO_PRODUTO --AND  PRODUTO, COR_PRODUTO
INNER JOIN ESTOQUE_PRODUTOS EP ON EP.PRODUTO = LP.PRODUTO AND EP.COR_PRODUTO=LP.COR_PRODUTO AND EP.FILIAL = LP.FILIAL
 where LE.FILIAL_ORIGEM = 'SANTOS - GONZAGA'
AND LE.ROMANEIO_NF_SAIDA IN ('000004625')
AND ISNULL(EP.DATA_AJUSTE,'') <= '20191002' 

SELECT * FROM CM_DATA_FECHAMENTO  WHERE FILIAL = 'ITAQUERA'

update CM_DATA_FECHAMENTO 
set DATA_SALDO_PA = '20191031'
where filial in('SAO MATHEUS', 'SP - SANTO AMARO', 'SAO BERNARDO')

SELECT * FROM ENTRADAS WHERE NF_ENTRADA = '000000036' AND FILIAL = 'AMOSTRA PIRAJA' AND NOME_CLIFOR = 'CAJAMAR - CQ'

UPDATE ENTRADAS SET 
/*EMISSAO = '20191001', */
SELECT * FROM ENTRADAS
/*SERIE_NF_ENTRADA = '02' */WHERE NF_ENTRADA = '000000036' AND FILIAL = 'AMOSTRA PIRAJA' AND NOME_CLIFOR = 'CAJAMAR - CQ'



SELECT SUM(SALDO_CONTAGEM) FROM ESTOQUE_PROD_CTG_ITENS WHERE NOME_CONTAGEM = 'SUMARÉ 11-11-2019'


select * from produtos_barra where produto = '24020396'

240203960010301          
240203960010301







--select * from loja_entradas where FILIAL_ORIGEM = 'OSASCO - UNIAO'
--AND ROMANEIO_NF_SAIDA IN ('000000004','000000008','000000009','000000010','000000011','000000012',
--							'000000013','000000014','000000015','000000016','000000017','000000019')
--ORDER BY NUMERO_NF_TRANSFERENCIA


--update loja_entradas set emissao = '20190902' where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000004';
--update loja_entradas set emissao = '20190901' where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000008';
--update loja_entradas set emissao = '20190902' where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000009';
--update loja_entradas set emissao = '20190902' where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000010';
--update loja_entradas set emissao = '20190902' where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000011';
--update loja_entradas set emissao = '20190902' where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000012';
--update loja_entradas set emissao = '20190902' where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000013';
--update loja_entradas set emissao = '20190902' where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000014';
--update loja_entradas set emissao = '20190902' where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000015';
--update loja_entradas set emissao = '20190902' where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000016';
--update loja_entradas set emissao = '20190902' where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000017';
--update loja_entradas set emissao = '20190902' where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000019';




--update loja_entradas set ENTRADA_CONFERIDA=1 where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000004';
--update loja_entradas set ENTRADA_CONFERIDA=1 where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000008';
--update loja_entradas set ENTRADA_CONFERIDA=1 where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000009';
--update loja_entradas set ENTRADA_CONFERIDA=1 where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000010';
--update loja_entradas set ENTRADA_CONFERIDA=1 where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000011';
--update loja_entradas set ENTRADA_CONFERIDA=1 where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000012';
--update loja_entradas set ENTRADA_CONFERIDA=1 where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000013';
--update loja_entradas set ENTRADA_CONFERIDA=1 where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000014';
--update loja_entradas set ENTRADA_CONFERIDA=1 where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000015';
--update loja_entradas set ENTRADA_CONFERIDA=1 where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000016';
--update loja_entradas set ENTRADA_CONFERIDA=1 where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000017';
--update loja_entradas set ENTRADA_CONFERIDA=1 where FILIAL_ORIGEM = 'OSASCO - UNIAO' and ROMANEIO_NF_SAIDA = '000000019';

--GO

--select ep.filial, EP.PRODUTO, ep.COR_PRODUTO, ep.DATA_AJUSTE,  le.EMISSAO, le.DATA_SAIDA, le.ROMANEIO_NF_SAIDA, le.FILIAL_ORIGEM
----UPDATE EP SET DATA_AJUSTE = le.EMISSAO
--from LOJA_ENTRADAS_PRODUTO LP 
--INNER JOIN LOJA_ENTRADAS LE 
--		ON LE.FILIAL=LP.FILIAL AND  LE.ROMANEIO_PRODUTO=LP.ROMANEIO_PRODUTO --AND  PRODUTO, COR_PRODUTO
--INNER JOIN ESTOQUE_PRODUTOS EP ON EP.PRODUTO = LP.PRODUTO AND EP.COR_PRODUTO=LP.COR_PRODUTO AND EP.FILIAL = LP.FILIAL
-- where LE.FILIAL_ORIGEM = 'OSASCO - UNIAO'
--AND LE.ROMANEIO_NF_SAIDA IN ('000000004','000000008','000000009','000000010','000000011','000000012',
--							'000000013','000000014','000000015','000000016','000000017','000000019')
--AND ISNULL(EP.DATA_AJUSTE,'') <= '20191002' 

-- select * from CM_DATA_FECHAMENTO where filial in( 'IPIRANGA','CIDADE OCIAN')

--update CM_DATA_FECHAMENTO 
--set DATA_SALDO_PA = '20190831'
--where filial in( 'IPIRANGA','CIDADE OCIAN')

--select * from FATURAMENTO_IMPOSTO where filial = 'OSASCO - UNIAO' 
--AND NF_SAIDA 
--IN ('000000004','000000008','000000009','000000010','000000011','000000012',
--							'000000013','000000014','000000015','000000016','000000017','000000019')
--AND SERIE_NF = '02'

--select * from FATURAMENTO where filial = 'OSASCO - UNIAO' 
--AND NF_SAIDA 
--IN ('000000004','000000008','000000009','000000010','000000011','000000012',
--							'000000013','000000014','000000015','000000016','000000017','000000019')
--AND SERIE_NF = '02'

--select * from ENTRADAS where filial = 'IPIRANGA' 
--AND NF_SAIDA 
--IN ('000000004','000000008','000000009','000000010','000000011','000000012',
--							'000000013','000000014','000000015','000000016','000000017','000000019')
--AND SERIE_NF = '02'

--SELECT ENTRADAS.NF_ENTRADA, ISNULL(DADOS_CADASTRO_XML_NFE.NOME_CLIFOR, ENTRADAS.NOME_CLIFOR) AS NOME_CLIFOR, ENTRADAS.OBS, CADASTRO_CLI_FOR.CLIFOR, 
--ISNULL(DADOS_CADASTRO_XML_NFE.UF, CADASTRO_CLI_FOR.UF) AS UF, CADASTRO_CLI_FOR.CONTA_CONTABIL,       
--ISNULL(DADOS_CADASTRO_XML_NFE.CGC_DESTINATARIO, CADASTRO_CLI_FOR.CGC_CPF) AS CGC_CPF,   CADASTRO_CLI_FOR.POSSUI_RECARGO,
-- CADASTRO_CLI_FOR.PJ_PF, CADASTRO_CLI_FOR.INDICADOR_FISCAL_TERCEIRO,     CTB_LX_INDICADOR_FISCAL_TERCEIRO.DESCRICAO_FISCAL_TERCEIRO,   
-- CADASTRO_CLI_FOR.PAIS,   ISNULL(DADOS_CADASTRO_XML_NFE.RAZAO_SOCIAL, CADASTRO_CLI_FOR.RAZAO_SOCIAL) AS RAZAO_SOCIAL,
--  ISNULL(DADOS_CADASTRO_XML_NFE.RG_IE,   CADASTRO_CLI_FOR.RG_IE) AS RG_IE,   CADASTRO_CLI_FOR.ACEITA_DIAS_FIXO,     
--   ISNULL(DADOS_CADASTRO_XML_NFE.ENDERECO, CADASTRO_CLI_FOR.ENDERECO) AS ENDERECO, ISNULL(DADOS_CADASTRO_XML_NFE.BAIRRO, CADASTRO_CLI_FOR.BAIRRO) AS BAIRRO,  
--    ISNULL(DADOS_CADASTRO_XML_NFE.CEP,   CADASTRO_CLI_FOR.CEP) AS CEP,   ISNULL(DADOS_CADASTRO_XML_NFE.CIDADE, CADASTRO_CLI_FOR.CIDADE) AS CIDADE,   
--	ISNULL(DADOS_CADASTRO_XML_NFE.UF, CADASTRO_CLI_FOR.UF) AS UF, CADASTRO_CLI_FOR.DDI,   CADASTRO_CLI_FOR.DDD1,  
--	 ISNULL(DADOS_CADASTRO_XML_NFE.TELEFONE_DESTINATARIO,   CADASTRO_CLI_FOR.TELEFONE1) AS TELEFONE1, CADASTRO_CLI_FOR.RAMAL1,
--	  CADASTRO_CLI_FOR.DDD2, CADASTRO_CLI_FOR.TELEFONE2,   CADASTRO_CLI_FOR.RAMAL2, CADASTRO_CLI_FOR.DDDFAX,   CADASTRO_CLI_FOR.FAX,   
--	  CADASTRO_CLI_FOR.CONTATO, CADASTRO_CLI_FOR.EMAIL,   ENTRADAS.EMISSAO, ENTRADAS.FILIAL_ENTRADA,   ENTRADAS.FILIAL_COBRANCA, 
--	  ENTRADAS.FILIAL, FILIAIS.CLIFOR, FILIAIS.COD_FILIAL, ENTRADAS.EMPRESA, FILIAIS.ESTOQUE_CTRL_PECA,     CADASTRO_CLI_FOR_A.UF AS FILIAL_UF,   
--	  CADASTRO_CLI_FOR_A.PAIS AS FILIAL_PAIS,   ENTRADAS.AGRUPAMENTO_ITENS, ENTRADAS.FATURA, ENTRADAS.COD_TRANSACAO, ENTRADAS.NATUREZA, NATUREZAS_ENTRADAS.DESC_NATUREZA,  
--	   NATUREZAS_ENTRADAS.CTB_TIPO_OPERACAO,     CTB_LX_TIPO_OPERACAO.DESC_TIPO_OPERACAO, CTB_LX_TIPO_OPERACAO.TIPO_OPERACAO,   NATUREZAS_ENTRADAS.NAO_MOSTRA_VALORES, 
--	   ENTRADAS.CONDICAO_PGTO,   COND_ENT_PGTOS.DESC_COND_PGTO, COND_ENT_PGTOS.TIPO_CONDICAO, ENTRADAS.RECEBIMENTO, ENTRADAS.NF_FATURA,     
--	   ENTRADAS.SERIE_NF_ENTRADA, ENTRADAS.ACERTO_CONTAS_P_R,   ENTRADAS.NF_PROPRIA_EMITIDA,   ENTRADAS.NF_ENTRADA_PROPRIA, ENTRADAS.TABELA_FILHA, 
--	   ENTRADAS.TRANSF_FILIAL, ENTRADAS.LANCAMENTO, ENTRADAS.TIPO_ENTRADAS, ENTRADAS.TRANSPORTADORA_A_PAGAR,     ENTRADAS.NF_ENTRADA_CONHECIMENTO,     
--	   ENTRADAS.NUMERO_CONHECIMENTO_RELACIONADO, ENTRADAS.MOEDA, ENTRADAS.MOEDA_COMPRA, ENTRADAS.IMPORTACAO, ENTRADAS.DATA_DIGITACAO, ENTRADAS.ORIGEM, 
--	   ENTRADAS.CONFERENCIA,   ENTRADAS.EMBALAGENS,       
--	   CAST((ENTRADAS.VALOR_TOTAL * POWER((CASE WHEN ISNULL(CAMBIO_NA_DATA, 0) = 0 THEN 1 ELSE CAMBIO_NA_DATA END),   
--	   ((CASE WHEN DBO.FX_PARAMETRO('CAMBIO_NA_MOEDA_PADRAO') = '.T.' THEN 1 ELSE -1 END) * -1))) AS NUMERIC(14, 2)) AS TOTAL_MOEDA_ENTRADA,         
--	   CAST((VALOR_TOTAL + VALOR_FRETE_TRANSPORTADORA + IMPORTACAO_IMPOSTO + IMPORTACAO_ICMS + IMPORTACAO_IPI + IMPORTACAO_ALFANDEGA + IMPORTACAO_OUTRAS_DESPESAS + 
--	   IMPORTACAO_FRETE + IMPORTACAO_SEGURO + IMPORTACAO_DESEMBARACO) AS NUMERIC(14,         2)) AS TOTAL_GERAL_ENTRADA, CAST(0 AS NUMERIC(8, 2)) AS PORC_TOTAL_GERAL, 
--	   ENTRADAS.CTB_LANCAMENTO, ENTRADAS.CTB_ITEM, ENTRADAS.TIPO_VOLUME, ENTRADAS.RATEIO_FILIAL, CTB_FILIAL_RATEIO.DESC_RATEIO_FILIAL,   ENTRADAS.RATEIO_CENTRO_CUSTO,       
--	   CTB_CENTRO_CUSTO_RATEIO.DESC_RATEIO_CENTRO_CUSTO, ENTRADAS.COMPRIMENTO_DE_ROLOS, ENTRADAS.DATA_FATURAMENTO_RELATIVO, ENTRADAS.UTILIZA_DIAS_FIXOS_FORNECEDOR,   
--	   ENTRADAS.NOME_CLIFOR_TRIANGULAR, ENTRADAS.SERIE_NF, SERIES_NF.DESCRICAO,       ENTRADAS.NUMERO_CONFERENCIA, ENTRADAS.NUMERO_ENTRADA, ENTRADAS.FATURA_NOME_CLIFOR, 
--	   ENTRADAS.FATURA_SERIE,   ENTRADAS.FATURA_NUMERO, ENTRADAS.MARCA_EXPORTACAO, ENTRADAS.ATUALIZACAO_EXPORTAR, ENTRADAS.DATA_EXPORTACAO, ENTRADAS.STATUS_TRANSITO,       
--	   FILIAIS.EMPRESA, ENTRADAS.DIFERENCA_VALOR,   ENTRADAS.FRETE, ENTRADAS.SEGURO, ENTRADAS.DESCONTO, ENTRADAS.ENCARGO, ENTRADAS.QTDE_TOTAL, ENTRADAS.QTDE_TOTAL_AUX, 
--	   ENTRADAS.VALOR_TOTAL, ENTRADAS.DEVOLUCAO,   ENTRADAS.FRETE_A_PAGAR,       ENTRADAS.IMPORTACAO_IMPOSTO, ENTRADAS.IMPORTACAO_ICMS, ENTRADAS.IMPORTACAO_IPI, 
--	   ENTRADAS.IMPORTACAO_ALFANDEGA, ENTRADAS.IMPORTACAO_OUTRAS_DESPESAS,   ENTRADAS.IMPORTACAO_FRETE, ENTRADAS.IMPORTACAO_SEGURO, ENTRADAS.IMPORTACAO_DESEMBARACO,       
--	   ENTRADAS.PESO, ENTRADAS.PESO_BRUTO, ENTRADAS.PORC_DESCONTO, ENTRADAS.PORC_ENCARGO,   ENTRADAS.COMISSAO_VALOR, ENTRADAS.COMISSAO_VALOR_GERENTE, 
--	   ENTRADAS.PORC_DESCONTO_DIGITADO, ENTRADAS.VALOR_IMPOSTO_AGREGAR, ENTRADAS.VALOR_SUB_ITENS,       ENTRADAS.VALOR_FRETE_TRANSPORTADORA,   
--	   ENTRADAS.CAMBIO_NA_DATA, ENTRADAS.ITEM_DIGITADO, CONVERT(BIT, 0) AS SEQUENCIAL_POR_FILIAL, ENTRADAS.FILIAL_SAIDA, ENTRADAS.NF_SAIDA, 
--	   ENTRADAS.SERIE_NF_SAIDA,   CTB_LX_TIPO_OPERACAO.GERA_FINANCEIRO,       NATUREZAS_ENTRADAS.LX_TIPO_LANCAMENTO, 
--	   ISNULL(FILIAIS.MATRIZ_FISCAL, FILIAIS.FILIAL) AS FILIAL_MATRIZ_FISCAL, ISNULL(FILIAIS.MATRIZ, FILIAIS.FILIAL) AS FILIAL_MATRIZ_CONTABIL,  
--	    CADASTRO_CLI_FOR.INDICA_FILIAL, ENTRADAS.ESPECIE_SERIE,       CTB_ESPECIE_SERIE.DESC_ESPECIE_SERIE, ENTRADAS.VALOR_CANCELADO, ENTRADAS.QTDE_CANCELADA, 
--		ENTRADAS.DATA_CANCELAMENTO,   ENTRADAS.NOTA_CANCELADA, ENTRADAS.NOTA_COMPLEMENTAR, FILIAIS_COBRANCA.COD_FILIAL AS COD_FILIAL_COBRANCA,       
--		ENTRADAS.COD_CLIFOR_SACADO, SACADO.NOME_CLIFOR AS NOME_SACADO, ENTRADAS.IMPORTACAO_TX_CAPATAZIA,   ENTRADAS.SEQUENCIAL_UNICO, ENTRADAS.DATA_GERACAO_NSU, 
--		CAST((CASE WHEN ISNULL(ENTRADAS.CODIGO_CLIENTE_VAREJO,       '') = '' THEN 0 ELSE 1 END) AS BIT) AS UTILIZA_CLIENTE_VAREJO, ENTRADAS.CODIGO_CLIENTE_VAREJO,   
--		CLIENTES_VAREJO.CLIENTE_VAREJO, ENTRADAS.PROTOCOLO_AUTORIZACAO_NFE, ENTRADAS.STATUS_NFE, ENTRADAS.CHAVE_NFE, ENTRADAS.LOG_STATUS_NFE,       
--		ENTRADAS.MOTIVO_CANCELAMENTO_NFE, ENTRADAS.PRIORIZACAO,   ENTRADAS.TIPO_EMISSAO_NFE, ENTRADAS.FIN_EMISSAO_NFE, ENTRADAS.DATA_AUTORIZACAO_NFE, 
--		ENTRADAS.REGISTRO_DPEC, ENTRADAS.DATA_REGISTRO_DPEC, ENTRADAS.PROTOCOLO_CANCELAMENTO_NFE,         
--		ENTRADAS.OBS_INTERESSE_FISCO, ENTRADAS.CFOP_CANCELAMENTO, CTB_ESPECIE_SERIE.NUMERO_MODELO_FISCAL, ENTRADAS.DATA_CONTINGENCIA, 
--		ENTRADAS.JUSTIFICATIVA_CONTINGENCIA, CLIENTES_VAREJO.PF_PJ AS CV_PF_PJ,       ISNULL(DADOS_CADASTRO_XML_NFE.CGC_DESTINATARIO,   CLIENTES_VAREJO.CPF_CGC) AS CV_CPF_CGC,
--		 ISNULL(DADOS_CADASTRO_XML_NFE.RG_IE, CLIENTES_VAREJO.RG_IE) AS CV_RG_IE, ISNULL(DADOS_CADASTRO_XML_NFE.ENDERECO, CLIENTES_VAREJO.ENDERECO) AS CV_ENDERECO, 
--		         ISNULL(DADOS_CADASTRO_XML_NFE.NUMERO,   CLIENTES_VAREJO.NUMERO) AS CV_NUMERO, ISNULL(DADOS_CADASTRO_XML_NFE.COMPLEMENTO, 
--				 CLIENTES_VAREJO.COMPLEMENTO) AS CV_COMPLEMENTO,   ISNULL(DADOS_CADASTRO_XML_NFE.BAIRRO,     CLIENTES_VAREJO.BAIRRO) AS CV_BAIRRO, 
--				 ISNULL(DADOS_CADASTRO_XML_NFE.CIDADE,   CLIENTES_VAREJO.CIDADE) AS CV_CIDADE, ISNULL(DADOS_CADASTRO_XML_NFE.UF, CLIENTES_VAREJO.UF) AS CV_UF,      
--				 ISNULL(DADOS_CADASTRO_XML_NFE.TELEFONE_DESTINATARIO,     CLIENTES_VAREJO.TELEFONE) AS CV_TELEFONE, ISNULL(DADOS_CADASTRO_XML_NFE.CEP,   
--				 CLIENTES_VAREJO.CEP) AS CV_CEP,   CLIENTES_VAREJO.PAIS AS CV_PAIS, ENTRADAS.IND_NAT_FRT, ENTRADAS.VEICULO_PLACA, ENTRADAS.MARCA_VOLUMES, 
--				 ENTRADAS.NUMERACAO_VOLUMES,     ENTRADAS.UF_PLACA_VEICULO, ENTRADAS.CALCULO_PIS_COFINS,   ENTRADAS.ENTRADA_XML,   ENTRADAS.CALCULO_ICMS_REDUZIDO, 
--				 ENTRADAS.INDICA_PRESENCA_COMPRADOR, ENTRADAS.DATA_HORA_EMISSAO, ENTRADAS.UTC_EMISSAO, ENTRADAS.UTC_DATA_AUTORIZACAO_NFE,            
--				 SERIES_NF.COD_SERIE_SINTEGRA AS SERIE_OFICIAL,     ENTRADAS.INDICA_ENTRADA_AUTOMATICA,   ENTRADAS.CONSTRUCAO_CIVIL, ENTRADAS.INFO_PGTO, 
--				 INFO_PGTO.DESC_INFO_PGTO, ENTRADAS.CADASTRO_CNO, ENTRADAS.TIPO_REPASSE, ENTRADAS.DESC_REPASSE 
--				 FROM ENTRADAS  
--				 INNER JOIN CADASTRO_CLI_FOR ON ENTRADAS.NOME_CLIFOR = CADASTRO_CLI_FOR.NOME_CLIFOR  
--				 INNER JOIN CADASTRO_CLI_FOR AS SACADO ON ENTRADAS.COD_CLIFOR_SACADO = SACADO.COD_CLIFOR  
--				 INNER   JOIN FILIAIS   ON     ENTRADAS.FILIAL = FILIAIS.FILIAL  
--				 LEFT JOIN CADASTRO_CLI_FOR AS CADASTRO_CLI_FOR_A ON FILIAIS.FILIAL = CADASTRO_CLI_FOR_A.NOME_CLIFOR  
--				 INNER JOIN NATUREZAS_ENTRADAS ON ENTRADAS.NATUREZA = NATUREZAS_ENTRADAS.NATUREZA  
--				 INNER JOIN         CTB_LX_TIPO_OPERACAO ON CTB_LX_TIPO_OPERACAO.CTB_TIPO_OPERACAO = NATUREZAS_ENTRADAS.CTB_TIPO_OPERACAO  
--				 INNER JOIN COND_ENT_PGTOS ON ENTRADAS.CONDICAO_PGTO = COND_ENT_PGTOS.CONDICAO_PGTO  
--				 LEFT JOIN SERIES_NF ON ENTRADAS.SERIE_NF = SERIES_NF.SERIE_NF          
--				 LEFT JOIN CTB_FILIAL_RATEIO ON ENTRADAS.RATEIO_FILIAL = CTB_FILIAL_RATEIO.RATEIO_FILIAL  
--				 LEFT JOIN CTB_CENTRO_CUSTO_RATEIO ON ENTRADAS.RATEIO_CENTRO_CUSTO = CTB_CENTRO_CUSTO_RATEIO.RATEIO_CENTRO_CUSTO  
--				 LEFT JOIN   CTB_LX_INDICADOR_FISCAL_TERCEIRO   
--				 ON     CADASTRO_CLI_FOR.INDICADOR_FISCAL_TERCEIRO = CTB_LX_INDICADOR_FISCAL_TERCEIRO.INDICADOR_FISCAL_TERCEIRO 
--				 LEFT JOIN FILIAIS AS FILIAIS_COBRANCA ON ENTRADAS.FILIAL_COBRANCA = FILIAIS_COBRANCA.FILIAL  
--				 LEFT JOIN   CTB_ESPECIE_SERIE ON       CTB_ESPECIE_SERIE.ESPECIE_SERIE = ENTRADAS.ESPECIE_SERIE  
--				 LEFT JOIN CLIENTES_VAREJO ON ENTRADAS.CODIGO_CLIENTE_VAREJO = CLIENTES_VAREJO.CODIGO_CLIENTE   
--				 LEFT JOIN DADOS_CADASTRO_XML_NFE ON DADOS_CADASTRO_XML_NFE.CHAVE_NFE   = ENTRADAS.CHAVE_NFE  
--				 AND     ENTRADAS.NF_ENTRADA = DADOS_CADASTRO_XML_NFE.NF_ENTRADA AND ENTRADAS.SERIE_NF_ENTRADA =DADOS_CADASTRO_XML_NFE.SERIE_NF_ENTRADA 
--				 AND ENTRADAS.NOME_CLIFOR = DADOS_CADASTRO_XML_NFE.NOME_CLIFOR   LEFT JOIN INFO_PGTO ON INFO_PGTO.ID_INFO_PGTO = ENTRADAS.INFO_PGTO   
--				 WHERE FILIAIS.MATRIZ IN ('MATRIZ')
--AND  ENTRADAS.NF_ENTRADA 
--IN ('000000004','000000008','000000009','000000010','000000011','000000012',
--							'000000013','000000014','000000015','000000016','000000017','000000019')
--AND ENTRADAS.SERIE_NF_ENTRADA = '02' AND ENTRADAS.NOME_CLIFOR = 'OSASCO - UNIAO'


--SELECT * FROM ENTRADAS_IMPOSTO WHERE NF_ENTRADA 
--IN ('000000004','000000008','000000009','000000010','000000011','000000012',
--							'000000013','000000014','000000015','000000016','000000017','000000019')
--AND SERIE_NF_ENTRADA = '02' AND NOME_CLIFOR = 'OSASCO - UNIAO'


--INSERT INTO ENTRADAS_IMPOSTO
--(AGREGA_APOS_DESCONTO,
--AGREGA_APOS_ENCARGO,
--BASE_IMPOSTO,
--ID_IMPOSTO,
--INCIDENCIA,
--ITEM_IMPRESSAO,
--LANCAMENTO_CTB_ITEM,
--NF_ENTRADA,
--NOME_CLIFOR,
--SERIE_NF_ENTRADA,
--SUB_ITEM_TAMANHO,
--TAXA_IMPOSTO,
--VALOR_IMPOSTO,
--BASE_IMPOSTO_CALC,
--CTB_LANCAMENTO_FINANCEIRO,
--CTB_ITEM_FINANCEIRO
--)

--SELECT 
--AGREGA_APOS_DESCONTO,
--AGREGA_APOS_ENCARGO,
--BASE_IMPOSTO,
--ID_IMPOSTO,
--INCIDENCIA,
--ITEM_IMPRESSAO,
--LANCAMENTO_CTB_ITEM,
--NF_SAIDA,
--'OSASCO - UNIAO' AS NOME_CLIFOR,
--'02' AS SERIE_NF_ENTRADA,
--SUB_ITEM_TAMANHO,
--TAXA_IMPOSTO,
--VALOR_IMPOSTO,
--BASE_IMPOSTO_CALC,
--CTB_LANCAMENTO_FINANCEIRO,
--CTB_ITEM_FINANCEIRO
--FROM FATURAMENTO_IMPOSTO
--where filial = 'OSASCO - UNIAO' 
--AND NF_SAIDA 
--IN ('000000004','000000008','000000009','000000010','000000011','000000012',
--							'000000013','000000014','000000015','000000016','000000017','000000019')
--AND SERIE_NF = '02'

UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE FILIAL = 'SAO MATHEUS' AND NF_ENTRADA = '000000008' AND NOME_CLIFOR = 'SP - PENHA'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112'  WHERE FILIAL = 'SAO MATHEUS' AND NF_ENTRADA = '000000009' AND NOME_CLIFOR = 'SP - PENHA'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112'  WHERE FILIAL = 'SAO MATHEUS' AND NF_ENTRADA = '000000010' AND NOME_CLIFOR = 'SP - PENHA'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112'  WHERE FILIAL = 'SAO MATHEUS' AND NF_ENTRADA = '000000011' AND NOME_CLIFOR = 'SP - PENHA'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112'  WHERE FILIAL = 'SAO MATHEUS' AND NF_ENTRADA = '000000012' AND NOME_CLIFOR = 'SP - PENHA'



UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SAO MATHEUS' AND NF_ENTRADA = '000000006' AND NOME_CLIFOR = 'SP - PENHA'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SP - SANTO AMARO' AND NF_ENTRADA = '000000018' AND NOME_CLIFOR = 'CAMPINAS - BANDEIRAS'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SP - SANTO AMARO' AND NF_ENTRADA = '000000019' AND NOME_CLIFOR = 'CAMPINAS - BANDEIRAS'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SP - SANTO AMARO' AND NF_ENTRADA = '000000020' AND NOME_CLIFOR = 'CAMPINAS - BANDEIRAS'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SP - SANTO AMARO' AND NF_ENTRADA = '000000021' AND NOME_CLIFOR = 'CAMPINAS - BANDEIRAS'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SP - SANTO AMARO' AND NF_ENTRADA = '000000022' AND NOME_CLIFOR = 'CAMPINAS - BANDEIRAS'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SP - SANTO AMARO' AND NF_ENTRADA = '000000023' AND NOME_CLIFOR = 'CAMPINAS - BANDEIRAS'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SP - SANTO AMARO' AND NF_ENTRADA = '000000024' AND NOME_CLIFOR = 'CAMPINAS - BANDEIRAS'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SP - SANTO AMARO' AND NF_ENTRADA = '000000025' AND NOME_CLIFOR = 'CAMPINAS - BANDEIRAS'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SP - SANTO AMARO' AND NF_ENTRADA = '000000027' AND NOME_CLIFOR = 'CAMPINAS - BANDEIRAS'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SP - SANTO AMARO' AND NF_ENTRADA = '000027322' AND NOME_CLIFOR = 'PIRASSUNUNGA'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SP - SANTO AMARO' AND NF_ENTRADA = '000027323' AND NOME_CLIFOR = 'PIRASSUNUNGA'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SP - SANTO AMARO' AND NF_ENTRADA = '000027324' AND NOME_CLIFOR = 'PIRASSUNUNGA'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SP - SANTO AMARO' AND NF_ENTRADA = '000027325' AND NOME_CLIFOR = 'PIRASSUNUNGA'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SP - SANTO AMARO' AND NF_ENTRADA = '000027326' AND NOME_CLIFOR = 'PIRASSUNUNGA'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SP - SANTO AMARO' AND NF_ENTRADA = '000027327' AND NOME_CLIFOR = 'PIRASSUNUNGA'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SAO BERNARDO' AND NF_ENTRADA = '000042354' AND NOME_CLIFOR = 'REGISTRO'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SAO BERNARDO' AND NF_ENTRADA = '000042359' AND NOME_CLIFOR = 'REGISTRO'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SAO BERNARDO' AND NF_ENTRADA = '000042360' AND NOME_CLIFOR = 'REGISTRO'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SAO BERNARDO' AND NF_ENTRADA = '000042361' AND NOME_CLIFOR = 'REGISTRO'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SAO BERNARDO' AND NF_ENTRADA = '000042362' AND NOME_CLIFOR = 'REGISTRO'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SAO BERNARDO' AND NF_ENTRADA = '000042363' AND NOME_CLIFOR = 'REGISTRO'
UPDATE ENTRADAS SET RECEBIMENTO = '20191112' WHERE  FILIAL = 'SAO BERNARDO' AND NF_ENTRADA = '000042364' AND NOME_CLIFOR = 'REGISTRO'

