declare @i int = 1
while @i <2
begin
SELECT *
-- UPDATE B SET GERADO=0
FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS B
WHERE B.DISTRIBUICAO = '00011923'
AND CAIXA NOT IN (
SELECT CAIXA from CAEDU_RESERVA_AUTOMATICA_WMS a
where a.DISTRIBUICAO = '00011923')

if @@ROWCOUNT > 0
begin
	UPDATE B SET GERADO=0
	FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS B
	WHERE B.DISTRIBUICAO = '00011923'
	AND CAIXA NOT IN (
	SELECT CAIXA from CAEDU_RESERVA_AUTOMATICA_WMS a
	where a.DISTRIBUICAO = '00011923')


	exec LX_GERA_VENDAS_WMS '00011923'
end
set @i=@i + 1
end

--select * from PDA_WMS_TB_DISTRIBUICAO_COLETA where distribuicao = '00011834'