select * from CSM_TRANSITO_NOTAS where NF_SAIDA = '00060575'


SELECT chave_nfe,* 
--*UPDATE A SET ERP_EBS_AR_DATA_ENVIO=NULL, ERP_EBS_GL_DATA_ENVIO=NULL, ERP_EBS_SYNCHRO_DATA_ENVIO=NULL
FROM FATURAMENTO A WHERE NF_SAIDA = '000060575' AND FILIAL='CD NAVEGANTES'



select * from TABELAS_PRECO order by 1


select b.* 
update b set PRECO=1.00, valor=500.00
FROM FATURAMENTO A 
inner join faturamento_prod b on b.NF_SAIDA=a.NF_SAIDA and b.FILIAL=a.FILIAL
WHERE a.NF_SAIDA = '000060575' AND a.FILIAL='CD NAVEGANTES'

select b.* 
update b set MPADRAO_PRECO_UNITARIO=1, MPADRAO_VALOR_ITEM=500, PRECO_UNITARIO=1, valor_item=500, MPADRAO_VALOR_DESCONTOS=0, MPADRAO_VALOR_ENCARGOS=0,
PRECO_UNITARIO_ORIGINAL=1
FROM FATURAMENTO A 
inner join FATURAMENTO_ITEM b on b.NF_SAIDA=a.NF_SAIDA and b.FILIAL=a.FILIAL
WHERE a.NF_SAIDA in ('000060574','000060575') AND a.FILIAL='CD NAVEGANTES'

update produtos_precos set preco1 = 0.01 where produto = '34016249' and CODIGO_TAB_PRECO='01'


select * from PRODUTOS_PRECOS where produto = '34016249' and CODIGO_TAB_PRECO='01'
select * 
--update a set NF_SAIDA=null
from CSM_TRANSITO_NOTAS a where nf_saida = '000060606'

