select A.* 
--UPDATE V SET TOT_QTDE_ORIGINAL=20, TOT_QTDE_ENTREGAR=20, TOT_VALOR_ORIGINAL=20*4.43, TOT_VALOR_ENTREGAR=20*4.43
--update vp set QTDE_ORIGINAL=20, valor_original = 20 * 4.43, valor_entregar = 20 * 4.43
--update ve set QTDE_EMBALADA=20, VALOR_EMBALADO=20*4.43
--UPDATE A SET QTDE_TOTAL=20
from CAEDU_RESERVA_AUTOMATICA_PACK_WMS a
inner join vendas v on v.pedido = a.VENDA
inner join VENDAS_PRODUTO vp on vp.PEDIDO = a.VENDA and vp.PRODUTO=a.PRODUTO
inner join VENDAS_PROD_EMBALADO ve on ve.caixa = a.CAIXA
where a.DISTRIBUICAO = '00013671'


--SELECT * FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS WHERE DISTRIBUICAO = '00013677'

SELECT * FROM PRODUTOS_PACKS_PERMITIDOS WHERE PRODUTO = 'Z3010092'