create table DBO.CGP_TRANSF_CAIXA_FILIAL (
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
CAIXA VARCHAR(8) NOT NULL,
FILIAL_DE VARCHAR(25) NOT NULL,
FILIAL_PARA VARCHAR(25) NOT NULL,
DATA_INSERT DATETIME NOT NULL DEFAULT GETDATE(),
DATA_ENSEMBLE DATETIME NULL
)
GO

CREATE INDEX IDX_CGP_TRANSF_CAIXA_FILIAL_CAIXA ON DBO.CGP_TRANSF_CAIXA_FILIAL (DATA_ENSEMBLE,CAIXA)
GO

