USE [CAEDU]
GO

/****** Object:  Table [dbo].[PRODUTOS_BARRA]    Script Date: 18/04/2018 17:12:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PRODUTOS_BARRA_APAGADOS](
	[CODIGO_BARRA] [varchar](25) NOT NULL,
	[PRODUTO] [char](12) NOT NULL,
	[COR_PRODUTO] [char](10) NOT NULL,
	[TAMANHO] [int] NULL,
	[GRADE] [varchar](8) NOT NULL,
	[DATA_OCORRENCIA] [datetime] NULL,
	[USUARIO] [varchar](50) NOT NULL,
 CONSTRAINT [XPKPRODUTOS_BARRA_APAGADOS] PRIMARY KEY CLUSTERED 
(
	[CODIGO_BARRA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

