
CREATE TABLE [dbo].[CGP_LOG_DISTRIBUICOES_EXCLUIDAS] (
	[ID] INT IDENTITY(1,1) NOT NULL,
	[ORIGEM] [int] NOT NULL,
	[DISTRIBUICAO] [varchar](12) NOT NULL,
	[TOT_QTDE_LINHAS] [int] NOT NULL,
	[TOT_QTDE_CAIXAS] [int] NOT NULL,
	[DATA] [datetime] NOT NULL,
	[DATA_UNOUS] [datetime] NULL,
	[DATA_EXCLUSAO] [datetime] NOT NULL DEFAULT (GETDATE()),
	CONSTRAINT [PK_CGP_LOG_DISTRIBUICOES_EXCLUIDAS] PRIMARY KEY CLUSTERED (ID)
)
GO

CREATE TABLE [dbo].[CGP_LOG_DISTRIBUICOES_EXCLUIDAS_ITENS](
	[ID] INT NOT NULL,
	[PACK] [char](1) NOT NULL,
	[PRODUTO] [varchar](12) NOT NULL,
	[COR_PRODUTO] [varchar](10)  NULL,
	[FILIAL] [varchar](25) NOT NULL,
	[FILIAL_ORIGEM] [varchar](25) NULL,
	[QTDE_TOTAL] [int] NULL,
	[QTDE_PACK] [int] NULL,
	[CAIXA] [char](8) NOT NULL,
	[VENDA] [varchar](12) NOT NULL,
 CONSTRAINT [FK_CGP_LOG_DISTRIBUICOES_EXCLUIDAS] FOREIGN KEY (ID) 
	REFERENCES CGP_LOG_DISTRIBUICOES_EXCLUIDAS (ID)
)
GO

CREATE INDEX IDX_CGP_LOG_DISTRIBUICOES_EXCLUIDAS_ITENS_1
	ON CGP_LOG_DISTRIBUICOES_EXCLUIDAS_ITENS (PRODUTO, COR_PRODUTO) 
GO

CREATE INDEX IDX_CGP_LOG_DISTRIBUICOES_EXCLUIDAS_ITENS_2
	ON CGP_LOG_DISTRIBUICOES_EXCLUIDAS_ITENS (CAIXA, VENDA) 
GO

CREATE INDEX IDX_CGP_LOG_DISTRIBUICOES_EXCLUIDAS_1
	ON CGP_LOG_DISTRIBUICOES_EXCLUIDAS (ORIGEM,DISTRIBUICAO)
GO

CREATE INDEX IDX_CGP_LOG_DISTRIBUICOES_EXCLUIDAS_2
	ON CGP_LOG_DISTRIBUICOES_EXCLUIDAS (DISTRIBUICAO,ORIGEM)
GO

CREATE INDEX IDX_CGP_LOG_DISTRIBUICOES_EXCLUIDAS_3
	ON CGP_LOG_DISTRIBUICOES_EXCLUIDAS (DATA_EXCLUSAO)
GO

