USE [CAEDU]
GO

/****** Object:  Index [IX_PRODUTOS_GRIFFES_GRIFFE]    Script Date: 9/4/2025 10:34:46 AM ******/
DROP INDEX [IX_PRODUTOS_GRIFFES_GRIFFE] ON [dbo].[PRODUTOS_GRIFFES]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [IX_PRODUTOS_GRIFFES_GRIFFE]    Script Date: 9/4/2025 10:34:47 AM ******/
CREATE NONCLUSTERED INDEX [IX_PRODUTOS_GRIFFES_GRIFFE] ON [dbo].[PRODUTOS_GRIFFES]
(
	[GRIFFE] ASC
)
INCLUDE([COD_GRIFFE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


