CREATE TABLE DBO.CGP_PDA_WMS_STATUS_DISTRIBUICAO (
ID INT IDENTITY(1,1) NOT NULL,
ORIGEM INT NOT NULL,
DISTRIBUICAO VARCHAR(8) NOT NULL,
STATUS_PDA INT NULL,
STATUS_LINX INT NULL,
DATA_RECEBIMENTO DATETIME NULL,
DATA_STATUS_LINX DATETIME NULL,
DATA_PROCESSAMENTO DATETIME NULL,
CONSTRAINT PK_CGP_PDA_WMS_STATUS_DISTRIBUICAO PRIMARY KEY (ID)
)
GO

CREATE INDEX IDX_CGP_PDA_WMS_STATUS_DISTRIBUICAO_1
ON DBO.CGP_PDA_WMS_STATUS_DISTRIBUICAO (ORIGEM,DISTRIBUICAO)
GO

CREATE INDEX IDX_CGP_PDA_WMS_STATUS_DISTRIBUICAO_2
ON DBO.CGP_PDA_WMS_STATUS_DISTRIBUICAO (DISTRIBUICAO,ORIGEM)
GO

