CREATE TABLE DBO.CAEDU_LICENCIADOR 
(COD_LIC CHAR(4) NOT NULL, 
DESC_LIC CHAR(40) NOT NULL, 
INATIVO BIT NOT NULL DEFAULT(0))
GO

ALTER TABLE DBO.CAEDU_LICENCIADOR 
ADD PRIMARY KEY (DESC_LIC)
GO

ALTER TABLE DBO.CAEDU_LICENCIADOR 
ADD UNIQUE (COD_LIC)
GO

