CREATE TABLE DBO.CAEDU_PERSONAGEM 
(COD_PERSONAGEM CHAR(4) NOT NULL, 
DESC_PERSONAGEM CHAR(40) NOT NULL,
DESC_LIC CHAR(40) NOT NULL,
INATIVO BIT NOT NULL DEFAULT(0))
GO

ALTER TABLE DBO.CAEDU_PERSONAGEM 
ADD PRIMARY KEY (DESC_PERSONAGEM)
GO

ALTER TABLE DBO.CAEDU_PERSONAGEM 
ADD UNIQUE (COD_PERSONAGEM)
GO

ALTER TABLE DBO.CAEDU_PERSONAGEM
ADD FOREIGN KEY (DESC_LIC)
REFERENCES DBO.CAEDU_LICENCIADOR(DESC_LIC)
GO

/*

SELECT COD_LIC, DESC_LIC, INATIVO FROM DBO.CAEDU_LICENCIADOR

SELECT COD_PERSONAGEM, DESC_PERSONAGEM, DESC_LIC, INATIVO FROM DBO.CAEDU_PERSONAGEM WHERE DESC_LIC = ?x

CAEDU_PERSONAGEM.COD_PERSONAGEM
*/