USE [CAEDU]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CGP_FATURAMENTO_ITEM_LOG](
	[ID] INT IDENTITY(1,1) NOT NULL,
	[CLASSIF_FISCAL] [char](10) NOT NULL,
	[CODIGO_FISCAL_OPERACAO] [char](4) NOT NULL,
	[CODIGO_ITEM] [varchar](50) NOT NULL,
	[COD_TABELA_FILHA] [char](1) NULL,
	[COMISSAO_ITEM] [numeric](13, 10) NULL,
	[COMISSAO_ITEM_GERENTE] [numeric](13, 10) NULL,
	[CONTA_CONTABIL] [varchar](20) NULL,
	[DESCONTO_ITEM] [numeric](14, 2) NULL,
	[DESCRICAO_ITEM] [varchar](80) NULL,
	[FAIXA] [char](1) NOT NULL,
	[FILIAL] [varchar](25) NOT NULL,
	[ID_EXCECAO_IMPOSTO] [int] NULL,
	[INDICADOR_CFOP] [tinyint] NULL,
	[ITEM_IMPRESSAO] [char](4) NOT NULL,
	[MPADRAO_DESCONTO_ITEM] [numeric](15, 5) NULL,
	[MPADRAO_PRECO_UNITARIO] [numeric](15, 5) NULL,
	[MPADRAO_VALOR_ITEM] [numeric](14, 2) NULL,
	[NF_SAIDA] [char](15) NOT NULL,
	[PESO] [numeric](7, 3) NULL,
	[PORCENTAGEM_ITEM_RATEIO] [numeric](13, 10) NULL,
	[PRECO_UNITARIO] [numeric](15, 5) NULL,
	[QTDE_DEVOLVIDA] [numeric](9, 3) NULL,
	[QTDE_ITEM] [numeric](9, 3) NULL,
	[QTDE_RETORNAR_BENEFICIAMENTO] [numeric](9, 3) NULL,
	[SERIE_NF] [varchar](6) NOT NULL,
	[SUB_ITEM_TAMANHO] [int] NOT NULL,
	[TRIBUT_ICMS] [char](3) NOT NULL,
	[TRIBUT_ORIGEM] [char](3) NOT NULL,
	[UNIDADE] [varchar](5) NULL,
	[VALOR_ITEM] [numeric](14, 2) NULL,
	[REFERENCIA] [varchar](50) NULL,
	[REFERENCIA_ITEM] [varchar](12) NULL,
	[REFERENCIA_PEDIDO] [varchar](12) NULL,
	[TIMESTAMP] [varchar](25) NULL,
	[MPADRAO_VALOR_DESCONTOS] [numeric](14, 2) NULL,
	[MPADRAO_VALOR_ENCARGOS] [numeric](14, 2) NULL,
	[NAO_SOMA_VALOR] [bit] NOT NULL,
	[OBS_ITEM] [varchar](254) NULL,
	[ITEM_NFE] [smallint] NULL,
	[MPADRAO_SEGURO_ITEM] [numeric](14, 2) NULL,
	[MPADRAO_FRETE_ITEM] [numeric](14, 2) NULL,
	[MPADRAO_ENCARGO_ITEM] [numeric](14, 2) NULL,
	[RATEIO_FILIAL] [varchar](15) NULL,
	[RATEIO_CENTRO_CUSTO] [varchar](15) NULL,
	[ORIGEM_ITEM] [char](1) NULL,
	[VALOR_IMPOSTO_ITEM] [numeric](14, 2) NULL,
	[INDICA_PRODUTO_PROCESSO] [bit] NOT NULL,
	[CODIGO_FCI] [char](36) NULL,
	[PRECO_UNITARIO_ORIGINAL] [numeric](15, 5) NOT NULL,
	[WK_DATA_PROCESSADO] [datetime] NULL,
	[CTB_TIPO_OPERACAO] [int] NULL,
	[ID_SUB_PROJETO] [int] NULL,
	[VALOR_IMPOSTO_ITEM_MUNICIPAL] [numeric](9, 2) NOT NULL,
	[VALOR_IMPOSTO_ITEM_ESTADUAL] [numeric](9, 2) NOT NULL,
	[ID_CEST_NCM] [int] NULL,
	[NUMERO_IMOBILIZADO] [varchar](20) NULL,
	[DATA_DELETE] DATETIME NOT NULL DEFAULT (GETDATE())
	CONSTRAINT PK_CGP_FATURAMENTO_ITEM_LOG PRIMARY KEY (ID)
) ON [PRIMARY]
GO

 CREATE INDEX [IDX_CGP_FATURAMENTO_ITEM_LOG] ON  dbo.CGP_FATURAMENTO_ITEM_LOG
(
	[NF_SAIDA] ASC,
	[SERIE_NF] ASC,
	[FILIAL] ASC,
	[ITEM_IMPRESSAO] ASC,
	[SUB_ITEM_TAMANHO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

 CREATE INDEX [IDX_CGP_FATURAMENTO_ITEM_LOG_DATA_DELETE] ON  dbo.CGP_FATURAMENTO_ITEM_LOG
(
	[DATA_DELETE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
