USE [CAEDU]
GO

/****** Object:  Table [dbo].[CAEDU_RESERVA_AUTOMATICA_PACK_WMS]    Script Date: 15/04/2025 09:13:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE INDEX IX02_CAEDU_RESERVA_AUTOMATICA_PACK_WMS
ON [dbo].[CAEDU_RESERVA_AUTOMATICA_PACK_WMS] (CAIXA);