USE [CAEDU]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [DBO].[RELATORIO_ESTOQUE_PROD_CTG_ITENS](
 [REPORT_NUM] [uniqueidentifier] NULL,
 [FILIAL] [varchar](25) NULL,
 [EMISSAO] [datetime] NULL,
 [produto] [char](12) NULL,
 [cor_produto] [char](10) NULL,
 [nome_contagem] [varchar](25) NULL,
 [qtde_contagem] [int] NULL,
 [saldo_contagem] [int] NULL,
 [diferenca_total] [int] NULL,
 [q1] [int] NULL,
 [q2] [int] NULL,
 [q3] [int] NULL,
 [q4] [int] NULL,
 [q5] [int] NULL,
 [q6] [int] NULL,
 [q7] [int] NULL,
 [q8] [int] NULL,
 [q9] [int] NULL,
 [q10] [int] NULL,
 [q11] [int] NULL,
 [q12] [int] NULL,
 [q13] [int] NULL,
 [q14] [int] NULL,
 [q15] [int] NULL,
 [q16] [int] NULL, 
 [q17] [int] NULL, 
 [q18] [int] NULL, 
 [q19] [int] NULL, 
 [q20] [int] NULL, 
 [q21] [int] NULL, 
 [q22] [int] NULL, 
 [q23] [int] NULL, 
 [q24] [int] NULL, 
 [q25] [int] NULL, 
 [q26] [int] NULL, 
 [q27] [int] NULL, 
 [q28] [int] NULL, 
 [q29] [int] NULL, 
 [q30] [int] NULL, 
 [q31] [int] NULL, 
 [q32] [int] NULL, 
 [q33] [int] NULL, 
 [q34] [int] NULL, 
 [q35] [int] NULL, 
 [q36] [int] NULL, 
 [q37] [int] NULL, 
 [q38] [int] NULL, 
 [q39] [int] NULL, 
 [q40] [int] NULL, 
 [q41] [int] NULL, 
 [q42] [int] NULL, 
 [q43] [int] NULL, 
 [q44] [int] NULL, 
 [q45] [int] NULL, 
 [q46] [int] NULL, 
 [q47] [int] NULL, 
 [q48] [int] NULL, 
 [s1] [int] NULL, 
 [s2] [int] NULL, 
 [s3] [int] NULL, 
 [s4] [int] NULL, 
 [s5] [int] NULL, 
 [s6] [int] NULL, 
 [s7] [int] NULL, 
 [s8] [int] NULL, 
 [s9] [int] NULL, 
 [s10] [int] NULL, 
 [s11] [int] NULL, 
 [s12] [int] NULL, 
 [s13] [int] NULL, 
 [s14] [int] NULL, 
 [s15] [int] NULL, 
 [s16] [int] NULL, 
 [s17] [int] NULL, 
 [s18] [int] NULL, 
 [s19] [int] NULL, 
 [s20] [int] NULL, 
 [s21] [int] NULL, 
 [s22] [int] NULL, 
 [s23] [int] NULL, 
 [s24] [int] NULL, 
 [s25] [int] NULL, 
 [s26] [int] NULL, 
 [s27] [int] NULL, 
 [s28] [int] NULL, 
 [s29] [int] NULL, 
 [s30] [int] NULL, 
 [s31] [int] NULL, 
 [s32] [int] NULL, 
 [s33] [int] NULL, 
 [s34] [int] NULL, 
 [s35] [int] NULL, 
 [s36] [int] NULL, 
 [s37] [int] NULL, 
 [s38] [int] NULL, 
 [s39] [int] NULL, 
 [s40] [int] NULL, 
 [s41] [int] NULL, 
 [s42] [int] NULL, 
 [s43] [int] NULL, 
 [s44] [int] NULL, 
 [s45] [int] NULL, 
 [s46] [int] NULL, 
 [s47] [int] NULL, 
 [s48] [int] NULL, 
 [desc_produto] [varchar](40) NULL, 
 [grupo_produto] [varchar](25) NULL, 
 [subgrupo_produto] [varchar](25) NULL, 
 [grade] [varchar](25) NULL, 
 [unidade] [char](5) NULL, 
 [peso] [numeric](14, 8) NULL, 
 [revenda] [bit] NULL, 
 [desc_cor_produto] [varchar](40) NULL, 
 [cor_sortida] [bit] NULL, 
 [cor_fabricante] [char](8) NULL, 
 [refer_fabricante] [varchar](25) NULL, 
 [d1] [int] NULL, 
 [d2] [int] NULL, 
 [d3] [int] NULL, 
 [d4] [int] NULL, 
 [d5] [int] NULL, 
 [d6] [int] NULL, 
 [d7] [int] NULL, 
 [d8] [int] NULL, 
 [d9] [int] NULL, 
 [d10] [int] NULL, 
 [d11] [int] NULL, 
 [d12] [int] NULL, 
 [d13] [int] NULL, 
 [d14] [int] NULL, 
 [d15] [int] NULL, 
 [d16] [int] NULL, 
 [d17] [int] NULL, 
 [d18] [int] NULL, 
 [d19] [int] NULL, 
 [d20] [int] NULL, 
 [d21] [int] NULL, 
 [d22] [int] NULL, 
 [d23] [int] NULL, 
 [d24] [int] NULL, 
 [d25] [int] NULL, 
 [d26] [int] NULL, 
 [d27] [int] NULL, 
 [d28] [int] NULL, 
 [d29] [int] NULL, 
 [d30] [int] NULL, 
 [d31] [int] NULL, 
 [d32] [int] NULL, 
 [d33] [int] NULL, 
 [d34] [int] NULL, 
 [d35] [int] NULL, 
 [d36] [int] NULL, 
 [d37] [int] NULL, 
 [d38] [int] NULL, 
 [d39] [int] NULL, 
 [d40] [int] NULL, 
 [d41] [int] NULL, 
 [d42] [int] NULL, 
 [d43] [int] NULL, 
 [d44] [int] NULL, 
 [d45] [int] NULL, 
 [d46] [int] NULL, 
 [d47] [int] NULL, 
 [d48] [int] NULL, 
 [ponteiro_preco_tam] [char](48) NULL, 
 [varia_preco_cor] [bit] NULL, 
 [varia_preco_tam] [bit] NULL, 
 [custo_reposicao1] [numeric](14, 2) NULL, 
 [custo_reposicao2] [numeric](14, 2) NULL, 
 [custo_reposicao3] [numeric](14, 2) NULL, 
 [custo_reposicao4] [numeric](14, 2) NULL, 
 [custo_medio1] [numeric](15, 5) NULL, 
 [custo_medio2] [numeric](15, 5) NULL, 
 [custo_medio3] [numeric](15, 5) NULL, 
 [custo_medio4] [numeric](15, 5) NULL, 
 [custo4_a_valorizar] [numeric](14, 2) NULL, 
 [custo3_a_valorizar] [numeric](14, 2) NULL, 
 [custo2_a_valorizar] [numeric](14, 2) NULL, 
 [custo1_a_valorizar] [numeric](14, 2) NULL, 
 [valor_contagem_diferenca] [numeric](14, 2) NULL, 
 [linha] [varchar](25) NULL, 
 [griffe] [varchar](25) NULL, 
 [erp_justificativa] [varchar](40) NULL)

GO

SET ANSI_PADDING OFF
GO

/* CRIA CAMPO COM FORMATO DE DATA AAAAMMDD */
alter table RELATORIO_ESTOQUE_PROD_CTG_ITENS
add EMISSAO2 AS CONVERT(VARCHAR,EMISSAO,112)
GO

