USE [CAEDU]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CAEDU_CANAL_VENDAS](
	[COD_CANAL] [char](3) NOT NULL,
	[DESC_CANAL] [varchar](40) NOT NULL,
	[OBS_CANAL] [varchar](250) NULL,
PRIMARY KEY CLUSTERED 
(
	[COD_CANAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


