select * from LOJAS_VAREJO where filial = 'CONTROLE DE QUALIDADE'

select * from LOJAS_VAREJO where filial = 'BARRA VELHA - CQ'


INSERT INTO LOJAS_VAREJO
(CODIGO_FILIAL, FILIAL, SEQUENCIA_TIKET, GERENTE_PERIODO, BENEFICIARIO_CHQ, 
CIDADE_CHQ, SENHA_DESISTENCIA_VENDA, NAO_ENVIA_ESTOQUE, SEQUENCIA_RESERVA, 
SEQUENCIA_SAIDAS, SEQUENCIA_ENTRADAS, SEQUENCIA_CLIENTES, NAO_GERA_GIRO, 
USA_CPF_RG_OU_CODIGO, DATA_PARA_TRANSFERENCIA, PERMANENCIA_TROCO, MOSTRA_FOTOS, 
TIRA_FOTO, VALIDA_PRODUTO, ABRE_VENDA_VENDEDOR, PEDE_SENHA_VEND, 
CPF_OBRIGATORIO, IMPRIME_ITEM_LANCADO, ACUMULA_ITEM_VENDA, SUSP_VENDA, 
TROCA_VOLTA_VENDA, LISTA_TIPO_PGTO_TICKET, SENHA_DESCONTO, DESC_CENTAVOS, 
FIXA_DESCONTO, PARCELAS_MESMO_DIA, ENT_SAI_CBAR, OBRIGA_TITULO, RODIZIO_FOTOS, 
DATAS_RESUMOS, DATAS_VENDEDORES, DESTACA_TROCA, DESCONTA_TROCA, MOSTRA_TICKET, 
SEQUENCIA_TICKET, PERG_IMP_ROMANEIOS, MOSTRA_NO_TICKET, 
IMPRIME_TICKETS_SUSPENSOS, PERG_IMP_TICKETS, MASCARA_CODIGO, JANELA_TROCO, 
PREVISAO_RETORNO, ALTERA_NA_LOJA, PARAMETRO_POR_LOJA, NOME_GERENTE_LOJA, 
COD_GERENTE_LOJA, COD_GERENTE_PERIODO, NOME_GERENTE_PERIODO, OCULTAR_FAIXA_PGTO, 
SENHA_TECNICA, CONTROLA_BAIXAS, USA_TICKET, SALDO_INICIAL, 
ACEITA_MAIS_PERIODOS, IMP_NOTA_CUPOM, PERG_PERMITE_EST, DESC_CENTAVOS_VEND, 
MOSTRA_EST, ENT_NUMTICKET, SENHA_VENDA, COMANDO_EXCLUSAO, 
MOVIMENTA_CAIXA_FECHADO, DESC_PGTO_AVISTA, LANCA_ACRES, TICKET_AGRUPADO, 
VALIDA_CHEQUE, PERG_FUNCIONARIO, PERMITE_ENT_FORNEC, FUNC_POR_FORA, 
LIMITE_PGTO_CHQ, LANCAMENTO_PADRAO, PERMITE_FUNC, NAO_IMP_PROD_TRANSITO, 
ENTRADA_TRANSITO, SUGERE_ADM, SUGERE_ADM_DESABILITA, ALIQUOTA_IMP_FISCAL, 
HAB_DESC_TROCA, JOGA_PARA_SEGUNDA, AUTOMATICA, LANCAMENTO_PADRAO_IMPOSTOS, 
LANCAMENTO_PADRAO_IMPOSTO, LX_STATUS_LOJA, SEQUENCIA_PRE_VENDA, SEQUENCIA_DAV, 
SEQUENCIA_FATURA, SEQUENCIA_RECIBO, SEQUENCIA_PEDIDO, SEQUENCIA_VENDA_SAT, 
LANCAMENTO_PADRAO_CANCELAMENTO_B2C, LANCAMENTO_PADRAO_DEVOL_DINHEIRO, 
LANCAMENTO_PADRAO_ESTORNO_CARTAO)

SELECT 
'000110' AS CODIGO_FILIAL, 'BARRA VELHA - CQ' AS FILIAL, SEQUENCIA_TIKET, GERENTE_PERIODO, BENEFICIARIO_CHQ, 
CIDADE_CHQ, SENHA_DESISTENCIA_VENDA, NAO_ENVIA_ESTOQUE, SEQUENCIA_RESERVA, 
SEQUENCIA_SAIDAS, SEQUENCIA_ENTRADAS, SEQUENCIA_CLIENTES, NAO_GERA_GIRO, 
USA_CPF_RG_OU_CODIGO, DATA_PARA_TRANSFERENCIA, PERMANENCIA_TROCO, MOSTRA_FOTOS, 
TIRA_FOTO, VALIDA_PRODUTO, ABRE_VENDA_VENDEDOR, PEDE_SENHA_VEND, 
CPF_OBRIGATORIO, IMPRIME_ITEM_LANCADO, ACUMULA_ITEM_VENDA, SUSP_VENDA, 
TROCA_VOLTA_VENDA, LISTA_TIPO_PGTO_TICKET, SENHA_DESCONTO, DESC_CENTAVOS, 
FIXA_DESCONTO, PARCELAS_MESMO_DIA, ENT_SAI_CBAR, OBRIGA_TITULO, RODIZIO_FOTOS, 
DATAS_RESUMOS, DATAS_VENDEDORES, DESTACA_TROCA, DESCONTA_TROCA, MOSTRA_TICKET, 
SEQUENCIA_TICKET, PERG_IMP_ROMANEIOS, MOSTRA_NO_TICKET, 
IMPRIME_TICKETS_SUSPENSOS, PERG_IMP_TICKETS, MASCARA_CODIGO, JANELA_TROCO, 
PREVISAO_RETORNO, ALTERA_NA_LOJA, PARAMETRO_POR_LOJA, NOME_GERENTE_LOJA, 
COD_GERENTE_LOJA, COD_GERENTE_PERIODO, NOME_GERENTE_PERIODO, OCULTAR_FAIXA_PGTO, 
SENHA_TECNICA, CONTROLA_BAIXAS, USA_TICKET, SALDO_INICIAL, 
ACEITA_MAIS_PERIODOS, IMP_NOTA_CUPOM, PERG_PERMITE_EST, DESC_CENTAVOS_VEND, 
MOSTRA_EST, ENT_NUMTICKET, SENHA_VENDA, COMANDO_EXCLUSAO, 
MOVIMENTA_CAIXA_FECHADO, DESC_PGTO_AVISTA, LANCA_ACRES, TICKET_AGRUPADO, 
VALIDA_CHEQUE, PERG_FUNCIONARIO, PERMITE_ENT_FORNEC, FUNC_POR_FORA, 
LIMITE_PGTO_CHQ, LANCAMENTO_PADRAO, PERMITE_FUNC, NAO_IMP_PROD_TRANSITO, 
ENTRADA_TRANSITO, SUGERE_ADM, SUGERE_ADM_DESABILITA, ALIQUOTA_IMP_FISCAL, 
HAB_DESC_TROCA, JOGA_PARA_SEGUNDA, AUTOMATICA, LANCAMENTO_PADRAO_IMPOSTOS, 
LANCAMENTO_PADRAO_IMPOSTO, LX_STATUS_LOJA, SEQUENCIA_PRE_VENDA, SEQUENCIA_DAV, 
SEQUENCIA_FATURA, SEQUENCIA_RECIBO, SEQUENCIA_PEDIDO, SEQUENCIA_VENDA_SAT, 
LANCAMENTO_PADRAO_CANCELAMENTO_B2C, LANCAMENTO_PADRAO_DEVOL_DINHEIRO, 
LANCAMENTO_PADRAO_ESTORNO_CARTAO
FROM LOJAS_VAREJO
WHERE filial = 'CONTROLE DE QUALIDADE'

