SELECT * FROM SYSOBJECTS WHERE NAME LIKE 'PDA_WMS%' AND TYPE='V'

SELECT * FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS WHERE DISTRIBUICAO = '00002300'
SELECT * FROM PDA_WMS_TB_DISTRIBUICAO WHERE DISTRIBUICAO = '00002300'

SELECT * FROM PDA_WMS_TB_RESERVA_DISTRIBUICAO WHERE DISTRIBUICAO = '00002300'

SELECT * FROM PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE WHERE PRODUTO = '62010264'