SELECT A.NOME_CLIFOR, A.NF_ENTRADA, A.FILIAL, A.NATUREZA, A.CONDICAO_PGTO, 
A.SERIE_NF_ENTRADA, A.SERIE_NF_ENTRADA, A.RECEBIMENTO, A.EMISSAO,  A.FRETE, A.SEGURO, A.ENCARGO, A.DESCONTO, A.NF_PROPRIA_EMITIDA, A.DATA_DIGITACAO,
A.IPI_VALOR, A.ICMS_BASE, A.ICMS_VALOR, A.QTDE_TOTAL, A.VALOR_TOTAL, A.CTB_ITEM, A.CTB_LANCAMENTO, A.ICMS_ISENTO, A.ICMS_OUTROS, A.PORC_DESCONTO,
A.RATEIO_CENTRO_CUSTO, A.RATEIO_FILIAL, A.VALOR_IMPOSTO_AGREGAR, A.VALOR_SUB_ITENS, A.COD_CLIFOR_SACADO, A.CHAVE_NFE, A.DATA_AUTORIZACAO_NFE, A.INFORMACAO_COMPLEMENTAR, 
A.ERP_EBS_AP_DATA_ENVIO, A.ERP_EBS_GL_DATA_ENVIO, A.ERP_EBS_SYNCHRO_DATA_ENVIO
FROM ENTRADAS A
INNER JOIN CSM_TRANSITO_NOTAS B 
	ON B.FILIAL_ENTRADA=A.FILIAL AND B.NOME_CLIFOR=A.NOME_CLIFOR AND B.NF_ENTRADA=A.NF_ENTRADA AND B.SERIE_NF_ENTRADA=A.SERIE_NF_ENTRADA
ORDER BY B.DATA DESC


SELECT A.FILIAL,A.NF_SAIDA,A.SERIE_NF,A.NOME_CLIFOR,A.CONDICAO_PGTO,A.NATUREZA_SAIDA,A.TRANSPORTADORA,A.TRANSP_REDESPACHO,
A.TIPO_FRETE, A.EMISSAO,A.DATA_SAIDA,A.FRETE, A.SEGURO, A.DESCONTO, A.ENCARGO, A.ICMS,A.VALOR_TOTAL,a.QTDE_TOTAL,
a.PESO_BRUTO,a.PESO_LIQUIDO,a.VOLUMES, a.TIPO_VOLUME, a.ICMS_BASE, a.CTB_ITEM, a.CTB_LANCAMENTO, a.ICMS_ISENTO, a.ICMS_OUTROS,
a.RATEIO_CENTRO_CUSTO, a.RATEIO_FILIAL, a.VALOR_IMPOSTO_AGREGAR, a.VALOR_SUB_ITENS, a.PROTOCOLO_AUTORIZACAO_NFE, a.CHAVE_NFE,
a.DATA_AUTORIZACAO_NFE, a.STATUS_NFE, a.LOG_STATUS_NFE, a.REGISTRO_DPEC, a.DATA_REGISTRO_DPEC, a.VEICULO_PLACA, a.UF_PLACA_VEICULO,
a.DATA_HORA_EMISSAO, a.INDICA_PRESENCA_COMPRADOR, a.UTC_DATA_SAIDA, a.UTC_EMISSAO, a.ERP_EBS_AR_DATA_ENVIO, a.ERP_EBS_GL_DATA_ENVIO,
a.ERP_EBS_SYNCHRO_DATA_ENVIO, a.INFO_PGTO 
FROM FATURAMENTO A
INNER JOIN CSM_TRANSITO_NOTAS B 
	ON B.FILIAL=A.FILIAL AND B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF
ORDER BY B.DATA DESC

/* saidas com imposto */

select	A.NOME_CLIFOR,A.NF_ENTRADA,A.SERIE_NF_ENTRADA, A.FILIAL_ENTRADA,  
		F.NF_SAIDA, F.SERIE_NF, F.FILIAL, f.NOME_CLIFOR as FILIAL_DESTINO, F.EMISSAO,
		F.VALOR_TOTAL, F.VALOR_IMPOSTO_AGREGAR AS FAT_VALOR_IMPOSTO_AGREGAR,
		FIT.CODIGO_ITEM, FIT.CLASSIF_FISCAL, FIT.ITEM_IMPRESSAO, FIT.SUB_ITEM_TAMANHO,
		FIT.CODIGO_FISCAL_OPERACAO, FIT.ID_EXCECAO_IMPOSTO, FIT.DESCRICAO_ITEM, 
		FIT.INDICADOR_CFOP, FIT.PRECO_UNITARIO, FIT.PRECO_UNITARIO_ORIGINAL, FIT.QTDE_ITEM, FIT.TRIBUT_ORIGEM, FIT.ID_CEST_NCM, FIT.VALOR_ITEM,
		FI.valor_imposto AS ICMS_VALOR_IMPOSTO, 
		FI.base_imposto AS ICMS_BASE_IMPOSTO, 
		FI.base_imposto_calc AS ICMS_BASE_IMPOSTO_CALC, 
		FI.taxa_imposto AS ICMS_TAXA_IMPOSTO, 
		FI2.valor_imposto AS IPI_VALOR_IMPOSTO, 
		FI2.base_imposto AS IPI_BASE_IMPOSTO, 
		FI2.base_imposto_calc AS IPI_BASE_IMPOSTO_CALC, 
		FI2.taxa_imposto AS IPI_TAXA_IMPOSTO, 
		FI5.valor_imposto AS PIS_VALOR_IMPOSTO, 
		FI5.base_imposto AS PIS_BASE_IMPOSTO, 
		FI5.base_imposto_calc AS PIS_BASE_IMPOSTO_CALC, 
		FI5.taxa_imposto AS PIS_TAXA_IMPOSTO, 
		FI6.valor_imposto AS COFINS_VALOR_IMPOSTO, 
		FI6.base_imposto AS COFINS_BASE_IMPOSTO, 
		FI6.base_imposto_calc AS COFINS_BASE_IMPOSTO_CALC, 
		FI6.taxa_imposto AS COFINS_TAXA_IMPOSTO
		
from CSM_TRANSITO_NOTAS A (NOLOCK)

LEFT JOIN FATURAMENTO F (NOLOCK) 
	ON F.FILIAL=A.FILIAL AND F.NF_SAIDA=A.NF_SAIDA AND F.SERIE_NF=A.SERIE_NF

LEFT JOIN FATURAMENTO_ITEM FIT (NOLOCK) 
	ON FIT.FILIAL = F.FILIAL AND FIT.NF_SAIDA = F.NF_SAIDA AND FIT.SERIE_NF = F.SERIE_NF 

LEFT JOIN FATURAMENTO_IMPOSTO FI  (NOLOCK) /* ICMS*/
	ON FI.FILIAL = FIT.FILIAL AND FI.NF_SAIDA = FIT.NF_SAIDA 
	AND FI.SERIE_NF = FIT.SERIE_NF AND FI.ITEM_IMPRESSAO = FIT.ITEM_IMPRESSAO 
	AND FI.SUB_ITEM_TAMANHO = FIT.SUB_ITEM_TAMANHO AND FI.ID_IMPOSTO = 1

LEFT JOIN FATURAMENTO_IMPOSTO FI2  (NOLOCK) /* IPI*/
	ON FI2.FILIAL = FIT.FILIAL AND FI2.NF_SAIDA = FIT.NF_SAIDA 
	AND FI2.SERIE_NF = FIT.SERIE_NF AND FI2.ITEM_IMPRESSAO = FIT.ITEM_IMPRESSAO 
	AND FI2.SUB_ITEM_TAMANHO = FIT.SUB_ITEM_TAMANHO AND FI2.ID_IMPOSTO = 2

LEFT JOIN FATURAMENTO_IMPOSTO FI5  (NOLOCK) /* PIS*/
	ON FI5.FILIAL = FIT.FILIAL AND FI5.NF_SAIDA = FIT.NF_SAIDA 
	AND FI5.SERIE_NF = FIT.SERIE_NF AND FI5.ITEM_IMPRESSAO = FIT.ITEM_IMPRESSAO 
	AND FI5.SUB_ITEM_TAMANHO = FIT.SUB_ITEM_TAMANHO AND FI5.ID_IMPOSTO = 5

LEFT JOIN FATURAMENTO_IMPOSTO FI6  (NOLOCK) /* COFINS*/
	ON FI6.FILIAL = FIT.FILIAL AND FI6.NF_SAIDA = FIT.NF_SAIDA 
	AND FI6.SERIE_NF = FIT.SERIE_NF AND FI6.ITEM_IMPRESSAO = FIT.ITEM_IMPRESSAO 
	AND FI6.SUB_ITEM_TAMANHO = FIT.SUB_ITEM_TAMANHO AND FI6.ID_IMPOSTO = 6

where A.NF_SAIDA <> '000000000'
ORDER BY F.NF_SAIDA, F.SERIE_NF, F.FILIAL, FIT.ITEM_IMPRESSAO, FIT.SUB_ITEM_TAMANHO

/* entradas com imposto */

select	A.NOME_CLIFOR,A.NF_ENTRADA,A.SERIE_NF_ENTRADA, A.FILIAL_ENTRADA,  
		E.EMISSAO, E.RECEBIMENTO,
		E.VALOR_TOTAL, E.VALOR_IMPOSTO_AGREGAR AS ENT_VALOR_IMPOSTO_AGREGAR,
		EIT.CODIGO_ITEM, EIT.CLASSIF_FISCAL, EIT.ITEM_IMPRESSAO, EIT.SUB_ITEM_TAMANHO,
		EIT.CODIGO_FISCAL_OPERACAO, EIT.ID_EXCECAO_IMPOSTO, EIT.DESCRICAO_ITEM, 
		EIT.INDICADOR_CFOP, EIT.PRECO_UNITARIO, EIT.PRECO_UNITARIO_ORIGINAL, EIT.QTDE_ITEM, EIT.TRIBUT_ORIGEM, EIT.ID_CEST_NCM, EIT.VALOR_ITEM,
		EI.valor_imposto AS ICMS_VALOR_IMPOSTO, 
		EI.base_imposto AS ICMS_BASE_IMPOSTO, 
		EI.base_imposto_calc AS ICMS_BASE_IMPOSTO_CALC, 
		EI.taxa_imposto AS ICMS_TAXA_IMPOSTO, 
		EI2.valor_imposto AS IPI_VALOR_IMPOSTO, 
		EI2.base_imposto AS IPI_BASE_IMPOSTO, 
		EI2.base_imposto_calc AS IPI_BASE_IMPOSTO_CALC, 
		EI2.taxa_imposto AS IPI_TAXA_IMPOSTO, 
		EI5.valor_imposto AS PIS_VALOR_IMPOSTO, 
		EI5.base_imposto AS PIS_BASE_IMPOSTO, 
		EI5.base_imposto_calc AS PIS_BASE_IMPOSTO_CALC, 
		EI5.taxa_imposto AS PIS_TAXA_IMPOSTO, 
		EI6.valor_imposto AS COFINS_VALOR_IMPOSTO, 
		EI6.base_imposto AS COFINS_BASE_IMPOSTO, 
		EI6.base_imposto_calc AS COFINS_BASE_IMPOSTO_CALC, 
		EI6.taxa_imposto AS COFINS_TAXA_IMPOSTO
		
from CSM_TRANSITO_NOTAS A (NOLOCK) 

INNER JOIN ENTRADAS E (NOLOCK) 
	ON E.NF_ENTRADA=A.NF_ENTRADA AND E.SERIE_NF_ENTRADA=A.SERIE_NF_ENTRADA AND E.NOME_CLIFOR=A.NOME_CLIFOR AND E.FILIAL=A.FILIAL_ENTRADA

INNER JOIN ENTRADAS_ITEM EIT (NOLOCK) 
	ON EIT.NOME_CLIFOR = E.NOME_CLIFOR AND EIT.NF_ENTRADA = E.NF_ENTRADA AND EIT.SERIE_NF_ENTRADA = E.SERIE_NF_ENTRADA 

INNER JOIN ENTRADAS_IMPOSTO EI  (NOLOCK) /* ICMS*/
	ON EI.NOME_CLIFOR = EIT.NOME_CLIFOR AND EI.NF_ENTRADA = EIT.NF_ENTRADA
	AND EI.SERIE_NF_ENTRADA = EIT.SERIE_NF_ENTRADA AND EI.ITEM_IMPRESSAO = EIT.ITEM_IMPRESSAO 
	AND EI.SUB_ITEM_TAMANHO = EIT.SUB_ITEM_TAMANHO AND EI.ID_IMPOSTO = 1

INNER JOIN ENTRADAS_IMPOSTO EI2  (NOLOCK) /* IPI*/
	ON EI2.NOME_CLIFOR = EIT.NOME_CLIFOR AND EI2.NF_ENTRADA = EIT.NF_ENTRADA
	AND EI2.SERIE_NF_ENTRADA = EIT.SERIE_NF_ENTRADA AND EI2.ITEM_IMPRESSAO = EIT.ITEM_IMPRESSAO 
	AND EI2.SUB_ITEM_TAMANHO = EIT.SUB_ITEM_TAMANHO AND EI2.ID_IMPOSTO = 2

INNER JOIN ENTRADAS_IMPOSTO EI5  (NOLOCK) /* PIS*/
	ON EI5.NOME_CLIFOR = EIT.NOME_CLIFOR AND EI5.NF_ENTRADA = EIT.NF_ENTRADA
	AND EI5.SERIE_NF_ENTRADA = EIT.SERIE_NF_ENTRADA AND EI5.ITEM_IMPRESSAO = EIT.ITEM_IMPRESSAO 
	AND EI5.SUB_ITEM_TAMANHO = EIT.SUB_ITEM_TAMANHO AND EI5.ID_IMPOSTO = 5

INNER JOIN ENTRADAS_IMPOSTO EI6  (NOLOCK) /* COFINS*/
	ON EI6.NOME_CLIFOR = EIT.NOME_CLIFOR AND EI6.NF_ENTRADA = EIT.NF_ENTRADA
	AND EI6.SERIE_NF_ENTRADA = EIT.SERIE_NF_ENTRADA AND EI6.ITEM_IMPRESSAO = EIT.ITEM_IMPRESSAO 
	AND EI6.SUB_ITEM_TAMANHO = EIT.SUB_ITEM_TAMANHO AND EI6.ID_IMPOSTO = 6

where A.NF_SAIDA <> '000000000' 
ORDER BY E.NF_ENTRADA, E.SERIE_NF_ENTRADA, E.NOME_CLIFOR, EIT.ITEM_IMPRESSAO, EIT.SUB_ITEM_TAMANHO




select A.FILIAL,A.NF_SAIDA,A.SERIE_NF,A.NOME_CLIFOR,A.CONDICAO_PGTO,A.NATUREZA_SAIDA,A.TRANSPORTADORA,A.TRANSP_REDESPACHO,
A.TIPO_FRETE, A.EMISSAO,A.DATA_SAIDA,A.FRETE, A.SEGURO, A.DESCONTO, A.ENCARGO, A.ICMS,A.VALOR_TOTAL,a.QTDE_TOTAL,
a.PESO_BRUTO,a.PESO_LIQUIDO,a.VOLUMES, a.TIPO_VOLUME, a.ICMS_BASE, a.CTB_ITEM, a.CTB_LANCAMENTO, a.ICMS_ISENTO, a.ICMS_OUTROS,
a.RATEIO_CENTRO_CUSTO, a.RATEIO_FILIAL, a.VALOR_IMPOSTO_AGREGAR, a.VALOR_SUB_ITENS, a.PROTOCOLO_AUTORIZACAO_NFE, a.CHAVE_NFE,
a.DATA_AUTORIZACAO_NFE, a.STATUS_NFE, a.LOG_STATUS_NFE, a.REGISTRO_DPEC, a.DATA_REGISTRO_DPEC, a.VEICULO_PLACA, a.UF_PLACA_VEICULO,
a.DATA_HORA_EMISSAO, a.INDICA_PRESENCA_COMPRADOR, a.UTC_DATA_SAIDA, a.UTC_EMISSAO, a.ERP_EBS_AR_DATA_ENVIO, a.ERP_EBS_GL_DATA_ENVIO,
a.ERP_EBS_SYNCHRO_DATA_ENVIO, a.INFO_PGTO 
from faturamento A
where FILIAL='CD BARRA VELHA' AND NOME_CLIFOR IN ('CD CAJAMAR','VENDA ATACADO')



select	F.NF_SAIDA, F.SERIE_NF, F.FILIAL, f.NOME_CLIFOR as FILIAL_DESTINO, F.EMISSAO,
		F.VALOR_TOTAL, F.VALOR_IMPOSTO_AGREGAR AS FAT_VALOR_IMPOSTO_AGREGAR,
		FIT.CODIGO_ITEM, FIT.CLASSIF_FISCAL, FIT.ITEM_IMPRESSAO, FIT.SUB_ITEM_TAMANHO,
		FIT.CODIGO_FISCAL_OPERACAO, FIT.ID_EXCECAO_IMPOSTO, FIT.DESCRICAO_ITEM, 
		FIT.INDICADOR_CFOP, FIT.PRECO_UNITARIO, FIT.PRECO_UNITARIO_ORIGINAL, FIT.QTDE_ITEM, FIT.TRIBUT_ORIGEM, FIT.ID_CEST_NCM, FIT.VALOR_ITEM,
		FI.valor_imposto AS ICMS_VALOR_IMPOSTO, 
		FI.base_imposto AS ICMS_BASE_IMPOSTO, 
		FI.base_imposto_calc AS ICMS_BASE_IMPOSTO_CALC, 
		FI.taxa_imposto AS ICMS_TAXA_IMPOSTO, 
		FI2.valor_imposto AS IPI_VALOR_IMPOSTO, 
		FI2.base_imposto AS IPI_BASE_IMPOSTO, 
		FI2.base_imposto_calc AS IPI_BASE_IMPOSTO_CALC, 
		FI2.taxa_imposto AS IPI_TAXA_IMPOSTO, 
		FI5.valor_imposto AS PIS_VALOR_IMPOSTO, 
		FI5.base_imposto AS PIS_BASE_IMPOSTO, 
		FI5.base_imposto_calc AS PIS_BASE_IMPOSTO_CALC, 
		FI5.taxa_imposto AS PIS_TAXA_IMPOSTO, 
		FI6.valor_imposto AS COFINS_VALOR_IMPOSTO, 
		FI6.base_imposto AS COFINS_BASE_IMPOSTO, 
		FI6.base_imposto_calc AS COFINS_BASE_IMPOSTO_CALC, 
		FI6.taxa_imposto AS COFINS_TAXA_IMPOSTO
		
from FATURAMENTO F (NOLOCK) 

LEFT JOIN FATURAMENTO_ITEM FIT (NOLOCK) 
	ON FIT.FILIAL = F.FILIAL AND FIT.NF_SAIDA = F.NF_SAIDA AND FIT.SERIE_NF = F.SERIE_NF 

LEFT JOIN FATURAMENTO_IMPOSTO FI  (NOLOCK) /* ICMS*/
	ON FI.FILIAL = FIT.FILIAL AND FI.NF_SAIDA = FIT.NF_SAIDA 
	AND FI.SERIE_NF = FIT.SERIE_NF AND FI.ITEM_IMPRESSAO = FIT.ITEM_IMPRESSAO 
	AND FI.SUB_ITEM_TAMANHO = FIT.SUB_ITEM_TAMANHO AND FI.ID_IMPOSTO = 1

LEFT JOIN FATURAMENTO_IMPOSTO FI2  (NOLOCK) /* IPI*/
	ON FI2.FILIAL = FIT.FILIAL AND FI2.NF_SAIDA = FIT.NF_SAIDA 
	AND FI2.SERIE_NF = FIT.SERIE_NF AND FI2.ITEM_IMPRESSAO = FIT.ITEM_IMPRESSAO 
	AND FI2.SUB_ITEM_TAMANHO = FIT.SUB_ITEM_TAMANHO AND FI2.ID_IMPOSTO = 2

LEFT JOIN FATURAMENTO_IMPOSTO FI5  (NOLOCK) /* PIS*/
	ON FI5.FILIAL = FIT.FILIAL AND FI5.NF_SAIDA = FIT.NF_SAIDA 
	AND FI5.SERIE_NF = FIT.SERIE_NF AND FI5.ITEM_IMPRESSAO = FIT.ITEM_IMPRESSAO 
	AND FI5.SUB_ITEM_TAMANHO = FIT.SUB_ITEM_TAMANHO AND FI5.ID_IMPOSTO = 5

LEFT JOIN FATURAMENTO_IMPOSTO FI6  (NOLOCK) /* COFINS*/
	ON FI6.FILIAL = FIT.FILIAL AND FI6.NF_SAIDA = FIT.NF_SAIDA 
	AND FI6.SERIE_NF = FIT.SERIE_NF AND FI6.ITEM_IMPRESSAO = FIT.ITEM_IMPRESSAO 
	AND FI6.SUB_ITEM_TAMANHO = FIT.SUB_ITEM_TAMANHO AND FI6.ID_IMPOSTO = 6

where F.FILIAL='CD BARRA VELHA' AND NOME_CLIFOR IN ('CD CAJAMAR','VENDA ATACADO')
ORDER BY F.NF_SAIDA, F.SERIE_NF, F.FILIAL, FIT.ITEM_IMPRESSAO, FIT.SUB_ITEM_TAMANHO
