--select ','+CHAR(39)+RTRIM(PEDIDO)+CHAR(39) from compras where year(emissao)=2019 and fornecedor LIKE 'CHIK%' AND TOT_QTDE_ENTREGAR<>0

--SELECT 'exec lx_movimenta_compras_pa @PEDIDO ='+CHAR(39)+RTRIM(PEDIDO)+CHAR(39)
--from compras where year(emissao)=2019 and fornecedor LIKE 'CHIK%' AND TOT_QTDE_ENTREGAR<>0


select  
 e.PRODUTO, e.COR_PRODUTO, FILIAL, CUSTO_MEDIO1, CUSTO_MEDIO2, CUSTO_MEDIO3, 
 CUSTO_MEDIO4, ULTIMO_CUSTO1, ULTIMO_CUSTO2, ULTIMO_CUSTO3, ULTIMO_CUSTO4, 
 DATA_CUSTO_MEDIO, DATA_ULT_CUSTO, ULTIMA_SAIDA, ULTIMA_ENTRADA, ESTOQUE, 
 ES1,  e.DATA_PARA_TRANSFERENCIA, DATA_AJUSTE, PRIMEIRA_ENTRADA
from COMPRAS_PRODUTO cp
inner join COMPRAS c on c.PEDIDO = cp.PEDIDO
inner join ESTOQUE_PRODUTOS e on e.PRODUTO = cp.PRODUTO and e.COR_PRODUTO = cp.COR_PRODUTO
where 1=1
and year(c.emissao)=2019 and c.fornecedor LIKE 'CHIK%'
and cp.pedido not in (
SELECT a.pedido 
FROM compras A
INNER JOIN COMPRAS_PROD_CANCELADA B ON B.PEDIDO = A.PEDIDO
where year(emissao)=2019 and fornecedor LIKE 'CHIK%' )


select  e.FILIAL, sum(e.ES1) as qty
 --e.PRODUTO, e.COR_PRODUTO, FILIAL, CUSTO_MEDIO1, CUSTO_MEDIO2, CUSTO_MEDIO3, 
 --CUSTO_MEDIO4, ULTIMO_CUSTO1, ULTIMO_CUSTO2, ULTIMO_CUSTO3, ULTIMO_CUSTO4, 
 --DATA_CUSTO_MEDIO, DATA_ULT_CUSTO, ULTIMA_SAIDA, ULTIMA_ENTRADA, ESTOQUE, 
 --ES1,  e.DATA_PARA_TRANSFERENCIA, DATA_AJUSTE, PRIMEIRA_ENTRADA
from COMPRAS_PRODUTO cp
inner join COMPRAS c on c.PEDIDO = cp.PEDIDO
inner join ESTOQUE_PRODUTOS e on e.PRODUTO = cp.PRODUTO and e.COR_PRODUTO = cp.COR_PRODUTO
where 1=1
and year(c.emissao)=2019 and c.fornecedor LIKE 'CHIK%'
and cp.pedido not in (
SELECT a.pedido 
FROM compras A
INNER JOIN COMPRAS_PROD_CANCELADA B ON B.PEDIDO = A.PEDIDO
where year(emissao)=2019 and fornecedor LIKE 'CHIK%' )
group by e.FILIAL
