/*
exclusão de caixas já processadas do e-commerce
*/

SET NOCOUNT ON

DECLARE @TABCAIXAS TABLE (ID INT IDENTITY(1,1), CAIXA VARCHAR(8))
insert into @TABCAIXAS (CAIXA)
select caixa 
from PDA_WMS_TRANSFERE_ESTOQUE_LOJA_VIRTUAL 
where flg_processamento=1 and data_processamento is not null


DECLARE @I INT = 1
DECLARE @TOT INT 

DECLARE @CAIXA VARCHAR(8)
DECLARE @PEDIDO VARCHAR(11)

SELECT @TOT = MAX(ID) FROM @TABCAIXAS


WHILE @I<=@TOT
BEGIN
	SELECT @CAIXA = CAIXA, @PEDIDO = 'CX-'+CAIXA	
	FROM @TABCAIXAS WHERE ID = @I

	if not exists(select 1 from faturamento_prod where caixa = @CAIXA)
	BEGIN
		DECLARE @VENDAS_PRODUTO
		TABLE (
		ID_VENDA INT IDENTITY(1,1),
		PEDIDO CHAR(12), 
		PRODUTO CHAR(12), 
		COR_PRODUTO CHAR(10), 
		ENTREGA DATETIME, 
		ITEM_PEDIDO CHAR(4)
		)
		INSERT INTO @VENDAS_PRODUTO (PEDIDO, PRODUTO,COR_PRODUTO, ENTREGA, ITEM_PEDIDO)
		SELECT PEDIDO, PRODUTO, COR_PRODUTO, ENTREGA, ITEM_PEDIDO 
		FROM VENDAS_PRODUTO WHERE PEDIDO = @PEDIDO

		DECLARE @ID_VENDA INT
		DECLARE @TOT_VENDA INT 
	
		SELECT @TOT_VENDA = MAX(ID_VENDA) 
		FROM @VENDAS_PRODUTO

		DECLARE @PRODUTO CHAR(12), 
				@COR_PRODUTO CHAR(10), 
				@ENTREGA DATETIME, 
				@ITEM_PEDIDO CHAR(4)

		-- EXCLUI TODOS OS ITENS DA TABELA FILHA VENDAS_PRODUTO LINHA A LINHA
		SELECT @ID_VENDA = MIN(ID_VENDA) 
		FROM @VENDAS_PRODUTO

		WHILE @ID_VENDA<=@TOT_VENDA
		BEGIN
			SELECT 	@PRODUTO = PRODUTO, 
					@COR_PRODUTO = COR_PRODUTO, 
					@ENTREGA = ENTREGA, 
					@ITEM_PEDIDO = ITEM_PEDIDO
			FROM @VENDAS_PRODUTO WHERE ID_VENDA = @ID_VENDA

			DELETE FROM VENDAS_PRODUTO 
			WHERE	PEDIDO = @PEDIDO AND 
					PRODUTO = @PRODUTO AND 
					COR_PRODUTO = @COR_PRODUTO AND 
					ENTREGA = @ENTREGA AND
					ITEM_PEDIDO = @ITEM_PEDIDO
			PRINT 'EXCLUIU VENDAS_PRODUTO: '+CONVERT(VARCHAR,@ID_VENDA)+'=> | '+@PEDIDO+'|'+@PRODUTO+'|'+@COR_PRODUTO	
			SET @ID_VENDA = @ID_VENDA + 1
		END

		DELETE FROM @VENDAS_PRODUTO

		DELETE FROM VENDAS
		WHERE PEDIDO = @PEDIDO
		PRINT 'EXCLUIU VENDAS PARA O PEDIDO: '+@PEDIDO

		DELETE 
		FROM FATURAMENTO_CAIXAS 
		WHERE CAIXA = @CAIXA
		PRINT 'EXCLUIU FATURAMENTO_CAIXAS PARA A CAIXA = '+@CAIXA
	END -- if not exists(select 1 from faturamento_prod where caixa = @CAIXA)
	ELSE
	BEGIN
		PRINT 'JÁ EXISTE FATURAMENTO FEITO PARA A CAIXA = '+@CAIXA
	END
	 
	--INCREMENTA O CONTADOR DE REGISTROS (REGNUM)
	PRINT 'LINHA ' + CONVERT(VARCHAR,@I) +' DE '+CONVERT(VARCHAR,@TOT)
	SET @I = @I + 1
END

SET NOCOUNT OFF






