SELECT * from VENDAS_PROD_EMBALADO
where caixa in (
SELECT caixa FROM PDA_WMS_TB_EMBARQUE 
WHERE DATA >= '20191213' AND DOCA = 'SP - ARICANDUVA CAIXA')
and NOME_CLIFOR <> 'SP - ARICANDUVA'

SELECT * FROM PDA_WMS_TB_EMBARQUE 
WHERE DATA >= '20191213' AND faturado = 0

SELECT * from FATURAMENTO_CAIXAS
where caixa in (
SELECT caixa FROM PDA_WMS_TB_EMBARQUE 
WHERE DATA >= '20191213' AND DOCA = 'SP - ARICANDUVA CAIXA')
and NOME_CLIFOR <> 'SP - ARICANDUVA'


select * from VENDAS_PROD_EMBALADO where caixa in ('15041706')
select * from vendas where pedido in ('CX-15527492','CX-15527367')

delete from pda_wms_tb_embarque where caixa in ('15107946','13663758')
update FATURAMENTO_CAIXAS set NOME_CLIFOR = 'SP - ARICANDUVA' WHERE CAIXA IN ('15527492','15527367')

--select * 
UPDATE A SET A.REPRESENTANTE='SP - ARICANDUVA', A.CLIENTE_ATACADO='SP - ARICANDUVA', GERENTE='SP - ARICANDUVA' , A.NOME_CLIFOR_ENTREGA='SP - ARICANDUVA'
from vendas A where pedido in ('CX-15527492','CX-15527367')