SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ==========================================================
-- Author:		PAULO DEVIDE
-- Create date: NOV/17
-- Description:	TRAZ A DATA DE RECEBIMENTO OU EMISSAO DA NOTA
-- ==========================================================
CREATE FUNCTION DBO.FX_DATA_ENTRADA
(
	@PDATA AS CHAR(1), @PNF CHAR(15), @PNOME_CLIFOR VARCHAR(25), @PSERIE VARCHAR(6)
)
RETURNS DATETIME
AS
BEGIN
	DECLARE @DATA_RETORNO DATETIME

	SELECT @DATA_RETORNO = CASE @PDATA
							WHEN 'E' THEN ENTRADAS.EMISSAO
							WHEN 'R' THEN ENTRADAS.RECEBIMENTO
							ELSE ''
							END
	FROM CAEDU.DBO.ENTRADAS ENTRADAS
	WHERE ENTRADAS.NF_ENTRADA = @PNF
			AND ENTRADAS.NOME_CLIFOR = @PNOME_CLIFOR
			AND ENTRADAS.SERIE_NF_ENTRADA = @PSERIE

	RETURN @DATA_RETORNO

END
GO

