
WITH BASE (FILIAL, PRODUTO, COR_PRODUTO, ESTOQUE, SALDO_CONTAGEM, QTDE_CONTAGEM,COMPARA)
AS (
select --SUM(B.ESTOQUE) AS ESTOQUE, SUM(A.SALDO_CONTAGEM) AS SALDO_CONTAGEM
B.FILIAL, A.produto,	A.cor_produto,	B.ESTOQUE,	A.SALDO_CONTAGEM,	QTDE_CONTAGEM, (B.ESTOQUE-A.SALDO_CONTAGEM) AS compara
from ESTOQUE_PROD_CTG_ITENS a
LEFT join ESTOQUE_PRODUTOS b on b.FILIAL='ITAQUERA' 
									AND b.PRODUTO=a.PRODUTO 
									AND b.COR_PRODUTO=a.COR_PRODUTO
WHERE NOME_CONTAGEM='ITAQUERA_2025-08-25')
SELECT * FROM BASE




