LX_CADE ITEM_COMPOSICAO

SELECT * FROM CM_ITEM_COMPOSICAO WHERE ITEM_COMPOSICAO like '3%'

INSERT INTO CM_ITEM_COMPOSICAO (
[ITEM_COMPOSICAO], [DESC_ITEM_COMPOSICAO], [INDICA_ENTRADA_SAIDA], [INATIVO], [INDICADOR_LINX], [COMPOE_CUSTO_MEDIO], [LANCAMENTO_PADRAO], [ATUALIZA_CUSTO_MOV], [FATOR_EST_PROPRIO], [FATOR_EST_DE_TERCEIRO], [FATOR_EST_COM_TERCEIRO], [INDICA_MOV_LOGICO], [LANCAMENTO_PADRAO_IMPOSTO])
VALUES (
'310', 'ITEM COMP. NAT:(242.05)(244.01)(245.02)', 'E', 0, 0, 1, null, 0, 1, 0, -1, 0, null)


SELECT * FROM NATUREZAS_ENTRADAS 
WHERE NATUREZA IN ('242.05','244.01','245.02')