DECLARE @TAB_PRODUTOS_INDICADOR_CFOP TABLE (
ID INT IDENTITY(1,1) NOT NULL,
PRODUTO CHAR(12) NULL, 
FILIAL VARCHAR(25) NULL, 
INDICADOR_CFOP TINYINT NULL, 
TRIBUT_ORIGEM CHAR(3) NULL, 
DATA_PARA_TRANSFERENCIA DATETIME NULL, 
TIPO_ITEM_SPED CHAR(5) NULL, 
LX_STATUS_REGISTRO INT NULL)

insert into @TAB_PRODUTOS_INDICADOR_CFOP (PRODUTO,FILIAL,INDICADOR_CFOP,TRIBUT_ORIGEM,
											DATA_PARA_TRANSFERENCIA,TIPO_ITEM_SPED,LX_STATUS_REGISTRO)
select 
	PRODUTO,
	FILIAL,
	INDICADOR_CFOP,
	TRIBUT_ORIGEM,
	DATA_PARA_TRANSFERENCIA,
	TIPO_ITEM_SPED,
	LX_STATUS_REGISTRO
from produtos_indicador_cfop  PIC 
where filial='CD NAVEGANTES' AND PIC.TRIBUT_ORIGEM=1


declare @i int = 1
declare @tot int
declare @ins int = 0

declare 
@PRODUTO CHAR(12), 
@FILIAL VARCHAR(25), 
@INDICADOR_CFOP TINYINT, 
@TRIBUT_ORIGEM CHAR(3), 
@DATA_PARA_TRANSFERENCIA DATETIME, 
@TIPO_ITEM_SPED CHAR(5), 
@LX_STATUS_REGISTRO INT

select @tot = max(id) from @TAB_PRODUTOS_INDICADOR_CFOP

while @i <= @tot
begin

	select
	@PRODUTO = PRODUTO,
	@FILIAL = FILIAL,
	@INDICADOR_CFOP = INDICADOR_CFOP,
	@TRIBUT_ORIGEM = TRIBUT_ORIGEM,
	@DATA_PARA_TRANSFERENCIA = DATA_PARA_TRANSFERENCIA,
	@TIPO_ITEM_SPED = TIPO_ITEM_SPED,
	@LX_STATUS_REGISTRO = LX_STATUS_REGISTRO
	from @TAB_PRODUTOS_INDICADOR_CFOP
	where id = @i

	if not exists(select 1 from PRODUTOS_INDICADOR_CFOP where PRODUTO = @PRODUTO AND FILIAL = 'CD BARRA VELHA')
	BEGIN
		INSERT INTO PRODUTOS_INDICADOR_CFOP (PRODUTO,FILIAL,INDICADOR_CFOP,TRIBUT_ORIGEM,
											DATA_PARA_TRANSFERENCIA,TIPO_ITEM_SPED,LX_STATUS_REGISTRO)
		VALUES (@PRODUTO, 'CD BARRA VELHA', @INDICADOR_CFOP, @TRIBUT_ORIGEM, GETDATE(), @TIPO_ITEM_SPED, @LX_STATUS_REGISTRO)
		set @ins= @ins + 1
	END
	set @i = @i + 1
end

select @ins



