--DECLARE @USUARIO VARCHAR(25) = 'CCP\MARCO.LINX'
insert into users (usuario, NOME_COMPLETO, DEPTO, ACESSO_TOTAL, ACESSO_ESP_1, ACESSO_ESP_2, INCLUIR, ALTERAR, EXCLUIR, PESQUISA_ESPECIAL, IMPRIMIR, CRIAR_RELATORIO, PASSW, NIVEL_ACESSO, AUDITORIA_GERAL, AUDITORIA, EMPRESA, EMPRESA_MULTI_ACESSO, PERMITE_EXPORTAR, EMAIL, PERMITE_EDITAR_LAYOUTS, PERMITE_EDITAR_EVENTOS, AUTENTICACAO_WINDOWS, LX_SYSTEM_USER, INATIVO,GRUPO)
select 'CAP' usuario, 'CENTRAL DE ATENDIMENTO PALMA' AS NOME_COMPLETO, DEPTO, ACESSO_TOTAL, ACESSO_ESP_1, ACESSO_ESP_2, INCLUIR, ALTERAR, EXCLUIR, PESQUISA_ESPECIAL, IMPRIMIR, CRIAR_RELATORIO, 'Qx7SaGmcne' PASSW, NIVEL_ACESSO, AUDITORIA_GERAL, AUDITORIA, EMPRESA, EMPRESA_MULTI_ACESSO, PERMITE_EXPORTAR, EMAIL, PERMITE_EDITAR_LAYOUTS, PERMITE_EDITAR_EVENTOS, AUTENTICACAO_WINDOWS, 'CAP' LX_SYSTEM_USER, INATIVO, GRUPO 
from USERS where usuario like 'CCP\PAULO.DEVIDE'

SELECT * FROM USERS WHERE USUARIO='CAP'

/*COM AUTENTICAÇÃO WINDOWS*/
DECLARE @USUARIO VARCHAR(25) = 'CCP\LILIAN.ROCHA'
insert into users (usuario, NOME_COMPLETO, DEPTO, ACESSO_TOTAL, ACESSO_ESP_1, ACESSO_ESP_2, INCLUIR, ALTERAR, EXCLUIR, PESQUISA_ESPECIAL, IMPRIMIR, CRIAR_RELATORIO, PASSW, NIVEL_ACESSO, AUDITORIA_GERAL, AUDITORIA, EMPRESA, EMPRESA_MULTI_ACESSO, PERMITE_EXPORTAR, EMAIL, PERMITE_EDITAR_LAYOUTS, PERMITE_EDITAR_EVENTOS, AUTENTICACAO_WINDOWS, LX_SYSTEM_USER, INATIVO,GRUPO)
select @USUARIO usuario, 'LILIAN DA ROCHA' AS NOME_COMPLETO, DEPTO, ACESSO_TOTAL, ACESSO_ESP_1, ACESSO_ESP_2, INCLUIR, ALTERAR, EXCLUIR, PESQUISA_ESPECIAL, IMPRIMIR, CRIAR_RELATORIO, '' PASSW, NIVEL_ACESSO, AUDITORIA_GERAL, AUDITORIA, EMPRESA, EMPRESA_MULTI_ACESSO, PERMITE_EXPORTAR, '' AS EMAIL, PERMITE_EDITAR_LAYOUTS, PERMITE_EDITAR_EVENTOS, AUTENTICACAO_WINDOWS, @USUARIO LX_SYSTEM_USER, INATIVO, GRUPO 
from USERS where usuario like 'CCP\PATRICIA.SOUZA'


SELECT * 
delete
FROM USERS 
--where usuario like 'CCP\PATRICIA.SOUZA'
where usuario like 'CCP\lilian.rocha'


