SELECT RIGHT('00'+CONVERT(VARCHAR,ID),2) FROM #TMPCODIGOS
WHERE RIGHT('00'+CONVERT(VARCHAR,ID),2) NOT IN (
SELECT CODIGO_TAB_PRECO FROM TABELAS_PRECO)
ORDER BY 1

--SELECT TOP 99 IDENTITY(int, 1,1) AS ID 
--INTO #TMPCODIGOS
--FROM FILIAIS

SELECT * FROM #TMPCODIGOS


select * from INFO_LOJAS

select * from TABELAS_PRECO 
order by DATA_PARA_TRANSFERENCIA desc
SELECT * FROM FILIAIS ORDER BY COD_FILIAL DESC

insert into INFO_LOJAS (ip,loja,CODIGO_FILIAL,CODIGO_PRECO,BANCO,VENDA,ATIVO,INSTANCIA,ABV,COLLATION)
values ('192.168.0.55','SP - LAPA','000133','55','CAEDU','VENDAS_SP_LAPA',1,'','LAP','SQL_Latin1_General_CP1_CI_AS'),
('192.168.0.55','CAMPINAS - CENTRO','000134','67','CAEDU','VENDAS_CAMPINAS_CENTRO',1,'','CAM','SQL_Latin1_General_CP1_CI_AS'),
('192.168.0.55','RP - SH NOVO SHOPPING','000135','69','CAEDU','VENDAS_RP_SH_NOVO_SHOPP',1,'','RPS','SQL_Latin1_General_CP1_CI_AS')
