USE [CAEDU]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [IX_PRODUTOS_LINHAS_LINHA]    Script Date: 15/05/2026 11:18:57 ******/
CREATE NONCLUSTERED INDEX [IX_PRODUTOS_LINHAS_LINHA] ON [dbo].[PRODUTOS_LINHAS]
(
	[LINHA] ASC
)
INCLUDE([COD_LINHA]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


