--select ERP_FT_CATEGORIA, erp_codigo_umode, p.DATA_PARA_TRANSFERENCIA,* from produtos p where DATA_PARA_TRANSFERENCIA>='20230127' order by p.DATA_PARA_TRANSFERENCIA desc

----lx_cade_coluna erp_ft

--select * from tb_modelagem order by 3 desc


--select * from COLECOES



insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('OUIN23','OUT/INV 23',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('VERA23','VERÃO 23',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('OUIN24','OUT/INV 24',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('VERA24','VERÃO 24',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('OUIN25','OUT/INV 25',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('VERA25','VERÃO 25',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('OUIN26','OUT/INV 26',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('VERA26','VERÃO 26',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('OUIN27','OUT/INV 27',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('VERA27','VERÃO 27',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('OUIN28','OUT/INV 28',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('VERA28','VERÃO 28',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('OUIN29','OUT/INV 29',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('VERA29','VERÃO 29',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('OUIN30','OUT/INV 30',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('VERA30','VERÃO 30',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('OUIN31','OUT/INV 31',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('VERA31','VERÃO 31',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('OUIN32','OUT/INV 32',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('VERA32','VERÃO 32',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('OUIN33','OUT/INV 33',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('VERA33','VERÃO 33',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('OUIN34','OUT/INV 34',0,GETDATE())
insert into COLECOES (COLECAO, DESC_COLECAO, INATIVO, DATA_PARA_TRANSFERENCIA) values ('VERA34','VERÃO 34',0,GETDATE())


--SELECT RIGHT( '000000'+CONVERT(VARCHAR,MAX(CONVERT(INT,CODIGO)+1)), 6) FROM CAEDU_LISTA_COMBO
--SELECT * FROM CAEDU_LISTA_COMBO WHERE id_dominio='002' AND 
--DESCRICAO IN (
--'NOMADE'
--,'INTO THE WIND'
--,'ESTRUTURA'
--,'LIBRE'
--,'BOSSA NOVA'
--,'ENERGY'
--,'METAVERSO'
--,'CAMP COLLEGE'
--,'FIELD DREAMS'
--,'SUMMER FEELINGS'
--,'EUPHORIA'
--,'CROCODILO BABY'
--,'UNDER THE SEA'
--,'BLOOMING'
--,'POOL PARTY'
--,'CANDY PARTY'
--,'BOSQUE ENCANTADO'
--,'ALÉM DO ARCO-ÍRIS'
--,'BRIGHT NIGHT'
--,'CANDY PARTY'
--,'ROMANTIC GIRL'
--,'STREET'
--,'BRIGHT NIGHT'
--,'SUMMER HISTORY'
--,'FUNHOUSE'
--,'BEACH VACATION'
--,'PLAY SUMMER'
--,'CALIFORNIA GIRL'
--,'FEARLESS CHILDHOOD'
--,'SUPERSONIC'
--,'ADVENTURE HUNTER'
--,'ALPHA GENERATION'
--,'FEARLESS YOUTH'
--,'TO THE MOON AND BACK'
--,'ADVENTURE ADDICTED'
--,'GIPSY KING'
--,'JOVEM FOFO'
--,'JOVEM FUN'
--,'CONTEMPORÂNEO MODERNO'
--,'CONTEMPORÂNEO CONFORTO'
--,'CHASING THE SUN'
--,'LET S GROOVY'
--,'BETTER VERSE'
--,'SIESTA BAY'
--,'REGATTA CLUB'
--,'UNDER THE OCEAN'
--,'GOING TO THE MOUNTAIN'
--,'MINIMALISMO TRANSCENDENTAL'
--,'METAVERSO'
--,'TWILIGHT ON THE PIER'
--,'BEYOND TIME'
--,'WINTER GIRLS 23'
--,'WINTER BOYS 23'
--,'FEMININO W23'
--,'MASCULINO W23'
--,'SLEEPWEAR GIRLS W23'
--,'SLEEPWEAR BOYS W23'
--,'SLEEPWEAR MASCULINO W24'
--,'PRIDE'
--,'MICKEY&FRIENDS'
--,'WONDER WOMAN'
--,'HARRY POTTER'
--,'NASA'
--,'MARVEL'
--,'POSITIVE VIBES'
--,'PANTANAL'
--,'PET FOFO'
--,'BÁSICOS'
--,'LOONEY TUNES FANTÁSTICO'
--,'AZUL TROPICAL'
--,'CHEVRON'
--,'FLORAL BICOLOR'
--,'AZULEJO GREGO'
--,'TIE DYE'
--,'ONÇA LIMA'
--,'ÉTNICO PB'
--,'BEACH GIRLS 24'
--,'BEACH BOYS 24'
--,'SUMMER GIRLS 24'
--,'SUMMER BOYS 24'
--,'FEMININO S24'
--,'MASCULINO S24'
--,'SLEEPWEAR GIRLS S24'
--,'SLEEPWEAR BOYS S24'
--,'SLEEPWEAR MASCULINO S24'
--,'COLORFUN'
--,'BARBIE CORE'
--,'COTTAGE CORE'
--,'BOLD TYPE'
--,'VERÃO TROPICAL'
--,'WINNIE THE POOH'
--,'M.I.C.K.E.Y.'
--,'SPIDER-MAN'
--,'POWERPUFF GIRLS'
--,'DONALD & DAISY MAD LOVE'
--,'TOM AND JERRY'
--,'HOME S24'
--,'BEACH MASCULINO 24'
--)


INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001101','NOMADE','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001102','INTO THE WIND','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001103','ESTRUTURA','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001104','LIBRE','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001105','BOSSA NOVA','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001106','ENERGY','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001107','METAVERSO','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001108','CAMP COLLEGE','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001109','FIELD DREAMS','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001110','SUMMER FEELINGS','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001111','EUPHORIA','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001112','CROCODILO BABY','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001113','UNDER THE SEA','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001114','BLOOMING','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001115','POOL PARTY','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001116','CANDY PARTY','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001117','BOSQUE ENCANTADO','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001118','ALÉM DO ARCO-ÍRIS','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001119','BRIGHT NIGHT','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001120','CANDY PARTY','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001121','ROMANTIC GIRL','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001122','STREET','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001123','BRIGHT NIGHT','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001124','SUMMER HISTORY','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001125','FUNHOUSE','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001126','BEACH VACATION','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001127','PLAY SUMMER','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001128','CALIFORNIA GIRL','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001129','FEARLESS CHILDHOOD','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001130','SUPERSONIC','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001131','ADVENTURE HUNTER','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001132','ALPHA GENERATION','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001133','FEARLESS YOUTH','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001134','TO THE MOON AND BACK','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001135','ADVENTURE ADDICTED','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001136','GIPSY KING','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001137','JOVEM FOFO','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001138','JOVEM FUN','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001140','CONTEMPORÂNEO MODERNO','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001141','CONTEMPORÂNEO CONFORTO','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001142','CHASING THE SUN','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001143','LET S GROOVY','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001144','BETTER VERSE','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001145','SIESTA BAY','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001146','REGATTA CLUB','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001147','UNDER THE OCEAN','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001148','GOING TO THE MOUNTAIN','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001149','MINIMALISMO TRANSCENDENTAL','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001150','METAVERSO','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001151','TWILIGHT ON THE PIER','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001152','BEYOND TIME','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001153','WINTER GIRLS 23','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001154','WINTER BOYS 23','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001155','FEMININO W23','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001156','MASCULINO W23','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001157','SLEEPWEAR GIRLS W23','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001158','SLEEPWEAR BOYS W23','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001159','SLEEPWEAR MASCULINO W24','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001160','PRIDE','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001161','MICKEY&FRIENDS','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001162','WONDER WOMAN','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001163','HARRY POTTER','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001164','NASA','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001165','MARVEL','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001166','POSITIVE VIBES','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001167','PANTANAL','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001168','PET FOFO','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001169','BÁSICOS','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001170','LOONEY TUNES FANTÁSTICO','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001171','AZUL TROPICAL','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001172','CHEVRON','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001173','FLORAL BICOLOR','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001174','AZULEJO GREGO','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001175','TIE DYE','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001176','ONÇA LIMA','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001177','ÉTNICO PB','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001178','BEACH GIRLS 24','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001179','BEACH BOYS 24','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001180','SUMMER GIRLS 24','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001181','SUMMER BOYS 24','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001182','FEMININO S24','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001183','MASCULINO S24','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001184','SLEEPWEAR GIRLS S24','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001185','SLEEPWEAR BOYS S24','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001186','SLEEPWEAR MASCULINO S24','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001187','COLORFUN','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001188','BARBIE CORE','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001189','COTTAGE CORE','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001190','BOLD TYPE','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001191','VERÃO TROPICAL','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001192','WINNIE THE POOH','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001193','M.I.C.K.E.Y.','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001194','SPIDER-MAN','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001195','POWERPUFF GIRLS','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001196','DONALD & DAISY MAD LOVE','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001197','TOM AND JERRY','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001198','HOME S24','002','TEMA')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001199','BEACH MASCULINO 24','002','TEMA')



INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001201','LIQUIDA LEVA TUDO','001','EVENTOS')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001202','ESPECIAL ESPORTIVO','001','EVENTOS')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001203','ALTO VERÃO','001','EVENTOS')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001204','CARNAVAL','001','EVENTOS')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001205','PREVIEW OUT/INV','001','EVENTOS')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001206','LANÇAMENTO OUT/INV','001','EVENTOS')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001207','DIA DA MULHER','001','EVENTOS')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001208','ESPECIAL PERSONAGENS','001','EVENTOS')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001209','NAMORADOS','001','EVENTOS')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001210','ESPECIAL JEANS','001','EVENTOS')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001211','PREVIEW PRIM/VER','001','EVENTOS')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001212','LANÇAMENTO PRIM/VER','001','EVENTOS')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001213','ESPECIAL LINGERIE','001','EVENTOS')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001214','ESPECIAL MODA PRAIA','001','EVENTOS')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001215','CAMPANHA CARTÃO CAEDU','001','EVENTOS')
INSERT INTO CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO) VALUES ('001216','ESPECIAL CALÇADOS','001','EVENTOS')


SELECT * 
--UPDATE A SET SEQUENCIA='001220'
FROM SEQUENCIAIS A WHERE TABELA_COLUNA LIKE 'CAEDU_LISTA_COMBO%'


SELECT A.DESCRICAO AS DESCRICAO_LISTA, B.CODIGO, B.DESCRICAO 
FROM CGP_FICHA_TECNICA A
INNER JOIN CGP_FICHA_TECNICA_ITENS B ON B.CODIGO_FT=A.CODIGO
ORDER BY 1,2


INSERT INTO PRODUTOS_TIPOS (TIPO_PRODUTO, DATA_PARA_TRANSFERENCIA,COD_TIPO_PRODUTO,INATIVO) VALUES ('C 5',GETDATE(),'OD',0)
INSERT INTO PRODUTOS_TIPOS (TIPO_PRODUTO, DATA_PARA_TRANSFERENCIA,COD_TIPO_PRODUTO,INATIVO) VALUES ('C FLEX',GETDATE(),'OE',0)
INSERT INTO PRODUTOS_TIPOS (TIPO_PRODUTO, DATA_PARA_TRANSFERENCIA,COD_TIPO_PRODUTO,INATIVO) VALUES ('MESA 5 INF',GETDATE(),'OF',0)
INSERT INTO PRODUTOS_TIPOS (TIPO_PRODUTO, DATA_PARA_TRANSFERENCIA,COD_TIPO_PRODUTO,INATIVO) VALUES ('MESA 5 SUP',GETDATE(),'OG',0)
INSERT INTO PRODUTOS_TIPOS (TIPO_PRODUTO, DATA_PARA_TRANSFERENCIA,COD_TIPO_PRODUTO,INATIVO) VALUES ('MESA JNS 1 INF',GETDATE(),'OH',0)
INSERT INTO PRODUTOS_TIPOS (TIPO_PRODUTO, DATA_PARA_TRANSFERENCIA,COD_TIPO_PRODUTO,INATIVO) VALUES ('MESA JNS 1 SUP',GETDATE(),'OI',0)
INSERT INTO PRODUTOS_TIPOS (TIPO_PRODUTO, DATA_PARA_TRANSFERENCIA,COD_TIPO_PRODUTO,INATIVO) VALUES ('MESA JNS 2 INF',GETDATE(),'OJ',0)
INSERT INTO PRODUTOS_TIPOS (TIPO_PRODUTO, DATA_PARA_TRANSFERENCIA,COD_TIPO_PRODUTO,INATIVO) VALUES ('MESA JNS 2 SUP',GETDATE(),'OK',0)
INSERT INTO PRODUTOS_TIPOS (TIPO_PRODUTO, DATA_PARA_TRANSFERENCIA,COD_TIPO_PRODUTO,INATIVO) VALUES ('ROLLER',GETDATE(),'OL',0)
INSERT INTO PRODUTOS_TIPOS (TIPO_PRODUTO, DATA_PARA_TRANSFERENCIA,COD_TIPO_PRODUTO,INATIVO) VALUES ('SOLO LICENCIADOS',GETDATE(),'OM',0)
INSERT INTO PRODUTOS_TIPOS (TIPO_PRODUTO, DATA_PARA_TRANSFERENCIA,COD_TIPO_PRODUTO,INATIVO) VALUES ('PEGBOARD',GETDATE(),'ON',0)

