 insert into produtos (
 [PRODUTO], [CODIGO_PRECO], [MATERIAL], [PERIODO_PCP], [TABELA_OPERACOES], [FATOR_OPERACOES], [CLASSIF_FISCAL], [TIPO_PRODUTO], [TABELA_MEDIDAS], 
 [DESC_PRODUTO], [GRUPO_PRODUTO], [SUBGRUPO_PRODUTO], [COLECAO], [GRADE], [DESC_PROD_NF], [LINHA], [GRIFFE], [CARTELA], [UNIDADE], [PESO], [REVENDA], 
 [REFER_FABRICANTE], [MODELAGEM], [SORTIMENTO_COR], [FABRICANTE], [SORTIMENTO_TAMANHO], [VARIA_PRECO_COR], [VARIA_PRECO_TAM], [PONTEIRO_PRECO_TAM], 
 [VARIA_CUSTO_COR], [PERTENCE_A_CONJUNTO], [TRIBUT_ICMS], [TRIBUT_ORIGEM], [VARIA_CUSTO_TAM], [CUSTO_REPOSICAO1], [CUSTO_REPOSICAO2], [CUSTO_REPOSICAO3], 
 [CUSTO_REPOSICAO4], [DATA_REPOSICAO], [ESTILISTA], [MODELISTA], [TAMANHO_BASE], [GIRO_ENTREGA], [INATIVO], [ENVIA_LOJA_VAREJO], [ENVIA_LOJA_ATACADO], 
 [ENVIA_REPRESENTANTE], [ENVIA_VAREJO_INTERNET], [ENVIA_ATACADO_INTERNET], [MODELO], [REDE_LOJAS], [DATA_PARA_TRANSFERENCIA], [FABRICANTE_ICMS_ABATER], 
 [FABRICANTE_PRAZO_PGTO], [TAXA_JUROS_DEFLACIONAR], [TAXAS_IMPOSTOS_APLICAR], [PRECO_REPOSICAO_1], [PRECO_REPOSICAO_2], [PRECO_REPOSICAO_3], [PRECO_REPOSICAO_4], 
 [PRECO_A_VISTA_REPOSICAO_1], [PRECO_A_VISTA_REPOSICAO_2], [PRECO_A_VISTA_REPOSICAO_3], [PRECO_A_VISTA_REPOSICAO_4], [FABRICANTE_FRETE], [DROP_DE_TAMANHOS], 
 [DATA_CADASTRAMENTO], [STATUS_PRODUTO], [TIPO_STATUS_PRODUTO], [OBS], [COMPOSICAO], [RESTRICAO_LAVAGEM], [EMPRESA], [ORCAMENTO], [CLIENTE_DO_PRODUTO], 
 [CONTA_CONTABIL], [ESPESSURA], [ALTURA], [LARGURA], [COMPRIMENTO], [EMPILHAMENTO_MAXIMO], [SEXO_TIPO], [PARTE_TIPO], [VERSAO_FICHA], 
 [COD_FLUXO_PRODUTO], [DATA_INICIO_DESENVOLVIMENTO], [INDICADOR_CFOP], [MONTAGEM_KIT], [MRP_AGRUPAR_NECESSIDADE_DIAS], [MRP_AGRUPAR_NECESSIDADE_TIPO], 
 [MRP_DIAS_SEGURANCA], [MRP_EMISSAO_LIBERACAO_DIAS], [MRP_ENTREGA_GIRO_DIAS], [MRP_PARTICIPANTE], [MRP_MAIOR_GIRO_MP_DIAS],  
 [OP_POR_COR], [OP_QTDE_MAXIMA], [OP_QTDE_MINIMA], [QUALIDADE], [SEMI_ACABADO], [CONTA_CONTABIL_COMPRA], [CONTA_CONTABIL_VENDA], 
 [CONTA_CONTABIL_DEV_COMPRA], [CONTA_CONTABIL_DEV_VENDA], [ID_EXCECAO_GRUPO], [ID_EXCECAO_IMPOSTO], [DIAS_COMPRA], [FATOR_P], [FATOR_Q], [FATOR_F], 
 [CONTINUIDADE], [COD_CATEGORIA], [COD_SUBCATEGORIA], [COD_PRODUTO_SOLUCAO], [COD_PRODUTO_SEGMENTO], [TIPO_ITEM_SPED], [POSSUI_GTIN], [PERC_COMISSAO], 
 [ACEITA_ENCOMENDA], [DIAS_GARANTIA_LOJA], [DIAS_GARANTIA_FABRICANTE], [POSSUI_MONTAGEM], [PERMITE_ENTREGA_FUTURA], [ID_PRECO], [NATUREZA_RECEITA], 
 [COD_ALIQUOTA_PIS_COFINS_DIF], [DATA_LIMITE_PEDIDO], [LX_STATUS_REGISTRO], [ERP_CUPS_SEGMENTO], [ERP_CUPS_STYLENUMBER], [ERP_CUPS_EVENTO], [ERP_CUPS_TEMA], 
 [ERP_CUPS_COMPRIMENTO], [ERP_CUPS_CONTRUCAO], [ERP_CUPS_COMPOSICAO], [ERP_CUPS_FORRO], [ERP_CUPS_PRODUTO], [ERP_CUPS_SUPPLIER], [ERP_CUPS_PRECO_CUSTO_ESTIMADO], 
 [ERP_CUPS_CODEBAR_REF], [ERP_CUPS_CODEBAR_PB], [ERP_CUPS_CODEBAR_CX], [ERP_CUPS_BLOQUEIA_PRODUTO], [ERP_CUPS_CONJUNTO], [ERP_CUPS_COMPRIMENTO_BOTTOM], 
 [ERP_CUPS_COMPOSICAO_BOTTOM], [ERP_CUPS_FORRO_BOTTOM], [ERP_CUPS_SUBGRUPO_ATACADO], [ARREDONDA], [ID_ARTIGO], [LX_HASH], [SPED_DATA_FIM], [SPED_DATA_INI], 
 [TIPO_PP], [ID_CEST_NCM], [ERP_AREA_JEANS], [ERP_QTD_PACK], [ERP_CUPS_CUSTO_FOB_MINIMO], [ERP_CUPS_CUSTO_FOB], [ERP_LICENCIADO], [ERP_DESC_LICENCIADO], 
 [ERP_TEMA_LICENCIADO], [ID_MODELAGEM], [ERP_USERS_ALTERA_PACK], [DIAS_ACERTO_CONSIGNACAO], [FATOR_A], [FATOR_B], [FATOR_BUFFER], [FATOR_LT], [TIPO_CANAL], 
 [ID_MODELAGEM2], [ERP_GRUPO_MERCADORIA], [ERP_TIPO_ETIQUETA], [ERP_DATA_ULTIMO_AGENDAMENTO], [TITULO_B2C], [DESCRICAO_B2C], [PRE_VENDA], [TAGS], [VIDEO_EMBED], 
 [CARACTERISTICAS_TECNICAS_B2C], [FRETE_GRATIS], [ESTOQUE_MINIMO], [DATA_PUBLICACAO_B2C], [GRUPO_PRODUTO_B2C], [SUBGRUPO_PRODUTO_B2C], [TIPO_PRODUTO_B2C], 
 [GRIFFE_B2C], [LINHA_B2C], [FABRICANTE_B2C], [CATEGORIA_B2C], [SUBCATEGORIA_B2C], [REPOSICAO_B2C], [IMG_ESTILO], [DESCRICAO_B2C_2], [DESCRICAO_B2C_3], 
 [ERP_MATERIA_PRIMA]
 )
 select [PRODUTO], [CODIGO_PRECO], [MATERIAL], [PERIODO_PCP], [TABELA_OPERACOES], [FATOR_OPERACOES], [CLASSIF_FISCAL], [TIPO_PRODUTO], [TABELA_MEDIDAS], 
 [DESC_PRODUTO], [GRUPO_PRODUTO], [SUBGRUPO_PRODUTO], [COLECAO], [GRADE], [DESC_PROD_NF], [LINHA], [GRIFFE], [CARTELA], [UNIDADE], [PESO], [REVENDA], 
 [REFER_FABRICANTE], [MODELAGEM], [SORTIMENTO_COR], [FABRICANTE], [SORTIMENTO_TAMANHO], [VARIA_PRECO_COR], [VARIA_PRECO_TAM], [PONTEIRO_PRECO_TAM], 
 [VARIA_CUSTO_COR], [PERTENCE_A_CONJUNTO], [TRIBUT_ICMS], [TRIBUT_ORIGEM], [VARIA_CUSTO_TAM], [CUSTO_REPOSICAO1], [CUSTO_REPOSICAO2], [CUSTO_REPOSICAO3], 
 [CUSTO_REPOSICAO4], [DATA_REPOSICAO], [ESTILISTA], [MODELISTA], [TAMANHO_BASE], [GIRO_ENTREGA], [INATIVO], [ENVIA_LOJA_VAREJO], [ENVIA_LOJA_ATACADO], 
 [ENVIA_REPRESENTANTE], [ENVIA_VAREJO_INTERNET], [ENVIA_ATACADO_INTERNET], [MODELO], [REDE_LOJAS], [DATA_PARA_TRANSFERENCIA], [FABRICANTE_ICMS_ABATER], 
 [FABRICANTE_PRAZO_PGTO], [TAXA_JUROS_DEFLACIONAR], [TAXAS_IMPOSTOS_APLICAR], [PRECO_REPOSICAO_1], [PRECO_REPOSICAO_2], [PRECO_REPOSICAO_3], [PRECO_REPOSICAO_4], 
 [PRECO_A_VISTA_REPOSICAO_1], [PRECO_A_VISTA_REPOSICAO_2], [PRECO_A_VISTA_REPOSICAO_3], [PRECO_A_VISTA_REPOSICAO_4], [FABRICANTE_FRETE], [DROP_DE_TAMANHOS], 
 [DATA_CADASTRAMENTO], [STATUS_PRODUTO], [TIPO_STATUS_PRODUTO], [OBS], [COMPOSICAO], [RESTRICAO_LAVAGEM], [EMPRESA], [ORCAMENTO], [CLIENTE_DO_PRODUTO], 
 [CONTA_CONTABIL], [ESPESSURA], [ALTURA], [LARGURA], [COMPRIMENTO], [EMPILHAMENTO_MAXIMO], [SEXO_TIPO], [PARTE_TIPO], [VERSAO_FICHA], 
 [COD_FLUXO_PRODUTO], [DATA_INICIO_DESENVOLVIMENTO], [INDICADOR_CFOP], [MONTAGEM_KIT], [MRP_AGRUPAR_NECESSIDADE_DIAS], [MRP_AGRUPAR_NECESSIDADE_TIPO], 
 [MRP_DIAS_SEGURANCA], [MRP_EMISSAO_LIBERACAO_DIAS], [MRP_ENTREGA_GIRO_DIAS], [MRP_PARTICIPANTE], [MRP_MAIOR_GIRO_MP_DIAS],  
 [OP_POR_COR], [OP_QTDE_MAXIMA], [OP_QTDE_MINIMA], [QUALIDADE], [SEMI_ACABADO], [CONTA_CONTABIL_COMPRA], [CONTA_CONTABIL_VENDA], 
 [CONTA_CONTABIL_DEV_COMPRA], [CONTA_CONTABIL_DEV_VENDA], [ID_EXCECAO_GRUPO], [ID_EXCECAO_IMPOSTO], [DIAS_COMPRA], [FATOR_P], [FATOR_Q], [FATOR_F], 
 [CONTINUIDADE], [COD_CATEGORIA], [COD_SUBCATEGORIA], [COD_PRODUTO_SOLUCAO], [COD_PRODUTO_SEGMENTO], [TIPO_ITEM_SPED], [POSSUI_GTIN], [PERC_COMISSAO], 
 [ACEITA_ENCOMENDA], [DIAS_GARANTIA_LOJA], [DIAS_GARANTIA_FABRICANTE], [POSSUI_MONTAGEM], [PERMITE_ENTREGA_FUTURA], [ID_PRECO], [NATUREZA_RECEITA], 
 [COD_ALIQUOTA_PIS_COFINS_DIF], [DATA_LIMITE_PEDIDO], [LX_STATUS_REGISTRO], [ERP_CUPS_SEGMENTO], [ERP_CUPS_STYLENUMBER], [ERP_CUPS_EVENTO], [ERP_CUPS_TEMA], 
 [ERP_CUPS_COMPRIMENTO], [ERP_CUPS_CONTRUCAO], [ERP_CUPS_COMPOSICAO], [ERP_CUPS_FORRO], [ERP_CUPS_PRODUTO], [ERP_CUPS_SUPPLIER], [ERP_CUPS_PRECO_CUSTO_ESTIMADO], 
 [ERP_CUPS_CODEBAR_REF], [ERP_CUPS_CODEBAR_PB], [ERP_CUPS_CODEBAR_CX], [ERP_CUPS_BLOQUEIA_PRODUTO], [ERP_CUPS_CONJUNTO], [ERP_CUPS_COMPRIMENTO_BOTTOM], 
 [ERP_CUPS_COMPOSICAO_BOTTOM], [ERP_CUPS_FORRO_BOTTOM], [ERP_CUPS_SUBGRUPO_ATACADO], [ARREDONDA], [ID_ARTIGO], [LX_HASH], [SPED_DATA_FIM], [SPED_DATA_INI], 
 [TIPO_PP], [ID_CEST_NCM], [ERP_AREA_JEANS], [ERP_QTD_PACK], [ERP_CUPS_CUSTO_FOB_MINIMO], [ERP_CUPS_CUSTO_FOB], [ERP_LICENCIADO], [ERP_DESC_LICENCIADO], 
 [ERP_TEMA_LICENCIADO], [ID_MODELAGEM], [ERP_USERS_ALTERA_PACK], [DIAS_ACERTO_CONSIGNACAO], [FATOR_A], [FATOR_B], [FATOR_BUFFER], [FATOR_LT], [TIPO_CANAL], 
 [ID_MODELAGEM2], [ERP_GRUPO_MERCADORIA], [ERP_TIPO_ETIQUETA], [ERP_DATA_ULTIMO_AGENDAMENTO], [TITULO_B2C], [DESCRICAO_B2C], [PRE_VENDA], [TAGS], [VIDEO_EMBED], 
 [CARACTERISTICAS_TECNICAS_B2C], [FRETE_GRATIS], [ESTOQUE_MINIMO], [DATA_PUBLICACAO_B2C], [GRUPO_PRODUTO_B2C], [SUBGRUPO_PRODUTO_B2C], [TIPO_PRODUTO_B2C], 
 [GRIFFE_B2C], [LINHA_B2C], [FABRICANTE_B2C], [CATEGORIA_B2C], [SUBCATEGORIA_B2C], [REPOSICAO_B2C], [IMG_ESTILO], [DESCRICAO_B2C_2], [DESCRICAO_B2C_3], 
 [ERP_MATERIA_PRIMA]
 from prod.caedu.dbo.produtos
 where produto = '53040199'
 go

 insert into produto_CORES
 ([PRODUTO], [COR_PRODUTO], [SIMILAR], [DESC_COR_PRODUTO], [SORTIMENTO_COR], [COR_SORTIDA], [STATUS_VENDA_ATUAL], [INICIO_VENDAS], [FIM_VENDAS], 
[COR_FABRICANTE], [TIPO_LAVAGEM_TINTURARIA], [TINTURARIA_LAVAGEM], [COR], [MATERIAL], [COR_MATERIAL], [ETIQUETA], [CUSTO_REPOSICAO1], [CUSTO_REPOSICAO2], 
[CUSTO_REPOSICAO3], [CUSTO_REPOSICAO4], [VARIANTE_TAMANHO], [DATA_PARA_TRANSFERENCIA], [PRECO_REPOSICAO_1], [PRECO_REPOSICAO_2], 
[PRECO_REPOSICAO_3], [PRECO_REPOSICAO_4], [PRECO_A_VISTA_REPOSICAO_1], [PRECO_A_VISTA_REPOSICAO_2], [PRECO_A_VISTA_REPOSICAO_3], [PRECO_A_VISTA_REPOSICAO_4], 
[CLASSIF_FISCAL], [COMPOSICAO], [TRIBUT_ORIGEM], [LX_STATUS_REGISTRO]
 )
SELECT 
[PRODUTO], [COR_PRODUTO], [SIMILAR], [DESC_COR_PRODUTO], [SORTIMENTO_COR], [COR_SORTIDA], [STATUS_VENDA_ATUAL], [INICIO_VENDAS], [FIM_VENDAS], 
[COR_FABRICANTE], [TIPO_LAVAGEM_TINTURARIA], [TINTURARIA_LAVAGEM], [COR], [MATERIAL], [COR_MATERIAL], [ETIQUETA], [CUSTO_REPOSICAO1], [CUSTO_REPOSICAO2], 
[CUSTO_REPOSICAO3], [CUSTO_REPOSICAO4],  [VARIANTE_TAMANHO], [DATA_PARA_TRANSFERENCIA], [PRECO_REPOSICAO_1], [PRECO_REPOSICAO_2], 
[PRECO_REPOSICAO_3], [PRECO_REPOSICAO_4], [PRECO_A_VISTA_REPOSICAO_1], [PRECO_A_VISTA_REPOSICAO_2], [PRECO_A_VISTA_REPOSICAO_3], [PRECO_A_VISTA_REPOSICAO_4], 
[CLASSIF_FISCAL], [COMPOSICAO], [TRIBUT_ORIGEM], [LX_STATUS_REGISTRO]
FROM prod.caedu.dbo.produto_CORES
where produto = '53040199'
go

insert into PRODUTOS_BARRA
([CODIGO_BARRA], [PRODUTO], [COR_PRODUTO], [TAMANHO], [GRADE], [DATA_PARA_TRANSFERENCIA], [NOME_CLIFOR], [CODIGO_BARRA_PADRAO], 
[INATIVO], [TIPO_COD_BAR], [LX_STATUS_REGISTRO], [ID_SKU], [LX_HASH]
)
select 
[CODIGO_BARRA], [PRODUTO], [COR_PRODUTO], [TAMANHO], [GRADE], [DATA_PARA_TRANSFERENCIA], [NOME_CLIFOR], [CODIGO_BARRA_PADRAO], 
[INATIVO], [TIPO_COD_BAR], [LX_STATUS_REGISTRO], [ID_SKU], [LX_HASH]
FROM prod.caedu.dbo.produtos_barra
where produto = '53040199'
go

insert into PRODUTOS_PACKS_PERMITIDOS
([PRODUTO], [PACK], [QTDE], [Q1], [Q2], [Q3], [Q4], [Q5], [Q6], [Q7], [Q8], [Q9], [Q10], [Q11], [Q12], [Q13], [Q14], [Q15], [Q16], 
[Q17], [Q18], [Q19], [Q20], [Q21], [Q22], [Q23], [Q24], [Q25], [Q26], [Q27], [Q28], [Q29], [Q30], [Q31], [Q32], [Q33], [Q34], 
[Q35], [Q36], [Q37], [Q38], [Q39], [Q40], [Q41], [Q42], [Q43], [Q44], [Q45], [Q46], [Q47], [Q48], [DATA_PARA_TRANSFERENCIA], 
[COR_PRODUTO], [INDICA_PACK_COR], [INATIVO]
)
select 
[PRODUTO], [PACK], [QTDE], [Q1], [Q2], [Q3], [Q4], [Q5], [Q6], [Q7], [Q8], [Q9], [Q10], [Q11], [Q12], [Q13], [Q14], [Q15], [Q16], 
[Q17], [Q18], [Q19], [Q20], [Q21], [Q22], [Q23], [Q24], [Q25], [Q26], [Q27], [Q28], [Q29], [Q30], [Q31], [Q32], [Q33], [Q34], 
[Q35], [Q36], [Q37], [Q38], [Q39], [Q40], [Q41], [Q42], [Q43], [Q44], [Q45], [Q46], [Q47], [Q48], [DATA_PARA_TRANSFERENCIA], 
[COR_PRODUTO], [INDICA_PACK_COR], [INATIVO]
from prod.caedu.dbo.PRODUTOS_PACKS_PERMITIDOS
where produto = '53040199'
go

insert into produtos_precos (
[CODIGO_TAB_PRECO], [PRODUTO], [PRECO1], [PRECO2], [PRECO3], [PRECO4], [LIMITE_DESCONTO], [PROMOCAO_DESCONTO], [ULT_ATUALIZACAO], 
[INICIO_PROMOCAO], [FIM_PROMOCAO], [DATA_PARA_TRANSFERENCIA], [MARK_UP_PREVISTO], [PROMOCAO_ATACADO], [PRECO_LIQUIDO1], [PRECO_LIQUIDO2], 
[PRECO_LIQUIDO3], [PRECO_LIQUIDO4], [LX_STATUS_REGISTRO], [PRECO1_ANTERIOR], [DATA_CARGA_PRECOS], [LX_HASH])
select 
A.[CODIGO_TAB_PRECO], [PRODUTO], [PRECO1], [PRECO2], [PRECO3], [PRECO4], [LIMITE_DESCONTO], [PROMOCAO_DESCONTO], [ULT_ATUALIZACAO], 
[INICIO_PROMOCAO], [FIM_PROMOCAO], A.[DATA_PARA_TRANSFERENCIA], [MARK_UP_PREVISTO], [PROMOCAO_ATACADO], [PRECO_LIQUIDO1], [PRECO_LIQUIDO2], 
[PRECO_LIQUIDO3], [PRECO_LIQUIDO4], A.[LX_STATUS_REGISTRO], [PRECO1_ANTERIOR], [DATA_CARGA_PRECOS], [LX_HASH]
from prod.caedu.dbo.PRODUTOS_PRECOS A
INNER JOIN TABELAS_PRECO ON TABELAS_PRECO.CODIGO_TAB_PRECO = A.CODIGO_TAB_PRECO
where produto = '53040199'
GO

insert into compras 
([PEDIDO], [FORNECEDOR], [FILIAL_A_ENTREGAR], [FILIAL_COBRANCA], [FILIAL_A_FATURAR], [CONDICAO_PGTO], [TRANSPORTADORA], [MOEDA], [COD_TRANSACAO], [EMISSAO], [CADASTRAMENTO], [APROVADO_POR], [PEDIDO_FORNECEDOR], [DESCONTO], [ENCARGO], [VALOR_IPI], [FRETE_A_PAGAR], [TOT_QTDE_ORIGINAL], [TOT_QTDE_ENTREGAR], [TOT_VALOR_ORIGINAL], [TOT_VALOR_ENTREGAR], [CTRL_MULT_ENTREGAS], [TABELA_FILHA], [ENTREGA_ACEITAVEL], [OBS], [REQUERIDO_POR], [TIPO_COMPRA], [PROGRAMACAO], [STATUS_APROVACAO], [DATA_APROVACAO], [ORIGEM_DA_COMPRA], [STATUS_COMPRA], [PEDIDO_VENDA], [COMPRIMENTO_DE_ROLOS], [TOT_VALOR_DESPESA], [MARCA_VOLUMES], [APROVADOR_POR],  [RATEIO_CENTRO_CUSTO], [RATEIO_FILIAL], [DATA_FATURAMENTO_RELATIVO], [NATUREZA_ENTRADA], [NATUREZA], [ID_ASSINATURA_DOCUMENTO], [DATA_PARA_TRANSFERENCIA], [PEDIDO_COMPRA_ORIGEM], [CAEDU_DATA_ENTREGA_ORIGINAL], [LX_STATUS_COMPRA], [QUANTIDADE_AGENDAMENTO], [QUANTIDADE_CANCELAMENTO], [CAEDU_DATA_OTB], [STATUS_CQ], [MOTIVO_CQ], [ERP_CONFERENCIA_PACKS], [ERP_CAB_COD_CABIDE], [ERP_CAB_CD_ENTREGA], [ERP_CAB_ENCABIDADO], [ERP_CAB_STATUS], [ERP_CAB_LOCALIZACAO], [ERP_CAB_QTDPECAS], [ERP_CAB_TIPO_PEDIDO], [ERP_CAB_DATA_ENVIO], [ERP_FOLLOW_UP_MARGEM], [OBJETO_ID], [ERP_CUPS_TIPO_PEDIDO], [ERP_CUPS_SEGMENTO], [ERP_CUPS_DATA_ACORDADA], [ERP_CUPS_PECA_MOSTRUARIO], [ERP_CUPS_EMBARQUE_ATUAL], [ERP_CUPS_EMBARQUE_REAL], [ERP_CUPS_CONTRATO], [ERP_CUPS_CHEGADA_PORTO], [ERP_CUPS_CHEGADA_CD], [ERP_CUPS_PROCESSO_CCF_CCA], [ERP_CUPS_EMBARQUE_LIBERADO], [ERP_CUPS_SEQ_PRODUTO], [ERP_CUPS_INCOTERM], [ERP_CUPS_ID_CONTRATO], [ERP_IMP_NUM_FATURA], [ERP_IMP_COD_PROCESSO], [ERP_IMP_TIPO_IMPORTACAO], [ERP_PERCENT_VERBAS], [BLOQ_EMBARQUE], [ERP_EBS_CTRL_PAGTO_PARCELA], [ERP_EBS_VLR_SISCOMEX], [ERP_EBS_VLR_CUSTO_FOB_DI], [ERP_EBS_VLR_TAXA_DI], [ERP_EBS_VLR_TAXA_BL], [ERP_IMPORTADO], [ERP_MOEDA], [ERP_TOTAL_QTD_DISTRIB], [ERP_PERCENT_DISTRIB], [ERP_TOTAL_CAIXAS_ORIGINAL], [ERP_PACK_RESTO], [CTB_TIPO_OPERACAO], [DESC_TIPO_OPERACAO], [GERAR_WF], [CHAVE_PROCESSO_SE], [ERP_DISTRIBUICAO], [ERP_MANUAL], [ERP_LIBERADO_CQ], [ERP_FATURADO], [ERP_CAB_OPCAO], [ERP_CAB_COD_BOLACHA], [ERP_UNOUS_DATA_ENVIO])

select [PEDIDO], [FORNECEDOR], [FILIAL_A_ENTREGAR], [FILIAL_COBRANCA], [FILIAL_A_FATURAR], [CONDICAO_PGTO], [TRANSPORTADORA], 
[MOEDA], [COD_TRANSACAO], [EMISSAO], [CADASTRAMENTO], [APROVADO_POR], [PEDIDO_FORNECEDOR], [DESCONTO], [ENCARGO], [VALOR_IPI], 
[FRETE_A_PAGAR], [TOT_QTDE_ORIGINAL], [TOT_QTDE_ENTREGAR], [TOT_VALOR_ORIGINAL], [TOT_VALOR_ENTREGAR], [CTRL_MULT_ENTREGAS], 
[TABELA_FILHA], [ENTREGA_ACEITAVEL], [OBS], [REQUERIDO_POR], [TIPO_COMPRA], [PROGRAMACAO], [STATUS_APROVACAO], [DATA_APROVACAO], 
[ORIGEM_DA_COMPRA], [STATUS_COMPRA], [PEDIDO_VENDA], [COMPRIMENTO_DE_ROLOS], [TOT_VALOR_DESPESA], [MARCA_VOLUMES], [APROVADOR_POR], 
 [RATEIO_CENTRO_CUSTO], [RATEIO_FILIAL], [DATA_FATURAMENTO_RELATIVO], [NATUREZA_ENTRADA], [NATUREZA], 
[ID_ASSINATURA_DOCUMENTO], [DATA_PARA_TRANSFERENCIA], [PEDIDO_COMPRA_ORIGEM], [CAEDU_DATA_ENTREGA_ORIGINAL], [LX_STATUS_COMPRA], 
[QUANTIDADE_AGENDAMENTO], [QUANTIDADE_CANCELAMENTO], [CAEDU_DATA_OTB], [STATUS_CQ], [MOTIVO_CQ], [ERP_CONFERENCIA_PACKS], [ERP_CAB_COD_CABIDE], 
[ERP_CAB_CD_ENTREGA], [ERP_CAB_ENCABIDADO], [ERP_CAB_STATUS], [ERP_CAB_LOCALIZACAO], [ERP_CAB_QTDPECAS], [ERP_CAB_TIPO_PEDIDO], [ERP_CAB_DATA_ENVIO], 
[ERP_FOLLOW_UP_MARGEM], [OBJETO_ID], [ERP_CUPS_TIPO_PEDIDO], [ERP_CUPS_SEGMENTO], [ERP_CUPS_DATA_ACORDADA], [ERP_CUPS_PECA_MOSTRUARIO], 
[ERP_CUPS_EMBARQUE_ATUAL], [ERP_CUPS_EMBARQUE_REAL], [ERP_CUPS_CONTRATO], [ERP_CUPS_CHEGADA_PORTO], [ERP_CUPS_CHEGADA_CD], 
[ERP_CUPS_PROCESSO_CCF_CCA], [ERP_CUPS_EMBARQUE_LIBERADO], [ERP_CUPS_SEQ_PRODUTO], [ERP_CUPS_INCOTERM], [ERP_CUPS_ID_CONTRATO], 
[ERP_IMP_NUM_FATURA], [ERP_IMP_COD_PROCESSO], [ERP_IMP_TIPO_IMPORTACAO], [ERP_PERCENT_VERBAS], [BLOQ_EMBARQUE], [ERP_EBS_CTRL_PAGTO_PARCELA], 
[ERP_EBS_VLR_SISCOMEX], [ERP_EBS_VLR_CUSTO_FOB_DI], [ERP_EBS_VLR_TAXA_DI], [ERP_EBS_VLR_TAXA_BL], [ERP_IMPORTADO], [ERP_MOEDA], [ERP_TOTAL_QTD_DISTRIB], 
[ERP_PERCENT_DISTRIB], [ERP_TOTAL_CAIXAS_ORIGINAL], [ERP_PACK_RESTO], [CTB_TIPO_OPERACAO], [DESC_TIPO_OPERACAO], [GERAR_WF], 
[CHAVE_PROCESSO_SE], [ERP_DISTRIBUICAO], [ERP_MANUAL], [ERP_LIBERADO_CQ], [ERP_FATURADO], [ERP_CAB_OPCAO], [ERP_CAB_COD_BOLACHA], 
[ERP_UNOUS_DATA_ENVIO]
from prod.caedu.dbo.compras where pedido = '237327'

select * from
 prod.caedu.dbo.compras_produto where pedido = '237327'

INSERT INTO COMPRAS_PRODUTO(
[PRODUTO], [PEDIDO], [ENTREGA], [COR_PRODUTO], [LIMITE_ENTREGA], [REQUISICAO], [CUSTO1], [CUSTO2], [CUSTO3], [CUSTO4], [CUSTO_MOEDA1], 
[CUSTO_MOEDA2], [CUSTO_MOEDA3], [CUSTO_MOEDA4], [QTDE_ORIGINAL], [QTDE_CANCELADA], [QTDE_ENTREGUE], [QTDE_ENTREGAR], [VALOR_ORIGINAL], 
[VALOR_ENTREGUE], [VALOR_ENTREGAR], [DESCONTO_ITEM], [IPI], [PACKS], [CO1], [CO2], [CO3], [CO4], [CO5], [CO6], [CO7], [CO8], [CO9], [CO10], 
[CO11], [CO12], [CO13], [CO14], [CO15], [CO16], [CO17], [CO18], [CO19], [CO20], [CO21], [CO22], [CO23], [CO24], [CO25], [CO26], [CO27], 
[CO28], [CO29], [CO30], [CO31], [CO32], [CO33], [CO34], [CO35], [CO36], [CO37], [CO38], [CO39], [CO40], [CO41], [CO42], [CO43], [CO44], 
[CO45], [CO46], [CO47], [CO48], [CE1], [CE2], [CE3], [CE4], [CE5], [CE6], [CE7], [CE8], [CE9], [CE10], [CE11], [CE12], [CE13], [CE14], 
[CE15], [CE16], [CE17], [CE18], [CE19], [CE20], [CE21], [CE22], [CE23], [CE24], [CE25], [CE26], [CE27], [CE28], [CE29], [CE30], [CE31], 
[CE32], [CE33], [CE34], [CE35], [CE36], [CE37], [CE38], [CE39], [CE40], [CE41], [CE42], [CE43], [CE44], [CE45], [CE46], [CE47], [CE48], 
[ENTREGUE_MOEDA_PADRAO], [CHEGADA_PREVISTA], [OBS_ITEM],  [DATA_CONFIRMACAO], [DATA_PARA_TRANSFERENCIA], [QTDE_COMPRA_RATEIO], 
[VALOR_COMPRA_RATEIO], [COD_ALOCACAO], [MULTIPLICADOR_ALOCACAO], [QUANTIDADE_AGENDAMENTO], [QUANTIDADE_CANCELAMENTO], [ERP_CUPS_PACKS_POR_CAIXA], 
[ERP_CUPS_CUSTO_FOB], [ERP_PERC_MARGEM], [ERP_CUPS_SEQUENCIA], [ERP_CUPS_CUSTO_FOB_MINIMO], [QTDE], [ERP_VERBAS_EMPENHO], [ERP_VERBAS_DATA_EMPENHO], 
[ERP_VERBAS_EMPENHO_ANO_MES], [ERP_VERBAS_STATUS_PR], [DATA_ACERTO_CONSIGNACAO], [ERP_CONJUNTO], [ERP_COR_PRODUTO2]
)
SELECT 
[PRODUTO], [PEDIDO], [ENTREGA], [COR_PRODUTO], [LIMITE_ENTREGA], [REQUISICAO], [CUSTO1], [CUSTO2], [CUSTO3], [CUSTO4], [CUSTO_MOEDA1], 
[CUSTO_MOEDA2], [CUSTO_MOEDA3], [CUSTO_MOEDA4], [QTDE_ORIGINAL], [QTDE_CANCELADA], [QTDE_ENTREGUE], [QTDE_ENTREGAR], [VALOR_ORIGINAL], 
[VALOR_ENTREGUE], [VALOR_ENTREGAR], [DESCONTO_ITEM], [IPI], [PACKS], [CO1], [CO2], [CO3], [CO4], [CO5], [CO6], [CO7], [CO8], [CO9], [CO10], 
[CO11], [CO12], [CO13], [CO14], [CO15], [CO16], [CO17], [CO18], [CO19], [CO20], [CO21], [CO22], [CO23], [CO24], [CO25], [CO26], [CO27], 
[CO28], [CO29], [CO30], [CO31], [CO32], [CO33], [CO34], [CO35], [CO36], [CO37], [CO38], [CO39], [CO40], [CO41], [CO42], [CO43], [CO44], 
[CO45], [CO46], [CO47], [CO48], [CE1], [CE2], [CE3], [CE4], [CE5], [CE6], [CE7], [CE8], [CE9], [CE10], [CE11], [CE12], [CE13], [CE14], 
[CE15], [CE16], [CE17], [CE18], [CE19], [CE20], [CE21], [CE22], [CE23], [CE24], [CE25], [CE26], [CE27], [CE28], [CE29], [CE30], [CE31], 
[CE32], [CE33], [CE34], [CE35], [CE36], [CE37], [CE38], [CE39], [CE40], [CE41], [CE42], [CE43], [CE44], [CE45], [CE46], [CE47], [CE48], 
[ENTREGUE_MOEDA_PADRAO], [CHEGADA_PREVISTA], [OBS_ITEM],  [DATA_CONFIRMACAO], [DATA_PARA_TRANSFERENCIA], [QTDE_COMPRA_RATEIO], 
[VALOR_COMPRA_RATEIO], [COD_ALOCACAO], [MULTIPLICADOR_ALOCACAO], [QUANTIDADE_AGENDAMENTO], [QUANTIDADE_CANCELAMENTO], [ERP_CUPS_PACKS_POR_CAIXA], 
[ERP_CUPS_CUSTO_FOB], [ERP_PERC_MARGEM], [ERP_CUPS_SEQUENCIA], [ERP_CUPS_CUSTO_FOB_MINIMO], [QTDE], [ERP_VERBAS_EMPENHO], [ERP_VERBAS_DATA_EMPENHO], 
[ERP_VERBAS_EMPENHO_ANO_MES], [ERP_VERBAS_STATUS_PR], [DATA_ACERTO_CONSIGNACAO], [ERP_CONJUNTO], [ERP_COR_PRODUTO2]
FROM prod.caedu.dbo.COMPRAS_PRODUTO
WHERE PEDIDO = '237327'
GO

INSERT INTO CAEDU_COMPRAS_PRODUTOS_PACKS (
[PEDIDO], [PRODUTO], [COR_PRODUTO], [DESC_COR_PRODUTO], [QTDE], [Q1], [Q2], [Q3], [Q4], [Q5], [Q6], [Q7], [Q8], [Q9], [Q10], [Q11], [Q12], 
[Q13], [Q14], [Q15], [Q16], [Q17], [Q18], [Q19], [Q20], [Q21], [Q22], [Q23], [Q24], [Q25], [Q26], [Q27], [Q28], [Q29], [Q30], [Q31], [Q32], 
[Q33], [Q34], [Q35], [Q36], [Q37], [Q38], [Q39], [Q40], [Q41], [Q42], [Q43], [Q44], [Q45], [Q46], [Q47], [Q48])
SELECT 
[PEDIDO], [PRODUTO], [COR_PRODUTO], [DESC_COR_PRODUTO], [QTDE], [Q1], [Q2], [Q3], [Q4], [Q5], [Q6], [Q7], [Q8], [Q9], [Q10], [Q11], [Q12], 
[Q13], [Q14], [Q15], [Q16], [Q17], [Q18], [Q19], [Q20], [Q21], [Q22], [Q23], [Q24], [Q25], [Q26], [Q27], [Q28], [Q29], [Q30], [Q31], [Q32], 
[Q33], [Q34], [Q35], [Q36], [Q37], [Q38], [Q39], [Q40], [Q41], [Q42], [Q43], [Q44], [Q45], [Q46], [Q47], [Q48]
FROM prod.caedu.dbo.CAEDU_COMPRAS_PRODUTOS_PACKS 
WHERE PEDIDO = '237327'
GO

INSERT INTO CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL(
[PEDIDO], [PRODUTO],  [QTDE], [Q1], [Q2], [Q3], [Q4], [Q5], [Q6], [Q7], [Q8], [Q9], [Q10], [Q11], [Q12], 
[Q13], [Q14], [Q15], [Q16], [Q17], [Q18], [Q19], [Q20], [Q21], [Q22], [Q23], [Q24], [Q25], [Q26], [Q27], [Q28], [Q29], [Q30], [Q31], [Q32], 
[Q33], [Q34], [Q35], [Q36], [Q37], [Q38], [Q39], [Q40], [Q41], [Q42], [Q43], [Q44], [Q45], [Q46], [Q47], [Q48])
SELECT 
[PEDIDO], [PRODUTO], [QTDE], [Q1], [Q2], [Q3], [Q4], [Q5], [Q6], [Q7], [Q8], [Q9], [Q10], [Q11], [Q12], 
[Q13], [Q14], [Q15], [Q16], [Q17], [Q18], [Q19], [Q20], [Q21], [Q22], [Q23], [Q24], [Q25], [Q26], [Q27], [Q28], [Q29], [Q30], [Q31], [Q32], 
[Q33], [Q34], [Q35], [Q36], [Q37], [Q38], [Q39], [Q40], [Q41], [Q42], [Q43], [Q44], [Q45], [Q46], [Q47], [Q48]
FROM prod.caedu.dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL 
WHERE PEDIDO = '237327'
GO

