/*
-- INSERIR TIPO DE COMPRA DO CADASTRO DE PEDIDO DE COMPRAS MANUALMENTE

-- SOLICITAÇAO DO USUARIO
	1ª COMPRA TODAS
	PAREDE TODAS

-- QUERY DA TELA DO PEDIDO DE COMPRA QUE TRAZ OS VALORES PARA ESCOLHER NA LISTA SUSPENSA
select  TIPO_COMPRA from COMPRAS_TIPOS where  COMPRAS_TIPOS.TIPO_COMPRA LIKE '%'  AND INDICA_COMPRA_PRODUTO='1'  

-- Roda este para listar toda a tabela de TIPO DE COMPRAS
select * from COMPRAS_TIPOS

-- roda este aqui para saber o ultimo sequencial
select * from AE_LX_DOCUMENTO
order by documento

VITRINE SECUNDARIA
VITRINE TERCIARIA
VITRINE G E GG

VITRINE SECUNDARIA G E GG

*/

-- RODA ESTE PRIMEIRO
begin tran
insert into AE_LX_DOCUMENTO 
values	(0,'VITRINE SECUNDARIA','C094',NULL,NULL,NULL,0,0,0),
		(0,'VITRINE TERCIARIA','C095',NULL,NULL,NULL,0,0,0),
		(0,'VITRINE G E GG','C096',NULL,NULL,NULL,0,0,0),
		(0,'VITRINE SECUNDARIA G E GG','C097',NULL,NULL,NULL,0,0,0)

-- RODA ESSE NA SEQUENCIA
INSERT INTO COMPRAS_TIPOS 
VALUES	('VITRINE SECUNDARIA','C094', 1,1,1,NULL),
		('VITRINE TERCIARIA','C095', 1,1,1,NULL),
		('VITRINE G E GG','C096', 1,1,1,NULL),
		('VITRINE SECUNDARIA G E GG','C097', 1,1,1,NULL)
commit


select * from compras_tipos