INSERT INTO CADASTRO_CLI_FOR (
[NOME_CLIFOR], [CARTEIRA], [BANCO], [CONTA_CONTABIL], [CLIFOR], [CGC_CPF], [RAZAO_SOCIAL], [PJ_PF], [RG_IE], [CEP], [ENDERECO], [BAIRRO], 
[CIDADE], [UF], [TELEFONE1], [PAIS], [DDI], [TELEFONE2], [FAX], [DDD1], [RAMAL1], [RAMAL2], [DDD2], [COBRANCA_ENDERECO], [COBRANCA_CIDADE], 
[COBRANCA_BAIRRO], [DDDFAX], [COBRANCA_UF], [COBRANCA_CEP], [COBRANCA_TELEFONE], [ENTREGA_ENDERECO], [ENTREGA_CIDADE], [ENTREGA_UF], 
[ENTREGA_BAIRRO], [ENTREGA_CEP], [ENTREGA_TELEFONE], [COBRANCA_DDD], [CONTATO], [COBRANCA_CGC], [CADASTRAMENTO], [COBRANCA_IE], [ANIVERSARIO], 
[INDICA_FORNECEDOR], [INDICA_CLIENTE], [IND_REPRESENTANTE], [INDICA_FILIAL], [ENTREGA_DDD], [ENTREGA_CGC], [ENTREGA_IE], [CC_AGENCIA], 
[CC_CONTA], [CC_NOME_AGENCIA], [REF_ANTERIOR], [ATUALIZACAO_EXPORTAR], [DATA_EXPORTACAO], [EMAIL], [STATUS_ENVIO], [INATIVO], 
[DATA_PARA_TRANSFERENCIA], [ENTREGA_PAIS], [COBRANCA_PAIS], [ENTREGA_DDI], [COBRANCA_DDI], [OBS_DE_FATURAMENTO], [ISENTO_IPI], 
[ISENTO_ICMS], [IRRF], [MESES_SEM_VENCIMENTO], [DATA_FIXA_PGTO], [ACEITA_AGRUPAR_FATURA], [PASSWEB], [VENCIMENTO_PASSWEB], 
[NUMERO_VIAS_FATURA], [REPORT_FATURA], [DIAS_ANTECIPACAO_PGTO], [POSSUI_RECARGO], [CODIGO_CHAVE], [TIPO_RELACAO_COMERCIAL], 
[ID_CLASIF_CLIFOR], [ENTREGA_RAZAO_SOCIAL], [COBRANCA_RAZAO_SOCIAL], [ACEITA_DIAS_FIXO], [COD_CLIFOR], [CTB_CONTA_CONTABIL], 
[INDICADOR_FISCAL_TERCEIRO], [ID_EXCECAO_GRUPO], [AGRUPAMENTO_ITENS], [CODIGO_CONTATO], [IM], [IM_ENTREGA], [IM_COBRANCA], 
[CADASTRO_CLI_FOR], [INSCRICAO_SUFRAMA], [NUMERO], [COMPLEMENTO], [COBRANCA_NUMERO], [COBRANCA_COMPLEMENTO], [ENTREGA_NUMERO], 
[ENTREGA_COMPLEMENTO], [CNAE], [INCL_AUTO_GRP_ECON], [EMAIL_NFE], [COD_MUNICIPIO_IBGE], [COD_MUNICIPIO_IBGE_ENTREGA], [COD_MUNICIPIO_IBGE_COBRANCA], 
[CODIGO_SPC], [ENVIADO_SPC], [IEST], [LX_STATUS_REGISTRO], [ERP_CLIFOR_WK], [LX_HASH], [EBS_ID_FORNECEDOR], [EBS_ID_LOCAL_FORNECEDOR], 
[EBS_ID_CLIENTE], [EBS_ID_LOCAL_CLIENTE], [TIPO_TRIBUTACAO], [INDICA_CPRB]
)
SELECT [NOME_CLIFOR], [CARTEIRA], [BANCO], [CONTA_CONTABIL], [CLIFOR], [CGC_CPF], [RAZAO_SOCIAL], [PJ_PF], [RG_IE], [CEP], [ENDERECO], [BAIRRO], 
[CIDADE], [UF], [TELEFONE1], [PAIS], [DDI], [TELEFONE2], [FAX], [DDD1], [RAMAL1], [RAMAL2], [DDD2], [COBRANCA_ENDERECO], [COBRANCA_CIDADE], 
[COBRANCA_BAIRRO], [DDDFAX], [COBRANCA_UF], [COBRANCA_CEP], [COBRANCA_TELEFONE], [ENTREGA_ENDERECO], [ENTREGA_CIDADE], [ENTREGA_UF], 
[ENTREGA_BAIRRO], [ENTREGA_CEP], [ENTREGA_TELEFONE], [COBRANCA_DDD], [CONTATO], [COBRANCA_CGC], [CADASTRAMENTO], [COBRANCA_IE], [ANIVERSARIO], 
[INDICA_FORNECEDOR], [INDICA_CLIENTE], [IND_REPRESENTANTE], [INDICA_FILIAL], [ENTREGA_DDD], [ENTREGA_CGC], [ENTREGA_IE], [CC_AGENCIA], 
[CC_CONTA], [CC_NOME_AGENCIA], [REF_ANTERIOR], [ATUALIZACAO_EXPORTAR], [DATA_EXPORTACAO], [EMAIL], [STATUS_ENVIO], [INATIVO], 
[DATA_PARA_TRANSFERENCIA], [ENTREGA_PAIS], [COBRANCA_PAIS], [ENTREGA_DDI], [COBRANCA_DDI], [OBS_DE_FATURAMENTO], [ISENTO_IPI], 
[ISENTO_ICMS], [IRRF], [MESES_SEM_VENCIMENTO], [DATA_FIXA_PGTO], [ACEITA_AGRUPAR_FATURA], [PASSWEB], [VENCIMENTO_PASSWEB], 
[NUMERO_VIAS_FATURA], [REPORT_FATURA], [DIAS_ANTECIPACAO_PGTO], [POSSUI_RECARGO], [CODIGO_CHAVE], [TIPO_RELACAO_COMERCIAL], 
[ID_CLASIF_CLIFOR], [ENTREGA_RAZAO_SOCIAL], [COBRANCA_RAZAO_SOCIAL], [ACEITA_DIAS_FIXO], [COD_CLIFOR], [CTB_CONTA_CONTABIL], 
[INDICADOR_FISCAL_TERCEIRO], [ID_EXCECAO_GRUPO], [AGRUPAMENTO_ITENS], [CODIGO_CONTATO], [IM], [IM_ENTREGA], [IM_COBRANCA], 
[CADASTRO_CLI_FOR], [INSCRICAO_SUFRAMA], [NUMERO], [COMPLEMENTO], [COBRANCA_NUMERO], [COBRANCA_COMPLEMENTO], [ENTREGA_NUMERO], 
[ENTREGA_COMPLEMENTO], [CNAE], [INCL_AUTO_GRP_ECON], [EMAIL_NFE], [COD_MUNICIPIO_IBGE], [COD_MUNICIPIO_IBGE_ENTREGA], [COD_MUNICIPIO_IBGE_COBRANCA], 
[CODIGO_SPC], [ENVIADO_SPC], [IEST], [LX_STATUS_REGISTRO], [ERP_CLIFOR_WK], [LX_HASH], [EBS_ID_FORNECEDOR], [EBS_ID_LOCAL_FORNECEDOR], 
[EBS_ID_CLIENTE], [EBS_ID_LOCAL_CLIENTE], [TIPO_TRIBUTACAO], [INDICA_CPRB]
FROM prod.caedu.dbo.CADASTRO_CLI_FOR
WHERE NOME_CLIFOR IN ('CAMPINAS - CENTRO', 'SP - LAPA' )  



SELECT * FROM FILIAIS WHERE FILIAL = 'SP - LAPA'

INSERT INTO CLIENTES_ATACADO
SELECT * FROM prod.caedu.dbo.CLIENTES_ATACADO 
WHERE CLIENTE_ATACADO = 'CAMPINAS - CENTRO'