

insert into PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,VALOR_DEFAULT,ULT_ATUALIZACAO,VALOR_ATUAL,DESC_PARAMETRO,TIPO_DADO,RANGE_VALOR_ATUAL,
GLOBAL,ESCOPO,POR_USUARIO_OK,DATA_PARA_TRANSFERENCIA,NOTA_PROGRAMADOR,PERMITE_POR_EMPRESA,ENVIA_PARA_LOJA,PERMITE_POR_LOJA,PERMITE_POR_TERMINAL,PERMITE_ALTERAR_NA_LOJA,
PERMITE_ALTERAR_NO_TERMINAL,ENVIA_PARA_REPRESENTANTE,PERMITE_POR_REPRESENTANTE,PERMITE_ALTERAR_NO_REPRESENTANTE)
VALUES
('PALMA_IGNORA_INTEGR_PDA',GETDATE(),'',GETDATE(),'.T.',
'INDICA SE PROC DE EXCLUSAO DE DISTRIBUICAO IGNORA INTEGRACAO PDA X LINX','L','',
0,0,1,GETDATE(),
'se o parametro for SIM, IGNORA QUANDO LINHA DE STATUS NAO EXISTIR',1,0,0,0,0,0,0,0,0)

select VALOR_ATUAL from parametros where parametro = 'PALMA_IGNORA_INTEGR_PDA'

UPDATE PARAMETROS SET VALOR_ATUAL = '.F.' where parametro = 'PALMA_IGNORA_INTEGR_PDA'
