--UPDATE COMPRAS SET STATUS_APROVACAO = 'A' WHERE PEDIDO IN
--(
--'173665-2',
--'173665-1'

--)



select * from INFO_LOJAS



SELECT * FROM LOJAS_VAREJO
SELECT * FROM PROP_LOJAS_VAREJO WHERE PROPRIEDADE = '00021'


SELECT * FROM PROP_LOJAS_VAREJO
where codigo_filial = '000131'

INNER JOIN PROP_LOJAS_VAREJO D ON C.CODIGO_FILIAL = D.CODIGO_FILIAL AND D.PROPRIEDADE  = '00021' 



INSERT INTO PROP_LOJAS_VAREJO (PROPRIEDADE, CODIGO_FILIAL, ITEM_PROPRIEDADE, VALOR_PROPRIEDADE, DATA_PARA_TRANSFERENCIA)
VALUES ('00021', '000097', '1', 'R3 - SIMONE', GETDATE()),
		('00021', '000098', '1', 'R3 - SIMONE', GETDATE())



INSERT INTO INFO_LOJAS
(IP,LOJA,CODIGO_FILIAL,CODIGO_PRECO,BANCO,VENDA,ATIVO, INSTANCIA, ABV,COLLATION)
VALUES
('192.168.0.55','OSASCO CENTRO','000098','98','CAEDU','VENDA_OSASCO_CENTRO',1, '', 'OSC','SQL_Latin1_General_CP1_CI_AS'),
('192.168.0.55','SOROCABA','000097','97','CAEDU','VENDA_SOROCABA',1, '', 'SCB','SQL_Latin1_General_CP1_CI_AS')


select * from INFO_LOJAS where codigo_filial = '000131'

SELECT * FROM FILIAIS WHERE COD_FILIAL='000131'
INSERT INTO INFO_LOJAS
(IP,LOJA,CODIGO_FILIAL,CODIGO_PRECO,BANCO,VENDA,ATIVO, INSTANCIA, ABV,COLLATION)
VALUES
('192.168.0.55','SP - SAO BENTO','000131','77','CAEDU','VENDA_SP_SAO_BENTO',1, '', 'SB','SQL_Latin1_General_CP1_CI_AS')

SELECT * FROM TABELAS_PRECO WHERE CODIGO_TAB_PRECO='77'