/*prod*/
DECLARE @TABELA VARCHAR(50)='ENTRADAS'
--select *
--FROM SYSCOLUMNS SC
--INNER JOIN SYSOBJECTS SO ON SO.ID=SC.ID
--WHERE SO.TYPE='U' 
--AND SO.name=@TABELA

SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH AS Tamanho,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = @TABELA
  AND TABLE_SCHEMA = 'dbo';
