SELECT W_CM_CONSULTA_RESUMO_CONTABIL.COD_CUSTO_MEDIO,
       W_CM_CONSULTA_RESUMO_CONTABIL.FILIAL,
       W_CM_CONSULTA_RESUMO_CONTABIL.DATA_SALDO,
       W_CM_CONSULTA_RESUMO_CONTABIL.ENTRADA_SAIDA,
       W_CM_CONSULTA_RESUMO_CONTABIL.CONTA_CONTABIL_ESTOQUE,
       W_CM_CONSULTA_RESUMO_CONTABIL.DESC_CONTA_ESTOQUE,
       W_CM_CONSULTA_RESUMO_CONTABIL.CONTA_CONTABIL,
       W_CM_CONSULTA_RESUMO_CONTABIL.DESC_CONTA,
       W_CM_CONSULTA_RESUMO_CONTABIL.VALOR_ACUMULADO,
       W_CM_CONSULTA_RESUMO_CONTABIL.ITEM_COMPOSICAO,
       W_CM_CONSULTA_RESUMO_CONTABIL.DESC_ITEM_COMPOSICAO,
       W_CM_CONSULTA_RESUMO_CONTABIL.RATEIO_FILIAL,
       W_CM_CONSULTA_RESUMO_CONTABIL.DESC_RATEIO_FILIAL,
       W_CM_CONSULTA_RESUMO_CONTABIL.RATEIO_CENTRO_CUSTO,
       W_CM_CONSULTA_RESUMO_CONTABIL.DESC_RATEIO_CENTRO_CUSTO,
       FILIAIS.MATRIZ AS FILIAL_MATRIZ_CONTABIL,
       FILIAIS.MATRIZ_FISCAL AS FILIAL_MATRIZ_FISCAL,
       W_CM_CONSULTA_RESUMO_CONTABIL.LANCAMENTO_PADRAO,
       W_CM_CONSULTA_RESUMO_CONTABIL.DESC_LANCAMENTO_PADRAO,
       FILIAIS.COD_FILIAL,
       W_CM_CONSULTA_RESUMO_CONTABIL.TIPO_ITEM,
       W_CM_CONSULTA_RESUMO_CONTABIL.NIVEL_SEMI_ACABADO
FROM W_CM_CONSULTA_RESUMO_CONTABIL
LEFT JOIN FILIAIS ON W_CM_CONSULTA_RESUMO_CONTABIL.FILIAL = FILIAIS.FILIAL
WHERE W_CM_CONSULTA_RESUMO_CONTABIL.COD_CUSTO_MEDIO = '201903'
ORDER BY W_CM_CONSULTA_RESUMO_CONTABIL.DATA_SALDO,
         W_CM_CONSULTA_RESUMO_CONTABIL.CONTA_CONTABIL_ESTOQUE,
         W_CM_CONSULTA_RESUMO_CONTABIL.ITEM_COMPOSICAO,
         W_CM_CONSULTA_RESUMO_CONTABIL.CONTA_CONTABIL