select  
DESC_COLECAO,
FORNECEDOR,
A.PRODUTO,
PRECO1,
A.QUANTIDADE AS QTDE_ENTREGAR,
B.GRADE,
COR_PRODUTO,
DESC_COR_PRODUTO,
A.TAMANHO,
DESC_PRODUTO,
CODIGO_BARRA,
LINHA,
TIPO_PRODUTO,
ENTREGA,
DESCRICAO_MSG, 
GRUPO_PRODUTO,
ERP_AREA_JEANS,
PACKS,
A.QUANTIDADE AS QTDE_TOTAL,
ZERAR_DATA
from PDA_TB_EC_PEDIDO_ITEM A 
inner join (
SELECT 
	C.DESC_COLECAO	AS [DESC_COLECAO],
	P.FABRICANTE	AS [FORNECEDOR],
	P.PRODUTO		AS [PRODUTO],
	PP.PRECO1		AS [PRECO1],
	CAST(0 AS INT)	AS [QTDE_ENTREGAR],
	P.GRADE			AS [GRADE],
	PB.COR_PRODUTO	AS [COR_PRODUTO],
	PC.DESC_COR_PRODUTO AS [DESC_COR_PRODUTO],
	PB.TAMANHO		AS [TAMANHO],
	P.DESC_PRODUTO	AS [DESC_PRODUTO],
	PB.CODIGO_BARRA AS [CODIGO_BARRA],
	P.LINHA			AS [LINHA],
	P.TIPO_PRODUTO	AS [TIPO_PRODUTO],
	SPACE(10)		AS [ENTREGA],
	SPACE(50)		AS [DESCRICAO_MSG], 
	P.GRUPO_PRODUTO AS [GRUPO_PRODUTO],
	P.ERP_AREA_JEANS AS [ERP_AREA_JEANS],
	'A'				AS [PACKS],
	CAST(0 AS INT)	AS [QTDE_TOTAL],
	SPACE(3) AS [ZERAR_DATA]
FROM CAEDU.DBO.PRODUTOS P
INNER JOIN CAEDU.DBO.COLECOES C ON C.COLECAO = P.COLECAO
INNER JOIN CAEDU.DBO.PRODUTOS_PRECOS PP 
			ON PP.PRODUTO=P.PRODUTO AND PP.CODIGO_TAB_PRECO='01'
INNER JOIN CAEDU.DBO.PRODUTOS_BARRA PB ON PB.PRODUTO = P.PRODUTO
INNER JOIN CAEDU.DBO.PRODUTO_CORES PC 
			ON PC.PRODUTO=PB.PRODUTO AND PC.COR_PRODUTO=PB.COR_PRODUTO
INNER JOIN CAEDU.DBO.PRODUTOS_LINHAS PL ON PL.LINHA=P.LINHA
) B ON B.PRODUTO = A.PRODUTO collate Latin1_General_CI_AS
AND B.COR_PRODUTO = A.COR collate Latin1_General_CI_AS
AND B.TAMANHO = A.TAMANHO

--INNER JOIN CAEDU.DBO.PRODUTOS B  ON B.PRODUTO = A.PRODUTO collate Latin1_General_CI_AS
--LEFT JOIN CAEDU.DBO.COLECOES C ON C.COLECAO = B.COLECAO
--LEFT JOIN CAEDU.DBO.PRODUTOS_PRECOS PP 
--			ON PP.PRODUTO = B.PRODUTO AND PP.CODIGO_TAB_PRECO='01' 
----LEFT JOIN CAEDU.DBO.PRODUTOS_BARRA PB 
----			ON PB.PRODUTO = B.PRODUTO 
----				AND PB.COR_PRODUTO=A.COR AND PB.TAMANHO=A.TAMANHO collate SQL_Latin1_General_CP1_CI_AS
where A.ID_PEDIDO = '401467'

/*
SELECT 
	C.DESC_COLECAO	AS [DESC_COLECAO],
	P.FABRICANTE	AS [FORNECEDOR],
	P.PRODUTO		AS [PRODUTO],
	PP.PRECO1		AS [PRECO1],
	CAST(0 AS INT)	AS [QTDE_ENTREGAR],
	P.GRADE			AS [GRADE],
	PB.COR_PRODUTO	AS [COR_PRODUTO],
	PC.DESC_COR_PRODUTO AS [DESC_COR_PRODUTO],
	PB.TAMANHO		AS [TAMANHO],
	P.DESC_PRODUTO	AS [DESC_PRODUTO],
	PB.CODIGO_BARRA AS [CODIGO_BARRA],
	P.LINHA			AS [LINHA],
	P.TIPO_PRODUTO	AS [TIPO_PRODUTO],
	SPACE(10)		AS [ENTREGA],
	SPACE(50)		AS [DESCRICAO_MSG], 
	P.GRUPO_PRODUTO AS [GRUPO_PRODUTO],
	P.ERP_AREA_JEANS AS [ERP_AREA_JEANS],
	'A'				AS [PACKS],
	CAST(0 AS INT)	AS [QTDE_TOTAL],
	SPACE(3) AS [ZERAR_DATA]
FROM CAEDU.DBO.PRODUTOS P
INNER JOIN CAEDU.DBO.COLECOES C ON C.COLECAO = P.COLECAO
INNER JOIN CAEDU.DBO.PRODUTOS_PRECOS PP 
			ON PP.PRODUTO=P.PRODUTO AND PP.CODIGO_TAB_PRECO='01'
INNER JOIN CAEDU.DBO.PRODUTOS_BARRA PB ON PB.PRODUTO = P.PRODUTO
INNER JOIN CAEDU.DBO.PRODUTO_CORES PC 
			ON PC.PRODUTO=PB.PRODUTO AND PC.COR_PRODUTO=PB.COR_PRODUTO
INNER JOIN CAEDU.DBO.PRODUTOS_LINHAS PL ON PL.LINHA=P.LINHA
WHERE P.PRODUTO = '51180101'




/*
SELECT @REGISTRO= LTRIM(RTRIM(DESC_COLECAO))+','+LTRIM(RTRIM(FORNECEDOR))+
','+LTRIM(RTRIM(@PEDIDO))+','+LTRIM(RTRIM(@PRODUTO))+','+CONVERT(VARCHAR,PRECO1)+','
		+CONVERT(VARCHAR,CONVERT(INTEGER,QTDE_ENTREGAR))+','
		+LTRIM(RTRIM(GRADE))+','+LTRIM(RTRIM(DESC_COR_PRODUTO))+','
		+LTRIM(RTRIM(TAMANHO))+','+LTRIM(RTRIM(DESC_PRODUTO))+','+
		LTRIM(RTRIM(CODIGO_BARRA))+','+LTRIM(RTRIM(@DESC_LINHA))+','
		+LTRIM(RTRIM(TIPO_PRODUTO))+','+LTRIM(RTRIM(ENTREGA))+','
		+LTRIM(RTRIM(DESCRICAO_MSG))+','
		+@DESC_LINHA+','+LTRIM(RTRIM(PACKS))+','+CONVERT(VARCHAR,QTDE_TOTAL)
		FROM @TABELASAIDA WHERE REGN = @I
*/

select * from caedu.dbo.compras_produto 
where produto collate Latin1_General_CI_AS in  (
select  produto 
from PDA_TB_EC_PEDIDO_ITEM 
where ID_PEDIDO = '401467'
) 
order by produto, COR_PRODUTO


select * from caedu.dbo.produtos_precos where codigo_tab_preco = '01'



select  * 
from PDA_TB_EC_PEDIDO_ITEM 
where ID_PEDIDO = '401467'


exec caedu.dbo.CAE_LX_TXT_ETIQUETA_FORNECEDOR '310483V', '01'
*/