--select * from caedu_lista_combo where desc_dominio='EVENTO'

SELECT P.COLECAO, C.DESC_COLECAO, ERP_CUPS_EVENTO, A.descricao
DESC_PRODUTO, PRODUTO, ETIQUETA=RTRIM(C.DESC_COLECAO)+'-'+RTRIM(A.descricao), OCUPA=LEN(RTRIM(C.DESC_COLECAO)+'-'+RTRIM(A.descricao))
FROM PRODUTOS P
INNER JOIN COLECOES C ON C.COLECAO=P.COLECAO
INNER JOIN caedu_lista_combo A ON A.codigo=P.ERP_CUPS_EVENTO AND A.id_dominio='001'
WHERE DATA_CADASTRAMENTO > '20230401' AND FABRICANTE='KOMPORT'


SELECT * FROM COLECOES ORDER BY 2