USE [CAEDU]
GO

/****** Object:  StoredProcedure [dbo].[PLM_IRIS_Umode_INS_PRODUTO_CORES]    Script Date: 14/06/2023 15:15:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [dbo].[PLM_IRIS_Umode_INS_PRODUTO_CORES]
@codigo_produto varchar(100),
@val_ins varchar(2000),
@debug int,
@retproc varchar(100) output
AS
begin

DECLARE @SQL varchar(8000);
declare @retorno int;

Set @retproc = 'NOK';

if exists (select 1 from PRODUTO_CORES where produto = @codigo_produto)
begin
	delete from PRODUTO_CORES where produto = @codigo_produto
end

set @SQL = 'INSERT INTO [CAEDU].[DBO].PRODUTO_CORES (PRODUTO,COR_PRODUTO,SIMILAR,DESC_COR_PRODUTO,STATUS_VENDA_ATUAL,INICIO_VENDAS,FIM_VENDAS,TIPO_LAVAGEM_TINTURARIA,COR,MATERIAL,COR_MATERIAL,ETIQUETA,VARIANTE_TAMANHO,CLASSIF_FISCAL,COMPOSICAO,TRIBUT_ORIGEM,LX_HASH,CUSTO_REPOSICAO1,PRECO_REPOSICAO_1,PRECO_A_VISTA_REPOSICAO_1) '
set @SQL = @SQL + 'VALUES (' + @val_ins + ')';

	print @sql;

	IF @debug > 0
		SELECT @sql;

	EXEC (@SQL);

Set @retproc = 'OK';
	
return @retorno;

end;
GO

USE [CAEDU]
GO

/****** Object:  StoredProcedure [dbo].[PLM_IRIS_Umode_INS_PRODUTO_v2]    Script Date: 14/06/2023 15:15:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [dbo].[PLM_IRIS_Umode_INS_PRODUTO_v2] 
@codigo_produto varchar(100),
@val_ins varchar(2000),
@debug int,
@retproc varchar(100) output
AS
begin

DECLARE @SQL varchar(8000);
declare @retorno int;

set @SQL = 'INSERT INTO [CAEDU].[DBO].PRODUTOS (PRODUTO,ERP_CODIGO_UMODE,CLASSIF_FISCAL,TIPO_PRODUTO,TABELA_MEDIDAS,DESC_PRODUTO,GRUPO_PRODUTO,SUBGRUPO_PRODUTO,COLECAO,GRADE,DESC_PROD_NF,LINHA,GRIFFE,UNIDADE,PESO,REVENDA,ESTILISTA,INATIVO,ENVIA_LOJA_VAREJO,ENVIA_LOJA_ATACADO,ENVIA_VAREJO_INTERNET,PONTEIRO_PRECO_TAM,CODIGO_PRECO,MATERIAL,PERIODO_PCP,TABELA_OPERACOES,FATOR_OPERACOES,CARTELA,REFER_FABRICANTE,MODELAGEM,FABRICANTE,CUSTO_REPOSICAO1,CUSTO_REPOSICAO2,CUSTO_REPOSICAO3,CUSTO_REPOSICAO4,DATA_REPOSICAO,MODELISTA,TAMANHO_BASE,GIRO_ENTREGA,MODELO,REDE_LOJAS,DATA_PARA_TRANSFERENCIA,FABRICANTE_ICMS_ABATER,FABRICANTE_PRAZO_PGTO,TAXA_JUROS_DEFLACIONAR,TAXAS_IMPOSTOS_APLICAR,PRECO_REPOSICAO_1,PRECO_REPOSICAO_2,PRECO_REPOSICAO_3,PRECO_REPOSICAO_4,PRECO_A_VISTA_REPOSICAO_1,PRECO_A_VISTA_REPOSICAO_2,PRECO_A_VISTA_REPOSICAO_3,PRECO_A_VISTA_REPOSICAO_4,FABRICANTE_FRETE,DROP_DE_TAMANHOS,DATA_CADASTRAMENTO,STATUS_PRODUTO,TIPO_STATUS_PRODUTO,OBS,COMPOSICAO,RESTRICAO_LAVAGEM,EMPRESA,ORCAMENTO,CLIENTE_DO_PRODUTO,CONTA_CONTABIL,ESPESSURA,ALTURA,LARGURA,COMPRIMENTO,EMPILHAMENTO_MAXIMO,SEXO_TIPO,PARTE_TIPO,VERSAO_FICHA,COD_FLUXO_PRODUTO,DATA_INICIO_DESENVOLVIMENTO,INDICADOR_CFOP,MONTAGEM_KIT,MRP_AGRUPAR_NECESSIDADE_DIAS,MRP_AGRUPAR_NECESSIDADE_TIPO,MRP_DIAS_SEGURANCA,MRP_EMISSAO_LIBERACAO_DIAS,MRP_ENTREGA_GIRO_DIAS,MRP_PARTICIPANTE,MRP_MAIOR_GIRO_MP_DIAS,OP_QTDE_MAXIMA,OP_QTDE_MINIMA,QUALIDADE,SEMI_ACABADO,CONTA_CONTABIL_COMPRA,CONTA_CONTABIL_VENDA,CONTA_CONTABIL_DEV_COMPRA,CONTA_CONTABIL_DEV_VENDA,ID_EXCECAO_GRUPO,ID_EXCECAO_IMPOSTO,DIAS_COMPRA,FATOR_P,FATOR_Q,FATOR_F,CONTINUIDADE,COD_CATEGORIA,COD_SUBCATEGORIA,COD_PRODUTO_SOLUCAO,COD_PRODUTO_SEGMENTO,TIPO_ITEM_SPED,ID_PRECO,NATUREZA_RECEITA,COD_ALIQUOTA_PIS_COFINS_DIF,DATA_LIMITE_PEDIDO,ERP_CUPS_SEGMENTO,ERP_CUPS_STYLENUMBER,ERP_CUPS_EVENTO,ERP_CUPS_TEMA,ERP_CUPS_COMPRIMENTO,ERP_CUPS_CONTRUCAO,ERP_CUPS_COMPOSICAO,ERP_CUPS_FORRO,ERP_CUPS_PRODUTO,ERP_CUPS_SUPPLIER,ERP_CUPS_PRECO_CUSTO_ESTIMADO,ERP_CUPS_CODEBAR_REF,ERP_CUPS_CODEBAR_PB,ERP_CUPS_CODEBAR_CX,ERP_CUPS_BLOQUEIA_PRODUTO,ERP_CUPS_CONJUNTO,ERP_CUPS_COMPRIMENTO_BOTTOM,ERP_CUPS_COMPOSICAO_BOTTOM,ERP_CUPS_FORRO_BOTTOM,ERP_CUPS_SUBGRUPO_ATACADO,ID_ARTIGO,SPED_DATA_FIM,SPED_DATA_INI,ID_CEST_NCM,ERP_QTD_PACK,ERP_CUPS_CUSTO_FOB_MINIMO,ERP_DESC_LICENCIADO,ERP_TEMA_LICENCIADO,ID_MODELAGEM,ERP_USERS_ALTERA_PACK,FATOR_A,FATOR_B,FATOR_BUFFER,FATOR_LT,TIPO_CANAL,ID_MODELAGEM2,ERP_GRUPO_MERCADORIA,ERP_TIPO_ETIQUETA,ERP_DATA_ULTIMO_AGENDAMENTO,TITULO_B2C,DESCRICAO_B2C,TAGS,VIDEO_EMBED,CARACTERISTICAS_TECNICAS_B2C,ESTOQUE_MINIMO,DATA_PUBLICACAO_B2C,GRUPO_PRODUTO_B2C,SUBGRUPO_PRODUTO_B2C,TIPO_PRODUTO_B2C,GRIFFE_B2C,LINHA_B2C,FABRICANTE_B2C,CATEGORIA_B2C,SUBCATEGORIA_B2C,IMG_ESTILO,DESCRICAO_B2C_2,DESCRICAO_B2C_3,ERP_MATERIA_PRIMA,TRIBUT_ICMS,TRIBUT_ORIGEM,SORTIMENTO_TAMANHO,ERP_FT_MARCA,ERP_FT_DESC_MARCA,ERP_FT_REPEAT,ERP_FT_DESC_REPEAT,ERP_FT_ESTRUTURA,ERP_FT_DESC_ESTRUTURA,ERP_FT_MATERIA_PRIMA,ERP_FT_DESC_MATERIA_PRIMA,ERP_FT_COMPOSICAO,ERP_FT_DESC_COMPOSICAO,ERP_FT_CATEGORIA,ERP_FT_DESC_CATEGORIA,ERP_FT_FIT,ERP_FT_DESC_FIT,ERP_FT_ESPECIFICACOES,ERP_FT_DESC_ESPECIFICACOES,ERP_FT_CLASSIFICACAO,ERP_FT_DESC_CLASSIFICACAO,ERP_FT_DESENHO,ERP_FT_DESC_DESENHO,ERP_FT_FATOR_F,ERP_FT_DESC_FATOR_F,ERP_FT_RISCO,ERP_FT_DESC_RISCO,ERP_LICENCIADO,REQUERIDO_POR,TIPO_COMPRA,ERP_CAB_COD_CABIDE,ERP_CAB_OPCAO,ERP_CUPS_CUSTO_FOB,ERP_UMODE_ID_VARIANTE,ERP_UMODE_BATCH_NAME,ENTREGA,LIMITE_ENTREGA,ERP_CUPS_DATA_ACORDADA) '
set @SQL = @SQL + 'VALUES (' + @val_ins + ')';

	print @sql;

	IF @debug > 0
		SELECT @sql;

	EXEC (@SQL);
	
	if (select count(*) from PRODUTOS where produto = @codigo_produto) > 0 begin
		set @retorno = 200;
		set @retproc = 'OK';
		if @debug > 0 
			select @retorno as 'cod','SUCESSO' as 'resultado';
	end
	else begin
		set @retorno = 400;
		set @retproc = 'NOK';
		if @debug > 0 
			select @retorno as 'cod', 'ERRO' as 'resultado';
	end;

	return @retorno;

end;


/*
EXEC PLM_IRIS_Umode_INS_PRODUTO '',1

SET @SQL = 'SELECT ProductID,Name,ProductNumber FROM SalesLT.Product where ProductID = '+ @Pid
 
EXEC (@SQL)
*/
GO


USE [CAEDU]
GO

/****** Object:  StoredProcedure [dbo].[PLM_IRIS_Umode_INS_PRODUTOS_PACKS_PERMITIDOS]    Script Date: 14/06/2023 15:16:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [dbo].[PLM_IRIS_Umode_INS_PRODUTOS_PACKS_PERMITIDOS]
@produto char(12),
@cor_produto char(12),
@param2 char(120),
@retorno varchar(100) output
AS 

set @retorno = 'NOK'
DECLARE @SQL varchar(8000);
--set @produto = '01050999'
/*
INSERT INTO [CAEDU].[DBO].PRODUTOS_PACKS_PERMITIDOS 
		(PRODUTO,PACK,QTDE,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,COR_PRODUTO,INDICA_PACK_COR,INATIVO) 
	VALUES 
		(@produto,'A',12,2,4,4,2,0,0,0,0,0,0,0,0,0,0,0,0,@cor_produto,1,0)
		          'A',12,2,2,3,3,2,0,0,0,0,0,0,0,0,0,0,0,0,0
		          'A',12,2,2,3,3,2,0,0,0,0,0,0,0,0,0,0,0
*/
Declare @produtosemaspas char(12);
set @produtosemaspas = REPLACE(@produto,'''','');
if exists (select 1 from PRODUTOS_PACKS_PERMITIDOS where produto = @produtosemaspas)
begin
	delete from PRODUTOS_PACKS_PERMITIDOS where produto = @produtosemaspas
end
set @SQL = 'INSERT INTO [CAEDU].[DBO].PRODUTOS_PACKS_PERMITIDOS (PRODUTO,PACK,QTDE,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,COR_PRODUTO,INDICA_PACK_COR,INATIVO)'
set @SQL = @SQL + ' VALUES (' + @produto + ',' + @param2 + ',' + @cor_produto + ',1,0)';

EXEC (@SQL);


set @retorno = 'OK'

GO

USE [CAEDU]
GO

/****** Object:  StoredProcedure [dbo].[PLM_IRIS_Umode_INS_PRODUTOS_PLM]    Script Date: 14/06/2023 15:16:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [dbo].[PLM_IRIS_Umode_INS_PRODUTOS_PLM] 
@codigo_produto varchar(100),
@val_ins varchar(2000),
@debug int,
@retproc varchar(100) output
AS
begin

DECLARE @SQL varchar(8000);
declare @retorno int;

set @SQL = 'INSERT INTO [CAEDU].[DBO].PRODUTOS_PLM (PRODUTO,ESTACAO,TOP_BOTTOM,VISAO,LICENCIADO,MALHA_TECIDO,LINHA_PROMO,LINHA_PROMO_JEANS,ESTACAO_COM_VERAO,LEVE_PESADO,EQUIPAMENTOS,LINHA_ANTIGA,CLASSIF_POR_PRODUTO_MARCAR_X,DESC_PROMO_PROG_POR_ANO,PROMO_PROGRAMA,DIA_NOITE,OBSERVACOES_PLANEJAMENTO,ALCA_CABIDE,PROGRAMA,MÊS_LOJA_ORIGINAL,ENTREGA_CD,CLUSTER_LOJA,MARGEM,CAMPANHA_DE_POR_CARTAO,CAMPANHA_DE_POR_VITRINE,LAVAGEM,GOLA,DECOTE,MANGA,COMPRIMENTO_MANGA,CINTURA,APLICACAO,TIPO_ALCA,ESTRUTURA_BOJO,TIPO_BICO,TIPO_SALTO,ALTURA_SALTO,TIPO_FECHAMENTO,BANHO,DATA_LACRE,LACRE,CLASSIFICACAO_COMPLEXIDADE,OBSERVAÇÃO_MODELAGEM,APROVACAO_PRODUTO,APROVACAO_MODELAGEM,APROVACAO_QUALIDADE,OBS_PRODUTO,MATERIAL_1,COMPOSICAO_1,GRAMATURA_1,UNIDADE_1,MATERIAL_2,COMPOSICAO_2,GRAMATURA_2,UNIDADE_2,MATERIAL_3,COMPOSICAO_3,GRAMATURA_3,UNIDADE_3,MAT_CALCADO_INTERNO,MAT_CALCADO_EXTERNO,MAT_OPCOES_EXTERNO,MAT_CALCADO_MP_SOLADO,MAT_DETALHAMENTO) '
set @SQL = @SQL + 'VALUES (' + @val_ins + ')';

	print @sql;

	IF @debug > 0
		SELECT @sql;

	EXEC (@SQL);
	
	if (select count(*) from PRODUTOS_PLM where produto = @codigo_produto) > 0 begin
		set @retorno = 200;
		set @retproc = 'OK';
		if @debug > 0 
			select @retorno as 'cod','SUCESSO' as 'resultado';
	end
	else begin
		set @retorno = 400;
		set @retproc = 'NOK';
		if @debug > 0 
			select @retorno as 'cod', 'ERRO' as 'resultado';
	end;

	return @retorno;

end;
GO

USE [CAEDU]
GO

/****** Object:  StoredProcedure [dbo].[PLM_IRIS_Umode_INS_PRODUTOS_PRECOS]    Script Date: 14/06/2023 15:16:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [dbo].[PLM_IRIS_Umode_INS_PRODUTOS_PRECOS] 
@produto char(12),
@preco_venda numeric (14,2),
@preco_custo numeric (14,2),
@retorno varchar(100) output
AS 

set @retorno = 'NOK'

declare @tabprecos table (id int identity(1,1) not null, CODIGO_TAB_PRECO char(2) not null)
insert into @tabprecos (CODIGO_TAB_PRECO)
select CODIGO_TAB_PRECO 
from TABELAS_PRECO 
where
	CODIGO_TAB_PRECO not in ('AT','37','04','CM','CL','VA','00','02', '85') AND INATIVO=0

declare @min int, @max int, @CODIGO_TAB_PRECO char(2) 
		--@preco_venda numeric (14,2),
		--@preco_custo numeric (14,2), 
		--@produto char(12) 

select @min = min(id), @max = max(id)
from @tabprecos

--set @produto = '01050999'
--set @preco_custo = 25.86
--set @preco_venda = 69.99

-- looping para incluir os preços de venda
while @min <= @max
begin
	
	select @CODIGO_TAB_PRECO=CODIGO_TAB_PRECO
	from @tabprecos
	where id = @min

	insert into PRODUTOS_PRECOS
			(CODIGO_TAB_PRECO, PRODUTO, PRECO1, PRECO2,PRECO3,PRECO4, ULT_ATUALIZACAO)  
	values 	(@CODIGO_TAB_PRECO,@PRODUTO, @preco_venda ,0,0,0, getdate())

	set @min = @min + 1
end
/*insert dos preços de custo - tabelas 00 (custo original) e 02 (transferencia)*/
insert into PRODUTOS_PRECOS
		(CODIGO_TAB_PRECO, PRODUTO, PRECO1, PRECO2,PRECO3,PRECO4, ULT_ATUALIZACAO)  
values 	('00',@PRODUTO, @preco_custo ,0,0,0, getdate()),
		('02',@PRODUTO, @preco_custo ,0,0,0, getdate()),
		('85',@PRODUTO, @preco_custo ,0,0,0, getdate())
set @retorno = 'OK'

GO


USE [CAEDU]
GO

/****** Object:  StoredProcedure [dbo].[PLM_IRIS_Umode_Ret_Seq]    Script Date: 14/06/2023 15:19:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROC [dbo].[PLM_IRIS_Umode_Ret_Seq] 
@GRUPO_PRODUTO nvarchar(50),
@SUBGRUPO_PRODUTO nvarchar(50),
@debug int,
@retproc varchar(100) output
AS
begin

	declare @novo_sequencial nvarchar(50);
	declare @grupo nvarchar(50);
	declare @sub_grupo nvarchar(50);

	set @retproc = null;
	
	
	SELECT  @novo_sequencial =  RIGHT('0000'+CONVERT(VARCHAR,CAST(PRODUTOS_SUBGRUPO.CODIGO_SEQUENCIAL AS INT)+1),4) , 
		    @grupo = PRODUTOS_GRUPO.CODIGO_GRUPO ,
			@sub_grupo = PRODUTOS_SUBGRUPO.CODIGO_SUBGRUPO 
			--, PRODUTOS_SUBGRUPO.CODIGO_SEQUENCIAL AS SEQUENCIAL 
	FROM PRODUTOS_SUBGRUPO 
	INNER JOIN PRODUTOS_GRUPO ON PRODUTOS_GRUPO.GRUPO_PRODUTO = PRODUTOS_SUBGRUPO.GRUPO_PRODUTO 
	WHERE PRODUTOS_SUBGRUPO.GRUPO_PRODUTO = @GRUPO_PRODUTO AND PRODUTOS_SUBGRUPO.SUBGRUPO_PRODUTO = @SUBGRUPO_PRODUTO;

	set @retproc = @grupo + @sub_grupo + @novo_sequencial;

	if @debug > 0
		select @novo_sequencial as 'novo sequencial', @grupo as 'grupo', @sub_grupo as 'sub grupo';

	UPDATE PRODUTOS_SUBGRUPO 
			SET PRODUTOS_SUBGRUPO.CODIGO_SEQUENCIAL = RIGHT('0000'+CONVERT(VARCHAR,CAST(PRODUTOS_SUBGRUPO.CODIGO_SEQUENCIAL AS INT)+1),4) 
			FROM PRODUTOS_SUBGRUPO INNER JOIN PRODUTOS_GRUPO ON PRODUTOS_GRUPO.GRUPO_PRODUTO = PRODUTOS_SUBGRUPO.GRUPO_PRODUTO 
			WHERE PRODUTOS_SUBGRUPO.GRUPO_PRODUTO = @GRUPO_PRODUTO AND 
					PRODUTOS_SUBGRUPO.SUBGRUPO_PRODUTO = @SUBGRUPO_PRODUTO;

	

	--return 200;

end;


/*

USE CAEDU
declare @retornoOUTUPUT varchar(100);
execute PLM_IRIS_Umode_Ret_Seq 'TOP aaa TECIDO','M/C - M/L',0,@retornoOUTUPUT output;
select @retornoOUTUPUT as 'retorno OUTPUT';

USE CAEDU
declare @retornoOUTUPUT varchar(100);
declare @retornointerno varchar(100);

exec @retornointerno = PLM_IRIS_Umode_Ret_Seq 'TOP TECIDO','M/C - M/L',0,@retornoOUTUPUT output;

select @retornoOUTUPUT as 'retorno OUTPUT';

select  @retornointerno as 'retorno interno';
        

WHERE PRODUTOS_SUBGRUPO.GRUPO_PRODUTO = 'TOP TECIDO' AND PRODUTOS_SUBGRUPO.SUBGRUPO_PRODUTO = 'M/C - M/L';

*/
GO


USE [CAEDU]
GO

/****** Object:  StoredProcedure [dbo].[CGP_LX_GERAR_CODIGO_BARRA]    Script Date: 14/06/2023 15:25:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE OR ALTER PROCEDURE [dbo].[CGP_LX_GERAR_CODIGO_BARRA] 
	@produto varchar(12)
AS
BEGIN
	declare @grade varchar(25), @griffe varchar(25)
	declare @tab_cores table (id int identity(1,1), produto varchar(12), cor_produto varchar(10), desc_cor_produto varchar(40))
	DECLARE @VALOR_ETIQ_DUPLA VARCHAR(5)

	select @VALOR_ETIQ_DUPLA=VALOR_ATUAL from parametros where parametro = 'P_ETIQUETA_DUPLA'         

	insert into @tab_cores (produto, cor_produto, desc_cor_produto)
	select  produto, cor_produto, desc_cor_produto
	from PRODUTO_CORES where produto = @produto

	declare @tab_grade table (id int identity(1,1), posicao int, tamanho varchar(8))

	select  @GRADE = GRADE, @griffe = GRIFFE
	from produtos p
	where p.produto = @produto


	insert into @tab_grade (posicao, tamanho)
	exec LX_TAMANHOS_DIGITADOS_GRADE @grade

	DECLARE @TAB_BARRAS TABLE (
	PRODUTO VARCHAR(12),
	COR_PRODUTO VARCHAR(10),
	GRADE VARCHAR(8),
	CODIGO_BARRA VARCHAR(25),
	DESC_COR_PRODUTO VARCHAR(40),
	CODIGO_BARRA_PADRAO BIT,
	TIPO_COD_BAR tinyint,
	TAMANHO INT
	)

	DECLARE @MIN_CORES INT, @MAX_CORES INT
	DECLARE @MIN_SIZES INT, @MAX_SIZES INT

	SELECT  @MIN_CORES = min(id), @MAX_CORES = max(id)
	from @tab_cores


	declare 
		@COR_PRODUTO VARCHAR(10),
		@CODIGO_BARRA VARCHAR(25),
		@DESC_COR_PRODUTO VARCHAR(40),
		@CODIGO_BARRA_PADRAO BIT,
		@TIPO_COD_BAR tinyint,
		@POSICAO_CHAR VARCHAR(2), 
		@POSICAO INT

	while @MIN_CORES <= @MAX_CORES /* Faz um loop pra gerar por produto + cor + tamanhos */
	begin

		select @COR_PRODUTO = cor_produto, @DESC_COR_PRODUTO=desc_cor_produto 
		from @tab_cores where id = @MIN_CORES

		SELECT  @MIN_SIZES = min(id), @MAX_SIZES = max(id)
		from @tab_grade

		while @MIN_SIZES <= @MAX_SIZES
		begin

			SELECT @GRADE=tamanho, @POSICAO_CHAR=RIGHT('00'+CONVERT(VARCHAR,POSICAO),2), @POSICAO=POSICAO  
			FROM @tab_grade
			WHERE ID = @MIN_SIZES

			SET @CODIGO_BARRA = RTRIM(LTRIM(@produto))+RTRIM(LTRIM(@COR_PRODUTO))+@POSICAO_CHAR
			SET @CODIGO_BARRA_PADRAO=1
			SET @TIPO_COD_BAR=2

			insert into @TAB_BARRAS (PRODUTO, COR_PRODUTO, GRADE, CODIGO_BARRA, DESC_COR_PRODUTO, CODIGO_BARRA_PADRAO, TIPO_COD_BAR, TAMANHO)
			values (@PRODUTO, @COR_PRODUTO, @GRADE, @CODIGO_BARRA, @DESC_COR_PRODUTO, @CODIGO_BARRA_PADRAO, @TIPO_COD_BAR, @POSICAO)

			IF @griffe='CALCADOS' AND @VALOR_ETIQ_DUPLA='.T.'
			BEGIN
				SET @CODIGO_BARRA = RTRIM(LTRIM(@produto))+RTRIM(LTRIM(@COR_PRODUTO))+@POSICAO_CHAR+'D'
				SET @CODIGO_BARRA_PADRAO=0
				SET @TIPO_COD_BAR=2
				insert into @TAB_BARRAS (PRODUTO, COR_PRODUTO, GRADE, CODIGO_BARRA, DESC_COR_PRODUTO, CODIGO_BARRA_PADRAO, TIPO_COD_BAR, TAMANHO)
				values (@PRODUTO, @COR_PRODUTO, @GRADE, @CODIGO_BARRA, @DESC_COR_PRODUTO, @CODIGO_BARRA_PADRAO, @TIPO_COD_BAR, @POSICAO)
			END

			set @MIN_SIZES = @MIN_SIZES + 1
		end

		set @MIN_CORES = @MIN_CORES + 1
	end

	--SELECT * FROM  @tab_cores
	--SELECT * FROM @tab_grade
	--SELECT * FROM @TAB_BARRAS

	--SELECT * FROM PRODUTOS_BARRA WHERE PRODUTO = @produto
	if exists (select 1 from PRODUTOS_BARRA where produto = @produto)
	begin
		delete from PRODUTOS_BARRA where produto = @produto
	--select 'deletar'
	end
	INSERT INTO PRODUTOS_BARRA (CODIGO_BARRA,
								PRODUTO,
								COR_PRODUTO,
								TAMANHO,
								GRADE,
								DATA_PARA_TRANSFERENCIA,
								CODIGO_BARRA_PADRAO,
								INATIVO,
								TIPO_COD_BAR)
	SELECT CODIGO_BARRA,PRODUTO,COR_PRODUTO,TAMANHO,GRADE,GETDATE() AS DATA_PARA_TRANSFERENCIA,CODIGO_BARRA_PADRAO,CAST(0 AS BIT) AS INATIVO,TIPO_COD_BAR
	FROM @TAB_BARRAS
	
END
GO

