USE [CAEDU]
GO

/****** Object:  View [dbo].[PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE]    Script Date: 27/01/2021 11:11:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE]  
AS        
    
SELECT  AP.PRODUTO,
	    AP.PACK,            
        SUM(AP.QUANTIDADE*ISNULL(MULTIPLICADOR,1) )ESTOQUE,
		ISNULL(RD.QUANTIDADE,0) RESERVA,
		SUM(AP.QUANTIDADE*ISNULL(MULTIPLICADOR,1)) - ISNULL(RD.QUANTIDADE,0) DISPONIVEL
   FROM  PDA_WMS_TB_ARMAZENAGEM E 
   INNER JOIN PDA_WMS_TB_ARMAZENAGEM_PALETE AP ON AP.PALETE = E.PALETE
   LEFT JOIN (SELECT  SUM(QTDE) QUANTIDADE,PRODUTO,PACK FROM  PDA_WMS_TB_RESERVA_DISTRIBUICAO R INNER JOIN PDA_WMS_STATUS_DISTRIBUICAO S ON R.DISTRIBUICAO = S.DISTRIBUICAO WHERE STATUS IN(1,2,7) GROUP BY PRODUTO,PACK) RD ON RD.PRODUTO = AP.PRODUTO AND RD.PACK=AP.PACK
GROUP BY AP.PRODUTO,
         RD.QUANTIDADE,
		 AP.PACK

GO


