ALTER VIEW [dbo].[PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE]  
AS        
    
SELECT  AP.PRODUTO,
	    AP.PACK,            
        SUM(AP.QUANTIDADE*ISNULL(MULTIPLICADOR,1) )ESTOQUE,
		ISNULL(RD.QUANTIDADE,0) RESERVA,
		SUM(AP.QUANTIDADE*ISNULL(MULTIPLICADOR,1)) - ISNULL(RD.QUANTIDADE,0) DISPONIVEL,
		F.FILIAL
   FROM  PDA_WMS_TB_ARMAZENAGEM E 
   INNER JOIN PDA_WMS_TB_ENDERECO_FILIAL F ON E.ID_ENDERECO = F.ID_ENDERECO                                         
   INNER JOIN PDA_WMS_TB_ARMAZENAGEM_PALETE AP ON AP.PALETE = E.PALETE   
   
   LEFT JOIN (SELECT  SUM(QTDE) QUANTIDADE,PRODUTO,PACK FROM  PDA_WMS_TB_RESERVA_DISTRIBUICAO R INNER JOIN PDA_WMS_STATUS_DISTRIBUICAO S ON R.DISTRIBUICAO = S.DISTRIBUICAO WHERE STATUS IN(1,2,7) GROUP BY PRODUTO,PACK) RD ON RD.PRODUTO = AP.PRODUTO AND RD.PACK=AP.PACK
GROUP BY AP.PRODUTO,
         RD.QUANTIDADE,
		 AP.PACK,
		 F.FILIAL