--select * 
----update a set VALOR_ATUAL='CD - SP - SAO ROQUE'
--from PARAMETROS a
--where parametro = 'FILIAL_DISTRIBUICAO'


--SELECT * FROM PARAMETROS WHERE VALOR_ATUAL LIKE 'CD%'

--LX_PROCESSOS

--select *
--from COMPRAS c
--where 
--not exists (select PEDIDO from ESTOQUE_PROD_ENT a where a.PEDIDO = c.pedido
--)



select ENTREGA, LIMITE_ENTREGA, PRODUTO, COR_PRODUTO,
a.PEDIDO,A.FORNECEDOR,A.FILIAL_A_ENTREGAR,A.FILIAL_COBRANCA, A.FILIAL_A_FATURAR,A.ERP_CUPS_SEGMENTO,
A.EMISSAO, A.PEDIDO_FORNECEDOR,A.TOT_QTDE_ENTREGAR,A.TOT_QTDE_ORIGINAL,a.TIPO_COMPRA
--update A set erp_unous_data_envio = null, ...
from COMPRAS A
INNER JOIN COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO
where TOT_QTDE_ENTREGAR>0 /*and EMISSAO > '20230101'*/ and FILIAL_A_ENTREGAR = 'CD CAJAMAR'
AND ENTREGA>'20241231'
