select	c.pedido, 
		c.fornecedor, 
		c.filial_a_entregar, 
		c.filial_cobranca, 
		c.filial_a_faturar,
		CAST(C.TOT_QTDE_ORIGINAL AS INT) TOT_QTDE_ORIGINAL,
		CAST(C.TOT_QTDE_ENTREGAR AS INT) TOT_QTDE_ENTREGAR,
		P.ENTREGA, 
		P.LIMITE_ENTREGA
from compras c 
INNER JOIN (SELECT DISTINCT PEDIDO, ENTREGA, LIMITE_ENTREGA 
			FROM COMPRAS_PRODUTO CP ) P 
	ON P.PEDIDO = C.PEDIDO
where c.TOT_QTDE_ENTREGAR>0 
AND c.FILIAL_A_ENTREGAR='CD REGIS'
AND c.pedido not in 
(select pedido from COMPRAS_PROD_CANCELADA)
AND P.LIMITE_ENTREGA > '20190112'
ORDER BY P.LIMITE_ENTREGA ASC


SELECT * FROM COMPRAS 
WHERE DATA_PARA_TRANSFERENCIA >= '20190111' AND DATA_PARA_TRANSFERENCIA<'20190112'
AND FILIAL_A_ENTREGAR='CD CAJAMAR'


select * from produtos_precos where produto = 'Z2010062'


SELECT P.PRODUTO, PP00.PRECO1 TAB_00,  PP01.PRECO1 TAB_01
FROM PRODUTOS P
INNER JOIN PRODUTOS_PRECOS PP00 ON PP00.PRODUTO = P.PRODUTO AND PP00.CODIGO_TAB_PRECO = '00'
INNER JOIN PRODUTOS_PRECOS PP01 ON PP01.PRODUTO = P.PRODUTO AND PP01.CODIGO_TAB_PRECO = '01'
WHERE P.PRODUTO = '01050742'