select c.PEDIDO, c.EMISSAO ,e.NF_ENTRADA, e.SERIE_NF_ENTRADA, e.FILIAL, 
c.FORNECEDOR, e.NOME_CLIFOR, e.ROMANEIO_PRODUTO, c.FILIAL_A_ENTREGAR,
c.TOT_QTDE_ENTREGAR, c.TOT_QTDE_ORIGINAL 
from COMPRAS c
inner join ESTOQUE_PROD_ENT e
	on e.PEDIDO=c.PEDIDO
where c.TOT_QTDE_ENTREGAR>0 and c.EMISSAO>'20210101'