SELECT	/*B.PEDIDO, B.PRODUTO, B.COR_PRODUTO, B.ENTREGA, B.ITEM_PEDIDO,
		C.PEDIDO, C.PRODUTO, C.COR_PRODUTO, C.ENTREGA, C.ITEM_PEDIDO, A.**/
		A.CLIENTE_ATACADO,B.*
FROM VENDAS A
INNER JOIN VENDAS_PRODUTO B ON B.PEDIDO=A.PEDIDO
--INNER JOIN VENDAS_PROD_EMBALADO C ON C.PEDIDO=A.PEDIDO
WHERE B.PRODUTO='18050384' AND A.FILIAL='VENDA ATACADO BARRA VELHA'   ORDER BY CLIENTE_ATACADO,A.PEDIDO


select * from PRODUTOS_PACKS_PERMITIDOS where produto = '51120031'



SELECT ESTOQUE,* FROM ESTOQUE_PRODUTOS where FILIAL='VENDA ATACADO BARRA VELHA'



select D.ESTOQUE,* 
from compras A
INNER JOIN COMPRAS_PRODUTO B ON B.PEDIDO=A.PEDIDO
INNER JOIN ESTOQUE_PROD_ENT C ON C.PEDIDO=A.PEDIDO
INNER JOIN ESTOQUE_PRODUTOS D ON D.PRODUTO=B.PRODUTO AND D.COR_PRODUTO=B.COR_PRODUTO AND D.FILIAL='VENDA ATACADO BARRA VELHA'
where ERP_CUPS_SEGMENTO='ATACADO' 
and FILIAL_A_ENTREGAR='CD BARRA VELHA'
AND A.EMISSAO>'20250101'


SELECT B.ESTOQUE,* 
FROM COMPRAS_PRODUTO A 
INNER JOIN ESTOQUE_PRODUTOS B ON B.PRODUTO=A.PRODUTO AND FILIAL='VENDA ATACADO BARRA VELHA'
WHERE PEDIDO='344020E' 

