SELECT (SELECT COUNT(*) FROM entradas_ITEM WHERE nf_entrada=e.nf_entrada AND SERIE_NF_entrada=e.SERIE_NF_entrada and NOME_CLIFOR=e.NOME_CLIFOR) AS QT, e.*
FROM entradas e
WHERE filial = 'CD BARRA VELHA' AND NOME_CLIFOR='CD NAVEGANTES' and nf_entrada = '000022673'
ORDER BY 1 DESC     



/*
select * from faturamento where filial = 'CD NAVEGANTES' AND NOME_CLIFOR='CD BARRA VELHA'

select * from faturamento_item fi
inner join
(
SELECT (SELECT COUNT(*) FROM FATURAMENTO_ITEM WHERE NF_SAIDA=F.NF_SAIDA AND SERIE_NF=F.SERIE_NF and FILIAL=F.FILIAL) AS QT, F.*
FROM FATURAMENTO F
WHERE filial = 'CD NAVEGANTES' AND NOME_CLIFOR='CD BARRA VELHA'
) as fat on fat.NF_SAIDA=fi.NF_SAIDA and fat.SERIE_NF=fi.SERIE_NF and fat.FILIAL=fi.FILIAL


--SELECT * FROM FATURAMENTO_ITEM WHERE NF_SAIDA='000022573' AND SERIE_NF='02' AND FILIAL='CD NAVEGANTES'

SELECT FI.NF_SAIDA,SUB_ITEM_TAMANHO,COUNT(*) AS QTD_SUBITEM
FROM FATURAMENTO_ITEM FI
INNER JOIN FATURAMENTO F ON F.NF_SAIDA=FI.NF_SAIDA AND F.SERIE_NF=FI.SERIE_NF AND F.FILIAL=FI.FILIAL
WHERE FI.FILIAL='CD NAVEGANTES' AND F.NOME_CLIFOR='CD BARRA VELHA'
GROUP BY FI.NF_SAIDA, FI.SUB_ITEM_TAMANHO

UPDATE FATURAMENTO_ITEM 
SET ITEM_IMPRESSAO='0001'
WHERE NF_SAIDA='000022573' AND SERIE_NF='02' AND FILIAL='CD NAVEGANTES' AND ITEM_NFE IN (1,2,3)
go
UPDATE FATURAMENTO_ITEM 
SET ITEM_IMPRESSAO='0002'
WHERE NF_SAIDA='000022573' AND SERIE_NF='02' AND FILIAL='CD NAVEGANTES' AND ITEM_NFE IN (4,5,6)
go

[‎03/‎10/‎2018 17:48]  Rafael Munhon:  
select * from entradas where CHAVE_NFE = '42180946377727001670550020000228051585954031' 
 

*/
				SELECT * FROM ENTRADAS_ITEM
				WHERE nf_entrada='000022673'
				AND serie_nf_entrada='02'
				AND NOME_CLIFOR='CD NAVEGANTES'
				AND ITEM_IMPRESSAO='0002'
				AND SUB_ITEM_TAMANHO=4

				UPDATE ENTRADAS_ITEM
				SET ITEM_IMPRESSAO = '001'
				WHERE nf_entrada='000022673'
				AND serie_nf_entrada='02'
				AND NOME_CLIFOR='CD NAVEGANTES'
				AND ITEM_NFE=<<ALLTRIM(TRANSFORM(vENTRADAS_ITEM.ITEM_NFE,"9999"))>>


					SELECT * FROM ENTRADAS_IMPOSTO
					WHERE nf_entrada='000022673'
					AND serie_nf_entrada='02'
					AND NOME_CLIFOR='CD NAVEGANTES'
					AND ITEM_IMPRESSAO='0001'
					AND SUB_ITEM_TAMANHO=4
					AND ID_IMPOSTO=1

DECLARE @NF_ENTRADA VARCHAR(15) = '000022673'
DECLARE @ITEM CHAR(4) = '0002', @SUBITEM INT = 4
DECLARE @PAI BIT =0, @ITEM_VIEW BIT = 1, @IMPOSTOS_VIEW BIT=1


IF @PAI=1
BEGIN
SELECT DISTINCT EI.NF_ENTRADA, EI.SERIE_NF_ENTRADA, EI.NOME_CLIFOR, EI.ITEM_IMPRESSAO 
FROM ENTRADAS_ITEM EI 
WHERE EI.NF_ENTRADA=@NF_ENTRADA AND EI.SERIE_NF_ENTRADA='02' AND EI.NOME_CLIFOR='CD NAVEGANTES' AND ITEM_IMPRESSAO=@ITEM
ORDER BY EI.ITEM_IMPRESSAO
--AND ITEM_IMPRESSAO='0002'
--AND SUB_ITEM_TAMANHO=1
END

IF @ITEM_VIEW=1
BEGIN
SELECT EI.NF_ENTRADA, EI.SERIE_NF_ENTRADA, EI.NOME_CLIFOR, EI.ITEM_NFE, EI.CODIGO_ITEM, EI.SUB_ITEM_TAMANHO, EI.ITEM_IMPRESSAO 
FROM ENTRADAS_ITEM EI WHERE EI.NF_ENTRADA=@NF_ENTRADA AND EI.SERIE_NF_ENTRADA='02' AND EI.NOME_CLIFOR='CD NAVEGANTES' AND SUB_ITEM_TAMANHO=@SUBITEM AND ITEM_IMPRESSAO=@ITEM
--AND ITEM_IMPRESSAO='0002'
--AND SUB_ITEM_TAMANHO=1
END

IF @IMPOSTOS_VIEW =1
BEGIN
SELECT  EI.NF_ENTRADA, EI.SERIE_NF_ENTRADA, EI.NOME_CLIFOR, EI.SUB_ITEM_TAMANHO, EI.ID_IMPOSTO, EI.ITEM_IMPRESSAO
FROM ENTRADAS_IMPOSTO EI WHERE EI.NF_ENTRADA=@NF_ENTRADA AND EI.SERIE_NF_ENTRADA='02' AND EI.NOME_CLIFOR='CD NAVEGANTES' AND SUB_ITEM_TAMANHO=@SUBITEM AND ITEM_IMPRESSAO=@ITEM
order by ITEM_IMPRESSAO,SUB_ITEM_TAMANHO, id_imposto
--AND ITEM_IMPRESSAO='0002'
--AND SUB_ITEM_TAMANHO=1
END


--SELECT NF_SAIDA, SERIE_NF, FILIAL, SUB_ITEM_TAMANHO, ITEM_IMPRESSAO, ID_IMPOSTO
--FROM FATURAMENTO_IMPOSTO
--WHERE NF_SAIDA='000022573' 
--	AND SERIE_NF='02' 
--	AND FILIAL='CD NAVEGANTES'

/*
UPDATE FATURAMENTO_ITEM 
SET ITEM_IMPRESSAO = '0'+LTRIM(RTRIM(ITEM_IMPRESSAO))
WHERE NF_SAIDA='000022577' 
AND SERIE_NF='02' 
AND FILIAL='CD NAVEGANTES' 

UPDATE FATURAMENTO_IMPOSTO 
SET ITEM_IMPRESSAO = '0'+LTRIM(RTRIM(ITEM_IMPRESSAO))
WHERE NF_SAIDA='000022577' 
AND SERIE_NF='02' 
AND FILIAL='CD NAVEGANTES' 
*/


select NF_SAIDA, SERIE_NF, FILIAL, ITEM_NFE, CODIGO_ITEM, SUB_ITEM_TAMANHO, ITEM_IMPRESSAO 
from FATURAMENTO_ITEM 
WHERE NF_SAIDA='000022573' 
AND SERIE_NF='02' 
AND FILIAL='CD NAVEGANTES' 
AND ITEM_NFE=2 



UPDATE FATURAMENTO_ITEM 
SET ITEM_IMPRESSAO = '002'
WHERE NF_SAIDA='000022573' 
AND SERIE_NF='02' 
AND FILIAL='CD NAVEGANTES' 
AND ITEM_NFE=2 



	SELECT * FROM FATURAMENTO_IMPOSTO
	WHERE NF_SAIDA='000022574' 
	AND SERIE_NF='02' 
	AND FILIAL='CD NAVEGANTES' 
	AND ITEM_IMPRESSAO='0001' 
	AND SUB_ITEM_TAMANHO=1 
	AND ID_IMPOSTO=1 
