SELECT (SELECT COUNT(*) FROM FATURAMENTO_ITEM WHERE NF_SAIDA=F.NF_SAIDA AND SERIE_NF=F.SERIE_NF and FILIAL=F.FILIAL) AS QT, F.*
FROM FATURAMENTO F
WHERE filial = 'CD NAVEGANTES' AND NOME_CLIFOR='CD BARRA VELHA' AND NF_SAIDA NOT IN ('000022573','000022574','000022577')


select * from faturamento where filial = 'CD NAVEGANTES' AND NOME_CLIFOR='CD BARRA VELHA'

select * from faturamento_item fi
inner join
(
SELECT (SELECT COUNT(*) FROM FATURAMENTO_ITEM WHERE NF_SAIDA=F.NF_SAIDA AND SERIE_NF=F.SERIE_NF and FILIAL=F.FILIAL) AS QT, F.*
FROM FATURAMENTO F
WHERE filial = 'CD NAVEGANTES' AND NOME_CLIFOR='CD BARRA VELHA'
) as fat on fat.NF_SAIDA=fi.NF_SAIDA and fat.SERIE_NF=fi.SERIE_NF and fat.FILIAL=fi.FILIAL


--SELECT * FROM FATURAMENTO_ITEM WHERE NF_SAIDA='000022573' AND SERIE_NF='02' AND FILIAL='CD NAVEGANTES'

SELECT FI.NF_SAIDA,SUB_ITEM_TAMANHO,COUNT(*) AS QTD_SUBITEM
FROM FATURAMENTO_ITEM FI
INNER JOIN FATURAMENTO F ON F.NF_SAIDA=FI.NF_SAIDA AND F.SERIE_NF=FI.SERIE_NF AND F.FILIAL=FI.FILIAL
WHERE FI.FILIAL='CD NAVEGANTES' AND F.NOME_CLIFOR='CD BARRA VELHA'
GROUP BY FI.NF_SAIDA, FI.SUB_ITEM_TAMANHO

UPDATE FATURAMENTO_ITEM 
SET ITEM_IMPRESSAO='0001'
WHERE NF_SAIDA='000022573' AND SERIE_NF='02' AND FILIAL='CD NAVEGANTES' AND ITEM_NFE IN (1,2,3)
go
UPDATE FATURAMENTO_ITEM 
SET ITEM_IMPRESSAO='0002'
WHERE NF_SAIDA='000022573' AND SERIE_NF='02' AND FILIAL='CD NAVEGANTES' AND ITEM_NFE IN (4,5,6)
go

DECLARE @NF_SAIDA VARCHAR(15) = '000022577'

SELECT item_impressao,* FROM FATURAMENTO_PROD WHERE NF_SAIDA=@NF_SAIDA AND SERIE_NF='02' AND FILIAL='CD NAVEGANTES'

SELECT NF_SAIDA, SERIE_NF, FILIAL, ITEM_NFE, CODIGO_ITEM, SUB_ITEM_TAMANHO, ITEM_IMPRESSAO 
FROM FATURAMENTO_ITEM WHERE NF_SAIDA=@NF_SAIDA AND SERIE_NF='02' AND FILIAL='CD NAVEGANTES'
--AND ITEM_IMPRESSAO='0002'
--AND SUB_ITEM_TAMANHO=1


--SELECT * FROM FATURAMENTO_IMPOSTO WHERE NF_SAIDA='000022573' AND SERIE_NF='02' AND FILIAL='CD NAVEGANTES'

SELECT  NF_SAIDA, SERIE_NF, FILIAL, SUB_ITEM_TAMANHO, ID_IMPOSTO, ITEM_IMPRESSAO
FROM FATURAMENTO_IMPOSTO WHERE NF_SAIDA=@NF_SAIDA AND SERIE_NF='02' AND FILIAL='CD NAVEGANTES'
order by ITEM_IMPRESSAO,SUB_ITEM_TAMANHO, id_imposto
--AND ITEM_IMPRESSAO='0002'
--AND SUB_ITEM_TAMANHO=1

SELECT  NF_SAIDA, SERIE_NF, FILIAL, SUB_ITEM_TAMANHO, ID_IMPOSTO, ITEM_IMPRESSAO
FROM FATURAMENTO_IMPOSTO WHERE NF_SAIDA=@NF_SAIDA AND SERIE_NF='02' AND FILIAL='CD NAVEGANTES' AND ITEM_IMPRESSAO='0002' AND SUB_ITEM_TAMANHO=1 and ID_IMPOSTO=1

	--SELECT NF_SAIDA, SERIE_NF, FILIAL, SUB_ITEM_TAMANHO, ITEM_IMPRESSAO, ID_IMPOSTO
	--FROM FATURAMENTO_IMPOSTO
	--WHERE NF_SAIDA='000022573' 
	--	AND SERIE_NF='02' 
	--	AND FILIAL='CD NAVEGANTES'


UPDATE FATURAMENTO_ITEM 
SET ITEM_IMPRESSAO = '0'+LTRIM(RTRIM(ITEM_IMPRESSAO))
WHERE NF_SAIDA='000022577' 
AND SERIE_NF='02' 
AND FILIAL='CD NAVEGANTES' 

UPDATE FATURAMENTO_IMPOSTO 
SET ITEM_IMPRESSAO = '0'+LTRIM(RTRIM(ITEM_IMPRESSAO))
WHERE NF_SAIDA='000022577' 
AND SERIE_NF='02' 
AND FILIAL='CD NAVEGANTES' 



select NF_SAIDA, SERIE_NF, FILIAL, ITEM_NFE, CODIGO_ITEM, SUB_ITEM_TAMANHO, ITEM_IMPRESSAO 
from FATURAMENTO_ITEM 
WHERE NF_SAIDA='000022573' 
AND SERIE_NF='02' 
AND FILIAL='CD NAVEGANTES' 
AND ITEM_NFE=2 



UPDATE FATURAMENTO_ITEM 
SET ITEM_IMPRESSAO = '002'
WHERE NF_SAIDA='000022573' 
AND SERIE_NF='02' 
AND FILIAL='CD NAVEGANTES' 
AND ITEM_NFE=2 



	SELECT * FROM FATURAMENTO_IMPOSTO
	WHERE NF_SAIDA='000022574' 
	AND SERIE_NF='02' 
	AND FILIAL='CD NAVEGANTES' 
	AND ITEM_IMPRESSAO='0001' 
	AND SUB_ITEM_TAMANHO=1 
	AND ID_IMPOSTO=1 
