/*
exec CGP_LX_PEDIDO_PDA_ECOMM_ETIQ '401467'
*/

CREATE OR ALTER PROCEDURE DBO.CGP_LX_PEDIDO_PDA_ECOMM_ETIQ
	@ID_PEDIDO VARCHAR(12)
AS
select  ID_PEDIDO,
DESC_COLECAO,
FORNECEDOR,
A.PRODUTO,
PRECO1,
A.QUANTIDADE AS QTDE_ENTREGAR,
B.GRADE,
COR_PRODUTO,
DESC_COR_PRODUTO,
B.TAMANHO2,
DESC_PRODUTO,
CODIGO_BARRA,
LINHA,
TIPO_PRODUTO,
ENTREGA,
DESCRICAO_MSG, 
GRUPO_PRODUTO,
ERP_AREA_JEANS,
PACKS,
A.QUANTIDADE AS QTDE_TOTAL,
ZERAR_DATA,
GRIFFE,
SUBGRUPO_PRODUTO
from PDA_TB_EC_PEDIDO_ITEM A 
inner join (
SELECT 
	C.DESC_COLECAO	AS [DESC_COLECAO],
	P.FABRICANTE	AS [FORNECEDOR],
	P.PRODUTO		AS [PRODUTO],
	PP.PRECO1		AS [PRECO1],
	CAST(0 AS INT)	AS [QTDE_ENTREGAR],
	P.GRADE			AS [GRADE],
	PB.COR_PRODUTO	AS [COR_PRODUTO],
	PC.DESC_COR_PRODUTO AS [DESC_COR_PRODUTO],
	PB.TAMANHO		AS [TAMANHO], /* pega o tamanho e não a posição na grade exemplo 10 a 16 - pos 7 = 10*/
	PB.GRADE		AS [TAMANHO2],
	P.DESC_PRODUTO	AS [DESC_PRODUTO],
	PB.CODIGO_BARRA AS [CODIGO_BARRA],
	P.LINHA			AS [LINHA],
	P.TIPO_PRODUTO	AS [TIPO_PRODUTO],
	SPACE(10)		AS [ENTREGA],
	SPACE(50)		AS [DESCRICAO_MSG], 
	P.GRUPO_PRODUTO AS [GRUPO_PRODUTO],
	P.ERP_AREA_JEANS AS [ERP_AREA_JEANS],
	'A'				AS [PACKS],
	CAST(0 AS INT)	AS [QTDE_TOTAL],
	SPACE(3) AS [ZERAR_DATA],
	P.GRIFFE	AS [GRIFFE],
	P.SUBGRUPO_PRODUTO AS [SUBGRUPO_PRODUTO]
FROM CAEDU.DBO.PRODUTOS P
INNER JOIN CAEDU.DBO.COLECOES C ON C.COLECAO = P.COLECAO
INNER JOIN CAEDU.DBO.PRODUTOS_PRECOS PP 
			ON PP.PRODUTO=P.PRODUTO AND PP.CODIGO_TAB_PRECO='01'
INNER JOIN CAEDU.DBO.PRODUTOS_BARRA PB ON PB.PRODUTO = P.PRODUTO
INNER JOIN CAEDU.DBO.PRODUTO_CORES PC 
			ON PC.PRODUTO=PB.PRODUTO AND PC.COR_PRODUTO=PB.COR_PRODUTO
INNER JOIN CAEDU.DBO.PRODUTOS_LINHAS PL ON PL.LINHA=P.LINHA
) B ON B.PRODUTO = A.PRODUTO collate Latin1_General_CI_AS
AND B.COR_PRODUTO = A.COR collate Latin1_General_CI_AS
AND B.TAMANHO = A.TAMANHO

where A.ID_PEDIDO = @ID_PEDIDO --'401467'
GO
