DECLARE @CUR_PARAMETROS TABLE (
TIPO_VENDA VARCHAR(25) NULL,
CODIGO_TAB_PRECO VARCHAR(2) NULL,
FRETE_PAGO INT NULL,
CTRL_MULT_ENTREGAS INT NULL,
REPRESENTANTE_PADRAO VARCHAR(25) NULL,
TRANSPORTADORA_PADRAO VARCHAR(25) NULL,
COND_PGTO_PADRAO VARCHAR(3) NULL,
COLECAO_PADRAO VARCHAR(25) NULL,
MOEDA_PADRAO VARCHAR(10) NULL,
TIPO_CAIXA_PADRAO VARCHAR(2) NULL,
TIPO_FRETE_DISTRIBUICAO VARCHAR(2) NULL
)

DECLARE @CUR_APROVACAO TABLE (APROVACAO CHAR(1))

DECLARE @V_CAIXAS TABLE (
	[ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[data] [datetime] NULL,
	[rownum] [int] NULL,
	[caixa] [varchar](8) NOT NULL,
	[doca] [varchar](35) NULL,
	[codigo_filial] [varchar](6) NULL,
	[filial] [varchar](25) NULL,
	[origem] [char](1) NULL,
	[distribuicao] [varchar](8) NULL,
	[produto] [varchar](8) NULL,
	[lojadestino] [varchar](25) NULL,
	[filial_origem] [varchar](25) NULL,
	[qtde_total] [int] NULL,
	[qtde_pack] [int] NULL,
	[venda] [varchar](12) NULL,
	[pack] [char](1) NULL,
	[CUSTO_1] [numeric](14, 2) NULL,
	[GRADE] [varchar](25) NULL,
	[ERP_QTD_PACK] [int] NULL,
	[qtde_packs] [int] NULL,
	[COR_PRODUTO] [varchar](5) NULL,
	[QTDE] [int] NULL,
	[Q1] [int] NULL,
	[Q2] [int] NULL,
	[Q3] [int] NULL,
	[Q4] [int] NULL,
	[Q5] [int] NULL,
	[Q6] [int] NULL,
	[Q7] [int] NULL,
	[Q8] [int] NULL,
	[Q9] [int] NULL,
	[Q10] [int] NULL,
	[Q11] [int] NULL,
	[Q12] [int] NULL,
	[Q13] [int] NULL,
	[Q14] [int] NULL,
	[Q15] [int] NULL,
	[Q16] [int] NULL,
	[faturado] [bit] NOT NULL,
	[data_ultimo_inventario] datetime null,
	[filial2] varchar(25)
)

INSERT INTO @CUR_PARAMETROS
	SELECT ISNULL(DBO.FX_PARAMETRO_EMPRESA('TIPO_VENDA',0),'') AS TIPO_VENDA,
 	ISNULL(DBO.FX_PARAMETRO_EMPRESA('TABELA_PRECO_PADRAO',0),'') AS CODIGO_TAB_PRECO,
    (CASE WHEN ISNULL(DBO.FX_PARAMETRO_EMPRESA('FRETE_PAGO',0),'.F.') = '.T.' THEN 1 ELSE 0 END) AS FRETE_PAGO,
	(CASE WHEN ISNULL(DBO.FX_PARAMETRO_EMPRESA('CTRL_MULT_ENTREGAS',0),'.F.') = '.T.' THEN 1 ELSE 0 END) AS CTRL_MULT_ENTREGAS,
	ISNULL(DBO.FX_PARAMETRO_EMPRESA('REPRESENTANTE_PADRAO',0),'') AS REPRESENTANTE_PADRAO,
	ISNULL(DBO.FX_PARAMETRO_EMPRESA('TRANSPORTADORA_PADRAO',0),'') AS TRANSPORTADORA_PADRAO,
	ISNULL(DBO.FX_PARAMETRO_EMPRESA('COND_PGTO_PADRAO',0),'') AS COND_PGTO_PADRAO,
	Isnull(RTRIM(LTRIM(DBO.FX_PARAMETRO('COLECAO_PADRAO'))),'') AS COLECAO_PADRAO,
	ISNULL(DBO.FX_PARAMETRO_EMPRESA('MOEDA_PADRAO',0),'') AS MOEDA_PADRAO,
	ISNULL(DBO.FX_PARAMETRO_EMPRESA('TIPO_CAIXA_PADRAO',0),'') AS TIPO_CAIXA_PADRAO,
	ISNULL(DBO.FX_PARAMETRO_EMPRESA('TIPO_FRETE_DISTRIBUICAO',0),'') AS TIPO_FRETE_DISTRIBUICAO

INSERT @CUR_APROVACAO
SELECT APROVACAO FROM VENDAS_TIPO WHERE TIPO = 'DISTRIBUICAO'

