SET NOCOUNT ON

DECLARE @TABCAIXAS TABLE (ID INT IDENTITY(1,1), CAIXA VARCHAR(8))

INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998873');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998874');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998875');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998876');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998877');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998878');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998879');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998880');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998881');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998882');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998883');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998884');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998885');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998886');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998887');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998888');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998889');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998890');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998891');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998892');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998893');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998894');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998895');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998897');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998896');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998900');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998901');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998903');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998904');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998898');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998899');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998902');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998905');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998906');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998907');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('15009514');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('15009513');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998909');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998908');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998910');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998911');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998912');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998913');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998914');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998915');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998916');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998917');
INSERT INTO @TABCAIXAS (CAIXA) VALUES ('14998918');

DECLARE @I INT = 1
DECLARE @TOT INT 

DECLARE @CAIXA VARCHAR(8)
DECLARE @PEDIDO VARCHAR(11)

SELECT @TOT = MAX(ID) FROM @TABCAIXAS


WHILE @I<=@TOT
BEGIN
	SELECT @CAIXA = CAIXA, @PEDIDO = 'CX-'+CAIXA	
	FROM @TABCAIXAS WHERE ID = @I

	if not exists(select 1 from faturamento_prod where caixa = @CAIXA)
	BEGIN
		DECLARE @VENDAS_PRODUTO
		TABLE (
		ID_VENDA INT IDENTITY(1,1),
		PEDIDO CHAR(12), 
		PRODUTO CHAR(12), 
		COR_PRODUTO CHAR(10), 
		ENTREGA DATETIME, 
		ITEM_PEDIDO CHAR(4)
		)
		INSERT INTO @VENDAS_PRODUTO (PEDIDO, PRODUTO,COR_PRODUTO, ENTREGA, ITEM_PEDIDO)
		SELECT PEDIDO, PRODUTO, COR_PRODUTO, ENTREGA, ITEM_PEDIDO 
		FROM VENDAS_PRODUTO WHERE PEDIDO = @PEDIDO

		DECLARE @ID_VENDA INT
		DECLARE @TOT_VENDA INT 
	
		SELECT @TOT_VENDA = MAX(ID_VENDA) 
		FROM @VENDAS_PRODUTO

		DECLARE @PRODUTO CHAR(12), 
				@COR_PRODUTO CHAR(10), 
				@ENTREGA DATETIME, 
				@ITEM_PEDIDO CHAR(4)

		-- EXCLUI TODOS OS ITENS DA TABELA FILHA VENDAS_PRODUTO LINHA A LINHA
		SELECT @ID_VENDA = MIN(ID_VENDA) 
		FROM @VENDAS_PRODUTO

		WHILE @ID_VENDA<=@TOT_VENDA
		BEGIN
			SELECT 	@PRODUTO = PRODUTO, 
					@COR_PRODUTO = COR_PRODUTO, 
					@ENTREGA = ENTREGA, 
					@ITEM_PEDIDO = ITEM_PEDIDO
			FROM @VENDAS_PRODUTO WHERE ID_VENDA = @ID_VENDA

			DELETE FROM VENDAS_PRODUTO 
			WHERE	PEDIDO = @PEDIDO AND 
					PRODUTO = @PRODUTO AND 
					COR_PRODUTO = @COR_PRODUTO AND 
					ENTREGA = @ENTREGA AND
					ITEM_PEDIDO = @ITEM_PEDIDO
			PRINT 'EXCLUIU VENDAS_PRODUTO: '+CONVERT(VARCHAR,@ID_VENDA)+'=> | '+@PEDIDO+'|'+@PRODUTO+'|'+@COR_PRODUTO	
			SET @ID_VENDA = @ID_VENDA + 1
		END

		DELETE FROM @VENDAS_PRODUTO

		DELETE FROM VENDAS
		WHERE PEDIDO = @PEDIDO
		PRINT 'EXCLUIU VENDAS PARA O PEDIDO: '+@PEDIDO

		DELETE 
		FROM FATURAMENTO_CAIXAS 
		WHERE CAIXA = @CAIXA
		PRINT 'EXCLUIU FATURAMENTO_CAIXAS PARA A CAIXA = '+@CAIXA
	END -- if not exists(select 1 from faturamento_prod where caixa = @CAIXA)
	ELSE
	BEGIN
		PRINT 'JÁ EXISTE FATURAMENTO FEITO PARA A CAIXA = '+@CAIXA
	END
	 
	--INCREMENTA O CONTADOR DE REGISTROS (REGNUM)
	PRINT 'LINHA ' + CONVERT(VARCHAR,@I)
	SET @I = @I + 1
END

SET NOCOUNT OFF






