CREATE PROCEDURE lx_estorna_empenho_otb
(
	@PEDIDO CHAR(8) 
)
AS
BEGIN
	DECLARE @PRODUTO CHAR(12)

	DECLARE @GRIFFE		VARCHAR(25)
	DECLARE @LINHA		VARCHAR(25)
	DECLARE @GRUPO		VARCHAR(25)
	DECLARE @SUBGRUPO	VARCHAR(25)
	DECLARE @ANOMES		INT

	DECLARE @EMPENHO 	NUMERIC(18,2)

	SELECT TOP 1 @PRODUTO = PRODUTO 
	FROM 	COMPRAS_PRODUTO 
	WHERE 	PEDIDO = @PEDIDO

	SELECT 	@ANOMES = MAX(ERP_VERBAS_EMPENHO_ANO_MES), 
			@EMPENHO = SUM(ERP_VERBAS_EMPENHO)
	FROM 	COMPRAS_PRODUTO 
	WHERE 	PEDIDO = @PEDIDO
	GROUP BY PEDIDO

	IF @@ROWCOUNT <> 0
	BEGIN
		SELECT 	@GRIFFE	= GRIFFE,
				@LINHA	= LINHA,
				@GRUPO	= GRUPO_PRODUTO,
				@SUBGRUPO = SUBGRUPO_PRODUTO
		FROM PRODUTOS
		WHERE PRODUTO = @PRODUTO
	END

	IF LEN(RTRIM(LTRIM(@GRIFFE)))>0
	BEGIN
		/* ESTORNA O SALDO EMPENHADO NO PEDIDO */
		UPDATE 	CAEDU_VERBA_COMPRAS
		SET EMPENHO = EMPENHO - ISNULL(@EMPENHO,0)
		WHERE  	(GRIFFE	= @GRIFFE 
				AND LINHA = @LINHA	
				AND GRUPO = @GRUPO	
				AND SUBGRUPO = @SUBGRUPO
				AND MES = @ANOMES)

	END

END 

