CREATE PROCEDURE LX_CAEDU_EXCLUI_DISTRIBUICAO_PEDIDO
	@PEDIDO VARCHAR(8)
AS

DECLARE @ROMANEIO_PRODUTO CHAR(8) = ''
/* Verifica se o pedido já foi faturado (distribuido) */
IF EXISTS(SELECT 1 	FROM faturamento_prod WHERE caixa IN (SELECT caixa from caedu_reserva_automatica
			where pedido = @PEDIDO))
BEGIN
	RAISERROR ('Erro: pedido ja faturado. Nao foi possivel a exclusao da distribuicao',16, 1 ); 
	RETURN -1
END

/* PEGA O CODIGO DO ROMANEIO_PRODUTO SE HOUVER */
SELECT DISTINCT @ROMANEIO_PRODUTO = ISNULL(ROMANEIO_PRODUTO,'') 
FROM CAEDU_RESERVA_AUTOMATICA 
WHERE PEDIDO = @PEDIDO

BEGIN TRANSACTION EXCLUI_DISTRIBUICAO

	/* EXCLUI VENDAS_PROD_EMBALADO */
	DELETE VENDAS_PROD_EMBALADO WHERE PEDIDO IN
	(select venda from caedu_reserva_automatica where pedido = @PEDIDO)
	IF @@ERROR <> 0   
	BEGIN  
		ROLLBACK TRANSACTION EXCLUI_DISTRIBUICAO
		RAISERROR ('Erro ao excluir VENDAS_PROD_EMBALADO',16, 1 ); 
		RETURN -1;  
	END  

	/* EXCLUI FATURAMENTO_CAIXAS */
	DELETE FATURAMENTO_CAIXAS WHERE CAIXA IN
	(select CAIXA from caedu_reserva_automatica where pedido = @PEDIDO)
	IF @@ERROR <> 0   
	BEGIN  
		ROLLBACK TRANSACTION EXCLUI_DISTRIBUICAO
		RAISERROR ('Erro ao excluir FATURAMENTO_CAIXAS',16, 1 ); 
		RETURN -1;  
	END  

	DELETE caedu_reserva_automatica where pedido = @PEDIDO
	IF @@ERROR <> 0   
	BEGIN  
		ROLLBACK TRANSACTION EXCLUI_DISTRIBUICAO
		RAISERROR ('Erro ao excluir CAEDU_RESERVA_AUTOMATICA',16, 1 ); 
		RETURN -1;  
	END  

	IF @ROMANEIO_PRODUTO <> ''
	BEGIN
		DELETE FROM ESTOQUE_PROD_SAI 
		WHERE ROMANEIO_PRODUTO = @ROMANEIO_PRODUTO  
			AND filial in ('SP - ATACADO','NOVO SP - ATACADO 2') 
			AND ROMANEIO_DESTINO IS NOT NULL

		IF @@ERROR <> 0   
		BEGIN  
			ROLLBACK TRANSACTION EXCLUI_DISTRIBUICAO
			DECLARE @msgerro varchar(1000)
			set @msgerro = 'Erro ao estornar estoque para ESTOQUE_PROD_SAI (romaneio_produto ='+@ROMANEIO_PRODUTO+')'
			RAISERROR (@msgerro,16, 1 ); 
			RETURN -1;  
		END  

	END

COMMIT TRANSACTION EXCLUI_DISTRIBUICAO
RETURN 0
