
CREATE PROCEDURE CGP_LOCAL_ENTREGA_PRODUTO 
@PRODUTO VARCHAR(8)
AS
select TOP 1 
case when C.FILIAL_A_ENTREGAR like 'VENDA ATACADO%' then 'VENDA ATACADO' 
ELSE 'CD CAJAMAR' 
END AS LOCAL_ENTREGA, 
CP.ENTREGA, CP.LIMITE_ENTREGA, CP.PRODUTO, CP.PEDIDO 
from COMPRAS C
INNER JOIN COMPRAS_PRODUTO CP
	ON CP.PEDIDO=C.PEDIDO
where PRODUTO=@PRODUTO
ORDER BY CP.ENTREGA DESC
GO

