DECLARE @TABPRO TABLE (
						ROWNUM INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
						PRODUTO VARCHAR(12) NOT NULL)
INSERT INTO @TABPRO
SELECT P.PRODUTO 
FROM PRODUTOS P 
LEFT JOIN PROP_PRODUTOS PP ON PP.PRODUTO = P.PRODUTO AND PP.PROPRIEDADE = '00105'
WHERE PP.PRODUTO IS NULL and P.INATIVO=0

DECLARE @ROWNUM INT, @TOT INT, @PRODUTO VARCHAR(12)

SELECT @ROWNUM=MIN(ROWNUM), @TOT=MAX(ROWNUM) 
FROM @TABPRO

WHILE @ROWNUM<=@TOT
BEGIN
	PRINT @ROWNUM

	SELECT @PRODUTO = PRODUTO 
	FROM @TABPRO
	WHERE ROWNUM=@ROWNUM

	INSERT INTO PROP_PRODUTOS VALUES ('00105',@PRODUTO,1,'X',GETDATE())
	SET @ROWNUM += 1
END

SELECT * 
FROM PROP_PRODUTOS A
INNER JOIN @TABPRO P ON P.PRODUTO = A.PRODUTO
WHERE PROPRIEDADE = '00105'
