select * from CAEDU_RESERVA_AUTOMATICA_PACK_WMS where distribuicao = '00002083'
select * from CAEDU_RESERVA_AUTOMATICA_PACK_WMS where distribuicao = '00001569'


select *  FROM PDA_WMS_TB_DISTRIBUICAO_COLETA where distribuicao  =  '00001569' 
select *  FROM PDA_WMS_TB_DISTRIBUICAO_COLETA where distribuicao  =  '00002083' 



select * from entradas where nf_entrada = '000003681' and NOME_CLIFOR = 'CD BARRA VELHA'

select * from entradas_ITEM where nf_entrada = '000003681' and NOME_CLIFOR = 'CD BARRA VELHA' AND CODIGO_ITEM = '13090141'


SELECT (1872/9)/4

SELECT * FROM PRODUTOS_PACKS_PERMITIDOS WHERE PRODUTO = '13090141'

DECLARE @CAIXA VARCHAR(100), @QTD_PIPES INT
SET @CAIXA = 'A|13090141|000003681|02|8845'
SELECT @QTD_PIPES = LEN(@CAIXA) - LEN(REPLACE(@CAIXA,'|',''))
SELECT @CAIXA CAIXA, @QTD_PIPES PIPES

	select ID_COLETA,DISTRIBUICAO,PRODUTO,QTDE, substring(CAIXA,1,1) as PACK,
	ROW_NUMBER() OVER (PARTITION BY DISTRIBUICAO order by DISTRIBUICAO,ID_COLETA) as COD_COLETA
	--into #DISTRIBUICAO_COLETA
	FROM PDA_WMS_TB_DISTRIBUICAO_COLETA
	WHERE DISTRIBUICAO = '00002083'
