SELECT *
       FROM (SELECT FILIAL AS FILIAL, COD_FILIAL ,CGC_CPF,RIGHT(COD_FILIAL,4) AS LINX , SUBSTRING(RTRIM(LTRIM(CGC_CPF)), 9,4) AS CNPJ FROM CAEDU.DBO.CGP_VW_UNIDADES ) A 
      WHERE (SUBSTRING(RTRIM(LTRIM(A.CGC_CPF)), 9,4) = '0006' OR RIGHT(COD_FILIAL,4) = '0006'  )
      ORDER BY SUBSTRING(RTRIM(LTRIM(A.CGC_CPF)), 9,4)