select E.FILIAL, E.PRODUTO, E.COR_PRODUTO, E.ESTOQUE, PP.PRECO1 
from estoque_produtos E
INNER JOIN PRODUTOS P ON P.PRODUTO=E.PRODUTO
INNER JOIN PRODUTOS_PRECOS PP ON PP.CODIGO_TAB_PRECO='73' AND PP.PRODUTO=E.PRODUTO
where filial='LOJA VIRTUAL' AND P.ENVIA_VAREJO_INTERNET=1