SELECT        dbo.PRODUTOS.PRODUTO, dbo.PRODUTOS.CLASSIF_FISCAL, dbo.PRODUTOS.TIPO_PRODUTO, dbo.PRODUTOS.DESC_PRODUTO, dbo.PRODUTOS.GRIFFE, dbo.PRODUTOS.LINHA, dbo.PRODUTOS.GRUPO_PRODUTO, 
                         dbo.PRODUTOS.SUBGRUPO_PRODUTO, LTRIM(RTRIM(dbo.PRODUTOS.GRIFFE)) + LTRIM(RTRIM(dbo.PRODUTOS.LINHA)) + LTRIM(RTRIM(dbo.PRODUTOS.GRUPO_PRODUTO)) 
                         + LTRIM(RTRIM(dbo.PRODUTOS.SUBGRUPO_PRODUTO)) + LTRIM(RTRIM(dbo.PRODUTOS.DESC_PRODUTO)) AS CHAVE, dbo.PRODUTOS.COLECAO, dbo.PRODUTOS.GRADE, dbo.PRODUTOS.DESC_PROD_NF, 
                         dbo.PRODUTOS.UNIDADE, dbo.PRODUTOS.PESO, dbo.PRODUTOS.REVENDA, dbo.PRODUTOS.REFER_FABRICANTE, dbo.PRODUTOS.SORTIMENTO_COR, dbo.PRODUTOS.FABRICANTE, 
                         dbo.PRODUTOS.SORTIMENTO_TAMANHO, dbo.PRODUTOS.VARIA_PRECO_COR, dbo.PRODUTOS.VARIA_PRECO_TAM, dbo.PRODUTOS.PONTEIRO_PRECO_TAM, dbo.PRODUTOS.VARIA_CUSTO_COR, 
                         dbo.PRODUTOS.PERTENCE_A_CONJUNTO, dbo.PRODUTOS.TRIBUT_ICMS, dbo.PRODUTOS.TRIBUT_ORIGEM, dbo.PRODUTOS.VARIA_CUSTO_TAM, dbo.PRODUTOS.CUSTO_REPOSICAO1, 
                         dbo.PRODUTO_CORES.COR_PRODUTO, dbo.PRODUTO_CORES.DESC_COR_PRODUTO, dbo.PRODUTOS_BARRA.CODIGO_BARRA, dbo.PRODUTOS_PACKS_PERMITIDOS.PACK, dbo.PRODUTOS_PACKS_PERMITIDOS.QTDE, 
                         dbo.PRODUTOS_PACKS_PERMITIDOS.Q1, dbo.PRODUTOS_PRECOS.CODIGO_TAB_PRECO, dbo.PRODUTOS_PRECOS.PRECO1, dbo.TABELAS_PRECO.TABELA, dbo.COLECOES.DESC_COLECAO
FROM            dbo.PRODUTOS INNER JOIN
                         dbo.PRODUTO_CORES ON dbo.PRODUTOS.PRODUTO = dbo.PRODUTO_CORES.PRODUTO INNER JOIN
                         dbo.PRODUTOS_BARRA ON dbo.PRODUTO_CORES.PRODUTO = dbo.PRODUTOS_BARRA.PRODUTO AND dbo.PRODUTO_CORES.COR_PRODUTO = dbo.PRODUTOS_BARRA.COR_PRODUTO INNER JOIN
                         dbo.PRODUTOS_PACKS_PERMITIDOS ON dbo.PRODUTOS.PRODUTO = dbo.PRODUTOS_PACKS_PERMITIDOS.PRODUTO INNER JOIN
                         dbo.PRODUTOS_PRECOS ON dbo.PRODUTOS.PRODUTO = dbo.PRODUTOS_PRECOS.PRODUTO INNER JOIN
                         dbo.TABELAS_PRECO ON dbo.PRODUTOS_PRECOS.CODIGO_TAB_PRECO = dbo.TABELAS_PRECO.CODIGO_TAB_PRECO INNER JOIN
                         dbo.COLECOES ON dbo.PRODUTOS.COLECAO = dbo.COLECOES.COLECAO
WHERE        (dbo.PRODUTOS.DATA_CADASTRAMENTO = '20190531') AND (dbo.PRODUTOS.OBS LIKE 'PRODUTO CHIK%')