

--select * from PROPRIEDADE where tabela = 'PRODUTOS'

--SELECT * FROM UNOUS_LINX_MAT_ALOC

SELECT P.PRODUTO, P.DESC_PRODUTO, H.CODIGO_FATOR, H.GRIFFE, H.LINHA, 
H.GRUPO_PRODUTO, H.SUBGRUPO_PRODUTO, H.UNOUS_NIVEL, PFLEX.VALOR_PROPRIEDADE AS VALOR_FLEX_ATUAL,
PFATOR.VALOR_PROPRIEDADE AS VALOR_FATOR_P_ATUAL, P.FATOR_P, 
CASE WHEN P.FATOR_P IN (1,2) THEN 'P1/P2' WHEN P.FATOR_P IN (3,4) THEN 'P3/P4' ELSE '' END AS P_CORRETO,
CASE WHEN UNOUS_NIVEL = 'COR' THEN (SELECT TOP 1 DESC_COR_PRODUTO FROM PRODUTO_CORES PC WHERE P.PRODUTO = PC.PRODUTO) ELSE '' END as VALOR_COR
FROM 
(select CODIGO_FATOR, GRIFFE, LINHA, GRUPO_PRODUTO, SUBGRUPO_PRODUTO, UNOUS_NIVEL 
from CAE_PRODUTOS_FATOR_P
GROUP BY CODIGO_FATOR, GRIFFE, LINHA, GRUPO_PRODUTO, SUBGRUPO_PRODUTO, UNOUS_NIVEL) AS H 
INNER JOIN PRODUTOS P 
	ON P.GRIFFE=H.GRIFFE AND P.LINHA=H.LINHA 
		AND P.GRUPO_PRODUTO = H.GRUPO_PRODUTO AND P.SUBGRUPO_PRODUTO = H.SUBGRUPO_PRODUTO
LEFT JOIN PROP_PRODUTOS PFLEX ON PFLEX.PRODUTO = P.PRODUTO AND PFLEX.PROPRIEDADE='00105'
LEFT JOIN PROP_PRODUTOS PFATOR ON PFATOR.PRODUTO = P.PRODUTO AND PFATOR.PROPRIEDADE='00107'
ORDER BY CODIGO_FATOR

