

declare @nEmpresa int, @NOVO_CODIGO VARCHAR(6)
set @nEmpresa = 1

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'CALCA - JEANS','018','TIPO DE PRODUTOS','CALCA - JEANS')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'CALCA - SARJA','018','TIPO DE PRODUTOS','CALCA - SARJA')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'INTEIRO - JEANS','018','TIPO DE PRODUTOS','INTEIRO - JEANS')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'INTEIRO - SARJA','018','TIPO DE PRODUTOS','INTEIRO - SARJA')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'SHORT/BERMUDA - JEANS','018','TIPO DE PRODUTOS','SHORT/BERMUDA - JEANS')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'SHORT/BERMUDA - SARJA','018','TIPO DE PRODUTOS','SHORT/BERMUDA - SARJA')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'TOP - JEANS','018','TIPO DE PRODUTOS','TOP - JEANS')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'TOP - SARJA','018','TIPO DE PRODUTOS','TOP - SARJA')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'1/2 COXA','019','FITS-JEANS','1/2 COXA')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'BLUSA','019','FITS-JEANS','BLUSA')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'CAMISA M/C','019','FITS-JEANS','CAMISA M/C')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'CAMISA M/L','019','FITS-JEANS','CAMISA M/L')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'CICLISTA','019','FITS-JEANS','CICLISTA')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'CIGARRETE','019','FITS-JEANS','CIGARRETE')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'COLETE','019','FITS-JEANS','COLETE')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'CONFORT','019','FITS-JEANS','CONFORT')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'CROPPED','019','FITS-JEANS','CROPPED')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'CURTO','019','FITS-JEANS','CURTO')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'FLARE','019','FITS-JEANS','FLARE')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'HOT PANTS','019','FITS-JEANS','HOT PANTS')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'JAQUETA','019','FITS-JEANS','JAQUETA')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'JEGGING','019','FITS-JEANS','JEGGING')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'MACACÃO CURTO','019','FITS-JEANS','MACACÃO CURTO')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'MACACÃO LONGO','019','FITS-JEANS','MACACÃO LONGO')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'PARKA','019','FITS-JEANS','PARKA')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'RETA','019','FITS-JEANS','RETA')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'SAIA MINI','019','FITS-JEANS','SAIA MINI')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'SKINNY','019','FITS-JEANS','SKINNY')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'SLIM','019','FITS-JEANS','SLIM')

SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.codigo', @nEmpresa, @NOVO_CODIGO OUTPUT  
INSERT INTO CAEDU_LISTA_COMBO(CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES (@NOVO_CODIGO,'VESTIDO CURTO','019','FITS-JEANS','VESTIDO CURTO')

               