SELECT * FROM PARAMETROS WHERE DATA_PARA_TRANSFERENCIA > '20181201'

SELECT * FROM PARAMETROS WHERE PARAMETRO = 'PALMA_CD_ORIGEM_DISTRIB'  

SELECT OBJECT_NAME(ID) AS OBJETO, * FROM SYSCOMMENTS WHERE TEXT LIKE '%CD REGIS%'

