SELECT 
       cm.ERP_CUPS_SEGMENTO 
       ,cm.ERP_CUPS_TIPO_PEDIDO
       ,cm.FORNECEDOR
       ,pr.ERP_CUPS_SUPPLIER
       ,cf.NOME_CLIFOR as [SUPPLIER (PRODUTO)] 
       ,ct.EXPORTADOR as [EXPORTADOR (CONTRATO)]
       ,ct.NUM_CONTRATO
       ,ct.ID_CONTRATO     
       ,cm.CONDICAO_PGTO 
       ,pg.DESC_COND_PGTO
       ,cm.ERP_CUPS_PROCESSO_CCF_CCA
       ,pr.ERP_CUPS_STYLENUMBER as [STYLE NUMBER]
       ,cp.PEDIDO
       ,cp.PRODUTO
       ,pr.GRIFFE 
       ,pr.LINHA
       ,pr.GRUPO_PRODUTO
       ,pr.SUBGRUPO_PRODUTO 
       ,pr.DESC_PRODUTO    
       ,pr.TIPO_PRODUTO
       ,cm.ERP_CUPS_DATA_ACORDADA
       ,cm.ERP_CUPS_EMBARQUE_ATUAL
       ,cm.ERP_CUPS_EMBARQUE_REAL as [EMBARQUE REAL (ETD)]
       ,cm.ERP_CUPS_CHEGADA_PORTO as [CHEGADA PORTO (ETA)]
       ,cm.ERP_CUPS_CHEGADA_CD as [CHEGADA CD]
       ,cp.ENTREGA 
       ,cp.LIMITE_ENTREGA 
       ,cp.ERP_CUPS_CUSTO_FOB as [CUSTO FOB (US$)]
       ,(cp.QTDE_ORIGINAL * isnull(cp.ERP_CUPS_CUSTO_FOB,0))  as [CUSTO FOB TOTAL (US$)]
       ,cp.ERP_CUPS_CUSTO_FOB_MINIMO as [FOB MÍNIMO]
       ,cp.CUSTO1 as [CUSTO] 
       ,(ISNULL(cp.QTDE_ENTREGAR,0) * ISNULL(cp.CUSTO1,0)) as [CUSTO TOTAL A ENTREGAR]
       ,ISNULL((SELECT PRECOS01.PRECO1 FROM PRODUTOS_PRECOS PRECOS01 
       WHERE PRECOS01.PRODUTO = pr.PRODUTO AND PRECOS01.CODIGO_TAB_PRECO='01'),0) as [PRECO VENDA VAREJO]
       ,ISNULL((SELECT PRECOAV.PRECO1 FROM PRODUTOS_PRECOS PRECOAV 
       WHERE PRECOAV.PRODUTO = pr.PRODUTO AND PRECOAV.CODIGO_TAB_PRECO='VA'),0) as [PRECO VA] 
       ,ISNULL((SELECT PRECOAT.PRECO1 FROM PRODUTOS_PRECOS PRECOAT 
       WHERE PRECOAT.PRODUTO = pr.PRODUTO AND PRECOAT.CODIGO_TAB_PRECO='AT'),0) as [PRECO AT]  
       ,pk.QTDE as [Total_PACK]
       ,cp.ERP_CUPS_PACKS_POR_CAIXA as [PACK POR CAIXA]
       ,cp.QTDE_ORIGINAL 
       ,cp.QTDE_ENTREGUE 
       ,cp.QTDE_ENTREGAR 
       ,cp.QTDE_CANCELADA
       ,cm.OBS
       ,cm.TIPO_COMPRA
       ,pr.CLASSIF_FISCAL 
       ,pr.PESO     
       ,pr.FATOR_P 
       ,co.DESC_COLECAO
       ,cm.REQUERIDO_POR 
       ,cm.FILIAL_A_ENTREGAR
       ,(ISNULL((SELECT PRECOS01.PRECO1 FROM PRODUTOS_PRECOS PRECOS01 
       WHERE PRECOS01.PRODUTO = pr.PRODUTO AND PRECOS01.CODIGO_TAB_PRECO='01'),0) - cp.CUSTO1) / ISNULL((SELECT PRECOS01.PRECO1 
       FROM PRODUTOS_PRECOS PRECOS01 WHERE PRECOS01.PRODUTO = pr.PRODUTO AND PRECOS01.CODIGO_TAB_PRECO='01'),1) as [MARGEM]
       ,cb.DESC_COR
       ,cm.NATUREZA_ENTRADA 
       ,pr.TRIBUT_ORIGEM
      ,cm.FILIAL_COBRANCA 
       ,cm.FILIAL_A_FATURAR 
       ,pc.CATEGORIA_PRODUTO
          ,case cm.STATUS_COMPRA
             when '01' then 'APROVADO'
             when '02' then 'EM ESTUDO'
             when '03' then 'REPROVADO'
             when '04' then 'AGUARDANDO SENHA'
             else ''
             end AS STATUS_PEDIDO
   ,pr.ERP_CUPS_EVENTO AS COD_EVENTO,
   lc.descricao as DESC_EVENTO

,CB_COMPRIMENTO.DESCRICAO AS COMPRIMENTO
,CB_CONSTRUCAO.DESCRICAO AS CONSTRUCAO
,CB_COMPOSICAO.descricao AS COMPOSICAO
,CB_FORRO.DESCRICAO AS FORRO
,CB_PRODUTO.descricao AS PRODUTO_DESC
,pr.ERP_LICENCIADO
,pr.ERP_DESC_LICENCIADO
,pr.ERP_TEMA_LICENCIADO
,cm.PEDIDO_FORNECEDOR
FROM  
       dbo.COMPRAS_PRODUTO cp
INNER JOIN  
             dbo.PRODUTOS pr ON cp.PRODUTO = pr.PRODUTO 
INNER JOIN  
       dbo.COLECOES co ON co.COLECAO = pr.COLECAO 
INNER JOIN 
       dbo.PRODUTOS_CATEGORIA pc ON pr.COD_CATEGORIA    = pc.COD_CATEGORIA
INNER JOIN  
       dbo.COMPRAS cm ON cp.PEDIDO = cm.PEDIDO 
INNER JOIN 
       dbo.CORES_BASICAS cb ON cb.COR = cp.COR_PRODUTO
LEFT   JOIN  
       dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL pk   ON (pk.PEDIDO = cp.PEDIDO) and (pk.PRODUTO = cp.PRODUTO)
LEFT JOIN 
       dbo.CADASTRO_CLI_FOR cf ON cf.CLIFOR  = pr.ERP_CUPS_SUPPLIER COLLATE Latin1_General_CI_AS
LEFT JOIN 
       dbo.COND_ENT_PGTOS pg on pg.CONDICAO_PGTO = cm.CONDICAO_PGTO
LEFT JOIN 
       DBO.CAEDU_CUPS_CONTRATOS ct ON ct.ID_CONTRATO = cm.ERP_CUPS_ID_CONTRATO
LEFT JOIN dbo.CAEDU_LISTA_COMBO lc 
ON lc.codigo = pr.ERP_CUPS_EVENTO
LEFT JOIN 
 DBO.CAEDU_LISTA_COMBO CB_COMPRIMENTO ON CB_COMPRIMENTO.codigo = PR.ERP_CUPS_COMPRIMENTO AND CB_COMPRIMENTO.id_dominio='003'
LEFT JOIN 
 DBO.CAEDU_LISTA_COMBO CB_CONSTRUCAO  ON CB_CONSTRUCAO.codigo = PR.ERP_CUPS_CONTRUCAO AND CB_CONSTRUCAO.ID_DOMINIO = '004'
LEFT JOIN 
 DBO.CAEDU_LISTA_COMBO CB_COMPOSICAO ON  CB_COMPOSICAO.codigo = PR.ERP_CUPS_COMPOSICAO AND CB_COMPOSICAO.id_dominio='005'
LEFT JOIN 
 DBO.CAEDU_LISTA_COMBO CB_FORRO ON CB_FORRO.codigo = PR.ERP_CUPS_FORRO AND CB_FORRO.id_dominio='008'
LEFT JOIN 
 DBO.CAEDU_LISTA_COMBO CB_PRODUTO ON CB_PRODUTO.codigo = PR.ERP_CUPS_PRODUTO AND CB_PRODUTO.id_dominio='007'

WHERE  
       (cm.FORNECEDOR IN ('KOMPORT','CD ARAQUARI','CD NAVEGANTES')) 
       AND ( cp.ENTREGA>43466) 
       AND (cm.NATUREZA_ENTRADA in ('221.01','200.01'))
	   
ORDER BY 
       cp.PEDIDO