/*select GRADE, GRADE_BASE, TAMANHOS_DIGITADOS,
TAMANHO_1, TAMANHO_2, TAMANHO_3, TAMANHO_4, TAMANHO_5, TAMANHO_6, TAMANHO_7, TAMANHO_8, 
TAMANHO_9, TAMANHO_10, TAMANHO_11, TAMANHO_12, TAMANHO_13, TAMANHO_14, TAMANHO_15, TAMANHO_16
from produtos_tamanhos*/


SELECT b.PRODUTO, count(*) as qty 
FROM PRODUTOS a
inner join produto_cores b on b.PRODUTO=a.PRODUTO
WHERE a.DATA_CADASTRAMENTO >= '20220501' AND a.DATA_CADASTRAMENTO <= '20221031'
AND a.PRODUTO NOT IN (SELECT PRODUTO FROM ESTOQUE_PROD1_ENT) 
group by b.PRODUTO
having count(*)>1


SELECT * FROM TRANSACOES WHERE CONTROL_SISTEMA LIKE '9996%'


select GRADE, GRADE_BASE, TAMANHOS_DIGITADOS, TAMANHO_1, TAMANHO_2, TAMANHO_3, TAMANHO_4, TAMANHO_5, 
TAMANHO_6, TAMANHO_7, TAMANHO_8, TAMANHO_9, TAMANHO_10, TAMANHO_11, TAMANHO_12, TAMANHO_13, TAMANHO_14, 
TAMANHO_15, TAMANHO_16
from PRODUTOS_TAMANHOS where grade = 'G AO GG'

SELECT PRODUTO, DESC_PRODUTO, ERP_QTD_PACK, GRADE 
FROM PRODUTOS A 
WHERE a.DATA_CADASTRAMENTO >= '20220501' AND a.DATA_CADASTRAMENTO <= '20221031'