SELECT * FROM PRODUTOS_PACKS_PERMITIDOS WHERE PRODUTO ='70055884'


select * from entradas where nf_entrada = '000018513' and FILIAL='CD NAVEGANTES'


select FP.* 
--SELECT FP.PRODUTO, FP.NF_SAIDA, PRODUTO, COR_PRODUTO, QTDE
from FATURAMENTO A
INNER JOIN FATURAMENTO_PROD FP ON FP.NF_SAIDA=A.NF_SAIDA AND A.SERIE_NF=FP.SERIE_NF --AND A.NOME_CLIFOR=FP.
where TIPO_FATURAMENTO='TRANSFERENCIA' and A.NOME_CLIFOR='CD REGIS' and A.FILIAL='CD NAVEGANTES'
--AND A.EMISSAO>'20180601' AND PEDIDO IS NULL
AND A.NF_SAIDA='000018513'--'000019617' 


70055884    


select * from 70055884



SELECT CAST(1 AS BIT) AS SELECAO, PACK,PRODUTO,NF,SERIE,A.ID_COLETA ETIQUETA,B.STATUS
 FROM  PDA_WMS_TB_RECEBIMENTO_IMPORTADO_COLETA A 
 INNER JOIN PDA_WMS_TB_REC_CD_STATUS_RECEBIMENTO B  
 ON (RTRIM(A.NF)+' '+RTRIM(SERIE) = B.PEDIDO) 
 WHERE /*B.STATUS>=3 */ 1=1 
 AND A.NF='000018513' AND SERIE='02' 



pda_in_reserva_distribuicao