

select  
	TABELA_LX_CEST.CODIGO_CEST, 
	TABELA_LX_NCM.CODIGO_NCM, 
	Cast(TABELA_LX_CEST.DESCRICAO As VARCHAR(254)) As DESCRICAO, 
	CEST_NCM.ID, TABELA_LX_CEST.INATIVO 
from TABELA_LX_CEST   
JOIN CEST_NCM ON TABELA_LX_CEST.ID = CEST_NCM.ID_CEST 
JOIN TABELA_LX_NCM ON CEST_NCM.ID_NCM = TABELA_LX_NCM.ID 
where  TABELA_LX_CEST.CODIGO_CEST LIKE '2006300' 
And CEST_NCM.INATIVO = 0  
And TABELA_LX_NCM.INATIVO = 0  
And TABELA_LX_CEST.INATIVO = 0  
and TABELA_LX_NCM.CODIGO_NCM = '39233000'

go


select ID_CEST_NCM,CLASSIF_FISCAL, P.PRODUTO, P.DESC_PRODUTO, X.* 
from produtos p
LEFT JOIN 
(select  TABELA_LX_CEST.CODIGO_CEST, TABELA_LX_NCM.CODIGO_NCM, Cast(TABELA_LX_CEST.DESCRICAO As VARCHAR(254)) As DESCRICAO, 
		CEST_NCM.ID, TABELA_LX_CEST.INATIVO 
from TABELA_LX_CEST   
JOIN CEST_NCM ON TABELA_LX_CEST.ID = CEST_NCM.ID_CEST 
JOIN TABELA_LX_NCM ON CEST_NCM.ID_NCM = TABELA_LX_NCM.ID 
where	1=1
		And CEST_NCM.INATIVO = 0  
		And TABELA_LX_NCM.INATIVO = 0  
		And TABELA_LX_CEST.INATIVO = 0) X ON X.CODIGO_NCM = P.CLASSIF_FISCAL AND X.ID=P.ID_CEST_NCM
where ID_CEST_NCM is not null
and DATA_CADASTRAMENTO>'20260101'




