select 
	NULL as ROMANEIO_PRODUTO,
	a.NOME_CLIFOR as loja,
	F.COD_FILIAL AS CODIGO_LOJA,
	a.emissao as data,
	NULL AS ecf,
	NULL AS cupom,
	b.TOTAL_ENTRADAS AS qtde,
	b.valor,
	b.produto, 
	b.cor_produto,
	NULL  as codigo_barra,
	a.NF_ENTRADA,
	a.SERIE_NF_ENTRADA,
	EN1,
	EN2,
	EN3,
	EN4,
	EN5,
	EN6,
	EN7,
	EN8,
	EN9,
	EN10,
	EN11,
	EN12,
	EN13,
	EN14,
	EN15,
	EN16

FROM ENTRADAS A

INNER JOIN 
	FILIAIS F 
		ON F.FILIAL = A.NOME_CLIFOR
INNER JOIN 
	ENTRADAS_PRODUTO B ON B.NF_ENTRADA = A.NF_ENTRADA 
		AND B.SERIE_NF_ENTRADA = A.SERIE_NF_ENTRADA 
		AND B.NOME_CLIFOR = A.NOME_CLIFOR 
WHERE 
	(a.emissao between '20151001' and '20170430')
	AND A.COD_TRANSACAO = 'ENTRADAS_102' 
	AND A.NATUREZA = '250.01'        

/*
SELECT B.* 
FROM ENTRADAS A
INNER JOIN ENTRADAS_PRODUTO B ON B.NF_ENTRADA = A.NF_ENTRADA AND B.SERIE_NF_ENTRADA = A.SERIE_NF_ENTRADA AND B.NOME_CLIFOR = A.NOME_CLIFOR 
WHERE A.NF_ENTRADA = '000046752' AND A.SERIE_NF_ENTRADA = '02' AND A.NOME_CLIFOR = 'PRAIA GRANDE' AND A.NATUREZA = '250.01'         

LX_CADE ENTRADA
*/