UPDATE FATURAMENTO_ITEM 
SET ITEM_IMPRESSAO = '0'+LTRIM(RTRIM(ITEM_IMPRESSAO))
WHERE NF_SAIDA IN (
SELECT NF_SAIDA
FROM FATURAMENTO F (NOLOCK)
WHERE filial = 'CD NAVEGANTES' AND NOME_CLIFOR='CD BARRA VELHA' AND NF_SAIDA NOT IN ('000022573','000022574','000022577') )
AND filial = 'CD NAVEGANTES' AND SERIE_NF='02'
AND LEN(ITEM_IMPRESSAO)=3





UPDATE FATURAMENTO_IMPOSTO 
SET ITEM_IMPRESSAO = '0'+LTRIM(RTRIM(ITEM_IMPRESSAO))
WHERE LEN(ITEM_IMPRESSAO)=3 AND FILIAL='CD NAVEGANTES' AND SERIE_NF='02'