insert into PDA_WMS_TB_ARMAZENAGEM_PALETE(PALETE,PACK,PRODUTO,QUANTIDADE) values ('13','A','12080026',42)

insert into PDA_WMS_TB_ARMAZENAGEM(ID_ENDERECO,PALETE) values (113,'13')


select * from PDA_WMS_TB_ARMAZENAGEM_PALETE

select * from PDA_WMS_TB_ARMAZENAGEM


SELECT TOT_QTDE_ORIGINAL,ERP_TOTAL_QTD_DISTRIB, ERP_PERCENT_DISTRIB, * FROM COMPRAS WHERE ERP_TOTAL_QTD_DISTRIB IS NOT NULL

SELECT * FROM [dbo].[PRODUTOS_PACKS_PERMITIDOS] WHERE PRODUTO = '12080026'    

SELECT * FROM [dbo].[PRODUTOS] WHERE PRODUTO = '12080026'    


SELECT * FROM CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL WHERE PEDIDO = '151073'

SELECT * FROM ESTOQUE_PRODUTOS WHERE PRODUTO = '12080026'

SELECT * FROM COMPRAS WHERE PEDIDO = '151073'

SELECT 8400/120

