/*ATUALIZADA*/
SELECT
	 DAT_ESTOQUE = CAST(GETDATE()-1 AS DATE)
	,SK_DIA = CAST(CONVERT (VARCHAR(8), GETDATE() - 1, 112) AS INTEGER)
	,FILIAL = RTRIM(LTRIM(A.FILIAL))
	,PRODUTO = UPPER(RTRIM(LTRIM(A.PRODUTO)))
	,CUSTO = ISNULL(B.PRECO1,0.00)
	,CUSTO_ORIGINAL = ISNULL(D.PRECO1,0.00)
	,PRECO_CAEDU = ISNULL(CASE WHEN C.PRECO1 = 0 THEN FL.PRECO1 ELSE C.PRECO1 END,0.00)
	,COR_PRODUTO = RTRIM(LTRIM(A.COR_PRODUTO))
	,COR_LOOKP = RTRIM(LTRIM(PC.DESC_COR_PRODUTO))
	,TAMANHO_GRADE = RTRIM(LTRIM(X.GRADE))
	,0 AS TAMANHO
	,QTD_ESTOQUE = X.ESTOQUE_COD_BARRA
	,QTD_IDADE_DIAS_ESTOQUE = CASE WHEN ISNULL(DATEDIFF (DAY, ISNULL(G.ULTIMA_ENTRADA, GETDATE()-1), GETDATE()-1), 0) = -1 THEN 0 ELSE ISNULL(DATEDIFF (DAY, ISNULL(G.ULTIMA_ENTRADA, GETDATE()-1), GETDATE()-1), 0) END
	,QTD_IDADE_ESTOQUE = CASE WHEN ISNULL(DATEDIFF (DAY, ISNULL(G.ULTIMA_ENTRADA, GETDATE()-1), GETDATE()-1), 0) = -1 THEN 0 ELSE (A.ESTOQUE * ISNULL(DATEDIFF (DAY, ISNULL(G.ULTIMA_ENTRADA, GETDATE()-1), GETDATE()-1), 0)) END
	,QTD_IDADE_DIAS_ESTOQUE_CD = ISNULL(DATEDIFF (DAY, ISNULL(F.ULTIMA_ENTRADA, GETDATE()-1), GETDATE()-1), 0)
	,VLR_ESTOQUE = CASE WHEN C.PRECO1 = 0 THEN FL.PRECO1 ELSE C.PRECO1 END
	,VLR_CUSTO_TOTAL_ESTOQUE = X.ESTOQUE_COD_BARRA * (CASE WHEN C.PRECO1 = 0 THEN FL.PRECO1 ELSE C.PRECO1 END)
	,ULTIMA_ENTRADA = CAST(ISNULL(G.ULTIMA_ENTRADA,GETDATE()-1) AS DATE)-- CASO VAZIO GETDATE - 1
	,SK_DIA_ULT_ENTRADA = CAST(CONVERT (VARCHAR(8), ISNULL(G.ULTIMA_ENTRADA,GETDATE()-1), 112) AS INTEGER)-- CASO VAZIO GETDATE - 1
	,SK_DIA_ULT_ENTRADA_CD = CAST(CONVERT (VARCHAR(8), ISNULL(F.ULTIMA_ENTRADA, GETDATE()-1), 112) AS INTEGER)-- CASO VAZIO GETDATE - 1
	,0 AS QTD_POSICAO_ULT_ENT
	,QTD_EMBALADA = COALESCE(Z.ESTOQUE_QTD_EMBALADA,0)
	,QTD_PULMAO =	CASE
						WHEN
							(P.TRIBUT_ORIGEM IN (1,6) AND PF.VALOR_PROPRIEDADE = 'SIM')
						THEN
							(X.ESTOQUE_COD_BARRA-COALESCE(Z.ESTOQUE_QTD_EMBALADA,0))
						ELSE
							0
					END
	,VLR_CUSTO_TOTAL = X.ESTOQUE_COD_BARRA * (CASE WHEN B.PRECO1 = 0 THEN FL.PRECO1 ELSE B.PRECO1 END)
	,VLR_CUSTO_ORIGINAL_TOTAL = X.ESTOQUE_COD_BARRA * (CASE WHEN D.PRECO1 = 0 THEN FL.PRECO1 ELSE D.PRECO1 END)
	,PRECO_CONTABIL = ISNULL(S.PRECO1, 0.00)
FROM
	CAEDU.DBO.ESTOQUE_PRODUTOS A WITH (NOLOCK)
LEFT JOIN
	CAEDU.DBO.PRODUTO_CORES PC WITH (NOLOCK)
ON
	A.PRODUTO = PC.PRODUTO
AND
	A.COR_PRODUTO = PC.COR_PRODUTO
LEFT JOIN
   (SELECT PRODUTO, PRECO1 FROM CAEDU.DBO.PRODUTOS_PRECOS WITH (NOLOCK) WHERE CODIGO_TAB_PRECO = '00') B
ON
	A.PRODUTO = B.PRODUTO
LEFT JOIN
   (SELECT PRODUTO, PRECO1 FROM CAEDU.DBO.PRODUTOS_PRECOS WITH (NOLOCK) WHERE CODIGO_TAB_PRECO = '05') C
ON
	A.PRODUTO = C.PRODUTO
LEFT JOIN
   (SELECT PRODUTO, PRECO1 FROM CAEDU.DBO.PRODUTOS_PRECOS WITH (NOLOCK) WHERE CODIGO_TAB_PRECO = '01') D
ON
	A.PRODUTO = D.PRODUTO
/*PRECO DA LOJA SÃO MATHEUS CONFORME SOLICITAÇÃO DO MARCIO E NATALIA, VIA EMAIL*/
LEFT JOIN
   (SELECT PRODUTO, PRECO1 FROM CAEDU.DBO.PRODUTOS_PRECOS WITH (NOLOCK) WHERE CODIGO_TAB_PRECO = '11') FL
ON
	A.PRODUTO = FL.PRODUTO
LEFT JOIN
   (SELECT PRODUTO, PRECO1 FROM CAEDU.DBO.PRODUTOS_PRECOS WITH (NOLOCK) WHERE CODIGO_TAB_PRECO = '85') S
ON
	A.PRODUTO = S.PRODUTO
LEFT JOIN
	(
		SELECT
			 PRODUTO
			,COR_PRODUTO
			,CODIGO_FILIAL
			,MIN(DATA_VENDA) AS DATA_PRIMEIRA_SAIDA
		FROM
			CAEDU.DBO.LOJA_VENDA_PRODUTO WITH (NOLOCK)
		WHERE
			QTDE <> 0
		GROUP BY
			 PRODUTO
			,COR_PRODUTO
			,CODIGO_FILIAL
	) E
ON
	A.PRODUTO = E.PRODUTO
AND
	A.FILIAL = E.CODIGO_FILIAL
AND
	A.COR_PRODUTO = E.COR_PRODUTO
LEFT JOIN
	(
		SELECT
			 COD_PRODUTO
			,MAX(ULTIMA_ENTRADA) AS ULTIMA_ENTRADA
		FROM
			(
				SELECT
					 BI.PRODUTO AS COD_PRODUTO
					,CAST(MAX(AI.EMISSAO) AS DATE) AS ULTIMA_ENTRADA
				FROM
					CAEDU.DBO.LOJA_ENTRADAS AI WITH (NOLOCK)
				INNER JOIN
					CAEDU.DBO.LOJA_ENTRADAS_PRODUTO BI WITH (NOLOCK)
				ON
					AI.ROMANEIO_PRODUTO = BI.ROMANEIO_PRODUTO
				AND
					AI.FILIAL = BI.FILIAL
				WHERE
					AI.FILIAL IN ('CD REGIS','CD CAJAMAR') AND AI.FILIAL_ORIGEM = 'CD ARAQUARI'
					/* colocar cd cajamar aqui e cd barra velha na origem*/
				GROUP BY
					BI.PRODUTO

			UNION

				SELECT
					 EI.CODIGO_ITEM AS COD_PRODUTO
					,CAST(MAX(E.RECEBIMENTO) AS DATE) AS ULTIMA_ENTRADA
				FROM
					CAEDU.DBO.ENTRADAS_ITEM EI WITH (NOLOCK)
				INNER JOIN
					CAEDU.DBO.ENTRADAS E WITH (NOLOCK)
				ON
					EI.NF_ENTRADA=E.NF_ENTRADA
				AND
					EI.SERIE_NF_ENTRADA=E.SERIE_NF_ENTRADA
				AND
					EI.NOME_CLIFOR=E.NOME_CLIFOR
				INNER JOIN
					CAEDU..ENTRADAS_PRODUTO P WITH (NOLOCK)
				ON
					E.NOME_CLIFOR = P.NOME_CLIFOR
				AND
					E.NF_ENTRADA = P.NF_ENTRADA
				AND
					E.SERIE_NF_ENTRADA = P.SERIE_NF_ENTRADA
				WHERE
					E.COD_TRANSACAO='ENTRADAS_102'
				AND
					E.FILIAL IN ('CD REGIS','CD CAJAMAR') /*melhoria - deixar somente CD CAJAMAR*/
				AND
					(QTDE_ITEM - QTDE_DEVOLVIDA) > 0
				GROUP BY
					EI.CODIGO_ITEM
			) TESTE
		GROUP BY
			COD_PRODUTO
	) F
ON
	A.PRODUTO = F.COD_PRODUTO
LEFT JOIN
	(
		SELECT
			 COD_PRODUTO
			,COR_PRODUTO
			,COD_FILIAL
			,MAX(ULTIMA_ENTRADA) AS ULTIMA_ENTRADA
		FROM
			(
				SELECT
					 COD_PRODUTO
					,COR_PRODUTO
					,COD_FILIAL
					,MAX(ULTIMA_ENTRADA) AS ULTIMA_ENTRADA
				FROM
					(
						SELECT
							 BI.PRODUTO AS COD_PRODUTO
							,BI.COR_PRODUTO
							,BI.FILIAL AS COD_FILIAL
							,CAST(MAX(AI.EMISSAO) AS DATE) AS ULTIMA_ENTRADA
						FROM
							CAEDU.DBO.LOJA_ENTRADAS AI WITH (NOLOCK)
						INNER JOIN
							CAEDU.DBO.LOJA_ENTRADAS_PRODUTO BI WITH (NOLOCK)
						ON
							AI.ROMANEIO_PRODUTO = BI.ROMANEIO_PRODUTO
						AND
							AI.FILIAL = BI.FILIAL
						WHERE
							AI.FILIAL IN ('CD REGIS','CD CAJAMAR') /*CD CAJAMAR*/
						AND
							AI.FILIAL_ORIGEM = 'CD ARAQUARI' /*CD BARRA VELHA*/
						GROUP BY
							 BI.PRODUTO
							,BI.COR_PRODUTO
							,BI.FILIAL

					UNION

						SELECT
							 EI.CODIGO_ITEM AS COD_PRODUTO
							,P.COR_PRODUTO
							,E.FILIAL
							,CAST(MAX(E.RECEBIMENTO) AS DATE) AS ULTIMA_ENTRADA
						FROM
							CAEDU.DBO.ENTRADAS_ITEM EI WITH (NOLOCK)
						INNER JOIN
							CAEDU.dbo.ENTRADAS E WITH (NOLOCK)
						ON
							EI.NF_ENTRADA=E.NF_ENTRADA
						AND
							EI.SERIE_NF_ENTRADA=E.SERIE_NF_ENTRADA
						AND
							EI.NOME_CLIFOR=E.NOME_CLIFOR
						INNER JOIN
							CAEDU..ENTRADAS_PRODUTO P WITH (NOLOCK)
						ON
							E.NOME_CLIFOR = P.NOME_CLIFOR
						AND
							E.NF_ENTRADA = P.NF_ENTRADA
						AND
							E.SERIE_NF_ENTRADA = P.SERIE_NF_ENTRADA
						WHERE
							E.COD_TRANSACAO='ENTRADAS_102'
						AND
							E.FILIAL LIKE '%CD %' /*COLOCAR UM IN AQUI E FIXAR OS CDs*/
						AND
							(QTDE_ITEM - QTDE_DEVOLVIDA) > 0
						GROUP BY
							 EI.CODIGO_ITEM
							,P.COR_PRODUTO
							,E.FILIAL
					) TESTE
				GROUP BY
					 COD_PRODUTO
					,COR_PRODUTO
					,COD_FILIAL

				UNION ALL

					SELECT
						 BI.PRODUTO AS COD_PRODUTO
						,BI.COR_PRODUTO
						,BI.FILIAL AS COD_FILIAL
						,CAST(MAX(AI.EMISSAO) AS DATE) AS ULTIMA_ENTRADA
					FROM
						CAEDU.DBO.LOJA_ENTRADAS AI WITH (NOLOCK)
					INNER JOIN
						CAEDU.DBO.LOJA_ENTRADAS_PRODUTO BI WITH (NOLOCK)
					ON
						AI.ROMANEIO_PRODUTO = BI.ROMANEIO_PRODUTO
					AND
						AI.FILIAL = BI.FILIAL
					WHERE
						BI.FILIAL NOT LIKE 'CD%'
					GROUP BY
						 BI.PRODUTO
						,BI.COR_PRODUTO
						,BI.FILIAL
			) DADOS_ULT_ENTRADA
		GROUP BY
			 COD_PRODUTO
			,COR_PRODUTO
			,COD_FILIAL
	) G
ON
	G.COD_PRODUTO = A.PRODUTO
AND
	RTRIM(LTRIM(G.COD_FILIAL)) = RTRIM(LTRIM(A.FILIAL))
AND
	RTRIM(LTRIM(G.COR_PRODUTO)) = RTRIM(LTRIM(A.COR_PRODUTO))
INNER JOIN
	(
		SELECT
			 A.COD_FILIAL
			,A.FILIAL
			,A.PRODUTO
			,A.COR_PRODUTO
			,A.TAMANHO
			,A.GRADE
			,SUM(CAST(A.ESTOQUE_COD_BARRA AS INT)) AS ESTOQUE_COD_BARRA
		FROM
			(
				SELECT
					 F.COD_FILIAL
					,E.FILIAL
					,E.PRODUTO
					,E.COR_PRODUTO
					,PB.TAMANHO
					,PB.GRADE
					,E.ESTOQUE_COD_BARRA
				FROM
					(
						SELECT
							 FILIAL
							,PRODUTO
							,COR_PRODUTO
							,ESTOQUE
							,LTRIM(RTRIM(REPLACE(ESTOQUE_COD_BARRA, '.', ''))) AS ESTOQUE_COD_BARRA
							,ROW_NUMBER() OVER(PARTITION BY FILIAL, PRODUTO, COR_PRODUTO ORDER BY FILIAL, PRODUTO, COR_PRODUTO) AS TAMANHO
						 FROM
							(
								SELECT
									 FILIAL
									,PRODUTO
									,COR_PRODUTO
									,ESTOQUE
									,ES1, ES2, ES3, ES4, ES5, ES6, ES7, ES8, ES9, ES10, ES11, ES12, ES13, ES14, ES15, ES16, ES17, ES18, ES19, ES20, ES21, ES22, ES23, ES24, ES25, ES26, ES27, ES28, ES29, ES30, ES31, ES32, ES33, ES34, ES35, ES36, ES37, ES38, ES39, ES40, ES41, ES42, ES43, ES44, ES45, ES46, ES47, ES48
								 FROM
									ESTOQUE_PRODUTOS WITH (NOLOCK)								 
							) P
						UNPIVOT(ESTOQUE_COD_BARRA FOR ES IN (ES1, ES2, ES3, ES4, ES5, ES6, ES7, ES8, ES9, ES10, ES11, ES12, ES13, ES14, ES15, ES16, ES17, ES18, ES19, ES20, ES21, ES22, ES23, ES24, ES25, ES26, ES27, ES28, ES29, ES30, ES31, ES32, ES33, ES34, ES35, ES36, ES37, ES38, ES39, ES40, ES41, ES42, ES43, ES44, ES45, ES46, ES47, ES48)) AS U
					)E
				LEFT JOIN
					(
						SELECT
							 PRODUTO
							,COR_PRODUTO
							,TAMANHO
							,MAX(GRADE) AS GRADE
							,MAX(COD_SEQUENCIA) AS COD_SEQUENCIA
						FROM
							(
								SELECT 
									 PRODUTO
									,COR_PRODUTO
									,TAMANHO
									,GRADE
									,ROW_NUMBER() OVER(PARTITION BY PRODUTO, COR_PRODUTO, TAMANHO ORDER BY PRODUTO, COR_PRODUTO, TAMANHO) AS COD_SEQUENCIA
								FROM
									PRODUTOS_BARRA WITH (NOLOCK)								
							) ABC
						GROUP BY
							 PRODUTO
							,COR_PRODUTO
							,TAMANHO
					) PB
				ON
					E.PRODUTO = PB.PRODUTO
				AND
					E.COR_PRODUTO = PB.COR_PRODUTO
				AND
					E.TAMANHO = PB.TAMANHO
				INNER JOIN
					FILIAIS F WITH (NOLOCK)
				ON
					F.FILIAL = E.FILIAL
			) A
		WHERE
			A.ESTOQUE_COD_BARRA <> 0
		GROUP BY
			 A.COD_FILIAL
			,A.FILIAL
			,A.PRODUTO
			,A.COR_PRODUTO
			,A.TAMANHO
			,A.GRADE
	) X
ON
	A.PRODUTO = X.PRODUTO
AND
	RTRIM(LTRIM(A.FILIAL)) = RTRIM(LTRIM(X.FILIAL))
AND
	RTRIM(LTRIM(A.COR_PRODUTO)) = RTRIM(LTRIM(X.COR_PRODUTO))
LEFT JOIN
	(
		SELECT DISTINCT
			 F.COD_FILIAL
			,E.FILIAL
			,PB.PRODUTO
			,PB.COR_PRODUTO
			,PB.TAMANHO
			,PB.GRADE
			,E.ESTOQUE_QTD_EMBALADA
		FROM
			(
				SELECT
					 FILIAL
					,PRODUTO
					,COR_PRODUTO
					,QTDE_EMBALADA
					,LTRIM(RTRIM(REPLACE(ESTOQUE_QTD_EMBALADA, '.', ''))) AS ESTOQUE_QTD_EMBALADA
					,ROW_NUMBER() OVER(PARTITION BY FILIAL, PRODUTO, COR_PRODUTO ORDER BY FILIAL, PRODUTO, COR_PRODUTO) AS TAMANHO
				FROM
					(
						SELECT
							 FILIAL
							,PRODUTO
							,COR_PRODUTO
							,SUM(QTDE_EMBALADA) AS QTDE_EMBALADA
							,SUM(E1) AS E1, SUM(E2) AS E2, SUM(E3) AS E3, SUM(E4) AS E4, SUM(E5) AS E5, SUM(E6) AS E6, SUM(E7) AS E7, SUM(E8) AS E8, SUM(E9) AS E9, SUM(E10) AS E10
							,SUM(E11) AS E11, SUM(E12) AS E12, SUM(E13) AS E13, SUM(E14) AS E14, SUM(E15) AS E15, SUM(E16) AS E16, SUM(E17) AS E17, SUM(E18) AS E18, SUM(E19) AS E19, SUM(E20) AS E20
							,SUM(E21) AS E21, SUM(E22) AS E22, SUM(E23) AS E23, SUM(E24) AS E24, SUM(E25) AS E25, SUM(E26) AS E26, SUM(E27) AS E27, SUM(E28) AS E28, SUM(E29) AS E29, SUM(E30) AS E30
							,SUM(E31) AS E31, SUM(E32) AS E32, SUM(E33) AS E33, SUM(E34) AS E34, SUM(E35) AS E35, SUM(E36) AS E36, SUM(E37) AS E37, SUM(E38) AS E38, SUM(E39) AS E39, SUM(E40) AS E40
							,SUM(E41) AS E41, SUM(E42) AS E42, SUM(E43) AS E43, SUM(E44) AS E44, SUM(E45) AS E45, SUM(E46) AS E46, SUM(E47) AS E47, SUM(E48) AS E48
						FROM
							VENDAS_PROD_EMBALADO WITH (NOLOCK)
						GROUP BY
							 FILIAL
							,PRODUTO
							,COR_PRODUTO
					) P
				UNPIVOT(ESTOQUE_QTD_EMBALADA FOR ES IN (E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26, E27, E28, E29, E30, E31, E32, E33, E34, E35, E36, E37, E38, E39, E40, E41, E42, E43, E44, E45, E46, E47, E48)) AS U
			)E
		INNER JOIN
			(
				SELECT
					 PRODUTO
					,COR_PRODUTO
					,TAMANHO
					,MAX(GRADE) AS GRADE
					,MAX(COD_SEQUENCIA) AS COD_SEQUENCIA
				FROM
				(
					SELECT 
						 PRODUTO
						,COR_PRODUTO
						,TAMANHO
						,GRADE
						,ROW_NUMBER() OVER(PARTITION BY PRODUTO, COR_PRODUTO, TAMANHO ORDER BY PRODUTO, COR_PRODUTO, TAMANHO) AS COD_SEQUENCIA
					FROM
						PRODUTOS_BARRA WITH (NOLOCK)
				) ABC
				GROUP BY
					 PRODUTO
					,COR_PRODUTO
					,TAMANHO
			) PB
		ON
			PB.PRODUTO = E.PRODUTO
		AND
			PB.COR_PRODUTO = E.COR_PRODUTO
		AND
			PB.TAMANHO = E.TAMANHO
		INNER JOIN
			FILIAIS F WITH (NOLOCK)
		ON
			F.FILIAL = E.FILIAL
	) Z
ON
	X.PRODUTO = Z.PRODUTO
AND
	RTRIM(LTRIM(X.FILIAL)) = RTRIM(LTRIM(Z.FILIAL))
AND
	RTRIM(LTRIM(X.COR_PRODUTO)) = RTRIM(LTRIM(Z.COR_PRODUTO))
AND
	RTRIM(LTRIM(X.GRADE)) = RTRIM(LTRIM(Z.GRADE))
LEFT JOIN
	PROP_FILIAIS PF WITH (NOLOCK)
ON
	PF.FILIAL=A.FILIAL
AND
	PF.PROPRIEDADE = '00080'
LEFT JOIN
	PRODUTOS P
ON
	A.PRODUTO=P.PRODUTO
WHERE
	X.ESTOQUE_COD_BARRA <> 0
AND
	A.FILIAL NOT IN ('MATRIZ', 'DIVERGENCIA')