SELECT PP.PROPRIEDADE, PP.VALOR_PROPRIEDADE, P.*
FROM PRODUTOS P
INNER JOIN 
(select GRIFFE, LINHA, GRUPO_PRODUTO, SUBGRUPO_PRODUTO from CAE_PRODUTOS_FATOR_P 
where UNOUS_NIVEL = 'FLEX'
GROUP BY GRIFFE, LINHA, GRUPO_PRODUTO, SUBGRUPO_PRODUTO) FP 
	ON FP.GRIFFE=P.GRIFFE 
		AND FP.LINHA = P.LINHA 
		AND FP.GRUPO_PRODUTO = P.GRUPO_PRODUTO 
		AND FP.SUBGRUPO_PRODUTO = P.SUBGRUPO_PRODUTO
LEFT JOIN PROP_PRODUTOS PP ON PP.PRODUTO = P.PRODUTO AND PP.PROPRIEDADE='00105'
