SELECT COMPRAS.PEDIDO, 
       COMPRAS.FORNECEDOR, 
       COMPRAS.FILIAL_A_ENTREGAR, 
       COMPRAS.FILIAL_COBRANCA, 
       COMPRAS.FILIAL_A_FATURAR, 
       COMPRAS.CONDICAO_PGTO, 
       COMPRAS.EMISSAO, 
       COMPRAS.APROVADO_POR, 
       COMPRAS.PEDIDO_FORNECEDOR, 
       COMPRAS.CADASTRAMENTO, 
       COMPRAS.TOT_QTDE_ORIGINAL, 
       COMPRAS.TOT_QTDE_ENTREGAR, 
       COMPRAS.TOT_VALOR_ORIGINAL, 
       COMPRAS.TOT_VALOR_ENTREGAR, 
       COMPRAS.TIPO_COMPRA, 
       COMPRAS.STATUS_APROVACAO, 
       COMPRAS.STATUS_COMPRA, 
       COMPRAS.ERP_PACK_RESTO, 
       COMPRAS_PRODUTO.PRODUTO, 
       COMPRAS_PRODUTO.ENTREGA, 
       COMPRAS_PRODUTO.COR_PRODUTO, 
       PRODUTO_CORES.DESC_COR_PRODUTO, 
       COMPRAS_PRODUTO.LIMITE_ENTREGA, 
       COMPRAS_PRODUTO.CUSTO1, 
       COMPRAS_PRODUTO.QTDE_ORIGINAL, 
       COMPRAS_PRODUTO.QTDE_CANCELADA, 
       COMPRAS_PRODUTO.QTDE_ENTREGUE, 
       COMPRAS_PRODUTO.QTDE_ENTREGAR, 
       COMPRAS_PRODUTO.VALOR_ORIGINAL, 
       COMPRAS_PRODUTO.VALOR_ENTREGUE, 
       COMPRAS_PRODUTO.VALOR_ENTREGAR, 
       COMPRAS_PRODUTO.PACKS, 
       COMPRAS_PRODUTO.CO1, 
       COMPRAS_PRODUTO.CO2, 
       COMPRAS_PRODUTO.CE1, 
       COMPRAS_PRODUTO.CE2, 
       COMPRAS_PRODUTO.QTDE, 
       CAEDU_COMPRAS_PRODUTOS_PACKS.QTDE       AS QTDE_PACK, 
       CAEDU_COMPRAS_PRODUTOS_PACKS.Q1, 
       CAEDU_COMPRAS_PRODUTOS_PACKS.Q2, 
       CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.QTDE AS QTDE_PACK_TOTAL, 
       CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.Q1   AS Q1_PACK_TOTAL, 
       CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.Q2   AS Q2_PACK_TOTAL, 
       PRODUTOS.CLASSIF_FISCAL, 
       PRODUTOS.TIPO_PRODUTO, 
       PRODUTOS.DESC_PRODUTO, 
       PRODUTOS.GRIFFE, 
       PRODUTOS.LINHA, 
       PRODUTOS.GRUPO_PRODUTO, 
       PRODUTOS.SUBGRUPO_PRODUTO, 
       PRODUTOS.GRADE, 
       PRODUTOS.COLECAO, 
       PRODUTOS.REFER_FABRICANTE, 
       PRODUTOS.FABRICANTE, 
       PRODUTOS.TRIBUT_ORIGEM, 
       PRODUTOS.CUSTO_REPOSICAO1, 
       PRODUTOS.INATIVO, 
       PRODUTOS.PRECO_REPOSICAO_1, 
       PRODUTOS.DATA_CADASTRAMENTO, 
       CAST(PRODUTOS.OBS AS VARCHAR(120)) AS OBS, 
       PRODUTOS.FATOR_P, 
       PRODUTOS.ERP_QTD_PACK, 
       PRODUTOS_BARRA.CODIGO_BARRA, 
       PRODUTOS_BARRA.TAMANHO, 
       PRODUTOS_BARRA.GRADE                    AS GRADE_BARRA, 
       PRODUTOS_PACKS_PERMITIDOS.PACK, 
       PRODUTOS_PACKS_PERMITIDOS.QTDE          AS QTDE_PACK_PERMITIDO, 
       PRODUTOS_PACKS_PERMITIDOS.Q1            AS Q1_PACK_PERMITIDO, 
       PRODUTOS_PACKS_PERMITIDOS.Q2            AS Q2_PACK_PERMITIDO 
FROM   COMPRAS 
       INNER JOIN COMPRAS_PRODUTO 
               ON COMPRAS.PEDIDO = COMPRAS_PRODUTO.PEDIDO 
       INNER JOIN CAEDU_COMPRAS_PRODUTOS_PACKS 
               ON COMPRAS.PEDIDO = CAEDU_COMPRAS_PRODUTOS_PACKS.PEDIDO 
       INNER JOIN CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL 
               ON COMPRAS.PEDIDO = 
                  CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.PEDIDO 
       INNER JOIN PRODUTOS 
               ON COMPRAS_PRODUTO.PRODUTO = PRODUTOS.PRODUTO 
       INNER JOIN PRODUTO_CORES 
               ON COMPRAS_PRODUTO.PRODUTO = PRODUTO_CORES.PRODUTO 
                  AND COMPRAS_PRODUTO.COR_PRODUTO = 
                      PRODUTO_CORES.COR_PRODUTO 
                  AND PRODUTOS.PRODUTO = PRODUTO_CORES.PRODUTO 
       INNER JOIN PRODUTOS_BARRA 
               ON PRODUTO_CORES.PRODUTO = PRODUTOS_BARRA.PRODUTO 
                  AND PRODUTO_CORES.COR_PRODUTO = 
                      PRODUTOS_BARRA.COR_PRODUTO 
       INNER JOIN PRODUTOS_PACKS_PERMITIDOS 
               ON PRODUTOS.PRODUTO = PRODUTOS_PACKS_PERMITIDOS.PRODUTO 
WHERE COMPRAS.EMISSAO = '20190603' AND COMPRAS.FORNECEDOR = 'CHIK S CENTER MODAS LTDA'

