select CODIGO_TAB_PRECO, pp.PRODUTO, PRECO1, PRECO2,PRECO3,PRECO4, 
ULT_ATUALIZACAO, pp.DATA_PARA_TRANSFERENCIA
from produtos_precos pp
join 
(select cp.PRODUTO
	from COMPRAS c
	inner join COMPRAS_PRODUTO cp on cp.pedido=c.pedido
where c.EMISSAO> dateadd(dd,-730,getdate())

UNION
 
SELECT LVP.PRODUTO 
FROM LOJA_VENDA LV
INNER JOIN LOJA_VENDA_PRODUTO LVP ON LVP.DATA_VENDA=LV.DATA_VENDA 
										AND LVP.CODIGO_FILIAL=LV.CODIGO_FILIAL
										AND LVP.TICKET = LV.TICKET
WHERE LV.DATA_VENDA > dateadd(dd,-730,getdate())
GROUP BY LVP.PRODUTO) as t1
on t1.PRODUTO = pp.PRODUTO and pp.CODIGO_TAB_PRECO='11' --SAO MATHEUS
where 1=1 and pp.PRODUTO like '%'