select * from estoque_prod_ent where pedido = '217585'  

select * from CSM_TRANSITO_NOTAS where FILIAL_ENTRADA = 'CD NAVEGANTES' AND NF_ENTRADA = '000242494' AND SERIE_NF_ENTRADA='001'

select * from CSM_TRANSITO_NOTAS 
where NOME_CLIFOR='KOMPORT' AND FILIAL_ENTRADA='CD NAVEGANTES'
AND NF_ENTRADA = '000034369'

select * from faturamento where FILIAL = 'CD NAVEGANTES' AND NOME_CLIFOR = 'CD BARRA VELHA' AND NF_SAIDA = '000036358'

-- ENTRADA DO ESTOQUE
SELECT * 
FROM ESTOQUE_PROD_ENT A
INNER JOIN ESTOQUE_PROD1_ENT B 
			ON B.ROMANEIO_PRODUTO = A.ROMANEIO_PRODUTO AND B.FILIAL = A.FILIAL
WHERE A.NF_ENTRADA = '000242494' AND A.FILIAL = 'CD NAVEGANTES'

-- TRANSITO NA LOJA(CD)
SELECT * FROM 
LOJA_ENTRADAS LE 
INNER JOIN LOJA_ENTRADAS_PRODUTO LEP 
			ON LEP.ROMANEIO_PRODUTO = LE.ROMANEIO_PRODUTO AND LEP.FILIAL = LE.FILIAL
WHERE LE.FILIAL = 'CD BARRA VELHA' AND LE.ROMANEIO_NF_SAIDA = '000036235' AND LE.FILIAL_ORIGEM = 'CD NAVEGANTES'
AND PRODUTO = '13090148' AND COR_PRODUTO = '00003'

SELECT * FROM 
LOJA_ENTRADAS LE 
INNER JOIN LOJA_ENTRADAS_PRODUTO LEP 
			ON LEP.ROMANEIO_PRODUTO = LE.ROMANEIO_PRODUTO AND LEP.FILIAL = LE.FILIAL
WHERE LE.EMISSAO >= '20200203' AND LEP.PRODUTO = '13090148' AND LEP.COR_PRODUTO = '00003' AND LE.FILIAL_ORIGEM = 'CD BARRA VELHA' AND le.filial = 'CD CAJAMAR'

select * from fornecedores where fornecedor = 'ACIL TEXTIL'

SELECT * FROM W_ESTOQUE_PRODUTOS_00 WHERE PRODUTO = '13090148' AND COR_PRODUTO='00003' AND FILIAL = 'CD CAJAMAR'


SELECT * FROM VENDAS_PROD_EMBALADO WHERE PRODUTO = '13090148' AND COR_PRODUTO='00003'
