
SELECT  dbo.VENDAS_PROD_EMBALADO.PRODUTO,
RTRIM (dbo.PRODUTOS.GRIFFE) AS GRIFFE,
RTRIM (dbo.PRODUTOS.LINHA) AS LINHA,
RTRIM (dbo.PRODUTOS.GRUPO_PRODUTO) AS GRUPO,
RTRIM (dbo.PRODUTOS.SUBGRUPO_PRODUTO) AS SUBGRUPO,
AVG (dbo.PRODUTOS.CUSTO_REPOSICAO1) AS CUSTO,
dbo.VENDAS_PROD_EMBALADO.NOME_CLIFOR,
dbo.PRODUTOS.FATOR_P,
SUM (dbo.VENDAS_PROD_EMBALADO.QTDE_EMBALADA) AS QTDE,
AVG (dbo.PRODUTOS_PRECOS.PRECO1) AS PRECO 
FROM dbo.VENDAS_PROD_EMBALADO
INNER JOIN dbo.PRODUTOS 
	ON dbo.VENDAS_PROD_EMBALADO.PRODUTO = dbo.PRODUTOS.PRODUTO
INNER JOIN dbo.PRODUTOS_PRECOS 
	ON dbo.PRODUTOS.PRODUTO = dbo.PRODUTOS_PRECOS.PRODUTO
WHERE (dbo.PRODUTOS_PRECOS.CODIGO_TAB_PRECO = '01')
AND (dbo.VENDAS_PROD_EMBALADO.NOME_CLIFOR = 'SP - SH CANTAREIRA')
GROUP BY
	dbo.VENDAS_PROD_EMBALADO.PRODUTO, dbo.PRODUTOS.GRIFFE, dbo.PRODUTOS.LINHA, dbo.PRODUTOS.GRUPO_PRODUTO,
	dbo.PRODUTOS.SUBGRUPO_PRODUTO, dbo.VENDAS_PROD_EMBALADO.NOME_CLIFOR, dbo.PRODUTOS.FATOR_P
ORDER BY dbo.VENDAS_PROD_EMBALADO.NOME_CLIFOR