select * from INFO_LOJAS

INSERT INTO INFO_LOJAS
select '192.168.39.10' as IP, F.FILIAL,F.COD_FILIAL,TPF.CODIGO_TAB_PRECO,'CAEDU' AS BANCO,TP.TABELA, 1 AS ATIVO,'' AS INSTANCIA, 
LEFT(F.FILIAL,3) AS ABV, 'SQL_Latin1_General_CP1_CI_AS' AS COLLATION
FROM FILIAIS F 
INNER JOIN TABELAS_PRECO_FILIAL TPF ON TPF.FILIAL=F.FILIAL
INNER JOIN TABELAS_PRECO TP ON TP.CODIGO_TAB_PRECO=TPF.CODIGO_TAB_PRECO
WHERE COD_FILIAL IN ('000150','000151')
