--TOTAL		4785
--COM BOX   3946 
--FALTA		839 PRA GERAR BOX
-- as outras queries estão dentro do programa c:\dev\prog\importa_base_txt_caixas_pda.prg

WITH SEMBOX (FILIAL,LOJADESTINO,CAIXA,DOCA,CODIGO_FILIAL,DATA,FATURADO)
AS
(
SELECT F.FILIAL, F.FILIAL AS LOJADESTINO,A.CAIXA,A.DOCA,A.CODIGO_FILIAL,A.DATA,A.FATURADO
FROM PDA_WMS_TB_EMBARQUE A
INNER JOIN FILIAIS F ON F.COD_FILIAL=A.CODIGO_FILIAL
LEFT JOIN FATURAMENTO_PROD FP ON FP.CAIXA=A.CAIXA
LEFT JOIN VENDAS_PROD_EMBALADO VE ON VE.CAIXA=A.CAIXA
WHERE 1=1
AND FP.CAIXA IS NULL AND VE.CAIXA IS NULL
AND A.DATA>'20250101' AND A.DATA < CONVERT(varchar,GETDATE(),112)
)

SELECT Z.*, B.distribuicao,
'CX-'+rtrim(z.caixa) as venda,
a.qtde as QTDE_TOTAL, A.PRODUTO,
a.COR_PRODUTO, a.qtde,
a.q1, a.q2, a.q3, a.q4, a.q5, a.q6, a.q7, a.q8, a.q9, a.q10, a.q11, 
a.q12, a.q13, a.q14, a.q15, a.q16, pp.preco1 as custo_1, p.grade, 
p.erp_qtd_pack, 'CD - SP - SAO ROQUE' AS filial_origem 
FROM SEMBOX Z
--LEFT JOIN [CCP\PAULO.DEVIDE].vw_union_distribuicoes B ON B.CAIXA=A.CAIXA
LEFT JOIN [CCP\PAULO.DEVIDE].[TB_CAIXAS_PDA_FASTASMA_4K] B ON B.CAIXA=Z.CAIXA
--LEFT JOIN CAEDU_COMPRAS_PRODUTOS_PACKS A ON A.PEDIDO=B.PEDIDO AND A.PRODUTO=B.PRODUTO AND A.COR_PRODUTO=B.cor_produto
left join PRODUTOS_PACKS_permitidos A on a.produto=B.produto and a.pack=b.PACK and a.Cor_produto=b.Cor_produto
LEFT JOIN PRODUTOS P ON P.PRODUTO = B.PRODUTO
LEFT JOIN PRODUTOS_PRECOS PP on pp.produto = B.produto and pp.CODIGO_TAB_PRECO='02'
WHERE B.distribuicao IS NOT NULL







