/*
SELECT COMPRAS_PRODUTO.PEDIDO, COUNT(DISTINCT COR_PRODUTO) 
FROM COMPRAS_PRODUTO 
INNER JOIN COMPRAS ON COMPRAS.PEDIDO = COMPRAS_PRODUTO.PEDIDO
where COMPRAS.emissao between '20180801' and '20180810'
GROUP BY COMPRAS_PRODUTO.PEDIDO
*/
DECLARE @PEDIDO VARCHAR(8) = '193893'
SELECT 
'C' AS TIPOLINHA,
GRADE, 
'' AS PEDIDO, 
'' AS PRODUTO, 
'' AS COR_PRODUTO, 
'' AS DESC_COR_PRODUTO, 
'' AS QTDE,
CAST(T.TAMANHO_1 AS VARCHAR) AS TAMANHO_1, 
CAST(T.TAMANHO_2 AS VARCHAR) AS TAMANHO_2, 
CAST(T.TAMANHO_3 AS VARCHAR) AS TAMANHO_3, 
CAST(T.TAMANHO_4 AS VARCHAR) AS TAMANHO_4, 
CAST(T.TAMANHO_5 AS VARCHAR) AS TAMANHO_5, 
CAST(T.TAMANHO_6 AS VARCHAR) AS TAMANHO_6, 
CAST(T.TAMANHO_7 AS VARCHAR) AS TAMANHO_7, 
CAST(T.TAMANHO_8 AS VARCHAR) AS TAMANHO_8, 
CAST(T.TAMANHO_9 AS VARCHAR) AS TAMANHO_9, 
CAST(T.TAMANHO_10 AS VARCHAR) AS TAMANHO_10, 
CAST(T.TAMANHO_11 AS VARCHAR) AS TAMANHO_11, 
CAST(T.TAMANHO_12 AS VARCHAR) AS TAMANHO_12, 
CAST(T.TAMANHO_13 AS VARCHAR) AS TAMANHO_13, 
CAST(T.TAMANHO_14 AS VARCHAR) AS TAMANHO_14, 
CAST(T.TAMANHO_15 AS VARCHAR) AS TAMANHO_15, 
CAST(T.TAMANHO_16 AS VARCHAR) AS TAMANHO_16
FROM PRODUTOS_TAMANHOS T (NOLOCK)
WHERE GRADE = (SELECT TOP 1 GRADE 
				FROM COMPRAS_PRODUTO 
				INNER JOIN PRODUTOS ON PRODUTOS.PRODUTO = COMPRAS_PRODUTO.PRODUTO 
				WHERE PEDIDO = @PEDIDO)                  
UNION ALL
select 'D' AS TIPOLINHA, 
B.GRADE,
A.PEDIDO, 
A.PRODUTO, 
A.COR_PRODUTO, 
A.DESC_COR_PRODUTO, 
A.QTDE,
CAST(A.Q1 AS VARCHAR) AS Q1, 
CAST(A.Q2 AS VARCHAR) AS Q2, 
CAST(A.Q3 AS VARCHAR) AS Q3, 
CAST(A.Q4 AS VARCHAR) AS Q4, 
CAST(A.Q5 AS VARCHAR) AS Q5, 
CAST(A.Q6 AS VARCHAR) AS Q6, 
CAST(A.Q7 AS VARCHAR) AS Q7, 
CAST(A.Q8 AS VARCHAR) AS Q8, 
CAST(A.Q9 AS VARCHAR) AS Q9, 
CAST(A.Q10 AS VARCHAR) AS Q10, 
CAST(A.Q11 AS VARCHAR) AS Q11, 
CAST(A.Q12 AS VARCHAR) AS Q12, 
CAST(A.Q13 AS VARCHAR) AS Q13, 
CAST(A.Q14 AS VARCHAR) AS Q14, 
CAST(A.Q15 AS VARCHAR) AS Q15, 
CAST(A.Q16 AS VARCHAR) AS Q16
from CAEDU_COMPRAS_PRODUTOS_PACKS A (NOLOCK)
inner join PRODUTOS B (NOLOCK) ON B.PRODUTO = A.PRODUTO
where pedido = @PEDIDO


