update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021223';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021225';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021280';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021287';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021311';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021352';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021415';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021423';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021453';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021454';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021455';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021493';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021494';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021497';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021578';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021607';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021608';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021609';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021614';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021641';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021654';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021655';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021659';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021681';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021682';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021748';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021768';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021769';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021770';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021782';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021783';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021784';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021785';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021786';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021789';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021835';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021905';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021939';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021944';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021947';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021948';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021949';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021972';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021973';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021974';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021997';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53021998';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53022022';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150001';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150002';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150003';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150004';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150005';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150006';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150017';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150018';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150019';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150020';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150024';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150025';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150026';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150027';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150028';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150029';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150030';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150031';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150032';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150033';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150034';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150035';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150036';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150037';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150038';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150039';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = '53150040';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = 'C3300074';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = 'C3300085';
update produtos set subgrupo_produto = 'CALCA PROGRAMA 1' where produto = 'C3300086';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '25020013';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '25020014';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '25020018';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '25020019';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080004';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080005';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080006';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080007';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080008';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080009';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080010';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080011';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080012';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080013';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080014';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080017';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080018';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080019';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080020';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080021';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080028';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080029';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080030';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080031';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080032';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080033';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080034';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080041';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080042';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080043';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080044';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080045';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080046';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080047';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080048';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080049';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080050';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080051';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080052';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080053';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080054';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080055';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080056';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080057';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080058';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080059';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080060';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080061';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080062';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080063';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080064';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080065';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080066';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080067';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080068';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080069';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080070';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080071';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080072';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080073';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080075';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080076';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080078';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080079';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080080';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080081';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080082';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080083';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080092';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080093';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080094';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080095';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080096';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080097';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080098';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080099';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080100';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080101';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080102';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080103';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080104';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080105';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080106';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080107';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080108';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080109';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080110';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080111';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080116';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080117';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080118';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080119';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080120';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080121';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080128';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080129';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080130';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080131';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080132';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080133';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080134';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080135';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080136';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080137';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080138';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080139';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080140';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080145';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080146';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080147';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080149';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080156';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080157';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080158';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080163';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080164';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080165';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080166';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080167';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080168';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080169';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080170';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080171';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080172';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080173';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080174';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080175';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080176';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080177';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080178';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080179';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080180';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080181';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080182';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080183';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080184';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080185';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080189';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080190';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080191';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080192';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080193';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080194';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080195';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080198';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080199';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080200';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080201';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080202';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080203';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080204';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080205';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080206';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080207';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080208';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080209';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080210';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080211';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080212';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080213';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080214';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080215';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080216';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080217';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080218';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080219';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080220';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080221';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080243';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080244';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080245';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080246';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080247';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080248';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080249';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080250';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080251';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080252';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080253';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080254';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080255';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080256';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080257';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080258';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080259';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080265';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080266';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080267';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080268';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080269';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080270';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080271';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080272';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080273';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080274';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080275';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080276';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080277';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080278';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080279';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080280';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080281';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080282';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080283';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080284';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080285';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080286';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080287';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080288';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080289';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080290';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080291';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080292';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080293';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080311';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080312';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080313';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080330';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080331';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080332';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080333';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080334';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080335';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080336';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080337';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080338';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080339';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080340';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080341';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080345';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080346';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080347';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080348';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080349';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080350';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080351';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080352';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080353';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080354';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080355';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080356';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080357';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080358';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080359';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080360';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080362';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080363';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080364';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080365';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = '44080366';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080385';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080386';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080397';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = '44080398';
update produtos set subgrupo_produto = 'COMPLEMENTO NAS' where produto = 'N4020028';
update produtos set subgrupo_produto = 'COMPLEMENTO NOS' where produto = 'N4020029';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60040191';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60040192';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60040193';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60040194';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60040195';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60040196';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60040197';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60040198';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60040199';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60040200';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60040249';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60040250';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60040251';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60040252';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60040253';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60040254';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060075';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060076';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060077';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060078';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060082';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060083';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060084';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060085';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060086';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060137';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060138';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060139';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060140';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060141';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060142';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060143';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060144';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060190';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060191';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060192';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060193';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060194';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060195';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060196';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060197';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060198';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060199';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060200';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060228';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060231';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60060285';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080002';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080003';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080004';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080005';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080006';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080007';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080008';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080009';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080010';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080011';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080012';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080013';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080014';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080015';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080021';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080022';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080023';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080024';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080025';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080026';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080027';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080028';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080029';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080030';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080031';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080032';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080034';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080035';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080036';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080037';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080038';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080039';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080040';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080041';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080042';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080043';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080044';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080045';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080046';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080047';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080048';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080049';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080050';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080051';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080052';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080053';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080054';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080055';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080056';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080057';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080058';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080059';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080060';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080061';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080062';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080063';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080064';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080065';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA POLAR' where produto = '60080066';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60040201';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60040202';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60040203';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60040204';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60040205';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60040206';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60040207';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60040208';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60040209';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60040210';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60040211';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60040212';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60040255';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60040256';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60040257';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60040258';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60040259';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060079';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060080';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060081';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060087';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060088';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060089';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060090';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060130';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060131';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060132';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060133';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060134';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060135';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060136';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060182';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060183';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060184';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060185';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060186';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060187';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060188';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060189';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60060278';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070002';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070003';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070004';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070005';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070006';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070007';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070021';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070022';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070023';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070024';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070025';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070026';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070027';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070028';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070029';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070030';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070031';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070032';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070033';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070034';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070035';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070036';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070037';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070038';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070039';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070040';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070041';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070042';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070043';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070044';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070045';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070046';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070047';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070048';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070049';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070050';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070051';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070052';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070053';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070054';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070055';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070056';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070057';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070058';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070059';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070060';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070061';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070062';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070063';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070064';
update produtos set subgrupo_produto = 'CAMISOLA/PIJAMA CORAL' where produto = '60070065';
