SELECT TAB.* 
FROM (
select 'PEDIDO' AS TIPO_DISTRIBUICAO,
		PEDIDO AS PEDIDO_DISTRIBUICAO,
		MAX(DATA) AS DATA,
		MAX(DATA_UNOUS) AS DATA_UNOUS,
		CASE WHEN ISNULL(DATA_UNOUS,'')<>'' THEN 'SIM' ELSE 'NÃO' END AS DISTRIBUICAO_UNOUS
from caedu_reserva_automatica

GROUP BY PEDIDO, ISNULL(DATA_UNOUS,'')
UNION 
select 'WMS' AS TIPO_DISTRIBUICAO,
		DISTRIBUICAO AS PEDIDO_DISTRIBUICAO,
		MAX(DATA) AS DATA,
		MAX(DATA_UNOUS) AS DATA_UNOUS,
		CASE WHEN ISNULL(DATA_UNOUS,'')<>'' THEN 'SIM' ELSE 'NÃO' END AS DISTRIBUICAO_UNOUS
from CAEDU_RESERVA_AUTOMATICA_PACK_WMS

GROUP BY DISTRIBUICAO, DATA, ISNULL(DATA_UNOUS,'')
) AS TAB
WHERE (TAB.DATA BETWEEN '@DATA1' AND '@DATA2')
