/*
Style Number
Pedido de Compra
Grife
Custo
DESC_EVENTO
ERP_DESC_LICENCIADO
PIS
COFINS
ICMS
Data de Emissão da NF
*/

select c.ERP_CUPS_STYLENUMBER, c.GRIFFE, c.LINHA, c.GRUPO_PRODUTO, c.SUBGRUPO_PRODUTO,
(select preco1 from produtos_precos where produto=c.PRODUTO and CODIGO_TAB_PRECO='00') as CUSTO_00, 
C.ERP_LICENCIADO, ERP_DESC_LICENCIADO,
d.PEDIDO as PEDIDO_VENDA, E.PRECO1 AS VALOR_PEDIDO_VENDA, A.EMISSAO AS EMISSAO_NOTA,
A.NOME_CLIFOR, 
f1.BASE_IMPOSTO BASE_ICMS, f1.TAXA_IMPOSTO TAXA_ICMS, f1.VALOR_IMPOSTO VALOR_ICMS,
f2.BASE_IMPOSTO BASE_IPI, f2.TAXA_IMPOSTO TAXA_IPI, f2.VALOR_IMPOSTO VALOR_IPI,
f5.BASE_IMPOSTO BASE_PIS, f5.TAXA_IMPOSTO TAXA_PIS, f5.VALOR_IMPOSTO VALOR_PIS,
f6.BASE_IMPOSTO BASE_COFINS, f6.TAXA_IMPOSTO TAXA_COFINS, f6.VALOR_IMPOSTO VALOR_COFINS,
B.*
from faturamento a
inner join FATURAMENTO_PROD b on b.NF_SAIDA=a.NF_SAIDA and b.SERIE_NF=a.SERIE_NF and b.FILIAL=a.FILIAL
inner join PRODUTOS c on c.produto = b.PRODUTO
LEFT join VENDAS d on d.PEDIDO = B.PEDIDO
LEFT join VENDAS_PRODUTO e ON E.PEDIDO = D.PEDIDO AND E.PRODUTO=B.PRODUTO AND E.COR_PRODUTO=B.COR_PRODUTO
left JOIN FATURAMENTO_IMPOSTO f1 /*icms*/ 
	on f1.NF_SAIDA=b.NF_SAIDA and f1.SERIE_NF=b.SERIE_NF and 
		f1.FILIAL=b.FILIAL AND F1.ITEM_IMPRESSAO=b.ITEM_IMPRESSAO 
		and f1.ID_IMPOSTO=1
left JOIN FATURAMENTO_IMPOSTO f2 /*ipi*/
	on f2.NF_SAIDA=b.NF_SAIDA and f2.SERIE_NF=b.SERIE_NF and 
		f2.FILIAL=b.FILIAL AND F2.ITEM_IMPRESSAO=b.ITEM_IMPRESSAO 
		and f2.ID_IMPOSTO=2
left JOIN FATURAMENTO_IMPOSTO f5 /*pis*/
	on f5.NF_SAIDA=b.NF_SAIDA and f5.SERIE_NF=b.SERIE_NF and 
		f5.FILIAL=b.FILIAL AND F5.ITEM_IMPRESSAO=b.ITEM_IMPRESSAO 
		and f5.ID_IMPOSTO=5
left JOIN FATURAMENTO_IMPOSTO f6 /*cofins*/
	on f6.NF_SAIDA=b.NF_SAIDA and f6.SERIE_NF=b.SERIE_NF and 
		f6.FILIAL=b.FILIAL AND F6.ITEM_IMPRESSAO=b.ITEM_IMPRESSAO 
		and f6.ID_IMPOSTO=6
where a.filial = 'VENDA ATACADO'