select  FILIAL, 
SUM(ESTOQUE) AS ESTOQUE, 
SUM(TRANSITO) AS TRANSITO, 
SUM(DISPONIVEL) AS DISPONIVEL, 
SUM(EMBALADO) AS EMBALADO
from W_ESTOQUE_PRODUTOS_00
--where FILIAL = 'SP - METRO CAPAO'
GROUP BY FILIAL
ORDER BY FILIAL
