/* COLECAO */
select COLECAO,
		DESC_COLECAO, 
		INATIVO
from colecoes
ORDER BY INATIVO, DESC_COLECAO

/* TEMAS */
SELECT CODIGO, DESCRICAO 
FROM CAEDU_LISTA_COMBO AS TEMAS
WHERE id_dominio='002'
ORDER BY DESCRICAO

/*TIPO PRODUTO*/
SELECT TIPO_PRODUTO, 
		COD_TIPO_PRODUTO, 
		INATIVO 
FROM PRODUTOS_TIPOS 
ORDER BY INATIVO, TIPO_PRODUTO

/*EVENTOS*/
SELECT CODIGO, DESCRICAO 
FROM CAEDU_LISTA_COMBO AS EVENTOS
WHERE id_dominio='001'
ORDER BY DESCRICAO

/*TIPO COMPRA*/
SELECT TIPO_COMPRA, AE_DOCUMENTO, INDICA_COMPRA_PRODUTO, INDICA_COMPRA_MATERIAL, INDICA_COMPRA_CONSUMO 
FROM COMPRAS_TIPOS 
WHERE INDICA_COMPRA_PRODUTO=1
ORDER BY INDICA_COMPRA_PRODUTO DESC, TIPO_COMPRA

select *  from produtos where DATA_PARA_TRANSFERENCIA > '20230301'

select top 10 * from compras order by DATA_PARA_TRANSFERENCIA desc