select	A.ROMANEIO_PRODUTO, 
		A.FILIAL, 
		A.EMISSAO, 
		A.CM_OPERACAO,
		A.RESPONSAVEL,
		B.PRODUTO,
		B.COR_PRODUTO,
		B.CUSTO1,
		B.CUSTO1 * B.QTDE AS VALOR,
		B.QTDE,
		B.EN_1, 
		B.EN_2, 
		B.EN_3, 
		B.EN_4, 
		B.EN_5, 
		B.EN_6, 
		B.EN_7, 
		B.EN_8, 
		B.EN_9, 
		B.EN_10, 
		B.EN_11, 
		B.EN_12, 
		B.EN_13, 
		B.EN_14, 
		B.EN_15, 
		B.EN_16
from estoque_prod_ent A
INNER JOIN ESTOQUE_PROD1_ENT B 
	ON B.ROMANEIO_PRODUTO=A.ROMANEIO_PRODUTO AND B.FILIAL=A.FILIAL
where 
		(A.EMISSAO BETWEEN '20170111' AND '20180110') 
			and (A.filial = 'CD REGIS') 
			AND (A.CM_OPERACAO IN ('003','026','661'))
ORDER BY A.ROMANEIO_PRODUTO 
 

