select	C.PEDIDO, C.FILIAL_A_ENTREGAR, C.FORNECEDOR, C.CONDICAO_PGTO, 
		C.EMISSAO, C.PEDIDO_FORNECEDOR, C.ERP_CUPS_PROCESSO_CCF_CCA, DESCONTO, 
		TOT_QTDE_ORIGINAL, TOT_QTDE_ENTREGAR, NATUREZA_ENTRADA, TIPO_COMPRA, C.ERP_CUPS_SEGMENTO,
		CP.PRODUTO, CP.COR_PRODUTO, p.DESC_PRODUTO, p.GRADE, left(t.TAMANHOS,len(t.TAMANHOS)-1) as TAMANHOS_GRADE, 
		p.GRIFFE, p.LINHA, p.GRUPO_PRODUTO, p.SUBGRUPO_PRODUTO, 
		cpp.QTDE as TOTAL_PACK, cpp.q1, cpp.q2, cpp.q3, cpp.q4, cpp.q5, cpp.q6, cpp.q7, cpp.q8, 
		cpp.q9, cpp.q10, cpp.q11, cpp.q12, cpp.q13, cpp.q14, cpp.q15, cpp.q16, 
		cp.ENTREGA, CP.LIMITE_ENTREGA, CP.CUSTO1, CP.QTDE_ORIGINAL, CP.QTDE_CANCELADA,
		CP.QTDE_ENTREGUE, CP.QTDE_ENTREGAR, CP.VALOR_ORIGINAL, CP.PACKS, 
		CP.CO1, CP.CO2, CP.CO3, CP.CO4, CP.CO5, CP.CO6, CP.CO7, CP.CO8, CP.CO9, CP.CO10, CP.CO11, CP.CO12, CP.CO13, CP.CO14, CP.CO15, CP.CO16
		,CP.* 
from compras c
inner join compras_produto cp on cp.PEDIDO=c.PEDIDO
INNER JOIN PRODUTOS P ON P.PRODUTO = CP.PRODUTO
INNER JOIN 
(SELECT	GRADE, 
(CASE WHEN TAMANHO_1 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_1)) = '' THEN '' ELSE TAMANHO_1 + '/' END) +
(CASE WHEN TAMANHO_2 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_2)) = '' THEN '' ELSE TAMANHO_2 + '/'  END) +
(CASE WHEN TAMANHO_3 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_3)) = '' THEN '' ELSE TAMANHO_3 + '/'  END) +
(CASE WHEN TAMANHO_4 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_4)) = '' THEN '' ELSE TAMANHO_4 + '/'  END) +
(CASE WHEN TAMANHO_5 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_5)) = '' THEN '' ELSE TAMANHO_5 + '/'  END) +
(CASE WHEN TAMANHO_6 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_6)) = '' THEN '' ELSE TAMANHO_6 + '/'  END) +
(CASE WHEN TAMANHO_7 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_7)) = '' THEN '' ELSE TAMANHO_7 + '/'  END) +
(CASE WHEN TAMANHO_8 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_8)) = '' THEN '' ELSE TAMANHO_8 + '/'  END) +
(CASE WHEN TAMANHO_9 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_9)) = '' THEN '' ELSE TAMANHO_9 + '/'  END) +
(CASE WHEN TAMANHO_10 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_10)) = '' THEN '' ELSE TAMANHO_10 + '/'  END) +
(CASE WHEN TAMANHO_11 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_11)) = '' THEN '' ELSE TAMANHO_11 + '/'  END) +
(CASE WHEN TAMANHO_12 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_12)) = '' THEN '' ELSE TAMANHO_12 + '/'  END) +
(CASE WHEN TAMANHO_13 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_13)) = '' THEN '' ELSE TAMANHO_13 + '/'  END) +
(CASE WHEN TAMANHO_14 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_14)) = '' THEN '' ELSE TAMANHO_14 + '/'  END) +
(CASE WHEN TAMANHO_15 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_15)) = '' THEN '' ELSE TAMANHO_15 + '/'  END) +
(CASE WHEN TAMANHO_16 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_16)) = '' THEN '' ELSE TAMANHO_16 END) AS TAMANHOS
FROM PRODUTOS_TAMANHOS ) AS T ON T.GRADE = P.GRADE
LEFT JOIN CAEDU_COMPRAS_PRODUTOS_PACKS cpp on cpp.PEDIDO=cp.PEDIDO and cpp.PRODUTO=cp.PRODUTO and cpp.COR_PRODUTO=cp.COR_PRODUTO 
where c.TOT_QTDE_ENTREGAR=c.TOT_QTDE_ORIGINAL and C.EMISSAO >= '20210101' and griffe='FEMININO'
order by c.EMISSAO


