select cp.PRODUTO, p.desc_produto, p.grade, 
p.GRIFFE, p.LINHA, p.GRUPO_PRODUTO, p.SUBGRUPO_PRODUTO, p.FABRICANTE,
pc.PROPRIEDADE, pr.TITULO_PROPRIEDADE, pc.VALOR_PROPRIEDADE, pc.DATA_PARA_TRANSFERENCIA
from PROP_COMPRAS pc
inner join PROPRIEDADE pr on pr.PROPRIEDADE=pc.PROPRIEDADE
inner join COMPRAS_PRODUTO cp on cp.PEDIDO = pc.PEDIDO
inner join PRODUTOS p on cp.PRODUTO=p.PRODUTO
where pc.propriedade = '00095' 
and pc.DATA_PARA_TRANSFERENCIA>='20240101' AND pc.DATA_PARA_TRANSFERENCIA<='20240306'
and p.GRIFFE = p.GRIFFE 
order by pc.DATA_PARA_TRANSFERENCIA asc