select p.PRODUTO, p.DESC_PRODUTO, p.GRIFFE, p.LINHA, p.GRUPO_PRODUTO, p.SUBGRUPO_PRODUTO, p.FABRICANTE
from PRODUTOS p
inner join ESTOQUE_PRODUTOS e on e.PRODUTO=p.PRODUTO
WHERE EXISTS (select 1 
from ESTOQUE_PROD_ENT A 
INNER JOIN ESTOQUE_PROD1_ENT B ON B.ROMANEIO_PRODUTO=A.ROMANEIO_PRODUTO AND B.FILIAL=A.FILIAL
where A.NOME_CLIFOR LIKE 'GRENDENE%' AND B.PRODUTO=P.PRODUTO)
AND (es1 > 0 or es2 > 0 or es3 > 0 or es4 > 0 or es5 > 0 or es6 > 0 or es7 > 0 or es8 > 0 
		or es9 > 0 or es10 > 0 or es11 > 0 or es12 > 0 or es13 > 0 or es14 > 0 or es15 > 0 or es16 > 0) 
GROUP BY p.PRODUTO, p.DESC_PRODUTO, p.GRIFFE, p.LINHA, p.GRUPO_PRODUTO, p.SUBGRUPO_PRODUTO, p.FABRICANTE