select FI.FILIAL FILIAL_DE,F.NOME_CLIFOR FILIAL_PARA, SUBSTRING(CONVERT(VARCHAR,F.EMISSAO,112),1,6) AS ANOMES,
FI.CODIGO_ITEM AS PRODUTO, P.GRIFFE, SUM(FI.QTDE_ITEM) AS QTDE
FROM faturamento F
INNER JOIN FATURAMENTO_ITEM FI
	ON FI.NF_SAIDA = F.NF_SAIDA AND FI.SERIE_NF = F.SERIE_NF AND FI.FILIAL = F.FILIAL
INNER JOIN PRODUTOS P ON P.PRODUTO = FI.CODIGO_ITEM
where F.FILIAL = 'CD CAJAMAR' 
AND EMISSAO>='20210301' AND EMISSAO<='20210731'
AND TIPO_FATURAMENTO = 'TRANSFERENCIA' AND COD_TRANSACAO IN ('FATURAMENTO_022','FATURAMENTO_023','FATURAMENTO_052') AND F.NATUREZA_SAIDA LIKE '120%'
GROUP BY FI.FILIAL ,F.NOME_CLIFOR , SUBSTRING(CONVERT(VARCHAR,F.EMISSAO,112),1,6) ,
FI.CODIGO_ITEM , P.GRIFFE
