

select   PRODUTO, COR_PRODUTO, A.ROMANEIO_PRODUTO, ROMANEIO_NF_SAIDA, B.PRECO1, B.VALOR, B.QTDE_ENTRADA, A.EMISSAO, A.QTDE_TOTAL, CHAVE_NFE, A.FILIAL
from LOJA_ENTRADAS A
INNER JOIN LOJA_ENTRADAS_PRODUTO B
			ON B.FILIAL=A.FILIAL AND  B.ROMANEIO_PRODUTO=A.ROMANEIO_PRODUTO
where A.FILIAL='SP - LAJEADO' AND (A.EMISSAO BETWEEN '20180901' AND '20180927') 





