select COUNT(*) from ESTOQUE_PRODUTOS_HISTORICO (nolock) where ESTOQUE > 0


SELECT A.PRODUTO, B.UNIDADE, A.ESTOQUE, C.PRECO1, B.DESC_PRODUTO, B.CLASSIF_FISCAL, A.COR_PRODUTO
FROM ESTOQUE_PRODUTOS_HISTORICO A
INNER JOIN 
	PRODUTOS B
		ON B.PRODUTO = A.PRODUTO
LEFT JOIN 
	PRODUTOS_PRECOS C 
		ON C.PRODUTO = A.PRODUTO AND C.CODIGO_TAB_PRECO = '00'
WHERE A.ESTOQUE>0


select * from transacoes where control_sistema like '999%'