
UPDATE PC SET PRECO1_ANTERIOR=PRECO1, PRECO1=(PRECO1 * 0.80), DATA_CARGA_PRECOS='20190418'
 FROM PRODUTOS_PRECOS PC 
 INNER JOIN PRODUTOS P ON P.PRODUTO = PC.PRODUTO
 WHERE PC.CODIGO_TAB_PRECO not in('00','01','02','03','04','05','35','37','cm','85', 'AT', 'VA')
 AND GRIFFE = 'FEMININO' AND LINHA = 'PROMOCIONAL' AND GRUPO_PRODUTO = 'INV COMM 3' AND SUBGRUPO_PRODUTO = 'C 3'
 GO
 
 UPDATE PC SET PRECO1_ANTERIOR=PRECO1, PRECO1=(PRECO1 * 0.80), DATA_CARGA_PRECOS='20190418'
 FROM PRODUTOS_PRECOS PC 
 INNER JOIN PRODUTOS P ON P.PRODUTO = PC.PRODUTO
 WHERE PC.CODIGO_TAB_PRECO not in('00','01','02','03','04','05','35','37','cm','85', 'AT', 'VA')
 AND GRIFFE = 'FEMININO' AND LINHA = 'PROMOCIONAL' AND GRUPO_PRODUTO = 'INV COMM 4' AND SUBGRUPO_PRODUTO = 'C 4'
 GO

 UPDATE PC SET PRECO1_ANTERIOR=PRECO1, PRECO1=(PRECO1 * 0.80), DATA_CARGA_PRECOS='20190418'
 FROM PRODUTOS_PRECOS PC 
 INNER JOIN PRODUTOS P ON P.PRODUTO = PC.PRODUTO
 WHERE PC.CODIGO_TAB_PRECO not in('00','01','02','03','04','05','35','37','cm','85', 'AT', 'VA')
 AND GRIFFE = 'FEMININO' AND LINHA = 'PROMOCIONAL' AND GRUPO_PRODUTO = 'INV COMM 5' AND SUBGRUPO_PRODUTO = 'C 5'
 GO

 UPDATE PC SET PRECO1_ANTERIOR=PRECO1, PRECO1=(PRECO1 * 0.80), DATA_CARGA_PRECOS='20190418'
 FROM PRODUTOS_PRECOS PC 
 INNER JOIN PRODUTOS P ON P.PRODUTO = PC.PRODUTO
 WHERE PC.CODIGO_TAB_PRECO not in('00','01','02','03','04','05','35','37','cm','85', 'AT', 'VA')
 AND GRIFFE = 'FEMININO' AND LINHA = 'PROMOCIONAL' AND GRUPO_PRODUTO = 'INV MESA 1' AND SUBGRUPO_PRODUTO = 'MESA 1 SUP'
 GO

 UPDATE PC SET PRECO1_ANTERIOR=PRECO1, PRECO1=(PRECO1 * 0.80), DATA_CARGA_PRECOS='20190418'
 FROM PRODUTOS_PRECOS PC 
 INNER JOIN PRODUTOS P ON P.PRODUTO = PC.PRODUTO
 WHERE PC.CODIGO_TAB_PRECO not in('00','01','02','03','04','05','35','37','cm','85', 'AT', 'VA')
 AND GRIFFE = 'FEMININO' AND LINHA = 'PROMOCIONAL' AND GRUPO_PRODUTO = 'INV MESA 2' AND SUBGRUPO_PRODUTO = 'MESA 2 INF'
 GO

 UPDATE PC SET PRECO1_ANTERIOR=PRECO1, PRECO1=(PRECO1 * 0.80), DATA_CARGA_PRECOS='20190418'
 FROM PRODUTOS_PRECOS PC 
 INNER JOIN PRODUTOS P ON P.PRODUTO = PC.PRODUTO
 WHERE PC.CODIGO_TAB_PRECO not in('00','01','02','03','04','05','35','37','cm','85', 'AT', 'VA')
 AND GRIFFE = 'FEMININO' AND LINHA = 'PROMOCIONAL' AND GRUPO_PRODUTO = 'INV MESA 2' AND SUBGRUPO_PRODUTO = 'MESA 2 SUP'
 GO

 UPDATE PC SET PRECO1_ANTERIOR=PRECO1, PRECO1=(PRECO1 * 0.80), DATA_CARGA_PRECOS='20190418'
 FROM PRODUTOS_PRECOS PC 
 INNER JOIN PRODUTOS P ON P.PRODUTO = PC.PRODUTO
 WHERE PC.CODIGO_TAB_PRECO not in('00','01','02','03','04','05','35','37','cm','85', 'AT', 'VA')
 AND GRIFFE = 'FEMININO' AND LINHA = 'PROMOCIONAL' AND GRUPO_PRODUTO = 'INV MESA 4' AND SUBGRUPO_PRODUTO = 'MESA 4 INF'
 GO

 UPDATE PC SET PRECO1_ANTERIOR=PRECO1, PRECO1=(PRECO1 * 0.80), DATA_CARGA_PRECOS='20190418'
 FROM PRODUTOS_PRECOS PC 
 INNER JOIN PRODUTOS P ON P.PRODUTO = PC.PRODUTO
 WHERE PC.CODIGO_TAB_PRECO not in('00','01','02','03','04','05','35','37','cm','85', 'AT', 'VA')
 AND GRIFFE = 'FEMININO' AND LINHA = 'PROMOCIONAL' AND GRUPO_PRODUTO = 'INV MESA 4' AND SUBGRUPO_PRODUTO = 'MESA 4 SUP'
 GO

 UPDATE PC SET PRECO1_ANTERIOR=PRECO1, PRECO1=(PRECO1 * 0.80), DATA_CARGA_PRECOS='20190418'
 FROM PRODUTOS_PRECOS PC 
 INNER JOIN PRODUTOS P ON P.PRODUTO = PC.PRODUTO
 WHERE PC.CODIGO_TAB_PRECO not in('00','01','02','03','04','05','35','37','cm','85', 'AT', 'VA')
 AND GRIFFE = 'FEMININO' AND LINHA = 'PROMOCIONAL' AND GRUPO_PRODUTO = 'INV MESA 5' AND SUBGRUPO_PRODUTO = 'MESA 5 SUP'
 GO

 UPDATE PC SET PRECO1_ANTERIOR=PRECO1, PRECO1=(PRECO1 * 0.80), DATA_CARGA_PRECOS='20190418'
 FROM PRODUTOS_PRECOS PC 
 INNER JOIN PRODUTOS P ON P.PRODUTO = PC.PRODUTO
 WHERE PC.CODIGO_TAB_PRECO not in('00','01','02','03','04','05','35','37','cm','85', 'AT', 'VA')
 AND GRIFFE = 'FEMININO' AND LINHA = 'PROMOCIONAL' AND GRUPO_PRODUTO = 'INV MESA FLEX' AND SUBGRUPO_PRODUTO = 'MESA 1 SUP'
 GO
