DECLARE @RETORNO INT = 0
DECLARE @PERMITE_ESPACO BIT = 1

DECLARE @CONTEUDO VARCHAR(100)
SET @CONTEUDO = 'beltrano cia. & filhos'

DECLARE @CONTEM_ESP BIT = 0
DECLARE @PADRAO VARCHAR(100)

IF @CONTEUDO IS NULL
    SET @RETORNO = 0

IF @PERMITE_ESPACO = 1
    SET @PADRAO = '%[^A-Za-z0-9._ /&-]%'   -- com espaço, permite &
ELSE
    SET @PADRAO = '%[^A-Za-z0-9._/&-]%'    -- sem espaço, permite &

IF PATINDEX(@PADRAO, LTRIM(RTRIM(@CONTEUDO)) COLLATE Latin1_General_BIN) > 0
    SET @CONTEM_ESP = 1

SELECT @CONTEM_ESP AS CONTEM_ESP, @RETORNO AS RETORNO