

USE [CAEDU]
GO
/****** Object:  StoredProcedure [dbo].[DBA_CALCULAMEDIAPONDERADA]    Script Date: 05/03/2020 09:04:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[DBA_CALCULAMEDIAPONDERADA]
AS

/*==========================================================================================================
Criada em                    : 10/06/2014
Autor                        : Suellen Moraes
Sistema que utiliza          : Banco de dados / linx
Descrição                    : realiza o calculo da média ponderada dos valores dos produtos em estoque e atualiza a tabela 05 - caedu
								O calculo da tabela 5 deve ser a multiplicação do estoque x valor de denda da loja para cada produto,
								depois somado o valor de venda de todas as lojas divido pelo sum do estoque
     
Última alteração em          : 03/08/2015
Autor da alteração           : Thiago Bongiovani
Motivo da alteração          : Nao deixar alterar quando o valor novo for igual a 0 (Zero)

Última alteração em          : 05/03/2020
Autor da alteração           : Paulo Devide
Motivo da alteração          : Inclusão de novos filtros de exceção (eliminando os novos CDs, CQs etc)
==========================================================================================================*/

-- CARREGA TABELA TEMPORA COM O ESTOQUE DE TODAS AS LOJAS PARA TODOS OS PRODUTOS.
drop table #ESTOQUE_PRODUTOS 
drop table #3
drop table #TAB_FINAL

SELECT A.* 
INTO      #ESTOQUE_PRODUTOS   
FROM      ESTOQUE_PRODUTOS  A
--INNER JOIN FILIAIS F ON F.FILIAL = A.FILIAL
--WHERE /*FILIAL NOT IN ('TRANSPORTADORA CAEDU','CD EMBU', 'CELOTE', 'CD VAREJO','CONTROLE DE QUALIDADE', 'DIVERGENCIA', 'JAU', 'TATUAPE', 'BAURU', 'RIO PRETO', 'MATRIZ')*/
--F.ERP_EXCLUI_DA_MEDIA_PONDERADA = 0 /*EXCLUI CDs E CONTROLE DE QUALIDADE E CQs*/
WHERE a.FILIAL not IN ('TRANSPORTADORA CAEDU','CD EMBU', 'CELOTE', 'CD VAREJO','CONTROLE DE QUALIDADE', 'DIVERGENCIA', 'JAU', 'TATUAPE', 'BAURU', 'RIO PRETO', 'MATRIZ',
'CD ARAQUARI','CD ARAUARI','CD REGIS','ARAQUARI CQ','NAVEGANTES CQ','REJEITADO CQ','BARRA VELHA - CQ','CAJAMAR - CQ',
'AMOSTRA CD REGIS','AMOSTRA PIRAJA','AMOSTRA TIJUCO','ARAQUARI CQ','BARRA VELHA - CQ', 'REJEITADO - CD CAJAMAR','REJEITADO CQ' )

-- ALTERA NA TABELA TEMPORARIA O NOME DA LOJA PARA O NOME DA SUA TABELA DE PREÇO CORRESPONDENTE
UPDATE C
SET C.FILIAL = B.TABELA
--SELECT DISTINCT A.LOJA, A.VENDA , B.TABELA, C.FILIAL
FROM INFO_LOJAS A
INNER JOIN TABELAS_PRECO B
ON A.CODIGO_PRECO = B.CODIGO_TAB_PRECO
AND A.VENDA = B.TABELA
INNER JOIN #ESTOQUE_PRODUTOS C
ON A.LOJA = C.FILIAL
WHERE A.ATIVO = 1
--ORDER BY A.LOJA


-- OS VALORES DOS CD_REGIS E CD_IMPORTACAO DEVEM SER CONSIDERADOS COMO TABELA DE PRECO VENDA ORIGINAL (SOLICITACAO DO mARCIO DO PLANEJAMENTO)
--UPDATE #ESTOQUE_PRODUTOS SET FILIAL = 'VENDA ORIGINAL' WHERE FILIAL = 'CD IMPORTACAO'  
--UPDATE #ESTOQUE_PRODUTOS SET FILIAL = 'VENDA ORIGINAL' WHERE FILIAL = 'CD REGIS'  
UPDATE #ESTOQUE_PRODUTOS SET FILIAL = 'VENDA ORIGINAL' WHERE FILIAL like 'CD%'  

-- ALTERA ESTOQUE NEGATIVO PARA 0 ( REGRA DE NEGOCIO ONDE O ESTOQUE NEGATIVO DEVE SER CONSIDERADO 0, SOLICITACAO DO mARCIO DO PLANEJAMENTO)
UPDATE #ESTOQUE_PRODUTOS SET ESTOQUE = 0 WHERE ESTOQUE < 0

-- CRIA TABELA TEMPORARIA AGRUPANDO A QUANTIDADE DO ESTOQUE POR PRODUTO E LOJA
SELECT      
	TP.tabela,       
	PP.CODIGO_TAB_PRECO,       
	#ESTOQUE_PRODUTOS.COR_PRODUTO,       
	PP.PRODUTO,       
	PP.PRECO1,       
	SUM(ISNULL (#ESTOQUE_PRODUTOS.estoque, 0)) AS 'ESTOQUE'  
INTO       #3  
FROM      TABELAS_PRECO AS TP  
LEFT JOIN PRODUTOS_PRECOS AS PP      
ON PP.CODIGO_TAB_PRECO = TP.CODIGO_TAB_PRECO  
LEFT JOIN #ESTOQUE_PRODUTOS      
ON pp.produto = #ESTOQUE_PRODUTOS.produto 
WHERE      (PP.CODIGO_TAB_PRECO = '01' OR      PP.CODIGO_TAB_PRECO > '05') AND      
	PP.CODIGO_TAB_PRECO NOT IN ('35', '37','25','26', 'CM', '85') AND      
	#ESTOQUE_PRODUTOS.filial = tp.tabela   
	AND (#ESTOQUE_PRODUTOS.ESTOQUE > 0)
GROUP BY       TP.tabela, PP.CODIGO_TAB_PRECO, #ESTOQUE_PRODUTOS.COR_PRODUTO, PP.PRODUTO, PP.PRECO1  
ORDER BY       PP.PRODUTO  


-- ALTERA PARA 1 PARA AS LOJAS ONDE O ESTOQUE FOI 0 PORÉM EM OUTRAS LOJAS TEM ESTOQUE PARA O MESMO PRODUTO
UPDATE #3
SET ESTOQUE = 1
--SELECT #3.PRODUTO, #3.ESTOQUE, A.PRODUTO
FROM #3
INNER JOIN 
	(SELECT PRODUTO
	FROM #3 A
	GROUP BY PRODUTO HAVING SUM(ESTOQUE) > 0 ) A
ON #3.PRODUTO = A.PRODUTO
WHERE #3.ESTOQUE = 0


-- CARREGA TABELA FINAL PARA ALTERAÇÃO DO PRECO 5 (MEDIA PONDERADA)
SELECT       
	'CAEDU' AS TABELA,       
	05 AS CODIGO_TAB_PRECO,       
	PP.PRODUTO AS PRODUTO, 
	SUM (#3.PRECO1 * #3.estoque) / CASE WHEN SUM(ISNULL (#3.estoque,0)) = 0 THEN 1 ELSE SUM(ISNULL (#3.estoque,0)) END AS PRECO1
INTO #TAB_FINAL
FROM      TABELAS_PRECO AS TP  
LEFT JOIN PRODUTOS_PRECOS AS PP      
ON PP.CODIGO_TAB_PRECO = TP.CODIGO_TAB_PRECO  
LEFT JOIN #3      
ON pp.produto = #3.produto  
WHERE      (PP.CODIGO_TAB_PRECO = '01' OR      PP.CODIGO_TAB_PRECO > '05') AND      
	PP.CODIGO_TAB_PRECO NOT IN ('35', '37','25','26', 'CM', '85') AND        
	#3.TABELA = tp.tabela  
GROUP BY       PP.PRODUTO  

-- ATUALIZA OS VALORES NA TABELA DE PREÇO 05 - CAEDU
UPDATE           PP       
SET           PP.PRECO1 = F.PRECO1  
--SELECT PP.PRODUTO, PP.PRECO1 , F.PRECO1   
FROM           PRODUTOS_PRECOS PP       
INNER JOIN #TAB_FINAL F           
ON PP.PRODUTO = F.PRODUTO      
WHERE	PP.CODIGO_TAB_PRECO = '05'          AND 
		F.CODIGO_TAB_PRECO = '05'           AND  
		PP.PRECO1 != F.PRECO1				AND
		F.PRECO1 > 0
--ORDER BY PRODUTO      










SELECT * FROM  #ESTOQUE_PRODUTOS WHERE PRODUTO = '06101180' AND ESTOQUE<>0
SELECT * FROM  #3 WHERE PRODUTO = '06101180' ORDER BY TABELA
SELECT * FROM  #TAB_FINAL WHERE PRODUTO = '06101180'

SELECT * FROM      TABELAS_PRECO AS TP WHERE TABELA LIKE '%LAJEADO%'
--SELECT * FROM INFO_LOJAS

--SELECT * FROM ESTOQUE_PRODUTOS WHERE FILIAL= 'SP - LAJEADO' AND PRODUTO = '06100966'

SELECT * FROM TABELAS_PRECO_FILIAL


--SELECT A.* 
----INTO      #ESTOQUE_PRODUTOS   
--FROM      ESTOQUE_PRODUTOS  A
--INNER JOIN FILIAIS F ON F.FILIAL = A.FILIAL
----WHERE /*FILIAL NOT IN ('TRANSPORTADORA CAEDU','CD EMBU', 'CELOTE', 'CD VAREJO','CONTROLE DE QUALIDADE', 'DIVERGENCIA', 'JAU', 'TATUAPE', 'BAURU', 'RIO PRETO', 'MATRIZ')*/
----F.ERP_EXCLUI_DA_MEDIA_PONDERADA = 0 /*EXCLUI CDs E CONTROLE DE QUALIDADE E CQs*/
--WHERE PRODUTO = '06100966' AND 
--a.FILIAL not IN ('TRANSPORTADORA CAEDU','CD EMBU', 'CELOTE', 'CD VAREJO','CONTROLE DE QUALIDADE', 'DIVERGENCIA', 'JAU', 'TATUAPE', 'BAURU', 'RIO PRETO', 'MATRIZ',
--'CD ARAQUARI','CD ARAUARI','CD BARRA VELHA','CD CAJAMAR','CD NAVEGANTES','CD REGIS','ARAQUARI CQ','NAVEGANTES CQ','REJEITADO CQ','BARRA VELHA - CQ','CAJAMAR - CQ',
--'AMOSTRA CD REGIS','AMOSTRA PIRAJA','AMOSTRA TIJUCO','ARAQUARI CQ','BARRA VELHA - CQ', 'REJEITADO - CD CAJAMAR','REJEITADO CQ' )

SELECT      
	TP.tabela,       
	PP.CODIGO_TAB_PRECO,       
	#ESTOQUE_PRODUTOS.COR_PRODUTO,       
	PP.PRODUTO,       
	PP.PRECO1,       
	SUM(ISNULL (#ESTOQUE_PRODUTOS.estoque, 0)) AS 'ESTOQUE'  
--INTO       #3  
FROM      TABELAS_PRECO AS TP  
LEFT JOIN PRODUTOS_PRECOS AS PP      
ON PP.CODIGO_TAB_PRECO = TP.CODIGO_TAB_PRECO  
LEFT JOIN #ESTOQUE_PRODUTOS      
ON pp.produto = #ESTOQUE_PRODUTOS.produto 
WHERE      (PP.CODIGO_TAB_PRECO = '01' OR      PP.CODIGO_TAB_PRECO > '05') AND      
	PP.CODIGO_TAB_PRECO NOT IN ('35', '37','25','26', 'CM', '85') AND      
	#ESTOQUE_PRODUTOS.filial = tp.tabela   
	AND (#ESTOQUE_PRODUTOS.ESTOQUE > 0) AND PP.PRODUTO = '06100966'
GROUP BY       TP.tabela, PP.CODIGO_TAB_PRECO, #ESTOQUE_PRODUTOS.COR_PRODUTO, PP.PRODUTO, PP.PRECO1  
ORDER BY       PP.PRODUTO


select * from TABELAS_PRECO 


select b.TABELA
FROM INFO_LOJAS A
INNER JOIN TABELAS_PRECO B
ON A.CODIGO_PRECO = B.CODIGO_TAB_PRECO
AND A.VENDA = B.TABELA
--INNER JOIN #ESTOQUE_PRODUTOS C
--ON A.LOJA = C.FILIAL
WHERE A.ATIVO = 1 
order by 1


select * from INFO_LOJAS where CODIGO_PRECO='99'

update a set STATUS='A' 
from TABELAS_PRECO a where
 CODIGO_TAB_PRECO in(
'36',
'53',
'57',
'58',
'59',
'60',
'66',
'77',
'78',
'98',
'99')


select a.CODIGO_TAB_PRECO, b.CODIGO_PRECO, a.TABELA, b.VENDA, b.LOJA 

update b set b.venda = a.TABELA
from TABELAS_PRECO a
left join INFO_LOJAS b on b.CODIGO_PRECO = a.CODIGO_TAB_PRECO
where codigo_preco is not null and tabela<>venda and CODIGO_PRECO<>'05'

update info_lojas set venda = 'VENDA_SPLAJEADO' where CODIGO_PRECO='99'