/*
UPDATE CADASTRO_CLI_FOR SET PAIS = 'BRASIL' WHERE PAIS IS NULL OR PAIS = ''
select @@ERROR

if @@ERROR<>0

	print 'entrou aqui'

select b.COD_MUNICIPIO_IBGE as CODIGO_IBGE
,a.COD_MUNICIPIO_IBGE
,a.COD_MUNICIPIO_IBGE_ENTREGA
,a.COD_MUNICIPIO_IBGE_COBRANCA
,a.*
from CADASTRO_CLI_FOR a
left join LCF_LX_MUNICIPIO b on b.DESC_MUNICIPIO = a.CIDADE
WHERE (PAIS IS NULL OR PAIS = '')
and UF <> 'EX'
--and  (
--		ISNULL(A.COD_MUNICIPIO_IBGE,'') = '' 
--		OR   ISNULL(A.COD_MUNICIPIO_IBGE_ENTREGA,'') = '' 
--		OR ISNULL(A.COD_MUNICIPIO_IBGE_COBRANCA,'') = '' 
--	 )


select DESC_MUNICIPIO, COD_MUNICIPIO_IBGE,count(*) as qt
from LCF_LX_MUNICIPIO
group by DESC_MUNICIPIO, COD_MUNICIPIO_IBGE
having count(*)>1


SELECT * 
from LCF_LX_MUNICIPIO m
left join CAE_ESTADOS_IBGE u on u.CODIGO = m.ID_UF

SELECT * FROM CAE_ESTADOS_IBGE

LX_CADE IBGE

*/

SET NOCOUNT ON

declare @cadastro table (
ID INT IDENTITY(1,1) PRIMARY KEY,
NOME_CLIFOR VARCHAR(25),
CLIFOR CHAR(6),
CADASTRO_OK BIT DEFAULT(1)
)

INSERT INTO @cadastro (NOME_CLIFOR,CLIFOR)
SELECT NOME_CLIFOR, CLIFOR 
FROM CADASTRO_CLI_FOR 
WHERE (PAIS IS NULL OR PAIS = '') AND UF<>'EX'


DECLARE @I INT, @TOT INT, @CLIFOR CHAR(6)

SELECT @I=MIN(ID), @TOT=MAX(ID) 
FROM @cadastro 

WHILE @I<=@TOT
BEGIN

	PRINT @I
	SELECT @CLIFOR = CLIFOR 
	FROM @cadastro 
	WHERE ID = @I

	UPDATE CADASTRO_CLI_FOR SET PAIS = 'BRASIL' 
	WHERE CLIFOR = @CLIFOR
	--PAIS IS NULL OR PAIS = ''

	IF @@ERROR<>0
	BEGIN
		UPDATE @cadastro SET CADASTRO_OK=0
		WHERE ID = @I
	END
	SET @I+=1

END

SELECT * FROM @cadastro WHERE CADASTRO_OK=0

SET NOCOUNT OFF
