select A.ROMANEIO_PRODUTO, A.FILIAL, A.FILIAL_ORIGEM, A.ROMANEIO_NF_SAIDA, A.EMISSAO, A.ENTRADA_CONFERIDA, A.DATA_ENTRADA_CONFERIDA,
B.PRODUTO, B.COR_PRODUTO, B.QTDE_ENTRADA, B.PRECO1, B.VALOR, P.GRIFFE, P.LINHA, P.GRUPO_PRODUTO, P.SUBGRUPO_PRODUTO, P.GRADE, P.DESC_PRODUTO, F.EMISSAO AS EMISSAO_NF
from LOJA_ENTRADAS A
INNER JOIN LOJA_ENTRADAS_PRODUTO B 
	ON B.ROMANEIO_PRODUTO = A.ROMANEIO_PRODUTO AND B.FILIAL = A.FILIAL
INNER JOIN FATURAMENTO F ON F.FILIAL=A.FILIAL_ORIGEM AND F.NF_SAIDA = A.ROMANEIO_NF_SAIDA
inner join PRODUTOS P ON P.PRODUTO = B.PRODUTO
where A.FILIAL_ORIGEM = 'CD CAJAMAR' AND f.EMISSAO BETWEEN '20200101' AND '20200124'