USE [CAEDU]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER TABLE dbo.FILIAIS 
	ADD EM_INVENTARIO BIT NULL DEFAULT(0),
		DT_ULTIMO_INVENTARIO DATETIME NULL,
		RESPONSAVEL_ULTIMO_INVENTARIO VARCHAR(25) NULL
GO

CREATE TABLE DBO.CGP_LOG_FILIAL_INVENTARIO
(	ID INT IDENTITY(1,1) NOT NULL,
	FILIAL VARCHAR(25) NOT NULL,
	EM_INVENTARIO BIT NULL,
	USUARIO_STATUS VARCHAR(25),
	DATA_STATUS DATETIME NULL,
	CONSTRAINT PK_CGP_LOG_FILIAL_INVENTARIO PRIMARY KEY (ID)
)
GO

INSERT INTO PARAMETROS (PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, 
						ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, POR_USUARIO_OK)
VALUES ('PALMA_HORA_INVENTARIO', '20230905', '', 
		'20230905', '18:00', 'HORARIO MINIMO PARA INICIAR CONTAGEM INVENTARIO', 'C', 0),
	   ('PALMA_STATUS_INVENTARIO', '20230905', '', 
		'20230905', '.F.', 'PERMISSAO PARA DESMARCAR STATUS DE INVENTARIO', 'L', 1)
GO

INSERT INTO PARAMETROS_USERS 
VALUES 
('CCP\PAULO.DEVIDE','PALMA_STATUS_INVENTARIO','.T.',GETDATE()),
('CCP\RPSILVA16','PALMA_STATUS_INVENTARIO','.T.',GETDATE()),
('CCP\MAURO.FREIRE','PALMA_STATUS_INVENTARIO','.T.',GETDATE()),
('CCP\MICHEL.MACEDO','PALMA_STATUS_INVENTARIO','.T.',GETDATE()),
('CCP\KELLY.SANTANA','PALMA_STATUS_INVENTARIO','.T.',GETDATE())
go

INSERT INTO TRANSACOES_PARAM 
VALUES ('PALMA_HORA_INVENTARIO','ESTOQUE_PRODUTOS_002',GETDATE(),NULL)
go

INSERT INTO TRANSACOES (COD_TRANSACAO,BLOQUEIA_EMPRESA_MULTI_ACESSO,TRANSACAO,
						TABELA_PAI,VERSAO_LIBERADA,TITULO, HELP, CONTROL_SISTEMA, 
						AUDITORIA, AUDITORIA_GERAL,AUDITORIA_EM_COLUNAS,DATA_PARA_TRANSFERENCIA,
						PERMITE_ALTERAR_MULTI_EMPRESA,CODIGO_QUERY,FILTRO_TRANSACAO,
						APLICACAO,LINK_SHARE)
VALUES ('LX999616_001',0,'001','LX999616','8.01','ATIVAÇÃO DE FILIAIS PARA INVENTÁRIO', NULL, 
		'999616', 0, 0,0,GETDATE(),	0,NULL,NULL, NULL,NULL)
GO

INSERT INTO TRANSACOES_NAVEGA VALUES ('4','LX999616_001','ESTPA',0,1,GETDATE(),'E')
GO

INSERT INTO TRANSACOES_PARAM 
VALUES ('PALMA_STATUS_INVENTARIO','LX999616_001',GETDATE(),NULL)
go


CREATE TABLE DBO.CGP_LOG_CONSULTA_ESTOQUE_FILIAL
(	ID INT IDENTITY(1,1) NOT NULL,
	DATA_HORA_CONSULTA DATETIME NULL,
	FILIAL VARCHAR(25) NULL,
	TOTAL_QTDE_ESTOQUE INT NULL,
	TOTAL_QTDE_ESTOQUE_DISPONIVEL INT NULL,
	TOTAL_QTDE_TRANSITO INT NULL,
	USUARIO VARCHAR(25) NULL,
	EM_INVENTARIO BIT NULL,
	CONSTRAINT PK_CGP_LOG_CONSULTA_ESTOQUE_FILIAL PRIMARY KEY (ID)
)
GO

CREATE TABLE DBO.CGP_LOG_ARQUIVO_AF_INVENTARIO
(	ID INT IDENTITY(1,1) NOT NULL,
	DATA_HORA_CONSULTA DATETIME NULL,
	FILIAL VARCHAR(25) NULL,
	QTD_PRODUTOS INT NULL,
	ESTOQUE INT NULL,
	TOTAL_LINHAS INT NULL,
	USUARIO VARCHAR(25) NULL,
	EM_INVENTARIO BIT NULL,
	CONSTRAINT PK_CGP_LOG_ARQUIVO_AF_INVENTARIO PRIMARY KEY (ID)
)
GO

ALTER TABLE DBO.CM_DATA_FECHAMENTO 
ADD DATA_SALDO_PA_ANTES DATETIME NULL
GO

INSERT INTO TRANSACOES (COD_TRANSACAO,BLOQUEIA_EMPRESA_MULTI_ACESSO,TRANSACAO,
						TABELA_PAI,VERSAO_LIBERADA,TITULO, HELP, CONTROL_SISTEMA, 
						AUDITORIA, AUDITORIA_GERAL,AUDITORIA_EM_COLUNAS,DATA_PARA_TRANSFERENCIA,
						PERMITE_ALTERAR_MULTI_EMPRESA,CODIGO_QUERY,FILTRO_TRANSACAO,
						APLICACAO,LINK_SHARE)
VALUES ('LX999711_001',0,'001','LX999711','8.01','LOG STATUS INVENTÁRIO DE FILIAIS', NULL, 
		'999711', 0, 0,0,GETDATE(),	0,NULL,NULL, NULL,NULL)
GO

INSERT INTO TRANSACOES_NAVEGA VALUES ('3','LX999711_001','ESTPA',0,1,GETDATE(),'E')
GO

INSERT INTO TRANSACOES (COD_TRANSACAO,BLOQUEIA_EMPRESA_MULTI_ACESSO,TRANSACAO,
						TABELA_PAI,VERSAO_LIBERADA,TITULO, HELP, CONTROL_SISTEMA, 
						AUDITORIA, AUDITORIA_GERAL,AUDITORIA_EM_COLUNAS,DATA_PARA_TRANSFERENCIA,
						PERMITE_ALTERAR_MULTI_EMPRESA,CODIGO_QUERY,FILTRO_TRANSACAO,
						APLICACAO,LINK_SHARE)
VALUES ('LX999712_001',0,'001','LX999712','8.01','LOG CONSULTA ESTOQUE POR FILIAL', NULL, 
		'999712', 0, 0,0,GETDATE(),	0,NULL,NULL, NULL,NULL)
GO

INSERT INTO TRANSACOES_NAVEGA VALUES ('3','LX999712_001','ESTPA',0,1,GETDATE(),'E')
GO

INSERT INTO TRANSACOES (COD_TRANSACAO,BLOQUEIA_EMPRESA_MULTI_ACESSO,TRANSACAO,
						TABELA_PAI,VERSAO_LIBERADA,TITULO, HELP, CONTROL_SISTEMA, 
						AUDITORIA, AUDITORIA_GERAL,AUDITORIA_EM_COLUNAS,DATA_PARA_TRANSFERENCIA,
						PERMITE_ALTERAR_MULTI_EMPRESA,CODIGO_QUERY,FILTRO_TRANSACAO,
						APLICACAO,LINK_SHARE)
VALUES ('LX999713_001',0,'001','LX999713','8.01','LOG CONSULTA ARQUIVO AF', NULL, 
		'999713', 0, 0,0,GETDATE(),	0,NULL,NULL, NULL,NULL)
GO

INSERT INTO TRANSACOES_NAVEGA VALUES ('3','LX999713_001','ESTPA',0,1,GETDATE(),'E')
GO

create or alter procedure DBO.CGP_PRC_LOG_CONSULTA_ESTOQUE_FILIAL
	@FILIAL VARCHAR(25),
	@TOTAL_QTDE_ESTOQUE INT,
	@TOTAL_QTDE_ESTOQUE_DISPONIVEL INT,
	@TOTAL_QTDE_TRANSITO INT,
	@USUARIO VARCHAR(25) 
AS
BEGIN
	DECLARE @EM_INVENTARIO BIT

	SELECT @EM_INVENTARIO=EM_INVENTARIO 
	FROM FILIAIS WHERE FILIAL = @FILIAL

	INSERT INTO DBO.CGP_LOG_CONSULTA_ESTOQUE_FILIAL
	(DATA_HORA_CONSULTA,
	FILIAL,
	TOTAL_QTDE_ESTOQUE,
	TOTAL_QTDE_ESTOQUE_DISPONIVEL,
	TOTAL_QTDE_TRANSITO,
	USUARIO,
	EM_INVENTARIO
	)
	VALUES (
	GETDATE(),
	@FILIAL,
	@TOTAL_QTDE_ESTOQUE,
	@TOTAL_QTDE_ESTOQUE_DISPONIVEL,
	@TOTAL_QTDE_TRANSITO,
	@USUARIO,
	@EM_INVENTARIO
	)
END
go

create or alter procedure DBO.CGP_PRC_LOG_ARQUIVO_AF_INVENTARIO
	@FILIAL VARCHAR(25),
	@QTD_PRODUTOS INT,
	@ESTOQUE INT,
	@TOTAL_LINHAS INT,
	@USUARIO VARCHAR(25)
AS
BEGIN
	DECLARE @EM_INVENTARIO BIT

	SELECT @EM_INVENTARIO=EM_INVENTARIO 
	FROM FILIAIS WHERE FILIAL = @FILIAL

	INSERT INTO DBO.CGP_LOG_ARQUIVO_AF_INVENTARIO
	(DATA_HORA_CONSULTA,FILIAL,QTD_PRODUTOS,ESTOQUE,TOTAL_LINHAS,USUARIO,EM_INVENTARIO)
	VALUES (
	GETDATE(),
	@FILIAL,
	@QTD_PRODUTOS,
	@ESTOQUE,
	@TOTAL_LINHAS,
	@USUARIO,
	@EM_INVENTARIO
	)
END
go

CREATE OR ALTER TRIGGER [dbo].[LXU_CGP_FILIAIS] 
ON [dbo].[FILIAIS]  
FOR UPDATE NOT FOR REPLICATION  
As   
-- UPDATE Trigger On FILIAIS  
-- PAULO DEVIDE - 08/09/2023 - ACIONAR O BLOQUEIO DA FILIAL ATRAVES DA TABELA
--                             CM_DATAS_FECHAMENTO PARA NÃO RECEBER LANÇAMENTOS DURANTE O INVENTÁRIO


Begin  
	DECLARE @FILIAL VARCHAR(25), 
			@DATA_SALDO_PA_ATUAL DATETIME, 
			@DT_ULTIMO_INVENTARIO DATETIME, 
			@EM_INVENTARIO BIT,
			@RESPONSAVEL_ULTIMO_INVENTARIO VARCHAR(25)

	IF UPDATE(EM_INVENTARIO)
	BEGIN
		SELECT @FILIAL = I.FILIAL, 
				@DT_ULTIMO_INVENTARIO = i.DT_ULTIMO_INVENTARIO,
				@DATA_SALDO_PA_ATUAL=F.DATA_SALDO_PA,
				@EM_INVENTARIO = I.EM_INVENTARIO,
				@RESPONSAVEL_ULTIMO_INVENTARIO=I.RESPONSAVEL_ULTIMO_INVENTARIO
		FROM inserted i 
		LEFT JOIN CM_DATA_FECHAMENTO f 
			ON F.FILIAL = i.FILIAL

		IF @EM_INVENTARIO=1
		BEGIN

			UPDATE CM_DATA_FECHAMENTO
			SET DATA_SALDO_PA_ANTES=@DATA_SALDO_PA_ATUAL, DATA_SALDO_PA=@DT_ULTIMO_INVENTARIO
			WHERE FILIAL = @FILIAL

		END
		ELSE
		BEGIN
			UPDATE CM_DATA_FECHAMENTO
			SET DATA_SALDO_PA = ISNULL(DATA_SALDO_PA_ANTES, DATA_SALDO_PA)
			WHERE FILIAL = @FILIAL
		END

		INSERT INTO DBO.CGP_LOG_FILIAL_INVENTARIO
					(FILIAL,EM_INVENTARIO,USUARIO_STATUS,DATA_STATUS)
		VALUES		(@FILIAL,@EM_INVENTARIO,@RESPONSAVEL_ULTIMO_INVENTARIO,GETDATE())


		
	END

End 
go
update filiais set EM_INVENTARIO=0
go

/*
select * from PARAMETROS_USERS where PARAMETRO='PALMA_STATUS_INVENTARIO'

SELECT FILIAL, 
ISNULL(EM_INVENTARIO, 0) AS EM_INVENTARIO,
DT_ULTIMO_INVENTARIO,
RESPONSAVEL_ULTIMO_INVENTARIO   
FROM FILIAIS FILIAIS   
INNER JOIN CADASTRO_CLI_FOR CADASTRO_CLI_FOR 
	ON CADASTRO_CLI_FOR.NOME_CLIFOR = FILIAIS.FILIAL   
WHERE FILIAIS.EMPRESA=1 AND CADASTRO_CLI_FOR.INATIVO=0    
ORDER BY FILIAL

--update filiais set EM_INVENTARIO=0

select GETDATE() AS DATA_HORA,FILIAL,EM_INVENTARIO,DT_ULTIMO_INVENTARIO,
RESPONSAVEL_ULTIMO_INVENTARIO FROM FILIAIS WHERE FILIAL = 'MG - BH CENTRO'

select * from CM_DATA_FECHAMENTO where filial like 'SP- ARARAQUARA'

SELECT * FROM CGP_LOG_FILIAL_INVENTARIO

SELECT * FROM DBO.CGP_LOG_CONSULTA_ESTOQUE_FILIAL

SELECT * FROM FILIAIS WHERE FILIAL = 'SP- ARARAQUARA'
*/

 