/*
* View e-millenium
* Validado - Paulo Devide - 07-01-2025
*/
CREATE OR ALTER VIEW dbo.EML_PRODUTO_CORES AS
  SELECT PRODUTO,
         COR_PRODUTO, 
         DESC_COR_PRODUTO COLLATE Latin1_General_CS_AS AS DESC_COR_PRODUTO,
		 DATA_PARA_TRANSFERENCIA
  FROM PRODUTO_CORES (nolock);
go

/*
* Function e-millenium
* Validado - Paulo Devide - 07-01-2025
*/
CREATE OR ALTER FUNCTION DBO.TRIM(@DATA VARCHAR(200)) RETURNS VARCHAR(200)
AS
BEGIN
  DECLARE @str VARCHAR(200)
  SET @str = RTRIM(LTRIM(@DATA))
  RETURN @str
END;
GO

/*
* View e-millenium
* Validado - Paulo Devide - 07-01-2025
*/
CREATE or alter VIEW dbo.EML_ESTOQUE AS
  SELECT ISNULL(a.FILIAL, '') AS FILIAL,
         ISNULL(a.PRODUTO, 0) AS PRODUTO,
         ISNULL(a.COR_PRODUTO, 0) AS COR_PRODUTO,
	     a.ESTOQUE - (ISNULL(b.T1,0) + ISNULL(b.T2,0) + ISNULL(b.T3,0) + ISNULL(b.T4,0) + ISNULL(b.T5,0) + ISNULL(b.T6,0) + ISNULL(b.T7,0) + ISNULL(b.T8,0) + ISNULL(b.T9,0) + ISNULL(b.T10,0) + ISNULL(b.T11,0) + ISNULL(b.T12,0)+ISNULL(b.T13,0)+ISNULL(b.T14,0)+ISNULL(b.T15,0)+ISNULL(b.T16,0)+ISNULL(b.T17,0)+ISNULL(b.T18,0)+ISNULL(b.T19,0)+ISNULL(b.T20,0)+ISNULL(b.T21,0)+ISNULL(b.T22,0)+ISNULL(b.T23,0)+ISNULL(b.T24,0)+ISNULL(b.T25,0)+ISNULL(b.T26,0)+ISNULL(b.T27,0)+ISNULL(b.T28,0)+ISNULL(b.T29,0)+ISNULL(b.T30,0)+ISNULL(b.T31,0)+ISNULL(b.T32,0)+ISNULL(b.T33,0)+ISNULL(b.T34,0)+ISNULL(b.T35,0)+ISNULL(b.T36,0)+ISNULL(b.T37,0)+ISNULL(b.T38,0)+ISNULL(b.T39,0)+ISNULL(b.T40,0)+ISNULL(b.T41,0)+ISNULL(b.T42,0)+ISNULL(b.T43,0)+ISNULL(b.T44,0)+ISNULL(b.T45,0)+ISNULL(b.T46,0)+ISNULL(b.T47,0)+ISNULL(b.T48,0)+ ISNULL(x.TOTAL,0)) AS ESTOQUE,
         a.ES1  - ISNULL(b.T1,0)  - ISNULL(x.EP1,0) AS ES1,
         a.ES2  - ISNULL(b.T2,0)  - ISNULL(x.EP2,0) AS ES2,
         a.ES3  - ISNULL(b.T3,0)  - ISNULL(x.EP3,0) AS ES3,
         a.ES4  - ISNULL(b.T4,0)  - ISNULL(x.EP4,0) AS ES4,
         a.ES5  - ISNULL(b.T5,0)  - ISNULL(x.EP5,0) AS ES5,
         a.ES6  - ISNULL(b.T6,0)  - ISNULL(x.EP6,0) AS ES6,
         a.ES7  - ISNULL(b.T7,0)  - ISNULL(x.EP7,0) AS ES7,
         a.ES8  - ISNULL(b.T8,0)  - ISNULL(x.EP8,0) AS ES8,
         a.ES9  - ISNULL(b.T9,0)  - ISNULL(x.EP9,0) AS ES9,
         a.ES10 - ISNULL(b.T10,0) - ISNULL(x.EP10,0) AS ES10,
         a.ES11 - ISNULL(b.T11,0) - ISNULL(x.EP11,0) AS ES11,
         a.ES12 - ISNULL(b.T12,0) - ISNULL(x.EP12,0) AS ES12,
         a.ES13 - ISNULL(b.T13,0) - ISNULL(x.EP13,0) AS ES13,
         a.ES14 - ISNULL(b.T14,0) - ISNULL(x.EP14,0) AS ES14,
         a.ES15 - ISNULL(b.T15,0) - ISNULL(x.EP15,0) AS ES15,
         a.ES16 - ISNULL(b.T16,0) - ISNULL(x.EP16,0) AS ES16,
         a.ES17 - ISNULL(b.T17,0) - ISNULL(x.EP17,0) AS ES17,
         a.ES18 - ISNULL(b.T18,0) - ISNULL(x.EP18,0) AS ES18,
         a.ES19 - ISNULL(b.T19,0) - ISNULL(x.EP19,0) AS ES19,
         a.ES20 - ISNULL(b.T20,0) - ISNULL(x.EP20,0) AS ES20,
         a.ES21 - ISNULL(b.T21,0) - ISNULL(x.EP21,0) AS ES21,
         a.ES22 - ISNULL(b.T22,0) - ISNULL(x.EP22,0) AS ES22,
         a.ES23 - ISNULL(b.T23,0) - ISNULL(x.EP23,0) AS ES23,
         a.ES24 - ISNULL(b.T24,0) - ISNULL(x.EP24,0) AS ES24,
         a.ES25 - ISNULL(b.T25,0) - ISNULL(x.EP25,0) AS ES25,
         a.ES26 - ISNULL(b.T26,0) - ISNULL(x.EP26,0) AS ES26,
         a.ES27 - ISNULL(b.T27,0) - ISNULL(x.EP27,0) AS ES27,
         a.ES28 - ISNULL(b.T28,0) - ISNULL(x.EP28,0) AS ES28,
         a.ES29 - ISNULL(b.T29,0) - ISNULL(x.EP29,0) AS ES29,
         a.ES30 - ISNULL(b.T30,0) - ISNULL(x.EP30,0) AS ES30,
         a.ES31 - ISNULL(b.T31,0) - ISNULL(x.EP31,0) AS ES31,
         a.ES32 - ISNULL(b.T32,0) - ISNULL(x.EP32,0) AS ES32,
         a.ES33 - ISNULL(b.T33,0) - ISNULL(x.EP33,0) AS ES33,
         a.ES34 - ISNULL(b.T34,0) - ISNULL(x.EP34,0) AS ES34,
         a.ES35 - ISNULL(b.T35,0) - ISNULL(x.EP35,0) AS ES35,
         a.ES36 - ISNULL(b.T36,0) - ISNULL(x.EP36,0) AS ES36,
         a.ES37 - ISNULL(b.T37,0) - ISNULL(x.EP37,0) AS ES37,
         a.ES38 - ISNULL(b.T38,0) - ISNULL(x.EP38,0) AS ES38,
         a.ES39 - ISNULL(b.T39,0) - ISNULL(x.EP39,0) AS ES39,
         a.ES40 - ISNULL(b.T40,0) - ISNULL(x.EP40,0) AS ES40,
         a.ES41 - ISNULL(b.T41,0) - ISNULL(x.EP41,0) AS ES41,
         a.ES42 - ISNULL(b.T42,0) - ISNULL(x.EP42,0) AS ES42,
         a.ES43 - ISNULL(b.T43,0) - ISNULL(x.EP43,0) AS ES43,
         a.ES44 - ISNULL(b.T44,0) - ISNULL(x.EP44,0) AS ES44,
         a.ES45 - ISNULL(b.T45,0) - ISNULL(x.EP45,0) AS ES45,
         a.ES46 - ISNULL(b.T46,0) - ISNULL(x.EP46,0) AS ES46,
         a.ES47 - ISNULL(b.T47,0) - ISNULL(x.EP47,0) AS ES47,
         a.ES48 - ISNULL(b.T48,0) - ISNULL(x.EP48,0) AS ES48,
	     (CASE WHEN a.DATA_PARA_TRANSFERENCIA >= ISNULL(x.DATA_PARA_TRANSFERENCIA,0) THEN a.DATA_PARA_TRANSFERENCIA ELSE x.DATA_PARA_TRANSFERENCIA END) AS DATA_PARA_TRANSFERENCIA,
	     a.ULTIMA_ENTRADA,
         a.ULTIMA_SAIDA 
  FROM ESTOQUE_PRODUTOS (nolock) A
  LEFT JOIN (
             SELECT B.FILIAL AS FILIAL,B.PRODUTO AS PRODUTO,B.COR_PRODUTO AS COR_PRODUTO,ISNULL(SUM(QTDE_ENTRADA),0) AS QTDE_TRANSITO ,
                    ISNULL(SUM(EN1),0) AS T1,ISNULL(SUM(EN2),0) AS T2,ISNULL(SUM(EN3),0) AS T3,ISNULL(SUM(EN4),0) AS T4,
                    ISNULL(SUM(EN5),0) AS T5,ISNULL(SUM(EN6),0) AS T6,ISNULL(SUM(EN7),0) AS T7,ISNULL(SUM(EN8),0) AS T8,
                    ISNULL(SUM(EN9),0) AS T9,ISNULL(SUM(EN10),0) AS T10,ISNULL(SUM(EN11),0) AS T11,ISNULL(SUM(EN12),0) AS T12,
                    ISNULL(SUM(EN13),0) AS T13,ISNULL(SUM(EN14),0) AS T14,ISNULL(SUM(EN15),0) AS T15,ISNULL(SUM(EN16),0) AS T16,
                    ISNULL(SUM(EN17),0) AS T17,ISNULL(SUM(EN18),0) AS T18,ISNULL(SUM(EN19),0) AS T19,ISNULL(SUM(EN20),0) AS T20,
                    ISNULL(SUM(EN21),0) AS T21,ISNULL(SUM(EN22),0) AS T22,ISNULL(SUM(EN23),0) AS T23,ISNULL(SUM(EN24),0) AS T24,
                    ISNULL(SUM(EN25),0) AS T25,ISNULL(SUM(EN26),0) AS T26,ISNULL(SUM(EN27),0) AS T27,ISNULL(SUM(EN28),0) AS T28,
                    ISNULL(SUM(EN29),0) AS T29,ISNULL(SUM(EN30),0) AS T30,ISNULL(SUM(EN31),0) AS T31,ISNULL(SUM(EN32),0) AS T32,
                    ISNULL(SUM(EN33),0) AS T33,ISNULL(SUM(EN34),0) AS T34,ISNULL(SUM(EN35),0) AS T35,ISNULL(SUM(EN36),0) AS T36,
                    ISNULL(SUM(EN37),0) AS T37,ISNULL(SUM(EN38),0) AS T38,ISNULL(SUM(EN39),0) AS T39,ISNULL(SUM(EN40),0) AS T40,
                    ISNULL(SUM(EN41),0) AS T41,ISNULL(SUM(EN42),0) AS T42,ISNULL(SUM(EN43),0) AS T43,ISNULL(SUM(EN44),0) AS T44,
                    ISNULL(SUM(EN45),0) AS T45,ISNULL(SUM(EN46),0) AS T46,ISNULL(SUM(EN47),0) AS T47,ISNULL(SUM(EN48),0) AS T48 
             FROM LOJA_ENTRADAS (nolock) A INNER JOIN LOJA_ENTRADAS_PRODUTO (nolock) B ON A.ROMANEIO_PRODUTO=B.ROMANEIO_PRODUTO AND A.FILIAL=B.FILIAL
		     WHERE ENTRADA_CONFERIDA = 0
		     GROUP BY B.FILIAL,B.PRODUTO,B.COR_PRODUTO
			) B ON A.PRODUTO = B.PRODUTO AND A.COR_PRODUTO = B.COR_PRODUTO AND A.FILIAL = B.FILIAL
  LEFT JOIN (-- Empenho de pedido de troca 
             SELECT EM.FILIAL,
                    EM.PRODUTO,
                    EM.COR_PRODUTO,
                    MAX(EM.DATA_PARA_TRANSFERENCIA) DATA_PARA_TRANSFERENCIA,
                    SUM(EM.TOTAL) AS TOTAL,
                    SUM(EM.E1) AS EP1,
                    SUM(EM.E2) AS EP2,
                    SUM(EM.E3) AS EP3,
                    SUM(EM.E4) AS EP4,
                    SUM(EM.E5) AS EP5,
                    SUM(EM.E6) AS EP6,
                    SUM(EM.E7) AS EP7,
                    SUM(EM.E8) AS EP8,
                    SUM(EM.E9) AS EP9,
                    SUM(EM.E10) AS EP10,
                    SUM(EM.E11) AS EP11,
                    SUM(EM.E12) AS EP12,
                    SUM(EM.E13) AS EP13,
                    SUM(EM.E14) AS EP14,
                    SUM(EM.E15) AS EP15,
                    SUM(EM.E16) AS EP16,
                    SUM(EM.E17) AS EP17,
                    SUM(EM.E18) AS EP18,
                    SUM(EM.E19) AS EP19,
                    SUM(EM.E20) AS EP20,
                    SUM(EM.E21) AS EP21,
                    SUM(EM.E22) AS EP22,
                    SUM(EM.E23) AS EP23,
                    SUM(EM.E24) AS EP24,
                    SUM(EM.E25) AS EP25,
                    SUM(EM.E26) AS EP26,
                    SUM(EM.E27) AS EP27,
                    SUM(EM.E28) AS EP28,
                    SUM(EM.E29) AS EP29,
                    SUM(EM.E30) AS EP30,
                    SUM(EM.E31) AS EP31,
                    SUM(EM.E32) AS EP32,
                    SUM(EM.E33) AS EP33,
                    SUM(EM.E34) AS EP34,
                    SUM(EM.E35) AS EP35,
                    SUM(EM.E36) AS EP36,
                    SUM(EM.E37) AS EP37,
                    SUM(EM.E38) AS EP38,
                    SUM(EM.E39) AS EP39,
                    SUM(EM.E40) AS EP40,
                    SUM(EM.E41) AS EP41,
                    SUM(EM.E42) AS EP42,
                    SUM(EM.E43) AS EP43,
                    SUM(EM.E44) AS EP44,
                    SUM(EM.E45) AS EP45,
                    SUM(EM.E46) AS EP46,
                    SUM(EM.E47) AS EP47,
                    SUM(EM.E48) AS EP48
				FROM (
                      SELECT EM.FILIAL,
                             EM.PRODUTO,
                             EM.COR_PRODUTO,
                             EM.DATA_PARA_TRANSFERENCIA,
                             ISNULL(EM.TOTAL,0) AS TOTAL,
                             CASE WHEN EM.TAMANHO = 1 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E1,
                             CASE WHEN EM.TAMANHO = 2 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E2,
                             CASE WHEN EM.TAMANHO = 3 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E3,
                             CASE WHEN EM.TAMANHO = 4 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E4,
                             CASE WHEN EM.TAMANHO = 5 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E5,
                             CASE WHEN EM.TAMANHO = 6 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E6,
                             CASE WHEN EM.TAMANHO = 7 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E7,
                             CASE WHEN EM.TAMANHO = 8 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E8,
                             CASE WHEN EM.TAMANHO = 9 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E9,
                             CASE WHEN EM.TAMANHO = 10 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E10,
                             CASE WHEN EM.TAMANHO = 11 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E11,
                             CASE WHEN EM.TAMANHO = 12 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E12,
                             CASE WHEN EM.TAMANHO = 13 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E13,
                             CASE WHEN EM.TAMANHO = 14 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E14,
                             CASE WHEN EM.TAMANHO = 15 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E15,
                             CASE WHEN EM.TAMANHO = 16 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E16,
                             CASE WHEN EM.TAMANHO = 17 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E17,
                             CASE WHEN EM.TAMANHO = 18 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E18,
                             CASE WHEN EM.TAMANHO = 19 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E19,
                             CASE WHEN EM.TAMANHO = 20 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E20,
                             CASE WHEN EM.TAMANHO = 21 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E21,
                             CASE WHEN EM.TAMANHO = 22 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E22,
                             CASE WHEN EM.TAMANHO = 23 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E23,
                             CASE WHEN EM.TAMANHO = 24 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E24,
                             CASE WHEN EM.TAMANHO = 25 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E25,
                             CASE WHEN EM.TAMANHO = 26 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E26,
                             CASE WHEN EM.TAMANHO = 27 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E27,
                             CASE WHEN EM.TAMANHO = 28 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E28,
                             CASE WHEN EM.TAMANHO = 29 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E29,
                             CASE WHEN EM.TAMANHO = 30 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E30,
                             CASE WHEN EM.TAMANHO = 31 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E31,
                             CASE WHEN EM.TAMANHO = 32 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E32,
                             CASE WHEN EM.TAMANHO = 33 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E33,
                             CASE WHEN EM.TAMANHO = 34 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E34,
                             CASE WHEN EM.TAMANHO = 35 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E35,
                             CASE WHEN EM.TAMANHO = 36 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E36,
                             CASE WHEN EM.TAMANHO = 37 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E37,
                             CASE WHEN EM.TAMANHO = 38 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E38,
                             CASE WHEN EM.TAMANHO = 39 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E39,
                             CASE WHEN EM.TAMANHO = 40 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E40,
                             CASE WHEN EM.TAMANHO = 41 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E41,
                             CASE WHEN EM.TAMANHO = 42 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E42,
                             CASE WHEN EM.TAMANHO = 43 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E43,
                             CASE WHEN EM.TAMANHO = 44 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E44,
                             CASE WHEN EM.TAMANHO = 45 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E45,
                             CASE WHEN EM.TAMANHO = 46 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E46,
                             CASE WHEN EM.TAMANHO = 47 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E47,
                             CASE WHEN EM.TAMANHO = 48 THEN ISNULL(EM.TOTAL,0) ELSE 0 END AS E48
                      FROM (
                            SELECT F.FILIAL,
                                   PR.PRODUTO,
                                   PR.COR_PRODUTO,
                                   PR.TAMANHO,
                                   (CASE WHEN PE.CANCELADO = 1 THEN 0 ELSE SUM(ISNULL(PR.QTDE,0)) END ) TOTAL, --REMOVENDO OS PEDIDOS QUE TIVERAM A TROCA CANCELADAS
                                   PE.DATA_PARA_TRANSFERENCIA
                            FROM LOJA_PEDIDO (nolock) PE
							INNER JOIN LOJA_PEDIDO_PRODUTO (nolock) PR ON PE.PEDIDO = PR.PEDIDO
                            INNER JOIN FILIAIS (nolock) F ON PE.CODIGO_FILIAL_ORIGEM = F.COD_FILIAL
                            INNER JOIN LOJA_PEDIDO_PGTO (nolock) PG ON PE.PEDIDO = PG.PEDIDO 
							                              AND PG.TIPO_PGTO IN('T','A','I')
                            WHERE PE.DIGITACAO_ENCERRADA = 1
                            AND PE.ENTREGUE = 0 
                            AND PR.QTDE > 0
                            AND PE.PEDIDO > 90000
							AND PE.TIPO_PEDIDO = 4
                            AND PE.PEDIDO_ID_ORIGEM IS NULL 
                            GROUP BY F.FILIAL
                                    ,PR.PRODUTO
                                    ,PR.COR_PRODUTO
                                    ,PR.TAMANHO
                                    ,PE.DATA_PARA_TRANSFERENCIA
                                    ,PE.CANCELADO           
                           ) EM
                      ) EM
				GROUP BY EM.FILIAL,
				         EM.PRODUTO,
				         EM.COR_PRODUTO
	        ) X ON A.PRODUTO = X.PRODUTO 
			    AND A.COR_PRODUTO = X.COR_PRODUTO
				AND A.FILIAL = X.FILIAL;
go

/*
* Tabela e-millenium
* Validado - Paulo Devide - 07-01-2025
* Objeto já existe no Linx
*/
if not Exists(select 1 from sysobjects where name = 'EML_MOVTOS_INTEGRADOS' and type='U')
begin
    CREATE TABLE dbo.EML_MOVTOS_INTEGRADOS
    (
      MOVTO_INTEGRADO INT PRIMARY KEY IDENTITY(1,1),
      PEDIDO INT,
      TICKET VARCHAR(8),
      TIPO_OPERACAO INT,
      COD_OPERACAO INT,
      SERIE VARCHAR(5),
      NUMERO_NOTA VARCHAR(50),
      COD_PEDIDOV VARCHAR(20),
      N_PEDIDO_CLIENTE VARCHAR(50)
    )

    ALTER TABLE EML_MOVTOS_INTEGRADOS ADD N_PEDIDO_CLIENTE VARCHAR(50);

    ALTER TABLE LOJA_PEDIDO_PRODUTO ADD ITEM_MILLENIUM VARCHAR(20) NULL;
end
go

/*
* Tabela e-millenium
* Validado - Paulo Devide - 07-01-2025
* Objeto já existe no Linx
*/
if not Exists(select 1 from sysobjects where name = 'EML_PRODUTOS' and type='U')
begin

    CREATE TABLE dbo.EML_PRODUTOS (
	    PRODUTO VARCHAR(12) NOT NULL,
	    COD_FILIAL VARCHAR(6) NOT NULL,
	    HASHCODE VARCHAR(50),
    )

    CREATE UNIQUE INDEX IDX_EML_PRODUTOS_0 ON dbo.EML_PRODUTOS (COD_FILIAL, PRODUTO);
end
go

/*
* Function e-millenium
* Validado - Paulo Devide - 07-01-2025
* Objeto já existe no Linx
*/
CREATE or alter FUNCTION [dbo].[EML_DATA_MILLISEGUNDOS]	
(@DATA_PARA_TRANSFERENCIA DATETIME,@MILLISEGUNDOS VARCHAR(20))
	RETURNS DATETIME
AS 
BEGIN
	DECLARE	@DATA_COMPLETA	DATETIME
	DECLARE @DIA			VARCHAR(2)
	DECLARE @MES			VARCHAR(2)
	DECLARE @ANO			VARCHAR(4)
	DECLARE @HORA			VARCHAR(2)
	DECLARE @MINUTO			VARCHAR(2)
	DECLARE @SEGUNDO		VARCHAR(2)

	SELECT @DIA = DATEPART(DAY,@DATA_PARA_TRANSFERENCIA)
	SELECT @MES = DATEPART(MONTH,@DATA_PARA_TRANSFERENCIA)
	SELECT @ANO = DATEPART(YEAR,@DATA_PARA_TRANSFERENCIA)
	SELECT @HORA = DATEPART(HOUR,@DATA_PARA_TRANSFERENCIA)
	SELECT @MINUTO = DATEPART(MINUTE,@DATA_PARA_TRANSFERENCIA)
	SELECT @SEGUNDO = DATEPART(SECOND,@DATA_PARA_TRANSFERENCIA)

	SELECT @DATA_COMPLETA = CONVERT(DATETIME,@ANO + '-' + @MES + '-' + @DIA + ' ' + @HORA + ':' + @MINUTO + ':' + @SEGUNDO + '.' + @MILLISEGUNDOS)

	RETURN @DATA_COMPLETA 

END
go

/*
* Tabela e-millenium
* Validado - Paulo Devide - 07-01-2025
* Inserir colunas novas - colunas já existem
*/
--ALTER TABLE EML_MOVTOS_INTEGRADOS ADD CODIGO_FILIAL VARCHAR(6) NULL, DATA_VENDA DATETIME NULL
--go

/*
* Tabela e-millenium
* Validado - Paulo Devide - 07-01-2025
*/ 
ALTER TABLE VENDAS ADD PEDIDO_IMP_MILEN VARCHAR(1) NULL
go

/*
* Trigger e-millenium
* Validado - Paulo Devide - 07-01-2025
* Fazer backup da trigger original antes
*/ 
CREATE OR ALTER TRIGGER LXD_VENDAS ON VENDAS
FOR DELETE NOT FOR REPLICATION
AS
begin

	Declare	@errmsg varchar(255);

    IF EXISTS (
        SELECT 1
        FROM deleted
        WHERE PEDIDO_IMP_MILEN = 'T'
    )
    BEGIN
        /* Lança um erro e impede a exclusão */
		select @errmsg = 'Exclusão não permitida: O pedido já foi importado para o Millennium.';
        goto error;
    END

	return
Error:
	raiserror (@errmsg, 16, 1)
	rollback transaction
End
go

/*
* Trigger e-millenium
* Validado - Paulo Devide - 07-01-2025
* Fazer backup da trigger original antes
*/
CREATE OR ALTER Trigger LXUDT_VENDAS On VENDAS
For UPDATE NOT FOR REPLICATION
As 
-- Trigger para controle de DATA_PARA_TRANSFERENCIA
Begin
	---DATA PARA TRANSFERENCIA---------------------------------------------------------------------------
	IF NOT UPDATE(DATA_PARA_TRANSFERENCIA)
	UPDATE 	T
	SET 	DATA_PARA_TRANSFERENCIA = GETDATE()
	FROM 	[VENDAS] T
			JOIN INSERTED I ON
				I.[PEDIDO]=T.[PEDIDO]
	-----------------------------------------------------------------------------------------------------
	return
End
go

/*
* Trigger e-millenium
* Validado - Paulo Devide - 07-01-2025
* Fazer backup da trigger original antes
*/
CREATE OR ALTER trigger [dbo].[LXI_VENDAS_PRODUTO] 
on [dbo].[VENDAS_PRODUTO]
  for INSERT NOT FOR REPLICATION
  as
begin
  declare  @errno   int,
           @errmsg  varchar(255)

  /* VENDAS_PRODUTO ON CHILD INSERT RESTRICT */  

  if exists (Select 1 
             From Vendas V
             Inner Join inserted I
              On V.Pedido = I.Pedido
             Where V.PEDIDO_IMP_MILEN = 'T')
  begin
    select @errno  = 30002,
           @errmsg = 'Inclusão de produto não permitida para pedidos já enviados ao Millennium.'
    goto error
  end  

  return
error:
    raiserror (@errmsg, 16, 1)
    rollback transaction
End
go

/*
* Trigger e-millenium
* Validado - Paulo Devide - 07-01-2025
* Fazer backup da trigger original antes
*/
CREATE OR ALTER Trigger [dbo].[LXU_VENDAS_PRODUTO] 
On [dbo].[VENDAS_PRODUTO]  
FOR UPDATE NOT FOR REPLICATION  
AS   
BEGIN
    DECLARE @ERRNO   INT,
	        @ERRMSG  VARCHAR(255);

    IF UPDATE(PRECO1) 
    OR UPDATE(VO1)  OR UPDATE(VO2)  OR UPDATE(VO3)  OR UPDATE(VO4) 
	OR UPDATE(VO5)  OR UPDATE(VO6)  OR UPDATE(VO7)  OR UPDATE(VO8) 
	OR UPDATE(VO9)  OR UPDATE(VO10) OR UPDATE(VO11) OR UPDATE(VO12) 
	OR UPDATE(VO13) OR UPDATE(VO14) OR UPDATE(VO15) OR UPDATE(VO16) 
	OR UPDATE(VO17) OR UPDATE(VO18) OR UPDATE(VO19) OR UPDATE(VO20) 
	OR UPDATE(VO21) OR UPDATE(VO22) OR UPDATE(VO23) OR UPDATE(VO24) 
	OR UPDATE(VO25) OR UPDATE(VO26) OR UPDATE(VO27) OR UPDATE(VO28) 
	OR UPDATE(VO29) OR UPDATE(VO30) OR UPDATE(VO31) OR UPDATE(VO32) 
	OR UPDATE(VO33) OR UPDATE(VO34) OR UPDATE(VO35) OR UPDATE(VO36) 
	OR UPDATE(VO37) OR UPDATE(VO38) OR UPDATE(VO39) OR UPDATE(VO40) 
	OR UPDATE(VO41) OR UPDATE(VO42) OR UPDATE(VO43) OR UPDATE(VO44) 
	OR UPDATE(VO45) OR UPDATE(VO46) OR UPDATE(VO47) OR UPDATE(VO48)
	BEGIN
	  if exists (Select 1 
                 From Vendas V
                 Inner Join inserted A
                  On V.Pedido = A.Pedido
                 Where V.PEDIDO_IMP_MILEN = 'T')
      begin
        select @errno  = 30002,
               @errmsg = 'Alteração do produto não permitida para pedidos já enviados ao Millennium.'
        goto error
      end
	END

	-- Alterado por Cris  
	-- Data: 27/09/2009  
	-- Venda entrega futura  
	 IF UPDATE(QTDE_CANCELADA) 
	 BEGIN   
		  DECLARE 
			@ID_VENDA_ENTREGA_FUTURA INT,  
			@CODIGO_CLIENTE VARCHAR(14),  
			@QTDE INT,  
			@PRODUTO CHAR(12),  
			@COR_PRODUTO CHAR(10),   
			@CODIGO_BARRA VARCHAR(25),   
			@PRECO NUMERIC(14,2),  
			@DESCONTO NUMERIC(14,2),  
			@TAMANHO INT,  
			@TICKET CHAR(8),  
			@CODIGO_FILIAL CHAR(6),  
			@TICKET_OLD CHAR(8),  
			@DATA_VENDA DATETIME,  
			@ITEM CHAR(4),  
			@CONTADOR INT--,  
			--@ERRNO   INT,
			--@ERRMSG  VARCHAR(255)  
		    
		-- VERIFICA SE O PEDIDO É ENTREGA FUTURA  
		IF EXISTS(
			SELECT 
				* 
			FROM 
				INSERTED A
				JOIN LJ_VENDA_ENTREGA_FUTURA B ON A.ID_VENDA_ENTREGA_FUTURA = B.ID_VENDA_ENTREGA_FUTURA
			WHERE
				B.QTDE_CANCELADA > 0 AND A.QTDE_CANCELADA = 0)
			
			BEGIN 
				SELECT 	@ERRNO=30002,
				@ERRMSG='NÃO É POSSÍVEL EXCLUIR EXISTEM ITENS COM ENTREGA FUTURA.'
				GOTO ERROR
			END 	
		    
		    
			SET @CONTADOR = 1  
		  
		   SELECT  
			@CODIGO_FILIAL = A.CODIGO_FILIAL, @TICKET_OLD = A.TICKET, @DATA_VENDA = A.DATA_VENDA, @CODIGO_CLIENTE = A.CODIGO_CLIENTE
		   FROM   
			LOJA_VENDA A  
			JOIN LJ_VENDA_ENTREGA_FUTURA B ON  A.TICKET = B.TICKET AND A.CODIGO_FILIAL = B.CODIGO_FILIAL AND A.DATA_VENDA = B.DATA_VENDA  
			JOIN INSERTED C ON B.ID_VENDA_ENTREGA_FUTURA = C.ID_VENDA_ENTREGA_FUTURA   
		   WHERE C.QTDE_CANCELADA > 0
			
		  --- GERA NOVO TICKET PARA A TROCA ENTREGA FUTURA (CANCELAMENTO) 	
		   SELECT   
			@TICKET = 'R' + RIGHT(REPLICATE('0', 7) + CONVERT(VARCHAR, CONVERT(INT, ISNULL(MAX(SUBSTRING(A.TICKET,2,8)), '0')) + 1), 7)  
		   FROM   
			LOJA_VENDA A  
		   WHERE   
			LEFT(A.TICKET,1) = 'R' AND A.CODIGO_FILIAL = @CODIGO_FILIAL   
		    

			IF NOT EXISTS(SELECT * FROM LOJA_VENDA WHERE TICKET = @TICKET AND CODIGO_FILIAL = @CODIGO_FILIAL )   
			BEGIN  
			 
				INSERT INTO   
					LOJA_VENDA (CODIGO_FILIAL, TICKET, DATA_VENDA, CODIGO_DESCONTO, CODIGO_CLIENTE,   
					DATA_DIGITACAO, VENDEDOR, OPERACAO_VENDA, CODIGO_TAB_PRECO, DESCONTO,   
					QTDE_TOTAL, VALOR_TIKET, VALOR_PAGO, VALOR_VENDA_BRUTA, VALOR_TROCA,   
					QTDE_TROCA_TOTAL, TERMINAL, GERENTE_LOJA, GERENTE_PERIODO, CODIGO_FILIAL_PGTO,   
					TERMINAL_PGTO, LANCAMENTO_CAIXA, DATA_HORA_CANCELAMENTO, PERIODO_FECHAMENTO, SUGESTAO_COD_FORMA_PGTO,   
					COD_FIDELIDADE_PROGRAMA, COD_FIDELIDADE_RESGATE, CPF_CGC_ECF)   
				SELECT 
					@CODIGO_FILIAL, @TICKET, CONVERT(VARCHAR(10),GETDATE(),112), NULL, @CODIGO_CLIENTE,  
					GETDATE(), VENDEDOR, OPERACAO_VENDA, CODIGO_TAB_PRECO, 0,   
					0, 0, 0, 0, 0, 0,
					TERMINAL, GERENTE_LOJA, GERENTE_PERIODO, NULL,   
					NULL, NULL, NULL, PERIODO_FECHAMENTO, SUGESTAO_COD_FORMA_PGTO,   
					NULL, NULL, CPF_CGC_ECF  
				FROM   
					LOJA_VENDA A  
					INNER JOIN LOJA_VENDA_PRODUTO B ON A.CODIGO_FILIAL = B.CODIGO_FILIAL AND A.TICKET = B.TICKET AND A.DATA_VENDA = B.DATA_VENDA   
					INNER JOIN LJ_VENDA_ENTREGA_FUTURA C ON B.CODIGO_FILIAL = C.CODIGO_FILIAL AND B.TICKET = C.TICKET AND B.DATA_VENDA = C.DATA_VENDA AND B.ITEM = C.ITEM  
				WHERE  
					A.TICKET = @TICKET_OLD AND A.CODIGO_FILIAL = @CODIGO_FILIAL AND A.DATA_VENDA = @DATA_VENDA  
				GROUP BY  
					VENDEDOR, OPERACAO_VENDA, CODIGO_TAB_PRECO, TERMINAL, GERENTE_LOJA, GERENTE_PERIODO,    
					PERIODO_FECHAMENTO, SUGESTAO_COD_FORMA_PGTO, CPF_CGC_ECF  
			END     

			DECLARE CUR_VENDAS CURSOR   
			FOR   

				SELECT 
					ID_VENDA_ENTREGA_FUTURA, SUM(QTDE), PRODUTO, COR_PRODUTO, PRECO1, SUM(DESCONTO_ITEM), TAMANHO, CODIGO_BARRA  
				FROM  
					(SELECT   
						A.ID_VENDA_ENTREGA_FUTURA, (SUM(A.QTDE_CANCELADA) *-1) AS QTDE, A.PRODUTO, A.COR_PRODUTO,   
						A.PRECO1, C.DESCONTO_ITEM, C.TAMANHO, C.CODIGO_BARRA  
					FROM  
						INSERTED A  
						JOIN LJ_VENDA_ENTREGA_FUTURA B ON A.ID_VENDA_ENTREGA_FUTURA = B.ID_VENDA_ENTREGA_FUTURA  
						JOIN LOJA_VENDA_PRODUTO C ON B.CODIGO_FILIAL = C.CODIGO_FILIAL AND B.TICKET = C.TICKET AND B.DATA_VENDA = C.DATA_VENDA AND B.ITEM = C.ITEM   
					GROUP BY   
						A.ID_VENDA_ENTREGA_FUTURA,A.PRODUTO, A.COR_PRODUTO,A.PRECO1, C.DESCONTO_ITEM, C.TAMANHO, C.CODIGO_BARRA  
					UNION ALL   
					SELECT  
						A.ID_VENDA_ENTREGA_FUTURA, SUM(A.QTDE_CANCELADA) AS QTDE, A.PRODUTO, A.COR_PRODUTO,  
						A.PRECO1, C.DESCONTO_ITEM, C.TAMANHO, C.CODIGO_BARRA  
					FROM  
						DELETED A  
						JOIN LJ_VENDA_ENTREGA_FUTURA B ON A.ID_VENDA_ENTREGA_FUTURA = B.ID_VENDA_ENTREGA_FUTURA  
						JOIN LOJA_VENDA_PRODUTO C ON B.CODIGO_FILIAL = C.CODIGO_FILIAL AND B.TICKET = C.TICKET AND B.DATA_VENDA = C.DATA_VENDA AND B.ITEM = C.ITEM   
					GROUP BY   
						A.ID_VENDA_ENTREGA_FUTURA,A.PRODUTO, A.COR_PRODUTO,A.PRECO1, C.DESCONTO_ITEM, C.TAMANHO, C.CODIGO_BARRA) A 
				GROUP BY  
					ID_VENDA_ENTREGA_FUTURA, PRODUTO, COR_PRODUTO, PRECO1, TAMANHO, CODIGO_BARRA  
				HAVING SUM(QTDE) != 0    

			OPEN CUR_VENDAS  
			FETCH NEXT FROM CUR_VENDAS INTO @ID_VENDA_ENTREGA_FUTURA, @QTDE, @PRODUTO, @COR_PRODUTO, @PRECO, @DESCONTO, @TAMANHO, @CODIGO_BARRA  

			WHILE @@FETCH_STATUS = 0    
			BEGIN  
			 
				UPDATE   
					LJ_VENDA_ENTREGA_FUTURA  
				SET   
					QTDE_CANCELADA =  @QTDE * -1, QTDE_ENTREGAR = 0, QTDE_ENTREGUE = 0   
				WHERE   
					ID_VENDA_ENTREGA_FUTURA = @ID_VENDA_ENTREGA_FUTURA  
				     
				SET @ITEM = RIGHT(REPLICATE('0', 4) + CONVERT(VARCHAR, @CONTADOR), 4)   
				  
				INSERT INTO 
					LOJA_VENDA_TROCA (TICKET, CODIGO_FILIAL, ITEM, DATA_VENDA, CODIGO_BARRA, PRODUTO, COR_PRODUTO, TAMANHO, QTDE, PRECO_LIQUIDO, INDICA_ENTREGA_FUTURA, NAO_MOVIMENTA_ESTOQUE)  
				VALUES
					(@TICKET, @CODIGO_FILIAL, @ITEM, CONVERT(VARCHAR(10),GETDATE(),112), @CODIGO_BARRA, @PRODUTO, @COR_PRODUTO, @TAMANHO, @QTDE*-1, @PRECO,  1, 1)  
			 
				UPDATE   
					 LOJA_VENDA  
				SET  
				 VALOR_PAGO = (VALOR_PAGO + (@QTDE*@PRECO)) , VALOR_TROCA = VALOR_TROCA + (@QTDE*@PRECO) *-1,   
				 QTDE_TROCA_TOTAL = QTDE_TROCA_TOTAL + (@QTDE *-1)
				WHERE 
					TICKET = @TICKET AND CODIGO_FILIAL = @CODIGO_FILIAL  
				
		 		SET @CONTADOR = @CONTADOR + 1  
			 
				FETCH NEXT FROM CUR_VENDAS  INTO @ID_VENDA_ENTREGA_FUTURA, @QTDE, @PRODUTO, @COR_PRODUTO, @PRECO, @DESCONTO, @TAMANHO, @CODIGO_BARRA  
			END   

			CLOSE CUR_VENDAS  
			DEALLOCATE CUR_VENDAS  
		END    

  RETURN
	ERROR:
    raiserror (@errmsg, 16, 1)
    ROLLBACK TRANSACTION
END
go

/*
* View e-millenium
* Validado - Paulo Devide - 07-01-2025
* Fazer backup da trigger original antes
*/
CREATE VIEW dbo.EML_VerificaTabelaSKU
AS
SELECT 
    CASE 
        WHEN OBJECT_ID('SKU', 'U') IS NOT NULL 
        THEN 1 
        ELSE 0 
    END AS ExisteSKU;
go

/*
* View e-millenium
* Validado - Paulo Devide - 07-01-2025
* Fazer backup da trigger original antes
*/
Create VIEW [dbo].[EML_MapeamentoTamanhos]
AS
SELECT
	g.GRADE AS GRADE_PRODUTO,
    x.Tamanho,
    x.Grade
FROM PRODUTOS_TAMANHOS (nolock) g
CROSS APPLY (VALUES
('TAMANHO_1', g.[TAMANHO_1], TRY_CAST(REPLACE('TAMANHO_1','Tamanho_','') AS INT)),
('TAMANHO_10', g.[TAMANHO_10], TRY_CAST(REPLACE('TAMANHO_10','Tamanho_','') AS INT)),
('TAMANHO_11', g.[TAMANHO_11], TRY_CAST(REPLACE('TAMANHO_11','Tamanho_','') AS INT)),
('TAMANHO_12', g.[TAMANHO_12], TRY_CAST(REPLACE('TAMANHO_12','Tamanho_','') AS INT)),
('TAMANHO_13', g.[TAMANHO_13], TRY_CAST(REPLACE('TAMANHO_13','Tamanho_','') AS INT)),
('TAMANHO_14', g.[TAMANHO_14], TRY_CAST(REPLACE('TAMANHO_14','Tamanho_','') AS INT)),
('TAMANHO_15', g.[TAMANHO_15], TRY_CAST(REPLACE('TAMANHO_15','Tamanho_','') AS INT)),
('TAMANHO_16', g.[TAMANHO_16], TRY_CAST(REPLACE('TAMANHO_16','Tamanho_','') AS INT)),
('TAMANHO_17', g.[TAMANHO_17], TRY_CAST(REPLACE('TAMANHO_17','Tamanho_','') AS INT)),
('TAMANHO_18', g.[TAMANHO_18], TRY_CAST(REPLACE('TAMANHO_18','Tamanho_','') AS INT)),
('TAMANHO_19', g.[TAMANHO_19], TRY_CAST(REPLACE('TAMANHO_19','Tamanho_','') AS INT)),
('TAMANHO_2', g.[TAMANHO_2], TRY_CAST(REPLACE('TAMANHO_2','Tamanho_','') AS INT)),
('TAMANHO_20', g.[TAMANHO_20], TRY_CAST(REPLACE('TAMANHO_20','Tamanho_','') AS INT)),
('TAMANHO_21', g.[TAMANHO_21], TRY_CAST(REPLACE('TAMANHO_21','Tamanho_','') AS INT)),
('TAMANHO_22', g.[TAMANHO_22], TRY_CAST(REPLACE('TAMANHO_22','Tamanho_','') AS INT)),
('TAMANHO_23', g.[TAMANHO_23], TRY_CAST(REPLACE('TAMANHO_23','Tamanho_','') AS INT)),
('TAMANHO_24', g.[TAMANHO_24], TRY_CAST(REPLACE('TAMANHO_24','Tamanho_','') AS INT)),
('TAMANHO_25', g.[TAMANHO_25], TRY_CAST(REPLACE('TAMANHO_25','Tamanho_','') AS INT)),
('TAMANHO_26', g.[TAMANHO_26], TRY_CAST(REPLACE('TAMANHO_26','Tamanho_','') AS INT)),
('TAMANHO_27', g.[TAMANHO_27], TRY_CAST(REPLACE('TAMANHO_27','Tamanho_','') AS INT)),
('TAMANHO_28', g.[TAMANHO_28], TRY_CAST(REPLACE('TAMANHO_28','Tamanho_','') AS INT)),
('TAMANHO_29', g.[TAMANHO_29], TRY_CAST(REPLACE('TAMANHO_29','Tamanho_','') AS INT)),
('TAMANHO_3', g.[TAMANHO_3], TRY_CAST(REPLACE('TAMANHO_3','Tamanho_','') AS INT)),
('TAMANHO_30', g.[TAMANHO_30], TRY_CAST(REPLACE('TAMANHO_30','Tamanho_','') AS INT)),
('TAMANHO_31', g.[TAMANHO_31], TRY_CAST(REPLACE('TAMANHO_31','Tamanho_','') AS INT)),
('TAMANHO_32', g.[TAMANHO_32], TRY_CAST(REPLACE('TAMANHO_32','Tamanho_','') AS INT)),
('TAMANHO_33', g.[TAMANHO_33], TRY_CAST(REPLACE('TAMANHO_33','Tamanho_','') AS INT)),
('TAMANHO_34', g.[TAMANHO_34], TRY_CAST(REPLACE('TAMANHO_34','Tamanho_','') AS INT)),
('TAMANHO_35', g.[TAMANHO_35], TRY_CAST(REPLACE('TAMANHO_35','Tamanho_','') AS INT)),
('TAMANHO_36', g.[TAMANHO_36], TRY_CAST(REPLACE('TAMANHO_36','Tamanho_','') AS INT)),
('TAMANHO_37', g.[TAMANHO_37], TRY_CAST(REPLACE('TAMANHO_37','Tamanho_','') AS INT)),
('TAMANHO_38', g.[TAMANHO_38], TRY_CAST(REPLACE('TAMANHO_38','Tamanho_','') AS INT)),
('TAMANHO_39', g.[TAMANHO_39], TRY_CAST(REPLACE('TAMANHO_39','Tamanho_','') AS INT)),
('TAMANHO_4', g.[TAMANHO_4], TRY_CAST(REPLACE('TAMANHO_4','Tamanho_','') AS INT)),
('TAMANHO_40', g.[TAMANHO_40], TRY_CAST(REPLACE('TAMANHO_40','Tamanho_','') AS INT)),
('TAMANHO_41', g.[TAMANHO_41], TRY_CAST(REPLACE('TAMANHO_41','Tamanho_','') AS INT)),
('TAMANHO_42', g.[TAMANHO_42], TRY_CAST(REPLACE('TAMANHO_42','Tamanho_','') AS INT)),
('TAMANHO_43', g.[TAMANHO_43], TRY_CAST(REPLACE('TAMANHO_43','Tamanho_','') AS INT)),
('TAMANHO_44', g.[TAMANHO_44], TRY_CAST(REPLACE('TAMANHO_44','Tamanho_','') AS INT)),
('TAMANHO_45', g.[TAMANHO_45], TRY_CAST(REPLACE('TAMANHO_45','Tamanho_','') AS INT)),
('TAMANHO_46', g.[TAMANHO_46], TRY_CAST(REPLACE('TAMANHO_46','Tamanho_','') AS INT)),
('TAMANHO_47', g.[TAMANHO_47], TRY_CAST(REPLACE('TAMANHO_47','Tamanho_','') AS INT)),
('TAMANHO_48', g.[TAMANHO_48], TRY_CAST(REPLACE('TAMANHO_48','Tamanho_','') AS INT)),
('TAMANHO_5', g.[TAMANHO_5], TRY_CAST(REPLACE('TAMANHO_5','Tamanho_','') AS INT)),
('TAMANHO_6', g.[TAMANHO_6], TRY_CAST(REPLACE('TAMANHO_6','Tamanho_','') AS INT)),
('TAMANHO_7', g.[TAMANHO_7], TRY_CAST(REPLACE('TAMANHO_7','Tamanho_','') AS INT)),
('TAMANHO_8', g.[TAMANHO_8], TRY_CAST(REPLACE('TAMANHO_8','Tamanho_','') AS INT)),
('TAMANHO_9', g.[TAMANHO_9], TRY_CAST(REPLACE('TAMANHO_9','Tamanho_','') AS INT))
) AS x(Nome_Tamanho, grade, Tamanho)
WHERE (x.grade IS NOT NULL and  x.grade<>' ' and x.grade not like '%.%');
go

---------------------------------------------------------------------------------------------------------
/*
* Function e-millenium
* Validado - Paulo Devide - 07-01-2025
* Fazer backup da trigger original antes
*/
CREATE or alter FUNCTION [dbo].[EML_DATA_VARCHAR]	
(@DATA_PARA_TRANSFERENCIA DATETIME)
	RETURNS varchar(200)
AS 
BEGIN
	DECLARE	@DATA_COMPLETA	varchar(200)
	DECLARE @DIA			VARCHAR(2)
	DECLARE @MES			VARCHAR(2)
	DECLARE @ANO			VARCHAR(4)
	DECLARE @HORA			VARCHAR(2)
	DECLARE @MINUTO			VARCHAR(2)
	DECLARE @SEGUNDO		VARCHAR(2)
	DECLARE @MILLISEGUNDOS	VARCHAR(3)

	SELECT @DIA = REPLICATE('0', 2 - LEN(DATEPART(DAY,@DATA_PARA_TRANSFERENCIA))) + RTrim(DATEPART(DAY,@DATA_PARA_TRANSFERENCIA))
	SELECT @MES = REPLICATE('0', 2 - LEN(DATEPART(MONTH,@DATA_PARA_TRANSFERENCIA))) + RTrim(DATEPART(MONTH,@DATA_PARA_TRANSFERENCIA))
	SELECT @ANO = DATEPART(YEAR,@DATA_PARA_TRANSFERENCIA)
	SELECT @HORA = REPLICATE('0', 2 - LEN(DATEPART(HOUR,@DATA_PARA_TRANSFERENCIA))) + RTrim(DATEPART(HOUR,@DATA_PARA_TRANSFERENCIA))
	SELECT @MINUTO = REPLICATE('0', 2 - LEN(DATEPART(MINUTE,@DATA_PARA_TRANSFERENCIA))) + RTrim(DATEPART(MINUTE,@DATA_PARA_TRANSFERENCIA))
	SELECT @SEGUNDO = REPLICATE('0', 2 - LEN(DATEPART(SECOND,@DATA_PARA_TRANSFERENCIA))) + RTrim(DATEPART(SECOND,@DATA_PARA_TRANSFERENCIA))
	SELECT @MILLISEGUNDOS = REPLICATE('0', 3 - LEN(DATEPART(MILLISECOND,@DATA_PARA_TRANSFERENCIA))) + RTrim(DATEPART(MILLISECOND,@DATA_PARA_TRANSFERENCIA))

	SELECT @DATA_COMPLETA = (@ANO + @MES + @DIA + @HORA + @MINUTO + @SEGUNDO + @MILLISEGUNDOS)

	RETURN @DATA_COMPLETA 

END
GO
