--select * from filiais where COD_FILIAL = '000127'


/** Cria a nova tabela de preços baseada em outra existente **/
insert into TABELAS_PRECO (CODIGO_TAB_PRECO,TABELA,MOEDA,LANCAMENTO_TABELA,
							DATA_DESATIVACAO,ATACADO_VAREJO,STATUS,ENVIA_LOJA_VAREJO,
							ENVIA_REPRESENTANTE,ENVIA_VAREJO_INTERNET, ENVIA_ATACADO_INTERNET,
							INATIVO,DATA_PARA_TRANSFERENCIA, CONDICAO_PGTO,OBS, CODIGO_TAB_PRECO_BASE,
							PRECO_TIPO,BLOQ_ATUALIZACAO_BASE, EMPRESA, LX_STATUS_REGISTRO)

SELECT 'ML' AS CODIGO_TAB_PRECO, 'VENDA_MERCADO_LIVRE' AS TABELA, MOEDA, '20221006' AS LANCAMENTO_TABELA,
							DATA_DESATIVACAO,ATACADO_VAREJO,STATUS,ENVIA_LOJA_VAREJO,
							ENVIA_REPRESENTANTE,ENVIA_VAREJO_INTERNET, ENVIA_ATACADO_INTERNET,
							INATIVO, GETDATE() AS DATA_PARA_TRANSFERENCIA, CONDICAO_PGTO,OBS, CODIGO_TAB_PRECO_BASE,
							PRECO_TIPO,BLOQ_ATUALIZACAO_BASE, EMPRESA, LX_STATUS_REGISTRO
FROM TABELAS_PRECO WHERE CODIGO_TAB_PRECO='73' /*TABELA LIKE '%TATUAPE%'*/

/** Atrela uma filial na nova tabela **/
SELECT * FROM TABELAS_PRECO_FILIAL

INSERT INTO TABELAS_PRECO_FILIAL
SELECT 'ML'  AS CODIGO_TAB_PRECO,
'LOJA VIRTUAL' AS FILIAL,
GERA_TABELA_LOJA,
PERMITE_GESTAO_LOJA,
FATOR_PRECO_BASE,
INATIVO,
DATA_PARA_TRANSFERENCIA,
BLOQ_ATUALIZACAO_BASE,
LIMITE_VARIACAO_PRECO,
LX_STATUS_REGISTRO
FROM TABELAS_PRECO_FILIAL
WHERE CODIGO_TAB_PRECO='73'


-- pega precos de sao matheus como base
begin tran
INSERT INTO PRODUTOS_PRECOS
(CODIGO_TAB_PRECO,
		PRODUTO,
		PRECO1,
		PRECO2,
		PRECO3,
		PRECO4,
		LIMITE_DESCONTO,
		PROMOCAO_DESCONTO,
		ULT_ATUALIZACAO,
		INICIO_PROMOCAO,
		FIM_PROMOCAO,
		DATA_PARA_TRANSFERENCIA,
		MARK_UP_PREVISTO,
		PROMOCAO_ATACADO,
		PRECO_LIQUIDO1,
		PRECO_LIQUIDO2,
		PRECO_LIQUIDO3,
		PRECO_LIQUIDO4,
		LX_STATUS_REGISTRO,
		PRECO1_ANTERIOR,
		DATA_CARGA_PRECOS)
SELECT	distinct
		'ML' AS CODIGO_TAB_PRECO,
		PRODUTO,
		PRECO1,
		PRECO2,
		PRECO3,
		PRECO4,
		LIMITE_DESCONTO,
		PROMOCAO_DESCONTO,
		CONVERT(VARCHAR,GETDATE(),112) AS ULT_ATUALIZACAO,
		INICIO_PROMOCAO,
		FIM_PROMOCAO,
		'19000101' AS DATA_PARA_TRANSFERENCIA,
		MARK_UP_PREVISTO,
		PROMOCAO_ATACADO,
		PRECO_LIQUIDO1,
		PRECO_LIQUIDO2,
		PRECO_LIQUIDO3,
		PRECO_LIQUIDO4,
		LX_STATUS_REGISTRO,
		PRECO1_ANTERIOR,
		DATA_CARGA_PRECOS
FROM PRODUTOS_PRECOS WHERE CODIGO_TAB_PRECO='11' 
AND PRODUTO NOT IN (SELECT PRODUTO FROM PRODUTOS_PRECOS WHERE CODIGO_TAB_PRECO='ML')

commit


SELECT * FROM PRODUTOS_PRECOS WHERE CODIGO_TAB_PRECO='ML'


