alter table arb_markdown_gerado add usuario_aprovacao varchar(40) null
go

insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','BARUERI',1,'gr.barueri@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','CARAGUATATUBA',1,'gr.caraguatatuba@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','CARAPICUIBA',1,'gr.carapicuiba@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','CIDADE OCIAN',1,'gr.cidadeocian@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','CIDADE TIRADENTES',1,'gr.cidadetiradentes@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','COTIA',1,'gr.cotia@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','CRUZEIRO',1,'gr.cruzeiro@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','DIADEMA',1,'gr.diadema@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','FERRAZ',1,'gr.ferraz@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','FRANCISCO MORATO',1,'gr.franciscomorato@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','FRANCO DA ROCHA',1,'gr.francodarocha@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','GUARATINGUETA',1,'gr.guaratingueta@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','HORTOLANDIA',1,'gr.hortolandia@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','INDAIATUBA',1,'gr.indaiatuba@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','IPIRANGA',1,'gr.ipiranga@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','ITAIM',1,'gr.itaimpaulista@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','ITAPECERICA',1,'gr.itapecerica@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','ITAPEVI',1,'gr.itapevi@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','ITAQUA',1,'gr.itaqua@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','ITAQUERA',1,'gr.itaquera@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','ITU',1,'gr.itu@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','JAÇANA',1,'gr.jacana@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','JARDIM ANGELA',1,'gr.mboimirim@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','JARDIM IGUATEMI',1,'gr.jardimiguatemi@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','JUNDIAI',1,'gr.jundiai@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','MAUA',1,'gr.maua@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','MOGI DAS CRUZES',1,'gr.mogidascruzes@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','MOGI GUACU',1,'gr.mogiguacu@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','PINDAMONHANGABA',1,'gr.pinda@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','PIRASSUNUNGA',1,'gr.pirassununga@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','POA',1,'gr.poa@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','PRAIA GRANDE',1,'gr.praiagrande@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','REGISTRO',1,'gr.registro@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','SAO BERNARDO',1,'gr.saobernardo@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','SAO MATHEUS',1,'gr.saomatheus@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','SP - BRASILANDIA ',1,'gr.brasilandia@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','SP - CAPAO CENTRO',1,'gr.capaocentro@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','SP - GRAJAU',1,'gr.grajau@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','SP - METRO CAPAO',1,'gr.metrocapao@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','SP - PIRAPORINHA',1,'gr.piraporinha@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','SP - TUCURUVI',1,'gr.tucuruvi@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','TAUBATE',1,'gr.taubate@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','VARZEA PAULISTA',1,'gr.varzea@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','VICENTE DE CARVALHO',1,'gr.vicentedecarvalho@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','VILA DAS MERCES',1,'gr.vilamerces@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','VILA DIRCE',1,'gr.viladirce@caedu.com.br',getdate()
insert prop_filiais (PROPRIEDADE,FILIAL,ITEM_PROPRIEDADE,VALOR_PROPRIEDADE,DATA_PARA_TRANSFERENCIA) select  '00090','VILA FORMOSA',1,'gr.vilaformosa@caedu.com.br',getdate()
