----INSERT INTO [CAEDU].[DBO].PRODUTOS (PRODUTO,ERP_CODIGO_UMODE,CLASSIF_FISCAL,TIPO_PRODUTO,TABELA_MEDIDAS,DESC_PRODUTO,GRUPO_PRODUTO,SUBGRUPO_PRODUTO,COLECAO,GRADE,DESC_PROD_NF,LINHA,GRIFFE,UNIDADE,PESO,REVENDA,ESTILISTA,INATIVO,ENVIA_LOJA_VAREJO,ENVIA_LOJA_ATACADO,ENVIA_VAREJO_INTERNET,PONTEIRO_PRECO_TAM,CODIGO_PRECO,MATERIAL,PERIODO_PCP,TABELA_OPERACOES,FATOR_OPERACOES,CARTELA,REFER_FABRICANTE,MODELAGEM,FABRICANTE,CUSTO_REPOSICAO1,CUSTO_REPOSICAO2,CUSTO_REPOSICAO3,CUSTO_REPOSICAO4,DATA_REPOSICAO,MODELISTA,TAMANHO_BASE,GIRO_ENTREGA,MODELO,REDE_LOJAS,DATA_PARA_TRANSFERENCIA,FABRICANTE_ICMS_ABATER,FABRICANTE_PRAZO_PGTO,TAXA_JUROS_DEFLACIONAR,TAXAS_IMPOSTOS_APLICAR,PRECO_REPOSICAO_1,PRECO_REPOSICAO_2,PRECO_REPOSICAO_3,PRECO_REPOSICAO_4,PRECO_A_VISTA_REPOSICAO_1,PRECO_A_VISTA_REPOSICAO_2,PRECO_A_VISTA_REPOSICAO_3,PRECO_A_VISTA_REPOSICAO_4,FABRICANTE_FRETE,DROP_DE_TAMANHOS,DATA_CADASTRAMENTO,STATUS_PRODUTO,TIPO_STATUS_PRODUTO,OBS,COMPOSICAO,RESTRICAO_LAVAGEM,ORCAMENTO,CLIENTE_DO_PRODUTO,CONTA_CONTABIL,ESPESSURA,ALTURA,LARGURA,COMPRIMENTO,EMPILHAMENTO_MAXIMO,SEXO_TIPO,PARTE_TIPO,VERSAO_FICHA,COD_FLUXO_PRODUTO,DATA_INICIO_DESENVOLVIMENTO,INDICADOR_CFOP,MONTAGEM_KIT,MRP_AGRUPAR_NECESSIDADE_DIAS,MRP_AGRUPAR_NECESSIDADE_TIPO,MRP_DIAS_SEGURANCA,MRP_EMISSAO_LIBERACAO_DIAS,MRP_ENTREGA_GIRO_DIAS,MRP_PARTICIPANTE,MRP_MAIOR_GIRO_MP_DIAS,OP_QTDE_MAXIMA,OP_QTDE_MINIMA,QUALIDADE,SEMI_ACABADO,CONTA_CONTABIL_COMPRA,CONTA_CONTABIL_VENDA,CONTA_CONTABIL_DEV_COMPRA,CONTA_CONTABIL_DEV_VENDA,ID_EXCECAO_GRUPO,ID_EXCECAO_IMPOSTO,DIAS_COMPRA,FATOR_P,FATOR_Q,FATOR_F,CONTINUIDADE,COD_CATEGORIA,COD_SUBCATEGORIA,COD_PRODUTO_SOLUCAO,COD_PRODUTO_SEGMENTO,TIPO_ITEM_SPED,ID_PRECO,NATUREZA_RECEITA,COD_ALIQUOTA_PIS_COFINS_DIF,DATA_LIMITE_PEDIDO,ERP_CUPS_SEGMENTO,ERP_CUPS_STYLENUMBER,ERP_CUPS_EVENTO,ERP_CUPS_TEMA,ERP_CUPS_COMPRIMENTO,ERP_CUPS_CONTRUCAO,ERP_CUPS_COMPOSICAO,ERP_CUPS_FORRO,ERP_CUPS_PRODUTO,ERP_CUPS_SUPPLIER,ERP_CUPS_PRECO_CUSTO_ESTIMADO,ERP_CUPS_CODEBAR_REF,ERP_CUPS_CODEBAR_PB,ERP_CUPS_CODEBAR_CX,ERP_CUPS_BLOQUEIA_PRODUTO,ERP_CUPS_CONJUNTO,ERP_CUPS_COMPRIMENTO_BOTTOM,ERP_CUPS_COMPOSICAO_BOTTOM,ERP_CUPS_FORRO_BOTTOM,ERP_CUPS_SUBGRUPO_ATACADO,ID_ARTIGO,LX_HASH,SPED_DATA_FIM,SPED_DATA_INI,ID_CEST_NCM,ERP_QTD_PACK,ERP_CUPS_CUSTO_FOB_MINIMO,ERP_CUPS_CUSTO_FOB,ERP_DESC_LICENCIADO,ERP_TEMA_LICENCIADO,ID_MODELAGEM,ERP_USERS_ALTERA_PACK,FATOR_A,FATOR_B,FATOR_BUFFER,FATOR_LT,TIPO_CANAL,ID_MODELAGEM2,ERP_GRUPO_MERCADORIA,ERP_TIPO_ETIQUETA,ERP_DATA_ULTIMO_AGENDAMENTO,TITULO_B2C,DESCRICAO_B2C,TAGS,VIDEO_EMBED,CARACTERISTICAS_TECNICAS_B2C,ESTOQUE_MINIMO,DATA_PUBLICACAO_B2C,GRUPO_PRODUTO_B2C,SUBGRUPO_PRODUTO_B2C,TIPO_PRODUTO_B2C,GRIFFE_B2C,LINHA_B2C,FABRICANTE_B2C,CATEGORIA_B2C,SUBCATEGORIA_B2C,IMG_ESTILO,DESCRICAO_B2C_2,DESCRICAO_B2C_3,ERP_MATERIA_PRIMA) VALUES (23280049,216148,'x','x','','ESTRUTURA TESTE','1','1','FEMIN','','ESTRUTURA TESTE','1','x','x',1,1,'Juliana Ferré',0,1,1,1,'111111111111111111111111111111111111111111111111','x','x','x','x',1,'x','x','x','x',1,1,1,1,getdate(),'x',1,1,'x','x',getdate(),1,1,1,1,1,1,1,1,1,1,1,1,1,1,getdate(),'x',1,'x','x','x','x','x','x',1,1,1,1,1,1,1,'x','x',getdate(),1,1,1,1,1,1,1,1,1,1,1,1,1,'x','x','x','x',1,1,'x',1,1,1,1,'x','x',1,1,'x',1,'x','x',getdate(),'x','x','x','x','x','x','x','x','x','x',1,'x','x','x',1,1,'x','x','x','x',1,1,getdate(),getdate(),1,1,1,1,'x','x',1,'x',1,1,1,1,'x',1,'x','x',getdate(),'x','x','x','x','x',1,getdate(),1,1,1,1,1,1,1,1,'x','x','x','x')

INSERT INTO PRODUTOS (
PRODUTO
,ERP_CODIGO_UMODE
,CLASSIF_FISCAL
,TIPO_PRODUTO
,TABELA_MEDIDAS
,DESC_PRODUTO
,GRUPO_PRODUTO
,SUBGRUPO_PRODUTO
,COLECAO
,GRADE
,DESC_PROD_NF
,LINHA
,GRIFFE
,UNIDADE
,PESO
,REVENDA
,ESTILISTA
,INATIVO
,ENVIA_LOJA_VAREJO
,ENVIA_LOJA_ATACADO
,ENVIA_VAREJO_INTERNET
,PONTEIRO_PRECO_TAM
,CODIGO_PRECO
,MATERIAL
,PERIODO_PCP
,TABELA_OPERACOES
,FATOR_OPERACOES
,CARTELA
,REFER_FABRICANTE
,MODELAGEM
,FABRICANTE
,CUSTO_REPOSICAO1
,CUSTO_REPOSICAO2
,CUSTO_REPOSICAO3
,CUSTO_REPOSICAO4
,DATA_REPOSICAO
,MODELISTA
,TAMANHO_BASE
,GIRO_ENTREGA
,MODELO
,REDE_LOJAS
,DATA_PARA_TRANSFERENCIA
,FABRICANTE_ICMS_ABATER
,FABRICANTE_PRAZO_PGTO
,TAXA_JUROS_DEFLACIONAR
,TAXAS_IMPOSTOS_APLICAR
,PRECO_REPOSICAO_1
,PRECO_REPOSICAO_2
,PRECO_REPOSICAO_3
,PRECO_REPOSICAO_4
,PRECO_A_VISTA_REPOSICAO_1
,PRECO_A_VISTA_REPOSICAO_2
,PRECO_A_VISTA_REPOSICAO_3
,PRECO_A_VISTA_REPOSICAO_4
,FABRICANTE_FRETE
,DROP_DE_TAMANHOS
,DATA_CADASTRAMENTO
,STATUS_PRODUTO
,TIPO_STATUS_PRODUTO
,OBS
,COMPOSICAO
,RESTRICAO_LAVAGEM
,EMPRESA
,ORCAMENTO
,CLIENTE_DO_PRODUTO
,CONTA_CONTABIL
,ESPESSURA
,ALTURA
,LARGURA
,COMPRIMENTO
,EMPILHAMENTO_MAXIMO
,SEXO_TIPO
,PARTE_TIPO
,VERSAO_FICHA
,COD_FLUXO_PRODUTO
,DATA_INICIO_DESENVOLVIMENTO
,INDICADOR_CFOP
,MONTAGEM_KIT
,MRP_AGRUPAR_NECESSIDADE_DIAS
,MRP_AGRUPAR_NECESSIDADE_TIPO
,MRP_DIAS_SEGURANCA
,MRP_EMISSAO_LIBERACAO_DIAS
,MRP_ENTREGA_GIRO_DIAS
,MRP_PARTICIPANTE
,MRP_MAIOR_GIRO_MP_DIAS
,OP_QTDE_MAXIMA
,OP_QTDE_MINIMA
,QUALIDADE
,SEMI_ACABADO
,CONTA_CONTABIL_COMPRA
,CONTA_CONTABIL_VENDA
,CONTA_CONTABIL_DEV_COMPRA
,CONTA_CONTABIL_DEV_VENDA
,ID_EXCECAO_GRUPO
,ID_EXCECAO_IMPOSTO
,DIAS_COMPRA
,FATOR_P
,FATOR_Q
,FATOR_F
,CONTINUIDADE
,COD_CATEGORIA
,COD_SUBCATEGORIA
,COD_PRODUTO_SOLUCAO
,COD_PRODUTO_SEGMENTO
,TIPO_ITEM_SPED
,ID_PRECO
,NATUREZA_RECEITA
,COD_ALIQUOTA_PIS_COFINS_DIF
,DATA_LIMITE_PEDIDO
,ERP_CUPS_SEGMENTO
,ERP_CUPS_STYLENUMBER
,ERP_CUPS_EVENTO
,ERP_CUPS_TEMA
,ERP_CUPS_COMPRIMENTO
,ERP_CUPS_CONTRUCAO
,ERP_CUPS_COMPOSICAO
,ERP_CUPS_FORRO
,ERP_CUPS_PRODUTO
,ERP_CUPS_SUPPLIER
,ERP_CUPS_PRECO_CUSTO_ESTIMADO
,ERP_CUPS_CODEBAR_REF
,ERP_CUPS_CODEBAR_PB
,ERP_CUPS_CODEBAR_CX
,ERP_CUPS_BLOQUEIA_PRODUTO
,ERP_CUPS_CONJUNTO
,ERP_CUPS_COMPRIMENTO_BOTTOM
,ERP_CUPS_COMPOSICAO_BOTTOM
,ERP_CUPS_FORRO_BOTTOM
,ERP_CUPS_SUBGRUPO_ATACADO
,ID_ARTIGO
,SPED_DATA_FIM
,SPED_DATA_INI
,ID_CEST_NCM
,ERP_QTD_PACK
,ERP_CUPS_CUSTO_FOB_MINIMO
,ERP_CUPS_CUSTO_FOB
,ERP_DESC_LICENCIADO
,ERP_TEMA_LICENCIADO
,ID_MODELAGEM
,ERP_USERS_ALTERA_PACK
,FATOR_A
,FATOR_B
,FATOR_BUFFER
,FATOR_LT
,TIPO_CANAL
,ID_MODELAGEM2
,ERP_GRUPO_MERCADORIA
,ERP_TIPO_ETIQUETA
,ERP_DATA_ULTIMO_AGENDAMENTO
,TITULO_B2C
,DESCRICAO_B2C
,TAGS
,VIDEO_EMBED
,CARACTERISTICAS_TECNICAS_B2C
,ESTOQUE_MINIMO
,DATA_PUBLICACAO_B2C
,GRUPO_PRODUTO_B2C
,SUBGRUPO_PRODUTO_B2C
,TIPO_PRODUTO_B2C
,GRIFFE_B2C
,LINHA_B2C
,FABRICANTE_B2C
,CATEGORIA_B2C
,SUBCATEGORIA_B2C
,IMG_ESTILO
,DESCRICAO_B2C_2
,DESCRICAO_B2C_3
,ERP_MATERIA_PRIMA
,TRIBUT_ICMS
,TRIBUT_ORIGEM
,SORTIMENTO_TAMANHO
)
VALUES(
'01050999'
,0
,'62064000'
,'IMPORTADO'
,NULL
,'CAMISA FLANELADA FEM FSH FFC200 A XADREZ'
,'TOP TECIDO'
,'TOP OUTROS TECIDOS'
,'IMPORT'
,'P AO GG'
,'CAMISA FLANELADA FEM FSH FFC200 A XADREZ'
,'FASHION'
,'FEMININO'
,'PC'
,1
,1
,NULL
,0
,1
,1
,1
,'111111111111111111111111111111111111111111111111'
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,'FFC 200 A'
,NULL
,'KOMPORT'
,'25.86'
,0
,0
,0
,'20220801'
,NULL
,1
,0
,NULL
,NULL
,GETDATE()
,0
,0
,0
,0
,'25.86'
,0
,0
,0
,'25.86'
,0
,0
,0
,0
,NULL
,'20221121'
,'01'
,'3'
,NULL
,NULL
,NULL
,1
,NULL
,NULL
,'114.01.005'
,0
,0
,0
,0
,0
,NULL
,NULL
,'00001'
,NULL
,NULL
,'11'
,0
,0
,0
,0
,0
,0
,0
,0
,0
,0
,1
,0
,'114.01.005'
,'311.01.002'
,'114.01.005'
,'311.01.002'
,NULL
,NULL
,NULL
,1
,1
,1
,1
,'2'
,'02'
,NULL
,NULL
,'00'
,NULL
,NULL
,NULL
,NULL
,'000155'
,'FFC 200 A'
,'000854'
,NULL
,'000007'
,'000023'
,'000123'
,'000158'
,'000169'
,'219776'
,NULL
,'0000090510564'
,'10000090510564'
,'90000090510564'
,NULL
,0
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,'12'
,NULL
,NULL
,0
,NULL
,'777777'
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,'TOP TECIDO'
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,'000819'
,'00'
,1
,1
)

--select * from produtos where produto = '01050999'

INSERT INTO PRODUTO_CORES (
PRODUTO
,COR_PRODUTO
,SIMILAR
,DESC_COR_PRODUTO
,STATUS_VENDA_ATUAL
,INICIO_VENDAS
,FIM_VENDAS
,TIPO_LAVAGEM_TINTURARIA
,COR
,MATERIAL
,COR_MATERIAL
,ETIQUETA
,VARIANTE_TAMANHO
,CLASSIF_FISCAL
,COMPOSICAO
,TRIBUT_ORIGEM
,LX_HASH
,CUSTO_REPOSICAO1
,PRECO_REPOSICAO_1
,PRECO_A_VISTA_REPOSICAO_1
)
VALUES (
'01050999'
,'00093'
,null
,'XADREZ'
,'1'
,'19000101'
,'20511231'
,null
,'00093'
,NULL
,NULL
,NULL
,NULL
,'62064000'
,NULL
,'1'
,NULL
,25.86
,25.86
,25.86
)

--SELECT * FROM PRODUTO_CORES WHERE PRODUTO = '01050999'

insert into produtos_packs_permitidos (
PRODUTO
,PACK
,QTDE
,Q1
,Q2
,Q3
,Q4
,Q5
,Q6
,Q7
,Q8
,Q9
,Q10
,Q11
,Q12
,Q13
,Q14
,Q15
,Q16
,COR_PRODUTO
,INDICA_PACK_COR
,INATIVO
)
values (
'01050999'
,'A'
,12
,2
,4
,4
,2
,0
,0
,0
,0
,0
,0
,0
,0
,0
,0
,0
,0
,'00093'
,1
,0
)

--select * from PRODUTOS_PACKS_PERMITIDOS where produto = '01050999'


--select * from produtos_precos where produto = '01050999'

declare @tabprecos table (id int identity(1,1) not null, CODIGO_TAB_PRECO char(2) not null)
insert into @tabprecos (CODIGO_TAB_PRECO)
select CODIGO_TAB_PRECO 
from TABELAS_PRECO 
where
	CODIGO_TAB_PRECO not in ('AT','37','04','CM','CL','VA','00','02', '85') AND INATIVO=0

declare @min int, @max int, @CODIGO_TAB_PRECO char(2), 
		@preco_venda numeric (14,2), @preco_custo numeric (14,2), @produto char(12) 

select @min = min(id), @max = max(id)
from @tabprecos

set @produto = '01050999'
set @preco_custo = 25.86
set @preco_venda = 69.99

-- looping para incluir os preços de venda
while @min <= @max
begin
	
	select @CODIGO_TAB_PRECO=CODIGO_TAB_PRECO
	from @tabprecos
	where id = @min

	insert into PRODUTOS_PRECOS
			(CODIGO_TAB_PRECO, PRODUTO, PRECO1, PRECO2,PRECO3,PRECO4, ULT_ATUALIZACAO)  
	values 	(@CODIGO_TAB_PRECO,@PRODUTO, @preco_venda ,0,0,0, getdate())

	set @min = @min + 1
end

/*insert dos preços de custo - tabelas 00 (custo original) e 02 (transferencia)*/
insert into PRODUTOS_PRECOS
		(CODIGO_TAB_PRECO, PRODUTO, PRECO1, PRECO2,PRECO3,PRECO4, ULT_ATUALIZACAO)  
values 	('00',@PRODUTO, @preco_custo ,0,0,0, getdate()),
		('02',@PRODUTO, @preco_custo ,0,0,0, getdate()),
		('85',@PRODUTO, @preco_custo ,0,0,0, getdate())

--delete from produtos_precos where produto = '01050999'

select * from prop_produtos where produto = '01050999'

select propriedade, TITULO_PROPRIEDADE, DESC_PROPRIEDADE, TABELA 
from PROPRIEDADE 
where propriedade in ('00039','00098','00099','00100','00105','00107','00108','00114')

--DECLARE @produto char(12)
set @produto = '01050999'
insert into PROP_PRODUTOS (PROPRIEDADE, PRODUTO, ITEM_PROPRIEDADE, VALOR_PROPRIEDADE, DATA_PARA_TRANSFERENCIA)
					values  ('00039', @produto, 1, '2', getdate()),
							('00098',@produto,  1, 'CALCA - JEANS', getdate()),
							('00099',@produto,  1, '1/2 COXA', getdate()),
							('00100',@produto,  1, 'NÃO', getdate()),
							('00105',@produto,  1, 'P', getdate()),
							('00107',@produto,  1, 'P1/P2', getdate()),
							('00108',@produto,  1, 'NÃO', getdate()),
							('00114',@produto,  1, 'NÃO', getdate())
