/*
exec PDA_AP_SP_SE_PRODUTO_SORTIMENTO
 @FILIAL ='VILA FORMOSA',
 @COD_BARRA ='Z60900020023901',
 @USUARIO = 1,
 @TP_TECNOLOGIA ='',
 @IMEI  = ''

 select * from produtos_barra where produto = 'Z6090002'

 SELECT * FROM PRODUTOS_PRECOS WHERE PRODUTO = '47011309' AND CODIGO_TAB_PRECO='00' -- 28.14
 SELECT * FROM PRODUTOS_PRECOS WHERE PRODUTO = '47011309' AND CODIGO_TAB_PRECO='44' -- 28.14

 SELECT * FROM FILIAIS WHERE COD_FILIAL = '000057'

 select * from produtos WHERE PRODUTO = 'J4010013'

 47011309 - komport
 Z6090002 - sp


*/



DECLARE @TAB_PRECO CHAR(2),
@PRECO_CONTABIL NUMERIC(9,2),
@PRECO_ORIGINAL NUMERIC(9,2),
@COD_LOJA VARCHAR(10) = '000057',
@TABELA_CUSTO INT = 00

IF @TABELA_CUSTO=85
BEGIN

	SELECT @TAB_PRECO=VALOR_ATUAL FROM PARAMETROS_LOJA WHERE PARAMETRO = 'CODIGO_TAB_PRECO' AND CODIGO_FILIAL = @COD_LOJA
	SELECT @PRECO_CONTABIL= PRODUTOS_PRECOS.PRECO1
	FROM PRODUTOS_PRECOS
	INNER JOIN TABELAS_PRECO ON TABELAS_PRECO.CODIGO_TAB_PRECO = PRODUTOS_PRECOS.CODIGO_TAB_PRECO
	INNER JOIN PRODUTOS_BARRA PB ON PRODUTOS_PRECOS.PRODUTO = PB.PRODUTO
	WHERE TABELAS_PRECO.STATUS <> 'I'
	AND PB.CODIGO_BARRA='Z60900020023901'
	AND PRODUTOS_PRECOS.CODIGO_TAB_PRECO ='85'

	SELECT @PRECO_ORIGINAL = PRODUTOS_PRECOS.PRECO1
	FROM PRODUTOS_PRECOS
	INNER JOIN TABELAS_PRECO ON TABELAS_PRECO.CODIGO_TAB_PRECO = PRODUTOS_PRECOS.CODIGO_TAB_PRECO
	INNER JOIN PRODUTOS_BARRA PB ON PRODUTOS_PRECOS.PRODUTO = PB.PRODUTO
	WHERE TABELAS_PRECO.STATUS <> 'I'
	AND PB.CODIGO_BARRA='Z60900020023901'
	AND PRODUTOS_PRECOS.CODIGO_TAB_PRECO =@TAB_PRECO

	SELECT @TABELA_CUSTO as TABELA_CUSTO,
	@TAB_PRECO 'TAB. PREÇO',
	@PRECO_CONTABIL 'PRECO CONTABIL',
	@PRECO_ORIGINAL 'PRECO ORIGINAL',
	(1-(@PRECO_CONTABIL/(@PRECO_ORIGINAL* (1-27.25/100))))*100 'MARGEM'
	END
ELSE
BEGIN
	SELECT @TAB_PRECO=VALOR_ATUAL FROM PARAMETROS_LOJA WHERE PARAMETRO = 'CODIGO_TAB_PRECO' AND CODIGO_FILIAL = @COD_LOJA
	SELECT	top 1
			@PRECO_CONTABIL=
			CASE
			WHEN
				A.TRIBUT_ORIGEM IN (0,2,3,4,5,7,8) 
					AND D.FILIAL IN ('CAJAMAR - CQ','CD CAJAMAR','CD CAJAMAR - ATACADO','CD CAMAJAR - ATACADO','LOJA VIRTUAL',
										'REJEITADO - CD CAJAMAR','REJEITADO - LOJA VIRTUAL','VENDA ATACADO','VENDA IMP 2021') 
			THEN
				(B.PRECO1) * (1 - 0.2125)
			WHEN
				A.TRIBUT_ORIGEM IN (0,2,3,4,5,7,8) AND D.FILIAL IN ('CD NAVEGANTES','NAVEGANTES CQ','VENDA ATACADO SC','CD BARRA VELHA') 
			THEN
				(B.PRECO1) * (1 - 0.2625)
			WHEN
				A.TRIBUT_ORIGEM IN (1,6)
			THEN
				(B.PRECO1) * (1 - 0.1325)
			ELSE 0
		END 
	FROM
		produtos A
	INNER JOIN
		PRODUTOS_PRECOS B
	ON
		B.PRODUTO = A.PRODUTO AND B.CODIGO_TAB_PRECO = '00'
	INNER JOIN
		ESTOQUE_PROD1_ENT C
	ON
		C.PRODUTO = A.PRODUTO
	INNER JOIN
		ESTOQUE_PROD_ENT D
	ON
		D.ROMANEIO_PRODUTO = C.ROMANEIO_PRODUTO AND D.FILIAL = C.FILIAL
	WHERE
		A.PRODUTO = (select top 1 produto from produtos_barra where CODIGO_BARRA = 'Z60900020023901') 
		AND ISNULL(D.NF_ENTRADA,'')<>''  AND ISNULL(D.PEDIDO,'')<>''
	ORDER BY EMISSAO DESC

	SELECT @PRECO_ORIGINAL = PRODUTOS_PRECOS.PRECO1
	FROM PRODUTOS_PRECOS
	INNER JOIN TABELAS_PRECO ON TABELAS_PRECO.CODIGO_TAB_PRECO = PRODUTOS_PRECOS.CODIGO_TAB_PRECO
	INNER JOIN PRODUTOS_BARRA PB ON PRODUTOS_PRECOS.PRODUTO = PB.PRODUTO
	WHERE TABELAS_PRECO.STATUS <> 'I'
	AND PB.CODIGO_BARRA='Z60900020023901'
	AND PRODUTOS_PRECOS.CODIGO_TAB_PRECO =@TAB_PRECO

	SELECT @TABELA_CUSTO as TABELA_CUSTO,
	@TAB_PRECO 'TAB. PREÇO',
	@PRECO_CONTABIL 'PRECO CONTABIL',
	@PRECO_ORIGINAL 'PRECO ORIGINAL',
	(1-(@PRECO_CONTABIL/(@PRECO_ORIGINAL* (1-27.25/100))))*100 'MARGEM'
	

END


