USE [CAEDU]
GO

/****** Object:  View [dbo].[W_VENDAS_AMARRACAO_PRODUCAO]    Script Date: 20/06/2023 14:19:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE OR ALTER VIEW [dbo].[W_VENDAS_AMARRACAO_PRODUCAO]
AS
-- 25/11/2013 - Rodrigo Souza - TP 4674242 - #2# - Alterado o comando INNER para LEFT JOIN pois não retornava as cores que já foram finalizadas.
-- 05/09/2012 - SZALONTAI - RETIRADA DO LINK COM ROMANEIOS_PRODUTO QUANDO O TIPO= 2 E TIPO=3 PARA ATENDER A TP 2851449
--                          #1#
-- RAFAEL - 14/08/2012 - ALTERACAO DO NUMERO DE DIGITOS DA NOTA PARA 15 E SERIE PARA 3
-- 13/03/2012 - SZALONTAI - ADIÇÃO DO LINK "AND (ROMANEIOS_RESERVAS.COR_PRODUTO = PRODUCAO_TAREFAS_SALDO.COR_PRODUTO OR PRODUCAO_TAREFAS_SALDO.COR_PRODUTO=PRODUTO_CORES.COR_PRODUTO)"  
--
-- 08/12/2010 - SZALONTAI - ADIÇÃO DO LEFT JOIN NOS JOIN´S ENTRE A TABELA DE FATURAMENTO_PROD COM AS TABELAS DE PRODUCAO PARA OP´S NÃO ENCERRADAS NO TIPO '03'.
--                          PARA ATENDER A TP 1377764.
--
-- 21/07/2009 - SZALONTAI - RETIRADA DO LINK "AND (ROMANEIOS_RESERVAS.COR_PRODUTO = PRODUCAO_TAREFAS_SALDO.COR_PRODUTO OR PRODUCAO_TAREFAS_SALDO.COR_PRODUTO=PRODUTO_CORES.COR_PRODUTO)"  
--							NOS SELECT ONDE O TIPO = "01", PARA TRAZER A CORES DIFERENTES DA VENDA E DA OP, QUANDO TEM LAVAGEM
--
-- 03/07/2009 - SZALONTAI - ADIÇÃO DO SELECT NA TABELA DE ESTOQUE VINCULADO À VENDA, VIA VENDAS_PROD_EMBALADO
--                          COLOCADO COMO TIPO '05' - ESTOQUE RESERVADO
--
-- 06/06/2006 - SZALONTAI - TROCA DA FUNCAO CHAR(2) AS SERIE_NF POR SERIE_NF = SPACE(2)
--                          TROCA ONDE HAVIA PRODUTO_CORES.COR POR PRODUTO_CORES.COR_PRODUTO
--
-- 01/02/2006 - SZALONTAI - TROCA DOS CAMPO VE1..VE48 POR R1..R48 QUANDO O TIPO É '04' - ENCOMENDA
--                          ESTA TROCA SE DEVE AO FATO DAS COLUNAS DE VENDAS NAO MOSTRAR RESERVAS PARCIAIS
-- 27/06/2005 - SZALONTAI - ADICIONADO CAMPO SERIE_NF PARA SELECIONAR A FATURA CORRETA.
-- 27/06/2005 - SZALONTAI - HAVIA A NECESSIDADE DE CONSULTAR NAS OPS ENCERRADAS A POSICAO DOS PEDIDOS. POR ISSO FOI 
--                          ADICIONADO SELECTS COM LEFT JOIN EM PRODUCAO_TAREFAS_SALDO PARA TRAZER DADOS DAS VENDAS
--                          QUANDO A OP ESTIVER ENCERRADA. COLOCADO TAMBEM CLAUSULA PRODUCAO_ORDEM.STATUS ='E' PARA 
--                          ESTES SELECT E CLAUSULA PRODUCAO_ORDEM.STATUS <>'E' PARA OS SELECT COM INNER JOIN COM 
--                          PRODUCAO_TAREFAS_SALDO.
--
-- 29/03/2005 - SERGIO - INCLUSÃO DA TABELA VENDAS_PRODUTO NOS CAMPOS VE1 A VE48
--
-- 21/02/2005 - SZALONTAI - TROCADO O CAMPO ROMANEIO DOS CAMPOS DOCUMENTO POR PEDIDO
--
-- 02/02/2005 - SZALONTAI - RETIRADO LEFT JOIN DO LINK COM A TABELA ROMANEIOS_RESERVA PARA O TIPO '04'
--
-- 12/11/2004 - SZALONTAI - ADICIONADO O CAMPO ROMANEIOS_RESERVAS.ROMANEIO AS ROMANEIO NO TIPO 04
--
-- 05/11/2004 - SZALONTAI - ADICIONADO FILTRO NO TIPO 01, PARA TRAZER SO AS OP´S SEM PEDIDOS
--

SELECT   
DISTINCT '01' AS TIPO, ROMANEIOS_RESERVAS.PEDIDO AS DOCUMENTO,ROMANEIOS_RESERVAS.ROMANEIO, ROMANEIOS_RESERVAS.PEDIDO, ROMANEIOS_RESERVAS.FILIAL, ROMANEIOS_RESERVAS.PRODUTO,  
ROMANEIOS_RESERVAS.COR_PEDIDO, ROMANEIOS_RESERVAS.ENTREGA, ROMANEIOS_RESERVAS.QTDE_R, ROMANEIOS_RESERVAS.ORDEM_PRODUCAO,  
ROMANEIOS_RESERVAS.INDICA_ADEQUADO,   
R1, R2, R3, R4, R5, R6, R7, R8, R9, R10, R11, R12,   
R13, R14, R15, R16, R17, R18, R19, R20, R21, R22, R23, R24,   
R25, R26, R27, R28, R29, R30, R31, R32, R33, R34, R35, R36,   
R37, R38, R39, R40, R41, R42, R43, R44, R45, R46, R47, R48,  
ROMANEIOS_RESERVAS.COR_PRODUTO, PRODUTOS.GRADE, PRODUCAO_ORDEM.EMISSAO, PRODUCAO_ORDEM.INICIO_LIBERADO, PRODUCAO_ORDEM.INICIO_PREVISTO,    
PRODUCAO_ORDEM.INICIO_REAL, PRODUCAO_ORDEM.PREVISAO_FIM,  PRODUCAO_ORDEM.PREVISAO_FIM_NA_EMISSAO, PRODUCAO_ORDEM.ENCERRAMENTO,    
PRODUCAO_ORDEM.QTDE_TOTAL, PRODUCAO_ORDEM.QTDE_EM_PRODUCAO,  PRODUCAO_ORDEM.ORDEM_CORTE,   
PRODUCAO_TAREFAS_SALDO.QTDE_S,   
PRODUCAO_TAREFAS_SALDO.S1,  PRODUCAO_TAREFAS_SALDO.S2, PRODUCAO_TAREFAS_SALDO.S3,  PRODUCAO_TAREFAS_SALDO.S4, PRODUCAO_TAREFAS_SALDO.S5,  PRODUCAO_TAREFAS_SALDO.S6,   
PRODUCAO_TAREFAS_SALDO.S7,  PRODUCAO_TAREFAS_SALDO.S8, PRODUCAO_TAREFAS_SALDO.S9,  PRODUCAO_TAREFAS_SALDO.S10, PRODUCAO_TAREFAS_SALDO.S11,  PRODUCAO_TAREFAS_SALDO.S12,   
PRODUCAO_TAREFAS_SALDO.S13,  PRODUCAO_TAREFAS_SALDO.S14, PRODUCAO_TAREFAS_SALDO.S15,  PRODUCAO_TAREFAS_SALDO.S16, PRODUCAO_TAREFAS_SALDO.S17,  PRODUCAO_TAREFAS_SALDO.S18,   
PRODUCAO_TAREFAS_SALDO.S19,  PRODUCAO_TAREFAS_SALDO.S20, PRODUCAO_TAREFAS_SALDO.S21,  PRODUCAO_TAREFAS_SALDO.S22, PRODUCAO_TAREFAS_SALDO.S23,  PRODUCAO_TAREFAS_SALDO.S24,   
PRODUCAO_TAREFAS_SALDO.S25,  PRODUCAO_TAREFAS_SALDO.S26, PRODUCAO_TAREFAS_SALDO.S27,  PRODUCAO_TAREFAS_SALDO.S28, PRODUCAO_TAREFAS_SALDO.S29,  PRODUCAO_TAREFAS_SALDO.S30,   
PRODUCAO_TAREFAS_SALDO.S31,  PRODUCAO_TAREFAS_SALDO.S32, PRODUCAO_TAREFAS_SALDO.S33,  PRODUCAO_TAREFAS_SALDO.S34, PRODUCAO_TAREFAS_SALDO.S35,  PRODUCAO_TAREFAS_SALDO.S36,   
PRODUCAO_TAREFAS_SALDO.S37,  PRODUCAO_TAREFAS_SALDO.S38, PRODUCAO_TAREFAS_SALDO.S39,  PRODUCAO_TAREFAS_SALDO.S40, PRODUCAO_TAREFAS_SALDO.S41,  PRODUCAO_TAREFAS_SALDO.S42,   
PRODUCAO_TAREFAS_SALDO.S43,  PRODUCAO_TAREFAS_SALDO.S44, PRODUCAO_TAREFAS_SALDO.S45,  PRODUCAO_TAREFAS_SALDO.S46, PRODUCAO_TAREFAS_SALDO.S47,  PRODUCAO_TAREFAS_SALDO.S48,    
PRODUCAO_TAREFAS_SALDO.ULTIMO_CUSTO_PREVISTO,    
PRODUCAO_TAREFAS.TAREFA , PRODUCAO_TAREFAS.SEQUENCIA_PRODUTIVA,  PRODUCAO_TAREFAS.SETOR_PARALELO_NUMERO,    
PRODUCAO_TAREFAS.FASE_PRODUCAO, PRODUCAO_TAREFAS.SETOR_PRODUCAO,  PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,    
PRODUCAO_TAREFAS.INICIO_LIBERADO AS INICIO_LIBERADO_TAREFA,   
PRODUCAO_TAREFAS.INICIO_PREVISTO AS INICIO_PREVISTO_TAREFA,    
PRODUCAO_TAREFAS.INICIO_REAL AS INICIO_REAL_TAREFA,   
PRODUCAO_TAREFAS.FIM_PREVISTO,    
PRODUCAO_TAREFAS.FIM_ATUALIZADO,   
PRODUCAO_TAREFAS.ENCERRAMENTO AS ENCERRAMENTO_TAREFA,    
PRODUCAO_TAREFAS.QTDE_PREVISTA,    
PRODUCAO_TAREFAS.QTDE_A_PRODUZIR,   
PRODUCAO_TAREFAS.QTDE_EM_PROCESSO,    
PRODUCAO_TAREFAS.QTDE_FINALIZADA,   
PRODUCAO_TAREFAS.QTDE_ALTERACAO_OP,    
PRODUCAO_TAREFAS.QTDE_PERDAS,  PRODUCAO_TAREFAS.QTDE_ALT_OUTRAS_TAREFAS,  PRODUCAO_TAREFAS.CUSTO_TAREFA, PRODUCAO_TAREFAS.DESCONTOS_TAREFA,    
PRODUCAO_TAREFAS.VALOR_TAREFA, PRODUCAO_TAREFAS.STATUS,  PRODUCAO_TAREFAS.TEMPO_OPERACAO, PRODUCAO_TAREFAS.UNIDADE_TEMPO,    
PRODUCAO_TAREFAS.SEQUENCIA_ANTERIOR,  PRODUCAO_FASE.DESC_FASE_PRODUCAO, PRODUCAO_RECURSOS.DESC_RECURSO,  PRODUCAO_SETOR.DESC_SETOR_PRODUCAO,   
MATA_SALDO, ITEM_PEDIDO,   
PRODUCAO_ORDEM.PROGRAMACAO,   
CAIXA = SPACE(8),TEMPO_CRONOMETRADO,TEMPO_CRONOM_FIXO,SERIE_NF = SPACE(3) 
FROM ROMANEIOS_RESERVAS   
JOIN ROMANEIOS_PRODUTO ON ROMANEIOS_RESERVAS.ROMANEIO = ROMANEIOS_PRODUTO.ROMANEIO AND   
     ROMANEIOS_RESERVAS.FILIAL = ROMANEIOS_PRODUTO.FILIAL AND 
     ROMANEIOS_RESERVAS.PRODUTO = ROMANEIOS_PRODUTO.PRODUTO AND   
     ROMANEIOS_RESERVAS.COR_PRODUTO = ROMANEIOS_PRODUTO.COR_PRODUTO  
JOIN PRODUTOS ON ROMANEIOS_RESERVAS.PRODUTO = PRODUTOS.PRODUTO  
JOIN PRODUTO_CORES ON  ROMANEIOS_RESERVAS.PRODUTO = PRODUTO_CORES.PRODUTO AND   
      ROMANEIOS_RESERVAS.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO  
JOIN PRODUCAO_ORDEM ON ROMANEIOS_RESERVAS.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO  
JOIN PRODUCAO_TAREFAS_SALDO ON  ROMANEIOS_RESERVAS.ORDEM_PRODUCAO = PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO AND   
        ROMANEIOS_RESERVAS.PRODUTO = PRODUCAO_TAREFAS_SALDO.PRODUTO 
-----------------------------------------------------------------------------------------------------
-- ALTERAÇÃO FEITA EM 21/07/2009 PARA TRAZER A CORES DIFERENTES DA VENDA E DA OP, QUANDO TEM LAVAGEM
--
AND           (ROMANEIOS_RESERVAS.COR_PRODUTO = PRODUCAO_TAREFAS_SALDO.COR_PRODUTO OR PRODUCAO_TAREFAS_SALDO.COR_PRODUTO=PRODUTO_CORES.COR_PRODUTO)  
--
-- FIM DA ALTERAÇÃO
-----------------------------------------------------------------------------------------------------

JOIN PRODUCAO_TAREFAS ON PRODUCAO_TAREFAS_SALDO.TAREFA = PRODUCAO_TAREFAS.TAREFA  
JOIN PRODUCAO_SETOR ON  PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND   
      PRODUCAO_TAREFAS.SETOR_PRODUCAO = PRODUCAO_SETOR.SETOR_PRODUCAO  
JOIN PRODUCAO_RECURSOS ON PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO  
JOIN PRODUCAO_FASE ON PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_FASE.FASE_PRODUCAO  
WHERE ISNULL(LTRIM(RTRIM(PRODUCAO_ORDEM.PEDIDO)),'')=''  AND ROMANEIOS_RESERVAS.QTDE_R>0  AND PRODUCAO_ORDEM.STATUS <> 'E'
--JOIN VENDAS ON ROMANEIOS_RESERVAS.PEDIDO = VENDAS.PEDIDO  
    
UNION ALL  

SELECT   
DISTINCT '01' AS TIPO, ROMANEIOS_RESERVAS.PEDIDO AS DOCUMENTO,ROMANEIOS_RESERVAS.ROMANEIO, ROMANEIOS_RESERVAS.PEDIDO, ROMANEIOS_RESERVAS.FILIAL, ROMANEIOS_RESERVAS.PRODUTO,  
ROMANEIOS_RESERVAS.COR_PEDIDO, ROMANEIOS_RESERVAS.ENTREGA, ROMANEIOS_RESERVAS.QTDE_R, ROMANEIOS_RESERVAS.ORDEM_PRODUCAO,  
ROMANEIOS_RESERVAS.INDICA_ADEQUADO,   
R1, R2, R3, R4, R5, R6, R7, R8, R9, R10, R11, R12,   
R13, R14, R15, R16, R17, R18, R19, R20, R21, R22, R23, R24,   
R25, R26, R27, R28, R29, R30, R31, R32, R33, R34, R35, R36,   
R37, R38, R39, R40, R41, R42, R43, R44, R45, R46, R47, R48,  
ROMANEIOS_RESERVAS.COR_PRODUTO, PRODUTOS.GRADE, PRODUCAO_ORDEM.EMISSAO, PRODUCAO_ORDEM.INICIO_LIBERADO, PRODUCAO_ORDEM.INICIO_PREVISTO,    
PRODUCAO_ORDEM.INICIO_REAL, PRODUCAO_ORDEM.PREVISAO_FIM,  PRODUCAO_ORDEM.PREVISAO_FIM_NA_EMISSAO, PRODUCAO_ORDEM.ENCERRAMENTO,    
PRODUCAO_ORDEM.QTDE_TOTAL, PRODUCAO_ORDEM.QTDE_EM_PRODUCAO,  PRODUCAO_ORDEM.ORDEM_CORTE,   
PRODUCAO_TAREFAS_SALDO.QTDE_S,   
PRODUCAO_TAREFAS_SALDO.S1,  PRODUCAO_TAREFAS_SALDO.S2, PRODUCAO_TAREFAS_SALDO.S3,  PRODUCAO_TAREFAS_SALDO.S4, PRODUCAO_TAREFAS_SALDO.S5,  PRODUCAO_TAREFAS_SALDO.S6,   
PRODUCAO_TAREFAS_SALDO.S7,  PRODUCAO_TAREFAS_SALDO.S8, PRODUCAO_TAREFAS_SALDO.S9,  PRODUCAO_TAREFAS_SALDO.S10, PRODUCAO_TAREFAS_SALDO.S11,  PRODUCAO_TAREFAS_SALDO.S12,   
PRODUCAO_TAREFAS_SALDO.S13,  PRODUCAO_TAREFAS_SALDO.S14, PRODUCAO_TAREFAS_SALDO.S15,  PRODUCAO_TAREFAS_SALDO.S16, PRODUCAO_TAREFAS_SALDO.S17,  PRODUCAO_TAREFAS_SALDO.S18,   
PRODUCAO_TAREFAS_SALDO.S19,  PRODUCAO_TAREFAS_SALDO.S20, PRODUCAO_TAREFAS_SALDO.S21,  PRODUCAO_TAREFAS_SALDO.S22, PRODUCAO_TAREFAS_SALDO.S23,  PRODUCAO_TAREFAS_SALDO.S24,   
PRODUCAO_TAREFAS_SALDO.S25,  PRODUCAO_TAREFAS_SALDO.S26, PRODUCAO_TAREFAS_SALDO.S27,  PRODUCAO_TAREFAS_SALDO.S28, PRODUCAO_TAREFAS_SALDO.S29,  PRODUCAO_TAREFAS_SALDO.S30,   
PRODUCAO_TAREFAS_SALDO.S31,  PRODUCAO_TAREFAS_SALDO.S32, PRODUCAO_TAREFAS_SALDO.S33,  PRODUCAO_TAREFAS_SALDO.S34, PRODUCAO_TAREFAS_SALDO.S35,  PRODUCAO_TAREFAS_SALDO.S36,   
PRODUCAO_TAREFAS_SALDO.S37,  PRODUCAO_TAREFAS_SALDO.S38, PRODUCAO_TAREFAS_SALDO.S39,  PRODUCAO_TAREFAS_SALDO.S40, PRODUCAO_TAREFAS_SALDO.S41,  PRODUCAO_TAREFAS_SALDO.S42,   
PRODUCAO_TAREFAS_SALDO.S43,  PRODUCAO_TAREFAS_SALDO.S44, PRODUCAO_TAREFAS_SALDO.S45,  PRODUCAO_TAREFAS_SALDO.S46, PRODUCAO_TAREFAS_SALDO.S47,  PRODUCAO_TAREFAS_SALDO.S48,    
PRODUCAO_TAREFAS_SALDO.ULTIMO_CUSTO_PREVISTO,    
PRODUCAO_TAREFAS.TAREFA , PRODUCAO_TAREFAS.SEQUENCIA_PRODUTIVA,  PRODUCAO_TAREFAS.SETOR_PARALELO_NUMERO,    
PRODUCAO_TAREFAS.FASE_PRODUCAO, PRODUCAO_TAREFAS.SETOR_PRODUCAO,  PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,    
PRODUCAO_TAREFAS.INICIO_LIBERADO AS INICIO_LIBERADO_TAREFA,   
PRODUCAO_TAREFAS.INICIO_PREVISTO AS INICIO_PREVISTO_TAREFA,    
PRODUCAO_TAREFAS.INICIO_REAL AS INICIO_REAL_TAREFA,   
PRODUCAO_TAREFAS.FIM_PREVISTO,    
PRODUCAO_TAREFAS.FIM_ATUALIZADO,   
PRODUCAO_TAREFAS.ENCERRAMENTO AS ENCERRAMENTO_TAREFA,    
PRODUCAO_TAREFAS.QTDE_PREVISTA,    
PRODUCAO_TAREFAS.QTDE_A_PRODUZIR,   
PRODUCAO_TAREFAS.QTDE_EM_PROCESSO,    
PRODUCAO_TAREFAS.QTDE_FINALIZADA,   
PRODUCAO_TAREFAS.QTDE_ALTERACAO_OP,    
PRODUCAO_TAREFAS.QTDE_PERDAS,  PRODUCAO_TAREFAS.QTDE_ALT_OUTRAS_TAREFAS,  PRODUCAO_TAREFAS.CUSTO_TAREFA, PRODUCAO_TAREFAS.DESCONTOS_TAREFA,    
PRODUCAO_TAREFAS.VALOR_TAREFA, PRODUCAO_TAREFAS.STATUS,  PRODUCAO_TAREFAS.TEMPO_OPERACAO, PRODUCAO_TAREFAS.UNIDADE_TEMPO,    
PRODUCAO_TAREFAS.SEQUENCIA_ANTERIOR,  PRODUCAO_FASE.DESC_FASE_PRODUCAO, PRODUCAO_RECURSOS.DESC_RECURSO,  PRODUCAO_SETOR.DESC_SETOR_PRODUCAO,   
MATA_SALDO, ITEM_PEDIDO,   
PRODUCAO_ORDEM.PROGRAMACAO,   
CAIXA = SPACE(8),TEMPO_CRONOMETRADO,TEMPO_CRONOM_FIXO,SERIE_NF = SPACE(3) 
FROM ROMANEIOS_RESERVAS   
JOIN ROMANEIOS_PRODUTO ON ROMANEIOS_RESERVAS.ROMANEIO = ROMANEIOS_PRODUTO.ROMANEIO AND   
     ROMANEIOS_RESERVAS.FILIAL = ROMANEIOS_PRODUTO.FILIAL AND 
     ROMANEIOS_RESERVAS.PRODUTO = ROMANEIOS_PRODUTO.PRODUTO AND   
     ROMANEIOS_RESERVAS.COR_PRODUTO = ROMANEIOS_PRODUTO.COR_PRODUTO  
JOIN PRODUTOS ON ROMANEIOS_RESERVAS.PRODUTO = PRODUTOS.PRODUTO  
JOIN PRODUTO_CORES ON  ROMANEIOS_RESERVAS.PRODUTO = PRODUTO_CORES.PRODUTO AND   
      ROMANEIOS_RESERVAS.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO  
JOIN PRODUCAO_ORDEM ON ROMANEIOS_RESERVAS.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO  
LEFT JOIN PRODUCAO_TAREFAS_SALDO ON  ROMANEIOS_RESERVAS.ORDEM_PRODUCAO = PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO AND   
        ROMANEIOS_RESERVAS.PRODUTO = PRODUCAO_TAREFAS_SALDO.PRODUTO 
-----------------------------------------------------------------------------------------------------
-- ALTERAÇÃO FEITA EM 21/07/2009 PARA TRAZER A CORES DIFERENTES DA VENDA E DA OP, QUANDO TEM LAVAGEM
--
AND           (ROMANEIOS_RESERVAS.COR_PRODUTO = PRODUCAO_TAREFAS_SALDO.COR_PRODUTO OR PRODUCAO_TAREFAS_SALDO.COR_PRODUTO=PRODUTO_CORES.COR_PRODUTO)  
-- FIM DA ALTERAÇÃO
-----------------------------------------------------------------------------------------------------
LEFT JOIN PRODUCAO_TAREFAS ON PRODUCAO_TAREFAS_SALDO.TAREFA = PRODUCAO_TAREFAS.TAREFA  
LEFT JOIN PRODUCAO_SETOR ON  PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND   
      PRODUCAO_TAREFAS.SETOR_PRODUCAO = PRODUCAO_SETOR.SETOR_PRODUCAO  
LEFT JOIN PRODUCAO_RECURSOS ON PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO  
LEFT JOIN PRODUCAO_FASE ON PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_FASE.FASE_PRODUCAO  
WHERE ISNULL(LTRIM(RTRIM(PRODUCAO_ORDEM.PEDIDO)),'')='' AND ROMANEIOS_RESERVAS.QTDE_R>0   AND PRODUCAO_ORDEM.STATUS = 'E'
--JOIN VENDAS ON ROMANEIOS_RESERVAS.PEDIDO = VENDAS.PEDIDO  
    
UNION ALL  
  
SELECT DISTINCT '02' AS TIPO, VENDAS_PROD_EMBALADO.PEDIDO AS DOCUMENTO,  
VENDAS_PROD_EMBALADO.ROMANEIO, VENDAS_PROD_EMBALADO.PEDIDO, VENDAS_PROD_EMBALADO.FILIAL, VENDAS_PROD_EMBALADO.PRODUTO,  
VENDAS_PROD_EMBALADO.PEDIDO_COR_PRODUTO AS COR_PEDIDO, vendas_prod_embalado.ENTREGA, QTDE_EMBALADA AS QTDE_R, VENDAS_PROD_EMBALADO.ORDEM_PRODUCAO,  
1 AS INDICA_ADEQUADO,   
E1 AS R1, E2 AS R2, E3 AS R3, E4 AS R4, E5 AS R5, E6 AS R6, E7 AS R7, E8 AS R8,   
E9 AS R9, E10 AS R10, E11 AS R11, E12 AS R12, E13 AS R13, E14 AS R14, E15 AS R15, E16 AS R16,   
E17 AS R17, E18 AS R18, E19 AS R19, E20 AS R20, E21 AS R21, E22 AS R22, E23 AS R23, E24 AS R24,   
E25 AS R25, E26 AS R26, E27 AS R27, E28 AS R28, E29 AS R29, E30 AS R30, E31 AS R31, E32 AS R32,   
E33 AS R33, E34 AS R34, E35 AS R35, E36 AS R36, E37 AS R37, E38 AS R38, E39 AS R39, E40 AS R40,   
E41 AS R41, E42 AS R42, E43 AS R43, E44 AS R44, E45 AS R45, E46 AS R46, E47 AS R47, E48 AS R48,  
VENDAS_PROD_EMBALADO.COR_PRODUTO, PRODUTOS.GRADE, PRODUCAO_ORDEM.EMISSAO, PRODUCAO_ORDEM.INICIO_LIBERADO, PRODUCAO_ORDEM.INICIO_PREVISTO,    
PRODUCAO_ORDEM.INICIO_REAL, PRODUCAO_ORDEM.PREVISAO_FIM,  PRODUCAO_ORDEM.PREVISAO_FIM_NA_EMISSAO, PRODUCAO_ORDEM.ENCERRAMENTO,    
PRODUCAO_ORDEM.QTDE_TOTAL, PRODUCAO_ORDEM.QTDE_EM_PRODUCAO,  PRODUCAO_ORDEM.ORDEM_CORTE,    
PRODUCAO_TAREFAS_SALDO.QTDE_S, PRODUCAO_TAREFAS_SALDO.S1,  PRODUCAO_TAREFAS_SALDO.S2, PRODUCAO_TAREFAS_SALDO.S3,  PRODUCAO_TAREFAS_SALDO.S4,   
PRODUCAO_TAREFAS_SALDO.S5,  PRODUCAO_TAREFAS_SALDO.S6, PRODUCAO_TAREFAS_SALDO.S7,  PRODUCAO_TAREFAS_SALDO.S8,   
PRODUCAO_TAREFAS_SALDO.S9,  PRODUCAO_TAREFAS_SALDO.S10, PRODUCAO_TAREFAS_SALDO.S11,  PRODUCAO_TAREFAS_SALDO.S12,   
PRODUCAO_TAREFAS_SALDO.S13,  PRODUCAO_TAREFAS_SALDO.S14, PRODUCAO_TAREFAS_SALDO.S15,  PRODUCAO_TAREFAS_SALDO.S16,   
PRODUCAO_TAREFAS_SALDO.S17,  PRODUCAO_TAREFAS_SALDO.S18, PRODUCAO_TAREFAS_SALDO.S19,  PRODUCAO_TAREFAS_SALDO.S20,   
PRODUCAO_TAREFAS_SALDO.S21,  PRODUCAO_TAREFAS_SALDO.S22, PRODUCAO_TAREFAS_SALDO.S23,  PRODUCAO_TAREFAS_SALDO.S24,   
PRODUCAO_TAREFAS_SALDO.S25,  PRODUCAO_TAREFAS_SALDO.S26, PRODUCAO_TAREFAS_SALDO.S27,  PRODUCAO_TAREFAS_SALDO.S28,   
PRODUCAO_TAREFAS_SALDO.S29,  PRODUCAO_TAREFAS_SALDO.S30, PRODUCAO_TAREFAS_SALDO.S31,  PRODUCAO_TAREFAS_SALDO.S32,   
PRODUCAO_TAREFAS_SALDO.S33,  PRODUCAO_TAREFAS_SALDO.S34, PRODUCAO_TAREFAS_SALDO.S35,  PRODUCAO_TAREFAS_SALDO.S36,   
PRODUCAO_TAREFAS_SALDO.S37,  PRODUCAO_TAREFAS_SALDO.S38, PRODUCAO_TAREFAS_SALDO.S39,  PRODUCAO_TAREFAS_SALDO.S40,   
PRODUCAO_TAREFAS_SALDO.S41,  PRODUCAO_TAREFAS_SALDO.S42, PRODUCAO_TAREFAS_SALDO.S43,  PRODUCAO_TAREFAS_SALDO.S44,   
PRODUCAO_TAREFAS_SALDO.S45,  PRODUCAO_TAREFAS_SALDO.S46, PRODUCAO_TAREFAS_SALDO.S47,  PRODUCAO_TAREFAS_SALDO.S48,    
PRODUCAO_TAREFAS_SALDO.ULTIMO_CUSTO_PREVISTO,  PRODUCAO_TAREFAS.TAREFA , PRODUCAO_TAREFAS.SEQUENCIA_PRODUTIVA,  PRODUCAO_TAREFAS.SETOR_PARALELO_NUMERO,    
PRODUCAO_TAREFAS.FASE_PRODUCAO, PRODUCAO_TAREFAS.SETOR_PRODUCAO,  PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,  
PRODUCAO_TAREFAS.INICIO_LIBERADO AS INICIO_LIBERADO_TAREFA,   
PRODUCAO_TAREFAS.INICIO_PREVISTO AS INICIO_PREVISTO_TAREFA,    
PRODUCAO_TAREFAS.INICIO_REAL AS INICIO_REAL_TAREFA,   
PRODUCAO_TAREFAS.FIM_PREVISTO,    
PRODUCAO_TAREFAS.FIM_ATUALIZADO,   
PRODUCAO_TAREFAS.ENCERRAMENTO AS ENCERRAMENTO_TAREFA,    
PRODUCAO_TAREFAS.QTDE_PREVISTA,    
PRODUCAO_TAREFAS.QTDE_A_PRODUZIR,   
PRODUCAO_TAREFAS.QTDE_EM_PROCESSO,    
PRODUCAO_TAREFAS.QTDE_FINALIZADA,   
PRODUCAO_TAREFAS.QTDE_ALTERACAO_OP,    
PRODUCAO_TAREFAS.QTDE_PERDAS,  PRODUCAO_TAREFAS.QTDE_ALT_OUTRAS_TAREFAS,  PRODUCAO_TAREFAS.CUSTO_TAREFA, PRODUCAO_TAREFAS.DESCONTOS_TAREFA,    
PRODUCAO_TAREFAS.VALOR_TAREFA, PRODUCAO_TAREFAS.STATUS,  PRODUCAO_TAREFAS.TEMPO_OPERACAO, PRODUCAO_TAREFAS.UNIDADE_TEMPO,    
PRODUCAO_TAREFAS.SEQUENCIA_ANTERIOR,  PRODUCAO_FASE.DESC_FASE_PRODUCAO, PRODUCAO_RECURSOS.DESC_RECURSO,  PRODUCAO_SETOR.DESC_SETOR_PRODUCAO,   
MATA_SALDO, ITEM_PEDIDO , PRODUCAO_ORDEM.PROGRAMACAO,VENDAS_PROD_EMBALADO.CAIXA,TEMPO_CRONOMETRADO,TEMPO_CRONOM_FIXO   ,SERIE_NF=SPACE(3)
  
FROM VENDAS_PROD_EMBALADO   
/*#1#
JOIN ROMANEIOS_PRODUTO ON VENDAS_PROD_EMBALADO.ROMANEIO = ROMANEIOS_PRODUTO.ROMANEIO AND   
     VENDAS_PROD_EMBALADO.FILIAL = ROMANEIOS_PRODUTO.FILIAL AND   
     VENDAS_PROD_EMBALADO.PRODUTO = ROMANEIOS_PRODUTO.PRODUTO AND   
     VENDAS_PROD_EMBALADO.COR_PRODUTO = ROMANEIOS_PRODUTO.COR_PRODUTO
*/       
JOIN PRODUTOS ON VENDAS_PROD_EMBALADO.PRODUTO = PRODUTOS.PRODUTO  
JOIN PRODUTO_CORES ON VENDAS_PROD_EMBALADO.PRODUTO = PRODUTO_CORES.PRODUTO AND   
      VENDAS_PROD_EMBALADO.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO  
  
JOIN PRODUCAO_ORDEM ON VENDAS_PROD_EMBALADO.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO  
LEFT JOIN PRODUCAO_TAREFAS_SALDO ON  VENDAS_PROD_EMBALADO.ORDEM_PRODUCAO = PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO AND   --#2#
        VENDAS_PROD_EMBALADO.PRODUTO = PRODUCAO_TAREFAS_SALDO.PRODUTO AND   --#2#
        VENDAS_PROD_EMBALADO.COR_PRODUTO = PRODUCAO_TAREFAS_SALDO.COR_PRODUTO  --#2#
LEFT JOIN PRODUCAO_TAREFAS ON PRODUCAO_TAREFAS_SALDO.TAREFA = PRODUCAO_TAREFAS.TAREFA  --#2#
LEFT JOIN PRODUCAO_SETOR ON PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND PRODUCAO_TAREFAS.SETOR_PRODUCAO = PRODUCAO_SETOR.SETOR_PRODUCAO  --#2#
LEFT JOIN PRODUCAO_RECURSOS ON PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO  --#2#
LEFT JOIN PRODUCAO_FASE ON PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_FASE.FASE_PRODUCAO  --#2#
WHERE PRODUCAO_ORDEM.STATUS <> 'E' AND QTDE_EMBALADA>0 
--JOIN VENDAS ON VENDAS_PROD_EMBALADO.PEDIDO = VENDAS.PEDIDO  
  
UNION ALL  

SELECT DISTINCT '02' AS TIPO, VENDAS_PROD_EMBALADO.PEDIDO AS DOCUMENTO,  
VENDAS_PROD_EMBALADO.ROMANEIO, VENDAS_PROD_EMBALADO.PEDIDO, VENDAS_PROD_EMBALADO.FILIAL, VENDAS_PROD_EMBALADO.PRODUTO,  
VENDAS_PROD_EMBALADO.PEDIDO_COR_PRODUTO AS COR_PEDIDO, VENDAS_PROD_EMBALADO.ENTREGA, QTDE_EMBALADA AS QTDE_R, VENDAS_PROD_EMBALADO.ORDEM_PRODUCAO,  
1 AS INDICA_ADEQUADO,   
E1 AS R1, E2 AS R2, E3 AS R3, E4 AS R4, E5 AS R5, E6 AS R6, E7 AS R7, E8 AS R8,   
E9 AS R9, E10 AS R10, E11 AS R11, E12 AS R12, E13 AS R13, E14 AS R14, E15 AS R15, E16 AS R16,   
E17 AS R17, E18 AS R18, E19 AS R19, E20 AS R20, E21 AS R21, E22 AS R22, E23 AS R23, E24 AS R24,   
E25 AS R25, E26 AS R26, E27 AS R27, E28 AS R28, E29 AS R29, E30 AS R30, E31 AS R31, E32 AS R32,   
E33 AS R33, E34 AS R34, E35 AS R35, E36 AS R36, E37 AS R37, E38 AS R38, E39 AS R39, E40 AS R40,   
E41 AS R41, E42 AS R42, E43 AS R43, E44 AS R44, E45 AS R45, E46 AS R46, E47 AS R47, E48 AS R48,  
VENDAS_PROD_EMBALADO.COR_PRODUTO, PRODUTOS.GRADE, PRODUCAO_ORDEM.EMISSAO, PRODUCAO_ORDEM.INICIO_LIBERADO, PRODUCAO_ORDEM.INICIO_PREVISTO,    
PRODUCAO_ORDEM.INICIO_REAL, PRODUCAO_ORDEM.PREVISAO_FIM,  PRODUCAO_ORDEM.PREVISAO_FIM_NA_EMISSAO, PRODUCAO_ORDEM.ENCERRAMENTO,    
PRODUCAO_ORDEM.QTDE_TOTAL, PRODUCAO_ORDEM.QTDE_EM_PRODUCAO,  PRODUCAO_ORDEM.ORDEM_CORTE,    
PRODUCAO_TAREFAS_SALDO.QTDE_S, PRODUCAO_TAREFAS_SALDO.S1,  PRODUCAO_TAREFAS_SALDO.S2, PRODUCAO_TAREFAS_SALDO.S3,  PRODUCAO_TAREFAS_SALDO.S4,   
PRODUCAO_TAREFAS_SALDO.S5,  PRODUCAO_TAREFAS_SALDO.S6, PRODUCAO_TAREFAS_SALDO.S7,  PRODUCAO_TAREFAS_SALDO.S8,   
PRODUCAO_TAREFAS_SALDO.S9,  PRODUCAO_TAREFAS_SALDO.S10, PRODUCAO_TAREFAS_SALDO.S11,  PRODUCAO_TAREFAS_SALDO.S12,   
PRODUCAO_TAREFAS_SALDO.S13,  PRODUCAO_TAREFAS_SALDO.S14, PRODUCAO_TAREFAS_SALDO.S15,  PRODUCAO_TAREFAS_SALDO.S16,   
PRODUCAO_TAREFAS_SALDO.S17,  PRODUCAO_TAREFAS_SALDO.S18, PRODUCAO_TAREFAS_SALDO.S19,  PRODUCAO_TAREFAS_SALDO.S20,   
PRODUCAO_TAREFAS_SALDO.S21,  PRODUCAO_TAREFAS_SALDO.S22, PRODUCAO_TAREFAS_SALDO.S23,  PRODUCAO_TAREFAS_SALDO.S24,   
PRODUCAO_TAREFAS_SALDO.S25,  PRODUCAO_TAREFAS_SALDO.S26, PRODUCAO_TAREFAS_SALDO.S27,  PRODUCAO_TAREFAS_SALDO.S28,   
PRODUCAO_TAREFAS_SALDO.S29,  PRODUCAO_TAREFAS_SALDO.S30, PRODUCAO_TAREFAS_SALDO.S31,  PRODUCAO_TAREFAS_SALDO.S32,   
PRODUCAO_TAREFAS_SALDO.S33,  PRODUCAO_TAREFAS_SALDO.S34, PRODUCAO_TAREFAS_SALDO.S35,  PRODUCAO_TAREFAS_SALDO.S36,   
PRODUCAO_TAREFAS_SALDO.S37,  PRODUCAO_TAREFAS_SALDO.S38, PRODUCAO_TAREFAS_SALDO.S39,  PRODUCAO_TAREFAS_SALDO.S40,   
PRODUCAO_TAREFAS_SALDO.S41,  PRODUCAO_TAREFAS_SALDO.S42, PRODUCAO_TAREFAS_SALDO.S43,  PRODUCAO_TAREFAS_SALDO.S44,   
PRODUCAO_TAREFAS_SALDO.S45,  PRODUCAO_TAREFAS_SALDO.S46, PRODUCAO_TAREFAS_SALDO.S47,  PRODUCAO_TAREFAS_SALDO.S48,    
PRODUCAO_TAREFAS_SALDO.ULTIMO_CUSTO_PREVISTO,  PRODUCAO_TAREFAS.TAREFA , PRODUCAO_TAREFAS.SEQUENCIA_PRODUTIVA,  PRODUCAO_TAREFAS.SETOR_PARALELO_NUMERO,    
PRODUCAO_TAREFAS.FASE_PRODUCAO, PRODUCAO_TAREFAS.SETOR_PRODUCAO,  PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,  
PRODUCAO_TAREFAS.INICIO_LIBERADO AS INICIO_LIBERADO_TAREFA,   
PRODUCAO_TAREFAS.INICIO_PREVISTO AS INICIO_PREVISTO_TAREFA,    
PRODUCAO_TAREFAS.INICIO_REAL AS INICIO_REAL_TAREFA,   
PRODUCAO_TAREFAS.FIM_PREVISTO,    
PRODUCAO_TAREFAS.FIM_ATUALIZADO,   
PRODUCAO_TAREFAS.ENCERRAMENTO AS ENCERRAMENTO_TAREFA,    
PRODUCAO_TAREFAS.QTDE_PREVISTA,    
PRODUCAO_TAREFAS.QTDE_A_PRODUZIR,   
PRODUCAO_TAREFAS.QTDE_EM_PROCESSO,    
PRODUCAO_TAREFAS.QTDE_FINALIZADA,   
PRODUCAO_TAREFAS.QTDE_ALTERACAO_OP,    
PRODUCAO_TAREFAS.QTDE_PERDAS,  PRODUCAO_TAREFAS.QTDE_ALT_OUTRAS_TAREFAS,  PRODUCAO_TAREFAS.CUSTO_TAREFA, PRODUCAO_TAREFAS.DESCONTOS_TAREFA,    
PRODUCAO_TAREFAS.VALOR_TAREFA, PRODUCAO_TAREFAS.STATUS,  PRODUCAO_TAREFAS.TEMPO_OPERACAO, PRODUCAO_TAREFAS.UNIDADE_TEMPO,    
PRODUCAO_TAREFAS.SEQUENCIA_ANTERIOR,  PRODUCAO_FASE.DESC_FASE_PRODUCAO, PRODUCAO_RECURSOS.DESC_RECURSO,  PRODUCAO_SETOR.DESC_SETOR_PRODUCAO,   
MATA_SALDO, ITEM_PEDIDO , PRODUCAO_ORDEM.PROGRAMACAO,VENDAS_PROD_EMBALADO.CAIXA,TEMPO_CRONOMETRADO,TEMPO_CRONOM_FIXO   ,SERIE_NF=SPACE(3)
  
FROM VENDAS_PROD_EMBALADO   
/*#1#
JOIN ROMANEIOS_PRODUTO ON VENDAS_PROD_EMBALADO.ROMANEIO = ROMANEIOS_PRODUTO.ROMANEIO AND   
     VENDAS_PROD_EMBALADO.FILIAL = ROMANEIOS_PRODUTO.FILIAL AND   
     VENDAS_PROD_EMBALADO.PRODUTO = ROMANEIOS_PRODUTO.PRODUTO AND   
     VENDAS_PROD_EMBALADO.COR_PRODUTO = ROMANEIOS_PRODUTO.COR_PRODUTO  
*/
JOIN PRODUTOS ON VENDAS_PROD_EMBALADO.PRODUTO = PRODUTOS.PRODUTO  
JOIN PRODUTO_CORES ON VENDAS_PROD_EMBALADO.PRODUTO = PRODUTO_CORES.PRODUTO AND   
      VENDAS_PROD_EMBALADO.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO  
  
JOIN PRODUCAO_ORDEM ON VENDAS_PROD_EMBALADO.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO  
LEFT JOIN PRODUCAO_TAREFAS_SALDO ON  VENDAS_PROD_EMBALADO.ORDEM_PRODUCAO = PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO AND   
        VENDAS_PROD_EMBALADO.PRODUTO = PRODUCAO_TAREFAS_SALDO.PRODUTO AND   
        VENDAS_PROD_EMBALADO.COR_PRODUTO = PRODUCAO_TAREFAS_SALDO.COR_PRODUTO  
  
LEFT JOIN PRODUCAO_TAREFAS ON PRODUCAO_TAREFAS_SALDO.TAREFA = PRODUCAO_TAREFAS.TAREFA  
LEFT JOIN PRODUCAO_SETOR ON PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND PRODUCAO_TAREFAS.SETOR_PRODUCAO = PRODUCAO_SETOR.SETOR_PRODUCAO  
LEFT JOIN PRODUCAO_RECURSOS ON PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO  
LEFT JOIN PRODUCAO_FASE ON PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_FASE.FASE_PRODUCAO  
WHERE PRODUCAO_ORDEM.STATUS = 'E' AND QTDE_EMBALADA>0 
--JOIN VENDAS ON VENDAS_PROD_EMBALADO.PEDIDO = VENDAS.PEDIDO  
  
UNION ALL  
  
SELECT DISTINCT '03' AS TIPO,NF_SAIDA AS DOCUMENTO,  
FATURAMENTO_PROD.ROMANEIO, FATURAMENTO_PROD.PEDIDO, FATURAMENTO_PROD.FILIAL, FATURAMENTO_PROD.PRODUTO,  
FATURAMENTO_PROD.PEDIDO_COR AS COR_PEDIDO, faturamento_prod.ENTREGA, QTDE AS QTDE_R, FATURAMENTO_PROD.ORDEM_PRODUCAO,1 AS INDICA_ADEQUADO,   
F1 AS R1, F2 AS R2, F3 AS R3, F4 AS R4, F5 AS R5, F6 AS R6, F7 AS R7, F8 AS R8,   
F9 AS R9, F10 AS R10, F11 AS R11, F12 AS R12, F13 AS R13, F14 AS R14, F15 AS R15, F16 AS R16,   
F17 AS R17, F18 AS R18, F19 AS R19, F20 AS R20, F21 AS R21, F22 AS R22, F23 AS R23, F24 AS R24,   
F25 AS R25, F26 AS R16, F27 AS R27, F28 AS R28, F29 AS R29, F30 AS R30, F31 AS R31, F32 AS R32,   
F33 AS R33, F34 AS R34, F35 AS R35, F36 AS R36, F37 AS R37, F38 AS R38, F39 AS R39, F40 AS F40,   
F41 AS R41, F42 AS R42, F43 AS R43, F44 AS R44, F45 AS R45, F46 AS R46, F47  AS R47, F48 AS R48,  
FATURAMENTO_PROD.COR_PRODUTO, PRODUTOS.GRADE, PRODUCAO_ORDEM.EMISSAO, PRODUCAO_ORDEM.INICIO_LIBERADO, PRODUCAO_ORDEM.INICIO_PREVISTO,    
PRODUCAO_ORDEM.INICIO_REAL, PRODUCAO_ORDEM.PREVISAO_FIM,  PRODUCAO_ORDEM.PREVISAO_FIM_NA_EMISSAO, PRODUCAO_ORDEM.ENCERRAMENTO,    
PRODUCAO_ORDEM.QTDE_TOTAL, PRODUCAO_ORDEM.QTDE_EM_PRODUCAO,  PRODUCAO_ORDEM.ORDEM_CORTE,   
PRODUCAO_TAREFAS_SALDO.QTDE_S,   
PRODUCAO_TAREFAS_SALDO.S1,  PRODUCAO_TAREFAS_SALDO.S2, PRODUCAO_TAREFAS_SALDO.S3,  PRODUCAO_TAREFAS_SALDO.S4,   
PRODUCAO_TAREFAS_SALDO.S5,  PRODUCAO_TAREFAS_SALDO.S6, PRODUCAO_TAREFAS_SALDO.S7,  PRODUCAO_TAREFAS_SALDO.S8,   
PRODUCAO_TAREFAS_SALDO.S9,  PRODUCAO_TAREFAS_SALDO.S10, PRODUCAO_TAREFAS_SALDO.S11,  PRODUCAO_TAREFAS_SALDO.S12,   
PRODUCAO_TAREFAS_SALDO.S13,  PRODUCAO_TAREFAS_SALDO.S14, PRODUCAO_TAREFAS_SALDO.S15,  PRODUCAO_TAREFAS_SALDO.S16,   
PRODUCAO_TAREFAS_SALDO.S17,  PRODUCAO_TAREFAS_SALDO.S18, PRODUCAO_TAREFAS_SALDO.S19,  PRODUCAO_TAREFAS_SALDO.S20,   
PRODUCAO_TAREFAS_SALDO.S21,  PRODUCAO_TAREFAS_SALDO.S22, PRODUCAO_TAREFAS_SALDO.S23,  PRODUCAO_TAREFAS_SALDO.S24,   
PRODUCAO_TAREFAS_SALDO.S25,  PRODUCAO_TAREFAS_SALDO.S26, PRODUCAO_TAREFAS_SALDO.S27,  PRODUCAO_TAREFAS_SALDO.S28,   
PRODUCAO_TAREFAS_SALDO.S29,  PRODUCAO_TAREFAS_SALDO.S30, PRODUCAO_TAREFAS_SALDO.S31,  PRODUCAO_TAREFAS_SALDO.S32,   
PRODUCAO_TAREFAS_SALDO.S33,  PRODUCAO_TAREFAS_SALDO.S34, PRODUCAO_TAREFAS_SALDO.S35,  PRODUCAO_TAREFAS_SALDO.S36,   
PRODUCAO_TAREFAS_SALDO.S37,  PRODUCAO_TAREFAS_SALDO.S38, PRODUCAO_TAREFAS_SALDO.S39,  PRODUCAO_TAREFAS_SALDO.S40,   
PRODUCAO_TAREFAS_SALDO.S41,  PRODUCAO_TAREFAS_SALDO.S42, PRODUCAO_TAREFAS_SALDO.S43,  PRODUCAO_TAREFAS_SALDO.S44,   
PRODUCAO_TAREFAS_SALDO.S45,  PRODUCAO_TAREFAS_SALDO.S46, PRODUCAO_TAREFAS_SALDO.S47,  PRODUCAO_TAREFAS_SALDO.S48,    
PRODUCAO_TAREFAS_SALDO.ULTIMO_CUSTO_PREVISTO,  PRODUCAO_TAREFAS.TAREFA , PRODUCAO_TAREFAS.SEQUENCIA_PRODUTIVA,  PRODUCAO_TAREFAS.SETOR_PARALELO_NUMERO,    
PRODUCAO_TAREFAS.FASE_PRODUCAO, PRODUCAO_TAREFAS.SETOR_PRODUCAO, PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,    
PRODUCAO_TAREFAS.INICIO_LIBERADO AS INICIO_LIBERADO_TAREFA,   
PRODUCAO_TAREFAS.INICIO_PREVISTO AS INICIO_PREVISTO_TAREFA,    
PRODUCAO_TAREFAS.INICIO_REAL AS INICIO_REAL_TAREFA,   
PRODUCAO_TAREFAS.FIM_PREVISTO,    
PRODUCAO_TAREFAS.FIM_ATUALIZADO,   
PRODUCAO_TAREFAS.ENCERRAMENTO AS ENCERRAMENTO_TAREFA,    
PRODUCAO_TAREFAS.QTDE_PREVISTA,    
PRODUCAO_TAREFAS.QTDE_A_PRODUZIR,   
PRODUCAO_TAREFAS.QTDE_EM_PROCESSO,    
PRODUCAO_TAREFAS.QTDE_FINALIZADA,   
PRODUCAO_TAREFAS.QTDE_ALTERACAO_OP,    
PRODUCAO_TAREFAS.QTDE_PERDAS,  PRODUCAO_TAREFAS.QTDE_ALT_OUTRAS_TAREFAS,  PRODUCAO_TAREFAS.CUSTO_TAREFA, PRODUCAO_TAREFAS.DESCONTOS_TAREFA,    
PRODUCAO_TAREFAS.VALOR_TAREFA, PRODUCAO_TAREFAS.STATUS,  PRODUCAO_TAREFAS.TEMPO_OPERACAO, PRODUCAO_TAREFAS.UNIDADE_TEMPO,    
PRODUCAO_TAREFAS.SEQUENCIA_ANTERIOR,  PRODUCAO_FASE.DESC_FASE_PRODUCAO, PRODUCAO_RECURSOS.DESC_RECURSO,  PRODUCAO_SETOR.DESC_SETOR_PRODUCAO,   
MATA_SALDO, ITEM_PEDIDO , PRODUCAO_ORDEM.PROGRAMACAO, CAIXA = SPACE(8),TEMPO_CRONOMETRADO,TEMPO_CRONOM_FIXO   ,SERIE_NF
FROM FATURAMENTO_PROD   
JOIN FILIAIS ON FILIAIS.COD_FILIAL = FATURAMENTO_PROD.COD_FILIAL_ESTOQUE
/*#1#
JOIN ROMANEIOS_PRODUTO ON FATURAMENTO_PROD.ROMANEIO = ROMANEIOS_PRODUTO.ROMANEIO AND   
     FILIAIS.FILIAL = ROMANEIOS_PRODUTO.FILIAL AND   
     FATURAMENTO_PROD.PRODUTO = ROMANEIOS_PRODUTO.PRODUTO AND   
     FATURAMENTO_PROD.COR_PRODUTO = ROMANEIOS_PRODUTO.COR_PRODUTO  
*/
JOIN PRODUTOS ON FATURAMENTO_PROD.PRODUTO = PRODUTOS.PRODUTO  
JOIN PRODUTO_CORES ON FATURAMENTO_PROD.PRODUTO = PRODUTO_CORES.PRODUTO AND   
      FATURAMENTO_PROD.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO  
JOIN PRODUCAO_ORDEM ON FATURAMENTO_PROD.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO  
LEFT JOIN PRODUCAO_TAREFAS_SALDO ON  FATURAMENTO_PROD.ORDEM_PRODUCAO = PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO AND   
        FATURAMENTO_PROD.PRODUTO = PRODUCAO_TAREFAS_SALDO.PRODUTO AND   
        FATURAMENTO_PROD.COR_PRODUTO = PRODUCAO_TAREFAS_SALDO.COR_PRODUTO  
LEFT JOIN PRODUCAO_TAREFAS ON PRODUCAO_TAREFAS_SALDO.TAREFA = PRODUCAO_TAREFAS.TAREFA  
LEFT JOIN PRODUCAO_SETOR ON PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND PRODUCAO_TAREFAS.SETOR_PRODUCAO = PRODUCAO_SETOR.SETOR_PRODUCAO  
LEFT JOIN PRODUCAO_RECURSOS ON PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO  
LEFT JOIN PRODUCAO_FASE ON PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_FASE.FASE_PRODUCAO  
--JOIN VENDAS ON FATURAMENTO_PROD.PEDIDO = VENDAS.PEDIDO  
WHERE PRODUCAO_ORDEM.STATUS <> 'E'  AND QTDE>0 

UNION ALL   

SELECT DISTINCT '03' AS TIPO,NF_SAIDA AS DOCUMENTO,  
FATURAMENTO_PROD.ROMANEIO, FATURAMENTO_PROD.PEDIDO, FATURAMENTO_PROD.FILIAL, FATURAMENTO_PROD.PRODUTO,  
FATURAMENTO_PROD.PEDIDO_COR AS COR_PEDIDO, faturamento_prod.ENTREGA, QTDE AS QTDE_R, FATURAMENTO_PROD.ORDEM_PRODUCAO,1 AS INDICA_ADEQUADO,   
F1 AS R1, F2 AS R2, F3 AS R3, F4 AS R4, F5 AS R5, F6 AS R6, F7 AS R7, F8 AS R8,   
F9 AS R9, F10 AS R10, F11 AS R11, F12 AS R12, F13 AS R13, F14 AS R14, F15 AS R15, F16 AS R16,   
F17 AS R17, F18 AS R18, F19 AS R19, F20 AS R20, F21 AS R21, F22 AS R22, F23 AS R23, F24 AS R24,   
F25 AS R25, F26 AS R16, F27 AS R27, F28 AS R28, F29 AS R29, F30 AS R30, F31 AS R31, F32 AS R32,   
F33 AS R33, F34 AS R34, F35 AS R35, F36 AS R36, F37 AS R37, F38 AS R38, F39 AS R39, F40 AS F40,   
F41 AS R41, F42 AS R42, F43 AS R43, F44 AS R44, F45 AS R45, F46 AS R46, F47  AS R47, F48 AS R48,  
FATURAMENTO_PROD.COR_PRODUTO, PRODUTOS.GRADE, PRODUCAO_ORDEM.EMISSAO, PRODUCAO_ORDEM.INICIO_LIBERADO, PRODUCAO_ORDEM.INICIO_PREVISTO,    
PRODUCAO_ORDEM.INICIO_REAL, PRODUCAO_ORDEM.PREVISAO_FIM,  PRODUCAO_ORDEM.PREVISAO_FIM_NA_EMISSAO, PRODUCAO_ORDEM.ENCERRAMENTO,    
PRODUCAO_ORDEM.QTDE_TOTAL, PRODUCAO_ORDEM.QTDE_EM_PRODUCAO,  PRODUCAO_ORDEM.ORDEM_CORTE,   
PRODUCAO_TAREFAS_SALDO.QTDE_S,   
PRODUCAO_TAREFAS_SALDO.S1,  PRODUCAO_TAREFAS_SALDO.S2, PRODUCAO_TAREFAS_SALDO.S3,  PRODUCAO_TAREFAS_SALDO.S4,   
PRODUCAO_TAREFAS_SALDO.S5,  PRODUCAO_TAREFAS_SALDO.S6, PRODUCAO_TAREFAS_SALDO.S7,  PRODUCAO_TAREFAS_SALDO.S8,   
PRODUCAO_TAREFAS_SALDO.S9,  PRODUCAO_TAREFAS_SALDO.S10, PRODUCAO_TAREFAS_SALDO.S11,  PRODUCAO_TAREFAS_SALDO.S12,   
PRODUCAO_TAREFAS_SALDO.S13,  PRODUCAO_TAREFAS_SALDO.S14, PRODUCAO_TAREFAS_SALDO.S15,  PRODUCAO_TAREFAS_SALDO.S16,   
PRODUCAO_TAREFAS_SALDO.S17,  PRODUCAO_TAREFAS_SALDO.S18, PRODUCAO_TAREFAS_SALDO.S19,  PRODUCAO_TAREFAS_SALDO.S20,   
PRODUCAO_TAREFAS_SALDO.S21,  PRODUCAO_TAREFAS_SALDO.S22, PRODUCAO_TAREFAS_SALDO.S23,  PRODUCAO_TAREFAS_SALDO.S24,   
PRODUCAO_TAREFAS_SALDO.S25,  PRODUCAO_TAREFAS_SALDO.S26, PRODUCAO_TAREFAS_SALDO.S27,  PRODUCAO_TAREFAS_SALDO.S28,   
PRODUCAO_TAREFAS_SALDO.S29,  PRODUCAO_TAREFAS_SALDO.S30, PRODUCAO_TAREFAS_SALDO.S31,  PRODUCAO_TAREFAS_SALDO.S32,   
PRODUCAO_TAREFAS_SALDO.S33,  PRODUCAO_TAREFAS_SALDO.S34, PRODUCAO_TAREFAS_SALDO.S35,  PRODUCAO_TAREFAS_SALDO.S36,   
PRODUCAO_TAREFAS_SALDO.S37,  PRODUCAO_TAREFAS_SALDO.S38, PRODUCAO_TAREFAS_SALDO.S39,  PRODUCAO_TAREFAS_SALDO.S40,   
PRODUCAO_TAREFAS_SALDO.S41,  PRODUCAO_TAREFAS_SALDO.S42, PRODUCAO_TAREFAS_SALDO.S43,  PRODUCAO_TAREFAS_SALDO.S44,   
PRODUCAO_TAREFAS_SALDO.S45,  PRODUCAO_TAREFAS_SALDO.S46, PRODUCAO_TAREFAS_SALDO.S47,  PRODUCAO_TAREFAS_SALDO.S48,    
PRODUCAO_TAREFAS_SALDO.ULTIMO_CUSTO_PREVISTO,  PRODUCAO_TAREFAS.TAREFA , PRODUCAO_TAREFAS.SEQUENCIA_PRODUTIVA,  PRODUCAO_TAREFAS.SETOR_PARALELO_NUMERO,    
PRODUCAO_TAREFAS.FASE_PRODUCAO, PRODUCAO_TAREFAS.SETOR_PRODUCAO, PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,    
PRODUCAO_TAREFAS.INICIO_LIBERADO AS INICIO_LIBERADO_TAREFA,   
PRODUCAO_TAREFAS.INICIO_PREVISTO AS INICIO_PREVISTO_TAREFA,    
PRODUCAO_TAREFAS.INICIO_REAL AS INICIO_REAL_TAREFA,   
PRODUCAO_TAREFAS.FIM_PREVISTO,    
PRODUCAO_TAREFAS.FIM_ATUALIZADO,   
PRODUCAO_TAREFAS.ENCERRAMENTO AS ENCERRAMENTO_TAREFA,    
PRODUCAO_TAREFAS.QTDE_PREVISTA,    
PRODUCAO_TAREFAS.QTDE_A_PRODUZIR,   
PRODUCAO_TAREFAS.QTDE_EM_PROCESSO,    
PRODUCAO_TAREFAS.QTDE_FINALIZADA,   
PRODUCAO_TAREFAS.QTDE_ALTERACAO_OP,    
PRODUCAO_TAREFAS.QTDE_PERDAS,  PRODUCAO_TAREFAS.QTDE_ALT_OUTRAS_TAREFAS,  PRODUCAO_TAREFAS.CUSTO_TAREFA, PRODUCAO_TAREFAS.DESCONTOS_TAREFA,    
PRODUCAO_TAREFAS.VALOR_TAREFA, PRODUCAO_TAREFAS.STATUS,  PRODUCAO_TAREFAS.TEMPO_OPERACAO, PRODUCAO_TAREFAS.UNIDADE_TEMPO,    
PRODUCAO_TAREFAS.SEQUENCIA_ANTERIOR,  PRODUCAO_FASE.DESC_FASE_PRODUCAO, PRODUCAO_RECURSOS.DESC_RECURSO,  PRODUCAO_SETOR.DESC_SETOR_PRODUCAO,   
MATA_SALDO, ITEM_PEDIDO , PRODUCAO_ORDEM.PROGRAMACAO, CAIXA = SPACE(8),TEMPO_CRONOMETRADO,TEMPO_CRONOM_FIXO   ,SERIE_NF
FROM FATURAMENTO_PROD   
JOIN FILIAIS ON FILIAIS.COD_FILIAL = FATURAMENTO_PROD.COD_FILIAL_ESTOQUE
/*#1#
JOIN ROMANEIOS_PRODUTO ON FATURAMENTO_PROD.ROMANEIO = ROMANEIOS_PRODUTO.ROMANEIO AND   
     FILIAIS.FILIAL = ROMANEIOS_PRODUTO.FILIAL AND   
     FATURAMENTO_PROD.PRODUTO = ROMANEIOS_PRODUTO.PRODUTO AND   
     FATURAMENTO_PROD.COR_PRODUTO = ROMANEIOS_PRODUTO.COR_PRODUTO  
*/
JOIN PRODUTOS ON FATURAMENTO_PROD.PRODUTO = PRODUTOS.PRODUTO  
JOIN PRODUTO_CORES ON FATURAMENTO_PROD.PRODUTO = PRODUTO_CORES.PRODUTO AND   
      FATURAMENTO_PROD.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO  
JOIN PRODUCAO_ORDEM ON FATURAMENTO_PROD.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO  
LEFT JOIN PRODUCAO_TAREFAS_SALDO ON  FATURAMENTO_PROD.ORDEM_PRODUCAO = PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO AND   
        FATURAMENTO_PROD.PRODUTO = PRODUCAO_TAREFAS_SALDO.PRODUTO AND   
        FATURAMENTO_PROD.COR_PRODUTO = PRODUCAO_TAREFAS_SALDO.COR_PRODUTO  
LEFT JOIN PRODUCAO_TAREFAS ON PRODUCAO_TAREFAS_SALDO.TAREFA = PRODUCAO_TAREFAS.TAREFA  
LEFT JOIN PRODUCAO_SETOR ON PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND PRODUCAO_TAREFAS.SETOR_PRODUCAO = PRODUCAO_SETOR.SETOR_PRODUCAO  
LEFT JOIN PRODUCAO_RECURSOS ON PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO  
LEFT JOIN PRODUCAO_FASE ON PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_FASE.FASE_PRODUCAO  
--JOIN VENDAS ON FATURAMENTO_PROD.PEDIDO = VENDAS.PEDIDO  
WHERE  PRODUCAO_ORDEM.STATUS = 'E'  AND QTDE>0 

UNION ALL   
    
SELECT DISTINCT '04' AS TIPO, VENDAS_PRODUTO.PEDIDO ,ROMANEIOS_RESERVAS.ROMANEIO AS ROMANEIO,   
VENDAS_PRODUTO.PEDIDO,   
VENDAS.FILIAL,   
VENDAS_PRODUTO.PRODUTO,  
VENDAS_PRODUTO.COR_PRODUTO,   
VENDAS_PRODUTO.ENTREGA,   
ROMANEIOS_RESERVAS.QTDE_R,
PRODUCAO_ORDEM.ORDEM_PRODUCAO,  
0 AS INDICA_ADEQUADO,   
R1, R2, R3, R4, R5, R6, R7, R8, R9, R10, R11, R12,   
R13, R14, R15, R16, R17, R18, R19, R20, R21, R22, R23, R24,   
R25, R26, R27, R28, R29, R30, R31, R32, R33, R34, R35, R36,   
R37, R38, R39, R40, R41, R42, R43, R44, R45, R46, R47, R48,  
VENDAS_PRODUTO.COR_PRODUTO,   
PRODUTOS.GRADE,   
PRODUCAO_ORDEM.EMISSAO,   
PRODUCAO_ORDEM.INICIO_LIBERADO,   
PRODUCAO_ORDEM.INICIO_PREVISTO,    
PRODUCAO_ORDEM.INICIO_REAL,   
PRODUCAO_ORDEM.PREVISAO_FIM,    
PRODUCAO_ORDEM.PREVISAO_FIM_NA_EMISSAO, PRODUCAO_ORDEM.ENCERRAMENTO,    
PRODUCAO_ORDEM.QTDE_TOTAL, PRODUCAO_ORDEM.QTDE_EM_PRODUCAO,  PRODUCAO_ORDEM.ORDEM_CORTE,   
PRODUCAO_TAREFAS_SALDO.QTDE_S,   
PRODUCAO_TAREFAS_SALDO.S1,  PRODUCAO_TAREFAS_SALDO.S2, PRODUCAO_TAREFAS_SALDO.S3,  PRODUCAO_TAREFAS_SALDO.S4, PRODUCAO_TAREFAS_SALDO.S5,  PRODUCAO_TAREFAS_SALDO.S6,   
PRODUCAO_TAREFAS_SALDO.S7,  PRODUCAO_TAREFAS_SALDO.S8, PRODUCAO_TAREFAS_SALDO.S9,  PRODUCAO_TAREFAS_SALDO.S10, PRODUCAO_TAREFAS_SALDO.S11,  PRODUCAO_TAREFAS_SALDO.S12,   
PRODUCAO_TAREFAS_SALDO.S13,  PRODUCAO_TAREFAS_SALDO.S14, PRODUCAO_TAREFAS_SALDO.S15,  PRODUCAO_TAREFAS_SALDO.S16, PRODUCAO_TAREFAS_SALDO.S17,  PRODUCAO_TAREFAS_SALDO.S18,   
PRODUCAO_TAREFAS_SALDO.S19,  PRODUCAO_TAREFAS_SALDO.S20, PRODUCAO_TAREFAS_SALDO.S21,  PRODUCAO_TAREFAS_SALDO.S22, PRODUCAO_TAREFAS_SALDO.S23,  PRODUCAO_TAREFAS_SALDO.S24,   
PRODUCAO_TAREFAS_SALDO.S25,  PRODUCAO_TAREFAS_SALDO.S26, PRODUCAO_TAREFAS_SALDO.S27,  PRODUCAO_TAREFAS_SALDO.S28, PRODUCAO_TAREFAS_SALDO.S29,  PRODUCAO_TAREFAS_SALDO.S30,   
PRODUCAO_TAREFAS_SALDO.S31,  PRODUCAO_TAREFAS_SALDO.S32, PRODUCAO_TAREFAS_SALDO.S33,  PRODUCAO_TAREFAS_SALDO.S34, PRODUCAO_TAREFAS_SALDO.S35,  PRODUCAO_TAREFAS_SALDO.S36,   
PRODUCAO_TAREFAS_SALDO.S37,  PRODUCAO_TAREFAS_SALDO.S38, PRODUCAO_TAREFAS_SALDO.S39,  PRODUCAO_TAREFAS_SALDO.S40, PRODUCAO_TAREFAS_SALDO.S41,  PRODUCAO_TAREFAS_SALDO.S42,   
PRODUCAO_TAREFAS_SALDO.S43,  PRODUCAO_TAREFAS_SALDO.S44, PRODUCAO_TAREFAS_SALDO.S45,  PRODUCAO_TAREFAS_SALDO.S46, PRODUCAO_TAREFAS_SALDO.S47,  PRODUCAO_TAREFAS_SALDO.S48,    
PRODUCAO_TAREFAS_SALDO.ULTIMO_CUSTO_PREVISTO,    
PRODUCAO_TAREFAS.TAREFA , PRODUCAO_TAREFAS.SEQUENCIA_PRODUTIVA,  PRODUCAO_TAREFAS.SETOR_PARALELO_NUMERO,    
PRODUCAO_TAREFAS.FASE_PRODUCAO, PRODUCAO_TAREFAS.SETOR_PRODUCAO,  PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,    
PRODUCAO_TAREFAS.INICIO_LIBERADO AS INICIO_LIBERADO_TAREFA,   
PRODUCAO_TAREFAS.INICIO_PREVISTO AS INICIO_PREVISTO_TAREFA,    
PRODUCAO_TAREFAS.INICIO_REAL AS INICIO_REAL_TAREFA,   
PRODUCAO_TAREFAS.FIM_PREVISTO,    
PRODUCAO_TAREFAS.FIM_ATUALIZADO,   
PRODUCAO_TAREFAS.ENCERRAMENTO AS ENCERRAMENTO_TAREFA,    
PRODUCAO_TAREFAS.QTDE_PREVISTA,    
PRODUCAO_TAREFAS.QTDE_A_PRODUZIR,   
PRODUCAO_TAREFAS.QTDE_EM_PROCESSO,    
PRODUCAO_TAREFAS.QTDE_FINALIZADA,   
PRODUCAO_TAREFAS.QTDE_ALTERACAO_OP,    
PRODUCAO_TAREFAS.QTDE_PERDAS,  PRODUCAO_TAREFAS.QTDE_ALT_OUTRAS_TAREFAS,  PRODUCAO_TAREFAS.CUSTO_TAREFA, PRODUCAO_TAREFAS.DESCONTOS_TAREFA,    
PRODUCAO_TAREFAS.VALOR_TAREFA, PRODUCAO_TAREFAS.STATUS,  PRODUCAO_TAREFAS.TEMPO_OPERACAO, PRODUCAO_TAREFAS.UNIDADE_TEMPO,    
PRODUCAO_TAREFAS.SEQUENCIA_ANTERIOR,  PRODUCAO_FASE.DESC_FASE_PRODUCAO, PRODUCAO_RECURSOS.DESC_RECURSO,  PRODUCAO_SETOR.DESC_SETOR_PRODUCAO,   
0 AS MATA_SALDO, VENDAS_PRODUTO.ITEM_PEDIDO, PRODUCAO_ORDEM.PROGRAMACAO, CAIXA = SPACE(8),TEMPO_CRONOMETRADO,TEMPO_CRONOM_FIXO   ,SERIE_NF=SPACE(3)
FROM VENDAS_PRODUTO  
INNER JOIN VENDAS ON  VENDAS_PRODUTO.PEDIDO= VENDAS.PEDIDO  
INNER JOIN PRODUCAO_ORDEM ON  VENDAS_PRODUTO.PEDIDO= PRODUCAO_ORDEM.PEDIDO  
INNER JOIN PRODUTOS ON VENDAS_PRODUTO.PRODUTO = PRODUTOS.PRODUTO  
INNER JOIN PRODUTO_CORES ON  VENDAS_PRODUTO.PRODUTO = PRODUTO_CORES.PRODUTO AND   
      VENDAS_PRODUTO.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO  
  
INNER JOIN PRODUCAO_TAREFAS_SALDO ON  PRODUCAO_ORDEM.ORDEM_PRODUCAO = PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO AND   
         VENDAS_PRODUTO.PRODUTO = PRODUCAO_TAREFAS_SALDO.PRODUTO AND   
         VENDAS_PRODUTO.COR_PRODUTO = PRODUCAO_TAREFAS_SALDO.COR_PRODUTO  
  
INNER JOIN PRODUCAO_TAREFAS ON PRODUCAO_TAREFAS_SALDO.TAREFA = PRODUCAO_TAREFAS.TAREFA  
INNER JOIN PRODUCAO_SETOR ON  PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND   
        PRODUCAO_TAREFAS.SETOR_PRODUCAO = PRODUCAO_SETOR.SETOR_PRODUCAO  
INNER JOIN PRODUCAO_RECURSOS ON PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO  
INNER JOIN PRODUCAO_FASE ON PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_FASE.FASE_PRODUCAO  
INNER JOIN ROMANEIOS_RESERVAS ON ROMANEIOS_RESERVAS.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO  AND 
								ROMANEIOS_RESERVAS.PEDIDO = VENDAS_PRODUTO.PEDIDO AND 
								ROMANEIOS_RESERVAS.PRODUTO = VENDAS_PRODUTO.PRODUTO AND 
								ROMANEIOS_RESERVAS.COR_PRODUTO = VENDAS_PRODUTO.COR_PRODUTO AND 
								ROMANEIOS_RESERVAS.ENTREGA = VENDAS_PRODUTO.ENTREGA AND 
								ROMANEIOS_RESERVAS.ITEM_PEDIDO = VENDAS_PRODUTO.ITEM_PEDIDO 
WHERE PRODUCAO_ORDEM.STATUS <> 'E' AND QTDE_ENTREGAR>0 

UNION ALL   
    
SELECT DISTINCT '04' AS TIPO, VENDAS_PRODUTO.PEDIDO ,ROMANEIOS_RESERVAS.ROMANEIO AS ROMANEIO,   
VENDAS_PRODUTO.PEDIDO,   
VENDAS.FILIAL,   
VENDAS_PRODUTO.PRODUTO,  
VENDAS_PRODUTO.COR_PRODUTO,   
VENDAS_PRODUTO.ENTREGA,   
ROMANEIOS_RESERVAS.QTDE_R,
PRODUCAO_ORDEM.ORDEM_PRODUCAO,  
0 AS INDICA_ADEQUADO,   
R1, R2, R3, R4, R5, R6, R7, R8, R9, R10, R11, R12,   
R13, R14, R15, R16, R17, R18, R19, R20, R21, R22, R23, R24,   
R25, R26, R27, R28, R29, R30, R31, R32, R33, R34, R35, R36,   
R37, R38, R39, R40, R41, R42, R43, R44, R45, R46, R47, R48,  
VENDAS_PRODUTO.COR_PRODUTO,   
PRODUTOS.GRADE,   
PRODUCAO_ORDEM.EMISSAO,   
PRODUCAO_ORDEM.INICIO_LIBERADO,   
PRODUCAO_ORDEM.INICIO_PREVISTO,    
PRODUCAO_ORDEM.INICIO_REAL,   
PRODUCAO_ORDEM.PREVISAO_FIM,    
PRODUCAO_ORDEM.PREVISAO_FIM_NA_EMISSAO, PRODUCAO_ORDEM.ENCERRAMENTO,    
PRODUCAO_ORDEM.QTDE_TOTAL, PRODUCAO_ORDEM.QTDE_EM_PRODUCAO,  PRODUCAO_ORDEM.ORDEM_CORTE,   
PRODUCAO_TAREFAS_SALDO.QTDE_S,   
PRODUCAO_TAREFAS_SALDO.S1,  PRODUCAO_TAREFAS_SALDO.S2, PRODUCAO_TAREFAS_SALDO.S3,  PRODUCAO_TAREFAS_SALDO.S4, PRODUCAO_TAREFAS_SALDO.S5,  PRODUCAO_TAREFAS_SALDO.S6,   
PRODUCAO_TAREFAS_SALDO.S7,  PRODUCAO_TAREFAS_SALDO.S8, PRODUCAO_TAREFAS_SALDO.S9,  PRODUCAO_TAREFAS_SALDO.S10, PRODUCAO_TAREFAS_SALDO.S11,  PRODUCAO_TAREFAS_SALDO.S12,   
PRODUCAO_TAREFAS_SALDO.S13,  PRODUCAO_TAREFAS_SALDO.S14, PRODUCAO_TAREFAS_SALDO.S15,  PRODUCAO_TAREFAS_SALDO.S16, PRODUCAO_TAREFAS_SALDO.S17,  PRODUCAO_TAREFAS_SALDO.S18,   
PRODUCAO_TAREFAS_SALDO.S19,  PRODUCAO_TAREFAS_SALDO.S20, PRODUCAO_TAREFAS_SALDO.S21,  PRODUCAO_TAREFAS_SALDO.S22, PRODUCAO_TAREFAS_SALDO.S23,  PRODUCAO_TAREFAS_SALDO.S24,   
PRODUCAO_TAREFAS_SALDO.S25,  PRODUCAO_TAREFAS_SALDO.S26, PRODUCAO_TAREFAS_SALDO.S27,  PRODUCAO_TAREFAS_SALDO.S28, PRODUCAO_TAREFAS_SALDO.S29,  PRODUCAO_TAREFAS_SALDO.S30,   
PRODUCAO_TAREFAS_SALDO.S31,  PRODUCAO_TAREFAS_SALDO.S32, PRODUCAO_TAREFAS_SALDO.S33,  PRODUCAO_TAREFAS_SALDO.S34, PRODUCAO_TAREFAS_SALDO.S35,  PRODUCAO_TAREFAS_SALDO.S36,   
PRODUCAO_TAREFAS_SALDO.S37,  PRODUCAO_TAREFAS_SALDO.S38, PRODUCAO_TAREFAS_SALDO.S39,  PRODUCAO_TAREFAS_SALDO.S40, PRODUCAO_TAREFAS_SALDO.S41,  PRODUCAO_TAREFAS_SALDO.S42,   
PRODUCAO_TAREFAS_SALDO.S43,  PRODUCAO_TAREFAS_SALDO.S44, PRODUCAO_TAREFAS_SALDO.S45,  PRODUCAO_TAREFAS_SALDO.S46, PRODUCAO_TAREFAS_SALDO.S47,  PRODUCAO_TAREFAS_SALDO.S48,    
PRODUCAO_TAREFAS_SALDO.ULTIMO_CUSTO_PREVISTO,    
PRODUCAO_TAREFAS.TAREFA , PRODUCAO_TAREFAS.SEQUENCIA_PRODUTIVA,  PRODUCAO_TAREFAS.SETOR_PARALELO_NUMERO,    
PRODUCAO_TAREFAS.FASE_PRODUCAO, PRODUCAO_TAREFAS.SETOR_PRODUCAO,  PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,    
PRODUCAO_TAREFAS.INICIO_LIBERADO AS INICIO_LIBERADO_TAREFA,   
PRODUCAO_TAREFAS.INICIO_PREVISTO AS INICIO_PREVISTO_TAREFA,    
PRODUCAO_TAREFAS.INICIO_REAL AS INICIO_REAL_TAREFA,   
PRODUCAO_TAREFAS.FIM_PREVISTO,    
PRODUCAO_TAREFAS.FIM_ATUALIZADO,   
PRODUCAO_TAREFAS.ENCERRAMENTO AS ENCERRAMENTO_TAREFA,    
PRODUCAO_TAREFAS.QTDE_PREVISTA,    
PRODUCAO_TAREFAS.QTDE_A_PRODUZIR,   
PRODUCAO_TAREFAS.QTDE_EM_PROCESSO,    
PRODUCAO_TAREFAS.QTDE_FINALIZADA,   
PRODUCAO_TAREFAS.QTDE_ALTERACAO_OP,    
PRODUCAO_TAREFAS.QTDE_PERDAS,  PRODUCAO_TAREFAS.QTDE_ALT_OUTRAS_TAREFAS,  PRODUCAO_TAREFAS.CUSTO_TAREFA, PRODUCAO_TAREFAS.DESCONTOS_TAREFA,    
PRODUCAO_TAREFAS.VALOR_TAREFA, PRODUCAO_TAREFAS.STATUS,  PRODUCAO_TAREFAS.TEMPO_OPERACAO, PRODUCAO_TAREFAS.UNIDADE_TEMPO,    
PRODUCAO_TAREFAS.SEQUENCIA_ANTERIOR,  PRODUCAO_FASE.DESC_FASE_PRODUCAO, PRODUCAO_RECURSOS.DESC_RECURSO,  PRODUCAO_SETOR.DESC_SETOR_PRODUCAO,   
0 AS MATA_SALDO, VENDAS_PRODUTO.ITEM_PEDIDO, PRODUCAO_ORDEM.PROGRAMACAO, CAIXA = SPACE(8),TEMPO_CRONOMETRADO,TEMPO_CRONOM_FIXO   ,SERIE_NF=SPACE(3)
FROM VENDAS_PRODUTO  
INNER JOIN VENDAS ON  VENDAS_PRODUTO.PEDIDO= VENDAS.PEDIDO  
INNER JOIN PRODUCAO_ORDEM ON  VENDAS_PRODUTO.PEDIDO= PRODUCAO_ORDEM.PEDIDO  
INNER JOIN PRODUTOS ON VENDAS_PRODUTO.PRODUTO = PRODUTOS.PRODUTO  
INNER JOIN PRODUTO_CORES ON  VENDAS_PRODUTO.PRODUTO = PRODUTO_CORES.PRODUTO AND   
      VENDAS_PRODUTO.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO  
  
LEFT JOIN PRODUCAO_TAREFAS_SALDO ON  PRODUCAO_ORDEM.ORDEM_PRODUCAO = PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO AND   
         VENDAS_PRODUTO.PRODUTO = PRODUCAO_TAREFAS_SALDO.PRODUTO AND   
         VENDAS_PRODUTO.COR_PRODUTO = PRODUCAO_TAREFAS_SALDO.COR_PRODUTO  
  
LEFT JOIN PRODUCAO_TAREFAS ON PRODUCAO_TAREFAS_SALDO.TAREFA = PRODUCAO_TAREFAS.TAREFA  
LEFT JOIN PRODUCAO_SETOR ON  PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND   
        PRODUCAO_TAREFAS.SETOR_PRODUCAO = PRODUCAO_SETOR.SETOR_PRODUCAO  
LEFT JOIN PRODUCAO_RECURSOS ON PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO  
LEFT JOIN PRODUCAO_FASE ON PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_FASE.FASE_PRODUCAO  
INNER JOIN ROMANEIOS_RESERVAS ON ROMANEIOS_RESERVAS.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO  AND 
								ROMANEIOS_RESERVAS.PEDIDO = VENDAS_PRODUTO.PEDIDO AND 
								ROMANEIOS_RESERVAS.PRODUTO = VENDAS_PRODUTO.PRODUTO AND 
								ROMANEIOS_RESERVAS.COR_PRODUTO = VENDAS_PRODUTO.COR_PRODUTO AND 
								ROMANEIOS_RESERVAS.ENTREGA = VENDAS_PRODUTO.ENTREGA AND 
								ROMANEIOS_RESERVAS.ITEM_PEDIDO = VENDAS_PRODUTO.ITEM_PEDIDO 
WHERE PRODUCAO_ORDEM.STATUS = 'E' AND QTDE_ENTREGAR>0 

UNION ALL   

SELECT '05' AS TIPO, D.ROMANEIO_PRODUTO, C.ROMANEIO,C.PEDIDO,C.FILIAL  ,C.PRODUTO, C.COR_PRODUTO, C.ENTREGA, -D.QTDE,C.ORDEM_PRODUCAO,0,
-EN_1, -EN_2, -EN_3, -EN_4, -EN_5, -EN_6, -EN_7, -EN_8, -EN_9, -EN_10, -EN_11, -EN_12,   
-EN_13, -EN_14, -EN_15, -EN_16, -EN_17, -EN_18, -EN_19, -EN_20, -EN_21, -EN_22, -EN_23, -EN_24,   
-EN_25, -EN_26, -EN_27, -EN_28, -EN_29, -EN_30, -EN_31, -EN_32, -EN_33, -EN_34, -EN_35, -EN_36,   
-EN_37, -EN_38, -EN_39, -EN_40, -EN_41, -EN_42, -EN_43, -EN_44, -EN_45, -EN_46, -EN_47, -EN_48,  
C.COR_PRODUTO,
PRODUTOS.GRADE, 
PRODUCAO_ORDEM.EMISSAO, 
PRODUCAO_ORDEM.INICIO_LIBERADO, PRODUCAO_ORDEM.INICIO_PREVISTO,    
PRODUCAO_ORDEM.INICIO_REAL, PRODUCAO_ORDEM.PREVISAO_FIM,  PRODUCAO_ORDEM.PREVISAO_FIM_NA_EMISSAO, PRODUCAO_ORDEM.ENCERRAMENTO,    
PRODUCAO_ORDEM.QTDE_TOTAL, PRODUCAO_ORDEM.QTDE_EM_PRODUCAO,  PRODUCAO_ORDEM.ORDEM_CORTE,0,   
0,  0, 0,  0, 0,  0,0,  0, 0,  0, 0,  0,   0,  0, 0,  0, 0,  0,   0,  0, 0,  0, 0,  0,   0,  0, 0,  0, 0,  0,   0,  0, 0,  0, 0,  0,   
0,  0, 0,  0, 0,  0,   0,  0, 0,  0, 0,  0,   0,    '' , '',  '',    '', '',  '',    0,   0,    0,   0,    0,   0,    0,    0,   0,    
0,   0,    0,  0,  0, 0,    0, '',  0, '',    '',  '', '',  '',   0, C.ITEM_PEDIDO,   PRODUCAO_ORDEM.PROGRAMACAO,   C.CAIXA ,0,0,SERIE_NF = SPACE(3) 
FROM VENDAS_PROD_EMBALADO  C
INNER JOIN VENDAS_PRODUTO CC	ON C.PEDIDO_PRODUTO = CC.PRODUTO AND
									C.PEDIDO_COR_PRODUTO = CC.COR_PRODUTO AND
									C.ENTREGA=CC.ENTREGA AND 
									C.ITEM_PEDIDO=CC.ITEM_PEDIDO AND
									C.PEDIDO=CC.PEDIDO
INNER JOIN VENDAS CCC			ON	CC.PEDIDO = CCC.PEDIDO
INNER JOIN ESTOQUE_PROD1_ENT D	ON	C.PEDIDO = D.PEDIDO_VENDA AND
									C.PRODUTO = D.PRODUTO AND
									C.COR_PRODUTO = D.COR_PRODUTO AND
									C.ITEM_PEDIDO = D.PEDIDO_VENDA_ITEM AND
									C.ENTREGA = D.PEDIDO_VENDA_ENTREGA AND 
									C.FILIAL = D.FILIAL AND
									C.ORDEM_PRODUCAO = D.ORDEM_PRODUCAO
INNER JOIN PRODUCAO_ORDEM		ON  C.ORDEM_PRODUCAO= PRODUCAO_ORDEM.ORDEM_PRODUCAO  
INNER JOIN PRODUTOS				ON	C.PRODUTO = PRODUTOS.PRODUTO  
INNER JOIN PRODUTO_CORES		ON  C.PRODUTO = PRODUTO_CORES.PRODUTO AND   
									C.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO      
GO


