USE [CAEDU]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [XAK1PRODUTO_SUBCATEGORIA]    Script Date: 19/06/2023 14:00:08 ******/
CREATE UNIQUE NONCLUSTERED INDEX [XAK1PRODUTO_SUBCATEGORIA] ON [dbo].[PRODUTOS_SUBCATEGORIA]
(
	[COD_SUBCATEGORIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO


