SELECT 
B.FILIAL, B.FILIAL_ORIGEM, B.NUMERO_NF_TRANSFERENCIA, B.EMISSAO, B.DATA_SAIDA,
A.PRODUTO, P.DESC_PRODUTO, A.COR_PRODUTO, pc.DESC_COR_PRODUTO ,
EN1, EN2, EN3, EN4, EN5, EN6, EN7, EN8, EN9, EN10, EN11, EN12, EN13, EN14, EN15, EN16,
A.VALOR, A.PRECO1, A.QTDE_ENTRADA, A.ITEM_IMPRESSAO 
FROM LOJA_ENTRADAS_PRODUTO A
INNER JOIN LOJA_ENTRADAS B ON B.ROMANEIO_PRODUTO=A.ROMANEIO_PRODUTO AND B.FILIAL=A.FILIAL
INNER JOIN PRODUTOS P ON P.PRODUTO = A.PRODUTO
INNER JOIN PRODUTO_CORES PC ON PC.PRODUTO = A.PRODUTO AND PC.COR_PRODUTO = A.COR_PRODUTO
WHERE 1=1 
AND A.PRODUTO = '01225179'
AND B.EMISSAO BETWEEN '20190101' AND '20190114'
AND B.FILIAL = 'CD CAJAMAR'


/*
Empresa	
Codigo_item 	
Descrição	
qtd	
Data_base	
Data do Inventário	
Arquivo NF	
Relatório de Movimentações
*/