LOJAS ESKALA COM TEC CONF; MENDES RIGONATTI E CIA LTDA; LOJAS AVENIDA S.A.


select * from faturamento
where NOME_CLIFOR like 'LOJAS ESKALA%'
AND EMISSAO BETWEEN '2017-03-01' AND '2017-04-19'

MENDES RIGONATTI E CIA LT
LOJAS ESKALA COM TEC CONF
LOJAS AVENIDA S.A - 0022 

select * from faturamento where 
FATURAMENTO.NOME_CLIFOR in ('MENDES RIGONATTI E CIA LT','LOJAS ESKALA COM TEC CONF','LOJAS AVENIDA S.A - 0022') and (FATURAMENTO.EMISSAO BETWEEN '20170301' AND '20170419')


SELECT F.NOME_CLIFOR AS CLIENTE,
F.NF_SAIDA AS NF,
F.EMISSAO AS EMISSAO,
F.VALOR_TOTAL AS VALOR_TOTAL,
F.TRANSPORTADORA AS TRANSPORTADORA,
F.CTB_LANCAMENTO AS LANCAMENTO_CONTABIL,
F.DATA_SAIDA AS DATA_SAIDA,
P.ID_PARCELA AS PARCELA
FROM FATURAMENTO F
LEFT JOIN CTB_LANCAMENTO C ON C.LANCAMENTO = F.CTB_LANCAMENTO
LEFT JOIN CTB_A_RECEBER_PARCELA P ON P.LANCAMENTO = C.LANCAMENTO
where 
F.NOME_CLIFOR in ('MENDES RIGONATTI E CIA LT','LOJAS ESKALA COM TEC CONF','LOJAS AVENIDA S.A - 0022') 
and (F.EMISSAO BETWEEN '20170301' AND '20170419')

