select NF_ENTRADA, SERIE_NF_ENTRADA, NOME_CLIFOR, FILIAL, 
FORMAT(RECEBIMENTO,'dd-MM-yyyy') as RECEBIMENTO, QTDE_TOTAL, VALOR_TOTAL	
from ENTRADAS 
WHERE FILIAL LIKE 'CD%'
AND RECEBIMENTO BETWEEN '20250501' AND '20251130'
AND COD_TRANSACAO='ENTRADAS_102' AND NATUREZA='200.01'
ORDER BY RECEBIMENTO, NOME_CLIFOR, NF_ENTRADA
