select	A.NOME_CLIFOR,A.NF_ENTRADA,A.SERIE_NF_ENTRADA, A.FILIAL_ENTRADA, E.RECEBIMENTO,
		E.VALOR_TOTAL, E.VALOR_IMPOSTO_AGREGAR AS ENT_VALOR_IMPOSTO_AGREGAR, 
		F.NF_SAIDA, F.SERIE_NF, F.FILIAL,
		F.VALOR_TOTAL, F.VALOR_IMPOSTO_AGREGAR AS FAT_VALOR_IMPOSTO_AGREGAR,
		FIT.CODIGO_ITEM, FIT.CLASSIF_FISCAL, FIT.ITEM_IMPRESSAO, FIT.SUB_ITEM_TAMANHO,
		FIT.CODIGO_FISCAL_OPERACAO, FIT.ID_EXCECAO_IMPOSTO, FIT.DESCRICAO_ITEM, 
		FIT.INDICADOR_CFOP, FIT.PRECO_UNITARIO, FIT.PRECO_UNITARIO_ORIGINAL, FIT.QTDE_ITEM, FIT.TRIBUT_ORIGEM, FIT.ID_CEST_NCM, FIT.VALOR_ITEM,
		FI.valor_imposto AS ICMS_VALOR_IMPOSTO, 
		FI.base_imposto AS ICMS_BASE_IMPOSTO, 
		FI.base_imposto_calc AS ICMS_BASE_IMPOSTO_CALC, 
		FI.taxa_imposto AS ICMS_TAXA_IMPOSTO, 
		FI2.valor_imposto AS IPI_VALOR_IMPOSTO, 
		FI2.base_imposto AS IPI_BASE_IMPOSTO, 
		FI2.base_imposto_calc AS IPI_BASE_IMPOSTO_CALC, 
		FI2.taxa_imposto AS IPI_TAXA_IMPOSTO, 
		FI5.valor_imposto AS PIS_VALOR_IMPOSTO, 
		FI5.base_imposto AS PIS_BASE_IMPOSTO, 
		FI5.base_imposto_calc AS PIS_BASE_IMPOSTO_CALC, 
		FI5.taxa_imposto AS PIS_TAXA_IMPOSTO, 
		FI6.valor_imposto AS COFINS_VALOR_IMPOSTO, 
		FI6.base_imposto AS COFINS_BASE_IMPOSTO, 
		FI6.base_imposto_calc AS COFINS_BASE_IMPOSTO_CALC, 
		FI6.taxa_imposto AS COFINS_TAXA_IMPOSTO
		
from CSM_TRANSITO_NOTAS A (NOLOCK)

LEFT JOIN FATURAMENTO F (NOLOCK) 
	ON F.FILIAL=A.FILIAL AND F.NF_SAIDA=A.NF_SAIDA AND F.SERIE_NF=A.SERIE_NF

LEFT JOIN ENTRADAS E  (NOLOCK)
	ON E.NOME_CLIFOR = A.NOME_CLIFOR AND E.NF_ENTRADA = A.NF_ENTRADA 
		AND E.SERIE_NF_ENTRADA = A.SERIE_NF_ENTRADA AND E.FILIAL = A.FILIAL_ENTRADA

LEFT JOIN FATURAMENTO_ITEM FIT (NOLOCK) 
	ON FIT.FILIAL = F.FILIAL AND FIT.NF_SAIDA = F.NF_SAIDA AND FIT.SERIE_NF = F.SERIE_NF 

LEFT JOIN FATURAMENTO_IMPOSTO FI  (NOLOCK) /* ICMS*/
	ON FI.FILIAL = FIT.FILIAL AND FI.NF_SAIDA = FIT.NF_SAIDA 
	AND FI.SERIE_NF = FIT.SERIE_NF AND FI.ITEM_IMPRESSAO = FIT.ITEM_IMPRESSAO 
	AND FI.SUB_ITEM_TAMANHO = FIT.SUB_ITEM_TAMANHO AND FI.ID_IMPOSTO = 1

LEFT JOIN FATURAMENTO_IMPOSTO FI2  (NOLOCK) /* IPI*/
	ON FI2.FILIAL = FIT.FILIAL AND FI2.NF_SAIDA = FIT.NF_SAIDA 
	AND FI2.SERIE_NF = FIT.SERIE_NF AND FI2.ITEM_IMPRESSAO = FIT.ITEM_IMPRESSAO 
	AND FI2.SUB_ITEM_TAMANHO = FIT.SUB_ITEM_TAMANHO AND FI2.ID_IMPOSTO = 2

LEFT JOIN FATURAMENTO_IMPOSTO FI5  (NOLOCK) /* PIS*/
	ON FI5.FILIAL = FIT.FILIAL AND FI5.NF_SAIDA = FIT.NF_SAIDA 
	AND FI5.SERIE_NF = FIT.SERIE_NF AND FI5.ITEM_IMPRESSAO = FIT.ITEM_IMPRESSAO 
	AND FI5.SUB_ITEM_TAMANHO = FIT.SUB_ITEM_TAMANHO AND FI5.ID_IMPOSTO = 5

LEFT JOIN FATURAMENTO_IMPOSTO FI6  (NOLOCK) /* COFINS*/
	ON FI6.FILIAL = FIT.FILIAL AND FI6.NF_SAIDA = FIT.NF_SAIDA 
	AND FI6.SERIE_NF = FIT.SERIE_NF AND FI6.ITEM_IMPRESSAO = FIT.ITEM_IMPRESSAO 
	AND FI6.SUB_ITEM_TAMANHO = FIT.SUB_ITEM_TAMANHO AND FI6.ID_IMPOSTO = 6

where A.NOME_CLIFOR = 'KOMPORT' AND DATA>'20171231' AND A.NF_SAIDA <> '000000000'
ORDER BY E.RECEBIMENTO, F.NF_SAIDA, F.SERIE_NF, F.FILIAL, FIT.ITEM_IMPRESSAO, FIT.SUB_ITEM_TAMANHO
--SELECT * FROM FATURAMENTO_IMPOSTO WHERE NF_SAIDA = '000022625' AND FILIAL='CD NAVEGANTES'      
--NF_SAIDA, SERIE_NF, FILIAL, ITEM_IMPRESSAO, SUB_ITEM_TAMANHO


 