select	f.filial as LJ_ORIGEM, 
		f.NOME_CLIFOR as LJ_DESTINO,
		f.NF_SAIDA, 
		CAST(f.EMISSAO AS DATE) as EMISSAO_NF,
		CAST(l.DATA_ENTRADA_CONFERIDA AS DATE) AS DATA_ENTRADA_CONFERIDA,
		CAST(f.QTDE_TOTAL AS INT) QTDE_TOTAL_PCS,
		f.VALOR_TOTAL as VALOR_NF,
		CASE 
			WHEN l.STATUS_TRANSITO  = 4 
			THEN 'TRANSITO LIBERADO' 
			ELSE 'TRANSITO PENDENTE' 
		END AS STATUS_TRANSITO,
		DATEDIFF(DD,F.EMISSAO, ISNULL(L.DATA_ENTRADA_CONFERIDA,GETDATE())) AS DIAS_EM_TRANSITO

from faturamento f 
LEFT JOIN LOJA_ENTRADAS L 
	ON L.ROMANEIO_NF_SAIDA = f.NF_SAIDA and l.FILIAL_ORIGEM = f.FILIAL and l.FILIAL = f.NOME_CLIFOR and l.SERIE_NF_ENTRADA = f.SERIE_NF
where f.NATUREZA_SAIDA like '120%'
and year(F.emissao) = year(getdate())
