select A.EMISSAO, A.RESPONSAVEL, A.ESTOQUE_AJUSTADO, A.TIPO, 
cm.DATA_SALDO, cm.CUSTO_MEDIO_UNITARIO, pp.preco1 as TAB85, ei.QTDE_CONTAGEM, ei.SALDO_CONTAGEM, b.*
from ESTOQUE_PROD_CONTAGEM a
inner join ESTOQUE_PROD_CTG_AJUSTE b on b.NOME_CONTAGEM=a.NOME_CONTAGEM
left join (
select *
from CM_ESTOQUE_PA d
where d.FILIAL = 'LOJA VIRTUAL' 
) as cm ON cm.filial = a.FILIAL and cm.PRODUTO=b.PRODUTO and cm.DATA_SALDO = DATEADD(DD,-1,CONVERT(VARCHAR(6),a.EMISSAO,112)+'01')
left join (select * from produtos_precos where CODIGO_TAB_PRECO='85' 
) pp on pp.PRODUTO = b.PRODUTO
inner join ESTOQUE_PROD_CTG_ITENS ei on ei.NOME_CONTAGEM=b.NOME_CONTAGEM and ei.PRODUTO=b.PRODUTO and ei.COR_PRODUTO=b.COR_PRODUTO
where a.NOME_CONTAGEM='LOJA VIRTUAL 07-08-22'    

--select TOP 5 * from CM_ESTOQUE_PA where filial = 'LOJA VIRTUAL' AND DATA_SALDO = DATEADD(DD,-1,CONVERT(VARCHAR(6),'20220807',112)+'01')

select	pp.CODIGO_TAB_PRECO, 
		case when pp.CODIGO_TAB_PRECO = '00' then 'CUSTO NOTA ENTRADA'
			when pp.CODIGO_TAB_PRECO = '01' then 'VENDA ORIGINAL'
			when pp.CODIGO_TAB_PRECO = '73' then 'PRECO VENDA E-COMMERCE'
			when pp.CODIGO_TAB_PRECO = '85' then 'CUSTO MEDIO CONTABIL'
		ELSE ''
		END AS DESCRICAO_TABELA,
		pp.PRODUTO, 
		pp.PRECO1
from produtos_precos pp
inner join (
SELECT produto FROM ESTOQUE_PROD_CTG_ITENS WHERE NOME_CONTAGEM='LOJA VIRTUAL 07-08-22') as a on a.PRODUTO = pp.PRODUTO
where pp.CODIGO_TAB_PRECO in ('00','01','73','85')
ORDER BY 3,1


