WITH BASE_PRODUTO (produto, DESC_PRODUTO, GRIFFE, LINHA, GRUPO_PRODUTO, SUBGRUPO_PRODUTO,
					GRADE,FABRICANTE, TRIBUT_ORIGEM_PRODUTO, CLASSIF_FISCAL,ID_CEST_NCM,
					CODIGO_CEST,DESCRICAO_CEST,INDICADOR_CFOP,ID_EXCECAO_GRUPO)
AS (
select	p.produto, 
		p.DESC_PRODUTO, 
		p.GRIFFE, 
		p.LINHA, 
		p.GRUPO_PRODUTO, 
		p.SUBGRUPO_PRODUTO,
		p.GRADE,
		p.FABRICANTE,
		p.TRIBUT_ORIGEM as TRIBUT_ORIGEM_PRODUTO,
		p.CLASSIF_FISCAL,
		p.ID_CEST_NCM,
		tbcest.CODIGO_CEST,
		tbcest.DESCRICAO as DESCRICAO_CEST,
		p.INDICADOR_CFOP,
		p.ID_EXCECAO_GRUPO
from produtos p
LEFT JOIN (select  
			TABELA_LX_CEST.CODIGO_CEST, 
			TABELA_LX_NCM.CODIGO_NCM, 
			Cast(TABELA_LX_CEST.DESCRICAO As VARCHAR(254)) As DESCRICAO, 
			CEST_NCM.ID, TABELA_LX_CEST.INATIVO 
		from TABELA_LX_CEST   
		JOIN CEST_NCM ON TABELA_LX_CEST.ID = CEST_NCM.ID_CEST 
		JOIN TABELA_LX_NCM ON CEST_NCM.ID_NCM = TABELA_LX_NCM.ID 
		where  
		CEST_NCM.INATIVO = 0  
		And TABELA_LX_NCM.INATIVO = 0  
		And TABELA_LX_CEST.INATIVO = 0  
		) as tbcest on tbcest.ID=p.ID_CEST_NCM and tbcest.CODIGO_NCM=p.CLASSIF_FISCAL

where p.INATIVO=0 
--and exists (
--select produto from estoque_produtos
--where 1=1 and 
--((ES1<>0) OR (ES2<>0) OR (ES3<>0) OR (ES4<>0) OR (ES5<>0) OR (ES6<>0) 
--		OR (ES7<>0) OR (ES8<>0) OR (ES9<>0) OR (ES10<>0) OR (ES11<>0) OR (ES12<>0) 
--		OR (ES13<>0) OR (ES14<>0) OR (ES15<>0) OR (ES16<>0))
--)
and exists (
select 1 
from compras_produto cp
inner join compras c on cp.pedido=cp.PEDIDO
where produto=p.PRODUTO and c.TOT_QTDE_ENTREGAR>0
))
select	A.*, 
		pc.CLASSIF_FISCAL as NCM_COR, 
		pc.COR_PRODUTO,
		pc.DESC_COR_PRODUTO,
		CONVERT(VARCHAR(10),pc.FIM_VENDAS,103) AS FIM_VENDAS,
		pc.TRIBUT_ORIGEM AS TRIBUT_ORIGEM_COR
FROM BASE_PRODUTO a
left join PRODUTO_CORES pc on pc.PRODUTO=a.produto


--SELECT a.*,	pic.FILIAL,
--		pic.TRIBUT_ORIGEM as TRIBUT_ORIGEM_CARAC_CONTAB,
--		pic.INDICADOR_CFOP,
--		pic.TIPO_ITEM_SPED
--FROM BASE_PRODUTO a
--left JOIN PRODUTOS_INDICADOR_CFOP pic on pic.PRODUTO=a.PRODUTO

/*
select	p.produto, 
		p.DESC_PRODUTO, 
		p.GRIFFE, 
		p.LINHA, 
		p.GRUPO_PRODUTO, 
		p.SUBGRUPO_PRODUTO,
		p.GRADE,
		p.FABRICANTE,
		p.CLASSIF_FISCAL,
		p.ID_CEST_NCM,
		p.TRIBUT_ORIGEM as TRIBUT_ORIGEM_PRODUTO,
		pic.FILIAL,
		pic.TRIBUT_ORIGEM as TRIBUT_ORIGEM_CARAC_CONTAB,
		pic.INDICADOR_CFOP,
		pic.TIPO_ITEM_SPED,
		CASE WHEN p.TRIBUT_ORIGEM=pic.TRIBUT_ORIGEM THEN 'IGUAL'
			ELSE	'DIFERENTE' END AS COMPARA

from produtos p
left JOIN PRODUTOS_INDICADOR_CFOP pic on pic.PRODUTO=p.PRODUTO
where p.INATIVO=0
and exists (
select produto from estoque_produtos
where 1=1 and 
((ES1<>0) OR (ES2<>0) OR (ES3<>0) OR (ES4<>0) OR (ES5<>0) OR (ES6<>0) 
		OR (ES7<>0) OR (ES8<>0) OR (ES9<>0) OR (ES10<>0) OR (ES11<>0) OR (ES12<>0) 
		OR (ES13<>0) OR (ES14<>0) OR (ES15<>0) OR (ES16<>0))
)
and exists (
select 1 
from compras_produto cp
inner join compras c on cp.pedido=cp.PEDIDO
where produto=p.PRODUTO and c.TOT_QTDE_ENTREGAR>0
)


select  
	TABELA_LX_CEST.CODIGO_CEST, 
	TABELA_LX_NCM.CODIGO_NCM, 
	Cast(TABELA_LX_CEST.DESCRICAO As VARCHAR(254)) As DESCRICAO, 
	CEST_NCM.ID, TABELA_LX_CEST.INATIVO 
from TABELA_LX_CEST   
JOIN CEST_NCM ON TABELA_LX_CEST.ID = CEST_NCM.ID_CEST 
JOIN TABELA_LX_NCM ON CEST_NCM.ID_NCM = TABELA_LX_NCM.ID 
where  CEST_NCM.ID=7345
And CEST_NCM.INATIVO = 0  
And TABELA_LX_NCM.INATIVO = 0  
And TABELA_LX_CEST.INATIVO = 0  
and TABELA_LX_NCM.CODIGO_NCM = '42029200'


select ID_CEST_NCM,* from produtos where produto = '55110301'
*/