select B.PRODUTO, P.DESC_PRODUTO, PP.PRECO1 AS PRECO_VENDA 
from ESTOQUE_PROD_CONTAGEM a
inner join ESTOQUE_PROD_CTG_ITENS b on b.NOME_CONTAGEM=a.NOME_CONTAGEM
inner join PRODUTOS P ON P.PRODUTO=B.PRODUTO
LEFT JOIN PRODUTOS_PRECOS PP ON PP.PRODUTO=B.PRODUTO AND PP.CODIGO_TAB_PRECO='01'
where (a.EMISSAO between '20220801' and '20220930') or 
(a.EMISSAO between '20230101' and '20230228')
GROUP BY B.PRODUTO, P.DESC_PRODUTO, PP.PRECO1