SELECT A.PEDIDO, A.CLIENTE_ATACADO, CAST(A.EMISSAO AS DATE) AS EMISSAO, B.PRODUTO, P.DESC_PRODUTO, P.GRADE, LEFT(T.TAMANHOS,LEN(T.TAMANHOS)-1) AS TAMANHOS, B.QTDE_ORIGINAL,
B.VO1, B.VO2, B.VO3, B.VO4, B.VO5, B.VO6, B.VO7, B.VO8, B.VO9, B.VO10, B.VO11, B.VO12, B.VO13, B.VO14, B.VO15, B.VO16,
B.PRECO1, B.VALOR_ORIGINAL
FROM VENDAS A
INNER JOIN VENDAS_PRODUTO B ON B.PEDIDO=A.PEDIDO
INNER JOIN PRODUTOS P ON P.PRODUTO = B.PRODUTO
INNER JOIN 
(SELECT	GRADE, 
(CASE WHEN TAMANHO_1 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_1)) = '' THEN '' ELSE TAMANHO_1 + '/' END) +
(CASE WHEN TAMANHO_2 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_2)) = '' THEN '' ELSE TAMANHO_2 + '/'  END) +
(CASE WHEN TAMANHO_3 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_3)) = '' THEN '' ELSE TAMANHO_3 + '/'  END) +
(CASE WHEN TAMANHO_4 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_4)) = '' THEN '' ELSE TAMANHO_4 + '/'  END) +
(CASE WHEN TAMANHO_5 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_5)) = '' THEN '' ELSE TAMANHO_5 + '/'  END) +
(CASE WHEN TAMANHO_6 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_6)) = '' THEN '' ELSE TAMANHO_6 + '/'  END) +
(CASE WHEN TAMANHO_7 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_7)) = '' THEN '' ELSE TAMANHO_7 + '/'  END) +
(CASE WHEN TAMANHO_8 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_8)) = '' THEN '' ELSE TAMANHO_8 + '/'  END) +
(CASE WHEN TAMANHO_9 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_9)) = '' THEN '' ELSE TAMANHO_9 + '/'  END) +
(CASE WHEN TAMANHO_10 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_10)) = '' THEN '' ELSE TAMANHO_10 + '/'  END) +
(CASE WHEN TAMANHO_11 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_11)) = '' THEN '' ELSE TAMANHO_11 + '/'  END) +
(CASE WHEN TAMANHO_12 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_12)) = '' THEN '' ELSE TAMANHO_12 + '/'  END) +
(CASE WHEN TAMANHO_13 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_13)) = '' THEN '' ELSE TAMANHO_13 + '/'  END) +
(CASE WHEN TAMANHO_14 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_14)) = '' THEN '' ELSE TAMANHO_14 + '/'  END) +
(CASE WHEN TAMANHO_15 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_15)) = '' THEN '' ELSE TAMANHO_15 + '/'  END) +
(CASE WHEN TAMANHO_16 LIKE '%.%' THEN '' WHEN RTRIM(LTRIM(TAMANHO_16)) = '' THEN '' ELSE TAMANHO_16 END) AS TAMANHOS
FROM PRODUTOS_TAMANHOS ) AS T ON T.GRADE = P.GRADE
WHERE A.FILIAL = 'VENDA ATACADO'
ORDER BY A.PEDIDO
