select FILIAL, 
		NOME_CONTAGEM, 
		cast(EMISSAO as date) EMISSAO, 
		CAST(DATA_AJUSTE as date) DATA_AJUSTE
from ESTOQUE_PROD_CONTAGEM 
where DATA_AJUSTE >= '20230101' and DATA_AJUSTE <= '20241231'
ORDER BY EMISSAO