--select *
--from filiais where filial = 'GO - SH PORTAL SUL'       

	
select 
f.FILIAL
,f.NF_SAIDA
,f.SERIE_NF
,f.chave_nfe
,f.NOME_CLIFOR as filial_destino
,f.TIPO_FATURAMENTO
,f.CONDICAO_PGTO
,f.NATUREZA_SAIDA
,f.TRANSPORTADORA
,f.TRANSP_REDESPACHO
,f.TIPO_FRETE
,f.COD_TRANSACAO
,f.EMISSAO
,f.DATA_SAIDA
,f.FRETE
,f.SEGURO
,f.DESCONTO
,f.DESCONTO_COND_PGTO
,f.ENCARGO
,f.ICMS
,f.IPI_VALOR
,f.VALOR_TOTAL
,f.QTDE_TOTAL
,f.NF_FATURA
,f.VOLUMES
,f.STATUS_NFE
,f.PROTOCOLO_CANCELAMENTO_NFE
,f.DATA_CANCELAMENTO
,f.DATA_AUTORIZACAO_NFE
,fp.PRODUTO
,fp.COR_PRODUTO
,fp.ITEM
,fp.PEDIDO
,fp.PEDIDO_PRODUTO
,fp.PEDIDO_COR
,fp.ENTREGA
,fp.CAIXA
,fp.IPI
,fp.ICMS
,fp.DESCONTO_ITEM
,fp.QTDE
,fp.PRECO
,fp.VALOR
,fp.PACKS
,fp.F1
,fp.F2
,fp.F3
,fp.F4
,fp.F5
,fp.F6
,fp.F7
,fp.F8
,fp.F9
,fp.F10
,fp.F11
,fp.F12
,fp.F13
,fp.F14
,fp.F15
,fp.F16
,fp.FAIXA
,fp.ORIGEM
,fp.ROMANEIO
,fp.CUSTO_NA_DATA
,fp.MOEDA
,fp.CAMBIO_NA_DATA
,fp.ORIGEM_EMB
,fp.DATA_PARA_TRANSFERENCIA
,fp.CODIGO_LOCAL_ENTREGA
,fp.CODIGO_FISCAL_OPERACAO
,fp.COD_FILIAL_ESTOQUE
,fp.ITEM_IMPRESSAO
,fp.ITEM_PEDIDO
,fp.ORDEM_PRODUCAO
,fp.VALOR_DIFERENCA_GUIA_FATURA_ITEM
,fp.DESC_VENDA_CLIENTE
,fp.ID_MODIFICACAO
,fp.LICENCIADO_ROYALTIES
,fp.ID_VENDA_ENTREGA_FUTURA
,fp.item_caedu
,fp.ID_CEST_NCM
from faturamento f
inner join faturamento_prod fp on fp.NF_SAIDA=f.NF_SAIDA and fp.SERIE_NF=f.SERIE_NF and fp.FILIAL=f.FILIAL
where f.filial = 'GO - SH PORTAL SUL'
and emissao between '20260601' and '20260831'


