CREATE TABLE DBO.CAEDU_RELATORIOS_EXCEL
(
CODIGO CHAR(4) NOT NULL,
TITULO VARCHAR(100) NOT NULL,
NOME_PADRAO_PLANILHA_SAIDA VARCHAR(100) NOT NULL,
QUERY TEXT NOT NULL,
INATIVO BIT NOT NULL DEFAULT (0),
AREA_SOLICITANTE VARCHAR(100) NULL,
DESCRICAO_RELATORIO VARCHAR(220) NULL,
CONSTRAINT PK_CAEDU_RELATORIOS_EXCEL PRIMARY KEY (CODIGO)
)
GO

CREATE TABLE DBO.CAEDU_RELATORIOS_EXCEL_PARAMETROS
(
CODIGO CHAR(4) NOT NULL,
PARAMETRO_ID VARCHAR(25) NOT NULL,
TIPO_DADO CHAR(1) NOT NULL,
VALOR_PARAMETRO VARCHAR(200) NULL,
VALOR_PADRAO VARCHAR(200) NULL,
PARAM_OBRIGATORIO BIT NOT NULL DEFAULT (1),
VALOR_PARAMETRO_NULO VARCHAR(200) NULL
CONSTRAINT PK_CAEDU_RELATORIOS_EXCEL_PARAMETROS PRIMARY KEY (CODIGO, PARAMETRO_ID)
)
GO

ALTER TABLE DBO.CAEDU_RELATORIOS_EXCEL_PARAMETROS
ADD CONSTRAINT FK_CAEDU_RELATORIOS_EXCEL_PARAMETROS_CODIGO FOREIGN KEY (CODIGO)
REFERENCES CAEDU_RELATORIOS_EXCEL (CODIGO)
GO




