update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010132';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020005';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020006';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020007';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020016';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020017';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020018';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020019';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020020';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020021';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020022';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010137';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020014';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010129';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020003';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010127';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020008';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010128';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020004';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01080017';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01080018';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240110';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240107';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240106';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01080019';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240108';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240117';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240109';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010090';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010119';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010088';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010117';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010089';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010120';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010060';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010062';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010118';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010054';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010086';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020010';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020013';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010136';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010135';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020023';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010130';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020012';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020011';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010040';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240146';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010087';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240142';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010068';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010042';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010085';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010110';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240145';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010056';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010075';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020002';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020015';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240143';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240144';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3030003';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3020009';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3010133';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3030005';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3030007';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3030008';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3030009';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3030010';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3030011';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3030012';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3010096';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3010047';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'F4010021';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3010106';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010082';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3010041';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010069';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3010095';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3010108';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3030002';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3010076';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3010112';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3010094';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3010105';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3030004';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'D3030006';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040067';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040072';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040092';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040043';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010007';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010055';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040074';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040050';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040052';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040091';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040102';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040100';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040040';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040042';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040051';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040063';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240121';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240120';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240124';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240125';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225052';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225051';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240119';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240126';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040070';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040068';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040039';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040071';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040086';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040038';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040036';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040069';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040037';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010111';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010043';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010012';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040101';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040107';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040004';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040106';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040011';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040012';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040021';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040064';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040049';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040061';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040073';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040013';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040062';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040020';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040002';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010038';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010030';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010044';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010013';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010024';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010031';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010045';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010014';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010032';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010009';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010015';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040005';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040033';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '45440038';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010029';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010061';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D1010042';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040094';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040024';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040028';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040027';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040093';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040019';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040022';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225048';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225050';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240127';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240122';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240123';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225049';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240118';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040068';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040052';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040036';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040052';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225052';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040012';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225051';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010111';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225048';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040042';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040028';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040070';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040024';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040005';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040093';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225050';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040043';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D1010042';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040040';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040061';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040091';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040068';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040004';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040051';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040091';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040086';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040102';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225049';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D1010042';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040022';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010038';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225050';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040092';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040038';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040020';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040073';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040094';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040069';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040092';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040049';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040011';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040093';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225051';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040094';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010032';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040072';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040037';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010031';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040063';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010055';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225049';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040027';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040069';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040070';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010061';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040002';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040086';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040013';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040074';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040019';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040067';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040106';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040042';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040062';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040039';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040062';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040061';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225052';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040021';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040050';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225048';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225048';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040064';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040100';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040037';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040038';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040039';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040102';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040019';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040107';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040071';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040107';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040100';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040106';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040101';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040101';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040002';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040036';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225048';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225049';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225050';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225051';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01225052';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240118';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = '01240119';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D1010042';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010007';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010012';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010013';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010014';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010015';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010024';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010031';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010032';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010038';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010055';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010061';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'D3010111';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040002';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040004';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040005';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040011';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040012';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040013';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040020';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040021';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040022';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040024';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040027';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040028';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040036';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040037';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040038';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040040';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040042';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040043';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040049';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040051';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040052';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040061';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040062';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040063';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040068';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040069';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040070';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040072';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040073';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040074';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040086';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040091';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040092';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040093';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040094';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040100';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'M/C E M/L' where produto = 'Z6040102';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080004';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080008';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080007';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040003';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040058';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080010';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080005';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040046';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040047';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = '05080190';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040060';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040057';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040045';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080011';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040059';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080006';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080002';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080009';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080012';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080003';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040048';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080012';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040047';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080012';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080007';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040047';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080009';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040059';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040046';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040059';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040003';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080011';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080008';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080006';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040057';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040046';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040058';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080009';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040057';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080006';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040060';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040045';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040048';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080007';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040060';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080011';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080008';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040045';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080005';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080010';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080002';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040058';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080010';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080004';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080003';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040003';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040045';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040046';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040047';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040048';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040057';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040058';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040059';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6040060';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080006';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080007';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080008';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080009';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080010';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080011';
update produtos set grupo_produto = 'TOP', subgrupo_produto = 'JAQUETA' where produto = 'Z6080012';
