UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = '64040014';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = '64040015';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = '64040016';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = '64040018';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = '64040019';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = '64040020';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = '64040021';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = '64040023';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = '64040024';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = '64040025';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = '64040026';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = '64040027';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = '64040028';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = '64040030';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = '64050016';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = 'Z2010008';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = 'Z2010010';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = 'Z2010011';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = 'Z2010012';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = 'Z2010014';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = 'Z2010015';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = 'Z2010016';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = 'Z2010017';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = 'Z2010018';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = 'Z2010019';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = 'Z2010020';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = 'Z2010021';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = 'Z2010022';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = 'Z2010023';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = 'Z2010024';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = 'Z2010025';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = 'Z2010032';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = 'Z2010033';
UPDATE PRODUTOS SET GRUPO_PRODUTO ='GARRAFA' WHERE PRODUTO = 'Z2010087';
UPDATE PRODUTOS SET GRUPO_PRODUTO = 'VIAGEM', SUBGRUPO_PRODUTO = 'PORTA OBJETO' WHERE PRODUTO = '64060018';
UPDATE PRODUTOS SET GRUPO_PRODUTO = 'VIAGEM', SUBGRUPO_PRODUTO = 'PORTA OBJETO' WHERE PRODUTO = '64060019';
UPDATE PRODUTOS SET GRUPO_PRODUTO = 'VIAGEM', SUBGRUPO_PRODUTO = 'PORTA OBJETO' WHERE PRODUTO = 'Z5030022';
UPDATE PRODUTOS SET GRUPO_PRODUTO = 'VIAGEM', SUBGRUPO_PRODUTO = 'PORTA OBJETO' WHERE PRODUTO = 'Z5030023';
UPDATE PRODUTOS SET GRUPO_PRODUTO = 'VIAGEM', SUBGRUPO_PRODUTO = 'PORTA OBJETO' WHERE PRODUTO = 'Z5030036';
update produtos set subgrupo_produto = 'PORTA OBJETO' where produto = 'Z5010008';
update produtos set subgrupo_produto = 'PORTA OBJETO' where produto = 'Z5010009';
update produtos set subgrupo_produto = 'PORTA OBJETO' where produto = 'Z5010076';
update produtos set subgrupo_produto = 'PORTA OBJETO' where produto = 'Z5010080';
update produtos set subgrupo_produto = 'PORTA OBJETO' where produto = 'Z5010081';
update produtos set subgrupo_produto = 'PORTA OBJETO' where produto = 'Z5010084';
update produtos set subgrupo_produto = 'PORTA OBJETO' where produto = 'Z5010090';
update produtos set subgrupo_produto = 'PORTA OBJETO' where produto = 'Z5010091';
update produtos set subgrupo_produto = 'PORTA OBJETO' where produto = 'Z5010097';
update produtos set subgrupo_produto = 'PORTA OBJETO' where produto = 'Z5010098';
update produtos set subgrupo_produto = 'PORTA OBJETO' where produto = 'Z5010099';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010026';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010027';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010028';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010029';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010031';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010032';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010034';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010041';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010043';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010044';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010045';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010046';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010050';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010051';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010052';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010053';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010054';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010055';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010056';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010057';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010058';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010059';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010070';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010071';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010072';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010073';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010074';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010075';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010076';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010077';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0010078';
update produtos set subgrupo_produto = 'CABELO INFANTIL' where produto = 'B0020032';
