--select ID_IMPOSTO, sum(valor_imposto)
--from entradas e
--inner join ENTRADAS_IMPOSTO ei 
--on ei.NOME_CLIFOR=e.NOME_CLIFOR and ei.NF_ENTRADA=e.NF_ENTRADA and ei.SERIE_NF_ENTRADA=e.SERIE_NF_ENTRADA
--where e.RECEBIMENTO>'20250101'
--group by ID_IMPOSTO



--select * from ctb_lx_imposto_tipo where ID_IMPOSto in (1,2,5,6,12)

SELECT    
dbo.COMPRAS_PRODUTO.PEDIDO,
dbo.COMPRAS.ERP_CUPS_SEGMENTO,
dbo.COMPRAS.FORNECEDOR,
dbo.COMPRAS.CADASTRAMENTO,
dbo.PRODUTOS.REFER_FABRICANTE,
dbo.PRODUTOS.ERP_GRUPO_MERCADORIA,
dbo.COMPRAS.REQUERIDO_POR,
dbo.COMPRAS.TIPO_COMPRA,
dbo.COMPRAS_PRODUTO.PRODUTO,
dbo.COMPRAS_PRODUTO.COR_PRODUTO,
dbo.PRODUTOS.GRIFFE,
--dbo.PRODUTOS.GRIFFE,
dbo.PRODUTOS.LINHA,
dbo.PRODUTOS.GRUPO_PRODUTO,
dbo.PRODUTOS.SUBGRUPO_PRODUTO,
dbo.PRODUTOS.CLASSIF_FISCAL,
dbo.PRODUTOS.DESC_PRODUTO,
dbo.PRODUTOS.TIPO_PRODUTO,
dbo.PRODUTOS.COLECAO,
dbo.PRODUTOS.FATOR_P,
dbo.COMPRAS_PRODUTO.ENTREGA,
dbo.COMPRAS_PRODUTO.LIMITE_ENTREGA,
dbo.COND_ENT_PGTOS.DESC_COND_PGTO,
dbo.COMPRAS_PRODUTO.CUSTO1,
dbo.PRODUTOS_PRECOS.PRECO1,
dbo.COMPRAS_PRODUTO.QTDE_ORIGINAL,
dbo.COMPRAS_PRODUTO.QTDE_CANCELADA,
dbo.COMPRAS_PRODUTO.QTDE_ENTREGUE,
dbo.COMPRAS_PRODUTO.QTDE_ENTREGAR,
dbo.COLECOES.DESC_COLECAO,
dbo.PRODUTOS_CATEGORIA.CATEGORIA_PRODUTO,
dbo.PRODUTOS.TRIBUT_ORIGEM,
dbo.COMPRAS.FILIAL_A_ENTREGAR,
dbo.PRODUTOS.ERP_DESC_LICENCIADO AS LICENCIADOR,
dbo.cadastro_cli_for.UF,
dbo.COMPRAS.ERP_CAB_COD_CABIDE,
dbo.COMPRAS.ERP_CAB_QTDPECAS,
dbo.COMPRAS.ERP_CAB_STATUS,
dbo.COMPRAS.ERP_CAB_DATA_ENVIO,
dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.QTDE as Total_PACK
, CASE COMPRAS.ERP_CAB_COD_BOLACHA
       WHEN 'E1'     THEN '1 ALARME'                
       WHEN 'E2'     THEN '2 ALARMES'               
       WHEN ''     THEN 'NENHUM'               
       ELSE ''
END  AS 'QTD ALARME'
, CASE COMPRAS.ERP_CAB_OPCAO
       WHEN '1'     THEN 'NENHUM'                
       WHEN '2'     THEN 'SÓ CABIDE'               
       WHEN '3'     THEN 'SÓ ALARME'               
       WHEN '4'     THEN 'CABIDE+ALARME'
       ELSE ''
END  AS 'OPCAO_CABIDE'
, CASE dbo.COMPRAS.STATUS_COMPRA
       WHEN '01'     THEN 'APROVADO'                
       WHEN '02'     THEN 'EM ESTUDO'               
       WHEN '03'     THEN 'REPROVADO'               
       WHEN '04'     THEN 'AGUARDANDO SENHA'
       ELSE ''
END  AS 'STATUS_PEDIDO'
,ISNULL((SELECT TOP 1 ISNULL(VALOR_PROPRIEDADE,'') AS VALOR_PROPRIEDADE
FROM PROP_PRODUTOS WHERE PROPRIEDADE = '00114' AND PRODUTO = COMPRAS_PRODUTO.PRODUTO),'') AS CAMPANHA_CARTAO
,(select min(emissao) from ESTOQUE_PROD_ENT where pedido = dbo.COMPRAS.pedido) as DATA_RECEBIMENTO
,(select top 1 DESC_COR_PRODUTO from dbo.PRODUTO_CORES where cor = dbo.COMPRAS_PRODUTO.COR_PRODUTO and PRODUTO = dbo.COMPRAS_PRODUTO.PRODUTO) as DESC_COR
,COALESCE(CAST(id_modelagem AS CHAR(5)),'')  AS "ID MODELAGEM"
,COALESCE(ERP_TEMA_LICENCIADO, '') AS "LICENCIADO"
,case produtos.CONTINUIDADE
when 1 THEN 'CONTINUO'
when 2 THEN 'SEMI-CONTINUO'
when 3 THEN 'DESCONTINUO'
else ''
end as CONTINUO,
ISNULL((SELECT TOP 1 ISNULL(VALOR_PROPRIEDADE,'') AS VALOR_PROPRIEDADE
       FROM PROP_COMPRAS WHERE PROPRIEDADE = '00093' AND PEDIDO = COMPRAS.PEDIDO),'') AS BONIFICACAO,
ISNULL((SELECT TOP 1 ISNULL(VALOR_PROPRIEDADE,'') AS VALOR_PROPRIEDADE
       FROM PROP_COMPRAS WHERE PROPRIEDADE = '00095' AND PEDIDO = COMPRAS.PEDIDO),'') AS PRONTA_ENTREGA,
 
CGP_UNOUS_ENVIAR_TODAS_LOJAS_PEDIDO = ISNULL((select VALOR_PROPRIEDADE from PROP_COMPRAS where propriedade = '00106' AND PEDIDO = COMPRAS.PEDIDO),'NÃO'),
CGP_UNOUS_ALOCAR_PRODUTO = ISNULL((SELECT VALOR_PROPRIEDADE FROM PROP_PRODUTOS WHERE PROPRIEDADE = '00108' AND PRODUTO = PRODUTOS.PRODUTO),'NÃO'),
ISNULL((SELECT TOP 1 ISNULL(VALOR_PROPRIEDADE,'') AS VALOR_PROPRIEDADE
       FROM PROP_COMPRAS WHERE PROPRIEDADE = '00111' AND PEDIDO = COMPRAS.PEDIDO),'') AS DATA_ORIGINAL,
ISNULL((SELECT TOP 1 ISNULL(VALOR_PROPRIEDADE,'') AS VALOR_PROPRIEDADE
       FROM PROP_COMPRAS WHERE PROPRIEDADE = '00112' AND PEDIDO = COMPRAS.PEDIDO),'') AS JUSTIFICATIVA,
ISNULL((SELECT TOP 1 ISNULL(VALOR_PROPRIEDADE,'') AS VALOR_PROPRIEDADE
       FROM PROP_COMPRAS WHERE PROPRIEDADE = '00110' AND PEDIDO = COMPRAS.PEDIDO),'') AS E_COMMERCE
,DBO.PRODUTOS.ERP_FT_DESC_CLASSIFICACAO AS CLASSIFICACAO, compras.DESCONTO
,dbo.PRODUTOS.ERP_CUPS_EVENTO
,(select top 1 DESCRICAO from dbo.CAEDU_LISTA_COMBO where codigo = dbo.PRODUTOS.ERP_CUPS_EVENTO) as DESC_EVENTO,
COMPRAS.ERP_CUPS_PROCESSO_CCF_CCA, COMPRAS.PEDIDO_FORNECEDOR, PRODUTOS.ERP_CUPS_SUPPLIER, 
ccf.FORNECEDOR as [SUPPLIER (PRODUTO)],
COMPRAS.ERP_CUPS_EMBARQUE_ATUAL,
COMPRAS.ERP_CUPS_EMBARQUE_REAL as [EMBARQUE REAL (ETD)],
COMPRAS_PRODUTO.ERP_CUPS_CUSTO_FOB as [CUSTO FOB (US$)],
--DESC_COND_PGTO,
ERP_CUPS_CONTRATO,
RTRIM(LTRIM(convert(VARCHAR(250), dbo.COMPRAS.OBS))) as OBS
,(SELECT EPE.PEDIDO, ENT.NATUREZA, ENT.NOME_CLIFOR, ENT.NF_ENTRADA, ENT.SERIE_NF_ENTRADA, ENT.RECEBIMENTO, 
	ENT.VALOR_SUB_ITENS as VALOR_BRUTO,ENT.DESCONTO,
	E_1.BASE_IMPOSTO AS BASE_ICMS, E_1.VALOR_IMPOSTO AS VALOR_ICMS, E_1.TAXA_IMPOSTO,
	E_2.BASE_IMPOSTO AS BASE_IPI, E_2.VALOR_IMPOSTO AS VALOR_IPI, E_2.TAXA_IMPOSTO,
	E_5.BASE_IMPOSTO AS BASE_PIS, E_5.VALOR_IMPOSTO AS VALOR_PIS,E_5.TAXA_IMPOSTO,
	E_6.BASE_IMPOSTO AS BASE_COFINS, E_6.VALOR_IMPOSTO AS VALOR_COFINS,E_6.TAXA_IMPOSTO,
	E_12.BASE_IMPOSTO AS BASE_ICMS_ST, E_12.VALOR_IMPOSTO AS VALOR_ICMS_ST,E_12.TAXA_IMPOSTO
 FROM ESTOQUE_PROD_ENT EPE
 INNER JOIN ENTRADAS ENT ON ENT.NF_ENTRADA=EPE.NF_ENTRADA AND ENT.SERIE_NF_ENTRADA=EPE.SERIE_NF_ENTRADA AND ENT.NOME_CLIFOR=EPE.NOME_CLIFOR

 LEFT JOIN ENTRADAS_IMPOSTO E_1 
	ON E_1.nome_clifor = EPE.NOME_CLIFOR    
		AND E_1.nf_entrada = EPE.NF_ENTRADA
		AND E_1.serie_nf_entrada = EPE.SERIE_NF_ENTRADA
		AND E_1.ID_IMPOSTO=1

 LEFT JOIN ENTRADAS_IMPOSTO E_2 
	ON E_2.nome_clifor = EPE.NOME_CLIFOR    
		AND E_2.nf_entrada = EPE.NF_ENTRADA
		AND E_2.serie_nf_entrada = EPE.SERIE_NF_ENTRADA
		AND E_2.ID_IMPOSTO=2

 LEFT JOIN ENTRADAS_IMPOSTO E_5 
	ON E_5.nome_clifor = EPE.NOME_CLIFOR    
		AND E_5.nf_entrada = EPE.NF_ENTRADA
		AND E_5.serie_nf_entrada = EPE.SERIE_NF_ENTRADA
		AND E_5.ID_IMPOSTO=5

 LEFT JOIN ENTRADAS_IMPOSTO E_6 
	ON E_6.nome_clifor = EPE.NOME_CLIFOR    
		AND E_6.nf_entrada = EPE.NF_ENTRADA
		AND E_6.serie_nf_entrada = EPE.SERIE_NF_ENTRADA
		AND E_6.ID_IMPOSTO=6

 LEFT JOIN ENTRADAS_IMPOSTO E_12 
	ON E_12.nome_clifor = EPE.NOME_CLIFOR    
		AND E_12.nf_entrada = EPE.NF_ENTRADA
		AND E_12.serie_nf_entrada = EPE.SERIE_NF_ENTRADA
		AND E_12.ID_IMPOSTO=12

 WHERE ENT.NATUREZA='200.01' 
	--AND  EPE.nome_clifor = 'S4 CONFECÇÕES LTDA ME' AND EPE.nf_entrada = '000006782' AND EPE.serie_nf_entrada = '001'
	AND PEDIDO=COMPRAS_PRODUTO.PEDIDO
	FOR JSON AUTO

) as IMPOSTOS
FROM         	dbo.COMPRAS_PRODUTO 
INNER JOIN
             	dbo.PRODUTOS ON dbo.COMPRAS_PRODUTO.PRODUTO = dbo.PRODUTOS.PRODUTO 
INNER JOIN
             	dbo.PRODUTOS_PRECOS ON dbo.PRODUTOS.PRODUTO = dbo.PRODUTOS_PRECOS.PRODUTO 
INNER JOIN
             	dbo.COLECOES ON DBO.COLECOES.COLECAO = DBO.PRODUTOS.COLECAO 
INNER JOIN
             	dbo.COMPRAS ON dbo.COMPRAS_PRODUTO.PEDIDO = dbo.COMPRAS.PEDIDO 
INNER JOIN
             	dbo.PRODUTOS_CATEGORIA  ON dbo.PRODUTOS.COD_CATEGORIA    = dbo.PRODUTOS_CATEGORIA.COD_CATEGORIA 
INNER JOIN
             	dbo.COND_ENT_PGTOS ON dbo.COMPRAS.CONDICAO_PGTO = dbo.COND_ENT_PGTOS.CONDICAO_PGTO
INNER JOIN 		
					dbo.cadastro_cli_for on compras.fornecedor=cadastro_cli_for.nome_clifor
LEFT JOIN 		
					dbo.FORNECEDORES ccf on ccf.clifor = produtos.ERP_CUPS_SUPPLIER
INNER JOIN  	
					dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL ON dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.PEDIDO = dbo.COMPRAS_PRODUTO.PEDIDO
--LEFT JOIN ESTOQUE_PROD_ENT EPE ON EPE.PEDIDO=COMPRAS.PEDIDO 

 WHERE (dbo.PRODUTOS_PRECOS.CODIGO_TAB_PRECO = '01') AND (dbo.COMPRAS_PRODUTO.ENTREGA > '20250101') AND (PRODUTOS.GRIFFE = 'INFANTIL')
 and isnull(dbo.PRODUTOS.ERP_DESC_LICENCIADO,'')<>''


 /*
 SELECT EPE.PEDIDO, ENT.NATUREZA, ENT.NOME_CLIFOR, ENT.NF_ENTRADA, ENT.SERIE_NF_ENTRADA, ENT.RECEBIMENTO, 
	ENT.VALOR_SUB_ITENS as VALOR_BRUTO,ENT.DESCONTO,
	E_1.BASE_IMPOSTO AS BASE_ICMS, E_1.VALOR_IMPOSTO AS VALOR_ICMS, E_1.TAXA_IMPOSTO,
	E_2.BASE_IMPOSTO AS BASE_IPI, E_2.VALOR_IMPOSTO AS VALOR_IPI, E_2.TAXA_IMPOSTO,
	E_5.BASE_IMPOSTO AS BASE_PIS, E_5.VALOR_IMPOSTO AS VALOR_PIS,E_5.TAXA_IMPOSTO,
	E_6.BASE_IMPOSTO AS BASE_COFINS, E_6.VALOR_IMPOSTO AS VALOR_COFINS,E_6.TAXA_IMPOSTO,
	E_12.BASE_IMPOSTO AS BASE_ICMS_ST, E_12.VALOR_IMPOSTO AS VALOR_ICMS_ST,E_12.TAXA_IMPOSTO
 FROM ESTOQUE_PROD_ENT EPE
 INNER JOIN ENTRADAS ENT ON ENT.NF_ENTRADA=EPE.NF_ENTRADA AND ENT.SERIE_NF_ENTRADA=EPE.SERIE_NF_ENTRADA AND ENT.NOME_CLIFOR=EPE.NOME_CLIFOR

 LEFT JOIN ENTRADAS_IMPOSTO E_1 
	ON E_1.nome_clifor = EPE.NOME_CLIFOR    
		AND E_1.nf_entrada = EPE.NF_ENTRADA
		AND E_1.serie_nf_entrada = EPE.SERIE_NF_ENTRADA
		AND E_1.ID_IMPOSTO=1

 LEFT JOIN ENTRADAS_IMPOSTO E_2 
	ON E_2.nome_clifor = EPE.NOME_CLIFOR    
		AND E_2.nf_entrada = EPE.NF_ENTRADA
		AND E_2.serie_nf_entrada = EPE.SERIE_NF_ENTRADA
		AND E_2.ID_IMPOSTO=2

 LEFT JOIN ENTRADAS_IMPOSTO E_5 
	ON E_5.nome_clifor = EPE.NOME_CLIFOR    
		AND E_5.nf_entrada = EPE.NF_ENTRADA
		AND E_5.serie_nf_entrada = EPE.SERIE_NF_ENTRADA
		AND E_5.ID_IMPOSTO=5

 LEFT JOIN ENTRADAS_IMPOSTO E_6 
	ON E_6.nome_clifor = EPE.NOME_CLIFOR    
		AND E_6.nf_entrada = EPE.NF_ENTRADA
		AND E_6.serie_nf_entrada = EPE.SERIE_NF_ENTRADA
		AND E_6.ID_IMPOSTO=6

 LEFT JOIN ENTRADAS_IMPOSTO E_12 
	ON E_12.nome_clifor = EPE.NOME_CLIFOR    
		AND E_12.nf_entrada = EPE.NF_ENTRADA
		AND E_12.serie_nf_entrada = EPE.SERIE_NF_ENTRADA
		AND E_12.ID_IMPOSTO=12

 WHERE ENT.NATUREZA='200.01' 
	--AND  EPE.nome_clifor = 'S4 CONFECÇÕES LTDA ME' AND EPE.nf_entrada = '000006782' AND EPE.serie_nf_entrada = '001'
	AND PEDIDO='329880'
	FOR JSON AUTO

*/





