alter table CAEDU_RESERVA_AUTOMATICA 
ADD DATA_UNOUS DATETIME NULL
GO

ALTER TABLE CAEDU_RESERVA_AUTOMATICA_PACK_WMS
ADD DATA_UNOUS DATETIME NULL
GO

UPDATE CAEDU_RESERVA_AUTOMATICA
SET DATA_UNOUS = DATA 
GO

UPDATE CAEDU_RESERVA_AUTOMATICA_PACK_WMS
SET DATA_UNOUS = DATA 
GO
