SELECT
dbo.COMPRAS_PRODUTO.PEDIDO,
dbo.COMPRAS.ERP_CUPS_SEGMENTO,
dbo.COMPRAS.FORNECEDOR,
dbo.PRODUTOS.REFER_FABRICANTE,
dbo.COMPRAS_PRODUTO.PRODUTO,
dbo.PRODUTOS.DESC_PRODUTO,
dbo.PRODUTOS.GRIFFE,
dbo.PRODUTOS.LINHA,
dbo.PRODUTOS.GRUPO_PRODUTO,
dbo.PRODUTOS.SUBGRUPO_PRODUTO,
FORMAT(dbo.COMPRAS.CADASTRAMENTO, 'dd/MM/yyyy') AS CADASTRAMENTO,
FORMAT(dbo.COMPRAS_PRODUTO.ENTREGA, 'dd/MM/yyyy') AS ENTREGA,
FORMAT(dbo.COMPRAS_PRODUTO.LIMITE_ENTREGA, 'dd/MM/yyyy') AS LIMITE_ENTREGA,
FORMAT((SELECT MIN(emissao) FROM ESTOQUE_PROD_ENT WHERE pedido = dbo.COMPRAS.pedido), 'dd/MM/yyyy') AS DATA_RECEBIMENTO,
dbo.COMPRAS_PRODUTO.CUSTO1,
dbo.PRODUTOS_PRECOS.PRECO1,
dbo.COMPRAS_PRODUTO.QTDE_ORIGINAL,
dbo.COMPRAS_PRODUTO.QTDE_CANCELADA,
dbo.COMPRAS_PRODUTO.QTDE_ENTREGUE,
dbo.COMPRAS_PRODUTO.QTDE_ENTREGAR,
dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.QTDE as Total_PACK,
dbo.COMPRAS.FILIAL_A_ENTREGAR,
dbo.cadastro_cli_for.UF,
dbo.COMPRAS.REQUERIDO_POR,
dbo.PRODUTOS.TIPO_PRODUTO,
dbo.COMPRAS.TIPO_COMPRA,
dbo.PRODUTOS.COLECAO,
dbo.COLECOES.DESC_COLECAO,
(select top 1 DESCRICAO from dbo.CAEDU_LISTA_COMBO where codigo = dbo.PRODUTOS.ERP_CUPS_EVENTO) as DESC_EVENTO,
dbo.PRODUTOS.FATOR_P,
CASE dbo.COMPRAS.STATUS_COMPRA
       WHEN '01'     THEN 'APROVADO'
       WHEN '02'     THEN 'EM ESTUDO'
       WHEN '03'     THEN 'REPROVADO'
       WHEN '04'     THEN 'AGUARDANDO SENHA'
       ELSE ''
END  AS 'STATUS_PEDIDO'
,ISNULL((SELECT TOP 1 ISNULL(VALOR_PROPRIEDADE,'') AS VALOR_PROPRIEDADE
FROM PROP_PRODUTOS WHERE PROPRIEDADE = '00114' AND PRODUTO = COMPRAS_PRODUTO.PRODUTO),'') AS CAMPANHA_CARTAO,
dbo.COMPRAS_PRODUTO.COR_PRODUTO,
(select top 1 DESC_COR_PRODUTO from dbo.PRODUTO_CORES where cor = dbo.COMPRAS_PRODUTO.COR_PRODUTO and PRODUTO = dbo.COMPRAS_PRODUTO.PRODUTO) as DESC_COR,
dbo.PRODUTOS.ERP_DESC_LICENCIADO AS LICENCIADOR,
COALESCE(ERP_TEMA_LICENCIADO, '') AS "LICENCIADO",
dbo.COND_ENT_PGTOS.DESC_COND_PGTO,
dbo.PRODUTOS.CLASSIF_FISCAL,
dbo.PRODUTOS_CATEGORIA.CATEGORIA_PRODUTO,
dbo.PRODUTOS.TRIBUT_ORIGEM,
dbo.PRODUTOS.ERP_GRUPO_MERCADORIA,
dbo.COMPRAS.ERP_CAB_COD_CABIDE,
dbo.COMPRAS.ERP_CAB_QTDPECAS,
dbo.COMPRAS.ERP_CAB_STATUS,
FORMAT(dbo.COMPRAS.ERP_CAB_DATA_ENVIO, 'dd/MM/yyyy') AS ERP_CAB_DATA_ENVIO,
CASE COMPRAS.ERP_CAB_COD_BOLACHA
       WHEN 'E1'     THEN '1 ALARME'
       WHEN 'E2'     THEN '2 ALARMES'
       WHEN ''     THEN 'NENHUM'
       ELSE ''
END  AS 'QTD ALARME',
CASE COMPRAS.ERP_CAB_OPCAO
       WHEN '1'     THEN 'NENHUM'
       WHEN '2'     THEN 'SÓ CABIDE'
       WHEN '3'     THEN 'SÓ ALARME'
       WHEN '4'     THEN 'CABIDE+ALARME'
       ELSE ''
END  AS 'OPCAO_CABIDE'
,COALESCE(CAST(id_modelagem AS CHAR(5)),'')  AS "ID MODELAGEM"
,case produtos.CONTINUIDADE
when 1 THEN 'CONTINUO'
when 2 THEN 'SEMI-CONTINUO'
when 3 THEN 'DESCONTINUO'
else ''
end as CONTINUO,
ISNULL((SELECT TOP 1 ISNULL(VALOR_PROPRIEDADE,'') AS VALOR_PROPRIEDADE
       FROM PROP_COMPRAS WHERE PROPRIEDADE = '00093' AND PEDIDO = COMPRAS.PEDIDO),'') AS BONIFICACAO,
ISNULL((SELECT TOP 1 ISNULL(VALOR_PROPRIEDADE,'') AS VALOR_PROPRIEDADE
       FROM PROP_COMPRAS WHERE PROPRIEDADE = '00095' AND PEDIDO = COMPRAS.PEDIDO),'') AS PRONTA_ENTREGA,
CGP_UNOUS_ENVIAR_TODAS_LOJAS_PEDIDO = ISNULL((select VALOR_PROPRIEDADE from PROP_COMPRAS where propriedade = '00106' AND PEDIDO = COMPRAS.PEDIDO),'NÃO'),
CGP_UNOUS_ALOCAR_PRODUTO = ISNULL((SELECT VALOR_PROPRIEDADE FROM PROP_PRODUTOS WHERE PROPRIEDADE = '00108' AND PRODUTO = PRODUTOS.PRODUTO),'NÃO'),
ISNULL((SELECT TOP 1 ISNULL(VALOR_PROPRIEDADE,'') AS VALOR_PROPRIEDADE
       FROM PROP_COMPRAS WHERE PROPRIEDADE = '00111' AND PEDIDO = COMPRAS.PEDIDO),'') AS DATA_ORIGINAL,
ISNULL((SELECT TOP 1 ISNULL(VALOR_PROPRIEDADE,'') AS VALOR_PROPRIEDADE
       FROM PROP_COMPRAS WHERE PROPRIEDADE = '00112' AND PEDIDO = COMPRAS.PEDIDO),'') AS JUSTIFICATIVA,
ISNULL((SELECT TOP 1 ISNULL(VALOR_PROPRIEDADE,'') AS VALOR_PROPRIEDADE
       FROM PROP_COMPRAS WHERE PROPRIEDADE = '00110' AND PEDIDO = COMPRAS.PEDIDO),'') AS E_COMMERCE
,DBO.PRODUTOS.ERP_FT_DESC_CLASSIFICACAO AS CLASSIFICACAO
,compras.DESCONTO,
COMPRAS.ERP_CUPS_PROCESSO_CCF_CCA,
COMPRAS.PEDIDO_FORNECEDOR,
PRODUTOS.ERP_CUPS_SUPPLIER,
ccf.FORNECEDOR as [SUPPLIER (PRODUTO)],
FORMAT(COMPRAS.ERP_CUPS_EMBARQUE_ATUAL, 'dd/MM/yyyy') AS ERP_CUPS_EMBARQUE_ATUAL,
FORMAT(COMPRAS.ERP_CUPS_EMBARQUE_REAL, 'dd/MM/yyyy') as [EMBARQUE REAL (ETD)],
COMPRAS_PRODUTO.ERP_CUPS_CUSTO_FOB as [CUSTO FOB (US$)],
DESC_COND_PGTO,
ERP_CUPS_CONTRATO,
RTRIM(LTRIM(convert(VARCHAR(250), dbo.COMPRAS.OBS))) as OBS,
PRODUTOS.GRADE,
FORMAT(COMPRAS.ERP_CUPS_DATA_ACORDADA, 'dd/MM/yyyy') AS ERP_CUPS_DATA_ACORDADA,
FORMAT(COMPRAS.ERP_CUPS_CHEGADA_PORTO, 'dd/MM/yyyy') AS ERP_CUPS_CHEGADA_PORTO,
FORMAT(COMPRAS.ERP_CUPS_CHEGADA_CD, 'dd/MM/yyyy') AS ERP_CUPS_CHEGADA_CD,
COMPRAS_PRODUTO.ERP_CUPS_CUSTO_FOB_MINIMO,
PRODUTOS.ERP_CUPS_STYLENUMBER,
PRODUTOS.ERP_LICENCIADO,
COMPRAS_PRODUTO.ERP_CUPS_PACKS_POR_CAIXA,
/* INICIO - JIRA SI-825 - PAULO DEVIDE 05-11-2025 */
ENT.NF_ENTRADA, ENT.SERIE_NF_ENTRADA, ENT.NOME_CLIFOR AS FORNECEDOR_NF, 
FORMAT(ENT.RECEBIMENTO, 'dd/MM/yyyy') AS DT_ENTREGA_NF,
ENT.CUSTO1 AS CUSTO_NF
/* FIM - JIRA SI-825 - PAULO DEVIDE 05-11-2025 */

FROM            dbo.COMPRAS_PRODUTO
INNER JOIN
                dbo.PRODUTOS 
                    ON dbo.COMPRAS_PRODUTO.PRODUTO = dbo.PRODUTOS.PRODUTO
INNER JOIN
                dbo.PRODUTOS_PRECOS 
                    ON dbo.PRODUTOS.PRODUTO = dbo.PRODUTOS_PRECOS.PRODUTO 
                    and dbo.PRODUTOS_PRECOS.CODIGO_TAB_PRECO = '01'
INNER JOIN
                dbo.COLECOES 
                    ON DBO.COLECOES.COLECAO = DBO.PRODUTOS.COLECAO
INNER JOIN
                dbo.COMPRAS 
                    ON dbo.COMPRAS_PRODUTO.PEDIDO = dbo.COMPRAS.PEDIDO
INNER JOIN
                dbo.PRODUTOS_CATEGORIA  
                    ON dbo.PRODUTOS.COD_CATEGORIA    = dbo.PRODUTOS_CATEGORIA.COD_CATEGORIA
INNER JOIN
                dbo.COND_ENT_PGTOS 
                    ON dbo.COMPRAS.CONDICAO_PGTO = dbo.COND_ENT_PGTOS.CONDICAO_PGTO
INNER JOIN
                dbo.cadastro_cli_for 
                    on compras.fornecedor=cadastro_cli_for.nome_clifor
LEFT JOIN
                dbo.FORNECEDORES ccf 
                    on ccf.clifor = produtos.ERP_CUPS_SUPPLIER
INNER JOIN
                dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL 
                    ON dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.PEDIDO = dbo.COMPRAS_PRODUTO.PEDIDO
/* INICIO - JIRA SI-825 - PAULO DEVIDE 05-11-2025 */
LEFT JOIN       (SELECT EPE1.PEDIDO, EPE1.NF_ENTRADA, EPE1.SERIE_NF_ENTRADA,  
                    EPE1.NOME_CLIFOR, E2.RECEBIMENTO, EPE2.PRODUTO, EPE2.COR_PRODUTO,
                    EPE2.CUSTO1
                    FROM ESTOQUE_PROD_ENT EPE1 
                    INNER JOIN ENTRADAS E2 
                        ON E2.NF_ENTRADA=EPE1.NF_ENTRADA 
                            AND E2.SERIE_NF_ENTRADA=EPE1.SERIE_NF_ENTRADA
                            AND E2.NOME_CLIFOR=EPE1.NOME_CLIFOR
                    INNER JOIN ESTOQUE_PROD1_ENT EPE2 
                        ON EPE2.ROMANEIO_PRODUTO=EPE1.ROMANEIO_PRODUTO
                            AND EPE2.FILIAL=EPE1.FILIAL
                ) AS ENT 
                    ON ENT.PEDIDO = dbo.COMPRAS_PRODUTO.PEDIDO 
                        AND ENT.PRODUTO = dbo.COMPRAS_PRODUTO.PRODUTO
                        AND ENT.COR_PRODUTO = dbo.COMPRAS_PRODUTO.COR_PRODUTO
/* FIM - JIRA SI-825 - PAULO DEVIDE 05-11-2025 */

WHERE (dbo.COMPRAS_PRODUTO.ENTREGA > 44562)
