select A.PEDIDO, CAST(A.EMISSAO AS DATE) EMISSAO, A.TIPO_COMPRA, A.FORNECEDOR, A.FILIAL_A_ENTREGAR, 
		B.PRODUTO, B.COR_PRODUTO, CAST(B.ENTREGA AS DATE) ENTREGA, CAST(B.LIMITE_ENTREGA AS DATE) LIMITE_ENTREGA , 
		CAST(A.TOT_QTDE_ENTREGAR AS INT) TOT_QTDE_ENTREGAR, 
		CAST(A.TOT_QTDE_ORIGINAL AS INT) TOT_QTDE_ORIGINAL, 
		cast(TOT_VALOR_ORIGINAL as money) as TOT_VALOR_ORIGINAL,
		DESCONTO, A.CTB_TIPO_OPERACAO
from compras a
inner join compras_produto b on b.pedido = a.pedido
where b.ENTREGA>='20220701' and a.FORNECEDOR<>'KOMPORT' 
		AND A.TIPO_COMPRA<>'E-COMMERCE' AND A.TOT_QTDE_ENTREGAR=A.TOT_QTDE_ORIGINAL
ORDER BY EMISSAO ASC




