SELECT     
dbo.COMPRAS_PRODUTO.PEDIDO, 
dbo.COMPRAS.ERP_CUPS_SEGMENTO, 
dbo.COMPRAS.FORNECEDOR, 
dbo.COMPRAS.CADASTRAMENTO,
dbo.PRODUTOS.REFER_FABRICANTE,
dbo.PRODUTOS.ERP_GRUPO_MERCADORIA,
dbo.COMPRAS.REQUERIDO_POR,
dbo.COMPRAS.TIPO_COMPRA,
dbo.COMPRAS_PRODUTO.PRODUTO, 
dbo.COMPRAS_PRODUTO.COR_PRODUTO,
dbo.PRODUTOS.GRIFFE, 
dbo.PRODUTOS.LINHA, 
dbo.PRODUTOS.GRUPO_PRODUTO, 
dbo.PRODUTOS.SUBGRUPO_PRODUTO, 
dbo.PRODUTOS.REFER_FABRICANTE,
dbo.COMPRAS_PRODUTO.OBS_ITEM,
dbo.PRODUTOS.CLASSIF_FISCAL,
dbo.PRODUTOS.DESC_PRODUTO, 
dbo.PRODUTOS.TIPO_PRODUTO, 
dbo.PRODUTOS.COLECAO, 
dbo.PRODUTOS.FATOR_P, 
dbo.COMPRAS.OBS, 
dbo.COMPRAS_PRODUTO.ENTREGA, 
dbo.COMPRAS_PRODUTO.LIMITE_ENTREGA, 
dbo.COND_ENT_PGTOS.DESC_COND_PGTO, 
dbo.COMPRAS_PRODUTO.CUSTO1, 
dbo.PRODUTOS_PRECOS.PRECO1, 
prc_at.preco1 as Preco__Base,
prc_va.preco1 as Preco_Tabela,
dbo.COMPRAS_PRODUTO.QTDE_ORIGINAL, 
dbo.COMPRAS_PRODUTO.QTDE_CANCELADA, 
dbo.COMPRAS_PRODUTO.QTDE_ENTREGUE, 
dbo.COMPRAS_PRODUTO.QTDE_ENTREGAR, 
dbo.COMPRAS_PRODUTO.DATA_CONFIRMACAO, 
dbo.COLECOES.DESC_COLECAO,
dbo.PRODUTOS_CATEGORIA.CATEGORIA_PRODUTO,
dbo.PRODUTOS.TRIBUT_ORIGEM,
dbo.COMPRAS.FILIAL_A_ENTREGAR,
dbo.cadastro_cli_for.UF,
dbo.COMPRAS.ERP_CAB_COD_CABIDE,
dbo.COMPRAS.ERP_CAB_QTDPECAS,
dbo.COMPRAS.ERP_CAB_ENCABIDADO,
dbo.COMPRAS.ERP_CAB_DATA_ENVIO
, CASE dbo.COMPRAS.STATUS_COMPRA 
       WHEN '01'     THEN 'APROVADO'                 
       WHEN '02'     THEN 'EM ESTUDO'                
       WHEN '03'     THEN 'REPROVADO'                
       WHEN '04'     THEN 'AGUARDANDO SENHA'
       ELSE ''
END  AS 'STATUS_PEDIDO'
,(select max(emissao) from ESTOQUE_PROD_ENT where pedido = dbo.COMPRAS.pedido) as DATA_RECEBIMENTO
,COALESCE(CAST(id_modelagem AS CHAR(5)),'')  AS "ID MODELAGEM"
,COALESCE(ERP_TEMA_LICENCIADO, '') AS "LICENCIADO"
,case produtos.CONTINUIDADE
when 1 THEN 'CONTINUO'
when 2 THEN 'SEMI-CONTINUO'
when 3 THEN 'DESCONTINUO'
else ''
end as CONTINUO,
ISNULL((SELECT TOP 1 ISNULL(VALOR_PROPRIEDADE,'') AS VALOR_PROPRIEDADE 
	FROM PROP_COMPRAS WHERE PROPRIEDADE = '00093' AND PEDIDO = COMPRAS.PEDIDO),'') AS BONIFICACAO

FROM         dbo.COMPRAS_PRODUTO INNER JOIN
                      dbo.PRODUTOS ON dbo.COMPRAS_PRODUTO.PRODUTO = dbo.PRODUTOS.PRODUTO INNER JOIN
                      dbo.PRODUTOS_PRECOS ON dbo.PRODUTOS.PRODUTO = dbo.PRODUTOS_PRECOS.PRODUTO INNER JOIN
                      dbo.COLECOES ON DBO.COLECOES.COLECAO = DBO.PRODUTOS.COLECAO INNER JOIN
                      dbo.COMPRAS ON dbo.COMPRAS_PRODUTO.PEDIDO = dbo.COMPRAS.PEDIDO INNER JOIN
                      dbo.PRODUTOS_CATEGORIA  ON dbo.PRODUTOS.COD_CATEGORIA    = dbo.PRODUTOS_CATEGORIA.COD_CATEGORIA INNER JOIN
                      dbo.COND_ENT_PGTOS ON dbo.COMPRAS.CONDICAO_PGTO = dbo.COND_ENT_PGTOS.CONDICAO_PGTO
INNER JOIN dbo.cadastro_cli_for on compras.fornecedor=cadastro_cli_for.nome_clifor 
LEFT    JOIN  dbo.PRODUTOS_PRECOS prc_at   ON dbo.PRODUTOS.PRODUTO          = prc_at.PRODUTO and prc_at.CODIGO_TAB_PRECO = 'AT'
LEFT    JOIN  dbo.PRODUTOS_PRECOS prc_va   ON dbo.PRODUTOS.PRODUTO          = prc_va.PRODUTO and prc_va.CODIGO_TAB_PRECO = 'VA'

WHERE     (dbo.PRODUTOS_PRECOS.CODIGO_TAB_PRECO = '01') AND (dbo.PRODUTOS.GRIFFE = 'MASCULINO') AND  (dbo.COMPRAS_PRODUTO.ENTREGA > 42005)

