SELECT ALOC.GRIFFE,ALOC.LINHA,ALOC.GRUPO_PRODUTO,ALOC.SUBGRUPO_PRODUTO,ALOC.UNOUS_NIVEL,ALOC.PRODUTO,ALOC.VALOR_PROPRIEDADE,ALOC.UNOUS_ALOCAR,ALOC.COR_PRODUTO
                FROM(SELECT ALOC.GRIFFE,ALOC.LINHA,ALOC.GRUPO_PRODUTO,ALOC.SUBGRUPO_PRODUTO,ALOC.UNOUS_NIVEL,ALOC.PRODUTO,MAX(ALOC.VALOR_PROPRIEDADE) AS VALOR_PROPRIEDADE,ALOC.UNOUS_ALOCAR,MAX(PC.COR_PRODUTO) AS COR_PRODUTO
                        FROM CAEDU.DBO.UNOUS_LINX_MAT_ALOC ALOC  WITH (NOLOCK)
                            INNER JOIN CAEDU.DBO.PRODUTO_CORES PC WITH (NOLOCK)    ON ALOC.PRODUTO = PC.PRODUTO AND ALOC.VALOR_PROPRIEDADE = PC.DESC_COR_PRODUTO
                            WHERE 1 = 1
                            AND ALOC.UNOUS_NIVEL = 'COR'
                            GROUP BY ALOC.GRIFFE,ALOC.LINHA,ALOC.GRUPO_PRODUTO,ALOC.SUBGRUPO_PRODUTO,ALOC.UNOUS_NIVEL,ALOC.PRODUTO,ALOC.UNOUS_ALOCAR
                    UNION
                        SELECT ALOC.GRIFFE,ALOC.LINHA,ALOC.GRUPO_PRODUTO,ALOC.SUBGRUPO_PRODUTO,ALOC.UNOUS_NIVEL,ALOC.PRODUTO,MAX(ALOC.VALOR_PROPRIEDADE) AS VALOR_PROPRIEDADE,ALOC.UNOUS_ALOCAR,MAX(PC.COR_PRODUTO) AS COR_PRODUTO
                        FROM CAEDU.DBO.UNOUS_LINX_MAT_ALOC ALOC  WITH (NOLOCK)
                            INNER JOIN CAEDU.DBO.PRODUTO_CORES PC WITH (NOLOCK) ON ALOC.PRODUTO = PC.PRODUTO               
                        WHERE 1 = 1    
                            AND ALOC.UNOUS_NIVEL != 'COR'
                        GROUP BY ALOC.GRIFFE,ALOC.LINHA,ALOC.GRUPO_PRODUTO,ALOC.SUBGRUPO_PRODUTO,ALOC.UNOUS_NIVEL,ALOC.PRODUTO,ALOC.UNOUS_ALOCAR) ALOC



SELECT ALOC.GRIFFE,ALOC.LINHA,ALOC.GRUPO_PRODUTO,ALOC.SUBGRUPO_PRODUTO,ALOC.UNOUS_NIVEL,ALOC.PRODUTO,MAX(ALOC.VALOR_PROPRIEDADE) AS VALOR_PROPRIEDADE,ALOC.UNOUS_ALOCAR,MAX(PC.COR_PRODUTO) AS COR_PRODUTO
                        FROM CAEDU.DBO.UNOUS_LINX_MAT_ALOC ALOC  WITH (NOLOCK)
                            INNER JOIN CAEDU.DBO.PRODUTO_CORES PC WITH (NOLOCK) ON ALOC.PRODUTO = PC.PRODUTO               
                        WHERE 1 = 1    AND ALOC.PRODUTO = '02021201'
                           -- AND ALOC.UNOUS_NIVEL != 'COR'
                        GROUP BY ALOC.GRIFFE,ALOC.LINHA,ALOC.GRUPO_PRODUTO,ALOC.SUBGRUPO_PRODUTO,ALOC.UNOUS_NIVEL,ALOC.PRODUTO,ALOC.UNOUS_ALOCAR            


						SELECT * FROM CAEDU.DBO.UNOUS_LINX_MAT_ALOC WHERE PRODUTO = '02021201'
