SELECT  dbo.COMPRAS_PRODUTO.PEDIDO,
dbo.PRODUTOS.ERP_DESC_LICENCIADO AS LICENCIADOR,
dbo.PRODUTOS.ERP_TEMA_LICENCIADO AS PERSONAGEM,
dbo.COMPRAS.FORNECEDOR,
dbo.cadastro_cli_for.cgc_cpf,
dbo.cadastro_cli_for.uf,
dbo.cadastro_cli_for.Razao_Social,
dbo.cadastro_cli_for.cidade,
dbo.COMPRAS.TIPO_COMPRA,                
dbo.COMPRAS_PRODUTO.PRODUTO,
dbo.PRODUTOS.GRIFFE, 
dbo.PRODUTOS.LINHA,
dbo.PRODUTOS.GRUPO_PRODUTO, 
dbo.PRODUTOS.SUBGRUPO_PRODUTO, 
dbo.PRODUTOS.DESC_PRODUTO, 
dbo.PRODUTOS.ERP_GRUPO_MERCADORIA,
dbo.PRODUTOS.TIPO_PRODUTO,
dbo.COMPRAS_PRODUTO.ENTREGA, 
dbo.COMPRAS_PRODUTO.LIMITE_ENTREGA,
AVG (dbo.COMPRAS_PRODUTO.CUSTO1) AS "PR CUSTO" , 
AVG (dbo.PRODUTOS_PRECOS.PRECO1) AS "PR VENDA", 
SUM (dbo.COMPRAS_PRODUTO.QTDE_ORIGINAL) AS "QTDE_ORIGINAL" ,                          
SUM (dbo.COMPRAS_PRODUTO.QTDE_CANCELADA) AS "QTDE_CANCELADA", 
SUM (dbo.COMPRAS_PRODUTO.QTDE_ENTREGUE) AS "QTDE_ENTREGUE",                       
SUM (dbo.COMPRAS_PRODUTO.QTDE_ENTREGAR) AS "QTDE ENTREGAR", 
dbo.COLECOES.DESC_COLECAO,
dbo.PRODUTOS.FATOR_P, dbo.PRODUTOS.FATOR_F, 
dbo.COMPRAS.FILIAL_A_ENTREGAR, 
dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.QTDE , 
dbo.COMPRAS.ERP_CAB_ENCABIDADO,  
dbo.COMPRAS.ERP_CAB_COD_CABIDE,
dbo.COMPRAS.ERP_CUPS_SEGMENTO,
dbo.COMPRAS.CADASTRAMENTO,
dbo.COMPRAS.REQUERIDO_POR,
dbo.PRODUTOS.TRIBUT_ORIGEM
, CASE dbo.COMPRAS.STATUS_COMPRA 
       WHEN '01'     THEN 'APROVADO'                 
       WHEN '02'     THEN 'EM ESTUDO'                
       WHEN '03'     THEN 'REPROVADO'                
       WHEN '04'     THEN 'AGUARDANDO SENHA'
       ELSE ''
END  AS 'STATUS_PEDIDO'
, max(z.RECEBIMENTO) as RECEBIMENTO 
FROM dbo.COMPRAS_PRODUTO     
INNER JOIN dbo.PRODUTOS ON dbo.COMPRAS_PRODUTO.PRODUTO = dbo.PRODUTOS.PRODUTO   
INNER JOIN dbo.PRODUTOS_PRECOS ON dbo.PRODUTOS.PRODUTO = dbo.PRODUTOS_PRECOS.PRODUTO   
INNER JOIN DBO.COLECOES ON DBO.COLECOES.COLECAO = DBO.PRODUTOS.COLECAO   
INNER JOIN dbo.COMPRAS ON dbo.COMPRAS_PRODUTO.PEDIDO = dbo.COMPRAS.PEDIDO   
INNER JOIN dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL  ON dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.PEDIDO = dbo.COMPRAS_PRODUTO.PEDIDO  
INNER JOIN dbo.cadastro_cli_for on compras.fornecedor=cadastro_cli_for.nome_clifor    

LEFT  JOIN (select pedido,RECEBIMENTO 
 FROM ENTRADAS e
 INNER JOIN ESTOQUE_PROD_ENT a 
 ON a.NF_ENTRADA=e.NF_ENTRADA and a.SERIE_NF_ENTRADA=e.SERIE_NF_ENTRADA and a.NOME_CLIFOR=e.NOME_CLIFOR
) z ON z.PEDIDO = COMPRAS.PEDIDO

WHERE     (dbo.PRODUTOS_PRECOS.CODIGO_TAB_PRECO = '01') and (dbo.COMPRAS_PRODUTO.ENTREGA >44562)

GROUP BY   dbo.COMPRAS_PRODUTO.PEDIDO, 
dbo.PRODUTOS.ERP_DESC_LICENCIADO,
dbo.PRODUTOS.ERP_TEMA_LICENCIADO,
dbo.COMPRAS.FORNECEDOR,dbo.cadastro_cli_for.cgc_cpf, 
dbo.cadastro_cli_for.uf,
dbo.cadastro_cli_for.razao_social,
dbo.cadastro_cli_for.cidade,
dbo.COMPRAS.TIPO_COMPRA,                                
dbo.COMPRAS_PRODUTO.PRODUTO, 
dbo.PRODUTOS.GRIFFE, dbo.PRODUTOS.LINHA,                   
dbo.PRODUTOS.GRUPO_PRODUTO, 
dbo.PRODUTOS.SUBGRUPO_PRODUTO, 
dbo.PRODUTOS.ERP_GRUPO_MERCADORIA,
dbo.PRODUTOS.DESC_PRODUTO, 
dbo.PRODUTOS.TIPO_PRODUTO,                            
dbo.COMPRAS_PRODUTO.ENTREGA, 
dbo.COMPRAS_PRODUTO.LIMITE_ENTREGA,                    
dbo.COLECOES.DESC_COLECAO, dbo.PRODUTOS.FATOR_P, 
dbo.PRODUTOS.FATOR_F, 
dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.QTDE, 
dbo.COMPRAS.FILIAL_A_ENTREGAR, 
dbo.COMPRAS.ERP_CAB_ENCABIDADO,  
dbo.COMPRAS.ERP_CAB_COD_CABIDE,
dbo.COMPRAS.ERP_CUPS_SEGMENTO,
dbo.COMPRAS.CADASTRAMENTO,
dbo.COMPRAS.REQUERIDO_POR,
dbo.COMPRAS.STATUS_COMPRA,
dbo.PRODUTOS.TRIBUT_ORIGEM
