SELECT *
FROM (
SELECT DISTINCT --TOP (?)                                                   
    LTRIM(RTRIM(P.PRODUTO)) AS COD_MERCADORIA
    ,P.DESC_PRODUTO AS DESCRICAO
    ,P.DESC_PROD_NF AS DESCRICAO_ABR       
    ,PGF.COD_GRIFFE AS COD_GRIFFE
    ,PGF.GRIFFE AS GRIFFE
    ,PL.COD_LINHA AS COD_LINHA
    ,PL.LINHA AS LINHA
    ,PG.CODIGO_GRUPO AS CODIGO_GRUPO
    ,PG.GRUPO_PRODUTO AS GRUPO     
    ,PSG.CODIGO_SUBGRUPO AS CODIGO_SUBGRUPO
    ,PSG.SUBGRUPO_PRODUTO AS SUBGRUPO      
    ,LEFT(RTRIM(ALOC.VALOR_PROPRIEDADE),3)+RIGHT(RTRIM(ALOC.VALOR_PROPRIEDADE),2)+CAST(LEN(ALOC.VALOR_PROPRIEDADE) AS VARCHAR(10)) AS UNOUS_NIVEL
    ,ISNULL(ALOC.VALOR_PROPRIEDADE, 'P1/P2') AS VALOR_PROPRIEDADE      
    ,FORN.COD_CLIFOR                                                
FROM CAEDU.DBO.PRODUTOS P WITH (NOLOCK)       
    INNER JOIN CAEDU.DBO.PRODUTOS_GRIFFES  PGF WITH (NOLOCK)    ON P.GRIFFE = PGF.GRIFFE
    INNER JOIN CAEDU.DBO.PRODUTOS_LINHAS PL WITH (NOLOCK)       ON P.LINHA = PL.LINHA
    INNER JOIN CAEDU.DBO.PRODUTOS_GRUPO PG WITH (NOLOCK)        ON P.GRUPO_PRODUTO = PG.GRUPO_PRODUTO
    INNER JOIN CAEDU.DBO.PRODUTOS_SUBGRUPO PSG WITH (NOLOCK)    ON P.GRUPO_PRODUTO = PSG.GRUPO_PRODUTO  AND P.SUBGRUPO_PRODUTO = PSG.SUBGRUPO_PRODUTO           
    LEFT JOIN CAEDU.DBO.CADASTRO_CLI_FOR FORN WITH (NOLOCK)       ON P.FABRICANTE = FORN.NOME_CLIFOR
    LEFT JOIN (SELECT ALOC.GRIFFE,ALOC.LINHA,ALOC.GRUPO_PRODUTO,ALOC.SUBGRUPO_PRODUTO,ALOC.UNOUS_NIVEL,ALOC.PRODUTO,ALOC.VALOR_PROPRIEDADE,ALOC.UNOUS_ALOCAR,ALOC.COR_PRODUTO
                FROM(SELECT ALOC.GRIFFE,ALOC.LINHA,ALOC.GRUPO_PRODUTO,ALOC.SUBGRUPO_PRODUTO,ALOC.UNOUS_NIVEL,ALOC.PRODUTO,MAX(ALOC.VALOR_PROPRIEDADE) AS VALOR_PROPRIEDADE,ALOC.UNOUS_ALOCAR,MAX(PC.COR_PRODUTO) AS COR_PRODUTO
                        FROM CAEDU.DBO.UNOUS_LINX_MAT_ALOC ALOC  WITH (NOLOCK)
                            INNER JOIN CAEDU.DBO.PRODUTO_CORES PC WITH (NOLOCK)    ON ALOC.PRODUTO = PC.PRODUTO AND ALOC.VALOR_PROPRIEDADE = PC.DESC_COR_PRODUTO
                            WHERE 1 = 1
                            AND ALOC.UNOUS_NIVEL = 'COR'
                            GROUP BY ALOC.GRIFFE,ALOC.LINHA,ALOC.GRUPO_PRODUTO,ALOC.SUBGRUPO_PRODUTO,ALOC.UNOUS_NIVEL,ALOC.PRODUTO,ALOC.UNOUS_ALOCAR
                    UNION
                        SELECT ALOC.GRIFFE,ALOC.LINHA,ALOC.GRUPO_PRODUTO,ALOC.SUBGRUPO_PRODUTO,ALOC.UNOUS_NIVEL,ALOC.PRODUTO,MAX(ALOC.VALOR_PROPRIEDADE) AS VALOR_PROPRIEDADE,ALOC.UNOUS_ALOCAR,MAX(PC.COR_PRODUTO) AS COR_PRODUTO
                        FROM CAEDU.DBO.UNOUS_LINX_MAT_ALOC ALOC  WITH (NOLOCK)
                            INNER JOIN CAEDU.DBO.PRODUTO_CORES PC WITH (NOLOCK) ON ALOC.PRODUTO = PC.PRODUTO               
                        WHERE 1 = 1    
                            AND ALOC.UNOUS_NIVEL != 'COR'
                        GROUP BY ALOC.GRIFFE,ALOC.LINHA,ALOC.GRUPO_PRODUTO,ALOC.SUBGRUPO_PRODUTO,ALOC.UNOUS_NIVEL,ALOC.PRODUTO,ALOC.UNOUS_ALOCAR) ALOC
            ) ALOC
        ON ALOC.PRODUTO = P.PRODUTO
        AND ALOC.GRIFFE = PGF.GRIFFE   
        AND ALOC.LINHA = PL.LINHA
        AND ALOC.GRUPO_PRODUTO = PG.GRUPO_PRODUTO
        AND ALOC.SUBGRUPO_PRODUTO = PSG.SUBGRUPO_PRODUTO        
WHERE 1 = 1
) A
WHERE  UNOUS_NIVEL IS NULL


SELECT * FROM CAE_PRODUTOS_FATOR_P WHERE 
GRIFFE = 'MASCULINO' AND
LINHA = 'JOVEM' AND 
GRUPO_PRODUTO = 'TOP MALHA'
AND SUBGRUPO_PRODUTO = 'S/M'