

SELECT PEDIDO, FORNECEDOR, FILIAL_A_ENTREGAR, EMISSAO, ENTREGA, LIMITE_ENTREGA, TOT_QTDE_ENTREGAR, C.GRIFFE, C.LINHA, C.GRUPO_PRODUTO, C.SUBGRUPO_PRODUTO, C.PRODUTO, B.COR_PRODUTO,  
	RIGHT('00'+CONVERT(VARCHAR,B.TAMANHO),2) AS TAMANHO,B.CODIGO_BARRA, C.DESC_PRODUTO, UNPVT.QTY, H.PRECO1 AS CUSTO_TAB_00 
FROM (
SELECT produto, cor_produto, cp1.pedido, CAST(EMISSAO AS DATE) AS EMISSAO, CAST(ENTREGA AS DATE) AS ENTREGA, CAST(LIMITE_ENTREGA AS DATE) AS LIMITE_ENTREGA, FORNECEDOR, FILIAL_A_ENTREGAR, TOT_QTDE_ENTREGAR,
		ISNULL(co1,0) AS co01, ISNULL(co2,0) AS co02, ISNULL(co3,0) AS co03, ISNULL(co4,0) AS co04, ISNULL(co5,0) AS co05, ISNULL(co6,0) AS co06, ISNULL(co7,0) AS co07, ISNULL(co8,0) AS co08, 
		ISNULL(co9,0) AS co09, ISNULL(co10,0) AS co10, ISNULL(co11,0) AS co11, ISNULL(co12,0) AS co12, ISNULL(co13,0) AS co13, ISNULL(co14,0) AS co14, ISNULL(co15,0) AS co15, ISNULL(co16,0) AS co16
		FROM COMPRAS_PRODUTO CP1
		INNER JOIN COMPRAS C1 ON C1.PEDIDO = CP1.PEDIDO
		where C1.TOT_QTDE_ENTREGAR<>0 and cp1.QTDE_ORIGINAL<>0 and (c1.EMISSAO > DATEADD(DD,-390,GETDATE())) /*PEGA 13 MESES DE CARTEIRA*/
      ) p
		UNPIVOT
(QTY FOR tamanho IN (CO01, CO02, CO03, CO04, CO05, CO06, CO07, CO08, CO09, CO10, CO11, CO12, CO13, CO14, CO15, CO16) )AS unpvt
LEFT JOIN (
SELECT  PRODUTO, COR_PRODUTO, TAMANHO, MIN(CODIGO_BARRA) AS CODIGO_BARRA
FROM [CAEDU].[dbo].PRODUTOS_BARRA
GROUP BY PRODUTO, COR_PRODUTO, TAMANHO) B 
	ON B.PRODUTO = unpvt.PRODUTO AND B.COR_PRODUTO = unpvt.COR_PRODUTO 
			AND B.TAMANHO = substring(unpvt.tamanho,3,2)
LEFT join [CAEDU].[dbo].PRODUTOS as c on b.PRODUTO=c.PRODUTO
LEFT join PRODUTO_CORES as e on c.PRODUTO=e.PRODUTO and unpvt.COR_PRODUTO=e.COR_PRODUTO 
LEFT join produtos_precos as H on c.PRODUTO=h.PRODUTO where h.CODIGO_TAB_PRECO ='00'
ORDER BY PEDIDO

