
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER DBO.TGR_UPD_PROP_COMPRAS 
   ON  DBO.PROP_COMPRAS
   FOR UPDATE
AS 
BEGIN
	SET NOCOUNT ON;
	
	IF UPDATE(VALOR_PROPRIEDADE)
	BEGIN
		DECLARE @PROPRIEDADE VARCHAR(5), @VALOR_PROPRIEDADE VARCHAR(70),  @VALOR_PROPRIEDADE_ANTES VARCHAR(70)

		SELECT	@PROPRIEDADE = inserted.PROPRIEDADE, 
				@VALOR_PROPRIEDADE = inserted.VALOR_PROPRIEDADE,
				@VALOR_PROPRIEDADE_ANTES = DELETED.VALOR_PROPRIEDADE
		FROM inserted
		INNER JOIN deleted ON deleted.PEDIDO = inserted.PEDIDO AND INSERTED.PROPRIEDADE = DELETED.PROPRIEDADE

		IF @PROPRIEDADE = '00106' AND (@VALOR_PROPRIEDADE_ANTES <> @VALOR_PROPRIEDADE)
		BEGIN
			
			UPDATE A SET ERP_UNOUS_DATA_ENVIO = NULL
			FROM COMPRAS A
			INNER JOIN inserted B ON B.PEDIDO = A.PEDIDO

		END
	END

END
GO
