/* cadastro de linhas da planilha verifica integridade */
select *
from produtos_griffes
where griffe in (
'ACESSORIOS'
,'CALCADOS'
,'FEMININO'
,'INFANTIL'
,'INTIMA E PRAIA'
,'JEANS'
,'MASCULINO'
)

/* cadastro de linhas da planilha verifica integridade */
select * 
from produtos_linhas
where linha in (
'1/3 NAS'
,'1/3 NOS'
,'10/16 NAS'
,'10/16 NOS'
,'4/8 NAS'
,'4/8 NOS'
,'BASICO'
,'BASKET'
,'CASUAL'
,'CITY'
,'ESPORTE'
,'FEMININO'
,'FPM'
,'INFANTIL NAS'
,'INFANTIL NOS'
,'JOVEM'
,'MASCULINO'
,'SUPER')


/* cadastro de grupos da planilha verifica integridade */
select * 
from produtos_grupo
where grupo_produto in 
('BEBE'
,'BELEZA'
,'BIJUTERIA'
,'BOLSA'
,'BONE'
,'BOTA'
,'BOTTOM'
,'BOTTOM PROGRAMA'
,'BRINQUEDO'
,'CARNAVAL'
,'CASA'
,'CHINELO'
,'CINTO'
,'COMPLEMENTO'
,'CUECA'
,'ESCRITÓRIO'
,'GARRAFA'
,'INTEIRO'
,'INTEIRO PROGRAMA'
,'INVERNO'
,'INVERNO BOTTOM'
,'INVERNO BOTTOM PROGRAMA'
,'INVERNO INTEIRO'
,'INVERNO INTEIRO PROGRAMA'
,'INVERNO LINHA NOITE'
,'INVERNO TOP'
,'INVERNO TOP PROGRAMA'
,'LINGERIE'
,'LINHA DIA'
,'LINHA NOITE'
,'LINHA PRAIA'
,'MEIA'
,'MUSICA'
,'NECESSAIRE'
,'PAPEL PRESENTE'
,'PET'
,'SANDALIA'
,'SANDALIA BAIXA'
,'SANDALIA SALTO'
,'SAPATILHA'
,'SAUDE'
,'SCARPIN'
,'TENIS'
,'TOP'
,'TOP PROGRAMA'
,'VIAGEM')

/* cadastro de subgrupos da planilha - verifica integridade */
DECLARE @tabsubgrupo table (GRUPO_PRODUTO varchar(25),SUBGRUPO_PRODUTO varchar(25))
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BEBE','COMPLEMENTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BEBE','MEIA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BELEZA','BANHO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BELEZA','CABELO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BELEZA','CABELO INFANTIL')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BELEZA','ESCOVA DE CABELO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BELEZA','MAQUIAGEM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BIJUTERIA','BIJUTERIA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOLSA','BOLSA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOLSA','BOLSA/MOCHILA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BONE','BONE')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTA','BABY')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTA','BOTA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTA','KIDS')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM','BOTTOM JEANS CURTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM','BOTTOM JEANS CURTO 1/3')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM','BOTTOM JEANS CURTO 10/16')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM','BOTTOM JEANS CURTO 4/8')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM','BOTTOM JEANS CURTO MARCAS')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM','BOTTOM JEANS CURTO SUPER')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM','BOTTOM JEANS LONGO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM','BOTTOM JEANS LONGO 1/3')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM','BOTTOM JEANS LONGO 10/16')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM','BOTTOM JEANS LONGO 4/8')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM','BOTTOM JEANS LONGO FPM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM','BOTTOM JEANS LONGO MARCAS')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM','BOTTOM JEANS LONGO SUPER')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM','BOTTOM MALHA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM','BOTTOM MALHA CURTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM','BOTTOM MALHA GINAST CURTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM','BOTTOM MALHA LONGO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM','BOTTOM TECIDO CURTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM','BOTTOM TECIDO LONGO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM PROGRAMA','BOTTOM JEANS CURTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM PROGRAMA','BOTTOM JEANS CURTO 10/16')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM PROGRAMA','BOTTOM JEANS CURTO 4/8')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM PROGRAMA','BOTTOM JEANS CURTO FPM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM PROGRAMA','BOTTOM JEANS LONGO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM PROGRAMA','BOTTOM JEANS LONGO 10/16')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM PROGRAMA','BOTTOM JEANS LONGO 4/8')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM PROGRAMA','BOTTOM JEANS LONGO FPM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM PROGRAMA','BOTTOM MALHA CURTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM PROGRAMA','BOTTOM MALHA CURTO LICENC')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM PROGRAMA','BOTTOM MALHA LONGO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM PROGRAMA','BOTTOM TECIDO CURTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BOTTOM PROGRAMA','BOTTOM TECIDO LONGO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('BRINQUEDO','BRINQUEDO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CARNAVAL','COMPLEMENTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CASA','CASA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CASA','MANTA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CASA','MANTA INFANTIL')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CASA','TOALHA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CHINELO','BABY')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CHINELO','CHINELO GRENDENE')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CHINELO','CHINELO HAVAIANAS')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CHINELO','KIDS')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CINTO','CINTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('COMPLEMENTO','CACHECOL/LENCO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('COMPLEMENTO','COMPLEMENTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CUECA','CUECA BOXER')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CUECA','CUECA BOXER COTTON')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CUECA','CUECA BOXER MICRO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CUECA','CUECA MARCAS')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CUECA','KIT CUECA APARENTE')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CUECA','KIT CUECA BOXER')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CUECA','KIT CUECA EMBUTIDO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CUECA','KIT CUECA LICENCIADO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CUECA','KIT CUECA MAIOR')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CUECA','KIT CUECA MARCAS')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CUECA','KIT CUECA MENOR')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CUECA','SAMBA CANCAO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('CUECA','SAMBA CANCAO MALHA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('ESCRITÓRIO','CADERNO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('ESCRITÓRIO','COMPLEMENTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('GARRAFA','GARRAFA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO','CONJ/ VEST/ MACAQ')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO','CONJUNTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO','CONJUNTO LICENCIADO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO','CONJUNTO/MACAQ LICENC')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO','INTEIRO BB')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO','INTEIRO JEANS')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO','INTEIRO JEANS 1/3')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO','INTEIRO JEANS 10/16')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO','INTEIRO JEANS 4/8')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO','INTEIRO JEANS FPM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO','INTEIRO MALHA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO','INTEIRO TECIDO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO','VESTIDO/MACAQUINHO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO','VESTIDO/MACAQUINHO LICENC')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO PROGRAMA','CONJ/ VEST/ MACAQ LICENC')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO PROGRAMA','CONJUNTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO PROGRAMA','CONJUNTO LICENCIADO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO PROGRAMA','INTEIRO MALHA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO PROGRAMA','INTEIRO TECIDO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO PROGRAMA','VESTIDO/MACAQUINHO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INTEIRO PROGRAMA','VESTIDO/MACAQUINHO LICENC')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO','COMPLEMENTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO','MEIA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO','MEIA CALCA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO BOTTOM','BOTTOM HELANCA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO BOTTOM','BOTTOM MOLETOM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO BOTTOM PROGRAMA','BOTTOM MOLETOM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO BOTTOM PROGRAMA','BOTTOM MOLETOM LICENCIADO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO INTEIRO','CONJUNTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO INTEIRO','CONJUNTO LICENCIADO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO INTEIRO','INTEIRO BB')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO INTEIRO','INTEIRO MALHA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO INTEIRO PROGRAMA','CONJUNTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO LINHA NOITE','PIJAMA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO LINHA NOITE','PIJAMA CORAL')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO LINHA NOITE','PIJAMA CORAL FPM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO LINHA NOITE','PIJAMA LEVE')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO LINHA NOITE','PIJAMA LEVE FPM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO LINHA NOITE','PIJAMA MALHA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO LINHA NOITE','PIJAMA PESADO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO TOP','TOP HELANCA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO TOP','TOP JEANS JAQUETA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO TOP','TOP JEANS JAQUETA 1/3')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO TOP','TOP JEANS JAQUETA 10/16')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO TOP','TOP JEANS JAQUETA 4/8')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO TOP','TOP MALHA JAQUETA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO TOP','TOP MALHA M/L')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO TOP','TOP MALHA M/L LICENCIADO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO TOP','TOP MOLETOM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO TOP','TOP MOLETOM LICENCIADO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO TOP','TOP TECIDO JAQUETA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO TOP','TOP TECIDO M/L')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO TOP','TOP TRICO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO TOP PROGRAMA','TOP MALHA M/L')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO TOP PROGRAMA','TOP MALHA M/L LICENCIADO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO TOP PROGRAMA','TOP MOLETOM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO TOP PROGRAMA','TOP MOLETOM LICENCIADO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO TOP PROGRAMA','TOP TECIDO JAQUETA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('INVERNO TOP PROGRAMA','TOP TRICO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINGERIE','CONJUNTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINGERIE','CONJUNTO LICENCIADO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINGERIE','KIT CALCINHA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINGERIE','KIT CALCINHA LICENCIADO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINGERIE','SEM COSTURA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','CALCINHA BASICA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','CALCINHA BASICA FPM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','CALCINHA DIFERENCIADA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','CALCINHA DIFERENCIADA FPM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','CALCINHA SEM COSTURA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','CALCINHA SORTIDA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','EVENTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','KIT CALCINHA ESTAMPADA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','KIT CALCINHA FPM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','KIT CALCINHA LISA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','KIT CALCINHA MARCAS')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','KIT CALCINHA SEM COSTURA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','SUTIA BASE')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','SUTIA BASE RENDA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','SUTIA BASICO FPM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','SUTIA DIFERENCIADO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','SUTIA DIFERENCIADO FPM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','SUTIA MARCAS')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','SUTIA NADADOR')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','SUTIA PUSH UP')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','SUTIA SEM COSTURA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','SUTIA TOMARA QUE CAIA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA DIA','SUTIA TRIANGULO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA NOITE','PANTUFA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA NOITE','PIJAMA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA NOITE','PIJAMA FPM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA NOITE','PIJAMA LIGANETE')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA NOITE','PIJAMA MALHA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA NOITE','PIJAMA MALHA FPM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA NOITE','PIJAMA PROGRAMA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA PRAIA','MAIO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA PRAIA','BIQUINI BOTTOM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA PRAIA','BIQUINI BOTTOM FPM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA PRAIA','BIQUINI TOP')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA PRAIA','BIQUINI TOP FPM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA PRAIA','BIQUINI/MAIO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA PRAIA','BOLSA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA PRAIA','CHAPEU')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA PRAIA','COMPLEMENTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA PRAIA','COMPLEMENTO FPM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA PRAIA','MAIO FPM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('LINHA PRAIA','SUNGA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('MEIA','KIT MEIA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('MEIA','KIT MEIA MAIOR')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('MEIA','KIT MEIA MARCAS')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('MEIA','MEIA CALCA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('MEIA','MEIA COORDENADA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('MUSICA','FONE DE OUVIDO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('NECESSAIRE','NECESSAIRE')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('PAPEL PRESENTE','PAPEL PRESENTE')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('PET','BRINQUEDO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('PET','COMPLEMENTO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('SANDALIA','BABY')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('SANDALIA','KIDS')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('SANDALIA BAIXA','PAPETE')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('SANDALIA BAIXA','RASTEIRA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('SANDALIA SALTO','SANDALIA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('SAPATILHA','SAPATILHA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('SAUDE','ESPORTE')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('SAUDE','HIGIENE')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('SCARPIN','SCARPIN')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TENIS','BABY')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TENIS','KIDS')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TENIS','TENIS')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TENIS','TENIS CASUAL')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TENIS','TENIS ESPORTIVO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP','TOP JEANS')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP','TOP JEANS 1/3')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP','TOP JEANS 10/16')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP','TOP JEANS 4/8')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP','TOP JEANS FPM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP','TOP JEANS SUPER')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP','TOP MALHA GINASTICA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP','TOP MALHA M/C')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP','TOP MALHA M/C LICENCIADO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP','TOP MALHA POLO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP','TOP MALHA S/M')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP','TOP MALHA S/M LICENCIADO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP','TOP TECIDO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP','TOP TECIDO M/C')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP','TOP TECIDO M/L')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP','TOP TECIDO S/M')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP','TOP TRICO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP PROGRAMA','TOP MALHA GINASTICA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP PROGRAMA','TOP MALHA M/C')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP PROGRAMA','TOP MALHA M/C LICENCIADO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP PROGRAMA','TOP MALHA M/C MARCAS')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP PROGRAMA','TOP MALHA POLO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP PROGRAMA','TOP MALHA S/M')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP PROGRAMA','TOP MALHA S/M LICENCIADO')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP PROGRAMA','TOP MALHA S/M MARCAS')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP PROGRAMA','TOP TECIDO M/C')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('TOP PROGRAMA','TOP TECIDO S/M')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('VIAGEM','BOLSA/MOCHILA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('VIAGEM','GUARDA CHUVA')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('VIAGEM','KIT VIAGEM')
insert into @tabsubgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO) VALUES ('VIAGEM','PORTA OBJETO')

select a.*, b.CODIGO_SUBGRUPO,b.CODIGO_SEQUENCIAL 
from @tabsubgrupo a 
inner join	produtos_subgrupo b 
	on b.GRUPO_PRODUTO=a.GRUPO_PRODUTO and b.SUBGRUPO_PRODUTO=a.SUBGRUPO_PRODUTO
--where b.CODIGO_SEQUENCIAL is null


 