select A.* 
--UPDATE A SET QTDE_TOTAL=50
--UPDATE v SET TOT_QTDE_ORIGINAL = 50, TOT_QTDE_ENTREGAR = 50, TOT_VALOR_ORIGINAL = 50*4.47, TOT_VALOR_ENTREGAR = 50*4.47
--UPDATE Ve SET QTDE_EMBALADA = 50, E1 = 50, VALOR_EMBALADO = 50*4.47
--UPDATE VP SET QTDE_ORIGINAL = 50, QTDE_ENTREGAR=50, VALOR_ORIGINAL = 4.47*50, VALOR_ENTREGAR=4.47*50, VO1=50,VE1=50
from CAEDU_RESERVA_AUTOMATICA_PACK_WMS a 
inner join VENDAS V on v.PEDIDO = a.VENDA
inner join VENDAS_PRODUTO vp on vp.PEDIDO = v.PEDIDO
inner join VENDAS_PROD_EMBALADO ve on ve.CAIXA = a.CAIXA
where a.DISTRIBUICAO = '00013802'

SELECT * 
FROM PRODUTOS_PACKS_PERMITIDOS Z WHERE PRODUTO = 'Z3010095' 
