

SELECT CAIXA INTO #CAIXAS FROM FATURAMENTO_PROD WHERE CAIXA IN (
SELECT CAIXA FROM CAEDU_RESERVA_AUTOMATICA_wms WHERE DISTRIBUICAO = '00003655')

select f.emissao,* 
from faturamento_prod fp
inner join faturamento f on f.NF_SAIDA = fp.NF_SAIDA and f.FILIAL = fp.FILIAL
where caixa in (select caixa from #CAIXAS)



UPDATE  CAEDU_RESERVA_AUTOMATICA_wms	
SET COR_PRODUTO = '00103'
WHERE DISTRIBUICAO = '00003655'
AND CAIXA NOT IN (SELECT CAIXA FROM #CAIXAS)

UPDATE VENDAS_PROD_EMBALADO 
SET COR_PRODUTO = '00103'
WHERE CAIXA IN (
SELECT CAIXA FROM CAEDU_RESERVA_AUTOMATICA_wms WHERE DISTRIBUICAO = '00003655' AND COR_PRODUTO = '00103'
)

SELECT * FROM FATURAMENTO_CAIXAS WHERE CAIXA IN (
SELECT CAIXA FROM CAEDU_RESERVA_AUTOMATICA_wms WHERE DISTRIBUICAO = '00003655' AND COR_PRODUTO = '00103'
)
