SELECT  
A.PRODUTO
,A.ESTOQUE
,A.RESERVA
,A.DISPONIVEL
,A.GRIFFE
,A.LINHA
,A.GRUPO_PRODUTO
,A.SUBGRUPO_PRODUTO
,A.ERP_QTD_PACK
,A.QTD_PACK_TOTAL
,A.ULTIMA_DISTRIBUICAO
,A.DIAS
,B.DESC_PRODUTO
,B.REFER_FABRICANTE
,B.CLASSIF_FISCAL
,B.TIPO_PRODUTO
,C.PRECO1
,B.FATOR_P
,B.COLECAO 
,B.TRIBUT_ORIGEM
,E.COR_PRODUTO
,E.PACK
,E.QTDE
,E.Q1
,E.Q2
,E.Q3
,E.Q4
,E.Q5
,E.Q6
,E.Q7
,E.Q8
,E.Q9
,E.Q10
,E.Q11
,E.Q12
,E.Q13
,E.Q14
,E.Q15
,E.Q16
--dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.QTDE as Total_PACK,
--dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.Q1 AS Tam_1,
--dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.Q2 AS Tam_2,
--dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.Q3 AS Tam_3,
--dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.Q4 AS Tam_4,
--dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.Q5 AS Tam_5,
--dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.Q6 AS Tam_6,
--dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.Q7 AS Tam_7,
--dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.Q8 AS Tam_8,
--dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.Q9 AS Tam_9,
--dbo.CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL.Q10 AS Tam_10,
--dbo.COLECOES.DESC_COLECAO,
--dbo.COMPRAS.ERP_TOTAL_QTD_DISTRIB,
--dbo.COMPRAS.ERP_PERCENT_DISTRIB

FROM dbo.VW_DITRIBUICAO A 
INNER JOIN
	dbo.PRODUTOS B 
		ON B.PRODUTO = A.PRODUTO 
INNER JOIN
	dbo.PRODUTOS_PRECOS C 
		ON C.PRODUTO = A.PRODUTO 
INNER JOIN 
	dbo.COLECOES D 
		ON D.COLECAO = B.COLECAO
INNER   JOIN  
	dbo.PRODUTOS_PACKS_PERMITIDOS E 
		ON E.PRODUTO = A.PRODUTO AND E.PACK = 'A'

WHERE     (C.CODIGO_TAB_PRECO = '01') 
		AND (B.GRIFFE = 'LINGERIE') 

ORDER BY
	A.PRODUTO

/*
SELECT A.PRODUTO
      ,A.ESTOQUE
      ,A.RESERVA
      ,A.DISPONIVEL
      ,A.GRIFFE
      ,A.LINHA
      ,A.GRUPO_PRODUTO
      ,A.SUBGRUPO_PRODUTO
      ,A.ERP_QTD_PACK
      ,A.QTD_PACK_TOTAL
      ,A.ULTIMA_DISTRIBUICAO
      ,A.DIAS
  FROM dbo.VW_DITRIBUICAO A
*/




