

ALTER TABLE FORNECEDORES 
ADD ERP_USA_BOLACHA BIT NOT NULL CONSTRAINT DF_ERP_USA_BOLACHA DEFAULT(0)
GO

ALTER TABLE COMPRAS
ADD ERP_CAB_OPCAO INT NOT NULL CONSTRAINT DF_ERP_CAB_OPCAO DEFAULT(0),
	ERP_CAB_COD_BOLACHA VARCHAR(15) NULL
GO


ALTER TABLE COMPRAS_PRODUTO 
ADD ERP_CONJUNTO BIT NOT NULL CONSTRAINT DF_ERP_CONJUNTO DEFAULT(0),
	ERP_COR_PRODUTO2 CHAR(6) NULL
GO

/*

SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('COMPRAS') AND NAME LIKE '%CAB%' ORDER BY COLID

SELECT TOP 10 * FROM PRODUTOS ORDER BY DATA_PARA_TRANSFERENCIA DESC

SELECT FORNECEDOR, ERP_USA_BOLACHA 
FROM FORNECEDORES 
WHERE FORNECEDOR = 'VITATEX COMERCIO'


select top 100 compras.emissao,* from compras order by compras.emissao desc

ERP_CAB_OPCAO compras.erp_cab_opcao, ERP_CAB_COD_BOLACHA compras.erp_cab_cod_bolacha

select * from compras_produto where pedido = '173143'  

	SELECT preco1 FROM produtos_precos 
	WHERE CODIGO_TAB_PRECO = '01' and produto = '23030518'


	select * from compras where pedido = '173143'  

select distinct desc_cor_produto from PRODUTO_CORES


EXEC LX_SEQUENCIAL 
	@TABELA_COLUNA = ']+TRANSFORM(STRTABLECOLUMN)+[', 
	@EMPRESA = ?wempresa_atual, 
	@SEQUENCIA = ?@strSequence OUTPUT, ]+'@UPDATE_SEQUENCIAL = '+IIF(BSAVE, '1', '0')+[, @NEWVALUE = ']+IIF(EMPTY(STRNEWVALUE), '', ALLTRIM(TRANSFORM(STRNEWVALUE)))+['])

limpar box itapevi



select object_name(id) as xuxa,* from syscomments where text like '%LX_SEQUENCIAL%'
*/

/*
insert into CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES ('000513','AMARELO','016','SEGUNDA COR',NULL);
insert into CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES ('000514','AZUL','016','SEGUNDA COR',NULL);
insert into CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES ('000515','BEGE','016','SEGUNDA COR',NULL);
insert into CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES ('000516','BRANCO','016','SEGUNDA COR',NULL);
insert into CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES ('000517','CINZA','016','SEGUNDA COR',NULL);
insert into CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES ('000518','LARANJA','016','SEGUNDA COR',NULL);
insert into CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES ('000519','LILAS','016','SEGUNDA COR',NULL);
insert into CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES ('000520','MARROM','016','SEGUNDA COR',NULL);
insert into CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES ('000521','NUDE','016','SEGUNDA COR',NULL);
insert into CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES ('000522','PINK','016','SEGUNDA COR',NULL);
insert into CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES ('000523','PRATA','016','SEGUNDA COR',NULL);
insert into CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES ('000524','PRETO','016','SEGUNDA COR',NULL);
insert into CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES ('000525','ROSA','016','SEGUNDA COR',NULL);
insert into CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES ('000526','ROXO','016','SEGUNDA COR',NULL);
insert into CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES ('000527','VERDE','016','SEGUNDA COR',NULL);
insert into CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES ('000528','VERMELHO','016','SEGUNDA COR',NULL);
insert into CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES ('000529','VINHO','016','SEGUNDA COR',NULL);
insert into CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES ('000530','VIOLETA','016','SEGUNDA COR',NULL);
insert into CAEDU_LISTA_COMBO (CODIGO,DESCRICAO,ID_DOMINIO,DESC_DOMINIO,ERP_CUPS_DESCRICAO_IMPORTACAO) VALUES ('000531','XADREZ','016','SEGUNDA COR',NULL);
*/

SELECT DESCRICAO,CODIGO FROM CAEDU_LISTA_COMBO WHERE ID_DOMINIO = '016' ORDER BY DESCRICAO


select * from COMPRAS where pedido = '173192'

select * from COMPRAS_PRODUTO where pedido = '173192'

SELECT * FROM TRANSACOES WHERE CONTROL_SISTEMA LIKE '004006%'


select * from compras_produto where pedido = '173196'