CREATE   TABLE PDA_TB_ARQUIVO_TRANSFERENCIA_ENTRE_LOJAS
(ID INT NOT NULL IDENTITY(1,1), 
ID_TRANSFERENCIA INT NOT NULL,
DT_TRANSFERENCIA DATETIME,
COD_FILIAL_ORIGEM CHAR(6) NOT NULL,
COD_FILIAL_DESTINO CHAR(6) NOT NULL,
CODIGO_BARRA VARCHAR(25) NOT NULL,
QUANTIDADE INT NOT NULL,
TTIMESTAMP DECIMAL (18,0) NOT NULL,
ID_USUARIO INT NULL,
CONSTRAINT PK_PDA_TB_ARQUIVO_TRANSFERENCIA_ENTRE_LOJAS PRIMARY KEY (ID)
)
GO

CREATE INDEX IDX_PDA_TB_ARQUIVO_TRANSFERENCIA_ENTRE_LOJAS_ID_TRANSFERENCIA ON PDA_TB_ARQUIVO_TRANSFERENCIA_ENTRE_LOJAS (ID_TRANSFERENCIA)
GO

CREATE INDEX IDX_PDA_TB_ARQUIVO_TRANSFERENCIA_ENTRE_LOJAS_COD_FILIAL_ORIGEM ON PDA_TB_ARQUIVO_TRANSFERENCIA_ENTRE_LOJAS (COD_FILIAL_ORIGEM)
GO


