CREATE   TABLE PDA_TB_ARQUIVO_CONTAGEM
(ID INT NOT NULL IDENTITY(1,1), 
ID_INVENTARIO INT NOT NULL,
DT_INVENTARIO DATETIME,
COD_FILIAL CHAR(6) NOT NULL,
CODIGO_BARRA VARCHAR(25) NOT NULL,
QUANTIDADE INT NOT NULL,
NOME_INVENTARIO VARCHAR(50) NOT NULL,
TTIMESTAMP DECIMAL (18,0) NOT NULL,
CONSTRAINT PK_PDA_TB_ARQUIVO_CONTAGEM PRIMARY KEY (ID)
)
GO

CREATE INDEX IDX_PDA_TB_ARQUIVO_CONTAGEM_ID_INVENTARIO ON PDA_TB_ARQUIVO_CONTAGEM (ID_INVENTARIO)
GO

CREATE INDEX IDX_PDA_TB_ARQUIVO_CONTAGEM_NOME_INVENTARIO ON PDA_TB_ARQUIVO_CONTAGEM (NOME_INVENTARIO)
GO


