SELECT TAB1.*, FILIAL, erp_ordem_rota, erp_cod_rota
FROM (
select a.CODIGO_FILIAL, a.PEDIDO, a.CAIXA_EUREKA, COUNT(*) AS VOLUMES, SUM(CAIXA_QTDE) AS TOTAL_PECAS 
from PDA_WMS_TB_CX_EUREKA a
GROUP BY CODIGO_FILIAL, PEDIDO, CAIXA_EUREKA ) AS TAB1
inner join FILIAIS f on f.COD_FILIAL = tab1.CODIGO_FILIAL

