USE [CAEDU_2.1]
GO
/****** Object:  StoredProcedure [dbo].[PDA_SP_FINAL_CAEDU]    Script Date: 02/17/2017 16:08:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
  
ALTER PROCEDURE [dbo].[PDA_SP_FINAL_CAEDU] -- [PDA_SP_FINAL_CAEDU] 127 ,1
 declare @ID_INVENTARIO INT = 182,@INCLUIR_NAO_CADASTRADO INT =1  
--AS  
--BEGIN  

IF @INCLUIR_NAO_CADASTRADO = 1
BEGIN

 WITH RESULTADO (COD_AUTOMACAO, COD_SKU, CONTAGEM_FINAL, DIVERGENCIA) AS (  
  SELECT COD_AUTOMACAO,  
   COD_SKU,  
   SUM(CASE WHEN FINAL = 0 THEN CONTAGEM ELSE FINAL END) CONTAGEM_FINAL,  
   ISNULL((SELECT IC.QTDE_CONTAGEM FROM PDA_TB_ITEM_COLETA IC WHERE IC.ID_INVENTARIO = @ID_INVENTARIO AND IC.LX_TIPO_ATIVIDADE = 6 AND IC.COD_AUTOMACAO = TOTAL.COD_AUTOMACAO), SUM(DIVERGENCIA))  AS DIVERGENCIA  
    FROM (     
    SELECT COD_AUTOMACAO,  
        COD_SKU,  
        ID_ENDERECO,  
        ISNULL(SUM(CONTAGEM),0) AS CONTAGEM,   
        ISNULL(SUM(FINAL),0) AS FINAL,   
        ISNULL(SUM(DIVERGENCIA),0) AS DIVERGENCIA  
      FROM (  
       SELECT T.COD_AUTOMACAO,  
           T.COD_SKU,  
           T.ID_ENDERECO,  
           CASE WHEN LX_TIPO_ATIVIDADE = 2 THEN QTDE_CONTAGEM END AS CONTAGEM,  
           CASE WHEN LX_TIPO_ATIVIDADE = 4 THEN QTDE_CONTAGEM END AS FINAL,  
           CASE WHEN LX_TIPO_ATIVIDADE = 5 THEN QTDE_CONTAGEM END AS DIVERGENCIA  
         FROM PDA_TB_ITEM_COLETA T  
        WHERE ID_INVENTARIO  = @ID_INVENTARIO  
        ) AUX  
     GROUP   
        BY COD_AUTOMACAO, COD_SKU, ID_ENDERECO  
      
   ) TOTAL    
     GROUP BY COD_AUTOMACAO, COD_SKU)  
  
 SELECT FINAL.COD_AUTOMACAO COD_AUTOMACAO    
   ,CAST( FINAL.CONTAGEM  as int) AS CONTAGEM  
  FROM  
   (  
     SELECT RESULTADO.COD_AUTOMACAO COD_AUTOMACAO  
       , CASE WHEN DIVERGENCIA = 0 THEN CONTAGEM_FINAL ELSE  DIVERGENCIA END AS CONTAGEM         
     FROM RESULTADO --LEFT    
          --JOIN PDA_TB_ESTOQUE_TEORICO ET   
           -- ON ET.ID_SKU = RESULT.COD_SKU   
          -- AND ET.ID_INVENTARIO = @ID_INVENTARIO       
         --INNER JOIN PDA_TB_SKU SK   
         --   ON RESULT.COD_AUTOMACAO = SK.COD_AUTOMACAO   
         --  AND SK.ID_INVENTARIO  = @ID_INVENTARIO   
    GROUP BY RESULTADO.COD_AUTOMACAO  
        , DIVERGENCIA  
        , CONTAGEM_FINAL  
          
     -- UNION ALL  
        
     -- SELECT CASE WHEN TEO.ID_AUTOMACAO = '' THEN (SELECT TOP 1 COD_AUTOMACAO FROM PDA_TB_SKU SK WHERE SK.COD_SKU = TEO.ID_SKU AND SK.ID_INVENTARIO = @ID_INVENTARIO) ELSE TEO.ID_AUTOMACAO END COD_AUTOMACAO          
     --   , CASE WHEN  TEO.QUANTIDADE < 0 THEN  
     --  TEO.QUANTIDADE * -1  
     --     ELSE   
     --  0   
     --     END AS CONTAGEM          
     --FROM PDA_TB_ESTOQUE_TEORICO TEO  
     --  WHERE TEO.ID_INVENTARIO = @ID_INVENTARIO  
     -- AND NOT EXISTS ( SELECT 1 FROM RESULT WHERE RESULT.COD_SKU = TEO.ID_SKU)  
           
    ) FINAL INNER JOIN PDA_TB_INVENTARIO I ON I.ID_INVENTARIO = @ID_INVENTARIO  
   GROUP BY FINAL.COD_AUTOMACAO  
    , FINAL.CONTAGEM     
   ORDER BY FINAL.COD_AUTOMACAO  
   
END
ELSE

BEGIN

WITH RESULTADO (COD_AUTOMACAO, COD_SKU, CONTAGEM_FINAL, DIVERGENCIA) AS (  
  SELECT COD_AUTOMACAO,  
   COD_SKU,  
   SUM(CASE WHEN FINAL = 0 THEN CONTAGEM ELSE FINAL END) CONTAGEM_FINAL,  
   ISNULL((SELECT IC.QTDE_CONTAGEM FROM PDA_TB_ITEM_COLETA IC WHERE IC.ID_INVENTARIO = @ID_INVENTARIO AND IC.LX_TIPO_ATIVIDADE = 6 AND IC.COD_AUTOMACAO = TOTAL.COD_AUTOMACAO), SUM(DIVERGENCIA))  AS DIVERGENCIA  
    FROM (     
    SELECT COD_AUTOMACAO,  
        COD_SKU,  
        ID_ENDERECO,  
        ISNULL(SUM(CONTAGEM),0) AS CONTAGEM,   
        ISNULL(SUM(FINAL),0) AS FINAL,   
        ISNULL(SUM(DIVERGENCIA),0) AS DIVERGENCIA  
      FROM (  
       SELECT T.COD_AUTOMACAO,  
           T.COD_SKU,  
           T.ID_ENDERECO,  
           CASE WHEN LX_TIPO_ATIVIDADE = 2 THEN QTDE_CONTAGEM END AS CONTAGEM,  
           CASE WHEN LX_TIPO_ATIVIDADE = 4 THEN QTDE_CONTAGEM END AS FINAL,  
           CASE WHEN LX_TIPO_ATIVIDADE = 5 THEN QTDE_CONTAGEM END AS DIVERGENCIA  
         FROM PDA_TB_ITEM_COLETA T 
         INNER JOIN PDA_TB_SKU SKU ON SKU.COD_AUTOMACAO = T.COD_AUTOMACAO AND SKU.ID_INVENTARIO = T.ID_INVENTARIO AND SKU.ID_INVENTARIO = @ID_INVENTARIO
        WHERE T.ID_INVENTARIO  = @ID_INVENTARIO  
        ) AUX  
     GROUP   
        BY COD_AUTOMACAO, COD_SKU, ID_ENDERECO  
      
   ) TOTAL    
     GROUP BY COD_AUTOMACAO, COD_SKU)  
  
 SELECT FINAL.COD_AUTOMACAO COD_AUTOMACAO    
   ,CAST( FINAL.CONTAGEM  as int) AS CONTAGEM  
  FROM  
   (  
     SELECT RESULTADO.COD_AUTOMACAO COD_AUTOMACAO  
       , CASE WHEN DIVERGENCIA = 0 THEN CONTAGEM_FINAL ELSE  DIVERGENCIA END AS CONTAGEM         
     FROM RESULTADO --LEFT    
          --JOIN PDA_TB_ESTOQUE_TEORICO ET   
           -- ON ET.ID_SKU = RESULT.COD_SKU   
          -- AND ET.ID_INVENTARIO = @ID_INVENTARIO       
         --INNER JOIN PDA_TB_SKU SK   
         --   ON RESULT.COD_AUTOMACAO = SK.COD_AUTOMACAO   
         --  AND SK.ID_INVENTARIO  = @ID_INVENTARIO   
    GROUP BY RESULTADO.COD_AUTOMACAO  
        , DIVERGENCIA  
        , CONTAGEM_FINAL  
          
     -- UNION ALL  
        
     -- SELECT CASE WHEN TEO.ID_AUTOMACAO = '' THEN (SELECT TOP 1 COD_AUTOMACAO FROM PDA_TB_SKU SK WHERE SK.COD_SKU = TEO.ID_SKU AND SK.ID_INVENTARIO = @ID_INVENTARIO) ELSE TEO.ID_AUTOMACAO END COD_AUTOMACAO          
     --   , CASE WHEN  TEO.QUANTIDADE < 0 THEN  
     --  TEO.QUANTIDADE * -1  
     --     ELSE   
     --  0   
     --     END AS CONTAGEM          
     --FROM PDA_TB_ESTOQUE_TEORICO TEO  
     --  WHERE TEO.ID_INVENTARIO = @ID_INVENTARIO  
     -- AND NOT EXISTS ( SELECT 1 FROM RESULT WHERE RESULT.COD_SKU = TEO.ID_SKU)  
           
    ) FINAL INNER JOIN PDA_TB_INVENTARIO I ON I.ID_INVENTARIO = @ID_INVENTARIO  
   GROUP BY FINAL.COD_AUTOMACAO  
    , FINAL.CONTAGEM     
   ORDER BY FINAL.COD_AUTOMACAO  

END
--END