
--update compras set ERP_CUPS_CHEGADA_CD = 'XX/xx/xxxx'
--where PEDIDO = 'XXXXXXXX'

--select c.PEDIDO, c.EMISSAO, c.FORNECEDOR, e.RECEBIMENTO, ep.PEDIDO, ep.NF_ENTRADA
UPDATE c SET ERP_CUPS_CHEGADA_CD = e.RECEBIMENTO
from ENTRADAS e
inner join ENTRADAS_PRODUTO ep 
	on ep.NF_ENTRADA=e.NF_ENTRADA
	and ep.SERIE_NF_ENTRADA=e.SERIE_NF_ENTRADA
	and ep.NOME_CLIFOR=e.NOME_CLIFOR
inner join COMPRAS c 
	on c.PEDIDO=ep.PEDIDO
where e.NF_ENTRADA='000274508' and e.SERIE_NF_ENTRADA='001' and e.NOME_CLIFOR='KOMPORT'