
declare @loja varchar(25), @OPCAO INT = 1

set @loja = 'SP - JAU'

IF @OPCAO=1
BEGIN
	SELECT b.* 
	FROM [ccp\paulo.devide].TB_CAIXAS_A_FATURAR_20250602 a
	LEFT JOIN FATURAMENTO_CAIXAS B ON B.caixa = A.caixa
	WHERE a.lojadestino = @loja
	
	SELECT b.* 
	FROM [ccp\paulo.devide].TB_CAIXAS_A_FATURAR_20250602 a
	LEFT JOIN VENDAS B ON B.PEDIDO = A.VENDA
	WHERE a.lojadestino = @loja

	SELECT b.* 
	FROM [ccp\paulo.devide].TB_CAIXAS_A_FATURAR_20250602 a
	LEFT JOIN VENDAS_PROD_EMBALADO B ON B.PEDIDO = A.VENDA
	WHERE a.lojadestino = @loja

END

IF @OPCAO=2
BEGIN 
	UPDATE VENDAS SET CLIENTE_ATACADO =@loja, REPRESENTANTE=@loja, GERENTE=@loja, NOME_CLIFOR_ENTREGA=@loja 
	WHERE PEDIDO in (
'CX-32252100', 
'CX-32252101' ) 
END

IF @OPCAO=3
BEGIN 
	UPDATE faturamento_caixas SET nome_clifor =@loja, NOME_CLIFOR_ENTREGA=@loja 
	WHERE caixa in (
'32252100',
'32252101') 
END

IF @OPCAO=4
BEGIN 
	UPDATE VENDAS_PROD_EMBALADO SET NOME_CLIFOR =@loja, REPRESENTANTE=@loja
	WHERE PEDIDO in (
'CX-32252100', 
'CX-32252101' ) 
END

--UPDATE B SET 
--TOT_QTDE_ORIGINAL=(SELECT SUM(QTDE_EMBALADA) FROM VENDAS_PROD_EMBALADO WHERE PEDIDO=B.PEDIDO), 
--TOT_QTDE_EMBALADA=(SELECT SUM(QTDE_EMBALADA) FROM VENDAS_PROD_EMBALADO WHERE PEDIDO=B.PEDIDO), 
--TOT_QTDE_ENTREGAR=(SELECT SUM(QTDE_EMBALADA) FROM VENDAS_PROD_EMBALADO WHERE PEDIDO=B.PEDIDO) 
--FROM [ccp\paulo.devide].TB_CAIXAS_A_FATURAR_20250602 a
--LEFT JOIN VENDAS B ON B.PEDIDO = A.VENDA

--SELECT * 
--UPDATE A SET FATURADO=1
--FROM [ccp\paulo.devide].TB_CAIXAS_A_FATURAR_20250602 a
--WHERE PRODUTO = '26050271'