p1 = 15.99
p2 = 19.99
p3 = 24.99
p4 = 29.99

select * 
update a set valor1 = 0.00, valor2=15.99, 
				ATUALIZADO=0 
from CAE_PRODUTOS_FATOR_P a
WHERE GRIFFE = 'INFANTIL' 
AND LINHA = '1/3 NAS'
AND GRUPO_PRODUTO = 'BOTTOM MALHA'
AND SUBGRUPO_PRODUTO = 'CALCA'
AND REFERENCIA = 1 


update a set valor1 = 16.00, valor2=19.99, 
ATUALIZADO = 0
from CAE_PRODUTOS_FATOR_P a
WHERE GRIFFE = 'INFANTIL' 
AND LINHA = '1/3 NAS'
AND GRUPO_PRODUTO = 'BOTTOM MALHA'
AND SUBGRUPO_PRODUTO = 'CALCA'
AND REFERENCIA = 2 

update a set valor1 = 20.00, valor2=24.99, 
ATUALIZADO = 0
from CAE_PRODUTOS_FATOR_P a
WHERE GRIFFE = 'INFANTIL' 
AND LINHA = '1/3 NAS'
AND GRUPO_PRODUTO = 'BOTTOM MALHA'
AND SUBGRUPO_PRODUTO = 'CALCA'
AND REFERENCIA = 3

update a set valor1 = 25.00, valor2=29.99, 
ATUALIZADO = 0
from CAE_PRODUTOS_FATOR_P a
WHERE GRIFFE = 'INFANTIL' 
AND LINHA = '1/3 NAS'
AND GRUPO_PRODUTO = 'BOTTOM MALHA'
AND SUBGRUPO_PRODUTO = 'CALCA'
AND REFERENCIA = 4

