USE [CAEDU]
GO
/****** Object:  Trigger [dbo].[CGP_FATURAMENTO_ITEM_DEL]    Script Date: 20/01/2021 16:19:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		PAULO DEVIDE
-- Create date: 20-JAN-21
-- Description:	INSERE UM REGISTRO NA TABELA 
-- =============================================
CREATE  TRIGGER [dbo].[CGP_ENTRADAS_ITEM_DEL] 
	ON [dbo].[ENTRADAS_ITEM] 
	FOR DELETE 
AS 
BEGIN
	SET NOCOUNT ON;

	INSERT INTO DBO.CGP_ENTRADAS_ITEM_LOG
	(CLASSIF_FISCAL
	,CODIGO_FISCAL_OPERACAO
	,CODIGO_ITEM
	,COD_TABELA_FILHA
	,COMISSAO_ITEM
	,COMISSAO_ITEM_GERENTE
	,CONTA_CONTABIL
	,DESCONTO_ITEM
	,DESCRICAO_ITEM
	,FAIXA
	,ID_EXCECAO_IMPOSTO
	,INDICADOR_CFOP
	,ITEM_IMPRESSAO
	,NF_ENTRADA
	,NOME_CLIFOR
	,PESO
	,PORCENTAGEM_ITEM_RATEIO
	,PRECO_UNITARIO
	,QTDE_DEVOLVIDA
	,QTDE_ITEM
	,QTDE_RETORNAR_BENEFICIAMENTO
	,SERIE_NF_ENTRADA
	,SUB_ITEM_TAMANHO
	,TRIBUT_ICMS
	,TRIBUT_ORIGEM
	,UNIDADE
	,VALOR_ITEM
	,REFERENCIA
	,REFERENCIA_ITEM
	,REFERENCIA_PEDIDO
	,DIVERGENTE
	,REFERENCIA_ENTREGA_PEDIDO
	,VALOR_ENCARGOS
	,VALOR_DESCONTOS
	,VALOR_ENCARGOS_IMPORTACAO
	,NAO_SOMA_VALOR
	,RATEIO_FILIAL
	,RATEIO_CENTRO_CUSTO
	,COD_REPRESENTANTE
	,COD_REPRESENTANTE_GERENTE
	,VALOR_ENCARGOS_ADUANEIROS
	,PORC_ITEM_RATEIO_FRETE
	,ITEM_NFE
	,MPADRAO_SEGURO_ITEM
	,MPADRAO_FRETE_ITEM
	,MPADRAO_ENCARGO_ITEM
	,DATA_PARA_TRANSFERENCIA
	,ORIGEM_ITEM
	,INDICA_PRODUTO_PROCESSO
	,PRECO_UNITARIO_ORIGINAL
	,CTB_TIPO_OPERACAO
	,ENCARGOS_IMPORT_DIGITADO
	,ID_SUB_PROJETO
	,ID_CEST_NCM
	,DATA_ACERTO_CONSIGNACAO
	)
	SELECT 
	CLASSIF_FISCAL
	,CODIGO_FISCAL_OPERACAO
	,CODIGO_ITEM
	,COD_TABELA_FILHA
	,COMISSAO_ITEM
	,COMISSAO_ITEM_GERENTE
	,CONTA_CONTABIL
	,DESCONTO_ITEM
	,DESCRICAO_ITEM
	,FAIXA
	,ID_EXCECAO_IMPOSTO
	,INDICADOR_CFOP
	,ITEM_IMPRESSAO
	,NF_ENTRADA
	,NOME_CLIFOR
	,PESO
	,PORCENTAGEM_ITEM_RATEIO
	,PRECO_UNITARIO
	,QTDE_DEVOLVIDA
	,QTDE_ITEM
	,QTDE_RETORNAR_BENEFICIAMENTO
	,SERIE_NF_ENTRADA
	,SUB_ITEM_TAMANHO
	,TRIBUT_ICMS
	,TRIBUT_ORIGEM
	,UNIDADE
	,VALOR_ITEM
	,REFERENCIA
	,REFERENCIA_ITEM
	,REFERENCIA_PEDIDO
	,DIVERGENTE
	,REFERENCIA_ENTREGA_PEDIDO
	,VALOR_ENCARGOS
	,VALOR_DESCONTOS
	,VALOR_ENCARGOS_IMPORTACAO
	,NAO_SOMA_VALOR
	,RATEIO_FILIAL
	,RATEIO_CENTRO_CUSTO
	,COD_REPRESENTANTE
	,COD_REPRESENTANTE_GERENTE
	,VALOR_ENCARGOS_ADUANEIROS
	,PORC_ITEM_RATEIO_FRETE
	,ITEM_NFE
	,MPADRAO_SEGURO_ITEM
	,MPADRAO_FRETE_ITEM
	,MPADRAO_ENCARGO_ITEM
	,DATA_PARA_TRANSFERENCIA
	,ORIGEM_ITEM
	,INDICA_PRODUTO_PROCESSO
	,PRECO_UNITARIO_ORIGINAL
	,CTB_TIPO_OPERACAO
	,ENCARGOS_IMPORT_DIGITADO
	,ID_SUB_PROJETO
	,ID_CEST_NCM
	,DATA_ACERTO_CONSIGNACAO
	FROM deleted
END
