USE [CAEDU]
GO

/****** Object:  View [dbo].[CGP_VW_DADOS_PEDIDOS]    Script Date: 08/04/2021 10:48:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW [dbo].[CGP_VW_DADOS_PEDIDOS] AS  
SELECT DISTINCT     
    'N' AS ISPROCCESSED       
    ,LTRIM(RTRIM(SUBSTRING(C.PEDIDO,1,20))) AS NUMERO_PEDIDO       
       ,CLI.COD_CLIFOR AS CODIGO_FORNECEDOR   
    ,CASE WHEN LTRIM(RTRIM(SUBSTRING(CP.PACKS,1,25))) = '' THEN 'X' ELSE LTRIM(RTRIM(SUBSTRING(CP.PACKS,1,25))) END AS NUMERO_PACK       
    ,LTRIM(RTRIM(CP.PRODUTO))  AS CODIGO_PRODUTO       
    ,NULL AS CODIGO_COR   
    ,NULL AS CODIGO_TAMANHO       
       ,CAST(CPT.QTDE AS INT) AS QTD_PECAS      
    ,C.ERP_TOTAL_CAIXAS_ORIGINAL AS QTD_PACKS  
    ,C.CADASTRAMENTO AS DATA_CRIACAO_ORDEM   
    ,CP.LIMITE_ENTREGA AS DATA_ENTREGA_ORDEM  
    ,RP.PED_CHEGADA AS DATA_AGENDAMENTO_ORDEM  
    ,C.DATA_PARA_TRANSFERENCIA AS DATA_ULTIMA_ATUALIZACAO_ORDEM  
       ,LTRIM(RTRIM(SUBSTRING(P.TIPO_PRODUTO,1,4))) AS TIPO_CODIGO_ETIQUETA  
    ,CASE WHEN RTRIM(LTRIM(C.FORNECEDOR)) = 'KOMPORT' THEN 'I' ELSE 'N' END   AS CODIGO_FONTE_ORDEM  
    ,CAST(PP1.PRECO1 AS DECIMAL (18,2)) AS VALOR_VENDA   
    ,CAST(PP0.PRECO1 AS DECIMAL (18,2)) AS VALOR_CUSTO  
    ,CAST(CPT.QTDE AS INT)  AS QUANTIDADE_PECAS_PEDIDO  
    ,C.ERP_TOTAL_CAIXAS_ORIGINAL AS QUANTIDADE_PACKS_PEDIDO       
    --,'0' AS CODIGO_ITEM_MAX_MIN  
   ,CASE WHEN ISNULL(LTRIM(RTRIM(PROP.VALOR_PROPRIEDADE)), 'NÃƒO') = 'SIM'   
         THEN (SELECT VALOR_ATUAL FROM PARAMETROS P WITH (NOLOCK) WHERE P.PARAMETRO = 'UNOUS_MINIMO_1_TODASLOJAS')   
   ELSE 0  
       END CODIGO_ITEM_MAX_MIN  
    ,CASE WHEN C.TOT_QTDE_ENTREGAR = 0 AND ISNULL(QTDE_CANCELADA,0) = 0 THEN 1  --RECEBIDO  
          WHEN C.TOT_QTDE_ENTREGAR = C.TOT_QTDE_ORIGINAL  AND ISNULL(QTDE_CANCELADA,0) = 0 THEN 2 --CARTEIRA  
    WHEN ISNULL(QTDE_CANCELADA,0) > 0 THEN 3 --CANCELADO  
  END AS CODIGO_STATUS   
    ,(SELECT VW.COD_RETAGUARDA FROM PARAMETROS P WITH (NOLOCK)  INNER JOIN CGP_VW_UNIDADES VW WITH (NOLOCK) ON P.VALOR_ATUAL = VW.FILIAL WHERE PARAMETRO = 'PALMA_CD_ORIGEM_DISTRIB') AS CD_PADRAO  
    ,C.EMISSAO   
    ,C.ERP_UNOUS_DATA_ENVIO          
    ,CP.ENTREGA  
    ,SUBSTRING(LTRIM(RTRIM(P.TIPO_PRODUTO)) +' '+ LTRIM(RTRIM(C.TIPO_COMPRA)),1,20) AS TIPO_PROD_COMPRA  
  FROM [DBO].COMPRAS C WITH (NOLOCK)  
       INNER JOIN [CAEDU].[DBO].CADASTRO_CLI_FOR CLI WITH (NOLOCK)  
            ON CLI.NOME_CLIFOR = C.FORNECEDOR  
    INNER JOIN (SELECT DISTINCT PEDIDO, PRODUTO, ENTREGA, LIMITE_ENTREGA, MAX(QTDE_CANCELADA) AS QTDE_CANCELADA , MAX(PACKS) AS PACKS  
         FROM [CAEDU].[DBO].COMPRAS_PRODUTO WITH (NOLOCK)  
                    GROUP BY PEDIDO, PRODUTO, ENTREGA,LIMITE_ENTREGA) CP   
            ON C.PEDIDO = CP.PEDIDO  
        INNER JOIN [CAEDU].[DBO].CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL CPT WITH (NOLOCK)  
         ON CP.PEDIDO = CPT.PEDIDO  
     AND CP.PRODUTO = CPT.PRODUTO            
        INNER JOIN [CAEDU].[DBO].PRODUTOS P WITH (NOLOCK)  
          ON P.PRODUTO = CP.PRODUTO  
        INNER JOIN [CAEDU].[DBO].PRODUTOS_PRECOS PP0 WITH (NOLOCK)  
          ON CP.PRODUTO = PP0.PRODUTO  
      AND PP0.CODIGO_TAB_PRECO = '00'   
        INNER JOIN [CAEDU].[DBO].PRODUTOS_PRECOS PP1 WITH (NOLOCK)  
          ON CP.PRODUTO = PP1.PRODUTO  
      AND PP1.CODIGO_TAB_PRECO = '01'  
   LEFT JOIN PROP_COMPRAS PROP WITH (NOLOCK)  
          ON PROP.PROPRIEDADE = '00106'  
      AND PROP.PEDIDO = C.PEDIDO  
      LEFT JOIN (SELECT PF.PEDIDO, MAX(PF.PED_CHEGADA) AS PED_CHEGADA, MAX(DATA) AS DATA FROM [PORTAL_FORNECEDOR].[DBO].[RECEBIMENTO_PEDIDO] PF GROUP BY PF.PEDIDO )RP  
          ON RP.PEDIDO = C.PEDIDO   
  
WHERE 1 = 1   
  AND CP.ENTREGA >= GETDATE() - 40    
  AND (C.ERP_UNOUS_DATA_ENVIO IS NULL OR RP.DATA > CONVERT(DATE, C.ERP_UNOUS_DATA_ENVIO, 103))  
  AND C.ERP_PACK_RESTO = 0   
  AND C.ERP_TOTAL_CAIXAS_ORIGINAL > 0     
  AND (
       (C.FORNECEDOR <> 'KOMPORT') 
		--OR 
	   --((C.FORNECEDOR = 'KOMPORT') AND (PROP.PROPRIEDADE = '00106') AND (ISNULL(LTRIM(RTRIM(PROP.VALOR_PROPRIEDADE)), 'NÃO') = 'SIM'))
	  )
    
  UNION  
  
    
SELECT  
       'N' AS ISPROCCESSED       
    ,(SELECT VW.COD_RETAGUARDA FROM PARAMETROS P WITH (NOLOCK)  INNER JOIN CGP_VW_UNIDADES VW WITH (NOLOCK) ON P.VALOR_ATUAL = VW.FILIAL WHERE PARAMETRO = 'PALMA_CD_ORIGEM_DISTRIB') AS NUMERO_PEDIDO      
    ,CASE WHEN CF.COD_CLIFOR IS NOT NULL THEN CF.COD_CLIFOR ELSE NULL END AS  CODIGO_FORNECEDOR   
       ,ISNULL(ED.PACK, 'A') AS NUMERO_PACK  
    ,LTRIM(RTRIM(ED.PRODUTO)) AS CODIGO_PRODUTO   
    ,NULL AS CODIGO_COR   
    ,NULL  AS CODIGO_TAMANHO              
    ,ED.ERP_QTD_PACK AS QTD_PECAS        
    ,ED.QTD_PACK_TOTAL AS QTD_PACKS      
    ,GETDATE() AS DATA_CRIACAO_ORDEM   
    ,GETDATE() AS DATA_ENTREGA_ORDEM  
    ,NULL AS DATA_AGENDAMENTO_ORDEM  
    ,GETDATE() AS DATA_ULTIMA_ATUALIZACAO_ORDEM  
       ,LTRIM(RTRIM(SUBSTRING(P.TIPO_PRODUTO,1,4))) AS TIPO_CODIGO_ETIQUETA  
    ,CASE WHEN RTRIM(LTRIM(P.TIPO_PRODUTO)) = 'IMPORTADO' THEN 'I' ELSE 'N' END   AS CODIGO_FONTE_ORDEM      
    ,CAST(PP1.PRECO1 AS DECIMAL (18,2)) AS VALOR_VENDA   
    ,CAST(PP0.PRECO1 AS DECIMAL (18,2)) AS VALOR_CUSTO      
    ,NULL  AS QUANTIDADE_PECAS_PEDIDO   
    ,NULL AS QUANTIDADE_PACKS_PEDIDO       
    ,'0' AS CODIGO_ITEM_MAX_MIN       
    ,4 AS CODIGO_STATUS  
    ,(SELECT VW.COD_RETAGUARDA FROM PARAMETROS P WITH (NOLOCK)  INNER JOIN CGP_VW_UNIDADES VW WITH (NOLOCK) ON P.VALOR_ATUAL = VW.FILIAL WHERE PARAMETRO = 'PALMA_CD_ORIGEM_DISTRIB') AS CD_PADRAO  
    ,GETDATE() AS EMISSAO  
    ,NULL AS ERP_UNOUS_DATA_ENVIO    
    ,GETDATE() AS ENTREGA  
    ,SUBSTRING(LTRIM(RTRIM(P.TIPO_PRODUTO)),1,20) AS TIPO_PROD_COMPRA  
 FROM [CAEDU].[DBO].VW_DITRIBUICAO ED WITH (NOLOCK)      
   INNER JOIN [CAEDU].[DBO].PRODUTOS P WITH (NOLOCK)   
        ON P.PRODUTO = ED.PRODUTO                 
      INNER JOIN PROP_PRODUTOS PROP  
           ON PROP.PRODUTO = P.PRODUTO  
    AND PROPRIEDADE ='00108'   
             AND PROP.VALOR_PROPRIEDADE = 'SIM'          
      INNER JOIN [CAEDU].[DBO].PRODUTOS_PRECOS PP0 WITH (NOLOCK)  
        ON ED.PRODUTO = PP0.PRODUTO  
       AND PP0.CODIGO_TAB_PRECO = '00'   
      INNER JOIN [CAEDU].[DBO].PRODUTOS_PRECOS PP1 WITH (NOLOCK)  
           ON ED.PRODUTO = PP1.PRODUTO  
       AND PP1.CODIGO_TAB_PRECO = '01'  
       LEFT JOIN [CAEDU].[DBO].CADASTRO_CLI_FOR CF  
           ON P.FABRICANTE = CF.NOME_CLIFOR  
    AND LTRIM(RTRIM(UPPER(P.FABRICANTE))) <> 'MATRIZ'  
WHERE 1 = 1      
  AND ED.QTD_PACK_TOTAL > 0  
  AND ED.FILIAL = 'CD CAJAMAR'
GROUP BY   
        ISNULL(ED.PACK, 'A')  
    ,LTRIM(RTRIM(ED.PRODUTO))  
    ,LTRIM(RTRIM(SUBSTRING(P.TIPO_PRODUTO,1,4)))  
    ,CASE WHEN RTRIM(LTRIM(P.TIPO_PRODUTO)) = 'IMPORTADO' THEN 'I' ELSE 'N' END  
    ,CAST(PP1.PRECO1 AS DECIMAL (18,2))  
    ,CAST(PP0.PRECO1 AS DECIMAL (18,2))  
    ,ED.ERP_QTD_PACK  
    ,CF.COD_CLIFOR   
    ,ED.QTD_PACK_TOTAL   
    ,P.TIPO_PRODUTO  
  
  
GO


