USE [CAEDU]
GO

/****** Object:  View [dbo].[VW_DITRIBUICAO]    Script Date: 27/01/2021 09:34:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER VIEW [dbo].[VW_DITRIBUICAO] AS
SELECT PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE.PRODUTO,
       PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE.ESTOQUE,
       PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE.RESERVA,
       PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE.DISPONIVEL,
       PRODUTOS.GRIFFE,
       PRODUTOS.LINHA,
       PRODUTOS.GRUPO_PRODUTO,
       PRODUTOS.SUBGRUPO_PRODUTO,
       ISNULL(PRODUTOS.ERP_QTD_PACK,0) AS ERP_QTD_PACK,
       ISNULL(PRODUTOS.ERP_QTD_PACK,0)* PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE.DISPONIVEL AS QTD_PACK_TOTAL,
       MAX(x.data) AS ULTIMA_DISTRIBUICAO,
       DATEDIFF(DD,ISNULL(MAX(x.data),CONVERT(VARCHAR(8),GETDATE(),112)), CONVERT(VARCHAR(8),GETDATE(),112)) AS DIAS,
	   PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE.PACK,
	   PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE.FILIAL AS COD_FILIAL,
	   F.FILIAL AS FILIAL
FROM PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE
JOIN PRODUTOS ON PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE.PRODUTO = PRODUTOS.PRODUTO
LEFT JOIN (select produto, dt_atualizacao as data from PDA_WMS_TB_RESERVA_DISTRIBUICAO
                    union  all
                    select produto, data from caedu_reserva_automatica where  gerado = 1
                    ) X ON PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE.PRODUTO = X.PRODUTO
--PDA_WMS_TB_RESERVA_DISTRIBUICAO ON PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE.PRODUTO = PDA_WMS_TB_RESERVA_DISTRIBUICAO.PRODUTO
INNER JOIN FILIAIS F ON F.COD_FILIAL = PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE.FILIAL
GROUP BY PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE.PRODUTO,
         PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE.ESTOQUE,
         PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE.RESERVA,
         PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE.DISPONIVEL,
         PRODUTOS.GRIFFE,
         PRODUTOS.LINHA,
         PRODUTOS.GRUPO_PRODUTO,
         PRODUTOS.SUBGRUPO_PRODUTO,
         PRODUTOS.ERP_QTD_PACK,
		 PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE.PACK,
		 PDA_WMS_VW_SE_DISPONIBILIDADE_ESTOQUE.FILIAL,
		 F.FILIAL





GO


