/*
* SEQUENCIAIS ZANTHUS
* PARA HIERARQUIAS DE PRODUTO
*/

ALTER TABLE [dbo].[PRODUTOS_GRIFFES]
ADD COD_ZANTHUS VARCHAR(8) NULL, ID_ZANTHUS INT NULL
GO

ALTER TABLE [dbo].[PRODUTOS_LINHAS]
ADD COD_ZANTHUS VARCHAR(8) NULL, ID_ZANTHUS INT NULL
GO

ALTER TABLE [dbo].[PRODUTOS_GRUPO]
ADD COD_ZANTHUS VARCHAR(8) NULL, ID_ZANTHUS INT NULL
GO

ALTER TABLE [dbo].[PRODUTOS_SUBGRUPO]
ADD COD_ZANTHUS VARCHAR(8) NULL, ID_ZANTHUS INT NULL
GO

INSERT INTO SEQUENCIAIS (TABELA_COLUNA,DESCRICAO,SEQUENCIA,TAMANHO,DATA_PARA_TRANSFERENCIA,PERMITE_POR_EMPRESA)
VALUES ('ZANTHUS.COD_ZANTHUS','CODIGO SEQUENCIAL DO PDV ZANTHUS','00000000',8,GETDATE(),0)

declare @nEmpresa int, @NOVO_CODIGO VARCHAR(8)
set @nEmpresa = 1
SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'ZANTHUS.COD_ZANTHUS', @nEmpresa, @NOVO_CODIGO OUTPUT  
SELECT @NOVO_CODIGO AS COD_ZANTHUS

SELECT * FROM SEQUENCIAIS WHERE TABELA_COLUNA = 'ZANTHUS.COD_ZANTHUS'
