select 
NOME_CLIFOR
,CLIFOR
,CGC_CPF
,RAZAO_SOCIAL
,PJ_PF
,RG_IE
,UF
,COBRANCA_UF
,ENTREGA_UF
,COBRANCA_CGC
,CADASTRAMENTO
,COBRANCA_IE
,INDICA_FORNECEDOR
,INDICA_CLIENTE
,IND_REPRESENTANTE
,INDICA_FILIAL
,ENTREGA_CGC
,ENTREGA_IE
,INATIVO
,ISENTO_IPI
,ISENTO_ICMS
,ACEITA_DIAS_FIXO
,INCL_AUTO_GRP_ECON
,ENVIADO_SPC
,LX_STATUS_REGISTRO
,INDICA_CPRB
,ATIVIDADE_SIMPLES_NACIONAL
,CEP
,ENDERECO
,BAIRRO
,CIDADE
,TELEFONE1
,'BRASIL' AS PAIS
,DDI
,TELEFONE2
,FAX
,DDD1
,RAMAL1
,RAMAL2
,DDD2
,COBRANCA_ENDERECO
,COBRANCA_CIDADE
,COBRANCA_BAIRRO
,DDDFAX
,COBRANCA_CEP
,COBRANCA_TELEFONE
,ENTREGA_ENDERECO
,ENTREGA_CIDADE
,ENTREGA_BAIRRO
,ENTREGA_CEP
,ENTREGA_TELEFONE
,COBRANCA_DDD
,CONTATO
,ENTREGA_DDD
,REF_ANTERIOR
,DATA_PARA_TRANSFERENCIA
,'BRASIL' AS ENTREGA_PAIS
,'BRASIL' AS COBRANCA_PAIS
,IRRF
,ACEITA_AGRUPAR_FATURA
,NUMERO_VIAS_FATURA
,DIAS_ANTECIPACAO_PGTO
,POSSUI_RECARGO
,TIPO_RELACAO_COMERCIAL
,ENTREGA_RAZAO_SOCIAL
,COBRANCA_RAZAO_SOCIAL
,COD_CLIFOR
,INDICADOR_FISCAL_TERCEIRO
,AGRUPAMENTO_ITENS
,CODIGO_CONTATO
,NUMERO
,COMPLEMENTO
,COBRANCA_NUMERO
,COBRANCA_COMPLEMENTO
,ENTREGA_NUMERO
,ENTREGA_COMPLEMENTO
,COD_MUNICIPIO_IBGE
,COD_MUNICIPIO_IBGE_ENTREGA
,COD_MUNICIPIO_IBGE_COBRANCA
,EBS_ID_FORNECEDOR
,EBS_ID_LOCAL_FORNECEDOR
,EBS_ID_CLIENTE
,EBS_ID_LOCAL_CLIENTE
from cadastro_cli_for
where nome_clifor in 
('ALPARGATAS SA - 0305'
,'AQUINO INDUSTRIA E COMERC'
,'DAKOTA CALÇADOS S/A'
,'DAKOTA CALÇADOS S/A - 000'
,'DBTEX TEXTIL LTDA'
,'FLUXO CONFECÇÃO LTDA'
,'FORÇA DO SOL COMÉRCIO E C'
,'INDUSTRIA DE CALCADOS BLI'
,'KAPPES CONFECCOES LTDA'
,'LABISE LINGERIE LTDA'
,'MRKM COMERCIAL IMPORTADOR'
,'PEGOLIN CONFECCOES LTDA'
,'ROSSI CALCADOS LTDA'
,'SKYLINE IMPORTAÇÃO E EXPO'
,'VELOCE CALCADOS LTDA'
,'VZT INDUSTRIA E COMERCIO')
