
declare @tabfab table (fabricante varchar(25)) 
insert into @tabfab (fabricante) values ('ACIL AUTOMAÇÃO COML')
insert into @tabfab (fabricante) values ('ACIL TEXTIL')
insert into @tabfab (fabricante) values ('AD CRIACOES LINGERIE')
insert into @tabfab (fabricante) values ('AKAZZO INDUSTRIA DE 00021')
insert into @tabfab (fabricante) values ('AKIYOSHI')
insert into @tabfab (fabricante) values ('ALPARGATAS S.A. - 0109')
insert into @tabfab (fabricante) values ('ALPARGATAS S.A. - 0164')
insert into @tabfab (fabricante) values ('ALPARGATAS SA - 0305')
insert into @tabfab (fabricante) values ('ALTOMAX COMERCIO DE 00013')
insert into @tabfab (fabricante) values ('AMICI BRANDS INDUSTRIA E')
insert into @tabfab (fabricante) values ('AQUA TEXTIL LTDA')
insert into @tabfab (fabricante) values ('AQUINO INDUSTRIA E COMERC')
insert into @tabfab (fabricante) values ('ART BLU CONFECCOES')
insert into @tabfab (fabricante) values ('BEAUTY(ONEIDE CONFECCOES)')
insert into @tabfab (fabricante) values ('BELLA SEDA')
insert into @tabfab (fabricante) values ('Bertinelli Industria e Co')
insert into @tabfab (fabricante) values ('BIMBUS')
insert into @tabfab (fabricante) values ('BJU KIDS CONFECCOES LTDA')
insert into @tabfab (fabricante) values ('BLUETEX IND E COM DE CONF')
insert into @tabfab (fabricante) values ('BRASIL ATIVO IND E COM')
insert into @tabfab (fabricante) values ('BROOKS INDUSTRIA EIRELI')
insert into @tabfab (fabricante) values ('C M CALÇADOS EIRELI')
insert into @tabfab (fabricante) values ('CAJADAN TEXTIL LTDA')
insert into @tabfab (fabricante) values ('CALCADOS BEIRA RIO S/A -')
insert into @tabfab (fabricante) values ('CALCADOS BEIRA RIO S00042')
insert into @tabfab (fabricante) values ('CALCADOS BEIRA RIO S00069')
insert into @tabfab (fabricante) values ('CALCADOS BEIRA RIO S00158')
insert into @tabfab (fabricante) values ('CALCADOS BEIRA RIO S00301')
insert into @tabfab (fabricante) values ('CALCADOS BEIRA RIO S00360')
insert into @tabfab (fabricante) values ('CALCADOS BEIRA RIO S00395')
insert into @tabfab (fabricante) values ('CARLYLE DA MATTA ME')
insert into @tabfab (fabricante) values ('CATIVA MALHAS')
insert into @tabfab (fabricante) values ('CHICOTE IND. COM. DE ROUP')
insert into @tabfab (fabricante) values ('CLIO')
insert into @tabfab (fabricante) values ('CONFECCAO LCM CABRAL LTDA')
insert into @tabfab (fabricante) values ('CONFECCOES ARIELPS LTDA')
insert into @tabfab (fabricante) values ('CONFECÇÕES EDNA')
insert into @tabfab (fabricante) values ('CONFECCOES M & N DIAS LTD')
insert into @tabfab (fabricante) values ('CRIACOES J GIL LTDA - EPP')
insert into @tabfab (fabricante) values ('CROMUS EMBALAGENS IND E C')
insert into @tabfab (fabricante) values ('CROMUS EMBALAGENS IND. E')
insert into @tabfab (fabricante) values ('DAKOTA CALÇADOS S/A')
insert into @tabfab (fabricante) values ('DAKOTA CALÇADOS S/A - 000')
insert into @tabfab (fabricante) values ('DANDARA INDUSTRIA DE CALC')
insert into @tabfab (fabricante) values ('DBTEX CONFECÇÕES LTDA')
insert into @tabfab (fabricante) values ('DBTEX TEXTIL LTDA')
insert into @tabfab (fabricante) values ('DETRICK MALHAS INDUSTRIA')
insert into @tabfab (fabricante) values ('DEZALI')
insert into @tabfab (fabricante) values ('DIVA')
insert into @tabfab (fabricante) values ('DOCE ESTILO')
insert into @tabfab (fabricante) values ('DONNA')
insert into @tabfab (fabricante) values ('DYX COMERCIO E CONFECCOES')
insert into @tabfab (fabricante) values ('E.M.P CALCADOS LTDA EPP')
insert into @tabfab (fabricante) values ('ENNAFIE INDUSTRIA E COMER')
insert into @tabfab (fabricante) values ('ESCOBEL INDUSTRIA E COMER')
insert into @tabfab (fabricante) values ('ETILUX IMPORTACAO E 00087')
insert into @tabfab (fabricante) values ('FLORISMAR TEXTIL LTDA')
insert into @tabfab (fabricante) values ('FLUXO CONFECÇÃO LTDA')
insert into @tabfab (fabricante) values ('FORCA DO MAR')
insert into @tabfab (fabricante) values ('FORÇA DO SOL COMÉRCIO E C')
insert into @tabfab (fabricante) values ('GALEGO MALHAS LTDA')
insert into @tabfab (fabricante) values ('GIMARA CONFECCOES LTDA')
insert into @tabfab (fabricante) values ('GIMARA CONFECCOES LTDA')
insert into @tabfab (fabricante) values ('GLOBINHO CONFECÇÕES EIREL')
insert into @tabfab (fabricante) values ('GRENDENE S/A')
insert into @tabfab (fabricante) values ('HATRAKA CONFECCOES LTDA')
insert into @tabfab (fabricante) values ('HO-TEXTIL CONFECCOES LTDA')
insert into @tabfab (fabricante) values ('IMAGEM KIDS')
insert into @tabfab (fabricante) values ('INDUSTRIA DE CALCADOS BLI')
insert into @tabfab (fabricante) values ('INDUSTRIA DE CALÇADOS LAC')
insert into @tabfab (fabricante) values ('INDUSTRIA DE CALCADOS PLU')
insert into @tabfab (fabricante) values ('INDUSTRIA DE CALCADOS RAQ')
insert into @tabfab (fabricante) values ('INDUSTRIA DE CALCADOS RKM')
insert into @tabfab (fabricante) values ('INDUSTRIA E COMERCIO DE M')
insert into @tabfab (fabricante) values ('INDUSTRIA E COMERCIO DE R')
insert into @tabfab (fabricante) values ('INSTINTO INTIMO ARTIGOS D')
insert into @tabfab (fabricante) values ('J & P CONFECCOES')
insert into @tabfab (fabricante) values ('J S ROSA CALCADOS E VESTU')
insert into @tabfab (fabricante) values ('JANA JOUR')
insert into @tabfab (fabricante) values ('JEZZIAN')
insert into @tabfab (fabricante) values ('JEZZIAN 2')
insert into @tabfab (fabricante) values ('JINRRA CONFFECCOES LTDA')
insert into @tabfab (fabricante) values ('KAPPES CONFECCOES LTDA')
insert into @tabfab (fabricante) values ('KOMPORT')
insert into @tabfab (fabricante) values ('KOMPORT')
insert into @tabfab (fabricante) values ('KONTRATO INDUSTRIA E COME')
insert into @tabfab (fabricante) values ('LA CONFECÇÃO EIRELI')
insert into @tabfab (fabricante) values ('LABISE LINGERIE LTDA')
insert into @tabfab (fabricante) values ('LAPIN INDUSTRIA TEXTIL EI')
insert into @tabfab (fabricante) values ('LIV INTIMATE COMERCIO EXP')
insert into @tabfab (fabricante) values ('LOCAL SURF')
insert into @tabfab (fabricante) values ('LPM MALHAS LTDA - EPP')
insert into @tabfab (fabricante) values ('LUELUA CALÇADOS EIRELI EP')
insert into @tabfab (fabricante) values ('LUIZ ACACCIO TUMIOTO')
insert into @tabfab (fabricante) values ('LUPO')
insert into @tabfab (fabricante) values ('LUPO NORDESTE LTDA')
insert into @tabfab (fabricante) values ('LUXCEL')
insert into @tabfab (fabricante) values ('LX TEXTIL')
insert into @tabfab (fabricante) values ('M & D MODAS FASHION LTDA')
insert into @tabfab (fabricante) values ('M CAFF CONFECÇÕES')
insert into @tabfab (fabricante) values ('M.G.S.')
insert into @tabfab (fabricante) values ('MALEIKO CONFECCOES EIRELI')
insert into @tabfab (fabricante) values ('MAR - QUENTE CONFECC00066')
insert into @tabfab (fabricante) values ('MARIA MULHER')
insert into @tabfab (fabricante) values ('MASH')
insert into @tabfab (fabricante) values ('MASTER C R N INDUSTRIA E')
insert into @tabfab (fabricante) values ('MASTER C R N INDUSTRIA E')
insert into @tabfab (fabricante) values ('MATRIZ')
insert into @tabfab (fabricante) values ('MC JO')
insert into @tabfab (fabricante) values ('META INDUSTRIA DE CALÇADO')
insert into @tabfab (fabricante) values ('MINAS BAHIA INDUSTRIA E C')
insert into @tabfab (fabricante) values ('MJ TIETE CONFECCOES LIMIT')
insert into @tabfab (fabricante) values ('MKR')
insert into @tabfab (fabricante) values ('MKR')
insert into @tabfab (fabricante) values ('MRKM COMERCIAL IMPORTADOR')
insert into @tabfab (fabricante) values ('NATIVO/BLUEWAVE')
insert into @tabfab (fabricante) values ('NOUK INDUSTRIA E COMERCIO')
insert into @tabfab (fabricante) values ('ONEFLIP INDUSTRIA E COMER')
insert into @tabfab (fabricante) values ('PARADOX')
insert into @tabfab (fabricante) values ('PARS INDUSTRIA E COMERCIO')
insert into @tabfab (fabricante) values ('PAXA')
insert into @tabfab (fabricante) values ('PDG INDUSTRIA E COMERCIO')
insert into @tabfab (fabricante) values ('PEGOLIN CONFECCOES LTDA')
insert into @tabfab (fabricante) values ('PF2 CONFECCOES EIRELI')
insert into @tabfab (fabricante) values ('PRISMA TEXTIL INDUSTRIA E')
insert into @tabfab (fabricante) values ('PSA')
insert into @tabfab (fabricante) values ('RC CONFECÇÃO LTDA')
insert into @tabfab (fabricante) values ('RECOLLETA INDUSTRIA E COM')
insert into @tabfab (fabricante) values ('REGINALDO FERNANDES FERRE')
insert into @tabfab (fabricante) values ('RENALUCI CONFECCOES EIREL')
insert into @tabfab (fabricante) values ('REPUBLICA DO SOL')
insert into @tabfab (fabricante) values ('RHP - INDUSTRIA E COMERCI')
insert into @tabfab (fabricante) values ('ROSSI CALCADOS LTDA')
insert into @tabfab (fabricante) values ('ROVITEX')
insert into @tabfab (fabricante) values ('ROVITEX - INDUSTRIA E COM')
insert into @tabfab (fabricante) values ('S4 CONFECÇÕES LTDA ME')
insert into @tabfab (fabricante) values ('SAWARY')
insert into @tabfab (fabricante) values ('SAWARY 2')
insert into @tabfab (fabricante) values ('SEMAX')
insert into @tabfab (fabricante) values ('SK INDUSTRIA DE CALÇADOS')
insert into @tabfab (fabricante) values ('SKYLINE IMPORTAÇÃO E EXPO')
insert into @tabfab (fabricante) values ('SLINKS CONFECCOES EIRELI')
insert into @tabfab (fabricante) values ('SOUZA & CAMBOS CONFE00016')
insert into @tabfab (fabricante) values ('SPORT SUL')
insert into @tabfab (fabricante) values ('SPORT SUL MALHAS')
insert into @tabfab (fabricante) values ('SRJ')
insert into @tabfab (fabricante) values ('STAR FEET CALÇADOS DE IND')
insert into @tabfab (fabricante) values ('T DISTRIBUIDORA LTDA')
insert into @tabfab (fabricante) values ('TEXTIL BRASIL IMP E EXP D')
insert into @tabfab (fabricante) values ('TEXTIL SANTA RITA')
insert into @tabfab (fabricante) values ('THE STYLE BOX IMPORTACAO')
insert into @tabfab (fabricante) values ('THREE HANDS COMERCIO E CO')
insert into @tabfab (fabricante) values ('TOP KIDS CONFECCOES LTDA')
insert into @tabfab (fabricante) values ('TOP ROCK')
insert into @tabfab (fabricante) values ('TOP ROCK INDUSTRIA TEXTIL')
insert into @tabfab (fabricante) values ('TRICOT N & E')
insert into @tabfab (fabricante) values ('TURMA LEGAL CONFECÇÕES LT')
insert into @tabfab (fabricante) values ('UZ3 INDUSTRIA')
insert into @tabfab (fabricante) values ('VELOCE CALCADOS LTDA')
insert into @tabfab (fabricante) values ('VIA VIP CALCADOS LTDA')
insert into @tabfab (fabricante) values ('VICTOR BLUE')
insert into @tabfab (fabricante) values ('VINICIUS DE MARIO ESVICER')
insert into @tabfab (fabricante) values ('VISTON CONFECCOES LTDA')
insert into @tabfab (fabricante) values ('VULCABRAS BA CALCADOS E A')
insert into @tabfab (fabricante) values ('VULCABRAS CE CALCADOS E A')
insert into @tabfab (fabricante) values ('VZT INDUSTRIA E COMERCIO')
insert into @tabfab (fabricante) values ('YD Confecções Ltda')
insert into @tabfab (fabricante) values ('YELLOW COMERCIO E INDUSTR')
insert into @tabfab (fabricante) values ('YENDS')
insert into @tabfab (fabricante) values ('ZHORK INDUSTRIA E COMERCI')
insert into @tabfab (fabricante) values ('ZIPYLIK')


select a.fabricante, b.fornecedor
from @tabfab a
left join FORNECEDORES b on b.fornecedor = a.fabricante
where b.FORNECEDOR is null
