

declare @nEmpresa int, @NOVO_CODIGO VARCHAR(8)
set @nEmpresa = 1
SET @NOVO_CODIGO = ''
EXEC LX_SEQUENCIAL 'CAEDU_REMARCACAO_PRECOS.PROCESS_ID', @nEmpresa, @NOVO_CODIGO OUTPUT  
SELECT @NOVO_CODIGO AS PROCESS_ID

SELECT * FROM SEQUENCIAIS WHERE TABELA_COLUNA = 'CAEDU_REMARCACAO_PRECOS.PROCESS_ID'

