/*
ROTINA PARA SUBIR TABELA EXCEL 3 COLUNAS VIA BANCO DE DADOS
PAULO DEVIDE
24-09-2024
select * from dbo.CAEDU_REMARCACAO_PRECOS a
where a.EXECUTION_DATE_TIME is null 

select getdate()+11

*/ 
SET NOCOUNT ON
 

declare @sequencia varchar(8)=''
EXEC LX_SEQUENCIAL 
@TABELA_COLUNA= 'CAEDU_REMARCACAO_PRECOS.PROCESS_ID', 
@EMPRESA= 1, 
@SEQUENCIA= @SEQUENCIA OUTPUT

declare @N_DIAS INT = 11 -- esta variavel soma em cima de getdate() 
						-- se quero amanhã, setar para 1, se quero para depois de amanhã setar pra 2 e assim por diante

declare @PROCESS_ID char(8) = @sequencia,
@CREATED_AT datetime = GETDATE()+@N_DIAS,
@LAST_MODIFIED datetime  = GETDATE()+@N_DIAS,
@SCHEDULING_DATE datetime = CONVERT(VARCHAR,GETDATE()+@N_DIAS,112),
@SCHEDULING_TIME varchar(5) = '23:00',
@SCHEDULING_USER VARCHAR(25) = 'CCP\PAULO.DEVIDE',
@NUMBER_COLUMNS SMALLINT = 2, -- 3 COLUNAS
@EXECUTION_DATE_TIME DATETIME = NULL

/*INSERT NA TABELA PAI COM OS DADOS DEFINIDOS NAS VARIAVEIS */
INSERT INTO CAEDU_REMARCACAO_PRECOS (PROCESS_ID,CREATED_AT,LAST_MODIFIED,SCHEDULING_DATE,
										SCHEDULING_TIME,SCHEDULING_USER,NUMBER_COLUMNS,EXECUTION_DATE_TIME)
VALUES  (@PROCESS_ID,@CREATED_AT,@LAST_MODIFIED,@SCHEDULING_DATE,
										@SCHEDULING_TIME,@SCHEDULING_USER,@NUMBER_COLUMNS,@EXECUTION_DATE_TIME)

/*VARIAVEIS DA TABELA FILHA*/
DECLARE @CODIGO_TAB_PRECO CHAR(2), @PRODUTO CHAR(12), @PRECO1 NUMERIC(14,2)

/*DEFINE VARIAVEL TABELA PARA ARMAZENAR PRODUTOS DO EXCEL*/
DECLARE @TABPRO TABLE 
(ID INT IDENTITY(1,1) PRIMARY KEY, 
CODIGO_TAB_PRECO CHAR(2),
PRODUTO CHAR(12), 
PRECO NUMERIC(14,2))

/*INSERE OS DADOS DO EXCEL NA VARIAVEL TABELA TEMPORARIA*/
INSERT INTO @TABPRO (CODIGO_TAB_PRECO,PRODUTO,PRECO) VALUES ('63','Z2010464',9.99);
INSERT INTO @TABPRO (CODIGO_TAB_PRECO,PRODUTO,PRECO) VALUES ('63','Z2010278',9.99);

/*FIM INSERE OS DADOS */

DECLARE @MIN INT, @MAX INT
SELECT @MIN=MIN(ID),@MAX=MAX(ID) FROM @TABPRO

WHILE @MIN <= @MAX
BEGIN
	PRINT @MIN

	SELECT @PRODUTO=PRODUTO, @PRECO1=PRECO, @CODIGO_TAB_PRECO = CODIGO_TAB_PRECO
	FROM @TABPRO WHERE ID = @MIN

	INSERT INTO CAEDU_REMARCACAO_PRECOS_ITENS (PROCESS_ID, CODIGO_TAB_PRECO, PRODUTO, PRECO1)
	values (@PROCESS_ID, @CODIGO_TAB_PRECO, @PRODUTO, @PRECO1)


	SET @MIN += 1
END

SET NOCOUNT OFF
