create table dbo.CAEDU_REMARCACAO_PRECOS (
PROCESS_ID				CHAR(8)  NOT NULL
,CREATED_AT 			DATETIME NOT NULL
,LAST_MODIFIED			DATETIME NOT NULL
,SCHEDULING_DATE		DATETIME NOT NULL
,SCHEDULING_TIME		VARCHAR(5) NOT NULL
,SCHEDULING_USER		VARCHAR(25) NOT NULL
,NUMBER_COLUMNS			SMALLINT NOT NULL
,EXECUTION_DATE_TIME	DATETIME NULL
,CONSTRAINT PK_CAEDU_REMARCACAO_PRECOS PRIMARY KEY (PROCESS_ID))
GO

create table dbo.CAEDU_REMARCACAO_PRECOS_ITENS (
PROCESS_ID			CHAR(8) NOT NULL
,CODIGO_TAB_PRECO	CHAR(2) NOT NULL
,PRODUTO			CHAR(12) NOT NULL 
,PRECO1				NUMERIC(14,2) NOT NULL
,CONSTRAINT PK_CAEDU_REMARCACAO_PRECOS_ITENS PRIMARY KEY (PROCESS_ID, CODIGO_TAB_PRECO, PRODUTO)
,CONSTRAINT FK_CAEDU_REMARCACAO_PRECOS_PROCESS_ID FOREIGN KEY (PROCESS_ID) 
REFERENCES DBO.CAEDU_REMARCACAO_PRECOS (PROCESS_ID)
,CONSTRAINT FK_CAEDU_REMARCACAO_PRECOS_PRODUTO FOREIGN KEY (PRODUTO) /* VALIDA CONTRA TABELA DE PRODUTOS*/
REFERENCES DBO.PRODUTOS (PRODUTO)
,CONSTRAINT FK_CAEDU_REMARCACAO_PRECOS_CODIGO_TAB_PRECO FOREIGN KEY (CODIGO_TAB_PRECO) /* VALIDA CONTRA TABELA TABELAS_PRECO*/
REFERENCES DBO.TABELAS_PRECO (CODIGO_TAB_PRECO)
)
GO

create TABLE dbo.CAEDU_REMARCACAO_PRECOS_HORARIOS
( HORA INT, ATIVO bit)
go


insert into dbo.CAEDU_REMARCACAO_PRECOS_HORARIOS
values (0,1),
 (1,1),
 (2,1),
 (3,1),
 (4,1),
 (5,1),
 (6,1),
 (7,1),
 (8,1),
 (9,1),
 (10,1),
 (11,1),
 (12,1),
 (13,1),
 (14,1),
 (15,1),
 (16,1),
 (17,1),
 (18,1),
 (19,1),
 (20,1),
 (21,1),
 (22,1),
 (23,1)

go
--DROP table dbo.CAEDU_REMARCACAO_PRECOS_ITENS
--DROP table dbo.CAEDU_REMARCACAO_PRECOS




