SELECT CAST(1 AS BIT) AS SELECAO, PACK,PRODUTO,NF,SERIE,A.ID_COLETA ETIQUETA,B.STATUS
 FROM  PDA_WMS_TB_RECEBIMENTO_IMPORTADO_COLETA A 
 INNER JOIN PDA_WMS_TB_REC_CD_STATUS_RECEBIMENTO B  
 ON (LTRIM(RTRIM(A.NF))+' '+LTRIM(RTRIM(SERIE)) = B.PEDIDO) WHERE B.STATUS>=3 
 AND A.NF='000008409' AND SERIE='02' 


 select * from PDA_WMS_TB_REC_CD_STATUS_RECEBIMENTO where pedido = '000008409 02'

 update PDA_WMS_TB_REC_CD_STATUS_RECEBIMENTO 
 set status = 3
 where pedido = '000008409 02'