SELECT
     B.SK_DIA
    ,B.SK_FILIAL
    ,B.SK_PRODUTO
    ,LTRIM(RTRIM(C.COD_PRODUTO))        AS COD_PRODUTO
    ,B.SK_PRODUTO_CORES   
    ,B.PRECO_CONTABIL                    AS PRECO_CONTABIL_ESTOQUE
    ,B.QTD_ESTOQUE
    ,CASE
        WHEN
            A.SK_IMPORTACAO IN (0,2,3,4,5,7,8) AND A.SK_FILIAL IN (76,8,19,14,9,78,134) --FILLIAL ENTRADA
        THEN
            (B.CUSTO) * (1 - 0.2125)
        WHEN
            A.SK_IMPORTACAO IN (0,2,3,4,5,7,8) AND A.SK_FILIAL IN (6,100,131) --FILLIAL ENTRADA
        THEN
            (B.CUSTO) * (1 - 0.2625)
        WHEN
            A.SK_IMPORTACAO IN (1,6)
        THEN
            (B.CUSTO) * (1 - 0.1325)
        ELSE 0
    END CUSTO_SEM_IMPOSTO
FROM
    FAT_PRIMEIRA_ENT A
INNER JOIN
    FAT_ESTOQUE B
ON
    A.SK_PRODUTO = B.SK_PRODUTO
INNER JOIN
    DIM_PRODUTO C
ON
    B.SK_PRODUTO = C.SK_PRODUTO
WHERE
    B.SK_DIA = CAST(CONVERT(VARCHAR(8),GETDATE()-1,112) AS INT)