--select * from tabelas_preco where codigo_tab_preco = 'A0'



DECLARE @TABELA VARCHAR(2) = 'A3' --PRACA DA MOCA

insert into 
PRODUTOS_PRECOS	(CODIGO_TAB_PRECO, PRODUTO, PRECO1, PRECO2,PRECO3,PRECO4, 
ULT_ATUALIZACAO, DATA_PARA_TRANSFERENCIA) 

SELECT @TABELA as CODIGO_TAB_PRECO, PP.PRODUTO, PP.PRECO1,
0 AS PRECO2,0 AS PRECO3, 0 AS PRECO4, 
GETDATE() AS ULT_ATUALIZACAO, GETDATE() AS DATA_PARA_TRANSFERENCIA

FROM (
select cp.PRODUTO
from COMPRAS c
inner join COMPRAS_PRODUTO cp on cp.pedido=c.pedido
where c.EMISSAO> dateadd(dd,-730,getdate())

UNION ALL
SELECT LVP.PRODUTO 
FROM LOJA_VENDA LV
INNER JOIN LOJA_VENDA_PRODUTO LVP ON LVP.DATA_VENDA=LV.DATA_VENDA 
										AND LVP.CODIGO_FILIAL=LV.CODIGO_FILIAL
										AND LVP.TICKET = LV.TICKET
WHERE LV.DATA_VENDA > dateadd(dd,-730,getdate())
) AS TAB1 

INNER JOIN PRODUTOS_PRECOS PP ON PP.PRODUTO=TAB1.PRODUTO AND PP.CODIGO_TAB_PRECO='11'

where TAB1.PRODUTO NOT IN (Select produto from produtos_precos where CODIGO_TAB_PRECO=@TABELA)

GROUP BY PP.CODIGO_TAB_PRECO, PP.PRODUTO, PP.PRECO1






