--Terminal	Codigo_filial	Filial	Numero_cupom_fiscal	Data_venda	mês/Ano	ano	Lancamento_caixa	Nf_entrada	Serie_nf_entrada	Produto	Cor_produto	Desc_produto	Qtde	 Custo1 	Enb_codigo_barra

select 
	CAST(B.EMISSAO AS DATE) AS EMISSAO_NF, 
	A.ENB_TERMINAL AS TERMINAL,
	A.ENB_CODIGO_FILIAL AS CODIGO_FILIAL,
	A.FILIAL AS FILIAL,
	A.ENB_COO AS NUMERO_CUPOM_FISCAL,
	CAST(A.EMISSAO AS DATE) AS DATA_VENDA,
	A.ROMANEIO_PRODUTO AS LANCAMENTO_CAIXA,
	A.NF_ENTRADA AS NF_ENTRADA,
	A.SERIE_NF_ENTRADA AS SERIE_NF_ENTRADA,
	P.PRODUTO AS PRODUTO,
	P.COR_PRODUTO AS COR_PRODUTO,
	PR.DESC_PRODUTO AS DESC_PRODUTO,
	P.QTDE AS QTDE,
	P.CUSTO1 AS CUSTO1,
	P.ENB_CODIGO_BARRA AS CODIGO_BARRA

from 
	estoque_prod_ent A (NOLOCK)
INNER JOIN 
	ENTRADAS B (NOLOCK)
		ON B.NF_ENTRADA = A.NF_ENTRADA 
			AND B.SERIE_NF_ENTRADA = A.SERIE_NF_ENTRADA
			AND B.NOME_CLIFOR = A.FILIAL
INNER JOIN estoque_prod1_ent P 
	ON P.ROMANEIO_PRODUTO = A.ROMANEIO_PRODUTO 
		AND P.FILIAL = A.FILIAL
INNER JOIN PRODUTOS PR
	ON PR.PRODUTO = P.PRODUTO

where 
	A.responsavel = 'INTEGRAÇÃO.EMSEMBLE'
	and A.TIPO_ROMANEIO = 'DEVOLUCAO DE VENDA'
	and A.CM_OPERACAO = '005'
	AND A.EMISSAO>='20160101' AND A.EMISSAO <= '20161231'
	AND (B.EMISSAO >= '20170101' AND B.EMISSAO <= '20170131') 
	AND B.NATUREZA = '250.01'
ORDER BY a.ROMANEIO_PRODUTO, a.FILIAL, p.PRODUTO, p.COR_PRODUTO



SELECT P.* 
FROM ESTOQUE_PROD_ENT a
INNER JOIN ESTOQUE_PROD1_ENT P ON P.ROMANEIO_PRODUTO = A.ROMANEIO_PRODUTO AND P.FILIAL = A.FILIAL
WHERE a.FILIAL='IPIRANGA' 
		AND a.ENB_TERMINAL='012' 
		AND a.EMISSAO='20150915' 
		AND a.ROMANEIO_PRODUTO = '000028'


--SELECT EMISSAO,* 
--FROM ENTRADAS
--WHERE NF_ENTRADA = '000026089'
--AND SERIE_NF_ENTRADA = '02'
--AND NOME_CLIFOR = 'POA'


/*
select TOP 100 A.* 
from 
	ENTRADAS A (NOLOCK)
INNER JOIN 
	ESTOQUE_PROD_ENT B (NOLOCK)
		ON B.NF_ENTRADA = A.NF_ENTRADA 
			AND B.SERIE_NF_ENTRADA = A.SERIE_NF_ENTRADA
			AND B.NOME_CLIFOR = A.NOME_CLIFOR
			AND B.responsavel = 'INTEGRAÇÃO.EMSEMBLE'
			AND B.TIPO_ROMANEIO = 'DEVOLUCAO DE VENDA'
			AND B.CM_OPERACAO = '005'
where 
	YEAR(B.EMISSAO)=2016
	AND (A.EMISSAO >= '20170101' AND A.EMISSAO <= '20170131') 
--	AND A.NATUREZA = '250.01'
*/

