--select convert(varchar,data,112) as data, count(*) as qty 
--from CSM_TRANSITO_NOTAS 
--where data between '20211101' and '20211211'
--group by convert(varchar,data,112)
--order by 1

select *
from CSM_TRANSITO_NOTAS 
where data between '20211201' and '20211211'
order by 1


select C.*,
	b.FILIAL
	,b.NF_SAIDA
	,b.SERIE_NF
	,TIPO_FATURAMENTO
	,b.NOME_CLIFOR
	,CONDICAO_PGTO
	,NATUREZA_SAIDA
	,TRANSPORTADORA
	,TRANSP_REDESPACHO
	,TIPO_FRETE
	,EMISSAO
	,DATA_SAIDA
	,FRETE
	,SEGURO
	,DESCONTO
	,DESCONTO_COND_PGTO
	,ENCARGO
	,ICMS
	,IPI_VALOR
	,VALOR_TOTAL
	,QTDE_TOTAL
	,NOTA_CANCELADA
	,ICMS_BASE
	,STATUS_TRANSITO
	,DATA_CANCELAMENTO
	,VALOR_CANCELADO
	,QTDE_CANCELADA
	DATA_PARA_TRANSFERENCIA
	,VALOR_ADICIONAL
	,IPI_ADICIONAL
	,ICMS_ISENTO
	,ICMS_OUTROS
	,VALOR_SUB_ITENS
	,CHAVE_NFE
	,PROTOCOLO_CANCELAMENTO_NFE
	,DATA_AUTORIZACAO_NFE
	,STATUS_NFE
	,MOTIVO_CANCELAMENTO_NFE
from CSM_TRANSITO_NOTAS a
inner join FATURAMENTO b 
	on b.FILIAL = a.FILIAL and b.SERIE_NF = a.SERIE_NF and b.NF_SAIDA = a.NF_SAIDA
inner join FATURAMENTO_IMPOSTO c 
	ON C.NF_SAIDA=B.NF_SAIDA AND C.FILIAL = B.FILIAL AND C.SERIE_NF = B.SERIE_NF AND C.ID_IMPOSTO = 1
where (b.EMISSAO between '20211201' and '20211211')





select a.FILIAL, a.NOME_CLIFOR, a.NF_SAIDA, a.SERIE_NF, a.NATUREZA_SAIDA, a.VALOR_TOTAL, a.EMISSAO, a.DATA_SAIDA, C.* 
from faturamento A
INNER JOIN faturamento_prod B on b.NF_SAIDA=a.NF_SAIDA AND b.FILIAL = a.FILIAL AND b.SERIE_NF = a.SERIE_NF
inner join FATURAMENTO_IMPOSTO c 
	ON C.NF_SAIDA=B.NF_SAIDA AND C.FILIAL = B.FILIAL AND C.SERIE_NF = B.SERIE_NF AND 
		b.ITEM_IMPRESSAO = c.ITEM_IMPRESSAO and C.ID_IMPOSTO = 1
where (a.EMISSAO between '20211201' and '20211211') and a.filial = 'CD BARRA VELHA' AND a.NOME_CLIFOR='CD CAJAMAR'

