SELECT	top 1
		a.produto, D.FILIAL, D.NF_ENTRADA, D.PEDIDO, D.NOME_CLIFOR, A.FABRICANTE, D.EMISSAO, B.PRECO1 AS CUSTO_00,
		CASE
        WHEN
            A.TRIBUT_ORIGEM IN (0,2,3,4,5,7,8) 
				AND D.FILIAL IN ('CAJAMAR - CQ','CD CAJAMAR','CD CAJAMAR - ATACADO','CD CAMAJAR - ATACADO','LOJA VIRTUAL',
									'REJEITADO - CD CAJAMAR','REJEITADO - LOJA VIRTUAL','VENDA ATACADO','VENDA IMP 2021') 
        THEN
            (B.PRECO1) * (1 - 0.2125)
        WHEN
            A.TRIBUT_ORIGEM IN (0,2,3,4,5,7,8) AND D.FILIAL IN ('CD NAVEGANTES','NAVEGANTES CQ','VENDA ATACADO SC','CD BARRA VELHA') 
        THEN
            (B.PRECO1) * (1 - 0.2625)
        WHEN
            A.TRIBUT_ORIGEM IN (1,6)
        THEN
            (B.PRECO1) * (1 - 0.1325)
        ELSE 0
    END CUSTO_SEM_IMPOSTO, a.TRIBUT_ORIGEM
FROM
    produtos A
INNER JOIN
    PRODUTOS_PRECOS B
ON
    B.PRODUTO = A.PRODUTO AND B.CODIGO_TAB_PRECO = '00'
INNER JOIN
    ESTOQUE_PROD1_ENT C
ON
    C.PRODUTO = A.PRODUTO
INNER JOIN
    ESTOQUE_PROD_ENT D
ON
    D.ROMANEIO_PRODUTO = C.ROMANEIO_PRODUTO AND D.FILIAL = C.FILIAL
WHERE
    A.PRODUTO = 'J4010013' AND ISNULL(D.NF_ENTRADA,'')<>''  AND ISNULL(D.PEDIDO,'')<>''
ORDER BY EMISSAO DESC


select top 1 produto from produtos_barra where CODIGO_BARRA = 'J40100130000301'


exec PDA_AP_SP_SE_PRODUTO_SORTIMENTO
 @FILIAL ='VILA FORMOSA',
 @COD_BARRA ='J40100130000301',
 @USUARIO = 1,
 @TP_TECNOLOGIA ='',
 @IMEI  = ''

 --SELECT * 
 --update a set preco1 = 19.99
 --FROM PRODUTOS_PRECOS a WHERE PRODUTO = 'J4010013' AND CODIGO_TAB_PRECO='44'
