SELECT 
		e.NOME_CLIFOR,
		e.FILIAL,
		e.NF_ENTRADA,
		e.SERIE_NF_ENTRADA,
		e.COD_TRANSACAO,
		ep.PEDIDO,
		C.CONDICAO_PGTO,
		CONVERT(VARCHAR,C.EMISSAO,103) AS EMISSAO, 
		C.PEDIDO_FORNECEDOR,
		CAST(C.TOT_QTDE_ORIGINAL AS INT) AS TOT_QTDE_ORIGINAL,
		CAST(C.TOT_VALOR_ORIGINAL AS NUMERIC(12,2)) AS TOT_VALOR_ORIGINAL,
		C.ERP_CUPS_TIPO_PEDIDO,
		C.ERP_CUPS_SEGMENTO,
		CONVERT(VARCHAR,C.ERP_CUPS_DATA_ACORDADA,103) AS DATA_ACORDADA,
		CONVERT(VARCHAR,C.ERP_CUPS_EMBARQUE_ATUAL,103) AS EMBARQUE_ATUAL,
		CONVERT(VARCHAR,C.ERP_CUPS_EMBARQUE_REAL,103) AS EMBARQUE_REAL,
		C.ERP_CUPS_CONTRATO,
		CONVERT(VARCHAR,C.ERP_CUPS_CHEGADA_PORTO,103) AS CHEGADA_PORTO,
		CONVERT(VARCHAR,C.ERP_CUPS_CHEGADA_CD,103) AS CHEGADA_CD,
		C.ERP_CUPS_PROCESSO_CCF_CCA,
		C.ERP_TOTAL_CAIXAS_ORIGINAL,
		CONVERT(VARCHAR,CP.ENTREGA,103) AS ENTREGA,
		CONVERT(VARCHAR,CP.LIMITE_ENTREGA,103) AS LIMITE_ENTREGA,
		CP.QTDE_ORIGINAL,
		P.PRODUTO,
		P.ERP_CUPS_STYLENUMBER
FROM ENTRADAS E
INNER JOIN ENTRADAS_PRODUTO EP 
	ON EP.NF_ENTRADA = E.NF_ENTRADA AND
		EP.SERIE_NF_ENTRADA = E.SERIE_NF_ENTRADA AND
		EP.NOME_CLIFOR = E.NOME_CLIFOR 
INNER JOIN COMPRAS C ON C.PEDIDO = EP.PEDIDO
INNER JOIN COMPRAS_PRODUTO CP 
	ON CP.PEDIDO = EP.PEDIDO AND CP.PRODUTO = EP.PRODUTO AND CP.COR_PRODUTO = EP.COR_PRODUTO
INNER JOIN PRODUTOS P ON P.PRODUTO = EP.PRODUTO
WHERE      E.emissao >= '20180101' 
AND        E.emissao <= '20181231' 
AND        E.nome_clifor = 'KOMPORT' 
AND        E.cod_transacao = 'ENTRADAS_102' 


