
DECLARE @LOJA VARCHAR(25), @QTDE_TOTAL INT

SET @LOJA = 'SP - PIRAPORINHA'

SET @QTDE_TOTAL = 108

SELECT CHAVE_NFE, NF_SAIDA, SERIE_NF, FILIAL, NOME_CLIFOR, A.QTDE_TOTAL, EMISSAO, STATUS_NFE
FROM FATURAMENTO A
WHERE FILIAL='CD - SP - SAO ROQUE'      
AND EMISSAO=CONVERT(VARCHAR,GETDATE(),112)
AND NOME_CLIFOR=@LOJA
AND QTDE_TOTAL=@QTDE_TOTAL

