


select	COMPRAS_PROD_CANCELADA.Pedido,
		COMPRAS_PROD_CANCELADA.Produto,	
		COMPRAS_PROD_CANCELADA.Cor_produto,
		COMPRAS_PROD_CANCELADA.Qtde_cancelada,	
		Data,	
		Griffe,	
		Linha,
		Grupo_produto,	
		Subgrupo_produto,
		'|' AS Exp, 
		COMPRAS_PRODUTO.pedido as Pedido1,	
		COMPRAS_PRODUTO.Entrega,	
		COMPRAS_PRODUTO.Limite_entrega,	
		COMPRAS_PRODUTO.Qtde_original,	
		COMPRAS_PRODUTO.Qtde_entregue,	
		COMPRAS_PRODUTO.Qtde_entregar,	
		COMPRAS_PRODUTO.Qtde_cancelada as Qtde_cancelada1,	
		COMPRAS_PRODUTO.Custo1,	
		COMPRAS_PRODUTO.Valor_original,
		'|' AS Exp1,
		COMPRAS.REQUERIDO_POR, 
		COMPRAS.APROVADO_POR,
		COMPRAS.EMISSAO
from COMPRAS_PROD_CANCELADA
inner join PRODUTOS ON PRODUTOS.PRODUTO = COMPRAS_PROD_CANCELADA.PRODUTO
inner join COMPRAS_PRODUTO ON COMPRAS_PRODUTO.PEDIDO = COMPRAS_PROD_CANCELADA.PEDIDO 
								AND COMPRAS_PRODUTO.PRODUTO = COMPRAS_PROD_CANCELADA.PRODUTO
								AND COMPRAS_PRODUTO.COR_PRODUTO = COMPRAS_PROD_CANCELADA.COR_PRODUTO
inner join COMPRAS ON COMPRAS.PEDIDO = COMPRAS_PROD_CANCELADA.PEDIDO
WHERE COMPRAS_PROD_CANCELADA.QTDE_CANCELADA>0
ORDER BY COMPRAS.EMISSAO, COMPRAS.PEDIDO
