select * 
--into dbo.bkp_produtos_envia_varejo_internet
update a set ENVIA_VAREJO_INTERNET=1
from produtos a where 1=1 --ENVIA_VAREJO_INTERNET=1 --and data_cadastramento<'20220901'
and produto in (
select top 300 produto
from W_ESTOQUE_PRODUTOS_00 where 1=1 and filial='LOJA VIRTUAL'
--AND PRODUTO IN (SELECT PRODUTO FROM PRODUTOS WHERE ENVIA_VAREJO_INTERNET=1)
and estoque<>0)


select produto,COR_PRODUTO, filial, estoque from W_ESTOQUE_PRODUTOS_00 where 1=1 and filial='LOJA VIRTUAL' 
AND PRODUTO IN (SELECT PRODUTO FROM PRODUTOS WHERE ENVIA_VAREJO_INTERNET=1)




SELECT 
		NOME_CLIFOR,NF_ENTRADA,TIPO_ENTRADAS,LANCAMENTO,
		F.COD_FILIAL,FILIAL_ENTRADA,COD_TRANSACAO ,
		NATUREZA,NATUREZA_CONTABILIZAR,CONDICAO_PGTO,
		SERIE_NF,RECEBIMENTO,NF_FATURA,EMISSAO,FATURA,FRETE,
		SEGURO,ACERTO_CONTAS_P_R ,DESCONTO,ENCARGO,NF_PROPRIA_EMITIDA,
		IPI_VALOR,ICMS_BASE,ICMS_VALOR,QTDE_TOTAL,QTDE_TOTAL_AUX,
		VALOR_TOTAL,TABELA_FILHA,TRANSF_FILIAL ,DEVOLUCAO,
		NF_ENTRADA_PROPRIA,MARCA_EXPORTACAO,ATUALIZACAO_EXPORTAR,
		DATA_EXPORTACAO,STATUS_TRANSITO,FRETE_A_PAGAR,TRANSPORTADORA_A_PAGAR ,
		VALOR_FRETE_TRANSPORTADORA,NF_ENTRADA_CONHECIMENTO,MOEDA,MOEDA_COMPRA,
		CAMBIO_NA_DATA,IMPORTACAO,IMPORTACAO_IMPOSTO,IMPORTACAO_ICMS ,
		IMPORTACAO_IPI,IMPORTACAO_ALFANDEGA,IMPORTACAO_OUTRAS_DESPESAS,
		IMPORTACAO_FRETE,IMPORTACAO_SEGURO,IMPORTACAO_DESEMBARACO,DATA_DIGITACAO ,
		OBS,ORIGEM,CONFERENCIA,PESO,PESO_BRUTO,EMBALAGENS,NUMERO_ENTRADA,
		VALOR_SOMENTE_CONTABIL,RECARGO,VALOR_ADICIONAL,IPI_ADICIONAL ,TIPO_VOLUME,
		DATA_FATURAMENTO_RELATIVO,UTILIZA_DIAS_FIXOS_FORNECEDOR,SERIE_NF_ENTRADA,
		AGRUPAMENTO_ITENS,COMISSAO_VALOR ,COMISSAO_VALOR_GERENTE,COMPRIMENTO_DE_ROLOS,
		CTB_ITEM,CTB_LANCAMENTO,e.EMPRESA,FATURA_NOME_CLIFOR,FATURA_NUMERO,
		FATURA_SERIE ,ICMS_ISENTO,ICMS_OUTROS,INSS,NOME_CLIFOR_TRIANGULAR,NUMERO_CONFERENCIA,
		PORC_DESCONTO,PORC_DESCONTO_DIGITADO,PORC_ENCARGO ,RATEIO_CENTRO_CUSTO,
		RATEIO_FILIAL,DIFERENCA_VALOR,VALOR_IMPOSTO_AGREGAR,VALOR_SUB_ITENS,
		ITEM_DIGITADO,e.TIMESTAMP,DESCONTO_BRUTO ,FILIAL_SAIDA,SERIE_NF_SAIDA,
		NF_SAIDA,ESPECIE_SERIE,NOTA_CANCELADA,DATA_CANCELAMENTO,QTDE_CANCELADA,
		VALOR_CANCELADO,NOTA_COMPLEMENTAR ,FILIAL_COBRANCA,NUMERO_CONHECIMENTO_RELACIONADO,
		COD_CLIFOR_SACADO,ID_CQ,IMPORTACAO_TX_CAPATAZIA,SEQUENCIAL_UNICO,DATA_GERACAO_NSU ,
		CODIGO_CLIENTE_VAREJO,CHAVE_NFE,PROTOCOLO_AUTORIZACAO_NFE,DATA_AUTORIZACAO_NFE,
		PROTOCOLO_CANCELAMENTO_NFE,GERAR_AUTOMATICO ,STATUS_NFE,LOG_STATUS_NFE,
		MOTIVO_CANCELAMENTO_NFE,ITEM_NFE,PRIORIZACAO,TIPO_EMISSAO_NFE,FIN_EMISSAO_NFE,
		REGISTRO_DPEC ,DATA_REGISTRO_DPEC,OBS_INTERESSE_FISCO,CFOP_CANCELAMENTO,
		DATA_CONTINGENCIA,JUSTIFICATIVA_CONTINGENCIA,
		IND_STATUS_NFE ,IND_STATUS_CANCEL_NFE,IND_STATUS_INUTLZ_NFE,IND_STATUS_NFEPACK,
		UF_PLACA_VEICULO,INFORMACAO_COMPLEMENTAR,
		IND_NAT_FRT,VEICULO_PLACA ,MARCA_VOLUMES,NUMERACAO_VOLUMES,LX_STATUS_REGISTRO,
		e.DATA_PARA_TRANSFERENCIA,CALCULO_PIS_COFINS,CALCULO_ICMS_REDUZIDO,ENTRADA_XML ,
		DATA_HORA_EMISSAO,INDICA_PRESENCA_COMPRADOR,UTC_DATA_AUTORIZACAO_NFE,UTC_EMISSAO,
		INDICA_ENDERECO_ENTREGA,INDICA_ENTRADA_AUTOMATICA ,INFO_PGTO,CONSTRUCAO_CIVIL,
		e.CADASTRO_CNO,TIPO_REPASSE,DESC_REPASSE ,
		
		(SELECT top 1 R.ROMANEIO_PRODUTO FROM ESTOQUE_PROD_ENT R 
		WHERE R.NF_ENTRADA = E.NF_ENTRADA AND R.SERIE_NF_ENTRADA = E.SERIE_NF_ENTRADA) AS ROMANEIO ,

		iif( coalesce(E.FRETE,0) > 0 , 'F' , 'C') AS CIF_FOB ,
		iif( coalesce(E.FRETE,0) > 0 , E.FRETE , VALOR_FRETE_TRANSPORTADORA) AS VALOR_FRETE 
		
		FROM ENTRADAS E 
		INNER JOIN FILIAIS F ON F.FILIAL = E.FILIAL 
		WHERE 1=1
		--E.COD_TRANSACAO = 'ENTRADAS_102' 
		--AND cast(SUBSTRING(cast(E.DATA_PARA_TRANSFERENCIA AS VARCHAR),1,19) AS DATETIME) > '19000101'
		AND RTRIM(F.COD_FILIAL) = '000141'






--ALTER TABLE ENTRADAS 
--ADD IND_STATUS_NFE SMALLINT null
--go
--ALTER TABLE ENTRADAS 
--ADD IND_STATUS_CANCEL_NFE SMALLINT null
--go
--ALTER TABLE ENTRADAS ADD IND_STATUS_INUTLZ_NFE SMALLINT null
--go
--ALTER TABLE ENTRADAS ADD IND_STATUS_NFEPACK SMALLINT null
--go
