select *
from produtos_subgrupo 
where grupo_produto = 'INVERNO TOP' AND CODIGO_SUBGRUPO>'26'
ORDER BY CODIGO_SUBGRUPO

BEGIN TRAN

INSERT INTO produtos_subgrupo (GRUPO_PRODUTO,SUBGRUPO_PRODUTO,CODIGO_SUBGRUPO,CODIGO_SEQUENCIAL)
VALUES
('INVERNO TOP','TOP HELANCA','27','0000'),
('INVERNO TOP','TOP JEANS JAQUETA','28','0000'),
('INVERNO TOP','TOP MALHA M/L','29','0000'),
('INVERNO TOP','TOP MOLETOM','30','0000'),
('INVERNO TOP','TOP TECIDO JAQUETA','31','0000'),
('INVERNO TOP','TOP TECIDO M/L','32','0000'),
('INVERNO TOP','TOP TRICO','33','0000')

COMMIT







