SELECT 'N' AS SELECAO,
ROW_NUMBER() OVER(ORDER BY E.PRODUTO,E.COR_PRODUTO ASC)  AS LINHA,
RTRIM(LTRIM(E.PRODUTO)) +';'+ RTRIM(LTRIM(E.COR_PRODUTO)) AS TXT,
E.PRODUTO, E.COR_PRODUTO, '000000' as item, 
NULL AS PEDIDO_COR, NULL AS CAIXA, NULL AS PEDIDO, NULL AS PEDIDO_PRODUTO,NULL AS ENTREGA,0.00 AS DESCONTO_ITEM,
E.ESTOQUE as qtde, 
PP.PRECO1 AS PRECO, (E.ESTOQUE*PP.PRECO1) AS VALOR, 
E.ES1 AS F1, E.ES2 AS F2, E.ES3 AS F3, E.ES4 AS F4, E.ES5 AS F5, E.ES6 AS F6, E.ES7 AS F7, E.ES8 AS F8, E.ES9 AS F9, E.ES10 AS F10, 
E.ES11 AS F11, E.ES12 AS F12, E.ES13 AS F13, E.ES14 AS F14, E.ES15 AS F15, E.ES16 AS F16, E.ES17 AS F17, E.ES18 AS F18, E.ES19 AS F19, 
E.ES20 AS F20, E.ES21 AS F21, E.ES22 AS F22, E.ES23 AS F23, E.ES24 AS F24, E.ES25 AS F25, E.ES26 AS F26, E.ES27 AS F27, E.ES28 AS F28, 
E.ES29 AS F29, E.ES30 AS F30, E.ES31 AS F31, E.ES32 AS F32, E.ES33 AS F33, E.ES34 AS F34, E.ES35 AS F35, E.ES36 AS F36, E.ES37 AS F37, 
E.ES38 AS F38, E.ES39 AS F39, E.ES40 AS F40, E.ES41 AS F41, E.ES42 AS F42, E.ES43 AS F43, E.ES44 AS F44, E.ES45 AS F45, E.ES46 AS F46, 
E.ES47 AS F47, E.ES48 AS F48, '1' AS FAIXA,'O' AS ORIGEM, NULL AS ROMANEIO, CURRENT_TIMESTAMP AS TIMESTAMP,
0.00 AS CUSTO_NA_DATA, 0 AS MATA_SALDO, 'R$' AS MOEDA,     1.000000 AS CAMBIO_NA_DATA, NULL AS CODIGO_LOCAL_ENTREGA,
NULL AS ITEM_PEDIDO, NULL AS ORDEM_PRODUCAO, '5152' AS CODIGO_FISCAL_OPERACAO, FI.COD_FILIAL AS COD_FILIAL_ESTOQUE,
p.DESC_PROD_NF AS DESC_PRODUTO, p.CLASSIF_FISCAL, p.GRADE, CAST(0 AS bit) AS VARIA_CUSTO_TAM, CAST(0 AS bit) AS VARIA_PRECO_TAM,
p.PONTEIRO_PRECO_TAM, p.INDICADOR_CFOP, CAST(0 AS bit) AS VARIA_PRECO_COR, p.UNIDADE, p.CONTA_CONTABIL, p.TRIBUT_ICMS, 
p.TRIBUT_ORIGEM, PC.DESC_COR_PRODUTO, CX.DESCRICAO_INDICADOR_CFOP,
E.FILIAL AS FILIAL_ESTOQUE, 16 AS NUMERO_TAMANHOS, TB.DESCRICAO	AS TRIBUT_ORIGEM_DESCRICAO, TI.DESCRICAO AS TRIBUT_ICMS_DESCRICAO,
XP.DESC_CONTA, CF.DESC_CLASSIFICACAO,
0.00 AS COMISSAO_ITEM, 0.00 AS COMISSAO_ITEM_GERENTE, 
1 AS PESO1, 1 AS PESO2, 1 AS PESO3, 1 AS PESO4, 1 AS PESO5, 1 AS PESO6, 1 AS PESO7, 1 AS PESO8, 1 AS PESO9, 1 AS PESO10, 
1 AS PESO11, 1 AS PESO12, 1 AS PESO13, 1 AS PESO14, 1 AS PESO15, 1 AS PESO16, 1 AS PESO17, 1 AS PESO18, 1 AS PESO19, 
1 AS PESO20, 1 AS PESO21, 1 AS PESO22, 1 AS PESO23, 1 AS PESO24, 1 AS PESO25, 1 AS PESO26, 1 AS PESO27, 1 AS PESO28, 
1 AS PESO29, 1 AS PESO30, 1 AS PESO31, 1 AS PESO32, 1 AS PESO33, 1 AS PESO34, 1 AS PESO35, 1 AS PESO36, 1 AS PESO37, 
1 AS PESO38, 1 AS PESO39, 1 AS PESO40, 1 AS PESO41, 1 AS PESO42, 1 AS PESO43, 1 AS PESO44, 1 AS PESO45, 1 AS PESO46, 
1 AS PESO47, 1 AS PESO48, CAST(1 AS bit) AS GERAR_ITEM, 'P' AS COD_TABELA_FILHA, 0.00 AS PORC_DESCONTO_ITEM,
0.00 AS PESO_BRUTO, p.DESC_PROD_NF, NULL AS ID_VENDA_ENTREGA_FUTURA, 'P' AS ORIGEM_ITEM, p.ID_CEST_NCM,
TBCEST.DESCRICAO, TBCEST.CODIGO_CEST
FROM ESTOQUE_PRODUTOS E
inner join PRODUTOS p on p.PRODUTO = E.PRODUTO
inner join PRODUTOS_PRECOS PP ON PP.PRODUTO=E.PRODUTO AND PP.CODIGO_TAB_PRECO='02'
INNER JOIN FILIAIS FI ON FI.FILIAL = E.FILIAL
INNER JOIN PRODUTO_CORES PC ON PC.PRODUTO=E.PRODUTO AND PC.COR_PRODUTO=E.COR_PRODUTO
INNER JOIN CTB_LX_INDICADOR_CFOP CX ON CX.INDICADOR_CFOP = p.INDICADOR_CFOP
INNER JOIN TRIBUT_ORIGEM TB ON TB.TRIBUT_ORIGEM = p.TRIBUT_ORIGEM
INNER JOIN TRIBUT_ICMS TI ON TI.TRIBUT_ICMS = p.TRIBUT_ICMS
INNER JOIN W_CTB_CONTA_CONTABIL AS XP ON XP.CONTA_CONTABIL=p.CONTA_CONTABIL
INNER JOIN CLASSIF_FISCAL CF ON CF.CLASSIF_FISCAL = p.CLASSIF_FISCAL
LEFT JOIN (
select  
	TABELA_LX_CEST.CODIGO_CEST, 
	TABELA_LX_NCM.CODIGO_NCM, 
	Cast(TABELA_LX_CEST.DESCRICAO As VARCHAR(254)) As DESCRICAO, 
	CEST_NCM.ID, TABELA_LX_CEST.INATIVO 
from TABELA_LX_CEST   
JOIN CEST_NCM ON TABELA_LX_CEST.ID = CEST_NCM.ID_CEST 
JOIN TABELA_LX_NCM ON CEST_NCM.ID_NCM = TABELA_LX_NCM.ID 
/*where  CEST_NCM.ID =       p.ID_CEST_NCM
And CEST_NCM.INATIVO = 0  
And TABELA_LX_NCM.INATIVO = 0  
And TABELA_LX_CEST.INATIVO = 0  
and TABELA_LX_NCM.CODIGO_NCM = '62064000'*/) AS TBCEST ON TBCEST.ID = p.ID_CEST_NCM AND TBCEST.CODIGO_NCM=p.CLASSIF_FISCAL



/*verifica se PRODUTO+COR está nos recebimentos em SC da Komport*/
WHERE  RTRIM(LTRIM(E.PRODUTO))+RTRIM(LTRIM(E.COR_PRODUTO)) IN

	/*Seleciona todos os produtos com entrada em SC pela KOMPORT (importados) desde 01/01/2023*/
	(select RTRIM(LTRIM(B.PRODUTO))+RTRIM(LTRIM(B.COR_PRODUTO)) AS CHAVE_ENTRADA 
	from estoque_prod_ent A
	INNER JOIN CADASTRO_CLI_FOR C
		ON C.NOME_CLIFOR = A.FILIAL 
	INNER JOIN ESTOQUE_PROD1_ENT B 
		ON B.ROMANEIO_PRODUTO=A.ROMANEIO_PRODUTO AND B.FILIAL=A.FILIAL
	where 1=1 
			AND A.NOME_CLIFOR = 'KOMPORT' 
			AND C.CGC_CPF IN ('46377727006710','46377727001670')
			AND A.EMISSAO > '20230101'
	GROUP BY RTRIM(LTRIM(B.PRODUTO))+RTRIM(LTRIM(B.COR_PRODUTO)) 
	)

AND E.FILIAL = 'CD CAJAMAR' /*define o DEPOSITO de estoque CD CAJAMAR 

							  Para pegar outros depositos de saida só mudar aqui*/ 

/* seleciona estoque se o produto tiver quantidade > 0 em pelo menos 1 posição na grade */
and (es1 > 0 or es2 > 0 or es3 > 0 or es4 > 0 or es5 > 0 or es6 > 0 or es7 > 0 or es8 > 0 
		or es9 > 0 or es10 > 0 or es11 > 0 or es12 > 0 or es13 > 0 or es14 > 0 or es15 > 0 or es16 > 0) 