/*
EXEC CGP_LX_GERA_NOTA_TRANSF_SALDO_CREDOR 'SAO MATHEUS','CD CAJAMAR',104962.84,'08/2024'
*/

CREATE OR ALTER PROCEDURE [DBO].[CGP_LX_GERA_NOTA_TRANSF_SALDO_CREDOR]
	@FILIAL_ORIGEM VARCHAR(25),
	@FILIAL_DESTINO VARCHAR(25),
	@VALOR DECIMAL(15,2),
	@REFERENTE VARCHAR(10),
	@EMISSAO_DIA DATE,
	@SERIE VARCHAR(3) = '02'
AS
/*
AUTOR......: PAULO DEVIDE
CRIADO EM..: 16-10-2024
FINALIDADE.: GERAR UMA NOTA FISCAL DE SAIDA PARA TRANSFERENCIA DE SALDO CREDOR
				DA FILIAL ORIGEM PARA A FILIAL DESTINO. A FILIAL TEM QUE SER DA MESMA UF
				O CAMPO OBS_INTERESSE_FISCO DEVERÁ CONTER OS DADOS DA NOTA, ATRAVÉS DO 
				PARAMETRO @TEXTO_FISCO
ALTERAÇÃO..:

*/
BEGIN

	DECLARE @ERRMSG VARCHAR(500) = '', /*VARIAVEL DE TRATAMENTO DE ERRO DO TRY CATCH*/
			@CNPJ VARCHAR(19), 
			@CIDADE VARCHAR(35),
			@UF_FILIAL VARCHAR(2),
			@ANOMES CHAR(4)

	DECLARE @TEMP TABLE (CHAVE_NF char(44)) /*VARIAVEL PARA CRIAR A CHAVE DA NOTA FISCAL ATRAVÉS DE PROCEDURE DO LINX*/

	/*declaração de váriaveis para insert na tabela FATURAMENTO*/
	DECLARE @FILIAL varchar(25) = @FILIAL_ORIGEM
	DECLARE @NF_SAIDA varchar(15) = 'XYXZ' -->VALOR SERÁ MUDADO DEPOIS POR ROTINA DE SEQUENCIAMENTO POR FILIAL /SERIE 
	DECLARE @SERIE_NF varchar(6) = @SERIE --'02'
	DECLARE @CODIGO_LOCAL_ENTREGA char(5) = NULL
	DECLARE @FILIAL_FATURADA varchar(25) = NULL
	DECLARE @TIPO_FATURAMENTO varchar(25) = 'TRANSFERENCIA'
	DECLARE @LANCAMENTO char(8) = NULL
	DECLARE @NOME_CLIFOR varchar(25) = @FILIAL_DESTINO --> CD CAJAMAR PARA FILIAIS ORIGEM DE SP E MG - VENDA NOVA PARA FILIAIS DE MG
	DECLARE @CONDICAO_PGTO char(3) = '##'
	DECLARE @NATUREZA_SAIDA char(7) = '120.07'
	DECLARE @TRANSPORTADORA varchar(25) = 'NOSSO CARRO'
	DECLARE @TRANSP_REDESPACHO varchar(25) = 'NOSSO CARRO'
	DECLARE @TIPO_FRETE char(2) = '06'
	DECLARE @COD_TRANSACAO char(23) = 'FATURAMENTO_023' --> tela de Faturamento de Consumiveis  
	DECLARE @EMISSAO datetime = CAST(@EMISSAO_DIA AS date) --> data do dia sem hh:mm:ss
	DECLARE @DATA_SAIDA datetime = CAST(@EMISSAO_DIA AS date) --> data do dia sem hh:mm:ss
	DECLARE @FRETE numeric(14,2) = 0
	DECLARE @SEGURO numeric(14,2) = 0
	DECLARE @DESCONTO numeric(14,2) = 0
	DECLARE @DESCONTO_COND_PGTO numeric(14,2) = 0
	DECLARE @ENCARGO numeric(14,2) = 0
	DECLARE @ICMS numeric(14,2) = 0
	DECLARE @IPI_VALOR numeric(14,2) = 0
	DECLARE @VALOR_TOTAL numeric(14,2) = 0
	DECLARE @QTDE_TOTAL numeric(9,3) = 0
	DECLARE @NF_FATURA bit = 0
	DECLARE @FATURA char(15) = NULL
	DECLARE @NOTA_IMPRESSA bit = 0
	DECLARE @ACERTO_CONTAS_P_R bit = 0
	DECLARE @TABELA_FILHA char(18) = 'FATURAMENTO_ITEM'  
	--DECLARE @OBS text 
	DECLARE @OBS varchar(5000)=null
	DECLARE @PESO_LIQUIDO numeric(9,3) = 0
	DECLARE @PESO_BRUTO numeric(9,3) = 0
	DECLARE @VOLUMES int = 1
	DECLARE @TIPO_VOLUME varchar(35) = 'CAIXA'
	DECLARE @CONFERIDO bit = 0
	DECLARE @CONFERIDO_POR varchar(25) = NULL
	DECLARE @ENTREGA_CIF tinyint = 4
	DECLARE @IRRF numeric(14,2) = 0
	DECLARE @IRRF_RET_FONTE bit = 0
	DECLARE @NOTA_CANCELADA bit = 0
	DECLARE @DEVOLUCAO bit = 0
	DECLARE @REPRESENTANTE varchar(25) = @FILIAL_DESTINO
	DECLARE @COMISSAO numeric(8,5) = 0
	DECLARE @PORCENTAGEM_ACERTO numeric(8,5) = 0
	DECLARE @GERENTE varchar(25) = @FILIAL_DESTINO
	DECLARE @COMISSAO_GERENTE numeric(8,5) = 0
	DECLARE @DESCONTO_BRUTO numeric(14,2) = 0
	DECLARE @TIMESTAMP varchar(28) = NULL
	DECLARE @CONFERENCIA varchar(11) = NULL
	DECLARE @MARCA_EXPORTACAO char(1) = NULL
	DECLARE @ATUALIZACAO_EXPORTAR datetime = NULL
	DECLARE @DATA_EXPORTACAO datetime = NULL
	DECLARE @ICMS_BASE numeric(14,2) = 0
	DECLARE @STATUS_TRANSITO char(1) = 0
	DECLARE @DATA_CANCELAMENTO datetime  = NULL
	DECLARE @VALOR_CANCELADO numeric(14,2) = 0
	DECLARE @QTDE_CANCELADA int = 0
	DECLARE @MOEDA char(6) = 'R$'
	DECLARE @CAMBIO_NA_DATA numeric(11,6) = 1
	DECLARE @COBRAR_MOEDA_PADRAO bit = 1
	DECLARE @DATA_FATURAMENTO_RELATIVO datetime = NULL
	DECLARE @RECARGO numeric(14,2) = 0
	DECLARE @DATA_PARA_TRANSFERENCIA datetime = GETDATE()
	DECLARE @NOME_CLIFOR_ENTREGA varchar(25) = @FILIAL_DESTINO
	DECLARE @TABELA_PRECO_FRETE varchar(25) = NULL
	DECLARE @VALOR_FRETE numeric(16,2) = 0
	DECLARE @NOME_CLIFOR_COBRANCA varchar(25) = NULL
	DECLARE @VALOR_ADICIONAL numeric(14,2) = NULL
	DECLARE @IPI_ADICIONAL numeric(14,2) = NULL
	DECLARE @OBS_TRANSPORTE varchar(200) = NULL
	DECLARE @AGRUPAMENTO_ITENS smallint = 0
	DECLARE @COMISSAO_VALOR numeric(14,2) = 0
	DECLARE @COMISSAO_VALOR_GERENTE numeric(14,2) = 0 
	DECLARE @CTB_ITEM int = NULL
	DECLARE @CTB_LANCAMENTO int = NULL
	DECLARE @DESCONTO_BRUTO_1 numeric(8,2) = 0
	DECLARE @DESCONTO_BRUTO_2 numeric(8,2) = 0
	DECLARE @DESCONTO_BRUTO_3 numeric(8,2) = 0
	DECLARE @DESCONTO_BRUTO_4 numeric(8,2) = 0
	DECLARE @DESCONTO_SOBRE_1 numeric(8,2) = 0
	DECLARE @DESCONTO_SOBRE_2 numeric(8,2) = 0
	DECLARE @DESCONTO_SOBRE_3 numeric(8,2) = 0
	DECLARE @DESCONTO_SOBRE_4 numeric(8,2) = 0
	DECLARE @EMPRESA int = 1
	DECLARE @FATURA_FILIAL varchar(25) = NULL
	DECLARE @FATURA_NUMERO char(15) = NULL
	DECLARE @FATURA_SERIE varchar(6) = NULL
	DECLARE @ICMS_ISENTO numeric(16,2) = 0
	DECLARE @ICMS_OUTROS numeric(16,2) = 0
	DECLARE @MPADRAO_DESCONTO numeric(14,2) = 0
	DECLARE @MPADRAO_DESCONTO_COND_PGTO numeric(14,2) = 0
	DECLARE @MPADRAO_ENCARGO numeric(14,2) = 0
	DECLARE @MPADRAO_FRETE numeric(14,2) = 0
	DECLARE @MPADRAO_IMPOSTO_AGREGAR numeric(14,2) = 0
	DECLARE @MPADRAO_SEGURO numeric(14,2) = 0
	DECLARE @MPADRAO_VALOR_SUB_ITENS numeric(14,2) = 0
	DECLARE @MPADRAO_VALOR_TOTAL numeric(14,2) = 0
	DECLARE @MULTI_DESCONTO_ACUMULAR bit = 0
	DECLARE @NUMERO_CONFERENCIA int = 0
	DECLARE @PORC_DESCONTO numeric(13,10) = 0
	DECLARE @PORC_DESCONTO_BRUTO numeric(13,10) = 0
	DECLARE @PORC_DESCONTO_COND_PGTO numeric(13,10) = 0
	DECLARE @PORC_DESCONTO_DIGITADO bit = 1
	DECLARE @PORC_ENCARGO numeric(13,10) = 0
	DECLARE @RATEIO_CENTRO_CUSTO varchar(15) = '003'
	DECLARE @RATEIO_FILIAL varchar(15) = (select clifor from CADASTRO_CLI_FOR where NOME_CLIFOR = @FILIAL_ORIGEM)
	DECLARE @VALOR_DIFERENCA_GUIA_FATURA numeric(14,2) = 0
	DECLARE @VALOR_IMPOSTO_AGREGAR numeric(14,2) = 0
	DECLARE @VALOR_SUB_ITENS numeric(14,2) = 0
	DECLARE @IMPRIMIR_ENDERECO_COBRANCA int = 0
	DECLARE @INDICA_CONSUMIDOR_FINAL bit = 0
	DECLARE @BANCO char(5) = NULL
	DECLARE @AGENCIA varchar(20) = NULL
	DECLARE @RESPONSAVEL_TRANSPORTE varchar(40) = NULL
	DECLARE @NOTA_COMPLEMENTAR bit = 0
	DECLARE @NUMERO_CONHECIMENTO_RELACIONADO char(15) = NULL
	DECLARE @PORC_DESCONTO_SEFAZ numeric(8,5) = 0
	DECLARE @DESCONTO_SEFAZ numeric(14,2) = 0
	DECLARE @MPADRAO_DESCONTO_SEFAZ numeric(14,2) = 0
	DECLARE @ID_CAIXA_PGTO int = NULL
	DECLARE @NRO_DE varchar(15) = NULL
	DECLARE @DATA_DE datetime = NULL
	DECLARE @NATUREZA_EXPORTACAO char(1) = NULL
	DECLARE @NRO_RE varchar(15) = NULL
	DECLARE @DATA_RE datetime = NULL
	DECLARE @NRO_CONHECIMENTO_EMBARQUE varchar(20) = NULL
	DECLARE @DATA_CONHECIMENTO datetime = NULL
	DECLARE @TIPO_CONHECIMENTO char(2) = NULL
	DECLARE @COD_PAIS varchar(4) = NULL
	DECLARE @NRO_COMPROVANTE_EXPORTACAO varchar(15) = NULL
	DECLARE @DATA_COMPROVANTE_EXPORTACAO datetime = NULL
	DECLARE @DATA_AVERBACAO datetime = NULL
	DECLARE @NF_EMITIDA_EXPORTADOR varchar(15) = NULL
	DECLARE @COD_RELACIONAMENTO_RE_NF char(1) = NULL
	DECLARE @NF_E_NUMERO char(10) = NULL
	DECLARE @NF_E_DATA_EMISSAO datetime = NULL
	DECLARE @NF_E_COD_VERIFICACAO char(10) = NULL
	DECLARE @NF_E_DATA_QUITACAO_GUIA datetime = NULL
	DECLARE @NF_E_GERACAO datetime = NULL
	DECLARE @SEQUENCIAL_UNICO int = NULL
	DECLARE @DATA_GERACAO_NSU datetime = NULL
	DECLARE @CODIGO_CLIENTE_VAREJO varchar(14) = NULL
	DECLARE @PROTOCOLO_AUTORIZACAO_NFE varchar(15) = NULL
	DECLARE @COD_MOTIVO_CANC char(2) = NULL
	DECLARE @PIN varchar(9) = NULL
	DECLARE @CHAVE_NFE varchar(44) = NULL
	DECLARE @PROTOCOLO_CANCELAMENTO_NFE varchar(15) = NULL
	DECLARE @DATA_AUTORIZACAO_NFE datetime = NULL
	DECLARE @GERAR_AUTOMATICO bit = 0
	DECLARE @STATUS_NFE smallint = 1 --> aguardando envio
	DECLARE @LOG_STATUS_NFE smallint = 0
	DECLARE @MOTIVO_CANCELAMENTO_NFE varchar(255) = NULL
	DECLARE @PRIORIZACAO bit = 0
	DECLARE @TIPO_EMISSAO_NFE tinyint = 1
	DECLARE @FIN_EMISSAO_NFE tinyint = 1
	DECLARE @REGISTRO_DPEC varchar(15) = '0'
	DECLARE @DATA_REGISTRO_DPEC datetime = '19000101'
	--DECLARE @OBS_INTERESSE_FISCO text; --> PREENCHIMENTO ABAIXO COM VALOR E VALOR POR EXTENSO
	DECLARE @OBS_INTERESSE_FISCO varchar(5000) = null
	DECLARE @ITEM_NFE smallint = 1
	DECLARE @DATA_CONTINGENCIA datetime = NULL
	DECLARE @JUSTIFICATIVA_CONTINGENCIA varchar(256) = NULL
	DECLARE @UF_EMBARQUE_EXPORTACAO char(2) = NULL
	DECLARE @LOCAL_EMBARQUE_EXPORTACAO varchar(60) = NULL
	DECLARE @CFOP_CANCELAMENTO char(4) = NULL
	DECLARE @VALOR_DESPACHO numeric(14,2) = 0
	DECLARE @VALOR_IMPOSTO_INCIDENCIA numeric(14,2) = 0
	DECLARE @MPADRAO_VALOR_IMPOSTO_INCIDENCIA numeric(14,2) = 0
	DECLARE @VEICULO_PLACA varchar(8) = NULL
	DECLARE @UF_PLACA_VEICULO char(2) = NULL
	DECLARE @MARCA_VOLUMES varchar(60) = NULL
	DECLARE @NUMERACAO_VOLUMES varchar(60) = NULL
	DECLARE @INFORMACAO_COMPLEMENTAR varchar(5000) = 'TRANSFERENCIA DO SALDO CREDOR' 
	DECLARE @WK_DATA_PROCESSADO datetime = NULL
	DECLARE @FILIAL_NF_ENTRADA_GPO varchar(25) = NULL
	DECLARE @NF_ENTRADA_GPO char(15) = NULL
	DECLARE @SERIE_NF_ENTRADA_GPO char(3) = NULL
	DECLARE @NOME_CLIFOR_NF_ENTRADA_GPO varchar(25) = NULL
	DECLARE @DATA_HORA_EMISSAO smalldatetime = NULL
	DECLARE @INDICA_PRESENCA_COMPRADOR tinyint = 0
	DECLARE @LOCAL_DESPACHO_EXPORTACAO varchar(60) = NULL
	DECLARE @UTC_DATA_AUTORIZACAO_NFE tinyint = NULL
	DECLARE @UTC_DATA_SAIDA tinyint = 3
	DECLARE @UTC_EMISSAO tinyint = 3
	DECLARE @ERP_EBS_AR_DATA_ENVIO datetime = NULL
	DECLARE @ERP_EBS_GL_DATA_ENVIO datetime = NULL
	DECLARE @ERP_EBS_SYNCHRO_DATA_ENVIO datetime = NULL
	DECLARE @INDICA_ENDERECO_ENTREGA bit = 0
	DECLARE @CONSTRUCAO_CIVIL tinyint = 3
	DECLARE @INFO_PGTO char(2) = '90'
	DECLARE @TIPO_DOC_EXPORTACAO varchar(100) = NULL
	DECLARE @CADASTRO_CNO varchar(14) = NULL
	DECLARE @ID_INTERMEDIADOR int = NULL
	DECLARE @DESC_MEIO_PGTO varchar(60) = NULL
	DECLARE @ID_PROCESSO int = NULL
	DECLARE @NOME_LOCAL_RETIRADA varchar(25) = NULL
	DECLARE @UTILIZA_ENTREGA bit = NULL
	DECLARE @NF_DISTRIBUICAO_EMPREGADOS bit = NULL
	DECLARE @DATA_PAGAMENTO datetime = NULL
	DECLARE @AUTORIZACAO varchar(128) = NULL

	/*PEGA O VALOR DE UTC 3 HORARIO NORMAL E 4 HORARIO DE VERÃO */
	SELECT @UTC_EMISSAO = CAST(VALOR_ATUAL AS INT), @UTC_DATA_SAIDA = CAST(VALOR_ATUAL AS INT) FROM PARAMETROS 
	WHERE PARAMETRO = 'PALMA_UTC_NFE_CAEDU'

	/*VARIAVEIS DA TABELA FATURAMENTO_ITEM*/
	DECLARE @CLASSIF_FISCAL char(10) = '00000000' -->CLASSIFICAÇÃO FISCAL /NCM, A NOTA FISCAL NÃO POSSUI PRODUTOS, TEM SOMENTE ITEM FISCAL  
	DECLARE @CODIGO_FISCAL_OPERACAO char(4) = '5602' --> CFOP DENTRO DE SP PARA OPERAÇÕES DE SALDO CREDOR 
	DECLARE @CODIGO_ITEM varchar(50) = '3206'  --> CÓDIGO DO ITEM FISCAL PARA SALDO credor                                            
	DECLARE @COD_TABELA_FILHA char(1) = 'C'
	DECLARE @COMISSAO_ITEM numeric(13,10) = 0
	DECLARE @COMISSAO_ITEM_GERENTE numeric(13,10) = 0 
	DECLARE @CONTA_CONTABIL varchar(20) = '117.02.001'          
	DECLARE @DESCONTO_ITEM numeric(14,2) = 0
	DECLARE @DESCRICAO_ITEM varchar(80) = 'TRANSFERENCIA DE SALDO CREDOR DE ICMS'  
	DECLARE @FAIXA char(1) = '1'  
	--DECLARE @FILIAL varchar(25);  --> VARIAVEL JÁ DECLARADA, PEGA VALOR DA CAPA DA NOTA
	DECLARE @ID_EXCECAO_IMPOSTO int = 625 --> CÓDIGO DE EXCEÇÃO FISCAL UTILIZADO PARA ESTA OPERAÇÃO
	DECLARE @INDICADOR_CFOP tinyint = 97
	DECLARE @ITEM_IMPRESSAO char(4) = '0001'  
	DECLARE @MPADRAO_DESCONTO_ITEM numeric(15,5) = 0
	DECLARE @MPADRAO_PRECO_UNITARIO numeric(15,5) = 0  
	DECLARE @MPADRAO_VALOR_ITEM numeric(14,2) = 0  
	--DECLARE @NF_SAIDA char(15);  --> VARIAVEL JÁ DECLARADA, PEGA VALOR DA CAPA DA NOTA
	DECLARE @PESO numeric(7,3) = 0
	DECLARE @PORCENTAGEM_ITEM_RATEIO numeric(13,10) = 0  
	DECLARE @PRECO_UNITARIO numeric(15,5) = 0  
	DECLARE @QTDE_DEVOLVIDA numeric(9,3) = 0  
	DECLARE @QTDE_ITEM numeric(9,3) = 0  
	DECLARE @QTDE_RETORNAR_BENEFICIAMENTO numeric(9,3) = 0
	--DECLARE @SERIE_NF varchar(6);  --> VARIAVEL JÁ DECLARADA, PEGA VALOR DA CAPA DA NOTA
	DECLARE @SUB_ITEM_TAMANHO int = 0 
	DECLARE @TRIBUT_ICMS char(3) = '90' 
	DECLARE @TRIBUT_ORIGEM char(3) ='0'  
	DECLARE @UNIDADE varchar(5) = 'UN'
	DECLARE @VALOR_ITEM numeric(14,2) = 0 
	DECLARE @REFERENCIA varchar(50) = NULL 
	DECLARE @REFERENCIA_ITEM varchar(12) = NULL
	DECLARE @REFERENCIA_PEDIDO varchar(12) = NULL
	--DECLARE @TIMESTAMP varchar(25);   --> VARIAVEL JÁ DECLARADA, PEGA VALOR DA CAPA DA NOTA
	DECLARE @MPADRAO_VALOR_DESCONTOS numeric(14,2) = 0 
	DECLARE @MPADRAO_VALOR_ENCARGOS numeric(14,2) = 0  
	DECLARE @NAO_SOMA_VALOR bit = 0 
	DECLARE @OBS_ITEM varchar(254) = NULL  
	--DECLARE @ITEM_NFE smallint;   --> VARIAVEL JÁ DECLARADA, PEGA VALOR DA CAPA DA NOTA
	DECLARE @MPADRAO_SEGURO_ITEM numeric(14,2) = 0   
	DECLARE @MPADRAO_FRETE_ITEM numeric(14,2) = 0   
	DECLARE @MPADRAO_ENCARGO_ITEM numeric(14,2) = 0   
	--DECLARE @RATEIO_FILIAL varchar(15);   --> VARIAVEL JÁ DECLARADA, PEGA VALOR DA CAPA DA NOTA -- COLOCAR NULL
	--DECLARE @RATEIO_CENTRO_CUSTO varchar(15);   --> VARIAVEL JÁ DECLARADA, PEGA VALOR DA CAPA DA NOTA -- COLOCAR NULL
	DECLARE @ORIGEM_ITEM char(1) = 'I'  
	DECLARE @VALOR_IMPOSTO_ITEM numeric(14,2) = 0 
	DECLARE @INDICA_PRODUTO_PROCESSO bit = 0 
	DECLARE @CODIGO_FCI char(36) = NULL 
	DECLARE @PRECO_UNITARIO_ORIGINAL numeric(15,5) = 0 
	--DECLARE @WK_DATA_PROCESSADO datetime;   --> VARIAVEL JÁ DECLARADA, PEGA VALOR DA CAPA DA NOTA -- COLOCAR NULL
	DECLARE @CTB_TIPO_OPERACAO int = NULL  
	DECLARE @ID_SUB_PROJETO int = NULL  
	DECLARE @VALOR_IMPOSTO_ITEM_MUNICIPAL numeric(9,2) = 0
	DECLARE @VALOR_IMPOSTO_ITEM_ESTADUAL numeric(9,2) = 0 
	DECLARE @ID_CEST_NCM int = NULL  
	DECLARE @NUMERO_IMOBILIZADO varchar(20) = NULL 
	DECLARE @NOME_CONTAGEM varchar(25) = NULL 
	DECLARE @OBS_CONTRIB_NOME varchar(20) = NULL  
	DECLARE @OBS_CONTRIB_CONTEUDO varchar(60)  = NULL 
	DECLARE @OBS_FISCO_NOME varchar(20)  = NULL  
	DECLARE @OBS_FISCO_CONTEUDO varchar(60)  = NULL 




	BEGIN TRY

		DELETE FROM @TEMP --> APAGA OS DADOS PARA RECEBER UMA NOVA CHAVE GENERICA DE NOTA FISCAL

		/*INICIO DO CONTROLE DE FLUXO DE TRANSAÇÃO*/
		BEGIN TRANSACTION

		/*INSERE DADOS NA CAPA DA NOTA FISCAL*/
		INSERT INTO [dbo].[FATURAMENTO]
			(FILIAL,
			NF_SAIDA,
			SERIE_NF,
			CODIGO_LOCAL_ENTREGA,
			FILIAL_FATURADA,
			TIPO_FATURAMENTO,
			LANCAMENTO,
			NOME_CLIFOR,
			CONDICAO_PGTO,
			NATUREZA_SAIDA,
			TRANSPORTADORA,
			TRANSP_REDESPACHO,
			TIPO_FRETE,
			COD_TRANSACAO,
			EMISSAO,
			DATA_SAIDA,
			FRETE,
			SEGURO,
			DESCONTO,
			DESCONTO_COND_PGTO,
			ENCARGO,
			ICMS,
			IPI_VALOR,
			VALOR_TOTAL,
			QTDE_TOTAL,
			NF_FATURA,
			FATURA,
			NOTA_IMPRESSA,
			ACERTO_CONTAS_P_R,
			TABELA_FILHA,
			OBS,
			PESO_LIQUIDO,
			PESO_BRUTO,
			VOLUMES,
			TIPO_VOLUME,
			CONFERIDO,
			CONFERIDO_POR,
			ENTREGA_CIF,
			IRRF,
			IRRF_RET_FONTE,
			NOTA_CANCELADA,
			DEVOLUCAO,
			REPRESENTANTE,
			COMISSAO,
			PORCENTAGEM_ACERTO,
			GERENTE,
			COMISSAO_GERENTE,
			DESCONTO_BRUTO,
			TIMESTAMP,
			CONFERENCIA,
			MARCA_EXPORTACAO,
			ATUALIZACAO_EXPORTAR,
			DATA_EXPORTACAO,
			ICMS_BASE,
			STATUS_TRANSITO,
			DATA_CANCELAMENTO,
			VALOR_CANCELADO,
			QTDE_CANCELADA,
			MOEDA,
			CAMBIO_NA_DATA,
			COBRAR_MOEDA_PADRAO,
			DATA_FATURAMENTO_RELATIVO,
			RECARGO,
			DATA_PARA_TRANSFERENCIA,
			NOME_CLIFOR_ENTREGA,
			TABELA_PRECO_FRETE,
			VALOR_FRETE,
			NOME_CLIFOR_COBRANCA,
			VALOR_ADICIONAL,
			IPI_ADICIONAL,
			OBS_TRANSPORTE,
			AGRUPAMENTO_ITENS,
			COMISSAO_VALOR,
			COMISSAO_VALOR_GERENTE,
			CTB_ITEM,
			CTB_LANCAMENTO,
			DESCONTO_BRUTO_1,
			DESCONTO_BRUTO_2,
			DESCONTO_BRUTO_3,
			DESCONTO_BRUTO_4,
			DESCONTO_SOBRE_1,
			DESCONTO_SOBRE_2,
			DESCONTO_SOBRE_3,
			DESCONTO_SOBRE_4,
			EMPRESA,
			FATURA_FILIAL,
			FATURA_NUMERO,
			FATURA_SERIE,
			ICMS_ISENTO,
			ICMS_OUTROS,
			MPADRAO_DESCONTO,
			MPADRAO_DESCONTO_COND_PGTO,
			MPADRAO_ENCARGO,
			MPADRAO_FRETE,
			MPADRAO_IMPOSTO_AGREGAR,
			MPADRAO_SEGURO,
			MPADRAO_VALOR_SUB_ITENS,
			MPADRAO_VALOR_TOTAL,
			MULTI_DESCONTO_ACUMULAR,
			NUMERO_CONFERENCIA,
			PORC_DESCONTO,
			PORC_DESCONTO_BRUTO,
			PORC_DESCONTO_COND_PGTO,
			PORC_DESCONTO_DIGITADO,
			PORC_ENCARGO,
			RATEIO_CENTRO_CUSTO,
			RATEIO_FILIAL,
			VALOR_DIFERENCA_GUIA_FATURA,
			VALOR_IMPOSTO_AGREGAR,
			VALOR_SUB_ITENS,
			IMPRIMIR_ENDERECO_COBRANCA,
			INDICA_CONSUMIDOR_FINAL,
			BANCO,
			AGENCIA,
			RESPONSAVEL_TRANSPORTE,
			NOTA_COMPLEMENTAR,
			NUMERO_CONHECIMENTO_RELACIONADO,
			PORC_DESCONTO_SEFAZ,
			DESCONTO_SEFAZ,
			MPADRAO_DESCONTO_SEFAZ,
			ID_CAIXA_PGTO,
			NRO_DE,
			DATA_DE,
			NATUREZA_EXPORTACAO,
			NRO_RE,
			DATA_RE,
			NRO_CONHECIMENTO_EMBARQUE,
			DATA_CONHECIMENTO,
			TIPO_CONHECIMENTO,
			COD_PAIS,
			NRO_COMPROVANTE_EXPORTACAO,
			DATA_COMPROVANTE_EXPORTACAO,
			DATA_AVERBACAO,
			NF_EMITIDA_EXPORTADOR,
			COD_RELACIONAMENTO_RE_NF,
			NF_E_NUMERO,
			NF_E_DATA_EMISSAO,
			NF_E_COD_VERIFICACAO,
			NF_E_DATA_QUITACAO_GUIA,
			NF_E_GERACAO,
			SEQUENCIAL_UNICO,
			DATA_GERACAO_NSU,
			CODIGO_CLIENTE_VAREJO,
			PROTOCOLO_AUTORIZACAO_NFE,
			COD_MOTIVO_CANC,
			PIN,
			CHAVE_NFE,
			PROTOCOLO_CANCELAMENTO_NFE,
			DATA_AUTORIZACAO_NFE,
			GERAR_AUTOMATICO,
			STATUS_NFE,
			LOG_STATUS_NFE,
			MOTIVO_CANCELAMENTO_NFE,
			PRIORIZACAO,
			TIPO_EMISSAO_NFE,
			FIN_EMISSAO_NFE,
			REGISTRO_DPEC,
			DATA_REGISTRO_DPEC,
			OBS_INTERESSE_FISCO,
			ITEM_NFE,
			DATA_CONTINGENCIA,
			JUSTIFICATIVA_CONTINGENCIA,
			UF_EMBARQUE_EXPORTACAO,
			LOCAL_EMBARQUE_EXPORTACAO,
			CFOP_CANCELAMENTO,
			VALOR_DESPACHO,
			VALOR_IMPOSTO_INCIDENCIA,
			MPADRAO_VALOR_IMPOSTO_INCIDENCIA,
			VEICULO_PLACA,
			UF_PLACA_VEICULO,
			MARCA_VOLUMES,
			NUMERACAO_VOLUMES,
			INFORMACAO_COMPLEMENTAR,
			WK_DATA_PROCESSADO,
			FILIAL_NF_ENTRADA_GPO,
			NF_ENTRADA_GPO,
			SERIE_NF_ENTRADA_GPO,
			NOME_CLIFOR_NF_ENTRADA_GPO,
			DATA_HORA_EMISSAO,
			INDICA_PRESENCA_COMPRADOR,
			LOCAL_DESPACHO_EXPORTACAO,
			UTC_DATA_AUTORIZACAO_NFE,
			UTC_DATA_SAIDA,
			UTC_EMISSAO,
			ERP_EBS_AR_DATA_ENVIO,
			ERP_EBS_GL_DATA_ENVIO,
			ERP_EBS_SYNCHRO_DATA_ENVIO,
			INDICA_ENDERECO_ENTREGA,
			CONSTRUCAO_CIVIL,
			INFO_PGTO,
			TIPO_DOC_EXPORTACAO,
			CADASTRO_CNO,
			ID_INTERMEDIADOR,
			DESC_MEIO_PGTO,
			ID_PROCESSO,
			NOME_LOCAL_RETIRADA,
			UTILIZA_ENTREGA,
			NF_DISTRIBUICAO_EMPREGADOS,
			DATA_PAGAMENTO,
			AUTORIZACAO)
		SELECT 
			@FILIAL AS FILIAL,
			@NF_SAIDA,
			@SERIE_NF,
			@CODIGO_LOCAL_ENTREGA,
			@FILIAL_FATURADA,
			@TIPO_FATURAMENTO,
			@LANCAMENTO,
			@NOME_CLIFOR,
			@CONDICAO_PGTO,
			@NATUREZA_SAIDA,
			@TRANSPORTADORA,
			@TRANSP_REDESPACHO,
			@TIPO_FRETE,
			@COD_TRANSACAO,
			@EMISSAO,
			@DATA_SAIDA,
			@FRETE,
			@SEGURO,
			@DESCONTO,
			@DESCONTO_COND_PGTO,
			@ENCARGO,
			@ICMS,
			@IPI_VALOR,
			@VALOR_TOTAL,
			@QTDE_TOTAL,
			@NF_FATURA,
			@FATURA,
			@NOTA_IMPRESSA,
			@ACERTO_CONTAS_P_R,
			@TABELA_FILHA,
			@OBS,
			@PESO_LIQUIDO,
			@PESO_BRUTO,
			@VOLUMES,
			@TIPO_VOLUME,
			@CONFERIDO,
			@CONFERIDO_POR,
			@ENTREGA_CIF,
			@IRRF,
			@IRRF_RET_FONTE,
			@NOTA_CANCELADA,
			@DEVOLUCAO,
			@REPRESENTANTE,
			@COMISSAO,
			@PORCENTAGEM_ACERTO,
			@GERENTE,
			@COMISSAO_GERENTE,
			@DESCONTO_BRUTO,
			@TIMESTAMP,
			@CONFERENCIA,
			@MARCA_EXPORTACAO,
			@ATUALIZACAO_EXPORTAR,
			@DATA_EXPORTACAO,
			@ICMS_BASE,
			@STATUS_TRANSITO,
			@DATA_CANCELAMENTO,
			@VALOR_CANCELADO,
			@QTDE_CANCELADA,
			@MOEDA,
			@CAMBIO_NA_DATA,
			@COBRAR_MOEDA_PADRAO,
			@DATA_FATURAMENTO_RELATIVO,
			@RECARGO,
			@DATA_PARA_TRANSFERENCIA,
			@NOME_CLIFOR_ENTREGA,
			@TABELA_PRECO_FRETE,
			@VALOR_FRETE,
			@NOME_CLIFOR_COBRANCA,
			@VALOR_ADICIONAL,
			@IPI_ADICIONAL,
			@OBS_TRANSPORTE,
			@AGRUPAMENTO_ITENS,
			@COMISSAO_VALOR,
			@COMISSAO_VALOR_GERENTE,
			@CTB_ITEM,
			@CTB_LANCAMENTO,
			@DESCONTO_BRUTO_1,
			@DESCONTO_BRUTO_2,
			@DESCONTO_BRUTO_3,
			@DESCONTO_BRUTO_4,
			@DESCONTO_SOBRE_1,
			@DESCONTO_SOBRE_2,
			@DESCONTO_SOBRE_3,
			@DESCONTO_SOBRE_4,
			@EMPRESA,
			@FATURA_FILIAL,
			@FATURA_NUMERO,
			@FATURA_SERIE,
			@ICMS_ISENTO,
			@ICMS_OUTROS,
			@MPADRAO_DESCONTO,
			@MPADRAO_DESCONTO_COND_PGTO,
			@MPADRAO_ENCARGO,
			@MPADRAO_FRETE,
			@MPADRAO_IMPOSTO_AGREGAR,
			@MPADRAO_SEGURO,
			@MPADRAO_VALOR_SUB_ITENS,
			@MPADRAO_VALOR_TOTAL,
			@MULTI_DESCONTO_ACUMULAR,
			@NUMERO_CONFERENCIA,
			@PORC_DESCONTO,
			@PORC_DESCONTO_BRUTO,
			@PORC_DESCONTO_COND_PGTO,
			@PORC_DESCONTO_DIGITADO,
			@PORC_ENCARGO,
			@RATEIO_CENTRO_CUSTO,
			@RATEIO_FILIAL,
			@VALOR_DIFERENCA_GUIA_FATURA,
			@VALOR_IMPOSTO_AGREGAR,
			@VALOR_SUB_ITENS,
			@IMPRIMIR_ENDERECO_COBRANCA,
			@INDICA_CONSUMIDOR_FINAL,
			@BANCO,
			@AGENCIA,
			@RESPONSAVEL_TRANSPORTE,
			@NOTA_COMPLEMENTAR,
			@NUMERO_CONHECIMENTO_RELACIONADO,
			@PORC_DESCONTO_SEFAZ,
			@DESCONTO_SEFAZ,
			@MPADRAO_DESCONTO_SEFAZ,
			@ID_CAIXA_PGTO,
			@NRO_DE,
			@DATA_DE,
			@NATUREZA_EXPORTACAO,
			@NRO_RE,
			@DATA_RE,
			@NRO_CONHECIMENTO_EMBARQUE,
			@DATA_CONHECIMENTO,
			@TIPO_CONHECIMENTO,
			@COD_PAIS,
			@NRO_COMPROVANTE_EXPORTACAO,
			@DATA_COMPROVANTE_EXPORTACAO,
			@DATA_AVERBACAO,
			@NF_EMITIDA_EXPORTADOR,
			@COD_RELACIONAMENTO_RE_NF,
			@NF_E_NUMERO,
			@NF_E_DATA_EMISSAO,
			@NF_E_COD_VERIFICACAO,
			@NF_E_DATA_QUITACAO_GUIA,
			@NF_E_GERACAO,
			@SEQUENCIAL_UNICO,
			@DATA_GERACAO_NSU,
			@CODIGO_CLIENTE_VAREJO,
			@PROTOCOLO_AUTORIZACAO_NFE,
			@COD_MOTIVO_CANC,
			@PIN,
			@CHAVE_NFE,
			@PROTOCOLO_CANCELAMENTO_NFE,
			@DATA_AUTORIZACAO_NFE,
			@GERAR_AUTOMATICO,
			@STATUS_NFE,
			@LOG_STATUS_NFE,
			@MOTIVO_CANCELAMENTO_NFE,
			@PRIORIZACAO,
			@TIPO_EMISSAO_NFE,
			@FIN_EMISSAO_NFE,
			@REGISTRO_DPEC,
			@DATA_REGISTRO_DPEC,
			@OBS_INTERESSE_FISCO,
			@ITEM_NFE,
			@DATA_CONTINGENCIA,
			@JUSTIFICATIVA_CONTINGENCIA,
			@UF_EMBARQUE_EXPORTACAO,
			@LOCAL_EMBARQUE_EXPORTACAO,
			@CFOP_CANCELAMENTO,
			@VALOR_DESPACHO,
			@VALOR_IMPOSTO_INCIDENCIA,
			@MPADRAO_VALOR_IMPOSTO_INCIDENCIA,
			@VEICULO_PLACA,
			@UF_PLACA_VEICULO,
			@MARCA_VOLUMES,
			@NUMERACAO_VOLUMES,
			@INFORMACAO_COMPLEMENTAR,
			@WK_DATA_PROCESSADO,
			@FILIAL_NF_ENTRADA_GPO,
			@NF_ENTRADA_GPO,
			@SERIE_NF_ENTRADA_GPO,
			@NOME_CLIFOR_NF_ENTRADA_GPO,
			@DATA_HORA_EMISSAO,
			@INDICA_PRESENCA_COMPRADOR,
			@LOCAL_DESPACHO_EXPORTACAO,
			@UTC_DATA_AUTORIZACAO_NFE,
			@UTC_DATA_SAIDA,
			@UTC_EMISSAO,
			@ERP_EBS_AR_DATA_ENVIO,
			@ERP_EBS_GL_DATA_ENVIO,
			@ERP_EBS_SYNCHRO_DATA_ENVIO,
			@INDICA_ENDERECO_ENTREGA,
			@CONSTRUCAO_CIVIL,
			@INFO_PGTO,
			@TIPO_DOC_EXPORTACAO,
			@CADASTRO_CNO,
			@ID_INTERMEDIADOR,
			@DESC_MEIO_PGTO,
			@ID_PROCESSO,
			@NOME_LOCAL_RETIRADA,
			@UTILIZA_ENTREGA,
			@NF_DISTRIBUICAO_EMPREGADOS,
			@DATA_PAGAMENTO,
			@AUTORIZACAO

			INSERT INTO dbo.FATURAMENTO_ITEM
			(CLASSIF_FISCAL,
			CODIGO_FISCAL_OPERACAO,
			CODIGO_ITEM,
			COD_TABELA_FILHA,
			COMISSAO_ITEM,
			COMISSAO_ITEM_GERENTE,
			CONTA_CONTABIL,
			DESCONTO_ITEM,
			DESCRICAO_ITEM,
			FAIXA,
			FILIAL,
			ID_EXCECAO_IMPOSTO,
			INDICADOR_CFOP,
			ITEM_IMPRESSAO,
			MPADRAO_DESCONTO_ITEM,
			MPADRAO_PRECO_UNITARIO,
			MPADRAO_VALOR_ITEM,
			NF_SAIDA,
			PESO,
			PORCENTAGEM_ITEM_RATEIO,
			PRECO_UNITARIO,
			QTDE_DEVOLVIDA,
			QTDE_ITEM,
			QTDE_RETORNAR_BENEFICIAMENTO,
			SERIE_NF,
			SUB_ITEM_TAMANHO,
			TRIBUT_ICMS,
			TRIBUT_ORIGEM,
			UNIDADE,
			VALOR_ITEM,
			REFERENCIA,
			REFERENCIA_ITEM,
			REFERENCIA_PEDIDO,
			TIMESTAMP,
			MPADRAO_VALOR_DESCONTOS,
			MPADRAO_VALOR_ENCARGOS,
			NAO_SOMA_VALOR,
			OBS_ITEM,
			ITEM_NFE,
			MPADRAO_SEGURO_ITEM,
			MPADRAO_FRETE_ITEM,
			MPADRAO_ENCARGO_ITEM,
			RATEIO_FILIAL,
			RATEIO_CENTRO_CUSTO,
			ORIGEM_ITEM,
			VALOR_IMPOSTO_ITEM,
			INDICA_PRODUTO_PROCESSO,
			CODIGO_FCI,
			PRECO_UNITARIO_ORIGINAL,
			WK_DATA_PROCESSADO,
			CTB_TIPO_OPERACAO,
			ID_SUB_PROJETO,
			VALOR_IMPOSTO_ITEM_MUNICIPAL,
			VALOR_IMPOSTO_ITEM_ESTADUAL,
			ID_CEST_NCM,
			NUMERO_IMOBILIZADO,
			NOME_CONTAGEM,
			OBS_CONTRIB_NOME,
			OBS_CONTRIB_CONTEUDO,
			OBS_FISCO_NOME,
			OBS_FISCO_CONTEUDO)
			SELECT 
				@CLASSIF_FISCAL,
				@CODIGO_FISCAL_OPERACAO,
				@CODIGO_ITEM,
				@COD_TABELA_FILHA,
				@COMISSAO_ITEM,
				@COMISSAO_ITEM_GERENTE,
				@CONTA_CONTABIL,
				@DESCONTO_ITEM,
				@DESCRICAO_ITEM,
				@FAIXA,
				@FILIAL,
				@ID_EXCECAO_IMPOSTO,
				@INDICADOR_CFOP,
				@ITEM_IMPRESSAO,
				@MPADRAO_DESCONTO_ITEM,
				@MPADRAO_PRECO_UNITARIO,
				@MPADRAO_VALOR_ITEM,
				@NF_SAIDA,
				@PESO,
				@PORCENTAGEM_ITEM_RATEIO,
				@PRECO_UNITARIO,
				@QTDE_DEVOLVIDA,
				@QTDE_ITEM,
				@QTDE_RETORNAR_BENEFICIAMENTO,
				@SERIE_NF,
				@SUB_ITEM_TAMANHO,
				@TRIBUT_ICMS,
				@TRIBUT_ORIGEM,
				@UNIDADE,
				@VALOR_ITEM,
				@REFERENCIA,
				@REFERENCIA_ITEM,
				@REFERENCIA_PEDIDO,
				@TIMESTAMP,
				@MPADRAO_VALOR_DESCONTOS,
				@MPADRAO_VALOR_ENCARGOS,
				@NAO_SOMA_VALOR,
				@OBS_ITEM,
				@ITEM_NFE,
				@MPADRAO_SEGURO_ITEM,
				@MPADRAO_FRETE_ITEM,
				@MPADRAO_ENCARGO_ITEM,
				@RATEIO_FILIAL,
				@RATEIO_CENTRO_CUSTO,
				@ORIGEM_ITEM,
				@VALOR_IMPOSTO_ITEM,
				@INDICA_PRODUTO_PROCESSO,
				@CODIGO_FCI,
				@PRECO_UNITARIO_ORIGINAL,
				@WK_DATA_PROCESSADO,
				@CTB_TIPO_OPERACAO,
				@ID_SUB_PROJETO,
				@VALOR_IMPOSTO_ITEM_MUNICIPAL,
				@VALOR_IMPOSTO_ITEM_ESTADUAL,
				@ID_CEST_NCM,
				@NUMERO_IMOBILIZADO,
				@NOME_CONTAGEM,
				@OBS_CONTRIB_NOME,
				@OBS_CONTRIB_CONTEUDO,
				@OBS_FISCO_NOME,
				@OBS_FISCO_CONTEUDO



			/* EXEMPLO DE TEXTO PARA A NOTA FISCAL
			Transferência de saldo Credor  - IE Nº 442223660111 - Valor R$ 220319,03 Duzentos e vinte mil, trezentos e 
			dezenove reais e três centavos  Apuração Ref:08/2024
			*/
			
			/* Monta o Texto para atualizar a capa da nota fiscal */
			SELECT @OBS_INTERESSE_FISCO = 'Transferencia de saldo credor - IE No. '+
						(select RTRIM(LTRIM(ISNULL(RG_IE,''))) from CADASTRO_CLI_FOR where NOME_CLIFOR=@FILIAL_ORIGEM) + ' Valor R$ ' +
						convert(varchar,@VALOR) + ' '+
						dbo.ValorPorExtenso(@VALOR)+ ' Apuracao Ref: '+	@REFERENTE

			/* ATUALIZA E CARREGA O VALOR NA VÁRIAVEL @NF_SAIDA */
			UPDATE faturamento_sequenciais 
				SET @NF_SAIDA = SEQUENCIAL = REPLICATE('0', 9 - LEN(LTRIM(RTRIM(SEQUENCIAL+1)))) + LTRIM(SEQUENCIAL+1) 
			WHERE SERIE_NF = @SERIE_NF and filial = @filial

			UPDATE FATURAMENTO 
				SET NF_SAIDA = @NF_SAIDA 
			WHERE NF_SAIDA = 'XYXZ'              

			SELECT @ANOMES = RIGHT(CAST(DATEPART(YY,@EMISSAO_DIA) AS CHAR(4)),2) +                 
						CASE WHEN LEN(CAST(DATEPART(MM,@EMISSAO_DIA) AS CHAR(2))) = 2                 
						THEN CAST(DATEPART(MM,@EMISSAO_DIA) AS CHAR(2))                
						ELSE '0' + CAST(DATEPART(MM,@EMISSAO_DIA) AS CHAR(2)) END  

			SELECT @CNPJ = CAD.CGC_CPF,
					@CIDADE = CAD.CIDADE,
					@UF_FILIAL = CAD.UF
			FROM CADASTRO_CLI_FOR CAD WHERE NOME_CLIFOR = @FILIAL_ORIGEM

			INSERT INTO @TEMP EXEC DBO.LX_GERA_CHAVE_NFE_GENERICA @NF_SAIDA,@SERIE_NF,@CNPJ,@CIDADE,@UF_FILIAL,@ANOMES,'55',1,'4.00'  

			SELECT @CHAVE_NFE = CHAVE_NF FROM @TEMP
			
			UPDATE FATURAMENTO SET CHAVE_NFE = @CHAVE_NFE, 
									DATA_HORA_EMISSAO = GETDATE(), 
									FIN_EMISSAO_NFE = 1,  
									OBS_INTERESSE_FISCO = @OBS_INTERESSE_FISCO   /*TEXTO DA NOTA COM VALOR POR EXTENSO */           
			WHERE NF_SAIDA = @NF_SAIDA AND SERIE_NF = @SERIE_NF  and filial = @filial  

  
			EXEC dbo.LX_GERA_IMPOSTOS_SAIDA @FILIAL, @NF_SAIDA, @SERIE_NF, 1, 0, 1    

			COMMIT TRANSACTION  

	END TRY

	BEGIN CATCH
			SELECT @ERRMSG = 'Erro ao inserir a capa da nota fiscal.' 
			SELECT @ERRMSG = @ERRMSG + CHAR(13)+CHAR(10) + 'Error: ' + CONVERT(VARCHAR(20),isnull(ERROR_NUMBER(),0)) + ' Message: ' +            
			ISNULL(RTRIM(ERROR_MESSAGE()), '') + ' Proc: ' + ISNULL(RTRIM(ERROR_PROCEDURE()), '') 

			ROLLBACK TRANSACTION  
			RAISERROR(@ERRMSG, 16, 1)

	END  CATCH

   
                           


END

