create or alter procedure DBO.CGP_PRC_LOG_ARQUIVO_AF_INVENTARIO
	@FILIAL VARCHAR(25),
	@QTD_PRODUTOS INT,
	@ESTOQUE INT,
	@TOTAL_LINHAS INT,
	@USUARIO VARCHAR(25)
AS
BEGIN
	DECLARE @EM_INVENTARIO BIT

	SELECT @EM_INVENTARIO=EM_INVENTARIO 
	FROM FILIAIS WHERE FILIAL = @FILIAL

	INSERT INTO DBO.CGP_LOG_ARQUIVO_AF_INVENTARIO
	(DATA_HORA_CONSULTA,FILIAL,QTD_PRODUTOS,ESTOQUE,TOTAL_LINHAS,USUARIO,EM_INVENTARIO)
	VALUES (
	GETDATE(),
	@FILIAL,
	@QTD_PRODUTOS,
	@ESTOQUE,
	@TOTAL_LINHAS,
	@USUARIO,
	@EM_INVENTARIO
	)
END