create or alter procedure DBO.CGP_PRC_LOG_CONSULTA_ESTOQUE_FILIAL
	@FILIAL VARCHAR(25),
	@TOTAL_QTDE_ESTOQUE INT,
	@TOTAL_QTDE_ESTOQUE_DISPONIVEL INT,
	@TOTAL_QTDE_TRANSITO INT,
	@USUARIO VARCHAR(25) 
AS
BEGIN
	DECLARE @EM_INVENTARIO BIT

	SELECT @EM_INVENTARIO=EM_INVENTARIO 
	FROM FILIAIS WHERE FILIAL = @FILIAL

	INSERT INTO DBO.CGP_LOG_CONSULTA_ESTOQUE_FILIAL
	(DATA_HORA_CONSULTA,
	FILIAL,
	TOTAL_QTDE_ESTOQUE,
	TOTAL_QTDE_ESTOQUE_DISPONIVEL,
	TOTAL_QTDE_TRANSITO,
	USUARIO,
	EM_INVENTARIO
	)
	VALUES (
	GETDATE(),
	@FILIAL,
	@TOTAL_QTDE_ESTOQUE,
	@TOTAL_QTDE_ESTOQUE_DISPONIVEL,
	@TOTAL_QTDE_TRANSITO,
	@USUARIO,
	@EM_INVENTARIO
	)
END