CREATE PROCEDURE DBO.PRC_EXCLUI_CAIXA_AVULSA
@CAIXA VARCHAR(8)
AS
BEGIN
	DECLARE @ERROFAT BIT = 0
	DECLARE @MSG VARCHAR(1000)
	DECLARE @TIPO_DISTRIBUICAO INT = 0
	IF EXISTS(SELECT 1 from VENDAS_PROD_EMBALADO (NOLOCK) where CAIXA = @CAIXA) 
	BEGIN
		SET @TIPO_DISTRIBUICAO = 3
	END
	IF EXISTS(SELECT 1 from CAEDU_RESERVA_AUTOMATICA_PACK_WMS (NOLOCK) where CAIXA = @CAIXA) 
	BEGIN
		SET @TIPO_DISTRIBUICAO = 2
	END
	IF EXISTS(SELECT 1 from CAEDU_RESERVA_AUTOMATICA (NOLOCK) where CAIXA = @CAIXA) 
	BEGIN
		SET @TIPO_DISTRIBUICAO = 1
	END

		IF @TIPO_DISTRIBUICAO = 2
		BEGIN	
			BEGIN TRY

				DELETE FROM FATURAMENTO_CAIXAS
				WHERE CAIXA = @CAIXA AND CAIXA NOT IN (SELECT CAIXA FROM FATURAMENTO_PROD)

				DELETE FROM CAEDU_RESERVA_AUTOMATICA_WMS 
				WHERE CAIXA = @CAIXA

				DELETE
				FROM VENDAS_PROD_EMBALADO
				WHERE CAIXA = @CAIXA

				DELETE CAEDU_RESERVA_AUTOMATICA_PACK_WMS 
				WHERE CAIXA = @CAIXA

			END TRY

			BEGIN CATCH

				 SET @MSG = 'ERRO NA TRANSACAO: '+ERROR_MESSAGE()
				RAISERROR(@MSG, 16, 1)

			END CATCH
		END

		IF @TIPO_DISTRIBUICAO = 1
		BEGIN	
			BEGIN TRY

				DELETE FROM FATURAMENTO_CAIXAS
				WHERE CAIXA = @CAIXA AND CAIXA NOT IN (SELECT CAIXA FROM FATURAMENTO_PROD)

				DELETE FROM CAEDU_RESERVA_AUTOMATICA
				WHERE CAIXA = @CAIXA

				DELETE
				FROM VENDAS_PROD_EMBALADO
				WHERE CAIXA = @CAIXA

			END TRY

			BEGIN CATCH

				 SET @MSG = 'ERRO NA TRANSACAO: '+ERROR_MESSAGE()
				RAISERROR(@MSG, 16, 1)

			END CATCH
		END

		IF @TIPO_DISTRIBUICAO = 3
		BEGIN	
			BEGIN TRY

				DELETE FROM FATURAMENTO_CAIXAS
				WHERE CAIXA = @CAIXA AND CAIXA NOT IN (SELECT CAIXA FROM FATURAMENTO_PROD)

				DELETE
				FROM VENDAS_PROD_EMBALADO
				WHERE CAIXA = @CAIXA

			END TRY

			BEGIN CATCH

				 SET @MSG = 'ERRO NA TRANSACAO: '+ERROR_MESSAGE()
				RAISERROR(@MSG, 16, 1)

			END CATCH
		END


END
GO



