USE [CAEDU]
GO
/****** Object:  StoredProcedure [dbo].[CGP_VALIDA_PEDIDO_UMODE]    Script Date: 14/10/2025 08:40:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER   PROCEDURE [dbo].[CGP_VALIDA_PEDIDO_UMODE]
	@PRODUTO VARCHAR(12)
AS

declare	@REQUERIDO_POR	varchar(25),	     	     
		@TIPO_COMPRA	varchar(25),	     	     
		@ERP_CAB_OPCAO	int,
		@ERP_CAB_COD_CABIDE	varchar(15),	     	     
		@ENTREGA	datetime,	     	     
		@LIMITE_ENTREGA	datetime,	     	     
		@ERP_CUPS_DATA_ACORDADA	datetime,  	     
		@DATA_UMODE	datetime,
		@ERP_CUPS_CUSTO_FOB_MINIMO numeric(10,4),
		@ERP_CUPS_CUSTO_FOB numeric(10,4),
		@MSG VARCHAR(MAX),
		@STATUS VARCHAR(3),
		@POSITION_REQUERIDO_POR INT = 0, 
		@TOTALPACK INT,
		@TOTALSOMAPACK INT,
		@ERP_USA_BOLACHA bit

SET @STATUS = 'OK'
SET @MSG = ''

select
	@REQUERIDO_POR = ISNULL(REQUERIDO_POR,'...'),	     	     
	@TIPO_COMPRA = ISNULL(TIPO_COMPRA,'...'),	     	     
	@ERP_CAB_OPCAO = ISNULL(ERP_CAB_OPCAO,0),
	@ERP_CAB_COD_CABIDE	= ISNULL(ERP_CAB_COD_CABIDE,'...'),	     	     
	@ENTREGA = ISNULL(ERP_ENTREGA,''),	     	     
	@LIMITE_ENTREGA	= ISNULL(ERP_LIMITE_ENTREGA,''),	     	     
	@ERP_CUPS_DATA_ACORDADA	= ISNULL(ERP_CUPS_DATA_ACORDADA,''),  	     
	@DATA_UMODE	= ISNULL(DATA_UMODE,''),
	@ERP_CUPS_CUSTO_FOB_MINIMO = ISNULL(ERP_CUPS_CUSTO_FOB_MINIMO,0),
	@ERP_CUPS_CUSTO_FOB = ISNULL(ERP_CUPS_CUSTO_FOB,0)
from produtos where PRODUTO = @PRODUTO

DECLARE @LF VARCHAR(10) = CHAR(13)+CHAR(10)

IF @DATA_UMODE = ''
BEGIN
	SET @STATUS = 'NOK'
	SET @MSG = @MSG + @LF + 'PRODUTO NÃO FOI CADASTRADO PELO PLM-UMODE!' +@LF+'CADASTRE /ALTERE O PEDIDO PELO FLUXO NORMAL' +@LF
END

select @POSITION_REQUERIDO_POR = CHARINDEX(@REQUERIDO_POR,NOTA_PROGRAMADOR) 
from parametros 
where parametro like 'PALMA_GERENTES_PEDIDO'

IF @POSITION_REQUERIDO_POR = 0
BEGIN
	SET @STATUS = 'NOK'
	SET @MSG = @MSG + @LF + 'REQUERIDO POR INVÁLIDO OU NULO' +@LF
END

IF NOT EXISTS(SELECT TIPO_COMPRA 
			FROM COMPRAS_TIPOS 
			WHERE TIPO_COMPRA = @TIPO_COMPRA)
BEGIN
	SET @STATUS = 'NOK'
	SET @MSG = @MSG + @LF + 'TIPO DE COMPRA INVÁLIDO OU NULO' + @LF
END

IF @ERP_CAB_OPCAO = 0
BEGIN
	SET @STATUS = 'NOK'
	SET @MSG = @MSG + @LF + 'OPÇÃO DE CABILOG INVÁLIDA OU NULA' +@LF
END

SELECT @ERP_USA_BOLACHA = ERP_USA_BOLACHA
FROM FORNECEDORES 
WHERE FORNECEDOR = (SELECT TOP 1 FABRICANTE FROM PRODUTOS WHERE PRODUTO = @PRODUTO)

IF @ERP_USA_BOLACHA=0 AND @ERP_CAB_OPCAO IN (3,4)
BEGIN
	SET @STATUS = 'NOK'
	SET @MSG = @MSG + @LF + 'OPÇÃO CABILOG 3 E 4 INVÁLIDA PARA O FORNECEDOR, POIS NÃO ESTA HABILITADO NO CADASTRO PARA USAR ALARME' +@LF
END

IF (@ERP_CAB_OPCAO IN (2,4)) AND (@ERP_CAB_COD_CABIDE='...')
BEGIN
	SET @STATUS = 'NOK'
	SET @MSG = @MSG + @LF + 'OPÇÃO DE CABIDE INVÁLIDA PARA OPCAO SELECIONADA' +@LF
END

IF (@ERP_CAB_OPCAO IN (2,4)) AND NOT EXISTS(SELECT 1 FROM CAEDU_LISTA_COMBO WHERE id_dominio='022' and descricao = @ERP_CAB_COD_CABIDE)
BEGIN
	SET @STATUS = 'NOK'
	SET @MSG = @MSG + @LF + 'CÓDIGO DE CABIDE '+@ERP_CAB_COD_CABIDE+' INEXISTENTE PARA OPCAO SELECIONADA' +@LF
END

IF (@ENTREGA = '') OR (@LIMITE_ENTREGA = '')
BEGIN
	SET @STATUS = 'NOK'
	SET @MSG = @MSG + @LF + 'DATA DE ENTREGA /LIMITE DE ENTREGA NÃO PREENCHIDA' +@LF
END

/* verifica se o pack foi configurado */
select 	@TOTALPACK = ISNULL(A.QTDE,0),
		@TOTALSOMAPACK = ISNULL(Q1,0)+ISNULL(Q2,0)+ISNULL(Q3,0)+ISNULL(Q4,0)+ISNULL(Q5,0)+
		ISNULL(Q6,0)+ISNULL(Q7,0)+ISNULL(Q8,0)+ISNULL(Q9,0)+ISNULL(Q10,0)+
		ISNULL(Q11,0)+ISNULL(Q12,0)+ISNULL(Q13,0)+ISNULL(Q14,0)+ISNULL(Q15,0)+ISNULL(Q16,0)
from PRODUTOS_PACKS_PERMITIDOS A
where produto = @PRODUTO

IF (@TOTALPACK=0) OR (@TOTALSOMAPACK=0)
BEGIN
	SET @STATUS = 'NOK'
	SET @MSG = @MSG + @LF + 'ERRO NA CONFIGURAÇÃO DO PACK DO PRODUTO' +@LF
END

IF LEN(@MSG)> 0
	SET @MSG = @MSG + @LF + 'FAÇA A ENTRADA DO PEDIDO PELO MÉTODO NORMAL - NÃO USAREMOS DADOS DO PLM/UMODE'

SELECT @STATUS AS STATUS_UMODE, @MSG AS MENSAGEM

