SELECT 
	FILIAL,
	PRODUTO,
	COR_PRODUTO,
	ITEM_COMPOSICAO,
	DESC_ITEM_COMPOSICAO,
	CAST(DATA_MOV AS date) DATA_MOV,
	DOC,
	OP_PED_ROMAN,
	SERIE_NF,
	QTDE,
	CUSTO_MEDIO_UNITARIO,
	VALOR_CUSTO,
	COD_CUSTO_MEDIO,
	COD_TRANSACAO,
	TIPO_OPERACAO,
	CHAVE_NFE
FROM FX_CSM_GERA_KARDEX_CM('DIADEMA','%','20240101','20240131')
WHERE ITEM_COMPOSICAO='018'
ORDER BY PRODUTO, DATA_MOV, ITEM_COMPOSICAO, DOC



	select * from ESTOQUE_PROD_CONTAGEM where YEAR(EMISSAO)=2024 and FILIAL not like '%CD%'


SELECT * 
FROM CM_ESTOQUE_PA 
WHERE COD_CUSTO_MEDIO LIKE '202401%' AND FILIAL='DIADEMA'



select top 1 * from CM_FECHAMENTO_CUSTO_MEDIO 
WHERE COD_CUSTO_MEDIO LIKE '202401%' and 
data_geracao = (select MAX(data_geracao) from CM_FECHAMENTO_CUSTO_MEDIO WHERE COD_CUSTO_MEDIO LIKE '202401%')
order by COD_CUSTO_MEDIO desc

	SELECT COD_CUSTO_MEDIO 
	FROM CM_FECHAMENTO_CUSTO_MEDIO 
	WHERE YEAR('20240131') = YEAR(DATA_SALDO) AND MONTH('20240131') = MONTH(DATA_SALDO) 