ALTER TABLE COMPRAS
    ADD ERP_IMPORTADO BIT NOT NULL DEFAULT(0)
go

ALTER TABLE COMPRAS
    ADD ERP_MOEDA VARCHAR(5) NULL 
GO

ALTER TABLE COMPRAS 
ADD ERP_TOTAL_QTD_DISTRIB INT NULL, ERP_PERCENT_DISTRIB NUMERIC(10,6) NULL
GO

ALTER TABLE COMPRAS
ADD ERP_TOTAL_CAIXAS_ORIGINAL INT NULL
GO

