ALTER TABLE COND_ENT_PGTOS
ADD ERP_EBS_TIPO_DATA_1 INT NULL,
	ERP_EBS_TIPO_DATA_2 INT NULL,
	ERP_EBS_TIPO_DATA_3 INT NULL,
	ERP_EBS_TIPO_DATA_4 INT NULL,
	ERP_EBS_TIPO_DATA_5 INT NULL,
	ERP_EBS_TIPO_DATA_6 INT NULL,
	ERP_EBS_TIPO_DATA_7 INT NULL,
	ERP_EBS_TIPO_DATA_8 INT NULL,
	ERP_EBS_TIPO_DATA_9 INT NULL,
	ERP_EBS_TIPO_DATA_10 INT NULL,
	ERP_EBS_TIPO_DATA_11 INT NULL,
	ERP_EBS_TIPO_DATA_12 INT NULL
GO
