ALTER TABLE ENTRADAS 
	ADD ERP_EBS_AP_DATA_ENVIO DATETIME NULL,
		ERP_EBS_GL_DATA_ENVIO DATETIME NULL,
		ERP_EBS_SYNCHRO_DATA_ENVIO DATETIME NULL
GO

ALTER TABLE FATURAMENTO 
	ADD ERP_EBS_AR_DATA_ENVIO DATETIME NULL,
		ERP_EBS_GL_DATA_ENVIO DATETIME NULL,
		ERP_EBS_SYNCHRO_DATA_ENVIO DATETIME NULL
GO


