
/*
COMPRAS_PRODUTO
PRODUTOS
*/

/*SELECT * FROM COMPRAS_PRODUTO WHERE PEDIDO = '128456'*/

CREATE TABLE CAEDU_LOG_AUTORIZA_COMPRAS (
ID_LOG CHAR(10) NOT NULL PRIMARY KEY,
DATA_LOG DATETIME NOT NULL DEFAULT (GETDATE()),
GRIFFE VARCHAR(25) NULL,
LINHA  VARCHAR(25) NULL,
GRUPO_PRODUTO  VARCHAR(25) NULL,
SUBGRUPO_PRODUTO VARCHAR(25) NULL,
PEDIDO CHAR(8) NULL,
FORNECEDOR VARCHAR(25) NULL,
PRODUTO CHAR(12) NULL,
DESC_PRODUTO VARCHAR(40),
QTDE_ORIGINAL INT NULL,
QTDE_ATUAL INT NULL,
QTDE_ANTERIOR INT NULL,
VALOR_ORIGINAL NUMERIC(14,2) NULL,
VALOR_ATUAL NUMERIC(14,2) NULL,
VALOR_ANTERIOR NUMERIC(14,2) NULL,
CUSTO_ORIGINAL NUMERIC(18,6) NULL,
CUSTO_ATUAL NUMERIC(18,6) NULL,
CUSTO_ANTERIOR NUMERIC(18,6) NULL,
LIMITE_ENTREGA_ORIGINAL DATETIME NULL,
LIMITE_ENTREGA_ATUAL DATETIME NULL,
LIMITE_ENTREGA_ANTERIOR DATETIME NULL,
MARGEM_ORIGINAL NUMERIC(14,2) NULL,
MARGEM_ATUAL NUMERIC(14,2) NULL,
MARGEM_ANTERIOR NUMERIC(14,2) NULL,
CONDICAO_PGTO_ORIGINAL CHAR(3) NULL,
CONDICAO_PGTO_ATUAL CHAR(3) NULL,
CONDICAO_PGTO_ANTERIOR CHAR(3) NULL,
STATUS_APROVACAO INT NULL, /* 1 - AGUARDANDO APROVAÇÃO, 2 - APROVADO,  3 - REPROVADO */
OBSERVACAO VARCHAR(250) NULL )





