
CREATE TABLE dbo.CAEDU_METRICAS_LOG_COMPRAS
(COD_METRICA		CHAR(2) NOT NULL PRIMARY KEY,
DESC_METRICA	VARCHAR(40) NOT NULL,
TIPO_DADO		VARCHAR(20) NOT NULL )
GO

INSERT INTO dbo.CAEDU_METRICAS_LOG_COMPRAS VALUES ('01', 'QUANTIDADE', 'INT')
INSERT INTO dbo.CAEDU_METRICAS_LOG_COMPRAS VALUES ('02', 'VALOR', 'NUMERIC (14,2)')
INSERT INTO dbo.CAEDU_METRICAS_LOG_COMPRAS VALUES ('03', 'CUSTO', 'NUMERIC (14,2)')
INSERT INTO dbo.CAEDU_METRICAS_LOG_COMPRAS VALUES ('04', 'LIMITE DE ENTREGA', 'DATETIME')
INSERT INTO dbo.CAEDU_METRICAS_LOG_COMPRAS VALUES ('05', 'MARGEM', 'NUMERIC (14,2)')
INSERT INTO dbo.CAEDU_METRICAS_LOG_COMPRAS VALUES ('06', 'CONDIÇÃO DE PAGAMENTO', 'CHAR(3)')
INSERT INTO dbo.CAEDU_METRICAS_LOG_COMPRAS VALUES ('07', 'SALDO OTB NACIONAL', 'BIT')
