/* EXEC dbo.spCAEDU_Consulta_Estoque_Integrado '000029', '20150519', '20160728' */
ALTER PROCEDURE dbo.spCAEDU_Consulta_Estoque_Integrado
/*
Autor....: PAULO EDUARDO DEVIDE
Criado em: 10/out/16
Executado pela tela LX999350
*/
@CODFILIAL varchar(6),
@DATA1 datetime,
@DATA2 datetime

AS

BEGIN

SELECT 
    OPERACAO,
    CM_OPERACAO,
    PRODUTO,
    COR_PRODUTO = ISNULL(RTRIM(LTRIM(COR_PRODUTO)),0),
    CODIGO_FILIAL,
    DATA_VENDA = CAST(DATA_VENDA AS DATE),
    SK_DIA = CONVERT (VARCHAR(8),DATA_VENDA,112) ,
    TAMANHO,
    PRECO_LIQUIDO,
    PRECO_CAEDU,
    PRECO_NORMAL,
    PRECO_ORIGINAL,
    QTD_VENDA = SUM(QTD_VENDA * CASE WHEN OPERACAO IN ('VENDA','FAT_SAIDA') THEN -1 ELSE 1 END),
    QTD_TROCA = SUM(QTD_TROCA),
    QTD_AJUSTE = SUM(QTD_AJUSTE * CASE WHEN OPERACAO = 'AJ-SAIDA' THEN -1 ELSE 1 END),
    VLR_VENDA_BRUTO = SUM(VLR_VENDA_BRUTO * CASE WHEN OPERACAO IN ('VENDA','FAT_SAIDA') THEN -1 ELSE 1 END),
    VLR_VENDA_LIQUIDO = SUM((VLR_VENDA_BRUTO - VLR_DESCTO_TICKET - VLR_DESCTO - VLR_TROCA) * CASE WHEN OPERACAO IN ('VENDA','FAT_SAIDA') THEN -1 ELSE 1 END),
    VLR_TROCA_BRUTO = SUM(VLR_TROCA_BRUTO),
    VLR_AJUSTE_BRUTO = SUM(VLR_AJUSTE_BRUTO * CASE WHEN OPERACAO = 'AJ-SAIDA' THEN -1 ELSE 1 END),
    VLR_CUSTO_TROCA = SUM(VLR_CUSTO_TROCA),
    VLR_DESCTO = SUM(VLR_DESCTO * CASE WHEN OPERACAO = 'AJ-SAIDA' THEN -1 ELSE 1 END),
    VLR_TROCA = SUM(VLR_TROCA),
    VLR_CUSTO_TOTAL = SUM(VLR_CUSTO_TOTAL * CASE WHEN OPERACAO = 'AJ-SAIDA' THEN -1 ELSE 1 END),
    VLR_DESCTO_TICKET = SUM(VLR_DESCTO_TICKET)
FROM (

/*OPERAÇÃO DE VENDAS DE LOJAS*/
SELECT 
    OPERACAO = MAX('VENDA'),
    CM_OPERACAO=MAX('VEN'),
    PRODUTO = P.PRODUTO,
    COR_PRODUTO = ISNULL(RTRIM(LTRIM(P.COR_PRODUTO)),0),
    CODIGO_FILIAL = P.CODIGO_FILIAL,
    DATA_VENDA = P.DATA_VENDA,
    TAMANHO = ISNULL(P.TAMANHO,0),
    PRECO_LIQUIDO = ISNULL(P.PRECO_LIQUIDO, 0),
    PRECO_CAEDU = ISNULL(PC.PRECO1,0),
    PRECO_NORMAL = ISNULL(PC2.PRECO1,0),
    PRECO_ORIGINAL = ISNULL(PC3.PRECO1,0),
    QTD_VENDA = SUM(ISNULL(P.QTDE, 0)),
    QTD_TROCA = 0,
    QTD_AJUSTE = 0,
    QTD_TICKET = CASE
				WHEN (SUM(P.QTDE) <> 0)
				    AND (SUM(P.QTDE_CANCELADA) = 0) THEN COUNT(DISTINCT P.TICKET)
				ELSE 0
				END,
    QTD_TICKET_CANCELADA = CASE
		  			    WHEN (SUM(P.QTDE_CANCELADA) <> 0)
			 			   AND (SUM(P.QTDE) = 0) THEN COUNT(DISTINCT P.TICKET)
					    ELSE 0
				        END,
    QTD_ITENS_CANCELADOS = SUM(P.QTDE_CANCELADA),
    VLR_VENDA_BRUTO = SUM((ISNULL(P.PRECO_LIQUIDO, 0) + ISNULL(P.DESCONTO_ITEM, 0)) * ISNULL(P.QTDE, 0)),
    VLR_TROCA_BRUTO = 0,
    VLR_AJUSTE_BRUTO = 0,
    VLR_CUSTO_TROCA = 0,
    VLR_DESCTO = SUM(ISNULL(P.DESCONTO_ITEM, 0) * ISNULL(P.QTDE, 0)),
VLR_TROCA = 0,
VLR_CUSTO_TOTAL = SUM(ISNULL(P.CUSTO, 0) * ISNULL(P.QTDE, 0)),
VLR_DESCTO_TICKET = SUM(ISNULL(P.QTDE, 0) * ISNULL(P.RATEIO_DESCONTO_VENDA, 0))
FROM 
    CAEDU.DBO.LOJA_VENDA_PRODUTO P WITH (NOLOCK)
LEFT JOIN 
    CAEDU.DBO.PRODUTOS_PRECOS PC WITH (NOLOCK) 
	   ON P.PRODUTO = PC.PRODUTO   AND PC.CODIGO_TAB_PRECO = '05'
LEFT JOIN 
    CAEDU.DBO.PRODUTOS_PRECOS PC2 WITH (NOLOCK) 
	   ON P.PRODUTO = PC2.PRODUTO AND PC2.CODIGO_TAB_PRECO = '00'
LEFT JOIN 
    CAEDU.DBO.PRODUTOS_PRECOS PC3 WITH (NOLOCK) 
	   ON P.PRODUTO = PC3.PRODUTO AND PC3.CODIGO_TAB_PRECO = '01'
WHERE 

    P.CODIGO_FILIAL = @CODFILIAL AND (P.DATA_VENDA BETWEEN @DATA1 AND @DATA2) AND P.QTDE <> 0

GROUP BY 
    P.PRODUTO,
    P.COR_PRODUTO,
    P.CODIGO_FILIAL,
    P.DATA_VENDA,
    P.TAMANHO,
    ISNULL(PC.PRECO1,0),
    ISNULL(PC2.PRECO1,0),
    ISNULL(PC3.PRECO1,0),
    ISNULL(P.PRECO_LIQUIDO, 0)

UNION 

/*OPERAÇÃO DE TROCAS DE LOJAS LINX*/
SELECT 
    OPERACAO = MAX('TROCA'),
    CM_OPERACAO = MAX('TRO'),
    PRODUTO = T.PRODUTO,
    COR_PRODUTO = ISNULL(RTRIM(LTRIM(T.COR_PRODUTO)),0),
    CODIGO_FILIAL = T.CODIGO_FILIAL,
    DATA_VENDA = T.DATA_VENDA,
    TAMANHO = T.TAMANHO,
    PRECO_LIQUIDO = ISNULL(T.PRECO_LIQUIDO, 0),
    PRECO_CAEDU = ISNULL(PC.PRECO1,0),
    PRECO_NORMAL = ISNULL(PC2.PRECO1,0),
    PRECO_ORIGINAL = ISNULL(PC3.PRECO1,0),
    QTD_VENDA = 0,
    QTD_TROCA = SUM(ISNULL(T.QTDE, 0)),
    QTD_AJUSTE = 0,
    QTD_TICKET = CASE
				WHEN (SUM(T.QTDE) <> 0)
				    AND (SUM(T.QTDE_CANCELADA) = 0) THEN COUNT(DISTINCT T.TICKET)
				ELSE 0
				END,
    QTD_TICKET_CANCELADA = CASE
					   WHEN (SUM(T.QTDE_CANCELADA) <> 0)
						  AND (SUM(T.QTDE) = 0) THEN COUNT(DISTINCT T.TICKET)
					   ELSE 0
					   END,
    QTD_ITENS_CANCELADOS = SUM(T.QTDE_CANCELADA),
    VLR_VENDA_BRUTO = 0,
    VLR_TROCA_BRUTO = SUM((ISNULL(T.PRECO_LIQUIDO, 0) + ISNULL(T.DESCONTO_ITEM, 0)) * ISNULL(T.QTDE, 0)),
    VLR_AJUSTE_BRUTO = 0,
    VLR_CUSTO = SUM(ISNULL(T.CUSTO, 0) * ISNULL(T.QTDE, 0)),
    VLR_DESCTO = SUM(ISNULL(T.DESCONTO_ITEM, 0) * ISNULL(T.QTDE, 0)),
    VLR_TROCA = SUM(ISNULL(T.PRECO_LIQUIDO, 0) * ISNULL(T.QTDE, 0)),
    VLR_CUSTO_TOTAL = 0,
    VLR_DESCTO_TICKET = 0
FROM 
    CAEDU.DBO.LOJA_VENDA_TROCA T
LEFT JOIN 
    CAEDU.DBO.PRODUTOS_PRECOS PC 
	   ON T.PRODUTO = PC.PRODUTO AND PC.CODIGO_TAB_PRECO = '05'
LEFT JOIN 
    CAEDU.DBO.PRODUTOS_PRECOS PC2 
	   ON T.PRODUTO = PC2.PRODUTO AND PC2.CODIGO_TAB_PRECO = '00'
LEFT JOIN 
    CAEDU.DBO.PRODUTOS_PRECOS PC3 
	   ON T.PRODUTO = PC3.PRODUTO AND PC3.CODIGO_TAB_PRECO = '01'
WHERE 

    T.CODIGO_FILIAL = @CODFILIAL AND (T.DATA_VENDA BETWEEN @DATA1 AND @DATA2) AND T.QTDE <> 0

GROUP BY 
    T.PRODUTO,
    T.COR_PRODUTO,
    T.CODIGO_FILIAL,
    T.DATA_VENDA,
    T.TAMANHO,
    ISNULL(T.PRECO_LIQUIDO, 0),
    ISNULL(PC.PRECO1,0),
    ISNULL(PC2.PRECO1,0),
    ISNULL(PC3.PRECO1,0)

UNION 

/*OPERAÇÃO DE TROCAS DE LOJAS PDV PALMA*/
SELECT 
    OPERACAO = MAX('TROCA'),
    CM_OPERACAO = MAX('TRO'),
    PRODUTO = TP.PRODUTO,
    COR_PRODUTO = ISNULL(RTRIM(LTRIM(TP.COR_PRODUTO)),0),
    CODIGO_FILIAL = TP.CODIGO_FILIAL,
    DATA_VENDA = TP.DATA_VENDA,
    TAMANHO = TP.TAMANHO,
    PRECO_LIQUIDO = ISNULL(TP.PRECO_LIQUIDO, 0),
    PRECO_CAEDU = ISNULL(PC.PRECO1,0),
    PRECO_NORMAL = ISNULL(PC2.PRECO1,0),
    PRECO_ORIGINAL = ISNULL(PC3.PRECO1,0),
    QTD_VENDA = 0,
    QTD_TROCA = SUM(ISNULL(TP.QTDE, 0)),
    QTD_AJUSTE = 0,
    QTD_TICKET =	CASE
				    WHEN (SUM(TP.QTDE) <> 0) AND (SUM(TP.QTDE_CANCELADA) = 0) THEN COUNT(DISTINCT TP.TICKET)
				    ELSE 0
				END,
    QTD_TICKET_CANCELADA =  CASE
						  WHEN (SUM(TP.QTDE_CANCELADA) <> 0) AND (SUM(TP.QTDE) = 0) THEN COUNT(DISTINCT TP.TICKET)
						  ELSE 0
					   END,
    QTD_ITENS_CANCELADOS = SUM(TP.QTDE_CANCELADA),
    VLR_VENDA_BRUTO = 0,
    VLR_TROCA_BRUTO = SUM((ISNULL(TP.PRECO_LIQUIDO, 0) + ISNULL(TP.DESCONTO_ITEM, 0)) * ISNULL(TP.QTDE, 0)),
    VLR_AJUSTE_BRUTO = 0,
    VLR_CUSTO = SUM(ISNULL(TP.CUSTO, 0) * ISNULL(TP.QTDE, 0)),
    VLR_DESCTO = SUM(ISNULL(TP.DESCONTO_ITEM, 0) * ISNULL(TP.QTDE, 0)),
    VLR_TROCA = SUM(ISNULL(TP.PRECO_LIQUIDO, 0) * ISNULL(TP.QTDE, 0)),
    VLR_CUSTO_TOTAL = 0,
    VLR_DESCTO_TICKET = 0
FROM 
    CAEDU.DBO.PDVP_LOJA_VENDA_TROCA TP
LEFT JOIN 
    CAEDU.DBO.PRODUTOS_PRECOS PC 
	   ON TP.PRODUTO = PC.PRODUTO AND PC.CODIGO_TAB_PRECO = '05'
LEFT JOIN 
    CAEDU.DBO.PRODUTOS_PRECOS PC2 
	   ON TP.PRODUTO = PC2.PRODUTO AND PC2.CODIGO_TAB_PRECO = '00'
LEFT JOIN 
    CAEDU.DBO.PRODUTOS_PRECOS PC3 
	   ON TP.PRODUTO = PC3.PRODUTO AND PC3.CODIGO_TAB_PRECO = '01'
WHERE 

    TP.CODIGO_FILIAL = @CODFILIAL AND (TP.DATA_VENDA BETWEEN @DATA1 AND @DATA2) AND TP.QTDE <> 0

GROUP BY 
    TP.PRODUTO,
    TP.COR_PRODUTO,
    TP.CODIGO_FILIAL,
    TP.DATA_VENDA,
    TP.TAMANHO,
    ISNULL(TP.PRECO_LIQUIDO, 0),
    ISNULL(PC.PRECO1,0),
    ISNULL(PC2.PRECO1,0),
    ISNULL(PC3.PRECO1, 0)

UNION 

/*OPERAÇÃO DE AJUSTES DE ENTRADA CM_OPERACAO = 003/661*/
SELECT 
    OPERACAO = MAX('AJ-ENTRADA'),
    CM_OPERACAO,
    PRODUTO = P.PRODUTO,
    COR_PRODUTO = ISNULL(RTRIM(LTRIM(P.COR_PRODUTO)),0),
    CODIGO_FILIAL = FI.COD_FILIAL,
    DATA_VENDA = E.EMISSAO,
    TAMANHO = 0,
    PRECO_LIQUIDO = ISNULL(P.CUSTO1, 0),
    PRECO_CAEDU = ISNULL(PC.PRECO1,0),
    PRECO_NORMAL = ISNULL(PC2.PRECO1,0),
    PRECO_ORIGINAL = ISNULL(PC3.PRECO1,0),
    QTD_VENDA = 0,
    QTD_TROCA = 0,
    QTD_AJUSTE = SUM(ISNULL(P.QTDE, 0)),
    QTD_TICKET = 0,
    QTD_TICKET_CANCELADA = 0,
    QTD_ITENS_CANCELADOS = 0,
    VLR_VENDA_BRUTO = 0,
    VLR_TROCA_BRUTO = 0,
    VLR_AJUSTE_BRUTO = SUM((ISNULL(P.CUSTO1, 0) + ISNULL(P.DESCONTO_ITEM, 0)) * ISNULL(P.QTDE, 0)),
    VLR_CUSTO_TROCA = 0,
    VLR_DESCTO = SUM(ISNULL(P.DESCONTO_ITEM, 0) * ISNULL(P.QTDE, 0)),
    VLR_TROCA = 0,
    VLR_CUSTO_TOTAL = SUM(ISNULL(P.CUSTO1, 0) * ISNULL(P.QTDE, 0)),
    VLR_DESCTO_TICKET = 0
FROM 
    CAEDU.DBO.ESTOQUE_PROD1_ENT P WITH (NOLOCK)
LEFT JOIN 
    FILIAIS FI 
	   ON FI.FILIAL = P.FILIAL
LEFT JOIN 
    ESTOQUE_PROD_ENT E (NOLOCK) 
	   ON E.ROMANEIO_PRODUTO = P.ROMANEIO_PRODUTO AND E.FILIAL = P.FILIAL
LEFT JOIN 
    CAEDU.DBO.PRODUTOS_PRECOS PC WITH (NOLOCK) 
	   ON P.PRODUTO = PC.PRODUTO AND PC.CODIGO_TAB_PRECO = '05'
LEFT JOIN 
    CAEDU.DBO.PRODUTOS_PRECOS PC2 WITH (NOLOCK) 
	   ON P.PRODUTO = PC2.PRODUTO AND PC2.CODIGO_TAB_PRECO = '00'
LEFT JOIN 
    CAEDU.DBO.PRODUTOS_PRECOS PC3 WITH (NOLOCK) 
	   ON P.PRODUTO = PC3.PRODUTO AND PC3.CODIGO_TAB_PRECO = '01'

WHERE 

    FI.COD_FILIAL = @CODFILIAL AND
    (E.EMISSAO BETWEEN @DATA1 AND @DATA2) AND P.QTDE <> 0 
    AND E.CM_OPERACAO IN ('003','661')

GROUP BY 
CM_OPERACAO,
P.PRODUTO,
P.COR_PRODUTO,
FI.COD_FILIAL,
E.EMISSAO,
ISNULL(PC.PRECO1,0),
ISNULL(PC2.PRECO1,0),
ISNULL(PC3.PRECO1,0),
ISNULL(P.CUSTO1, 0)

UNION 

/*OPERAÇÃO DE AJUSTES DE SAIDA CM_OPERACAO = 011/662*/
SELECT 
OPERACAO = MAX('AJ-SAIDA'),
CM_OPERACAO,
PRODUTO = PS.PRODUTO,
COR_PRODUTO = ISNULL(RTRIM(LTRIM(PS.COR_PRODUTO)),0),
CODIGO_FILIAL = FI.COD_FILIAL,
DATA_VENDA = S.EMISSAO,
TAMANHO = 0,
PRECO_LIQUIDO = ISNULL(PS.CUSTO1, 0),
PRECO_CAEDU = ISNULL(PC.PRECO1,0),
PRECO_NORMAL = ISNULL(PC2.PRECO1, 0),
PRECO_ORIGINAL = ISNULL(PC3.PRECO1,0),
QTD_VENDA = 0,
QTD_TROCA = 0,
QTD_AJUSTE = SUM(ISNULL(PS.QTDE, 0)),
QTD_TICKET = 0,
QTD_TICKET_CANCELADA = 0,
QTD_ITENS_CANCELADOS = 0,
VLR_VENDA_BRUTO = 0,
VLR_TROCA_BRUTO = 0,
VLR_AJUSTE_BRUTO = SUM((ISNULL(PS.CUSTO1, 0) + ISNULL(PS.DESCONTO_ITEM, 0)) * ISNULL(PS.QTDE, 0)),
VLR_CUSTO_TROCA = 0,
VLR_DESCTO = SUM(ISNULL(PS.DESCONTO_ITEM, 0) * ISNULL(PS.QTDE, 0)),
VLR_TROCA = 0,
VLR_CUSTO_TOTAL = SUM(ISNULL(PS.CUSTO1, 0) * ISNULL(PS.QTDE, 0)),
VLR_DESCTO_TICKET = 0
FROM 
    CAEDU.DBO.ESTOQUE_PROD1_SAI PS WITH (NOLOCK)
LEFT JOIN 
    FILIAIS FI 
	   ON FI.FILIAL = PS.FILIAL
LEFT JOIN 
    ESTOQUE_PROD_SAI S (NOLOCK) 
	   ON S.ROMANEIO_PRODUTO = PS.ROMANEIO_PRODUTO AND S.FILIAL = PS.FILIAL
LEFT JOIN CAEDU.DBO.PRODUTOS_PRECOS PC WITH (NOLOCK) 
    ON PS.PRODUTO = PC.PRODUTO AND PC.CODIGO_TAB_PRECO = '05'
LEFT JOIN 
    CAEDU.DBO.PRODUTOS_PRECOS PC2 WITH (NOLOCK) 
	   ON PS.PRODUTO = PC2.PRODUTO AND PC2.CODIGO_TAB_PRECO = '00'
LEFT JOIN CAEDU.DBO.PRODUTOS_PRECOS PC3 WITH (NOLOCK) 
    ON PS.PRODUTO = PC3.PRODUTO AND PC3.CODIGO_TAB_PRECO = '01'
WHERE 

    FI.COD_FILIAL = @CODFILIAL AND
    (S.EMISSAO BETWEEN @DATA1 AND @DATA2) AND PS.QTDE <> 0
     AND S.CM_OPERACAO IN ('011','662')

GROUP BY 
    CM_OPERACAO,
    PS.PRODUTO,
    PS.COR_PRODUTO,
    FI.COD_FILIAL,
    S.EMISSAO,
    ISNULL(PC.PRECO1,0),
    ISNULL(PC2.PRECO1,0),
    ISNULL(PC3.PRECO1,0),
    ISNULL(PS.CUSTO1, 0)

UNION

/*OPERAÇÃO DE AJUSTES DE INVENTÁRIO*/
SELECT 
    OPERACAO = MAX('AJ_INVENT'),
    CM_OPERACAO=MAX('INV'),
    PRODUTO = P.PRODUTO,
    COR_PRODUTO = ISNULL(RTRIM(LTRIM(P.COR_PRODUTO)),0),
    CODIGO_FILIAL = fi.COD_FILIAL,
    DATA_VENDA = epc.DATA_AJUSTE,
    TAMANHO = 0,
    PRECO_LIQUIDO = ISNULL(WPC.CUSTO_REPOSICAO1, 0),
    PRECO_CAEDU = ISNULL(WPC.CUSTO_REPOSICAO1,0),
    PRECO_NORMAL = ISNULL(WPC.CUSTO_REPOSICAO1,0),
    PRECO_ORIGINAL = ISNULL(WPC.CUSTO_REPOSICAO1,0),
    QTD_VENDA = SUM(ISNULL(P.QTDE_AJUSTE, 0)),
    QTD_TROCA = 0,
    QTD_AJUSTE = 0,
    QTD_TICKET = 0,
    QTD_TICKET_CANCELADA = 0,
    QTD_ITENS_CANCELADOS = 0,
    VLR_VENDA_BRUTO = SUM(ISNULL(WPC.CUSTO_REPOSICAO1, 0) * ISNULL(P.QTDE_AJUSTE, 0)),
    VLR_TROCA_BRUTO = 0,
    VLR_AJUSTE_BRUTO = 0,
    VLR_CUSTO_TROCA = 0,
    VLR_DESCTO = 0,
    VLR_TROCA = 0,
    VLR_CUSTO_TOTAL = SUM(ISNULL(WPC.CUSTO_REPOSICAO1, 0) * ISNULL(P.QTDE_AJUSTE, 0)),
    VLR_DESCTO_TICKET = 0
FROM 
    DBO.ESTOQUE_PROD_CTG_AJUSTE P WITH (NOLOCK)
LEFT JOIN 
    DBO.ESTOQUE_PROD_CONTAGEM epc  (NOLOCK) 
	   ON epc.NOME_CONTAGEM = P.NOME_CONTAGEM
LEFT JOIN 
    FILIAIS fi 
	   ON epc.FILIAL = fi.FILIAL
LEFT JOIN 
    DBO.W_PRODUTOS_CORES WPC 
	   ON WPC.PRODUTO = P.PRODUTO	AND WPC.COR_PRODUTO = P.COR_PRODUTO 

WHERE 

    fi.COD_FILIAL=@CODFILIAL and (epc.DATA_AJUSTE	BETWEEN @DATA1 AND @DATA2) 
	   AND P.QTDE_AJUSTE <> 0

GROUP BY 
    P.PRODUTO,
    P.COR_PRODUTO,
    fi.COD_FILIAL,
    epc.DATA_AJUSTE,
    WPC.CUSTO_REPOSICAO1

UNION 

/*Movto Entradas de Produtos nas Lojas*/
SELECT 
    OPERACAO = MAX('MOVLOJAS'),
    CM_OPERACAO = MAX('LOJ'),
    PRODUTO = P.PRODUTO,
    COR_PRODUTO = ISNULL(RTRIM(LTRIM(P.COR_PRODUTO)), ''),
    CODIGO_FILIAL = FI.COD_FILIAL,
    DATA_VENDA = LE.DATA_SAIDA,
    TAMANHO = 0,
    PRECO_LIQUIDO = ISNULL(P.PRECO1, 0),
    PRECO_CAEDU = ISNULL(PC.PRECO1, 0),
    PRECO_NORMAL = ISNULL(PC2.PRECO1, 0),
    PRECO_ORIGINAL = ISNULL(PC3.PRECO1, 0),
    QTD_VENDA = 0,
    QTD_TROCA = 0,
    QTD_AJUSTE = SUM(ISNULL(P.QTDE_ENTRADA, 0)),
    QTD_TICKET = 0,
    QTD_TICKET_CANCELADA = 0,
    QTD_ITENS_CANCELADOS = 0,
    VLR_VENDA_BRUTO = 0,
    VLR_TROCA_BRUTO = 0,
    VLR_AJUSTE_BRUTO = SUM((ISNULL(P.PRECO1, 0)) * ISNULL(P.QTDE_ENTRADA, 0)),
    VLR_CUSTO_TROCA = 0,
    VLR_DESCTO = 0,
    VLR_TROCA = 0,
    VLR_CUSTO_TOTAL = SUM(ISNULL(P.PRECO1, 0) * ISNULL(P.QTDE_ENTRADA, 0)),
    VLR_DESCTO_TICKET = 0

FROM W_LOJA_ENTRADAS_PRODUTO P

LEFT JOIN 
    FILIAIS FI 
	   ON FI.FILIAL = P.FILIAL	   

LEFT JOIN 
    W_LOJA_ENTRADAS LE 
	   ON LE.ROMANEIO_PRODUTO = P.ROMANEIO_PRODUTO AND LE.FILIAL = P.FILIAL	

LEFT JOIN 
    CAEDU.DBO.PRODUTOS_PRECOS PC WITH (NOLOCK) 
	   ON P.PRODUTO = PC.PRODUTO AND PC.CODIGO_TAB_PRECO = '05'

LEFT JOIN 
    CAEDU.DBO.PRODUTOS_PRECOS PC2 WITH (NOLOCK) 
	   ON P.PRODUTO = PC2.PRODUTO AND PC2.CODIGO_TAB_PRECO = '00'

LEFT JOIN 
    CAEDU.DBO.PRODUTOS_PRECOS PC3 WITH (NOLOCK) 
	   ON P.PRODUTO = PC3.PRODUTO AND PC3.CODIGO_TAB_PRECO = '01'

WHERE 

    FI.COD_FILIAL = @CODFILIAL AND (LE.DATA_SAIDA BETWEEN @DATA1 AND @DATA2)

GROUP BY 
    P.PRODUTO,
    P.COR_PRODUTO,
    FI.COD_FILIAL,
    LE.DATA_SAIDA,
    ISNULL(PC.PRECO1, 0),
    ISNULL(PC2.PRECO1, 0),
    ISNULL(PC3.PRECO1, 0),
    ISNULL(P.PRECO1, 0)

UNION

/*Transferencias*/
SELECT 
    OPERACAO = MAX('FAT_SAIDA'),
    CM_OPERACAO=MAX('FAT'),
    PRODUTO = P.PRODUTO,
    COR_PRODUTO = ISNULL(RTRIM(LTRIM(P.COR_PRODUTO)),0),
    CODIGO_FILIAL = fi.COD_FILIAL,
    DATA_VENDA = F.EMISSAO,
    TAMANHO = 0,
    PRECO_LIQUIDO = ISNULL(P.PRECO, 0),
    PRECO_CAEDU = ISNULL(P.PRECO,0),
    PRECO_NORMAL = ISNULL(P.PRECO,0),
    PRECO_ORIGINAL = ISNULL(P.PRECO,0),
    QTD_VENDA = SUM(ISNULL(P.QTDE, 0)),
    QTD_TROCA = 0,
    QTD_AJUSTE = 0,
    QTD_TICKET = 0,
    QTD_TICKET_CANCELADA = 0,
    QTD_ITENS_CANCELADOS = 0,
    VLR_VENDA_BRUTO = SUM(ISNULL(P.PRECO, 0) * ISNULL(P.QTDE, 0)),
    VLR_TROCA_BRUTO = 0,
    VLR_AJUSTE_BRUTO = 0,
    VLR_CUSTO_TROCA = 0,
    VLR_DESCTO = 0,
    VLR_TROCA = 0,
    VLR_CUSTO_TOTAL = SUM(ISNULL(P.PRECO, 0) * ISNULL(P.QTDE, 0)),
    VLR_DESCTO_TICKET = 0

FROM DBO.FATURAMENTO_PROD P WITH (NOLOCK)

LEFT JOIN 
    FATURAMENTO  F 
	   ON F.NF_SAIDA = P.NF_SAIDA AND F.SERIE_NF = P.SERIE_NF	AND F.FILIAL = P.FILIAL 
LEFT JOIN 
    FILIAIS FI 
	   ON FI.FILIAL = F.FILIAL	   

WHERE 

    FI.COD_FILIAL	= @CODFILIAL  AND (F.EMISSAO BETWEEN @DATA1	AND @DATA2)

GROUP BY 
    P.PRODUTO,
    P.COR_PRODUTO,
    fi.COD_FILIAL,
    f.emissao,
    P.PRECO

UNION

/*Devoluçoes nas Lojas*/
SELECT 
    OPERACAO = MAX('ENT_DEVOL'),
    CM_OPERACAO=MAX('EDV'),
    PRODUTO = P.CODIGO_ITEM,
    COR_PRODUTO = '',
    CODIGO_FILIAL = fi.COD_FILIAL,
    DATA_VENDA = E.EMISSAO,
    TAMANHO = 0,
    PRECO_LIQUIDO = ISNULL(P.PRECO_UNITARIO, 0),
    PRECO_CAEDU = ISNULL(P.PRECO_UNITARIO,0),
    PRECO_NORMAL = ISNULL(P.PRECO_UNITARIO,0),
    PRECO_ORIGINAL = ISNULL(P.PRECO_UNITARIO,0),
    QTD_VENDA = SUM(ISNULL(P.QTDE_ITEM, 0)),
    QTD_TROCA = 0,
    QTD_AJUSTE = 0,
    QTD_TICKET = 0,
    QTD_TICKET_CANCELADA = 0,
    QTD_ITENS_CANCELADOS = 0,
    VLR_VENDA_BRUTO = SUM(ISNULL(P.PRECO_UNITARIO, 0) * ISNULL(P.QTDE_ITEM, 0)),
    VLR_TROCA_BRUTO = 0,
    VLR_AJUSTE_BRUTO = 0,
    VLR_CUSTO_TROCA = 0,
    VLR_DESCTO = 0,
    VLR_TROCA = 0,
    VLR_CUSTO_TOTAL = SUM(ISNULL(P.PRECO_UNITARIO, 0) * ISNULL(P.QTDE_ITEM, 0)),
    VLR_DESCTO_TICKET = 0

FROM dbo.ENTRADAS e
     LEFT JOIN 
	   FILIAIS FI 
		  ON FI.FILIAL = e.FILIAL
	LEFT JOIN 
	   ENTRADAS_ITEM P 
		  ON P.NF_ENTRADA = e.NF_ENTRADA AND P.SERIE_NF_ENTRADA = e.SERIE_NF_ENTRADA AND P.NOME_CLIFOR = e.NOME_CLIFOR

WHERE 

    natureza IN('250.01', '250.02') AND e.COD_TRANSACAO = 'ENTRADAS_102'
    AND FI.COD_FILIAL = @CODFILIAL	AND (E.EMISSAO BETWEEN @DATA1	AND @DATA2)

GROUP BY 
    P.CODIGO_ITEM,
    fi.COD_FILIAL,
    E.emissao,
    P.PRECO_UNITARIO


) UNIAOVENDATROCA

WHERE 

    CODIGO_FILIAL IN (@CODFILIAL)

GROUP BY 
    OPERACAO,
    CM_OPERACAO,
    PRODUTO,
    COR_PRODUTO,
    CODIGO_FILIAL,
    DATA_VENDA,
    TAMANHO,
    PRECO_LIQUIDO,
    PRECO_CAEDU,
    PRECO_NORMAL,
    PRECO_ORIGINAL


END
