ALTER TABLE FORNECEDORES 
	ADD ERP_BLOQUEIO_AUDITORIA BIT NULL CONSTRAINT DF_FORNECEDORES_ERP_BLOQUEIO_AUDITORIA DEFAULT(0);

GO

UPDATE FORNECEDORES SET ERP_BLOQUEIO_AUDITORIA=0 WHERE 1=1
GO


--SELECT FORNECEDOR, ERP_BLOQUEIO_AUDITORIA FROM FORNECEDORES WHERE FORNECEDOR = 'M.G.S.'