IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE NAME = 'LX_CAEDU_EXCLUI_DISTRIBUICAO_WMS_DESMARCAR_GERADO' AND TYPE='P')
BEGIN
	DROP PROCEDURE LX_CAEDU_EXCLUI_DISTRIBUICAO_WMS_DESMARCAR_GERADO
END
GO

CREATE PROCEDURE LX_CAEDU_EXCLUI_DISTRIBUICAO_WMS_DESMARCAR_GERADO
	@DISTRIBUICAO VARCHAR(8)
AS
BEGIN	


	DECLARE @MSG VARCHAR(1000)
	-- Executando a tarefa em transação
	/*BEGIN TRANSACTION -- TRANSAÇÃO ABERTA NO LINX*/

	DECLARE @ERROFAT BIT
	SET @ERROFAT = 0
	
	-- Executando a tarefa em transação

	IF NOT EXISTS(SELECT 1 from CAEDU_RESERVA_AUTOMATICA_PACK_WMS 
								where DISTRIBUICAO = @DISTRIBUICAO)
	BEGIN
		SET @ERROFAT = 1
		SET @MSG = 'A DISTRIBUICAO: '+@DISTRIBUICAO+', NAO EXISTE!!!'
		GOTO ERROFAT
	END
	
	IF EXISTS(SELECT 1
				FROM faturamento_prod
				WHERE caixa IN (SELECT caixa from CAEDU_RESERVA_AUTOMATICA_PACK_WMS 
								where DISTRIBUICAO = @DISTRIBUICAO))
	BEGIN
		SET @ERROFAT = 1
		SET @MSG = 'EXISTEM CAIXAS FATURADAS PARA A DISTRIBUICAO: '+@DISTRIBUICAO+', EXCLUSAO NAO PERMITIDA!!!'
		GOTO ERROFAT
	END

	BEGIN TRY

			DELETE VENDAS 
			WHERE PEDIDO IN (SELECT VENDA FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS WHERE DISTRIBUICAO = @DISTRIBUICAO) 

			--DELETE VENDAS 
			--WHERE PEDIDO IN (SELECT VENDA FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS WHERE DISTRIBUICAO = @DISTRIBUICAO) 


			DELETE FROM FATURAMENTO_CAIXAS
			WHERE CAIXA IN (SELECT CAIXA FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS WHERE DISTRIBUICAO = @DISTRIBUICAO) 

			DELETE FROM CAEDU_RESERVA_AUTOMATICA_WMS WHERE DISTRIBUICAO = @DISTRIBUICAO 

			DELETE
			FROM VENDAS_PROD_EMBALADO
			WHERE CAIXA IN (
			SELECT CAIXA FROM CAEDU_RESERVA_AUTOMATICA_PACK_WMS WHERE DISTRIBUICAO = @DISTRIBUICAO) 

			UPDATE CAEDU_RESERVA_AUTOMATICA_PACK_WMS 
			SET GERADO = 0
			WHERE DISTRIBUICAO = @DISTRIBUICAO

			/*COMMIT TRAN -- TRANSAÇÃO ABERTA NO LINX*/

	END TRY

	BEGIN CATCH

		 SET @MSG = 'ERRO NA TRANSAÇÃO: '+ERROR_MESSAGE()
		 RAISERROR(@MSG, 16, 1)
		 /*ROLLBACK TRAN -- TRANSAÇÃO ABERTA NO LINX*/

	END CATCH

	ERROFAT:
	IF @ERROFAT = 1
	BEGIN
		RAISERROR(@MSG, 16, 1)
	END

END

