SET NOCOUNT ON

DECLARE @TAB_AF TABLE (
griffe VARCHAR(25) NULL,
linha VARCHAR(25) NULL,
GRUPO_PRODUTO VARCHAR(25) NULL,
SUBGRUPO_PRODUTO VARCHAR(25) NULL,
PRODUTO VARCHAR(12) NULL,
COR_PRODUTO  VARCHAR(10) NULL,
CODIGO_BARRA  VARCHAR(25) NULL,
DESC_PRODUTO  VARCHAR(40) NULL,
desc_cor_produto  VARCHAR(40) NULL,
TAMANHO VARCHAR(10),
qtde INT,
PRECO1 NUMERIC(14,2)
)

	DECLARE @FILIAL VARCHAR(25)
	set @FILIAL = 'SP - TUCURUVI'

	; WITH AF (griffe,linha,GRUPO_PRODUTO,SUBGRUPO_PRODUTO,PRODUTO,COR_PRODUTO,
			CODIGO_BARRA,DESC_PRODUTO,desc_cor_produto,TAMANHO,qtde,PRECO1)
	AS (
	SELECT c.griffe, c.linha, c.GRUPO_PRODUTO, c.SUBGRUPO_PRODUTO, C.PRODUTO, b.COR_PRODUTO, B.CODIGO_BARRA, c.DESC_PRODUTO,
				e.desc_cor_produto, RIGHT('00'+convert(varchar,b.TAMANHO),2) as TAMANHO, unpvt.qtde, h.PRECO1
			FROM (SELECT produto, cor_produto,  ES1,ES2,ES3,ES4,ES5,ES6,ES7,ES8,ES9,ES10,ES11,ES12,ES13,ES14,ES15,ES16,ES17,ES18,ES19,ES20
			FROM [CAEDU].[dbo].estoque_produtos
			where FILIAL =@FILIAL
							) p
			UNPIVOT
	(qtde FOR tamanho IN
	(ES1,ES2,ES3,ES4,ES5,ES6,ES7,ES8,ES9,ES10,ES11,ES12,ES13,ES14,ES15,ES16,ES17,ES18,ES19,ES20) )AS unpvt
	LEFT JOIN (
	SELECT  PRODUTO, COR_PRODUTO, TAMANHO, MIN(CODIGO_BARRA) AS CODIGO_BARRA
	FROM [CAEDU].[dbo].PRODUTOS_BARRA
	GROUP BY PRODUTO, COR_PRODUTO, TAMANHO
	) B ON B.PRODUTO = unpvt.PRODUTO AND B.COR_PRODUTO = unpvt.COR_PRODUTO AND B.TAMANHO = substring(unpvt.tamanho,3,2)
	LEFT join [CAEDU].[dbo].PRODUTOS as c on b.PRODUTO=c.PRODUTO
	LEFT join [CAEDU].[dbo].PRODUTO_CORES as e on c.PRODUTO=e.PRODUTO and unpvt.COR_PRODUTO=e.COR_PRODUTO
	LEFT join [CAEDU].[dbo].produtos_precos as H on c.PRODUTO=h.PRODUTO where h.CODIGO_TAB_PRECO ='00'
	)
	
INSERT INTO @TAB_AF 
SELECT griffe,linha,GRUPO_PRODUTO,SUBGRUPO_PRODUTO,PRODUTO,COR_PRODUTO,
			CODIGO_BARRA,DESC_PRODUTO,desc_cor_produto,TAMANHO,qtde,PRECO1
FROM AF

--SELECT * FROM @TAB_AF

DECLARE @PRODUTOS_CORES TABLE (
ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
PRODUTO VARCHAR(12) NULL,
COR_PRODUTO VARCHAR(10) NULL
)

INSERT INTO @PRODUTOS_CORES 
SELECT PRODUTO, COR_PRODUTO
FROM @TAB_AF
GROUP BY PRODUTO, COR_PRODUTO
ORDER BY PRODUTO, COR_PRODUTO

DECLARE @I INT, @TOT INT, @TOTAL_AF INT, @TOTAL_ESTOQUE INT

DECLARE @PRODUTO VARCHAR(12), @COR_PRODUTO  VARCHAR(10)

SELECT @I = MIN(ID), @TOT = MAX(ID) 
FROM @PRODUTOS_CORES

DECLARE @TAB_ERRO TABLE
(ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
PRODUTO VARCHAR(12) NULL,
COR_PRODUTO VARCHAR(10) NULL,
TOTAL_AF INT, 
TOTAL_ESTOQUE INT
)

PRINT @TOT

WHILE @I <= @TOT
BEGIN

	PRINT @I

	SELECT @PRODUTO = PRODUTO, @COR_PRODUTO = COR_PRODUTO
	FROM @PRODUTOS_CORES
	WHERE ID = @I

	SELECT @TOTAL_AF = SUM(QTDE)
	FROM @TAB_AF
	WHERE PRODUTO = @PRODUTO AND COR_PRODUTO=@COR_PRODUTO

	SELECT @TOTAL_ESTOQUE = SUM(ESTOQUE)
	FROM ESTOQUE_PRODUTOS
	WHERE PRODUTO = @PRODUTO AND COR_PRODUTO=@COR_PRODUTO AND FILIAL=@FILIAL

	IF @TOTAL_ESTOQUE <> @TOTAL_AF
	BEGIN
		INSERT INTO @TAB_ERRO (PRODUTO, COR_PRODUTO, TOTAL_AF, TOTAL_ESTOQUE) VALUES (@PRODUTO, @COR_PRODUTO, @TOTAL_AF, @TOTAL_ESTOQUE)
	END

	SET @I += 1
END
SELECT * FROM @TAB_ERRO

SET NOCOUNT OFF
