USE [CAEDU]
GO
/****** Object:  StoredProcedure [dbo].[CAE_ATUALIZA_PRODUTOS_FATOR_P]    Script Date: 16/04/2026 09:36:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[CAE_ATUALIZA_PRODUTOS_FATOR_P]

AS
BEGIN
/****
* 	COORDENADOR.................: LUCIANO REIS
*	ANALISTA RESPONSAVEL........: PAULO EDUARDO DEVIDE
*	DATA DA CRIACAO.............: 07/05/2013
*	DATA DA ULTIMA MODIFICACAO..: 07/05/2013
*   ATUALIZACAO DA TABELA dbo.CAE_PRODUTOS_FATOR_P
*   ALTERAÇÃO...................: 21/05/2024
*   SETAR CAMPO UNOUS_ALOCAR = 1 E INCLUSAO DA COLUNA UNOUS_NIVEL
*   ALTERADO POR................: PAULO EDUARDO DEVIDE
*/

DECLARE @ULTIMO INT, @I INT, @TOTREG INT, @NREF INT
DECLARE @GRIFFE VARCHAR(25),@LINHA VARCHAR(25)
DECLARE @GRUPO_PRODUTO VARCHAR(25),@SUBGRUPO_PRODUTO VARCHAR(25)
DECLARE @CODIGO_FATOR CHAR(6), @REFERENCIA CHAR(1)
DECLARE @VALOR1 NUMERIC(14,2), @VALOR2 NUMERIC(14,2)

SELECT @ULTIMO = CAST(MAX(CODIGO_FATOR) AS INT)
FROM dbo.CAE_PRODUTOS_FATOR_P

declare @hierarquia table (
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
GRIFFE VARCHAR(25),
LINHA VARCHAR(25),
GRUPO_PRODUTO VARCHAR(25),
SUBGRUPO_PRODUTO VARCHAR(25)
)

INSERT INTO @hierarquia (GRIFFE, LINHA, GRUPO_PRODUTO, SUBGRUPO_PRODUTO)

select 
P.GRIFFE,P.LINHA,P.GRUPO_PRODUTO,P.SUBGRUPO_PRODUTO 
FROM PRODUTOS P
LEFT JOIN  dbo.CAE_PRODUTOS_FATOR_P AS FP 
			ON FP.GRIFFE=P.GRIFFE 
				AND FP.LINHA=P.LINHA 
				AND FP.GRUPO_PRODUTO=P.GRUPO_PRODUTO 
				AND FP.SUBGRUPO_PRODUTO=P.SUBGRUPO_PRODUTO
WHERE FP.GRIFFE IS NULL
GROUP BY P.GRIFFE,P.LINHA,P.GRUPO_PRODUTO,P.SUBGRUPO_PRODUTO 

--select * from @hierarquia

SET @I=1

SELECT @TOTREG=COUNT(*) 
FROM @hierarquia

WHILE @I <= @TOTREG
BEGIN

	SELECT @CODIGO_FATOR=RIGHT('000000'+CAST(ID + @ULTIMO AS VARCHAR),6),
		@GRIFFE=GRIFFE,@LINHA=LINHA,@GRUPO_PRODUTO=GRUPO_PRODUTO,
		@SUBGRUPO_PRODUTO=SUBGRUPO_PRODUTO  
	FROM  @hierarquia 
	WHERE ID = @I
	
	SET @NREF=1
	WHILE @NREF <= 4
	BEGIN
		SET @REFERENCIA = CAST(@NREF AS CHAR(1))

		SET @VALOR1 = 
			CASE @NREF
				WHEN 1 THEN 0 
				WHEN 2 THEN 1
				WHEN 3 THEN 2
				WHEN 4 THEN 3
			END		

		SET @VALOR2 = 
			CASE @NREF
				WHEN 1 THEN 0.99 
				WHEN 2 THEN 1.99
				WHEN 3 THEN 2.99
				WHEN 4 THEN 1000000
			END		
		
		/* FATOR P DEFAULT PARA UNOUS_NIVEL */
		INSERT INTO dbo.CAE_PRODUTOS_FATOR_P
		(CODIGO_FATOR, REFERENCIA, GRIFFE, LINHA, GRUPO_PRODUTO, SUBGRUPO_PRODUTO, VALOR1, VALOR2, UNOUS_ALOCAR, UNOUS_NIVEL )
		VALUES 
		(@CODIGO_FATOR, @REFERENCIA, @GRIFFE, @LINHA, @GRUPO_PRODUTO, @SUBGRUPO_PRODUTO, @VALOR1, @VALOR2, 1,'FATOR_P')
		
		SET @NREF = @NREF + 1
	END
	
	
	SET @I=@I+1
END

END

