select A.PRODUTO,A.COR_PRODUTO,rtrim(ltrim(A.FILIAL)) as FILIAL,
A.DISPONIVEL, A.ESTOQUE, A.EMBALADO, A.TRANSITO,
A.TIPO_PRODUTO, A.DESC_PRODUTO, A.DESC_COR_PRODUTO,
A.GRIFFE, A.LINHA, A.GRUPO_PRODUTO, A.SUBGRUPO_PRODUTO,
A.COLECAO, A.GRADE, A.FABRICANTE, A.REFER_FABRICANTE
from W_ESTOQUE_PRODUTOS_00 A 
where a.ESTOQUE != 0


select COUNT(*)
from ESTOQUE_PRODUTOS a
where a.ESTOQUE != 0