select	Produto,	
		Classif_fiscal,	
		Tipo_produto,	
		Desc_produto,	
		Griffe,	
		Linha,	
		Grupo_produto,	
		Subgrupo_produto,
		LTRIM(RTRIM(GRIFFE))+LTRIM(RTRIM(LINHA))+LTRIM(RTRIM(GRUPO_PRODUTO))+LTRIM(RTRIM(SUBGRUPO_PRODUTO))+LTRIM(RTRIM(DESC_PRODUTO)) AS CHAVE,
		Colecao,	
		Grade,
		Desc_prod_nf,
		Unidade,
		Peso,
		Revenda,
		Refer_fabricante,
		Sortimento_cor,
		Fabricante,
		Sortimento_tamanho,
		Varia_preco_cor,
		Varia_preco_tam,
		Ponteiro_preco_tam,
		Varia_custo_cor,
		Pertence_a_conjunto,
		Tribut_icms,
		Tribut_origem,
		Varia_custo_tam,
		Custo_reposicao1

from produtos where obs like 'PRODUTO CHIK%' AND DATA_CADASTRAMENTO = '20190531'