select * from caedu_reserva_automatica where data >= '20190927'

select * from caedu_reserva_automatica where pedido = '228473-1'

update caedu_reserva_automatica 
set data = convert(varchar, data, 112)
where data >= '20190927'

SELECT 0 AS EXCLUI, CAEDU_RESERVA_AUTOMATICA.PEDIDO, CAEDU_RESERVA_AUTOMATICA.PRODUTO, CAEDU_RESERVA_AUTOMATICA.COR_PRODUTO, 
CAEDU_RESERVA_AUTOMATICA.FILIAL, CAEDU_RESERVA_AUTOMATICA.FILIAL_ORIGEM, CAEDU_RESERVA_AUTOMATICA.QTDE_TOTAL, CAEDU_RESERVA_AUTOMATICA.Q1, 
CAEDU_RESERVA_AUTOMATICA.Q2, CAEDU_RESERVA_AUTOMATICA.Q3, CAEDU_RESERVA_AUTOMATICA.Q4, CAEDU_RESERVA_AUTOMATICA.Q5, CAEDU_RESERVA_AUTOMATICA.Q6, 
CAEDU_RESERVA_AUTOMATICA.Q7, CAEDU_RESERVA_AUTOMATICA.Q8, CAEDU_RESERVA_AUTOMATICA.Q9, CAEDU_RESERVA_AUTOMATICA.Q10, CAEDU_RESERVA_AUTOMATICA.Q11, 
CAEDU_RESERVA_AUTOMATICA.Q12, CAEDU_RESERVA_AUTOMATICA.Q13, CAEDU_RESERVA_AUTOMATICA.Q14, CAEDU_RESERVA_AUTOMATICA.Q15, CAEDU_RESERVA_AUTOMATICA.Q16, 
0 AS Q17, 0 AS Q18, 0 AS Q19, 0 AS Q20, 0 AS Q21, 0 AS Q22, 0 AS Q23, 0 AS Q24, 0 AS Q25, 0 AS Q26, 0 AS Q27, 0 AS Q28, 0 AS Q29, 0 AS Q30, 0 AS Q31, 
0 AS Q32, 0 AS Q33, 0 AS Q34, 0 AS Q35, 0 AS Q36, 0 AS Q37, 0 AS Q38, 0 AS Q39, 0 AS Q40, 0 AS Q41, 0 AS Q42, 0 AS Q43, 0 AS Q44, 0 AS Q45, 0 AS Q46, 
0 AS Q47, 0 AS Q48, CAEDU_RESERVA_AUTOMATICA.DATA, CAEDU_RESERVA_AUTOMATICA.QTDE_PACK, CAEDU_RESERVA_AUTOMATICA.CAIXA, CAEDU_RESERVA_AUTOMATICA.VENDA, 
CAEDU_RESERVA_AUTOMATICA.ROMANEIO, CAEDU_RESERVA_AUTOMATICA.GERADO, ISNULL(COMPRAS.ERP_MANUAL,0) AS ERP_MANUAL 
FROM CAEDU_RESERVA_AUTOMATICA  
JOIN COMPRAS ON CAEDU_RESERVA_AUTOMATICA.PEDIDO = COMPRAS.PEDIDO 
where data >= '20190927'
ORDER BY  CAEDU_RESERVA_AUTOMATICA.PEDIDO, CAEDU_RESERVA_AUTOMATICA.PRODUTO, CAEDU_RESERVA_AUTOMATICA.COR_PRODUTO

insert into compras 
select * from prod.caedu.dbo.compras where pedido = '228473-1'

insert into compras 
([PEDIDO], [FORNECEDOR], [FILIAL_A_ENTREGAR], [FILIAL_COBRANCA], [FILIAL_A_FATURAR], [CONDICAO_PGTO], [TRANSPORTADORA], [MOEDA], [COD_TRANSACAO], [EMISSAO], [CADASTRAMENTO], [APROVADO_POR], [PEDIDO_FORNECEDOR], [DESCONTO], [ENCARGO], [VALOR_IPI], [FRETE_A_PAGAR], [TOT_QTDE_ORIGINAL], [TOT_QTDE_ENTREGAR], [TOT_VALOR_ORIGINAL], [TOT_VALOR_ENTREGAR], [CTRL_MULT_ENTREGAS], [TABELA_FILHA], [ENTREGA_ACEITAVEL], [OBS], [REQUERIDO_POR], [TIPO_COMPRA], [PROGRAMACAO], [STATUS_APROVACAO], [DATA_APROVACAO], [ORIGEM_DA_COMPRA], [STATUS_COMPRA], [PEDIDO_VENDA], [COMPRIMENTO_DE_ROLOS], [TOT_VALOR_DESPESA], [MARCA_VOLUMES], [APROVADOR_POR],  [RATEIO_CENTRO_CUSTO], [RATEIO_FILIAL], [DATA_FATURAMENTO_RELATIVO], [NATUREZA_ENTRADA], [NATUREZA], [ID_ASSINATURA_DOCUMENTO], [DATA_PARA_TRANSFERENCIA], [PEDIDO_COMPRA_ORIGEM], [CAEDU_DATA_ENTREGA_ORIGINAL], [LX_STATUS_COMPRA], [QUANTIDADE_AGENDAMENTO], [QUANTIDADE_CANCELAMENTO], [CAEDU_DATA_OTB], [STATUS_CQ], [MOTIVO_CQ], [ERP_CONFERENCIA_PACKS], [ERP_CAB_COD_CABIDE], [ERP_CAB_CD_ENTREGA], [ERP_CAB_ENCABIDADO], [ERP_CAB_STATUS], [ERP_CAB_LOCALIZACAO], [ERP_CAB_QTDPECAS], [ERP_CAB_TIPO_PEDIDO], [ERP_CAB_DATA_ENVIO], [ERP_FOLLOW_UP_MARGEM], [OBJETO_ID], [ERP_CUPS_TIPO_PEDIDO], [ERP_CUPS_SEGMENTO], [ERP_CUPS_DATA_ACORDADA], [ERP_CUPS_PECA_MOSTRUARIO], [ERP_CUPS_EMBARQUE_ATUAL], [ERP_CUPS_EMBARQUE_REAL], [ERP_CUPS_CONTRATO], [ERP_CUPS_CHEGADA_PORTO], [ERP_CUPS_CHEGADA_CD], [ERP_CUPS_PROCESSO_CCF_CCA], [ERP_CUPS_EMBARQUE_LIBERADO], [ERP_CUPS_SEQ_PRODUTO], [ERP_CUPS_INCOTERM], [ERP_CUPS_ID_CONTRATO], [ERP_IMP_NUM_FATURA], [ERP_IMP_COD_PROCESSO], [ERP_IMP_TIPO_IMPORTACAO], [ERP_PERCENT_VERBAS], [BLOQ_EMBARQUE], [ERP_EBS_CTRL_PAGTO_PARCELA], [ERP_EBS_VLR_SISCOMEX], [ERP_EBS_VLR_CUSTO_FOB_DI], [ERP_EBS_VLR_TAXA_DI], [ERP_EBS_VLR_TAXA_BL], [ERP_IMPORTADO], [ERP_MOEDA], [ERP_TOTAL_QTD_DISTRIB], [ERP_PERCENT_DISTRIB], [ERP_TOTAL_CAIXAS_ORIGINAL], [ERP_PACK_RESTO], [CTB_TIPO_OPERACAO], [DESC_TIPO_OPERACAO], [GERAR_WF], [CHAVE_PROCESSO_SE], [ERP_DISTRIBUICAO], [ERP_MANUAL], [ERP_LIBERADO_CQ], [ERP_FATURADO], [ERP_CAB_OPCAO], [ERP_CAB_COD_BOLACHA], [ERP_UNOUS_DATA_ENVIO])

select [PEDIDO], [FORNECEDOR], [FILIAL_A_ENTREGAR], [FILIAL_COBRANCA], [FILIAL_A_FATURAR], [CONDICAO_PGTO], [TRANSPORTADORA], 
[MOEDA], [COD_TRANSACAO], [EMISSAO], [CADASTRAMENTO], [APROVADO_POR], [PEDIDO_FORNECEDOR], [DESCONTO], [ENCARGO], [VALOR_IPI], 
[FRETE_A_PAGAR], [TOT_QTDE_ORIGINAL], [TOT_QTDE_ENTREGAR], [TOT_VALOR_ORIGINAL], [TOT_VALOR_ENTREGAR], [CTRL_MULT_ENTREGAS], 
[TABELA_FILHA], [ENTREGA_ACEITAVEL], [OBS], [REQUERIDO_POR], [TIPO_COMPRA], [PROGRAMACAO], [STATUS_APROVACAO], [DATA_APROVACAO], 
[ORIGEM_DA_COMPRA], [STATUS_COMPRA], [PEDIDO_VENDA], [COMPRIMENTO_DE_ROLOS], [TOT_VALOR_DESPESA], [MARCA_VOLUMES], [APROVADOR_POR], 
 [RATEIO_CENTRO_CUSTO], [RATEIO_FILIAL], [DATA_FATURAMENTO_RELATIVO], [NATUREZA_ENTRADA], [NATUREZA], 
[ID_ASSINATURA_DOCUMENTO], [DATA_PARA_TRANSFERENCIA], [PEDIDO_COMPRA_ORIGEM], [CAEDU_DATA_ENTREGA_ORIGINAL], [LX_STATUS_COMPRA], 
[QUANTIDADE_AGENDAMENTO], [QUANTIDADE_CANCELAMENTO], [CAEDU_DATA_OTB], [STATUS_CQ], [MOTIVO_CQ], [ERP_CONFERENCIA_PACKS], [ERP_CAB_COD_CABIDE], 
[ERP_CAB_CD_ENTREGA], [ERP_CAB_ENCABIDADO], [ERP_CAB_STATUS], [ERP_CAB_LOCALIZACAO], [ERP_CAB_QTDPECAS], [ERP_CAB_TIPO_PEDIDO], [ERP_CAB_DATA_ENVIO], 
[ERP_FOLLOW_UP_MARGEM], [OBJETO_ID], [ERP_CUPS_TIPO_PEDIDO], [ERP_CUPS_SEGMENTO], [ERP_CUPS_DATA_ACORDADA], [ERP_CUPS_PECA_MOSTRUARIO], 
[ERP_CUPS_EMBARQUE_ATUAL], [ERP_CUPS_EMBARQUE_REAL], [ERP_CUPS_CONTRATO], [ERP_CUPS_CHEGADA_PORTO], [ERP_CUPS_CHEGADA_CD], 
[ERP_CUPS_PROCESSO_CCF_CCA], [ERP_CUPS_EMBARQUE_LIBERADO], [ERP_CUPS_SEQ_PRODUTO], [ERP_CUPS_INCOTERM], [ERP_CUPS_ID_CONTRATO], 
[ERP_IMP_NUM_FATURA], [ERP_IMP_COD_PROCESSO], [ERP_IMP_TIPO_IMPORTACAO], [ERP_PERCENT_VERBAS], [BLOQ_EMBARQUE], [ERP_EBS_CTRL_PAGTO_PARCELA], 
[ERP_EBS_VLR_SISCOMEX], [ERP_EBS_VLR_CUSTO_FOB_DI], [ERP_EBS_VLR_TAXA_DI], [ERP_EBS_VLR_TAXA_BL], [ERP_IMPORTADO], [ERP_MOEDA], [ERP_TOTAL_QTD_DISTRIB], 
[ERP_PERCENT_DISTRIB], [ERP_TOTAL_CAIXAS_ORIGINAL], [ERP_PACK_RESTO], [CTB_TIPO_OPERACAO], [DESC_TIPO_OPERACAO], [GERAR_WF], 
[CHAVE_PROCESSO_SE], [ERP_DISTRIBUICAO], [ERP_MANUAL], [ERP_LIBERADO_CQ], [ERP_FATURADO], [ERP_CAB_OPCAO], [ERP_CAB_COD_BOLACHA], 
[ERP_UNOUS_DATA_ENVIO]
from prod.caedu.dbo.compras where pedido = '228473-1'




