DECLARE @TABNOTAS TABLE (ID INT IDENTITY(1,1),
NF_ENTRADA CHAR(15),
NOME_CLIFOR VARCHAR(25),
SERIE_NF_ENTRADA VARCHAR(6),
FILIAL_ENTRADA VARCHAR(25),
TRANSITO_BAIXADO BIT)

declare @id int, @tot int

DECLARE	@NF_ENTRADA CHAR(15), 
		@NOME_CLIFOR VARCHAR(25), 
		@SERIE_NF_ENTRADA VARCHAR(6), 
		@FILIAL_ENTRADA VARCHAR(25)

DECLARE @LISTAPROD VARCHAR(MAX)
DECLARE @CODIGO_BARRA VARCHAR(25), @QTD VARCHAR(6), @TAMANHO INT
DECLARE @TAB_SKU TABLE (ID INT IDENTITY(1,1), PRODUTO CHAR(12), CODIGO_BARRA VARCHAR(25),QTD INT)

SET @NF_ENTRADA = '000256444'

INSERT INTO @TAB_SKU (PRODUTO,CODIGO_BARRA, QTD)
SELECT 
	unp.PRODUTO, ISNULL(CODIGO_BARRA,'') AS CODIGO_BARRA, QTD
	FROM (
	select A.PRODUTO, A.FILIAL,
	P.DESC_PRODUTO, A.COR_PRODUTO, pc.DESC_COR_PRODUTO,
	B.NF_ENTRADA, B.SERIE_NF_ENTRADA,
	ISNULL(EN_1,0) EN1, 
	ISNULL(EN_2,0) EN2, 
	ISNULL(EN_3,0) EN3, 
	ISNULL(EN_4,0) EN4, 
	ISNULL(EN_5,0) EN5, 
	ISNULL(EN_6,0) EN6, 
	ISNULL(EN_7,0) EN7, 
	ISNULL(EN_8,0) EN8, 
	ISNULL(EN_9,0) EN9, 
	ISNULL(EN_10,0) EN10, 
	ISNULL(EN_11,0) EN11, 
	ISNULL(EN_12,0) EN12, 
	ISNULL(EN_13,0) EN13, 
	ISNULL(EN_14,0) EN14, 
	ISNULL(EN_15,0) EN15, 
	ISNULL(EN_16,0) EN16
	from ESTOQUE_PROD1_ENT A
	INNER JOIN ESTOQUE_PROD_ENT B ON B.ROMANEIO_PRODUTO = A.ROMANEIO_PRODUTO AND B.FILIAL = A.FILIAL
	inner join PRODUTOS p on p.PRODUTO = A.PRODUTO
	inner join PRODUTO_CORES pc on pc.PRODUTO = A.PRODUTO and pc.COR_PRODUTO = A.COR_PRODUTO
	where B.NF_ENTRADA = @NF_ENTRADA AND B.NOME_CLIFOR = 'KOMPORT' AND B.filial = 'VENDA ATACADO SC'
	) as p
	unpivot
	(qtd for POSICAO IN (EN1, EN2, EN3, EN4, EN5, EN6, EN7, EN8, EN9, EN10, EN11, EN12, EN13, EN14, EN15, EN16)
	) AS unp
	LEFT JOIN
		PRODUTOS_BARRA b 
			on b.PRODUTO = unp.PRODUTO and b.COR_PRODUTO = unp.COR_PRODUTO and b.TAMANHO = CAST(SUBSTRING(POSICAO,3,2) AS INT) 
	WHERE QTD>0
	ORDER BY unp.PRODUTO, unp.COR_PRODUTO

--SELECT * FROM @TAB_SKU
DECLARE @TABPRO TABLE (ID INT IDENTITY(1,1), PRODUTO CHAR(12))
INSERT INTO @TABPRO (PRODUTO)
SELECT PRODUTO FROM @TAB_SKU
GROUP BY PRODUTO

--SELECT * FROM @TABPRO
DECLARE @IPRO INT, @TOTPRO INT, @PRODUTO CHAR(12)
DECLARE @I INT, @TOT2 INT


SELECT @IPRO = MIN(ID), @TOTPRO = MAX(ID)
FROM @TABPRO

WHILE @IPRO <= @TOTPRO
BEGIN
	
	SELECT @PRODUTO = PRODUTO 
	FROM @TABPRO 
	WHERE ID = @IPRO
	
	SET @LISTAPROD = ''
	SELECT @I = MIN(ID), @TOT2 = MAX(ID)
	FROM @TAB_SKU
	WHERE PRODUTO = @PRODUTO

	WHILE @I <= @TOT2
	BEGIN
		SELECT @CODIGO_BARRA = CODIGO_BARRA, @QTD = CONVERT(VARCHAR,QTD)
		FROM @TAB_SKU WHERE ID = @I

		SET	@LISTAPROD = @LISTAPROD + RTRIM(LTRIM(@CODIGO_BARRA)) + ';' + @QTD + '|'

		SET @I = @I + 1
	END

	SET @TAMANHO = LEN(@LISTAPROD)
	IF @TAMANHO > 0
	BEGIN
		SET @LISTAPROD = LEFT(@LISTAPROD, @TAMANHO-1)
		--SELECT @LISTAPROD
		PRINT @PRODUTO

		EXEC CGP_MOVIMENTA_ESTOQUE_FILIAIS 
			'VENDA ATACADO SC', 
			'CD NAVEGANTES', 
			@LISTAPROD, 
			@TRANSFERIDO=0
	END

	SET @IPRO = @IPRO + 1
END