/** trocar produtos entre pedidos **/

--select * from compras_produto where pedido = '172486'
--select * from compras_produto where pedido = '169838B'

--select * from CAEDU_COMPRAS_PRODUTOS_PACKS where pedido = '172486'
--select * from CAEDU_COMPRAS_PRODUTOS_PACKS where pedido = '169838B'

--select * from CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL where pedido = '172486'
--select * from CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL where pedido = '169838B'

ABF 406        	172473	60010089
ABF 408        	172475	60010087
select * from compras_produto where pedido = '172473'
select * from compras_produto where pedido = '172475'

DECLARE @PEDIDO1 VARCHAR(8) = '172486'  
DECLARE @PRODUTO1 VARCHAR(12) = 'B5010042'
DECLARE @COR1 VARCHAR(5) = '00121' --VINHO  
DECLARE @DESCRICAO_COR1 VARCHAR(25) = 'VINHO'                                 

DECLARE @PEDIDO2 VARCHAR(8) = '169838B' 
DECLARE @PRODUTO2 VARCHAR(12) = '51041902'
DECLARE @COR2 VARCHAR(5) = '00006' --CINZA CLARO                             
DECLARE @DESCRICAO_COR2 VARCHAR(25) = 'CINZA CLARO'                                 

UPDATE COMPRAS_PRODUTO 
SET PRODUTO = @PRODUTO2, COR_PRODUTO=@COR2
WHERE PEDIDO = @PEDIDO1

UPDATE COMPRAS_PRODUTO 
SET PRODUTO = @PRODUTO1, COR_PRODUTO=@COR1
WHERE PEDIDO = @PEDIDO2

UPDATE CAEDU_COMPRAS_PRODUTOS_PACKS SET
PRODUTO = @PRODUTO2,
COR_PRODUTO = @COR2,
DESC_COR_PRODUTO = @DESCRICAO_COR2
WHERE PEDIDO = @PEDIDO1
 
UPDATE CAEDU_COMPRAS_PRODUTOS_PACKS SET
PRODUTO = @PRODUTO1,
COR_PRODUTO = @COR1,
DESC_COR_PRODUTO = @DESCRICAO_COR1
WHERE PEDIDO = @PEDIDO2

UPDATE CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL SET
PRODUTO = @PRODUTO2
WHERE PEDIDO = @PEDIDO1
 
UPDATE CAEDU_COMPRAS_PRODUTOS_PACKS_TOTAL SET
PRODUTO = @PRODUTO1
WHERE PEDIDO = @PEDIDO2

     