--EXEC LX_CAEDU_SELECIONA_GRUPO_MERCADORIA @GRIFFE = 'ACESSORIOS', @LINHA = 'PROMOCIONAL', @GRUPO_PRODUTO = 'BOLSA', @SUBGRUPO_PRODUTO = 'BOLSA CLASSICO/CONTEMP'
--select * from PARAMETROS where parametro like 'ROWSOURCE_GRUPOMERCADORIA%'

ALTER PROCEDURE LX_CAEDU_SELECIONA_GRUPO_MERCADORIA 
(
@GRIFFE VARCHAR(25) = NULL,
@LINHA VARCHAR(25) = NULL,
@GRUPO_PRODUTO VARCHAR(25) = NULL,
@SUBGRUPO_PRODUTO VARCHAR(25) = NULL
)
AS
BEGIN 


	IF LTRIM(ISNULL(@GRIFFE,'')) = ''
	BEGIN
		SET @GRIFFE = NULL
	END

	IF LTRIM(ISNULL(@LINHA,'')) = ''
	BEGIN
		SET @LINHA = NULL
	END

	IF LTRIM(ISNULL(@GRUPO_PRODUTO,'')) = ''
	BEGIN
		SET @GRUPO_PRODUTO = NULL
	END

	IF LTRIM(ISNULL(@SUBGRUPO_PRODUTO,'')) = ''
	BEGIN
		SET @SUBGRUPO_PRODUTO = NULL
	END

	IF ISNULL(@LINHA,'') = 'PROMOCIONAL'
	BEGIN
		SET @GRIFFE = NULL
		SET @LINHA = NULL
		SET @GRUPO_PRODUTO = NULL
		SET @SUBGRUPO_PRODUTO = NULL
	END

	
	SELECT DISTINCT 
/*
		CODIGO_FATOR, 
		GRIFFE, 
		LINHA, 
		GRUPO_PRODUTO, 
		SUBGRUPO_PRODUTO, */
		ISNULL(ERP_GRUPO_MERCADORIA,'') AS ERP_GRUPO_MERCADORIA
	FROM CAE_PRODUTOS_FATOR_P
	WHERE 
		GRIFFE = ISNULL(@GRIFFE, GRIFFE)
		AND LINHA = ISNULL(@LINHA, LINHA)
		AND GRUPO_PRODUTO = ISNULL(@GRUPO_PRODUTO, GRUPO_PRODUTO)
		AND SUBGRUPO_PRODUTO = ISNULL(@SUBGRUPO_PRODUTO, SUBGRUPO_PRODUTO)
END

