SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO	
-- ==============================================
-- Author:		PAULO DEVIDE
-- Create date: 2022-03-08
-- Description:	NÃO PERMITIR A INSERÇÃO DE LETRA
--				NO 2º CARACTER DO CODIGO DO GRUPO
-- ==============================================
CREATE TRIGGER DBO.LX_CGP_PRODUTOS_GRUPO 
   ON  DBO.PRODUTOS_GRUPO 
   FOR INSERT,UPDATE
AS 
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @CODIGO_GRUPO CHAR(2), @PART1 CHAR(1), @PART2 CHAR(1)
	SELECT @CODIGO_GRUPO = CODIGO_GRUPO
	FROM INSERTED

	SET @PART1 = SUBSTRING(@CODIGO_GRUPO,1,1)
	SET @PART2 = SUBSTRING(@CODIGO_GRUPO,2,1)

	IF ISNUMERIC(@PART2)=0
	BEGIN
		RAISERROR('Não é permitido utilizar letra na segunda posição do código',16,1)
		ROLLBACK TRANSACTION 
		RETURN 
	END

END
GO
