SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO	
-- ===============================================
-- Author:		PAULO DEVIDE
-- Create date: 2022-03-08
-- Description:	NÃO PERMITIR A INSERÇÃO DE LETRA
--				EM NENHUM CARACTER DO CODIGO DO 
--				SUBGRUPO E VERIFICAR SE TODAS AS
--				POSIÇÕES DO SEQUENCIAL SÃO NUMERO
--				E SE O TAMANHO DO SEQUENCIAL TEM 4
-- ===============================================
CREATE TRIGGER DBO.LX_CGP_PRODUTOS_SUBGRUPO 
   ON  DBO.PRODUTOS_SUBGRUPO 
   FOR INSERT,UPDATE
AS 
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @CODIGO_SUBGRUPO CHAR(2), @PART1 CHAR(1), @PART2 CHAR(1)
	DECLARE @PARTSEQ1 CHAR(1), @PARTSEQ2 CHAR(1), @PARTSEQ3 CHAR(1), @PARTSEQ4 CHAR(1)
	DECLARE @TAMANHO_SEQ INT

	SELECT	@CODIGO_SUBGRUPO = CODIGO_SUBGRUPO,
			@PARTSEQ1 = SUBSTRING(CODIGO_SEQUENCIAL,1,1),
			@PARTSEQ2 = SUBSTRING(CODIGO_SEQUENCIAL,2,1),
			@PARTSEQ3 = SUBSTRING(CODIGO_SEQUENCIAL,3,1),
			@PARTSEQ4 = SUBSTRING(CODIGO_SEQUENCIAL,4,1), 
			@TAMANHO_SEQ = LEN(RTRIM(LTRIM(CODIGO_SEQUENCIAL)))
	FROM INSERTED

	SET @PART1 = SUBSTRING(@CODIGO_SUBGRUPO,1,1)
	SET @PART2 = SUBSTRING(@CODIGO_SUBGRUPO,2,1)

	IF @TAMANHO_SEQ<4
	BEGIN
		RAISERROR('SEQUENCIAL OBRIGATÓRIO CONTER 4 DIGITOS (0000 ATÉ 9999) !!!',16,1)
		ROLLBACK TRANSACTION 
		RETURN 
	END

	IF (ISNUMERIC(@PART1)=0) OR (ISNUMERIC(@PART2)=0) 
	BEGIN
		RAISERROR('Não é permitido utilizar letra no codigo do subgrupo!!!',16,1)
		ROLLBACK TRANSACTION 
		RETURN 
	END

	IF (ISNUMERIC(@PARTSEQ1)=0) OR (ISNUMERIC(@PARTSEQ2)=0) 
		OR (ISNUMERIC(@PARTSEQ3)=0) OR (ISNUMERIC(@PARTSEQ4)=0) 
	BEGIN
		RAISERROR('Obrigatório usar número (0 - 9) em todas as posições do sequencial!!!',16,1)
		ROLLBACK TRANSACTION 
		RETURN 
	END


END
GO
