USE [CAEDU]
GO

/****** Object:  View [dbo].[W_ARB_FILTRO]    Script Date: 16/11/2023 13:40:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE OR ALTER VIEW [dbo].[W_ARB_FILTRO]
AS
SELECT  DISTINCT GRIFFE, LINHA, GRUPO_PRODUTO FROM PRODUTOS
GO


