
CREATE TABLE CAEDU_REPORT_PRODUTOS_SANEAMENTO_FISCAL (
ID_REPORT UNIQUEIDENTIFIER NOT NULL, 
ID_ROW INT NOT NULL,
Produto char(12) NULL, 
Desc_produto varchar(40) NULL, 
Grupo_produto varchar(25) NULL, 
Subgrupo_produto varchar(25) NULL, 
Griffe varchar(25) NULL, 
Linha varchar(25) NULL, 
Fabricante varchar(25) NULL, 
Classif_fiscal char(10) NULL, 
Tribut_origem char(3) NULL, 
Indicador_cfop tinyint NULL, 
Descricao_indicador_cfop varchar(40) NULL, 
Item_Sped char(5) NULL, 
Id_excecao_grupo int NULL, 
Desc_excecao_grupo varchar(40) NULL, 
Data_cadastramento datetime NULL, 
Filial1 varchar(25) NULL, 
Caracteristica_contabil1 tinyint NULL, 
Descricao_caracteristica_contabil1 varchar(40) NULL, 
Tributacao_Origem1 char(3) NULL, 
Descricao_Tribut_Origem1 varchar(150) NULL, 
Item_SPED1 char(5) NULL, 
Filial2 varchar(25) NULL, 
Caracteristica_contabil2 tinyint NULL, 
Descricao_caracteristica_contabil2 varchar(40) NULL, 
Tributacao_Origem2 char(3) NULL, 
Descricao_Tribut_Origem2 varchar(150) NULL, 
Item_SPED2 char(5) NULL, 
Filial3 varchar(25) NULL, 
Caracteristica_contabil3 tinyint NULL, 
Descricao_caracteristica_contabil3 varchar(40) NULL, 
Tributacao_Origem3 char(3) NULL, 
Descricao_Tribut_Origem3 varchar(150) NULL, 
Item_SPED3 char(5) NULL, 
Filial4 varchar(25) NULL, 
Caracteristica_contabil4 tinyint NULL, 
Descricao_caracteristica_contabil4 varchar(40) NULL, 
Tributacao_Origem4 char(3) NULL, 
Descricao_Tribut_Origem4 varchar(150) NULL, 
Item_SPED4 char(5) NULL, 
Filial5 varchar(25) NULL, 
Caracteristica_contabil5 tinyint NULL, 
Descricao_caracteristica_contabil5 varchar(40) NULL, 
Tributacao_Origem5 char(3) NULL, 
Descricao_Tribut_Origem5 varchar(150) NULL, 
Item_SPED5 char(5) NULL)
go

ALTER TABLE CAEDU_REPORT_PRODUTOS_SANEAMENTO_FISCAL
ADD CONSTRAINT PK_CAEDU_REPORT_PRODUTOS_SANEAMENTO_FISCAL
PRIMARY KEY (ID_REPORT, ID_ROW)
GO
