CREATE TABLE DBO.CAEDU_COMPRAS_PROD_CANCELADA_LOG
(ID_CANCELADO INT NOT NULL IDENTITY(1,1),
 PEDIDO CHAR(8) NOT NULL,
 DATA DATETIME NOT NULL,
 USUARIO VARCHAR(25) NOT NULL, 
 MOTIVO TEXT NOT NULL,
 DATALOG AS GETDATE(),
 QTDE_LINHAS_ORIGINAIS  INT NOT NULL,
 QTDE_LINHAS_CANCELADAS INT NOT NULL,
 ACOES_LOG TEXT NULL,
 CONSTRAINT PK_CAEDU_COMPRAS_PROD_CANCELADA_LOG PRIMARY KEY (ID_CANCELADO)
 ,CONSTRAINT UNQ_CAEDU_COMPRAS_PROD_CANCELADA_LOG UNIQUE (PEDIDO,DATA)
) 
GO

