select * from CM_ESTOQUE_PA_COMPOSICAO 
where produto in ('06150203'/*,'01050943'*/)
AND FILIAL = 'LOJA VIRTUAL SAO ROQUE' AND ITEM_COMPOSICAO in ('000','999','901')
ORDER BY ITEM_COMPOSICAO,DATA_SALDO, COD_CUSTO_MEDIO



select * from CM_ESTOQUE_PA 
where produto in ('06150203'/*,'01050943'*/)
AND FILIAL = 'LOJA VIRTUAL SAO ROQUE'
ORDER BY DATA_SALDO, COD_CUSTO_MEDIO


SELECT * 
FROM CM_FECHAMENTO_CUSTO_MEDIO 
WHERE DATA_SALDO>'20250930' AND DATA_GERACAO IS NOT NULL
ORDER BY DATA_SALDO,DATA_GERACAO DESC


SELECT TOP 1 *
FROM CM_FECHAMENTO_CUSTO_MEDIO 
WHERE DATA_SALDO = (SELECT MAX(DATA_SALDO) FROM CM_FECHAMENTO_CUSTO_MEDIO WHERE DATA_GERACAO IS NOT NULL)
ORDER BY DATA_GERACAO DESC

SELECT *
/*ITEM, ITEM_COMPOSICAO, DOC, OP_PED_ROMAN, SERIE_NF, ESPECIE_SERIE, PRODUTO, COR_PRODUTO, FILIAL, DATA_MOV, QTDE, VALOR, VALOR_ENCARGO,
VALOR_DESCONTO, VALOR_ENCARGO_IMPORTACAO, VALOR_IMPOSTO_DESTACAR, VALOR_IMPOSTO_AGREGAR, VALOR_FRETE, VALOR_SEGURO, VALOR_FRETE_TRANSPORTADORA,
VALOR_DESPESAS, VALOR_RESERVAS, VALOR_CONHECIMENTO_RELACIONADO, VALOR_BRUTO, VALOR_LIQ, VALOR_BASE_IPI, VALOR_IPI, GRADE, TIPO_OPERACAO, CFOP,
DESCRICAO_CFOP, UNIDADE, CLASSIF_FISCAL, MATRIZ_FISCAL, COD_TERCEIRO, CHAVE_NFE, SEQUENCIA, COD_TRANSACAO,
SPACE(10) AS COD_CUSTO_MEDIO, CAST(0 AS NUMERIC(18,5)) AS CUSTO_MEDIO_UNITARIO*/
FROM FX_CM_MONTA_CARDEX_PA_CSM('06150203','%','LOJA VIRTUAL SAO ROQUE','20251101','20260129',0,NULL) 


SELECT TOP 1
       COD_CUSTO_MEDIO
FROM   CM_FECHAMENTO_CUSTO_MEDIO
WHERE  DATA_SALDO < '20251101'
  AND  DATA_GERACAO IS NOT NULL
ORDER BY DATA_SALDO DESC, DATA_GERACAO DESC;

	--update A 
	--set COD_CUSTO_MEDIO=(SELECT TOP 1 COD_CUSTO_MEDIO 
	--						FROM CM_ESTOQUE_PA where produto = A.PRODUTO
	--						and filial=A.FILIAL ORDER BY DATA_SALDO DESC)
	--FROM @TABELA A
	--where (A.DATA_MOV > @ULT_DATA_SALDO) and A.CUSTO_MEDIO_UNITARIO=0 

SELECT TOP 1 A.COD_CUSTO_MEDIO 
FROM CM_ESTOQUE_PA A
INNER JOIN CM_FECHAMENTO_CUSTO_MEDIO B ON B.COD_CUSTO_MEDIO = A.COD_CUSTO_MEDIO
where produto = '06150203'
	and filial='LOJA VIRTUAL SAO ROQUE' ORDER BY A.DATA_SALDO DESC , DATA_GERACAO DESC


SELECT TOP 1
		   *
	FROM   CM_FECHAMENTO_CUSTO_MEDIO
	WHERE  DATA_SALDO < '20260101'
	  AND  DATA_GERACAO IS NOT NULL
	ORDER BY DATA_SALDO DESC, DATA_GERACAO DESC
