/*
select * 
from compras_produto 
where pedido in ('280807','280807V')
*/

select p.grade,P.ERP_QTD_PACK,pp.* 
--UPDATE PP SET ERP_QTD_PACK=12
--UPDATE PP SET Q4=4,Q5=4,Q6=4,Q7=0, QTDE=12
from produtos p
inner join PRODUTOS_PACKS_PERMITIDOS pp 
	on pp.PRODUTO = p.PRODUTO
where p.produto = '63010284'


select * from produtos_tamanhos where grade = '4 AO 8'


select * 
--UPDATE A SET Q4=4,Q5=4,Q6=4,Q7=0, QTDE=12
from CAEDU_COMPRAS_PRODUTOS_PACKS A
where pedido in ('280807','280807V')

SELECT B.* 

update b set en_7=0, en_6=200,en_5=200,en_4=200
FROM ESTOQUE_PROD_ENT A
INNER JOIN ESTOQUE_PROD1_ENT B 
	ON B.ROMANEIO_PRODUTO=A.ROMANEIO_PRODUTO AND B.FILIAL=A.FILIAL
WHERE NF_ENTRADA = '000020584' 
	AND A.FILIAL IN ('CD NAVEGANTES','VENDA ATACADO SC') 



SELECT B.*
--update b set en_7=0, en_6=200,en_5=200,en_4=200
FROM ESTOQUE_PROD_ENT A
INNER JOIN ESTOQUE_PROD1_ENT B 
	ON B.ROMANEIO_PRODUTO=A.ROMANEIO_PRODUTO AND B.FILIAL=A.FILIAL
WHERE NF_ENTRADA = '000053340' 
	AND A.FILIAL IN ('CD BARRA VELHA') 


SELECT B.* 
update b set en7=0, en6=12,en5=12,en4=12
FROM LOJA_ENTRADAS A
INNER JOIN LOJA_ENTRADAS_PRODUTO B ON B.ROMANEIO_PRODUTO = A.ROMANEIO_PRODUTO AND B.FILIAL=A.FILIAL
WHERE A.ROMANEIO_NF_SAIDA='000053341' AND A.FILIAL='CD BARRA VELHA'

