--exec sp_executesql N'
--/* FATURAMENTO_042 Execute(Alias:Tabela_validacao)  */'

select  id_excecao_imposto, desc_excecao, CTB_EXCECAO_IMPOSTO.INATIVO,* 
from CTB_EXCECAO_IMPOSTO 
where CTB_EXCECAO_IMPOSTO.ID_EXCECAO_IMPOSTO LIKE '%2385%'  
--and (codigo_fiscal_operacao = '5152' or codigo_fiscal_operacao is null)  
--and (ctb_tipo_operacao = 120 or ctb_tipo_operacao is null)  
--and (indicador_cfop = 78 or indicador_cfop is null)  
--and (indicador_fiscal_terceiro = 1 or indicador_fiscal_terceiro is null)  
----and (uf = 'SC' or uf is null)  and (uf_filial = 'SC' or uf_filial is null)  
----and (dt_inicio_vigencia >= '20220525' or dt_inicio_vigencia is null)  
--and (dt_fim_vigencia <= '20220525' or dt_fim_vigencia is null)  
--and (tribut_icms = '00' or tribut_icms is null)  
and (tribut_origem = '1' or tribut_origem is null)  
and (nome_clifor = 'CD BARRA VELHA' or nome_clifor is null)  
and (natureza_saida = '120.01' or natureza_saida is null) 
and (cod_filial = '000092' or cod_filial is null)  and inativo = 0 
and aplica_saida = 1 and material is null and produto is null


SELECT *
FROM FATURAMENTO
WHERE NF_SAIDA = '000024923' and SERIE_NF = '02' and FILIAL = 'CD NAVEGANTES'

SELECT ID_EXCECAO_IMPOSTO, *
FROM FATURAMENTO_ITEM
WHERE NF_SAIDA = '000024923' and SERIE_NF = '02' and FILIAL = 'CD NAVEGANTES'

BEGIN TRAN 

UPDATE FATURAMENTO_ITEM
SET ID_EXCECAO_IMPOSTO = '2385'
WHERE NF_SAIDA = '000024923' and SERIE_NF = '02' and FILIAL = 'CD NAVEGANTES'

commit

compras


select * from faturamento_item where nf_saida = '000054092' and filial = 'CD NAVEGANTES' AND CODIGO_ITEM = '58020038'


UPDATE FATURAMENTO_ITEM SET ID_EXCECAO_IMPOSTO = '2385' WHERE NF_SAIDA = '000054092' AND FILIAL = 'CD NAVEGANTES' AND SERIE_NF = '02';
UPDATE FATURAMENTO_ITEM SET ID_EXCECAO_IMPOSTO = '2385' WHERE NF_SAIDA = '000037748' AND FILIAL = 'CD NAVEGANTES' AND SERIE_NF = '02';
UPDATE FATURAMENTO_ITEM SET ID_EXCECAO_IMPOSTO = '2385' WHERE NF_SAIDA = '000049432' AND FILIAL = 'CD NAVEGANTES' AND SERIE_NF = '02';
UPDATE FATURAMENTO_ITEM SET ID_EXCECAO_IMPOSTO = '2385' WHERE NF_SAIDA = '000054469' AND FILIAL = 'CD NAVEGANTES' AND SERIE_NF = '02';
UPDATE FATURAMENTO_ITEM SET ID_EXCECAO_IMPOSTO = '2385' WHERE NF_SAIDA = '000053334' AND FILIAL = 'CD NAVEGANTES' AND SERIE_NF = '02';
UPDATE FATURAMENTO_ITEM SET ID_EXCECAO_IMPOSTO = '2385' WHERE NF_SAIDA = '000053936' AND FILIAL = 'CD NAVEGANTES' AND SERIE_NF = '02';
UPDATE FATURAMENTO_ITEM SET ID_EXCECAO_IMPOSTO = '2385' WHERE NF_SAIDA = '000024954' AND FILIAL = 'CD NAVEGANTES' AND SERIE_NF = '02';
UPDATE FATURAMENTO_ITEM SET ID_EXCECAO_IMPOSTO = '2385' WHERE NF_SAIDA = '000051300' AND FILIAL = 'CD NAVEGANTES' AND SERIE_NF = '02';
UPDATE FATURAMENTO_ITEM SET ID_EXCECAO_IMPOSTO = '2385' WHERE NF_SAIDA = '000025719' AND FILIAL = 'CD NAVEGANTES' AND SERIE_NF = '02';
UPDATE FATURAMENTO_ITEM SET ID_EXCECAO_IMPOSTO = '2385' WHERE NF_SAIDA = '000032061' AND FILIAL = 'CD NAVEGANTES' AND SERIE_NF = '02';
UPDATE FATURAMENTO_ITEM SET ID_EXCECAO_IMPOSTO = '2385' WHERE NF_SAIDA = '000053609' AND FILIAL = 'CD NAVEGANTES' AND SERIE_NF = '02';
UPDATE FATURAMENTO_ITEM SET ID_EXCECAO_IMPOSTO = '2385' WHERE NF_SAIDA = '000041923' AND FILIAL = 'CD NAVEGANTES' AND SERIE_NF = '02';
UPDATE FATURAMENTO_ITEM SET ID_EXCECAO_IMPOSTO = '2385' WHERE NF_SAIDA = '000033806' AND FILIAL = 'CD NAVEGANTES' AND SERIE_NF = '02';
UPDATE FATURAMENTO_ITEM SET ID_EXCECAO_IMPOSTO = '2385' WHERE NF_SAIDA = '000053894' AND FILIAL = 'CD NAVEGANTES' AND SERIE_NF = '02';

