SELECT P.PRODUTO,P.DESC_PRODUTO,P.GRIFFE, P.LINHA,P.GRUPO_PRODUTO, P.SUBGRUPO_PRODUTO, PP.PRECO1,
CASE 
WHEN (PP.PRECO1 BETWEEN 0 AND 13.99) THEN 1
WHEN (PP.PRECO1 BETWEEN 14 AND 15.99) THEN 2
WHEN (PP.PRECO1 BETWEEN 16 AND 17.99) THEN 3
WHEN (PP.PRECO1 BETWEEN 18 AND 1019.99) THEN 4
ELSE P.FATOR_P
END AS FATOR_P_MUDAR,
FATOR_P 
FROM PRODUTOS P
INNER JOIN PRODUTOS_PRECOS PP ON PP.PRODUTO=P.PRODUTO AND PP.CODIGO_TAB_PRECO='01'
WHERE P.GRIFFE = 'LINGERIE'	
AND P.LINHA = 'BASICO' 	
AND P.GRUPO_PRODUTO = 'CALCINHA'	
AND P.SUBGRUPO_PRODUTO = 'CALCINHA FPM'	



UPDATE P
SET FATOR_P = 
CASE 
WHEN (PP.PRECO1 BETWEEN 0 AND 13.99) THEN 1
WHEN (PP.PRECO1 BETWEEN 14 AND 15.99) THEN 2
WHEN (PP.PRECO1 BETWEEN 16 AND 17.99) THEN 3
WHEN (PP.PRECO1 BETWEEN 18 AND 1019.99) THEN 4
ELSE P.FATOR_P
END 
FROM PRODUTOS P
INNER JOIN PRODUTOS_PRECOS PP ON PP.PRODUTO=P.PRODUTO AND PP.CODIGO_TAB_PRECO='01'
WHERE P.GRIFFE = 'LINGERIE'	
AND P.LINHA = 'BASICO' 	
AND P.GRUPO_PRODUTO = 'CALCINHA'	
AND P.SUBGRUPO_PRODUTO = 'CALCINHA FPM'	
