UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM MALHA LONGO' WHERE GRIFFE='FEMININO' AND 
LINHA='CASUAL' AND GRUPO_PRODUTO='BOTTOM MALHA' AND SUBGRUPO_PRODUTO='CALCA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM MALHA CURTO' WHERE GRIFFE='FEMININO' AND 
LINHA='CASUAL' AND GRUPO_PRODUTO='BOTTOM MALHA' AND SUBGRUPO_PRODUTO='SAIA/SHORTS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM TECIDO LONGO' WHERE GRIFFE='FEMININO' AND 
LINHA='CASUAL' AND GRUPO_PRODUTO='BOTTOM TECIDO' AND SUBGRUPO_PRODUTO='CALCA OUTROS TECIDOS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM TECIDO CURTO' WHERE GRIFFE='FEMININO' AND 
LINHA='CASUAL' AND GRUPO_PRODUTO='BOTTOM TECIDO' AND SUBGRUPO_PRODUTO='SAIA/SHORTS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'INTEIRO MALHA' WHERE GRIFFE='FEMININO' AND 
LINHA='CASUAL' AND GRUPO_PRODUTO='INTEIRO' AND SUBGRUPO_PRODUTO='INTEIRO MALHA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'INTEIRO TECIDO' WHERE GRIFFE='FEMININO' AND 
LINHA='CASUAL' AND GRUPO_PRODUTO='INTEIRO' AND SUBGRUPO_PRODUTO='INTEIRO TECIDO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA JAQUETA' WHERE GRIFFE='FEMININO' AND 
LINHA='CASUAL' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='JAQUETA MALHA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP TECIDO JAQUETA' WHERE GRIFFE='FEMININO' AND 
LINHA='CASUAL' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='JAQUETA TECIDO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA M/L' WHERE GRIFFE='FEMININO' AND 
LINHA='CASUAL' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='M/L MALHA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA TRICO' WHERE GRIFFE='FEMININO' AND 
LINHA='CASUAL' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='TRICO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA M/C' WHERE GRIFFE='FEMININO' AND 
LINHA='CASUAL' AND GRUPO_PRODUTO='TOP MALHA' AND SUBGRUPO_PRODUTO='M/C' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA S/M' WHERE GRIFFE='FEMININO' AND 
LINHA='CASUAL' AND GRUPO_PRODUTO='TOP MALHA' AND SUBGRUPO_PRODUTO='S/M' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP TECIDO' WHERE GRIFFE='FEMININO' AND 
LINHA='CASUAL' AND GRUPO_PRODUTO='TOP TECIDO' AND SUBGRUPO_PRODUTO='M/L' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP TECIDO' WHERE GRIFFE='FEMININO' AND 
LINHA='CASUAL' AND GRUPO_PRODUTO='TOP TECIDO' AND SUBGRUPO_PRODUTO='S/M E M/C' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM MALHA LONGO' WHERE GRIFFE='FEMININO' AND 
LINHA='CITY' AND GRUPO_PRODUTO='BOTTOM MALHA' AND SUBGRUPO_PRODUTO='CALCA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM MALHA CURTO' WHERE GRIFFE='FEMININO' AND 
LINHA='CITY' AND GRUPO_PRODUTO='BOTTOM MALHA' AND SUBGRUPO_PRODUTO='SAIA/SHORTS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM TECIDO LONGO' WHERE GRIFFE='FEMININO' AND 
LINHA='CITY' AND GRUPO_PRODUTO='BOTTOM TECIDO' AND SUBGRUPO_PRODUTO='CALCA OUTROS TECIDOS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM TECIDO CURTO' WHERE GRIFFE='FEMININO' AND 
LINHA='CITY' AND GRUPO_PRODUTO='BOTTOM TECIDO' AND SUBGRUPO_PRODUTO='SAIA/SHORTS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'INTEIRO MALHA' WHERE GRIFFE='FEMININO' AND 
LINHA='CITY' AND GRUPO_PRODUTO='INTEIRO' AND SUBGRUPO_PRODUTO='INTEIRO MALHA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'INTEIRO TECIDO' WHERE GRIFFE='FEMININO' AND 
LINHA='CITY' AND GRUPO_PRODUTO='INTEIRO' AND SUBGRUPO_PRODUTO='INTEIRO TECIDO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA JAQUETA' WHERE GRIFFE='FEMININO' AND 
LINHA='CITY' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='JAQUETA MALHA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP TECIDO JAQUETA' WHERE GRIFFE='FEMININO' AND 
LINHA='CITY' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='JAQUETA TECIDO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA M/L' WHERE GRIFFE='FEMININO' AND 
LINHA='CITY' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='M/L MALHA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA TRICO' WHERE GRIFFE='FEMININO' AND 
LINHA='CITY' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='TRICO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA M/C' WHERE GRIFFE='FEMININO' AND 
LINHA='CITY' AND GRUPO_PRODUTO='TOP MALHA' AND SUBGRUPO_PRODUTO='M/C' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA S/M' WHERE GRIFFE='FEMININO' AND 
LINHA='CITY' AND GRUPO_PRODUTO='TOP MALHA' AND SUBGRUPO_PRODUTO='S/M' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP TECIDO' WHERE GRIFFE='FEMININO' AND 
LINHA='CITY' AND GRUPO_PRODUTO='TOP TECIDO' AND SUBGRUPO_PRODUTO='M/L' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP TECIDO' WHERE GRIFFE='FEMININO' AND 
LINHA='CITY' AND GRUPO_PRODUTO='TOP TECIDO' AND SUBGRUPO_PRODUTO='S/M E M/C' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM MALHA LONGO' WHERE GRIFFE='FEMININO' AND 
LINHA='ESPORTE' AND GRUPO_PRODUTO='BOTTOM MALHA' AND SUBGRUPO_PRODUTO='CALCA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM MALHA CURTO' WHERE GRIFFE='FEMININO' AND 
LINHA='ESPORTE' AND GRUPO_PRODUTO='BOTTOM MALHA' AND SUBGRUPO_PRODUTO='GINASTICA BERMUDA/SHORTS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM MALHA MOLETON' WHERE GRIFFE='FEMININO' AND 
LINHA='ESPORTE' AND GRUPO_PRODUTO='INVERNO BOTTOM' AND SUBGRUPO_PRODUTO='MOLETON' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA M/L' WHERE GRIFFE='FEMININO' AND 
LINHA='ESPORTE' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='M/L MALHA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA MOLETON' WHERE GRIFFE='FEMININO' AND 
LINHA='ESPORTE' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='MOLETON' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA GINASTICA' WHERE GRIFFE='FEMININO' AND 
LINHA='ESPORTE' AND GRUPO_PRODUTO='TOP MALHA' AND SUBGRUPO_PRODUTO='GINASTICA TOP' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA M/C' WHERE GRIFFE='FEMININO' AND 
LINHA='ESPORTE' AND GRUPO_PRODUTO='TOP MALHA' AND SUBGRUPO_PRODUTO='M/C' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA S/M' WHERE GRIFFE='FEMININO' AND 
LINHA='ESPORTE' AND GRUPO_PRODUTO='TOP MALHA' AND SUBGRUPO_PRODUTO='S/M' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM MALHA LONGO' WHERE GRIFFE='FEMININO' AND 
LINHA='FASHION' AND GRUPO_PRODUTO='BOTTOM MALHA' AND SUBGRUPO_PRODUTO='CALCA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM MALHA CURTO' WHERE GRIFFE='FEMININO' AND 
LINHA='FASHION' AND GRUPO_PRODUTO='BOTTOM MALHA' AND SUBGRUPO_PRODUTO='SAIA/SHORTS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM TECIDO CURTO' WHERE GRIFFE='FEMININO' AND 
LINHA='FASHION' AND GRUPO_PRODUTO='BOTTOM TECIDO' AND SUBGRUPO_PRODUTO='SAIA/SHORTS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'INTEIRO MALHA' WHERE GRIFFE='FEMININO' AND 
LINHA='FASHION' AND GRUPO_PRODUTO='INTEIRO' AND SUBGRUPO_PRODUTO='INTEIRO MALHA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'INTEIRO TECIDO' WHERE GRIFFE='FEMININO' AND 
LINHA='FASHION' AND GRUPO_PRODUTO='INTEIRO' AND SUBGRUPO_PRODUTO='INTEIRO TECIDO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP TECIDO JAQUETA' WHERE GRIFFE='FEMININO' AND 
LINHA='FASHION' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='JAQUETA TECIDO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA M/L' WHERE GRIFFE='FEMININO' AND 
LINHA='FASHION' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='M/L MALHA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA MOLETON' WHERE GRIFFE='FEMININO' AND 
LINHA='FASHION' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='MOLETON' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA TRICO' WHERE GRIFFE='FEMININO' AND 
LINHA='FASHION' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='TRICO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP LICENCIADOS' WHERE GRIFFE='FEMININO' AND 
LINHA='FASHION' AND GRUPO_PRODUTO='TOP MALHA' AND SUBGRUPO_PRODUTO='LICENCIADOS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA M/C' WHERE GRIFFE='FEMININO' AND 
LINHA='FASHION' AND GRUPO_PRODUTO='TOP MALHA' AND SUBGRUPO_PRODUTO='M/C' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA S/M' WHERE GRIFFE='FEMININO' AND 
LINHA='FASHION' AND GRUPO_PRODUTO='TOP MALHA' AND SUBGRUPO_PRODUTO='S/M' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP TECIDO' WHERE GRIFFE='FEMININO' AND 
LINHA='FASHION' AND GRUPO_PRODUTO='TOP TECIDO' AND SUBGRUPO_PRODUTO='TOP OUTROS TECIDOS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM MALHA LONGO' WHERE GRIFFE='FEMININO' AND 
LINHA='ROMANTICO' AND GRUPO_PRODUTO='BOTTOM MALHA' AND SUBGRUPO_PRODUTO='CALCA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM MALHA CURTO' WHERE GRIFFE='FEMININO' AND 
LINHA='ROMANTICO' AND GRUPO_PRODUTO='BOTTOM MALHA' AND SUBGRUPO_PRODUTO='SAIA/SHORTS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM TECIDO CURTO' WHERE GRIFFE='FEMININO' AND 
LINHA='ROMANTICO' AND GRUPO_PRODUTO='BOTTOM TECIDO' AND SUBGRUPO_PRODUTO='SAIA/SHORTS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'INTEIRO MALHA' WHERE GRIFFE='FEMININO' AND 
LINHA='ROMANTICO' AND GRUPO_PRODUTO='INTEIRO' AND SUBGRUPO_PRODUTO='INTEIRO MALHA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'INTEIRO TECIDO' WHERE GRIFFE='FEMININO' AND 
LINHA='ROMANTICO' AND GRUPO_PRODUTO='INTEIRO' AND SUBGRUPO_PRODUTO='INTEIRO TECIDO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP TECIDO JAQUETA' WHERE GRIFFE='FEMININO' AND 
LINHA='ROMANTICO' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='JAQUETA TECIDO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA M/L' WHERE GRIFFE='FEMININO' AND 
LINHA='ROMANTICO' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='M/L MALHA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA MOLETON' WHERE GRIFFE='FEMININO' AND 
LINHA='ROMANTICO' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='MOLETON' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA TRICO' WHERE GRIFFE='FEMININO' AND 
LINHA='ROMANTICO' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='TRICO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP LICENCIADOS' WHERE GRIFFE='FEMININO' AND 
LINHA='ROMANTICO' AND GRUPO_PRODUTO='TOP MALHA' AND SUBGRUPO_PRODUTO='LICENCIADOS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA M/C' WHERE GRIFFE='FEMININO' AND 
LINHA='ROMANTICO' AND GRUPO_PRODUTO='TOP MALHA' AND SUBGRUPO_PRODUTO='M/C' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA S/M' WHERE GRIFFE='FEMININO' AND 
LINHA='ROMANTICO' AND GRUPO_PRODUTO='TOP MALHA' AND SUBGRUPO_PRODUTO='S/M' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP TECIDO' WHERE GRIFFE='FEMININO' AND 
LINHA='ROMANTICO' AND GRUPO_PRODUTO='TOP TECIDO' AND SUBGRUPO_PRODUTO='TOP OUTROS TECIDOS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM MALHA LONGO' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM CASUAL' AND GRUPO_PRODUTO='BOTTOM MALHA' AND SUBGRUPO_PRODUTO='CALCA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM MALHA CURTO' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM CASUAL' AND GRUPO_PRODUTO='BOTTOM MALHA' AND SUBGRUPO_PRODUTO='SAIA/SHORTS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM TECIDO LONGO' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM CASUAL' AND GRUPO_PRODUTO='BOTTOM TECIDO' AND SUBGRUPO_PRODUTO='CALCA OUTROS TECIDOS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM TECIDO CURTO' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM CASUAL' AND GRUPO_PRODUTO='BOTTOM TECIDO' AND SUBGRUPO_PRODUTO='SAIA/SHORTS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'INTEIRO MALHA' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM CASUAL' AND GRUPO_PRODUTO='INTEIRO' AND SUBGRUPO_PRODUTO='INTEIRO MALHA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM MALHA MOLETON' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM CASUAL' AND GRUPO_PRODUTO='INVERNO BOTTOM' AND SUBGRUPO_PRODUTO='CALCA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP TECIDO JAQUETA' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM CASUAL' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='JAQUETA TECIDO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA M/L' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM CASUAL' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='M/L' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA MOLETON' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM CASUAL' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='MOLETON' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA TRICO' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM CASUAL' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='TRICO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP LICENCIADOS' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM CASUAL' AND GRUPO_PRODUTO='TOP MALHA' AND SUBGRUPO_PRODUTO='LICENCIADOS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA M/C' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM CASUAL' AND GRUPO_PRODUTO='TOP MALHA' AND SUBGRUPO_PRODUTO='M/C' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA S/M' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM CASUAL' AND GRUPO_PRODUTO='TOP MALHA' AND SUBGRUPO_PRODUTO='S/M' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP TECIDO' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM CASUAL' AND GRUPO_PRODUTO='TOP TECIDO' AND SUBGRUPO_PRODUTO='S/M E M/C' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM MALHA LONGO' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM FASHION' AND GRUPO_PRODUTO='BOTTOM MALHA' AND SUBGRUPO_PRODUTO='CALCA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM MALHA CURTO' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM FASHION' AND GRUPO_PRODUTO='BOTTOM MALHA' AND SUBGRUPO_PRODUTO='SAIA/SHORTS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM TECIDO LONGO' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM FASHION' AND GRUPO_PRODUTO='BOTTOM TECIDO' AND SUBGRUPO_PRODUTO='CALCA OUTROS TECIDOS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM TECIDO CURTO' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM FASHION' AND GRUPO_PRODUTO='BOTTOM TECIDO' AND SUBGRUPO_PRODUTO='SAIA/SHORTS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'INTEIRO MALHA' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM FASHION' AND GRUPO_PRODUTO='INTEIRO' AND SUBGRUPO_PRODUTO='INTEIRO MALHA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM MALHA MOLETON' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM FASHION' AND GRUPO_PRODUTO='INVERNO BOTTOM' AND SUBGRUPO_PRODUTO='CALCA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP TECIDO JAQUETA' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM FASHION' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='JAQUETA TECIDO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA M/L' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM FASHION' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='M/L' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA MOLETON' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM FASHION' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='MOLETON' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA TRICO' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM FASHION' AND GRUPO_PRODUTO='INVERNO TOP' AND SUBGRUPO_PRODUTO='TRICO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP LICENCIADOS' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM FASHION' AND GRUPO_PRODUTO='TOP MALHA' AND SUBGRUPO_PRODUTO='LICENCIADOS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA M/C' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM FASHION' AND GRUPO_PRODUTO='TOP MALHA' AND SUBGRUPO_PRODUTO='M/C' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP MALHA S/M' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM FASHION' AND GRUPO_PRODUTO='TOP MALHA' AND SUBGRUPO_PRODUTO='S/M' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP TECIDO' WHERE GRIFFE='FEMININO' AND 
LINHA='FPM FASHION' AND GRUPO_PRODUTO='TOP TECIDO' AND SUBGRUPO_PRODUTO='S/M E M/C' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM JEANS LONGO' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='BOTTOM CASUAL' AND SUBGRUPO_PRODUTO='CALCA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM JEANS CURTO' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='BOTTOM CASUAL' AND SUBGRUPO_PRODUTO='SAIA/SHORTS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM JEANS LONGO' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='BOTTOM CITY' AND SUBGRUPO_PRODUTO='CALCA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM JEANS CURTO' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='BOTTOM CITY' AND SUBGRUPO_PRODUTO='SAIA/SHORTS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM JEANS LONGO' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='BOTTOM FASHION' AND SUBGRUPO_PRODUTO='CALCA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM JEANS CURTO' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='BOTTOM FASHION' AND SUBGRUPO_PRODUTO='SAIA/SHORTS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM JEANS LONGO' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='BOTTOM FPM CASUAL' AND SUBGRUPO_PRODUTO='CALCA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM JEANS CURTO' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='BOTTOM FPM CASUAL' AND SUBGRUPO_PRODUTO='SAIA/SHORTS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM JEANS LONGO' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='BOTTOM FPM FASHION' AND SUBGRUPO_PRODUTO='CALCA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM JEANS CURTO' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='BOTTOM FPM FASHION' AND SUBGRUPO_PRODUTO='SAIA/SHORTS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM JEANS LONGO' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='BOTTOM ROMANTICO' AND SUBGRUPO_PRODUTO='CALCA' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM JEANS CURTO' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='BOTTOM ROMANTICO' AND SUBGRUPO_PRODUTO='SAIA/SHORTS' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'INTEIRO JEANS' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='INTEIRO CASUAL' AND SUBGRUPO_PRODUTO='INTEIRO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'INTEIRO JEANS' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='INTEIRO CITY' AND SUBGRUPO_PRODUTO='INTEIRO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'INTEIRO JEANS' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='INTEIRO FASHION' AND SUBGRUPO_PRODUTO='INTEIRO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'INTEIRO JEANS' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='INTEIRO FPM CASUAL' AND SUBGRUPO_PRODUTO='INTEIRO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'INTEIRO JEANS' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='INTEIRO FPM FASHION' AND SUBGRUPO_PRODUTO='INTEIRO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'INTEIRO JEANS' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='INTEIRO ROMANTICO' AND SUBGRUPO_PRODUTO='INTEIRO' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM JEANS LONGO' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='MESA JEANS' AND SUBGRUPO_PRODUTO='MESA JEANS INF' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'BOTTOM JEANS LONGO' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='MESA JEANS' AND SUBGRUPO_PRODUTO='MESA JEANS SUP' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP JEANS' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='TOP CASUAL' AND SUBGRUPO_PRODUTO='M/C E M/L' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP JEANS' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='TOP CITY' AND SUBGRUPO_PRODUTO='M/C E M/L' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP JEANS' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='TOP FASHION' AND SUBGRUPO_PRODUTO='M/C E M/L' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP JEANS' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='TOP FPM CASUAL' AND SUBGRUPO_PRODUTO='M/C E M/L' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP JEANS' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='TOP FPM FASHION' AND SUBGRUPO_PRODUTO='M/C E M/L' 
UPDATE CAE_PRODUTOS_FATOR_P SET ERP_GRUPO_MERCADORIA = 'TOP JEANS' WHERE GRIFFE='FEMININO' AND 
LINHA='JEANS' AND GRUPO_PRODUTO='TOP ROMANTICO' AND SUBGRUPO_PRODUTO='M/C E M/L' 
