select * from PRODUTOS_BARRA_APAGADOS where CODIGO_BARRA = 'C31501140002006'

INSERT INTO CAEDU.dbo.PRODUTOS_BARRA
(CODIGO_BARRA, PRODUTO, COR_PRODUTO, TAMANHO, GRADE, DATA_PARA_TRANSFERENCIA, NOME_CLIFOR, CODIGO_BARRA_PADRAO, INATIVO, TIPO_COD_BAR, LX_STATUS_REGISTRO, ID_SKU, LX_HASH)
VALUES(N'C31501140002006', N'C3150114', N'00020', 6, N'M', '2022-01-18 13:26:16.660', NULL, 1, 0, 2, 0, NULL, NULL);

insert into PRODUTO_CORES 
(PRODUTO, COR_PRODUTO, SIMILAR, DESC_COR_PRODUTO, SORTIMENTO_COR, COR_SORTIDA, STATUS_VENDA_ATUAL, INICIO_VENDAS, FIM_VENDAS, COR_FABRICANTE, 
TIPO_LAVAGEM_TINTURARIA, TINTURARIA_LAVAGEM, COR, MATERIAL, COR_MATERIAL, ETIQUETA, CUSTO_REPOSICAO1, CUSTO_REPOSICAO2, CUSTO_REPOSICAO3, CUSTO_REPOSICAO4, 
VARIANTE_TAMANHO, DATA_PARA_TRANSFERENCIA, PRECO_REPOSICAO_1, PRECO_REPOSICAO_2, PRECO_REPOSICAO_3, PRECO_REPOSICAO_4, PRECO_A_VISTA_REPOSICAO_1, 
PRECO_A_VISTA_REPOSICAO_2, PRECO_A_VISTA_REPOSICAO_3, PRECO_A_VISTA_REPOSICAO_4, CLASSIF_FISCAL, COMPOSICAO, TRIBUT_ORIGEM, LX_STATUS_REGISTRO, LX_HASH)

select PRODUTO, '00020' as COR_PRODUTO, SIMILAR, 'AZUL CLARO' DESC_COR_PRODUTO, SORTIMENTO_COR, COR_SORTIDA, STATUS_VENDA_ATUAL, INICIO_VENDAS, FIM_VENDAS, 
COR_FABRICANTE, TIPO_LAVAGEM_TINTURARIA, TINTURARIA_LAVAGEM, COR, MATERIAL, COR_MATERIAL, ETIQUETA, CUSTO_REPOSICAO1, CUSTO_REPOSICAO2, CUSTO_REPOSICAO3, 
CUSTO_REPOSICAO4, VARIANTE_TAMANHO, getdate() as DATA_PARA_TRANSFERENCIA, PRECO_REPOSICAO_1, PRECO_REPOSICAO_2, PRECO_REPOSICAO_3, PRECO_REPOSICAO_4, 
PRECO_A_VISTA_REPOSICAO_1, PRECO_A_VISTA_REPOSICAO_2, PRECO_A_VISTA_REPOSICAO_3, PRECO_A_VISTA_REPOSICAO_4, CLASSIF_FISCAL, COMPOSICAO, TRIBUT_ORIGEM, LX_STATUS_REGISTRO, LX_HASH
from produto_cores 
where produto = 'C3150114'


select * from produto_cores where cor_produto = '00020'




