select * from filiais where filial like 'RS%'

select * from filiais where COD_FILIAL = '000137'

select * from LOJAS_VAREJO where filial = 'SP - SANTO AMARO'

select * from LOJAS_VAREJO where filial = 'BARRA VELHA - CQ'


INSERT INTO LOJAS_VAREJO
(CODIGO_FILIAL, FILIAL, SEQUENCIA_TIKET, GERENTE_PERIODO, BENEFICIARIO_CHQ, 
CIDADE_CHQ, SENHA_DESISTENCIA_VENDA, NAO_ENVIA_ESTOQUE, SEQUENCIA_RESERVA, 
SEQUENCIA_SAIDAS, SEQUENCIA_ENTRADAS, SEQUENCIA_CLIENTES, NAO_GERA_GIRO, 
USA_CPF_RG_OU_CODIGO, DATA_PARA_TRANSFERENCIA, PERMANENCIA_TROCO, MOSTRA_FOTOS, 
TIRA_FOTO, VALIDA_PRODUTO, ABRE_VENDA_VENDEDOR, PEDE_SENHA_VEND, 
CPF_OBRIGATORIO, IMPRIME_ITEM_LANCADO, ACUMULA_ITEM_VENDA, SUSP_VENDA, 
TROCA_VOLTA_VENDA, LISTA_TIPO_PGTO_TICKET, SENHA_DESCONTO, DESC_CENTAVOS, 
FIXA_DESCONTO, PARCELAS_MESMO_DIA, ENT_SAI_CBAR, OBRIGA_TITULO, RODIZIO_FOTOS, 
DATAS_RESUMOS, DATAS_VENDEDORES, DESTACA_TROCA, DESCONTA_TROCA, MOSTRA_TICKET, 
SEQUENCIA_TICKET, PERG_IMP_ROMANEIOS, MOSTRA_NO_TICKET, 
IMPRIME_TICKETS_SUSPENSOS, PERG_IMP_TICKETS, MASCARA_CODIGO, JANELA_TROCO, 
PREVISAO_RETORNO, ALTERA_NA_LOJA, PARAMETRO_POR_LOJA, NOME_GERENTE_LOJA, 
COD_GERENTE_LOJA, COD_GERENTE_PERIODO, NOME_GERENTE_PERIODO, OCULTAR_FAIXA_PGTO, 
SENHA_TECNICA, CONTROLA_BAIXAS, USA_TICKET, SALDO_INICIAL, 
ACEITA_MAIS_PERIODOS, IMP_NOTA_CUPOM, PERG_PERMITE_EST, DESC_CENTAVOS_VEND, 
MOSTRA_EST, ENT_NUMTICKET, SENHA_VENDA, COMANDO_EXCLUSAO, 
MOVIMENTA_CAIXA_FECHADO, DESC_PGTO_AVISTA, LANCA_ACRES, TICKET_AGRUPADO, 
VALIDA_CHEQUE, PERG_FUNCIONARIO, PERMITE_ENT_FORNEC, FUNC_POR_FORA, 
LIMITE_PGTO_CHQ, LANCAMENTO_PADRAO, PERMITE_FUNC, NAO_IMP_PROD_TRANSITO, 
ENTRADA_TRANSITO, SUGERE_ADM, SUGERE_ADM_DESABILITA, ALIQUOTA_IMP_FISCAL, 
HAB_DESC_TROCA, JOGA_PARA_SEGUNDA, AUTOMATICA, LANCAMENTO_PADRAO_IMPOSTOS, 
LANCAMENTO_PADRAO_IMPOSTO, LX_STATUS_LOJA, SEQUENCIA_PRE_VENDA, SEQUENCIA_DAV, 
SEQUENCIA_FATURA, SEQUENCIA_RECIBO, SEQUENCIA_PEDIDO, SEQUENCIA_VENDA_SAT, 
LANCAMENTO_PADRAO_CANCELAMENTO_B2C, LANCAMENTO_PADRAO_DEVOL_DINHEIRO, 
LANCAMENTO_PADRAO_ESTORNO_CARTAO)

SELECT 
'000137' AS CODIGO_FILIAL, 'RS - PORTO ALEGRE CENTRO' AS FILIAL, SEQUENCIA_TIKET, GERENTE_PERIODO, BENEFICIARIO_CHQ, 
CIDADE_CHQ, SENHA_DESISTENCIA_VENDA, NAO_ENVIA_ESTOQUE, SEQUENCIA_RESERVA, 
SEQUENCIA_SAIDAS, SEQUENCIA_ENTRADAS, SEQUENCIA_CLIENTES, NAO_GERA_GIRO, 
USA_CPF_RG_OU_CODIGO, DATA_PARA_TRANSFERENCIA, PERMANENCIA_TROCO, MOSTRA_FOTOS, 
TIRA_FOTO, VALIDA_PRODUTO, ABRE_VENDA_VENDEDOR, PEDE_SENHA_VEND, 
CPF_OBRIGATORIO, IMPRIME_ITEM_LANCADO, ACUMULA_ITEM_VENDA, SUSP_VENDA, 
TROCA_VOLTA_VENDA, LISTA_TIPO_PGTO_TICKET, SENHA_DESCONTO, DESC_CENTAVOS, 
FIXA_DESCONTO, PARCELAS_MESMO_DIA, ENT_SAI_CBAR, OBRIGA_TITULO, RODIZIO_FOTOS, 
DATAS_RESUMOS, DATAS_VENDEDORES, DESTACA_TROCA, DESCONTA_TROCA, MOSTRA_TICKET, 
SEQUENCIA_TICKET, PERG_IMP_ROMANEIOS, MOSTRA_NO_TICKET, 
IMPRIME_TICKETS_SUSPENSOS, PERG_IMP_TICKETS, MASCARA_CODIGO, JANELA_TROCO, 
PREVISAO_RETORNO, ALTERA_NA_LOJA, PARAMETRO_POR_LOJA, NOME_GERENTE_LOJA, 
COD_GERENTE_LOJA, COD_GERENTE_PERIODO, NOME_GERENTE_PERIODO, OCULTAR_FAIXA_PGTO, 
SENHA_TECNICA, CONTROLA_BAIXAS, USA_TICKET, SALDO_INICIAL, 
ACEITA_MAIS_PERIODOS, IMP_NOTA_CUPOM, PERG_PERMITE_EST, DESC_CENTAVOS_VEND, 
MOSTRA_EST, ENT_NUMTICKET, SENHA_VENDA, COMANDO_EXCLUSAO, 
MOVIMENTA_CAIXA_FECHADO, DESC_PGTO_AVISTA, LANCA_ACRES, TICKET_AGRUPADO, 
VALIDA_CHEQUE, PERG_FUNCIONARIO, PERMITE_ENT_FORNEC, FUNC_POR_FORA, 
LIMITE_PGTO_CHQ, LANCAMENTO_PADRAO, PERMITE_FUNC, NAO_IMP_PROD_TRANSITO, 
ENTRADA_TRANSITO, SUGERE_ADM, SUGERE_ADM_DESABILITA, ALIQUOTA_IMP_FISCAL, 
HAB_DESC_TROCA, JOGA_PARA_SEGUNDA, AUTOMATICA, LANCAMENTO_PADRAO_IMPOSTOS, 
LANCAMENTO_PADRAO_IMPOSTO, LX_STATUS_LOJA, SEQUENCIA_PRE_VENDA, SEQUENCIA_DAV, 
SEQUENCIA_FATURA, SEQUENCIA_RECIBO, SEQUENCIA_PEDIDO, SEQUENCIA_VENDA_SAT, 
LANCAMENTO_PADRAO_CANCELAMENTO_B2C, LANCAMENTO_PADRAO_DEVOL_DINHEIRO, 
LANCAMENTO_PADRAO_ESTORNO_CARTAO
FROM LOJAS_VAREJO
WHERE filial = 'SP - SANTO AMARO'

SELECT * FROM TABELAS_PRECO order by CODIGO_TAB_PRECO
SELECT * FROM TABELAS_PRECO WHERE CODIGO_TAB_PRECO='77' /*TABELA LIKE '%TATUAPE%'*/

select * from produtos_precos where CODIGO_TAB_PRECO = '77'

INSERT INTO  LOJA_OPERACOES_VENDA
(OPERACAO_VENDA
,DESC_OPERACAO_VENDA
,CADASTRA_CLIENTE
,DESCONTO_OPERACAO
,DESCONTO_POR_ITEM
,LIMITE_DESCONTO
,USA_TABELA_PADRAO
,CODIGO_TAB_PRECO
,ALTERA_TABELA
,ALTERA_PRECO
,ALTERA_DESCONTO
,PORCENTAGEM_ABATER_COMISSAO
,PGTOS_EM_ABERTO
,OPERACAO_INATIVA
,DATA_ATIVACAO
,DATA_DESATIVACAO
,DATA_PARA_TRANSFERENCIA
,LIMITE_DESCONTO_GERENTE
,ALTERA_DESCONTO_PGTO
,ALTERA_PRECO_BRUTO
,DESCONTO_ITEM_VENDA
,DESCONTO_ITEM_TROCA
,LIMITE_DESCONTO_ITEM
,LIMITE_DESCONTO_ITEM_GERENTE
,LX_STATUS_REGISTRO
,ID_OPERACAO_VENDA

)
SELECT 
'087' AS OPERACAO_VENDA
,'OPERACAO VENDA RS - POA-CENTRO' AS DESC_OPERACAO_VENDA
,CADASTRA_CLIENTE
,DESCONTO_OPERACAO
,DESCONTO_POR_ITEM
,LIMITE_DESCONTO
,USA_TABELA_PADRAO
,'87' AS CODIGO_TAB_PRECO
,ALTERA_TABELA
,ALTERA_PRECO
,ALTERA_DESCONTO
,PORCENTAGEM_ABATER_COMISSAO
,PGTOS_EM_ABERTO
,OPERACAO_INATIVA
,DATA_ATIVACAO
,DATA_DESATIVACAO
,DATA_PARA_TRANSFERENCIA
,LIMITE_DESCONTO_GERENTE
,ALTERA_DESCONTO_PGTO
,ALTERA_PRECO_BRUTO
,DESCONTO_ITEM_VENDA
,DESCONTO_ITEM_TROCA
,LIMITE_DESCONTO_ITEM
,LIMITE_DESCONTO_ITEM_GERENTE
,LX_STATUS_REGISTRO
,ID_OPERACAO_VENDA
FROM LOJA_OPERACOES_VENDA 
WHERE OPERACAO_VENDA = '056'

select * from LOJA_OPERACOES_VENDA 
WHERE OPERACAO_VENDA = '087'

SELECT ','+NAME FROM SYSCOLUMNS WHERE ID=OBJECT_ID('LOJA_OPERACOES_VENDA') ORDER BY COLID

SELECT * FROM TABELAS_PRECO
WHERE TABELA LIKE '%SAPOPEMBA%'

-- pega precos de sao matheus como base
begin tran
INSERT INTO PRODUTOS_PRECOS
(CODIGO_TAB_PRECO,
		PRODUTO,
		PRECO1,
		PRECO2,
		PRECO3,
		PRECO4,
		LIMITE_DESCONTO,
		PROMOCAO_DESCONTO,
		ULT_ATUALIZACAO,
		INICIO_PROMOCAO,
		FIM_PROMOCAO,
		DATA_PARA_TRANSFERENCIA,
		MARK_UP_PREVISTO,
		PROMOCAO_ATACADO,
		PRECO_LIQUIDO1,
		PRECO_LIQUIDO2,
		PRECO_LIQUIDO3,
		PRECO_LIQUIDO4,
		LX_STATUS_REGISTRO,
		PRECO1_ANTERIOR,
		DATA_CARGA_PRECOS)
SELECT	distinct
		'87' AS CODIGO_TAB_PRECO,
		PRODUTO,
		PRECO1,
		PRECO2,
		PRECO3,
		PRECO4,
		LIMITE_DESCONTO,
		PROMOCAO_DESCONTO,
		CONVERT(VARCHAR,GETDATE(),112) AS ULT_ATUALIZACAO,
		INICIO_PROMOCAO,
		FIM_PROMOCAO,
		'19000101' AS DATA_PARA_TRANSFERENCIA,
		MARK_UP_PREVISTO,
		PROMOCAO_ATACADO,
		PRECO_LIQUIDO1,
		PRECO_LIQUIDO2,
		PRECO_LIQUIDO3,
		PRECO_LIQUIDO4,
		LX_STATUS_REGISTRO,
		PRECO1_ANTERIOR,
		DATA_CARGA_PRECOS
FROM PRODUTOS_PRECOS WHERE CODIGO_TAB_PRECO='11'

commit



SELECT * FROM TABELAS_PRECO_FILIAL

INSERT INTO TABELAS_PRECO_FILIAL
SELECT '66'  AS CODIGO_TAB_PRECO,
'SP - SAPOPEMBA' AS FILIAL,
GERA_TABELA_LOJA,
PERMITE_GESTAO_LOJA,
FATOR_PRECO_BASE,
INATIVO,
DATA_PARA_TRANSFERENCIA,
BLOQ_ATUALIZACAO_BASE,
LIMITE_VARIACAO_PRECO,
LX_STATUS_REGISTRO
FROM TABELAS_PRECO_FILIAL
WHERE CODIGO_TAB_PRECO='97'
