--select * from CADASTRO_CLI_FOR where clifor in ('000118','000135','000133','000134')
--select * from filiais where COD_FILIAL in ('000118','000135','000133','000134')

----
select * from FORNECEDORES where COD_FORNECEDOR in ('000118','000135','000133','000134')

UPDATE FORNECEDORES 
SET MOEDA = 'R$', CTB_CONTA_CONTABIL='212.01.001', FORNECE_PROD_ACAB=1
WHERE COD_FORNECEDOR in ('000135','000133','000134')
-----
SELECT * FROM CLIENTES_ATACADO WHERE COD_CLIENTE in ('000118','000135','000133','000134')

UPDATE CLIENTES_ATACADO 
SET MOEDA = 'R$', TRANSP_REDESPACHO='O PROPRIO', INDICADOR_VENDA='D'
WHERE COD_CLIENTE in ('000135','000133','000134')

--SELECT * FROM CLIENTE_REPRE WHERE 
--CLIENTE_ATACADO='SP - CAMPO LIMPO'
--WHERE COD_CLIENTE in ('000135','000133','000134')

INSERT INTO CLIENTE_REPRE
SELECT NOME_CLIFOR, NOME_CLIFOR, GETDATE(), 0.00000, 1 FROM CADASTRO_CLI_FOR WHERE CLIFOR IN ('000135','000133','000134')
-------------------

SELECT * FROM REPRESENTANTES WHERE CLIFOR  in ('000118','000135','000133','000134') ORDER BY CLIFOR

UPDATE REPRESENTANTES
SET CTB_CONTA_CONTABIL='212.01.001'
WHERE CLIFOR  in ('000135','000133','000134')

-----------------

SELECT * FROM LOJAS_VAREJO WHERE CODIGO_FILIAL  in ('000118','000135','000133','000134') ORDER BY CODIGO_FILIAL

-- INSERE LOJA_VAREJO
INSERT INTO LOJAS_VAREJO
(CODIGO_FILIAL, FILIAL, SEQUENCIA_TIKET, GERENTE_PERIODO, BENEFICIARIO_CHQ, 
CIDADE_CHQ, SENHA_DESISTENCIA_VENDA, NAO_ENVIA_ESTOQUE, SEQUENCIA_RESERVA, 
SEQUENCIA_SAIDAS, SEQUENCIA_ENTRADAS, SEQUENCIA_CLIENTES, NAO_GERA_GIRO, 
USA_CPF_RG_OU_CODIGO, DATA_PARA_TRANSFERENCIA, PERMANENCIA_TROCO, MOSTRA_FOTOS, 
TIRA_FOTO, VALIDA_PRODUTO, ABRE_VENDA_VENDEDOR, PEDE_SENHA_VEND, 
CPF_OBRIGATORIO, IMPRIME_ITEM_LANCADO, ACUMULA_ITEM_VENDA, SUSP_VENDA, 
TROCA_VOLTA_VENDA, LISTA_TIPO_PGTO_TICKET, SENHA_DESCONTO, DESC_CENTAVOS, 
FIXA_DESCONTO, PARCELAS_MESMO_DIA, ENT_SAI_CBAR, OBRIGA_TITULO, RODIZIO_FOTOS, 
DATAS_RESUMOS, DATAS_VENDEDORES, DESTACA_TROCA, DESCONTA_TROCA, MOSTRA_TICKET, 
SEQUENCIA_TICKET, PERG_IMP_ROMANEIOS, MOSTRA_NO_TICKET, 
IMPRIME_TICKETS_SUSPENSOS, PERG_IMP_TICKETS, MASCARA_CODIGO, JANELA_TROCO, 
PREVISAO_RETORNO, ALTERA_NA_LOJA, PARAMETRO_POR_LOJA, NOME_GERENTE_LOJA, 
COD_GERENTE_LOJA, COD_GERENTE_PERIODO, NOME_GERENTE_PERIODO, OCULTAR_FAIXA_PGTO, 
SENHA_TECNICA, CONTROLA_BAIXAS, USA_TICKET, SALDO_INICIAL, 
ACEITA_MAIS_PERIODOS, IMP_NOTA_CUPOM, PERG_PERMITE_EST, DESC_CENTAVOS_VEND, 
MOSTRA_EST, ENT_NUMTICKET, SENHA_VENDA, COMANDO_EXCLUSAO, 
MOVIMENTA_CAIXA_FECHADO, DESC_PGTO_AVISTA, LANCA_ACRES, TICKET_AGRUPADO, 
VALIDA_CHEQUE, PERG_FUNCIONARIO, PERMITE_ENT_FORNEC, FUNC_POR_FORA, 
LIMITE_PGTO_CHQ, LANCAMENTO_PADRAO, PERMITE_FUNC, NAO_IMP_PROD_TRANSITO, 
ENTRADA_TRANSITO, SUGERE_ADM, SUGERE_ADM_DESABILITA, ALIQUOTA_IMP_FISCAL, 
HAB_DESC_TROCA, JOGA_PARA_SEGUNDA, AUTOMATICA, LANCAMENTO_PADRAO_IMPOSTOS, 
LANCAMENTO_PADRAO_IMPOSTO, LX_STATUS_LOJA, SEQUENCIA_PRE_VENDA, SEQUENCIA_DAV, 
SEQUENCIA_FATURA, SEQUENCIA_RECIBO, SEQUENCIA_PEDIDO, SEQUENCIA_VENDA_SAT, 
LANCAMENTO_PADRAO_CANCELAMENTO_B2C, LANCAMENTO_PADRAO_DEVOL_DINHEIRO, 
LANCAMENTO_PADRAO_ESTORNO_CARTAO)

SELECT 
'000133' AS CODIGO_FILIAL, 'SP - LAPA' AS FILIAL, SEQUENCIA_TIKET, GERENTE_PERIODO, BENEFICIARIO_CHQ, 
CIDADE_CHQ, SENHA_DESISTENCIA_VENDA, NAO_ENVIA_ESTOQUE, SEQUENCIA_RESERVA, 
SEQUENCIA_SAIDAS, SEQUENCIA_ENTRADAS, SEQUENCIA_CLIENTES, NAO_GERA_GIRO, 
USA_CPF_RG_OU_CODIGO, DATA_PARA_TRANSFERENCIA, PERMANENCIA_TROCO, MOSTRA_FOTOS, 
TIRA_FOTO, VALIDA_PRODUTO, ABRE_VENDA_VENDEDOR, PEDE_SENHA_VEND, 
CPF_OBRIGATORIO, IMPRIME_ITEM_LANCADO, ACUMULA_ITEM_VENDA, SUSP_VENDA, 
TROCA_VOLTA_VENDA, LISTA_TIPO_PGTO_TICKET, SENHA_DESCONTO, DESC_CENTAVOS, 
FIXA_DESCONTO, PARCELAS_MESMO_DIA, ENT_SAI_CBAR, OBRIGA_TITULO, RODIZIO_FOTOS, 
DATAS_RESUMOS, DATAS_VENDEDORES, DESTACA_TROCA, DESCONTA_TROCA, MOSTRA_TICKET, 
SEQUENCIA_TICKET, PERG_IMP_ROMANEIOS, MOSTRA_NO_TICKET, 
IMPRIME_TICKETS_SUSPENSOS, PERG_IMP_TICKETS, MASCARA_CODIGO, JANELA_TROCO, 
PREVISAO_RETORNO, ALTERA_NA_LOJA, PARAMETRO_POR_LOJA, NOME_GERENTE_LOJA, 
COD_GERENTE_LOJA, COD_GERENTE_PERIODO, NOME_GERENTE_PERIODO, OCULTAR_FAIXA_PGTO, 
SENHA_TECNICA, CONTROLA_BAIXAS, USA_TICKET, SALDO_INICIAL, 
ACEITA_MAIS_PERIODOS, IMP_NOTA_CUPOM, PERG_PERMITE_EST, DESC_CENTAVOS_VEND, 
MOSTRA_EST, ENT_NUMTICKET, SENHA_VENDA, COMANDO_EXCLUSAO, 
MOVIMENTA_CAIXA_FECHADO, DESC_PGTO_AVISTA, LANCA_ACRES, TICKET_AGRUPADO, 
VALIDA_CHEQUE, PERG_FUNCIONARIO, PERMITE_ENT_FORNEC, FUNC_POR_FORA, 
LIMITE_PGTO_CHQ, LANCAMENTO_PADRAO, PERMITE_FUNC, NAO_IMP_PROD_TRANSITO, 
ENTRADA_TRANSITO, SUGERE_ADM, SUGERE_ADM_DESABILITA, ALIQUOTA_IMP_FISCAL, 
HAB_DESC_TROCA, JOGA_PARA_SEGUNDA, AUTOMATICA, LANCAMENTO_PADRAO_IMPOSTOS, 
LANCAMENTO_PADRAO_IMPOSTO, LX_STATUS_LOJA, SEQUENCIA_PRE_VENDA, SEQUENCIA_DAV, 
SEQUENCIA_FATURA, SEQUENCIA_RECIBO, SEQUENCIA_PEDIDO, SEQUENCIA_VENDA_SAT, 
LANCAMENTO_PADRAO_CANCELAMENTO_B2C, LANCAMENTO_PADRAO_DEVOL_DINHEIRO, 
LANCAMENTO_PADRAO_ESTORNO_CARTAO
FROM LOJAS_VAREJO
WHERE filial = 'SP - CAMPO LIMPO'

UNION ALL

SELECT 
'000134' AS CODIGO_FILIAL, 'CAMPINAS - CENTRO' AS FILIAL, SEQUENCIA_TIKET, GERENTE_PERIODO, BENEFICIARIO_CHQ, 
CIDADE_CHQ, SENHA_DESISTENCIA_VENDA, NAO_ENVIA_ESTOQUE, SEQUENCIA_RESERVA, 
SEQUENCIA_SAIDAS, SEQUENCIA_ENTRADAS, SEQUENCIA_CLIENTES, NAO_GERA_GIRO, 
USA_CPF_RG_OU_CODIGO, DATA_PARA_TRANSFERENCIA, PERMANENCIA_TROCO, MOSTRA_FOTOS, 
TIRA_FOTO, VALIDA_PRODUTO, ABRE_VENDA_VENDEDOR, PEDE_SENHA_VEND, 
CPF_OBRIGATORIO, IMPRIME_ITEM_LANCADO, ACUMULA_ITEM_VENDA, SUSP_VENDA, 
TROCA_VOLTA_VENDA, LISTA_TIPO_PGTO_TICKET, SENHA_DESCONTO, DESC_CENTAVOS, 
FIXA_DESCONTO, PARCELAS_MESMO_DIA, ENT_SAI_CBAR, OBRIGA_TITULO, RODIZIO_FOTOS, 
DATAS_RESUMOS, DATAS_VENDEDORES, DESTACA_TROCA, DESCONTA_TROCA, MOSTRA_TICKET, 
SEQUENCIA_TICKET, PERG_IMP_ROMANEIOS, MOSTRA_NO_TICKET, 
IMPRIME_TICKETS_SUSPENSOS, PERG_IMP_TICKETS, MASCARA_CODIGO, JANELA_TROCO, 
PREVISAO_RETORNO, ALTERA_NA_LOJA, PARAMETRO_POR_LOJA, NOME_GERENTE_LOJA, 
COD_GERENTE_LOJA, COD_GERENTE_PERIODO, NOME_GERENTE_PERIODO, OCULTAR_FAIXA_PGTO, 
SENHA_TECNICA, CONTROLA_BAIXAS, USA_TICKET, SALDO_INICIAL, 
ACEITA_MAIS_PERIODOS, IMP_NOTA_CUPOM, PERG_PERMITE_EST, DESC_CENTAVOS_VEND, 
MOSTRA_EST, ENT_NUMTICKET, SENHA_VENDA, COMANDO_EXCLUSAO, 
MOVIMENTA_CAIXA_FECHADO, DESC_PGTO_AVISTA, LANCA_ACRES, TICKET_AGRUPADO, 
VALIDA_CHEQUE, PERG_FUNCIONARIO, PERMITE_ENT_FORNEC, FUNC_POR_FORA, 
LIMITE_PGTO_CHQ, LANCAMENTO_PADRAO, PERMITE_FUNC, NAO_IMP_PROD_TRANSITO, 
ENTRADA_TRANSITO, SUGERE_ADM, SUGERE_ADM_DESABILITA, ALIQUOTA_IMP_FISCAL, 
HAB_DESC_TROCA, JOGA_PARA_SEGUNDA, AUTOMATICA, LANCAMENTO_PADRAO_IMPOSTOS, 
LANCAMENTO_PADRAO_IMPOSTO, LX_STATUS_LOJA, SEQUENCIA_PRE_VENDA, SEQUENCIA_DAV, 
SEQUENCIA_FATURA, SEQUENCIA_RECIBO, SEQUENCIA_PEDIDO, SEQUENCIA_VENDA_SAT, 
LANCAMENTO_PADRAO_CANCELAMENTO_B2C, LANCAMENTO_PADRAO_DEVOL_DINHEIRO, 
LANCAMENTO_PADRAO_ESTORNO_CARTAO
FROM LOJAS_VAREJO
WHERE filial = 'SP - CAMPO LIMPO'

UNION ALL

SELECT 
'000135' AS CODIGO_FILIAL, 'RP - SH NOVO SHOPPING' AS FILIAL, SEQUENCIA_TIKET, GERENTE_PERIODO, BENEFICIARIO_CHQ, 
CIDADE_CHQ, SENHA_DESISTENCIA_VENDA, NAO_ENVIA_ESTOQUE, SEQUENCIA_RESERVA, 
SEQUENCIA_SAIDAS, SEQUENCIA_ENTRADAS, SEQUENCIA_CLIENTES, NAO_GERA_GIRO, 
USA_CPF_RG_OU_CODIGO, DATA_PARA_TRANSFERENCIA, PERMANENCIA_TROCO, MOSTRA_FOTOS, 
TIRA_FOTO, VALIDA_PRODUTO, ABRE_VENDA_VENDEDOR, PEDE_SENHA_VEND, 
CPF_OBRIGATORIO, IMPRIME_ITEM_LANCADO, ACUMULA_ITEM_VENDA, SUSP_VENDA, 
TROCA_VOLTA_VENDA, LISTA_TIPO_PGTO_TICKET, SENHA_DESCONTO, DESC_CENTAVOS, 
FIXA_DESCONTO, PARCELAS_MESMO_DIA, ENT_SAI_CBAR, OBRIGA_TITULO, RODIZIO_FOTOS, 
DATAS_RESUMOS, DATAS_VENDEDORES, DESTACA_TROCA, DESCONTA_TROCA, MOSTRA_TICKET, 
SEQUENCIA_TICKET, PERG_IMP_ROMANEIOS, MOSTRA_NO_TICKET, 
IMPRIME_TICKETS_SUSPENSOS, PERG_IMP_TICKETS, MASCARA_CODIGO, JANELA_TROCO, 
PREVISAO_RETORNO, ALTERA_NA_LOJA, PARAMETRO_POR_LOJA, NOME_GERENTE_LOJA, 
COD_GERENTE_LOJA, COD_GERENTE_PERIODO, NOME_GERENTE_PERIODO, OCULTAR_FAIXA_PGTO, 
SENHA_TECNICA, CONTROLA_BAIXAS, USA_TICKET, SALDO_INICIAL, 
ACEITA_MAIS_PERIODOS, IMP_NOTA_CUPOM, PERG_PERMITE_EST, DESC_CENTAVOS_VEND, 
MOSTRA_EST, ENT_NUMTICKET, SENHA_VENDA, COMANDO_EXCLUSAO, 
MOVIMENTA_CAIXA_FECHADO, DESC_PGTO_AVISTA, LANCA_ACRES, TICKET_AGRUPADO, 
VALIDA_CHEQUE, PERG_FUNCIONARIO, PERMITE_ENT_FORNEC, FUNC_POR_FORA, 
LIMITE_PGTO_CHQ, LANCAMENTO_PADRAO, PERMITE_FUNC, NAO_IMP_PROD_TRANSITO, 
ENTRADA_TRANSITO, SUGERE_ADM, SUGERE_ADM_DESABILITA, ALIQUOTA_IMP_FISCAL, 
HAB_DESC_TROCA, JOGA_PARA_SEGUNDA, AUTOMATICA, LANCAMENTO_PADRAO_IMPOSTOS, 
LANCAMENTO_PADRAO_IMPOSTO, LX_STATUS_LOJA, SEQUENCIA_PRE_VENDA, SEQUENCIA_DAV, 
SEQUENCIA_FATURA, SEQUENCIA_RECIBO, SEQUENCIA_PEDIDO, SEQUENCIA_VENDA_SAT, 
LANCAMENTO_PADRAO_CANCELAMENTO_B2C, LANCAMENTO_PADRAO_DEVOL_DINHEIRO, 
LANCAMENTO_PADRAO_ESTORNO_CARTAO
FROM LOJAS_VAREJO
WHERE filial = 'SP - CAMPO LIMPO'

---------------

SELECT * FROM TABELAS_PRECO WHERE TABELA LIKE '%CAMPO%'
select * from FORNECEDORES where COD_FORNECEDOR in ('000118','000135','000133','000134')
/* == TABELAS DISPONIVEIS

55
67
69

*/

INSERT INTO TABELAS_PRECO
(CODIGO_TAB_PRECO,TABELA,MOEDA,LANCAMENTO_TABELA,ATACADO_VAREJO,
STATUS,ENVIA_LOJA_VAREJO,ENVIA_LOJA_ATACADO, ENVIA_REPRESENTANTE, ENVIA_VAREJO_INTERNET, INATIVO, 
DATA_PARA_TRANSFERENCIA, PORCENTAGEM_TABELA_BASE, BLOQ_ATUALIZACAO_BASE, EMPRESA, LX_STATUS_REGISTRO)
VALUES 
('55','VENDAS_SP_LAPA','R$',CONVERT(VARCHAR,GETDATE(),112),1,
'A',1,0, 0, 0, 0, 
GETDATE(), 0.00000, 0, 1, 0),
('67','VENDAS_CAMPINAS_CENTRO','R$',CONVERT(VARCHAR,GETDATE(),112),1,
'A',1,0, 0, 0, 0, 
GETDATE(), 0.00000, 0, 1, 0),
('69','VENDAS_RP_SH_NOVO_SHOPP','R$',CONVERT(VARCHAR,GETDATE(),112),1,
'A',1,0, 0, 0, 0, 
GETDATE(), 0.00000, 0, 1, 0)

DELETE FROM PRODUTOS_PRECOS WHERE CODIGO_TAB_PRECO IN ('55','67','69')

begin tran
DELETE FROM PRODUTOS_PRECOS WHERE CODIGO_TAB_PRECO = '69' -- DELETA PRIMEIRO PRA NAO DAR PAU DE DUPLICIDADE DE PK
INSERT INTO PRODUTOS_PRECOS
(CODIGO_TAB_PRECO,
		PRODUTO,
		PRECO1,
		PRECO2,
		PRECO3,
		PRECO4,
		LIMITE_DESCONTO,
		PROMOCAO_DESCONTO,
		ULT_ATUALIZACAO,
		INICIO_PROMOCAO,
		FIM_PROMOCAO,
		DATA_PARA_TRANSFERENCIA,
		MARK_UP_PREVISTO,
		PROMOCAO_ATACADO,
		PRECO_LIQUIDO1,
		PRECO_LIQUIDO2,
		PRECO_LIQUIDO3,
		PRECO_LIQUIDO4,
		LX_STATUS_REGISTRO,
		PRECO1_ANTERIOR,
		DATA_CARGA_PRECOS)
SELECT	distinct
		'69' AS CODIGO_TAB_PRECO,
		PRODUTO,
		PRECO1,
		PRECO2,
		PRECO3,
		PRECO4,
		LIMITE_DESCONTO,
		PROMOCAO_DESCONTO,
		CONVERT(VARCHAR,GETDATE(),112) AS ULT_ATUALIZACAO,
		INICIO_PROMOCAO,
		FIM_PROMOCAO,
		'19000101' AS DATA_PARA_TRANSFERENCIA,
		MARK_UP_PREVISTO,
		PROMOCAO_ATACADO,
		PRECO_LIQUIDO1,
		PRECO_LIQUIDO2,
		PRECO_LIQUIDO3,
		PRECO_LIQUIDO4,
		LX_STATUS_REGISTRO,
		PRECO1_ANTERIOR,
		DATA_CARGA_PRECOS
FROM PRODUTOS_PRECOS WHERE CODIGO_TAB_PRECO='11'

commit

-----------------

INSERT INTO  LOJA_OPERACOES_VENDA
(OPERACAO_VENDA
,DESC_OPERACAO_VENDA
,CADASTRA_CLIENTE
,DESCONTO_OPERACAO
,DESCONTO_POR_ITEM
,LIMITE_DESCONTO
,USA_TABELA_PADRAO
,CODIGO_TAB_PRECO
,ALTERA_TABELA
,ALTERA_PRECO
,ALTERA_DESCONTO
,PORCENTAGEM_ABATER_COMISSAO
,PGTOS_EM_ABERTO
,OPERACAO_INATIVA
,DATA_ATIVACAO
,DATA_DESATIVACAO
,DATA_PARA_TRANSFERENCIA
,LIMITE_DESCONTO_GERENTE
,ALTERA_DESCONTO_PGTO
,ALTERA_PRECO_BRUTO
,DESCONTO_ITEM_VENDA
,DESCONTO_ITEM_TROCA
,LIMITE_DESCONTO_ITEM
,LIMITE_DESCONTO_ITEM_GERENTE
,LX_STATUS_REGISTRO
,ID_OPERACAO_VENDA

)

SELECT 
'055' AS OPERACAO_VENDA
,'OPERACAO DE VENDA SP - LAPA' AS DESC_OPERACAO_VENDA
,CADASTRA_CLIENTE
,DESCONTO_OPERACAO
,DESCONTO_POR_ITEM
,LIMITE_DESCONTO
,USA_TABELA_PADRAO
,'55' AS CODIGO_TAB_PRECO
,ALTERA_TABELA
,ALTERA_PRECO
,ALTERA_DESCONTO
,PORCENTAGEM_ABATER_COMISSAO
,PGTOS_EM_ABERTO
,OPERACAO_INATIVA
,DATA_ATIVACAO
,DATA_DESATIVACAO
,DATA_PARA_TRANSFERENCIA
,LIMITE_DESCONTO_GERENTE
,ALTERA_DESCONTO_PGTO
,ALTERA_PRECO_BRUTO
,DESCONTO_ITEM_VENDA
,DESCONTO_ITEM_TROCA
,LIMITE_DESCONTO_ITEM
,LIMITE_DESCONTO_ITEM_GERENTE
,LX_STATUS_REGISTRO
,ID_OPERACAO_VENDA
FROM LOJA_OPERACOES_VENDA 
WHERE OPERACAO_VENDA = '056'

UNION ALL

SELECT 
'067' AS OPERACAO_VENDA
,'OPERACAO DE VENDA CAMPINAS - CENTRO' AS DESC_OPERACAO_VENDA
,CADASTRA_CLIENTE
,DESCONTO_OPERACAO
,DESCONTO_POR_ITEM
,LIMITE_DESCONTO
,USA_TABELA_PADRAO
,'67' AS CODIGO_TAB_PRECO
,ALTERA_TABELA
,ALTERA_PRECO
,ALTERA_DESCONTO
,PORCENTAGEM_ABATER_COMISSAO
,PGTOS_EM_ABERTO
,OPERACAO_INATIVA
,DATA_ATIVACAO
,DATA_DESATIVACAO
,DATA_PARA_TRANSFERENCIA
,LIMITE_DESCONTO_GERENTE
,ALTERA_DESCONTO_PGTO
,ALTERA_PRECO_BRUTO
,DESCONTO_ITEM_VENDA
,DESCONTO_ITEM_TROCA
,LIMITE_DESCONTO_ITEM
,LIMITE_DESCONTO_ITEM_GERENTE
,LX_STATUS_REGISTRO
,ID_OPERACAO_VENDA
FROM LOJA_OPERACOES_VENDA 
WHERE OPERACAO_VENDA = '056'

UNION ALL

SELECT 
'069' AS OPERACAO_VENDA
,'OPERACAO DE VENDA RP - SH NOVO SHOPPING' AS DESC_OPERACAO_VENDA
,CADASTRA_CLIENTE
,DESCONTO_OPERACAO
,DESCONTO_POR_ITEM
,LIMITE_DESCONTO
,USA_TABELA_PADRAO
,'69' AS CODIGO_TAB_PRECO
,ALTERA_TABELA
,ALTERA_PRECO
,ALTERA_DESCONTO
,PORCENTAGEM_ABATER_COMISSAO
,PGTOS_EM_ABERTO
,OPERACAO_INATIVA
,DATA_ATIVACAO
,DATA_DESATIVACAO
,DATA_PARA_TRANSFERENCIA
,LIMITE_DESCONTO_GERENTE
,ALTERA_DESCONTO_PGTO
,ALTERA_PRECO_BRUTO
,DESCONTO_ITEM_VENDA
,DESCONTO_ITEM_TROCA
,LIMITE_DESCONTO_ITEM
,LIMITE_DESCONTO_ITEM_GERENTE
,LX_STATUS_REGISTRO
,ID_OPERACAO_VENDA
FROM LOJA_OPERACOES_VENDA 
WHERE OPERACAO_VENDA = '056'

--SELECT * 
--FROM LOJA_OPERACOES_VENDA 
--WHERE OPERACAO_VENDA IN ('055','067','069')

