/*
		TABELA --> CSM_TRANSITO_NOTAS_LOG_ITENS
		------------------ CHAVE PRIMARIA DA TABELA CSM_TRANSITO_NOTAS
		NOME_CLIFOR 
		NF_ENTRADA
		SERIE_NF_ENTRADA
		------------------- CHAVE DA NOTA DE SAIDA (DADOS PARA RELACIONAR COM A CAPA FATURAMENTO)
		NF_SAIDA INDICE
		SERIE_NF INDICE
		FILIAL (CD BARRA VELHA) INDICE
		-------------------
		PEDIDO_COMPRA (PEDIDO DA ESTOQUE_PROD_ENT DA NOTA DE ENTRADA)
		CHAVE_NFE (CHAVE NFE DA NOTA DE SAIDA) UNIQUE 
		ORIGEM ('E')
		DATA_NF (DATA DE EMISSAO DA NOTA DE SAIDA) INDICE
		PRODUTO (PRODUTO PEGA DA FATURAMENTO_PROD DA NOTA DE SAIDA)
		PRECO1_CHEIO (PRODUTOS_PRECOS TABELA 01 - VENDA ORIGINAL)
		PRECO1_MAJORADO (PRECO UNITARIO DA NOTA FATURAMENTO_PROD JA MAJORADO)
		PERCENTUAL_MAJORAMENTO (VARIAVEL @fator_preco 0,75)
		DATA_LOG - INDICE (TIMESTAMP) 
*/

USE [CAEDU]
GO
CREATE TABLE [dbo].[CSM_TRANSITO_NOTAS_LOG_ITENS](
	[NOME_CLIFOR] [varchar](25) NOT NULL,
	[NF_ENTRADA] [char](15) NOT NULL,
	[SERIE_NF_ENTRADA] [varchar](6) NOT NULL,
	[FILIAL] [varchar](25) NOT NULL,
	[SERIE_NF] [varchar](6) NOT NULL,
	[NF_SAIDA] [varchar](15) NOT NULL,
	[PEDIDO_COMPRA] [char](8) null,
	[CHAVE_NFE] [varchar](44) NULL,
	[ORIGEM] [char] (1) null,
	[DATA_NF] [datetime] NOT null,
	[PRODUTO] [char](12) NOT NULL,
	[COR_PRODUTO] [char](10) NOT NULL,
	[PRECO1_CHEIO] [numeric](14,2) NULL,
	[PRECO1_MAJORADO] [numeric](14,2) NULL,
	[PERCENTUAL_MAJORAMENTO] [numeric](6,2) NULL,
	[DATA_LOG] [datetime] not null
	)
GO
ALTER TABLE [dbo].[CSM_TRANSITO_NOTAS_LOG_ITENS]
	ADD constraint DF_DATA_LOG_CSM_TRANSITO_NOTAS_LOG_ITENS DEFAULT (GETDATE()) FOR DATA_LOG
GO

/*INDICE PRA RELACIONAR A CAPA DA NOTA DE ENTRADAS*/
CREATE INDEX idx_csm_transito_notas_log_itens_nf_entrada
ON [CSM_TRANSITO_NOTAS_LOG_ITENS] (NOME_CLIFOR,NF_ENTRADA,SERIE_NF_ENTRADA)
GO
/*INDICE PARA RELACIONAR A CAPA DA NOTA DE SAIDA*/
CREATE INDEX idx_csm_transito_notas_log_itens_nf_saida
ON [CSM_TRANSITO_NOTAS_LOG_ITENS] (FILIAL,NF_SAIDA,SERIE_NF)
GO
/*INDICE PARA PEDIDO*/
CREATE INDEX idx_csm_transito_notas_log_itens_pedido
ON [CSM_TRANSITO_NOTAS_LOG_ITENS] (PEDIDO_COMPRA)
GO
/*INDICE PARA chave_nfe*/
CREATE INDEX idx_csm_transito_notas_log_itens_chave_nfe
ON [CSM_TRANSITO_NOTAS_LOG_ITENS] (CHAVE_NFE)
GO
/*INDICE PRODUTO E COR*/
CREATE INDEX idx_csm_transito_notas_log_itens_nf_produto_cor
ON [CSM_TRANSITO_NOTAS_LOG_ITENS] (PRODUTO,COR_PRODUTO)
GO
/*INDICE PARA DATA NF*/
CREATE INDEX idx_csm_transito_notas_log_itens_data_nf
ON [CSM_TRANSITO_NOTAS_LOG_ITENS] (DATA_NF)
GO




