
CREATE TABLE [PDA_WMS_TB_REC_NF_DOCA]
(
	[PEDIDO] [varchar](10) NULL,
	[NOTAFISCAL] [varchar](10) NULL,
	[DT_ENTRADA] [datetime] NULL,
	[ID_USUARIO] [int] NULL
) 
GO
CREATE NONCLUSTERED INDEX [IX_REC_NF_DOC_DT] ON [PDA_WMS_TB_REC_NF_DOCA] 
(
	[DT_ENTRADA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_REC_NF_DOCA] ON [PDA_WMS_TB_REC_NF_DOCA] 
(
	[PEDIDO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE TABLE [PDA_WMS_TB_REC_NF_ADM]
(
	[PEDIDO] [varchar](10) NULL,
	[NOTAFISCAL] [varchar](10) NULL,
	[DT_ENTRADA] [datetime] NULL,
	[ID_USUARIO] [int] NULL
)
GO
CREATE NONCLUSTERED INDEX [IX_REC_NF_ADM] ON [PDA_WMS_TB_REC_NF_ADM] 
(
	[PEDIDO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_REC_NF_ADM_DT] ON [PDA_WMS_TB_REC_NF_ADM] 
(
	[DT_ENTRADA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


