USE [CAEDU]
GO

/****** Object:  Table [dbo].[ENTRADAS_ITEM]    Script Date: 29/03/2021 15:21:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CGP_ENTRADAS_ITEM_LOG](
	[ID] INT IDENTITY(1,1) NOT NULL,
	[CLASSIF_FISCAL] [char](10) NOT NULL,
	[CODIGO_FISCAL_OPERACAO] [char](4) NOT NULL,
	[CODIGO_ITEM] [varchar](50) NOT NULL,
	[COD_TABELA_FILHA] [char](1) NULL,
	[COMISSAO_ITEM] [numeric](8, 5) NULL,
	[COMISSAO_ITEM_GERENTE] [numeric](8, 5) NULL,
	[CONTA_CONTABIL] [varchar](20) NULL,
	[DESCONTO_ITEM] [numeric](15, 5) NULL,
	[DESCRICAO_ITEM] [varchar](80) NOT NULL,
	[FAIXA] [char](1) NOT NULL,
	[ID_EXCECAO_IMPOSTO] [int] NULL,
	[INDICADOR_CFOP] [tinyint] NULL,
	[ITEM_IMPRESSAO] [char](4) NOT NULL,
	[NF_ENTRADA] [char](15) NOT NULL,
	[NOME_CLIFOR] [varchar](25) NOT NULL,
	[PESO] [numeric](9, 5) NULL,
	[PORCENTAGEM_ITEM_RATEIO] [numeric](13, 10) NULL,
	[PRECO_UNITARIO] [numeric](15, 5) NULL,
	[QTDE_DEVOLVIDA] [numeric](9, 3) NULL,
	[QTDE_ITEM] [numeric](9, 3) NULL,
	[QTDE_RETORNAR_BENEFICIAMENTO] [numeric](9, 3) NULL,
	[SERIE_NF_ENTRADA] [varchar](6) NOT NULL,
	[SUB_ITEM_TAMANHO] [int] NOT NULL,
	[TRIBUT_ICMS] [char](3) NOT NULL,
	[TRIBUT_ORIGEM] [char](3) NOT NULL,
	[UNIDADE] [varchar](5) NULL,
	[VALOR_ITEM] [numeric](14, 2) NULL,
	[REFERENCIA] [varchar](50) NULL,
	[REFERENCIA_ITEM] [varchar](12) NULL,
	[REFERENCIA_PEDIDO] [varchar](12) NULL,
	[DIVERGENTE] [tinyint] NULL,
	[TIMESTAMP] [varchar](25) NULL,
	[REFERENCIA_ENTREGA_PEDIDO] [datetime] NULL,
	[VALOR_ENCARGOS] [numeric](14, 2) NULL,
	[VALOR_DESCONTOS] [numeric](14, 2) NULL,
	[VALOR_ENCARGOS_IMPORTACAO] [numeric](14, 2) NULL,
	[NAO_SOMA_VALOR] [bit] NOT NULL,
	[RATEIO_FILIAL] [varchar](15) NULL,
	[RATEIO_CENTRO_CUSTO] [varchar](15) NULL,
	[COD_REPRESENTANTE] [char](6) NULL,
	[COD_REPRESENTANTE_GERENTE] [char](6) NULL,
	[VALOR_ENCARGOS_ADUANEIROS] [numeric](14, 2) NOT NULL,
	[PORC_ITEM_RATEIO_FRETE] [numeric](13, 10) NULL,
	[ITEM_NFE] [smallint] NULL,
	[MPADRAO_SEGURO_ITEM] [numeric](14, 2) NOT NULL,
	[MPADRAO_FRETE_ITEM] [numeric](14, 2) NOT NULL,
	[MPADRAO_ENCARGO_ITEM] [numeric](14, 2) NOT NULL,
	[DATA_PARA_TRANSFERENCIA] [datetime] NULL,
	[ORIGEM_ITEM] [char](1) NULL,
	[INDICA_PRODUTO_PROCESSO] [bit] NOT NULL,
	[PRECO_UNITARIO_ORIGINAL] [numeric](15, 5) NOT NULL,
	[CTB_TIPO_OPERACAO] [int] NULL,
	[ENCARGOS_IMPORT_DIGITADO] [bit] NOT NULL,
	[ID_SUB_PROJETO] [int] NULL,
	[ID_CEST_NCM] [int] NULL,
	[DATA_ACERTO_CONSIGNACAO] [datetime] NULL,
	[DATA_DELETE] DATETIME NOT NULL DEFAULT (GETDATE())
	CONSTRAINT PK_CGP_ENTRADAS_ITEM_LOG PRIMARY KEY (ID)
 ) ON [PRIMARY]
GO

CREATE INDEX [IDX_ENTRADAS_ITEM_LOG] ON  dbo.CGP_ENTRADAS_ITEM_LOG
(
	[NF_ENTRADA] ASC,
	[SERIE_NF_ENTRADA] ASC,
	[ITEM_IMPRESSAO] ASC,
	[SUB_ITEM_TAMANHO] ASC,
	[NOME_CLIFOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, 
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 98) ON [PRIMARY]
go

 CREATE INDEX [IDX_CGP_ENTRADAS_ITEM_LOG_DATA_DELETE] ON  dbo.CGP_ENTRADAS_ITEM_LOG
(
	[DATA_DELETE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO





