CREATE TABLE DBO.CGP_LOG_ALTERACAO_PEDIDO (
    ID             INT IDENTITY PRIMARY KEY,
    PEDIDO         CHAR(8)  NOT NULL,
    CAMPO          VARCHAR(100)  NOT NULL,
    VALOR_ANTERIOR VARCHAR(200),
    VALOR_NOVO     VARCHAR(200),
    USUARIO        VARCHAR(100)  NOT NULL,
    DATA_HORA      DATETIME  DEFAULT GETDATE(),
    ARQUIVO_ORIGEM VARCHAR(200)
)

