select A.ROMANEIO_PRODUTO, A.FILIAL, A.FILIAL_ORIGEM, A.ROMANEIO_NF_SAIDA, A.EMISSAO, A.ENTRADA_CONFERIDA, A.DATA_ENTRADA_CONFERIDA,
B.PRODUTO, B.COR_PRODUTO, B.QTDE_ENTRADA, B.PRECO1, B.VALOR, P.GRIFFE, P.LINHA, P.GRUPO_PRODUTO, P.SUBGRUPO_PRODUTO, P.GRADE, P.DESC_PRODUTO
from LOJA_ENTRADAS A
INNER JOIN LOJA_ENTRADAS_PRODUTO B 
	ON B.ROMANEIO_PRODUTO = A.ROMANEIO_PRODUTO AND B.FILIAL = A.FILIAL
inner join PRODUTOS P ON P.PRODUTO = B.PRODUTO
where A.FILIAL = 'SP - SAPOPEMBA'