select A.ROMANEIO_PRODUTO, A.FILIAL, A.FILIAL_ORIGEM, A.ROMANEIO_NF_SAIDA, A.EMISSAO, A.ENTRADA_CONFERIDA, A.DATA_ENTRADA_CONFERIDA,
B.PRODUTO, B.COR_PRODUTO, B.QTDE_ENTRADA, B.PRECO1, B.VALOR, P.GRIFFE, P.LINHA, P.GRUPO_PRODUTO, P.SUBGRUPO_PRODUTO, P.GRADE, P.DESC_PRODUTO,
B.EN1, B.EN2, B.EN3, B.EN4, B.EN5, B.EN6, B.EN7, B.EN8, B.EN9, B.EN10, B.EN11, B.EN12, B.EN13, B.EN14, B.EN15, B.EN16
from LOJA_ENTRADAS A
INNER JOIN LOJA_ENTRADAS_PRODUTO B 
	ON B.ROMANEIO_PRODUTO = A.ROMANEIO_PRODUTO AND B.FILIAL = A.FILIAL
inner join PRODUTOS P ON P.PRODUTO = B.PRODUTO
where A.FILIAL = 'SAO MATHEUS' AND (A.EMISSAO BETWEEN '20190601' AND '20191231')
order by EMISSAO, ROMANEIO_PRODUTO