/*
exclusão de caixas já processadas do e-commerce
*/

SET NOCOUNT ON

DECLARE @TABCAIXAS TABLE (ID INT IDENTITY(1,1), CAIXA VARCHAR(8))
insert into @TABCAIXAS (CAIXA)
select  caixa 
from PDA_WMS_TRANSFERE_ESTOQUE_LOJA_VIRTUAL 
where caixa_excluida = 0 and flg_processamento=1 and data_processamento is not null


DECLARE @I INT = 1
DECLARE @TOT INT 

DECLARE @CAIXA VARCHAR(8)
DECLARE @PEDIDO VARCHAR(11)

SELECT @TOT = MAX(ID) FROM @TABCAIXAS

WHILE @I<=@TOT
BEGIN
	SELECT @CAIXA = CAIXA, @PEDIDO = 'CX-'+CAIXA	
	FROM @TABCAIXAS WHERE ID = @I

	if exists(select 1 from faturamento_prod where caixa = @CAIXA)
	BEGIN
		PRINT 'JÁ EXISTE FATURAMENTO FEITO PARA A CAIXA = '+@CAIXA
	END
	
	ELSE
	BEGIN
		-- DELETA VENDAS_PROD_EMBALADO
		DELETE FROM VENDAS_PROD_EMBALADO WHERE CAIXA = @CAIXA

		/*
		-- DELETA VENDAS_PRODUTO
		DELETE FROM VENDAS_PRODUTO WHERE PEDIDO = @PEDIDO

		-- DELETA VENDAS
		DELETE FROM VENDAS
		WHERE PEDIDO = @PEDIDO

		-- DELETA FATURAMENTO_CAIXAS
		DELETE 
		FROM FATURAMENTO_CAIXAS 
		WHERE CAIXA = @CAIXA
		*/

		UPDATE PDA_WMS_TRANSFERE_ESTOQUE_LOJA_VIRTUAL SET caixa_excluida=1
		WHERE CAIXA = @CAIXA

	END
	 
	--INCREMENTA O CONTADOR DE REGISTROS (REGNUM)
	PRINT 'LINHA ' + CONVERT(VARCHAR,@I) +' DE '+CONVERT(VARCHAR,@TOT)
	SET @I = @I + 1

END

SET NOCOUNT OFF


