select  'SELECT DISTINCT COMANDO FROM LX_PROCESSO_LOG WHERE COMANDO LIKE ' + CHAR(39) + '%' + RTRIM(F.NF_SAIDA) + '%' + CHAR(39) + ' AND DATA_LOG >= ' + CHAR(39) + '20191030'+ CHAR(39), 
		F.FILIAL, 
		F.NF_SAIDA, 
		F.NOME_CLIFOR
from faturamento F
INNER JOIN FATURAMENTO_PROD FP 
	ON FP.FILIAL=F.FILIAL AND FP.NF_SAIDA=F.NF_SAIDA AND FP.SERIE_NF=F.SERIE_NF
INNER JOIN PRODUTOS P 
	ON P.PRODUTO = FP.PRODUTO
INNER JOIN PRODUTO_CORES pc 
	on pc.PRODUTO = fp.PRODUTO and pc.COR_PRODUTO = fp.COR_PRODUTO
where F.filial = 'CD CAJAMAR' 
AND CAST(F.NF_SAIDA AS INT) IN
(23558,23557,23559,23561,23564,23565,23567,23570,3843,42976,42958,3836,41945,3827)
GROUP BY 
		F.FILIAL, 
		F.NF_SAIDA, 
		F.NOME_CLIFOR


SELECT DISTINCT COMANDO FROM LX_PROCESSO_LOG WHERE COMANDO LIKE '%000023567%' AND DATA_LOG >= '20191030'
SELECT DISTINCT COMANDO FROM LX_PROCESSO_LOG WHERE COMANDO LIKE '%000023570%' AND DATA_LOG >= '20191030'
SELECT DISTINCT COMANDO FROM LX_PROCESSO_LOG WHERE COMANDO LIKE '%000023564%' AND DATA_LOG >= '20191030'
SELECT DISTINCT COMANDO FROM LX_PROCESSO_LOG WHERE COMANDO LIKE '%000023565%' AND DATA_LOG >= '20191030'
SELECT DISTINCT COMANDO FROM LX_PROCESSO_LOG WHERE COMANDO LIKE '%000023559%' AND DATA_LOG >= '20191030'
SELECT DISTINCT COMANDO FROM LX_PROCESSO_LOG WHERE COMANDO LIKE '%000023561%' AND DATA_LOG >= '20191030'
SELECT DISTINCT COMANDO FROM LX_PROCESSO_LOG WHERE COMANDO LIKE '%000023557%' AND DATA_LOG >= '20191030'
SELECT DISTINCT COMANDO FROM LX_PROCESSO_LOG WHERE COMANDO LIKE '%000023558%' AND DATA_LOG >= '20191030'
GO

--LX_GERA_TRANSFERENCIA_AUTOMATICA @FILIAL = 'CD CAJAMAR', @ROMANEIO_PRODUTO = '000023567', @FILIAL_DESTINO = 'CRUZEIRO', @SERIE_NF = '1', @ORIGEM = 'F', @EXCLUSAO = 'S'
--GO
--LX_GERA_TRANSFERENCIA_AUTOMATICA @FILIAL = 'CD CAJAMAR', @ROMANEIO_PRODUTO = '000023570', @FILIAL_DESTINO = 'CRUZEIRO', @SERIE_NF = '1', @ORIGEM = 'F', @EXCLUSAO = 'S'
--GO

LX_GERA_TRANSFERENCIA_AUTOMATICA @FILIAL = 'CD CAJAMAR', @ROMANEIO_PRODUTO = '000023564', @FILIAL_DESTINO = 'GUARATINGUETA', @SERIE_NF = '1', @ORIGEM = 'F', @EXCLUSAO = 'S'
GO

--LX_GERA_TRANSFERENCIA_AUTOMATICA @FILIAL = 'CD CAJAMAR', @ROMANEIO_PRODUTO = '000023565', @FILIAL_DESTINO = 'GUARATINGUETA', @SERIE_NF = '1', @ORIGEM = 'F', @EXCLUSAO = 'S'
--GO
--LX_GERA_TRANSFERENCIA_AUTOMATICA @FILIAL = 'CD CAJAMAR', @ROMANEIO_PRODUTO = '000023559', @FILIAL_DESTINO = 'PINDAMONHANGABA', @SERIE_NF = '1', @ORIGEM = 'F', @EXCLUSAO = 'S'
--GO
--LX_GERA_TRANSFERENCIA_AUTOMATICA @FILIAL = 'CD CAJAMAR', @ROMANEIO_PRODUTO = '000023561', @FILIAL_DESTINO = 'PINDAMONHANGABA', @SERIE_NF = '1', @ORIGEM = 'F', @EXCLUSAO = 'S'
--GO
--LX_GERA_TRANSFERENCIA_AUTOMATICA @FILIAL = 'CD CAJAMAR', @ROMANEIO_PRODUTO = '000023557', @FILIAL_DESTINO = 'TAUBATE', @SERIE_NF = '1', @ORIGEM = 'F', @EXCLUSAO = 'S'
--GO
--LX_GERA_TRANSFERENCIA_AUTOMATICA @FILIAL = 'CD CAJAMAR', @ROMANEIO_PRODUTO = '000023558', @FILIAL_DESTINO = 'TAUBATE', @SERIE_NF = '1', @ORIGEM = 'F', @EXCLUSAO = 'S'
--GO


SELECT * FROM CM_DATA_FECHAMENTO WHERE FILIAL IN (
'TAUBATE'
,'PINDAMONHANGABA'
,'GUARATINGUETA'
,'CRUZEIRO')


UPDATE CM_DATA_FECHAMENTO 
SET DATA_SALDO_PA = '20191031'
WHERE FILIAL IN (
'TAUBATE'
,'PINDAMONHANGABA'
,'GUARATINGUETA'
,'CRUZEIRO')
