

ALTER FUNCTION [dbo].[FX_VAL_ICMS_ANTECIPADO](	@EMPRESA 				INT, 
												@LANCAMENTO 			INT,
												@CAMPO 					TINYINT,
												@CFOP                   CHAR(4),
												@REFERENCIA				VARCHAR(50)) /*#1#*/
------------------------------------------------------------------------------------------------------------------------------------------------
-- 29/11/2024 - CARLOS ALBERTO      - LINXERP-21211  - #3# - 02.24.020 - AJUSTE NA FÓRMULA, PARA CONSIDERAR O VALOR DE IMPOSTO AGREGADO, ENCARGOS, SEGURO, FRETE E DESCONTO
-- 18/11/2024 - JULIANA NASCIMENTO  - LINXERP-21061  - #2# - 02.24.020 - AJUSTE NA GERAÇÃO C197 PARA SOMAR O IPI
-- 07/10/2024 - DARIO SILVA         - PRODSHOP-25246 - #1# - 02.24.010 - AJUSTE NA GERAÇÃO C197 / E111 
------------------------------------------------------------------------------------------------------------------------------------------------

RETURNS NUMERIC(14,2)

AS
BEGIN
	/*
	@CAMPO	1 - VALOR_IMPOSTO
			2 - VALOR_IMPOSTO_ESPELHO
			3 - VALOR_IMPOSTO_CALC
	*/

	DECLARE	@SUM				NUMERIC(14,2),
			@SUM_BASE			NUMERIC(14,2),
			@RETORNO			NUMERIC(14,2),
			@ALIQUOTA_INTERNA	NUMERIC(14,2);
	
	IF ISNULL(@SUM,0) = 0
		SELECT	@SUM=SUM(CASE WHEN @CAMPO=3 THEN A.VALOR_IMPOSTO_CALC 
							 WHEN @CAMPO=2 THEN A.VALOR_IMPOSTO_ESPELHO 
							 ELSE A.VALOR_IMPOSTO END),
				@SUM_BASE=SUM(/*CASE WHEN @CAMPO=3 THEN A.BASE_IMPOSTO_CALC 
							 WHEN @CAMPO=2 THEN A.BASE_IMPOSTO_ESPELHO 
							 /*#3#*/
							 ELSE A.BASE_IMPOSTO END */
							 EI.VALOR_ITEM + (ISNULL(I.VALOR_IMPOSTO_ESPELHO,0) + 
											  ISNULL(B.FRETE *  ( EI.PORCENTAGEM_ITEM_RATEIO ) / 100, 0) + 
											  ISNULL(B.SEGURO * ( EI.PORCENTAGEM_ITEM_RATEIO ) / 100, 0) + 
											  ISNULL(B.ENCARGO *( EI.PORCENTAGEM_ITEM_RATEIO ) / 100, 0)) - 
											  ISNULL(CASE WHEN ISNULL(EI.VALOR_DESCONTOS,0) = 0 THEN (B.DESCONTO * (EI.PORCENTAGEM_ITEM_RATEIO) / 100) ELSE EI.VALOR_DESCONTOS END,0)), 
							/*#3#*/
				@ALIQUOTA_INTERNA = MIN(AL.ICMS_ENTRADA) 
		FROM ENTRADAS_IMPOSTO A (NOLOCK) 
		INNER JOIN ENTRADAS B (NOLOCK) 
				ON	A.NF_ENTRADA		= B.NF_ENTRADA 			AND 
					A.NOME_CLIFOR		= B.NOME_CLIFOR 		AND 
					A.SERIE_NF_ENTRADA	= B.SERIE_NF_ENTRADA
		INNER JOIN FILIAIS AS F (NOLOCK) 
				ON B.FILIAL = F.FILIAL 
		INNER JOIN CADASTRO_CLI_FOR AS CCF (NOLOCK) 
				ON F.MATRIZ_FISCAL = CCF.NOME_CLIFOR 
		INNER JOIN CADASTRO_CLI_FOR AS T (NOLOCK) 
				ON A.NOME_CLIFOR = T.NOME_CLIFOR  
		INNER JOIN UNIDADES_FEDERACAO_ICMS AS AL (NOLOCK) 
				ON AL.UF = CCF.UF AND AL.UF_DESTINO = CCF.UF
/*#1#*/	INNER JOIN ENTRADAS_ITEM EI (NOLOCK)
				ON B.NOME_CLIFOR = EI.NOME_CLIFOR
				AND B.NF_ENTRADA = EI.NF_ENTRADA
				AND B.SERIE_NF_ENTRADA = EI.SERIE_NF_ENTRADA
				AND A.ITEM_IMPRESSAO = EI.ITEM_IMPRESSAO
				AND A.SUB_ITEM_TAMANHO = EI.SUB_ITEM_TAMANHO
/*#2#*/	LEFT JOIN ENTRADAS_IMPOSTO I (NOLOCK)
				ON A.NOME_CLIFOR = I.NOME_CLIFOR
				AND A.NF_ENTRADA = I.NF_ENTRADA
				AND A.SERIE_NF_ENTRADA = I.SERIE_NF_ENTRADA
				AND A.ITEM_IMPRESSAO = I.ITEM_IMPRESSAO
				AND A.SUB_ITEM_TAMANHO = I.SUB_ITEM_TAMANHO
				AND I.ID_IMPOSTO = 2
WHERE	B.EMPRESA = @EMPRESA 							AND 
				B.CTB_LANCAMENTO = @LANCAMENTO 					AND 
				A.ID_IMPOSTO = 1								AND
				EI.CODIGO_FISCAL_OPERACAO = ISNULL(@CFOP,EI.CODIGO_FISCAL_OPERACAO)	AND 
		/*#3#*/
		--(CASE WHEN EI.REFERENCIA IS NULL OR EI.REFERENCIA =  '' THEN EI.CODIGO_ITEM
		--		ELSE LEFT(EI.CODIGO_ITEM, LEN(EI.REFERENCIA)) 
		--END = @REFERENCIA OR @REFERENCIA IS NULL); /*#2#*/
				(EI.CODIGO_ITEM = @REFERENCIA OR @REFERENCIA IS NULL)
		/*#3#*/
/*#1#*/
	IF ISNULL(@SUM,0) > 0
		BEGIN 
			SET @RETORNO = ROUND((@SUM_BASE * (@ALIQUOTA_INTERNA/100)), 2) - @SUM
		END;

	IF ISNULL(@RETORNO, 0) < 0
		SET @RETORNO = 0.00;

	RETURN ISNULL(@RETORNO, 0);

END;
