/*
SELECT FATURAMENTO_ENTRADA_DEVOLUCAO.FILIAL,
       FATURAMENTO_ENTRADA_DEVOLUCAO.NF_SAIDA,
       FATURAMENTO_ENTRADA_DEVOLUCAO.SERIE_NF,
       FATURAMENTO_ENTRADA_DEVOLUCAO.ITEM_IMPRESSAO_SAIDA,
       FATURAMENTO_ENTRADA_DEVOLUCAO.SUB_ITEM_SAIDA,
       FATURAMENTO_ENTRADA_DEVOLUCAO.NOME_CLIFOR,
       FATURAMENTO_ENTRADA_DEVOLUCAO.NF_ENTRADA,
       FATURAMENTO_ENTRADA_DEVOLUCAO.SERIE_NF_ENTRADA,
       FATURAMENTO_ENTRADA_DEVOLUCAO.ITEM_IMPRESSAO_ENTRADA,
       FATURAMENTO_ENTRADA_DEVOLUCAO.SUB_ITEM_ENTRADA,
       FATURAMENTO_ENTRADA_DEVOLUCAO.ORIGEM_ENTRADA_SAIDA,
       FATURAMENTO_ENTRADA_DEVOLUCAO.QTDE_DEVOLVIDA,
       QTDE_DISPONIVEL=(FATURAMENTO_ITEM.QTDE_ITEM-FATURAMENTO_ITEM.QTDE_DEVOLVIDA),
       FATURAMENTO.EMISSAO,
       FATURAMENTO_ITEM.CODIGO_ITEM,
       FATURAMENTO_ITEM.DESCRICAO_ITEM,
       FATURAMENTO_ITEM.MPADRAO_PRECO_UNITARIO AS PRECO_UNITARIO,
       FATURAMENTO_ITEM.DESCONTO_ITEM,
       FATURAMENTO_ITEM.UNIDADE,
       VALOR = (FATURAMENTO_ENTRADA_DEVOLUCAO.QTDE_DEVOLVIDA*FATURAMENTO_ITEM.MPADRAO_PRECO_UNITARIO),
       FATURAMENTO_ITEM.CLASSIF_FISCAL,
       FATURAMENTO_ITEM.TRIBUT_ORIGEM,
       FATURAMENTO_ITEM.TRIBUT_ORIGEM,
       FATURAMENTO_ITEM.CONTA_CONTABIL,
       FATURAMENTO_ITEM.INDICADOR_CFOP,
       FATURAMENTO_ITEM.TRIBUT_ICMS,
       FATURAMENTO_ITEM.UNIDADE,
       CONVERT(DECIMAL, 1) AS FATOR_CONVERSAO_UNIDADE,
       DBO.FX_PRODUCAO_PRECO(CAST((DBO.FX_PRODUCAO_PRECO(FATURAMENTO_ITEM.TIMESTAMP, 'F') * POWER((CASE
                                                                                                       WHEN ISNULL(FATURAMENTO.CAMBIO_NA_DATA, 0) = 0 THEN 1
                                                                                                       ELSE FATURAMENTO.CAMBIO_NA_DATA
                                                                                                   END),(CASE
                                                                                                             WHEN DBO.FX_PARAMETRO('CAMBIO_NA_MOEDA_PADRAO') = '.F.' THEN -1
                                                                                                             ELSE 1
                                                                                                         END)))AS NUMERIC(14, 2)), 'T') AS TIMESTAMP,
       FATURAMENTO_ITEM.COMISSAO_ITEM,
       FATURAMENTO_ITEM.COMISSAO_ITEM_GERENTE,
       REPRESENTANTES.COD_REPRESENTANTE,
       REPRESENTANTES2.COD_REPRESENTANTE AS COD_REPRESENTANTE_GERENTE,
       FATURAMENTO_ITEM.REFERENCIA,
       FATURAMENTO_ITEM.REFERENCIA_ITEM,
       FATURAMENTO_ITEM.REFERENCIA_PEDIDO,
       TRIBUT_ICMS.DESCRICAO AS TRIBUT_ICMS_DESCRICAO,
       TRIBUT_ORIGEM.DESCRICAO AS TRIBUT_ORIGEM_DESCRICAO,
       CTB_CONTA_PLANO.DESC_CONTA,
       CLASSIF_FISCAL.DESC_CLASSIFICACAO,
       CTB_LX_INDICADOR_CFOP.DESCRICAO_INDICADOR_CFOP,
       FATURAMENTO.PORC_ENCARGO,
       FATURAMENTO.PORC_DESCONTO,
       CONVERT(BIT, 1) AS PORC_DESCONTO_DIGITADO,
       FATURAMENTO.CODIGO_LOCAL_ENTREGA,
       FATURAMENTO.NOME_CLIFOR_ENTREGA,
       FATURAMENTO.REPRESENTANTE,
       FATURAMENTO.GERENTE,
       FATURAMENTO_ITEM.FAIXA,
       FATURAMENTO_ITEM.COD_TABELA_FILHA,
       FATURAMENTO.AGRUPAMENTO_ITENS,
       CODIGO_FISCAL_OPERACAO = CTB_LX_NATUREZAS_OPERACAO.CFOP_RETORNO_DEVOLUCAO,
       FATURAMENTO_ITEM.ORIGEM_ITEM,
       FATURAMENTO.FRETE,
       FATURAMENTO.SEGURO,
       FATURAMENTO_ITEM.MPADRAO_FRETE_ITEM,
       FATURAMENTO_ITEM.MPADRAO_SEGURO_ITEM,
       FATURAMENTO_ITEM.MPADRAO_ENCARGO_ITEM,
       FATURAMENTO_ITEM.ID_CEST_NCM,
       TABELA_LX_CEST.DESCRICAO,
       TABELA_LX_CEST.CODIGO_CEST,
       FATURAMENTO.NOME_LOCAL_RETIRADA
FROM FATURAMENTO_ENTRADA_DEVOLUCAO
INNER JOIN FATURAMENTO_ITEM ON FATURAMENTO_ENTRADA_DEVOLUCAO.FILIAL = FATURAMENTO_ITEM.FILIAL
AND FATURAMENTO_ENTRADA_DEVOLUCAO.NF_SAIDA = FATURAMENTO_ITEM.NF_SAIDA
AND FATURAMENTO_ENTRADA_DEVOLUCAO.SERIE_NF = FATURAMENTO_ITEM.SERIE_NF
AND FATURAMENTO_ENTRADA_DEVOLUCAO.ITEM_IMPRESSAO_SAIDA = FATURAMENTO_ITEM.ITEM_IMPRESSAO
AND FATURAMENTO_ENTRADA_DEVOLUCAO.SUB_ITEM_SAIDA = FATURAMENTO_ITEM.SUB_ITEM_TAMANHO
INNER JOIN FATURAMENTO ON FATURAMENTO_ITEM.FILIAL = FATURAMENTO.FILIAL
AND FATURAMENTO_ITEM.NF_SAIDA = FATURAMENTO.NF_SAIDA
AND FATURAMENTO_ITEM.SERIE_NF = FATURAMENTO.SERIE_NF
INNER JOIN TRIBUT_ICMS ON FATURAMENTO_ITEM.TRIBUT_ICMS = TRIBUT_ICMS.TRIBUT_ICMS
INNER JOIN CTB_LX_INDICADOR_CFOP ON FATURAMENTO_ITEM.INDICADOR_CFOP = CTB_LX_INDICADOR_CFOP.INDICADOR_CFOP
INNER JOIN CLASSIF_FISCAL ON FATURAMENTO_ITEM.CLASSIF_FISCAL = CLASSIF_FISCAL.CLASSIF_FISCAL
INNER JOIN TRIBUT_ORIGEM ON TRIBUT_ORIGEM.TRIBUT_ORIGEM = FATURAMENTO_ITEM.TRIBUT_ORIGEM
INNER JOIN CTB_LX_NATUREZAS_OPERACAO ON CTB_LX_NATUREZAS_OPERACAO.CODIGO_FISCAL_OPERACAO = FATURAMENTO_ITEM.CODIGO_FISCAL_OPERACAO
LEFT JOIN CTB_CONTA_PLANO ON FATURAMENTO_ITEM.CONTA_CONTABIL = CTB_CONTA_PLANO.CONTA_CONTABIL
LEFT JOIN REPRESENTANTES ON FATURAMENTO.REPRESENTANTE = REPRESENTANTES.REPRESENTANTE
LEFT JOIN REPRESENTANTES REPRESENTANTES2 ON FATURAMENTO.GERENTE = REPRESENTANTES2.REPRESENTANTE
LEFT JOIN CEST_NCM LISTA_CEST_NCM ON FATURAMENTO_ITEM.ID_CEST_NCM = LISTA_CEST_NCM.ID
LEFT JOIN TABELA_LX_CEST ON LISTA_CEST_NCM.ID_CEST = TABELA_LX_CEST.ID
WHERE FATURAMENTO_ENTRADA_DEVOLUCAO.NF_ENTRADA = '000000890'
  AND FATURAMENTO_ENTRADA_DEVOLUCAO.SERIE_NF_ENTRADA = '8'
  AND FATURAMENTO_ENTRADA_DEVOLUCAO.NOME_CLIFOR = 'KENIA PARREIRA BARBAGLIA'
ORDER BY FATURAMENTO_ENTRADA_DEVOLUCAO.FILIAL,
         FATURAMENTO_ENTRADA_DEVOLUCAO.NF_SAIDA,
         FATURAMENTO_ENTRADA_DEVOLUCAO.SERIE_NF
 
SELECT * 
FROM FATURAMENTO_ENTRADA_DEVOLUCAO A 
WHERE NF_ENTRADA = '000000890' AND SERIE_NF_ENTRADA = '8' AND NOME_CLIFOR = 'KENIA PARREIRA BARBAGLIA'  

select *
from FATURAMENTO_ITEM fi
where fi.nf_saida = '000000817' and fi.serie_nf='8' and fi.filial='VENDA ATACADO BARRA VELHA'

*/

/*
inserir os outros <N> itens
*/
declare @xuxa table (
QTDE_DEVOLVIDA numeric(9,3),
ITEM_IMPRESSAO_SAIDA varchar(4),
ORIGEM_ENTRADA_SAIDA varchar(1),
ITEM_IMPRESSAO_ENTRADA varchar(4),
SUB_ITEM_SAIDA int,
SUB_ITEM_ENTRADA int,
FILIAL varchar(25),
NF_SAIDA varchar(15),
SERIE_NF varchar(6), 
NOME_CLIFOR varchar(25),
NF_ENTRADA varchar(15), 
SERIE_NF_ENTRADA varchar(6)
)


insert into @xuxa
SELECT
        QTDE_ITEM AS QTDE_DEVOLVIDA,
        ITEM_IMPRESSAO as ITEM_IMPRESSAO_SAIDA,
        'E' ORIGEM_ENTRADA_SAIDA,
        '0001' AS ITEM_IMPRESSAO_ENTRADA,
        SUB_ITEM_TAMANHO AS SUB_ITEM_SAIDA,
        SUB_ITEM_TAMANHO AS SUB_ITEM_ENTRADA,
        FI.FILIAL,
        FI.NF_SAIDA,
        FI.SERIE_NF,
        F.NOME_CLIFOR,
        '000000890' AS NF_ENTRADA,
        '8' AS SERIE_NF_ENTRADA
from FATURAMENTO_ITEM fi
INNER JOIN FATURAMENTO F ON F.NF_SAIDA = FI.NF_SAIDA AND F.SERIE_NF=FI.SERIE_NF AND F.FILIAL=FI.FILIAL
where fi.nf_saida = '000000817' and fi.serie_nf='8' and fi.filial='VENDA ATACADO BARRA VELHA'
AND FI.ITEM_IMPRESSAO <> '0001'


insert into FATURAMENTO_ENTRADA_DEVOLUCAO 
        (QTDE_DEVOLVIDA,
        ITEM_IMPRESSAO_SAIDA,
        ORIGEM_ENTRADA_SAIDA,
        ITEM_IMPRESSAO_ENTRADA,
        SUB_ITEM_SAIDA,
        SUB_ITEM_ENTRADA,
        FILIAL,
        NF_SAIDA,
        SERIE_NF,
        NOME_CLIFOR,
        NF_ENTRADA,
        SERIE_NF_ENTRADA)
select  QTDE_DEVOLVIDA,
        ITEM_IMPRESSAO_SAIDA,
        ORIGEM_ENTRADA_SAIDA,
        ITEM_IMPRESSAO_ENTRADA,
        SUB_ITEM_SAIDA,
        SUB_ITEM_ENTRADA,
        FILIAL,
        NF_SAIDA,
        SERIE_NF,
        NOME_CLIFOR,
        NF_ENTRADA,
        SERIE_NF_ENTRADA
from @xuxa

/*
SELECT * 
FROM FATURAMENTO_ENTRADA_DEVOLUCAO A 
WHERE NF_ENTRADA = '000000890' AND SERIE_NF_ENTRADA = '8' AND NOME_CLIFOR = 'KENIA PARREIRA BARBAGLIA'  
AND ITEM_IMPRESSAO_SAIDA = '0001' AND SUB_ITEM_ENTRADA IN (2,3)

UPDATE A
SET QTDE_DEVOLVIDA = 12
FROM FATURAMENTO_ENTRADA_DEVOLUCAO A 
WHERE NF_ENTRADA = '000000890' AND SERIE_NF_ENTRADA = '8' AND NOME_CLIFOR = 'KENIA PARREIRA BARBAGLIA'  
--AND ITEM_IMPRESSAO_SAIDA = '0001' AND SUB_ITEM_ENTRADA IN (1,4)
AND ITEM_IMPRESSAO_SAIDA = '0001' AND SUB_ITEM_ENTRADA IN (2,3)

UPDATE A
SET QTDE_DEVOLVIDA = 8
FROM FATURAMENTO_ENTRADA_DEVOLUCAO A 
WHERE NF_ENTRADA = '000000890' AND SERIE_NF_ENTRADA = '8' AND NOME_CLIFOR = 'KENIA PARREIRA BARBAGLIA'  
--AND ITEM_IMPRESSAO_SAIDA = '0014' AND SUB_ITEM_ENTRADA IN (1,4)
AND ITEM_IMPRESSAO_SAIDA = '0014' AND SUB_ITEM_ENTRADA IN (2,3)

*/