
DECLARE @CODIGO VARCHAR(6)
SELECT @CODIGO = MAX(CODIGO) FROM CGP_FICHA_TECNICA_ITENS

SELECT RIGHT('000000'+CONVERT(VARCHAR,CAST(@CODIGO AS INT)+1),6)

INSERT INTO CGP_FICHA_TECNICA_ITENS (CODIGO,DESCRICAO,CODIGO_FT,INATIVO)
VALUES 
(RIGHT('000000'+CONVERT(VARCHAR,CAST(@CODIGO AS INT)+1),6),'COLETE','0006',0),
(RIGHT('000000'+CONVERT(VARCHAR,CAST(@CODIGO AS INT)+2),6),'MACAQUINHO','0006',0),
(RIGHT('000000'+CONVERT(VARCHAR,CAST(@CODIGO AS INT)+3),6),'MIJAOZINHO','0006',0),
(RIGHT('000000'+CONVERT(VARCHAR,CAST(@CODIGO AS INT)+4),6),'SHORTS-SAIA','0006',0)

select a.* 
from CGP_FICHA_TECNICA_ITENS a
inner join CGP_FICHA_TECNICA b on b.CODIGO=a.CODIGO_FT
where b.DESCRICAO='CATEGORIA'
