SELECT * 
FROM PRODUTOS_SUBGRUPO 
WHERE GRUPO_PRODUTO = 'ACESSORIOS' 
ORDER BY CODIGO_SUBGRUPO

INSERT INTO PRODUTOS_SUBGRUPO (GRUPO_PRODUTO,SUBGRUPO_PRODUTO,CODIGO_SUBGRUPO,CODIGO_SEQUENCIAL,NUMERO_PARTES_PRODUTO)
VALUES ('INTEIRO','BODY S/M E M/C','38','0000',0)
INSERT INTO PRODUTOS_SUBGRUPO (GRUPO_PRODUTO,SUBGRUPO_PRODUTO,CODIGO_SUBGRUPO,CODIGO_SEQUENCIAL,NUMERO_PARTES_PRODUTO)
VALUES ('INTEIRO','BODY M/L','39','0000',0)
INSERT INTO PRODUTOS_SUBGRUPO (GRUPO_PRODUTO,SUBGRUPO_PRODUTO,CODIGO_SUBGRUPO,CODIGO_SEQUENCIAL,NUMERO_PARTES_PRODUTO)
VALUES ('INTEIRO','MACACAO/VESTIDO','40','0000',0)


INSERT INTO PRODUTOS_SUBGRUPO (GRUPO_PRODUTO,SUBGRUPO_PRODUTO,CODIGO_SUBGRUPO,CODIGO_SEQUENCIAL,NUMERO_PARTES_PRODUTO)
VALUES ('INVERNO BOTTOM','MALHA/MOLETOM','22','0000',0)


select * from PRODUTOS_GRUPO order by codigo_grupo


update cadastro_cli_for set indica_cliente = 1 where clifor = '218610'