--55 VENDAS_SP_LAPA
--67 VENDAS_CAMPINAS_CENTRO
--69 VENDAS_RP_SH_NOVO_SHOPP
DECLARE @TABELA CHAR(2) = '69'

DELETE FROM PRODUTOS_PRECOS WHERE CODIGO_TAB_PRECO=@TABELA;

INSERT INTO PRODUTOS_PRECOS
(	CODIGO_TAB_PRECO
	,PRODUTO
	,PRECO1
	,PRECO2
	,PRECO3
	,PRECO4
	,LIMITE_DESCONTO
	,PROMOCAO_DESCONTO
	,ULT_ATUALIZACAO
	,INICIO_PROMOCAO
	,FIM_PROMOCAO
	,DATA_PARA_TRANSFERENCIA
	,MARK_UP_PREVISTO
	,PROMOCAO_ATACADO
	,PRECO_LIQUIDO1
	,PRECO_LIQUIDO2
	,PRECO_LIQUIDO3
	,PRECO_LIQUIDO4
	,LX_STATUS_REGISTRO
	,PRECO1_ANTERIOR
	,DATA_CARGA_PRECOS
	,LX_HASH
)
SELECT  
	@TABELA AS CODIGO_TAB_PRECO
	,PRODUTO
	,PRECO1
	,PRECO2
	,PRECO3
	,PRECO4
	,LIMITE_DESCONTO
	,PROMOCAO_DESCONTO
	,ULT_ATUALIZACAO
	,INICIO_PROMOCAO
	,FIM_PROMOCAO
	,DATA_PARA_TRANSFERENCIA
	,MARK_UP_PREVISTO
	,PROMOCAO_ATACADO
	,PRECO_LIQUIDO1
	,PRECO_LIQUIDO2
	,PRECO_LIQUIDO3
	,PRECO_LIQUIDO4
	,LX_STATUS_REGISTRO
	,PRECO1_ANTERIOR
	,DATA_CARGA_PRECOS
	,LX_HASH
FROM PRODUTOS_PRECOS WHERE CODIGO_TAB_PRECO='11'
