/*
SELECT * FROM ESTOQUE_PROD_ENT WHERE ROMANEIO_PRODUTO = '6072274'

SELECT * FROM ESTOQUE_PROD1_ENT WHERE ROMANEIO_PRODUTO = '6072274'
*/
DECLARE @TAB1 TABLE (ID INT IDENTITY(1,1), NF VARCHAR(15), FILIAL VARCHAR(25))
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10755', 'CARAGUATATUBA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10757', 'CARAPICUIBA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10758', 'CIDADE OCIAN');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10760', 'CIDADE TIRADENTES');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10761', 'COTIA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10762', 'CRUZEIRO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10764', 'DIADEMA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10765', 'FERRAZ');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10766', 'FRANCISCO MORATO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10768', 'FRANCO DA ROCHA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10769', 'GUARATINGUETA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10770', 'HORTOLANDIA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10772', 'IPIRANGA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10773', 'ITAIM');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10774', 'ITAPECERICA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10776', 'ITAPEVI');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10777', 'ITAQUA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10778', 'ITAQUERA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10779', 'JARDIM ANGELA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10781', 'JARDIM IGUATEMI');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10784', 'JUNDIAI');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10785', 'MAUA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10787', 'MAUA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10790', 'MOGI DAS CRUZES');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10792', 'OSASCO - UNIAO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10793', 'OSASCO CENTRO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10796', 'PINDAMONHANGABA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10797', 'PRAIA GRANDE');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10853', 'REGISTRO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10854', 'SANTO ANDRE - CENTRO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10855', 'SANTOS - CENTRO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10856', 'SAO VICENTE');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10857', 'SOROCABA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10858', 'SP - ARICANDUVA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10859', 'SP - CAMPO LIMPO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10860', 'SP - CAPAO CENTRO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10861', 'SP - GRAJAU');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10862', 'SP - METRO CAPAO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10863', 'SP - PIRAPORINHA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10864', 'SP - SANTO AMARO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10865', 'SP - SANTO AMARO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10866', 'SP - SAO MIGUEL');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10867', 'SP - TUCURUVI');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10868', 'SUMARE');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10869', 'TAUBATE');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10870', 'VARZEA PAULISTA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10871', 'VICENTE DE CARVALHO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10872', 'VILA DIRCE');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('10873', 'VILA FORMOSA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('12460', 'BARUERI');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('12462', 'CAMPINAS - BANDEIRAS');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('12514', 'VILA DIRCE');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('12515', 'VILA DAS MERCES');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012463', 'CARAGUATATUBA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012464', 'CIDADE OCIAN');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012467', 'CIDADE TIRADENTES');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012469', 'COTIA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012470', 'CRUZEIRO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012471', 'FRANCISCO MORATO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012473', 'FRANCO DA ROCHA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012474', 'HORTOLANDIA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012475', 'IPIRANGA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012476', 'ITAIM');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012477', 'ITAPEVI');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012478', 'ITAQUA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012479', 'ITAQUERA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012481', 'ITU');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012482', 'JAÇANA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012483', 'JARDIM ANGELA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012484', 'JUNDIAI');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012485', 'MAUA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012486', 'MOGI DAS CRUZES');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012487', 'OSASCO - UNIAO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012488', 'OSASCO - UNIAO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012489', 'OSASCO CENTRO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012490', 'PIRASSUNUNGA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012491', 'PRAIA GRANDE');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012492', 'REGISTRO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012493', 'SANTOS - CENTRO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012494', 'SANTOS - GONZAGA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012495', 'SANTOS - GONZAGA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012496', 'SAO BERNARDO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012497', 'SAO MATHEUS');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012498', 'SAO VICENTE');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012499', 'SOROCABA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012500', 'SP - ARICANDUVA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012501', 'SP - BRASILANDIA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012502', 'SP - CAMPO LIMPO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012504', 'SP - CAPAO CENTRO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012505', 'SP - GRAJAU');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012506', 'SP - METRO CAPAO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012507', 'SP - PENHA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012508', 'SP - PIRAPORINHA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012509', 'SP - SANTO AMARO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012510', 'SP - SAO MIGUEL');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012511', 'SUMARE');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012512', 'VARZEA PAULISTA');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012513', 'VICENTE DE CARVALHO');
INSERT INTO @TAB1 (NF,FILIAL) VALUES ('000012516', 'VILA FORMOSA');




DECLARE @MIN INT, @MAX INT 
SELECT @MIN = MIN(ID), @MAX = MAX(ID) FROM @TAB1
declare @nEmpresa int, @NOVO_CODIGO VARCHAR(8), @HOJE DATETIME, @NF VARCHAR(15), @PRODUTO VARCHAR(8), @COR VARCHAR(5), @QTDE INT, @FILIAL VARCHAR(25)

WHILE @MIN <= @MAX
BEGIN

SELECT @NF = NF, @FILIAL = FILIAL FROM @TAB1 WHERE ID = @MIN

set @nEmpresa = 1
SET @NOVO_CODIGO = ''
SET @HOJE = CONVERT(VARCHAR,GETDATE(),112)
SET @PRODUTO = '55110119'
SET @COR = '00029'
SET @QTDE = 6
EXEC LX_SEQUENCIAL 'ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO', @nEmpresa, @NOVO_CODIGO OUTPUT  
SELECT @NOVO_CODIGO AS ROMANEIO_PRODUTO

INSERT INTO ESTOQUE_PROD_ENT ([ROMANEIO_PRODUTO], [FILIAL], [ORDEM_PRODUCAO], [EMISSAO], [RESPONSAVEL], [NOME_CLIFOR], [NF_ENTRADA], [FILIAL_DESTINO], [PEDIDO], [ROMANEIO_ORIGEM], [FILIAL_ORIGEM], [OBS], [SEGUNDA_QUALIDADE], [ORDEM_SERVICO], [ACERTO_ENTRADA], [ENTREGA_PEDIDO], [SERIE_NF_ENTRADA], [TIPO_ENTRADA], [TIPO_ROMANEIO], [COMENTARIO], [DATA_DIGITACAO], [NAO_VALIDAR_ENTRADA], [CAIXA], [RATEIO_CENTRO_CUSTO], [CM_OPERACAO], [RATEIO_FILIAL], [CONTA_CONTABIL], [NF_ENTRADA_PROPRIA], [DATA_PARA_TRANSFERENCIA], [ENB_CODIGO_FILIAL], [ENB_TERMINAL], [ENB_COO], [INDICA_PRE_ROMANEIO], [PEDIDO2], [ERP_OBS_INTERESSE_FISCO], [valor], [COD_CUSTO_MEDIO])
VALUES (@NOVO_CODIGO, @FILIAL, NULL, @HOJE, 'CCP\PAULO.DEVIDE', NULL, @NF, NULL, NULL, NULL, NULL, 'ENTRADA CD CAJAMAR -  NF '+@NF, 0, NULL, 0, NULL, NULL, 1, 'ENTRADA AJUSTE ESTOQUE', NULL, @HOJE, 0, NULL, NULL, '026', NULL, NULL, 0, GETDATE(), NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL) 

INSERT INTO ESTOQUE_PROD1_ENT ([ROMANEIO_PRODUTO], [PRODUTO], [FILIAL], [COR_PRODUTO], [QTDE], [EN_1], [EN_2], [EN_3], [EN_4], [EN_5], [EN_6], [EN_7], [EN_8], [EN_9], [EN_10], [EN_11], [EN_12], [EN_13], [EN_14], [EN_15], [EN_16], [EN_17], [EN_18], [EN_19], [EN_20], [EN_21], [EN_22], [EN_23], [EN_24], [EN_25], [EN_26], [EN_27], [EN_28], [EN_29], [EN_30], [EN_31], [EN_32], [EN_33], [EN_34], [EN_35], [EN_36], [EN_37], [EN_38], [EN_39], [EN_40], [EN_41], [EN_42], [EN_43], [EN_44], [EN_45], [EN_46], [EN_47], [EN_48],  [ORDEM_PRODUCAO], [TAREFA], [SEGUNDA_QUALIDADE], [CUSTO1], [CUSTO2], [CUSTO3], [CUSTO4], [DATA_CUSTO], [VALOR], [DESCONTO_ITEM], [ITEM_IMPRESSAO], [MATA_SALDO_PEDIDO], [ITEM_IMPRESSAO_FATURA], [CUSTO_PRODUCAO], [CUSTO_INDIRETO], [IPI], [COMISSAO], [COMISSAO_GERENTE], [COD_REPRESENTANTE], [COD_REPRESENTANTE_GERENTE], [ID_MODIFICACAO], [PEDIDO_VENDA], [PEDIDO_VENDA_ENTREGA], [PEDIDO_VENDA_ITEM], [PACKS], [NF_SAIDA], [SERIE_NF], [DATA_PARA_TRANSFERENCIA], [ENB_CODIGO_FILIAL], [ENB_TERMINAL], [ENB_COO], [ENB_CODIGO_BARRA], [DATA_ACERTO_CONSIGNACAO], [PEDIDO2])
SELECT @NOVO_CODIGO AS ROMANEIO_PRODUTO, [PRODUTO], @FILIAL AS FILIAL, [COR_PRODUTO], [QTDE], [EN_1], [EN_2], [EN_3], [EN_4], [EN_5], [EN_6], [EN_7], [EN_8], [EN_9], [EN_10], [EN_11], [EN_12], [EN_13], [EN_14], [EN_15], [EN_16], [EN_17], [EN_18], [EN_19], [EN_20], [EN_21], [EN_22], [EN_23], [EN_24], [EN_25], [EN_26], [EN_27], [EN_28], [EN_29], [EN_30], [EN_31], [EN_32], [EN_33], [EN_34], [EN_35], [EN_36], [EN_37], [EN_38], [EN_39], [EN_40], [EN_41], [EN_42], [EN_43], [EN_44], [EN_45], [EN_46], [EN_47], [EN_48],  [ORDEM_PRODUCAO], [TAREFA], [SEGUNDA_QUALIDADE], [CUSTO1], [CUSTO2], [CUSTO3], [CUSTO4], [DATA_CUSTO], [VALOR], [DESCONTO_ITEM], [ITEM_IMPRESSAO], [MATA_SALDO_PEDIDO], [ITEM_IMPRESSAO_FATURA], [CUSTO_PRODUCAO], [CUSTO_INDIRETO], [IPI], [COMISSAO], [COMISSAO_GERENTE], [COD_REPRESENTANTE], [COD_REPRESENTANTE_GERENTE], [ID_MODIFICACAO], [PEDIDO_VENDA], [PEDIDO_VENDA_ENTREGA], [PEDIDO_VENDA_ITEM], [PACKS], [NF_SAIDA], [SERIE_NF], [DATA_PARA_TRANSFERENCIA], [ENB_CODIGO_FILIAL], [ENB_TERMINAL], [ENB_COO], [ENB_CODIGO_BARRA], [DATA_ACERTO_CONSIGNACAO], [PEDIDO2]
FROM ESTOQUE_PROD1_ENT WHERE ROMANEIO_PRODUTO = '6072274' AND FILIAL = 'CAMPINAS - BANDEIRAS'

SET @MIN = @MIN + 1
END


