/*
select * from TRANSACOES where CONTROL_SISTEMA='002007spk'

select * 
--UPDATE A SET VALOR_PROPRIEDADE = 'SIM'
from PROP_TABELAS_PRECO A
WHERE A.CODIGO_TAB_PRECO IN ('A0','A1','A2')

--INSERT INTO PROP_TABELAS_PRECO
SELECT '00118' PROPRIEDADE, CODIGO_TAB_PRECO, 1 AS ITEM_PROPRIEDADE, 'NÃO' AS VALOR_PROPRIEDADE, GETDATE() AS DATA_PARA_TRANSFERENCIA 
FROM TABELAS_PRECO 
--WHERE CODIGO_TAB_PRECO != '01'

*/

DECLARE @LISTATABS TABLE (ID INT IDENTITY(1,1), CODIGO_TAB_PRECO CHAR(2))

insert into @LISTATABS (CODIGO_TAB_PRECO)
select T.CODIGO_TAB_PRECO
from TABELAS_PRECO T
INNER JOIN PROP_TABELAS_PRECO PTP ON PTP.CODIGO_TAB_PRECO=T.CODIGO_TAB_PRECO
where PTP.VALOR_PROPRIEDADE='SIM'


DECLARE @I INT, @TOT INT, @CODIGO_TAB_PRECO CHAR(2)

select @I = MIN(ID), @TOT = MAX(ID)
from @LISTATABS

WHILE @I <= 1 --@TOT
BEGIN

	SELECT @CODIGO_TAB_PRECO = CODIGO_TAB_PRECO
	FROM @LISTATABS 
	WHERE ID = @I

	SELECT TAB2.PRODUTO, TAB1.PRODUTO, @CODIGO_TAB_PRECO AS CODIGO_TAB_PRECO, TAB2.PRECO1 
	FROM (
	(SELECT L1.PRODUTO, L1.CODIGO_TAB_PRECO, L1.PRECO1
	FROM PRODUTOS P
	INNER JOIN PRODUTOS_PRECOS L1 ON L1.PRODUTO=P.PRODUTO AND L1.CODIGO_TAB_PRECO=@CODIGO_TAB_PRECO) ) AS TAB1

	RIGHT JOIN 
	(SELECT L1.PRODUTO, L1.CODIGO_TAB_PRECO, L1.PRECO1
	FROM PRODUTOS P
	INNER JOIN PRODUTOS_PRECOS L1 ON L1.PRODUTO=P.PRODUTO AND L1.CODIGO_TAB_PRECO='11') AS TAB2
	ON TAB2.PRODUTO = TAB1.PRODUTO

	INNER JOIN 
	(select cp.PRODUTO
	from COMPRAS c
	inner join COMPRAS_PRODUTO cp on cp.pedido=c.pedido
	where c.EMISSAO> dateadd(dd,-730,getdate())

	UNION
 
	SELECT LVP.PRODUTO 
	FROM LOJA_VENDA LV
	INNER JOIN LOJA_VENDA_PRODUTO LVP ON LVP.DATA_VENDA=LV.DATA_VENDA 
											AND LVP.CODIGO_FILIAL=LV.CODIGO_FILIAL
											AND LVP.TICKET = LV.TICKET
	WHERE LV.DATA_VENDA > dateadd(dd,-730,getdate())
	GROUP BY LVP.PRODUTO) AS TPRO ON TPRO.PRODUTO = TAB2.PRODUTO
	WHERE TAB1.PRODUTO IS NULL

	SET @I += 1

END
