select (BASE_IMPOSTO * 0.07) AS XUXA,B.*
--UPDATE B SET ID_EXCECAO_IMPOSTO='3473'
UPDATE B SET TAXA_IMPOSTO=7, 
VALOR_IMPOSTO=(BASE_IMPOSTO * 0.07),
VALOR_IMPOSTO_CALCULADO=(BASE_IMPOSTO * 0.07)
from FATURAMENTO A
--INNER JOIN FATURAMENTO_ITEM B ON B.FILIAL=A.FILIAL 
--			AND B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF
INNER JOIN FATURAMENTO_IMPOSTO B ON  B.FILIAL=A.FILIAL 
		AND B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF
where A.FILIAL = 'CD CAJAMAR' 
AND NOME_CLIFOR='GO - SHOPPING ARAGUAIA' --AND ID_EXCECAO_IMPOSTO='2418' 
AND TAXA_IMPOSTO=12

