/*
select	fp.*
--fp.produto, p.desc_produto, fp.COR_PRODUTO 
from faturamento f
inner join FATURAMENTO_PROD fp on fp.FILIAL = f.FILIAL and fp.NF_SAIDA=f.NF_SAIDA and fp.SERIE_NF = f.SERIE_NF
inner join produtos p on p.PRODUTO = fp.PRODUTO
where	cast(f.nf_saida as int) = 21395 
		and f.filial = 'cd cajamar' 
		and f.NOME_CLIFOR='AACD ASSOCIACAO E ASSIST.'
*/
SELECT unp.NF_SAIDA, SERIE_NF, UNP.PRODUTO, unp.DESC_PRODUTO, unp.COR_PRODUTO, unp.DESC_COR_PRODUTO,
POSICAO, CAST(SUBSTRING(POSICAO,2,2) AS INT) AS TAMANHO, 
ISNULL(CODIGO_BARRA,'') AS CODIGO_BARRA, ISNULL(B.GRADE,'') AS GRADE, QTD
FROM (
select NF_SAIDA, SERIE_NF, FATURAMENTO_PROD.PRODUTO, 
P.DESC_PRODUTO, FATURAMENTO_PROD.COR_PRODUTO, pc.DESC_COR_PRODUTO,
ISNULL(F1,0) F1, 
ISNULL(F2,0) F2, 
ISNULL(F3,0) F3, 
ISNULL(F4,0) F4, 
ISNULL(F5,0) F5, 
ISNULL(F6,0) F6, 
ISNULL(F7,0) F7, 
ISNULL(F8,0) F8, 
ISNULL(F9,0) F9, 
ISNULL(F10,0) F10, 
ISNULL(F11,0) F11, 
ISNULL(F12,0) F12, 
ISNULL(F13,0) F13, 
ISNULL(F14,0) F14, 
ISNULL(F15,0) F15, 
ISNULL(F16,0) F16
from FATURAMENTO_PROD 
inner join PRODUTOS p on p.PRODUTO = FATURAMENTO_PROD.PRODUTO
inner join PRODUTO_CORES pc on pc.PRODUTO = FATURAMENTO_PROD.PRODUTO and pc.COR_PRODUTO = FATURAMENTO_PROD.COR_PRODUTO
where nf_saida = '000021395' AND filial = 'CD CAJAMAR'
) as p
unpivot
(qtd for POSICAO IN (F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, F13, F14, F15, F16)
) AS unp
LEFT JOIN
	PRODUTOS_BARRA b 
		on b.PRODUTO = unp.PRODUTO and b.COR_PRODUTO = unp.COR_PRODUTO and b.TAMANHO = CAST(SUBSTRING(POSICAO,2,2) AS INT) 
WHERE QTD>0
ORDER BY unp.PRODUTO, unp.COR_PRODUTO
