select  * from compras where fornecedor = 'CHIK S CENTER MODAS 00190' AND TOT_QTDE_ENTREGAR <> 0

select   
SUM(TOT_QTDE_ORIGINAL) AS TOT_QTDE_ORIGINAL, SUM(TOT_VALOR_ORIGINAL ) AS TOT_VALOR_ORIGINAL,
sum(TOT_QTDE_ENTREGAR) as TOT_QTDE_ENTREGAR
from compras where fornecedor = 'CHIK S CENTER MODAS 00190' AND TOT_QTDE_ENTREGAR <> 0
--GROUP BY PEDIDO, PEDIDO_FORNECEDOR


SELECT  a.pedido, a.FORNECEDOR, a.FILIAL_A_ENTREGAR, cast(emissao as date) as EMISSAO, PEDIDO_FORNECEDOR,
B.PRODUTO, C.DESC_PRODUTO, C.GRADE, C.GRIFFE, C.LINHA, C.GRUPO_PRODUTO, C.SUBGRUPO_PRODUTO,
B.ENTREGA, B.LIMITE_ENTREGA, B.CUSTO1, B.QTDE_ORIGINAL, B.QTDE_ENTREGAR, B.VALOR_ORIGINAL, B.VALOR_ENTREGAR, 
B.QTDE_ENTREGUE, B.VALOR_ENTREGUE, B.PACKS

from compras A
INNER JOIN COMPRAS_PRODUTO b on b.pedido = a.PEDIDO
INNER JOIN PRODUTOS C ON C.PRODUTO = B.PRODUTO 
where A.fornecedor = 'CHIK S CENTER MODAS 00190' AND A.TOT_QTDE_ENTREGAR <> 0
