CREATE PROCEDURE LX_TAMANHOS_DIGITADOS_GRADE 
@GRADE VARCHAR(25)
AS
BEGIN

	DECLARE @TAMANHOS_DIGITADOS INT
	DECLARE @I INT
	SET @I = 1
	DECLARE @TAMANHO_LIDO VARCHAR(8)
	DECLARE @TAB TABLE (POSICAO INT, TAMANHO VARCHAR(8))

	SELECT @TAMANHOS_DIGITADOS = TAMANHOS_DIGITADOS 
	FROM PRODUTOS_TAMANHOS WHERE GRADE = @GRADE

	WHILE @I <= @TAMANHOS_DIGITADOS
	BEGIN
		SELECT @TAMANHO_LIDO = 
		CASE
			WHEN @I = 1 THEN TAMANHO_1
			WHEN @I = 2 THEN TAMANHO_2
			WHEN @I = 3 THEN TAMANHO_3
			WHEN @I = 4 THEN TAMANHO_4
			WHEN @I = 5 THEN TAMANHO_5
			WHEN @I = 6 THEN TAMANHO_6
			WHEN @I = 7 THEN TAMANHO_7
			WHEN @I = 8 THEN TAMANHO_8
			WHEN @I = 9 THEN TAMANHO_9
			WHEN @I = 10 THEN TAMANHO_10
			WHEN @I = 11 THEN TAMANHO_11
			WHEN @I = 12 THEN TAMANHO_12
			WHEN @I = 13 THEN TAMANHO_13
			WHEN @I = 14 THEN TAMANHO_14
			WHEN @I = 15 THEN TAMANHO_15
			WHEN @I = 16 THEN TAMANHO_16
			WHEN @I = 17 THEN TAMANHO_17
			WHEN @I = 18 THEN TAMANHO_18
			WHEN @I = 19 THEN TAMANHO_19
			WHEN @I = 20 THEN TAMANHO_20
			WHEN @I = 21 THEN TAMANHO_21
			WHEN @I = 22 THEN TAMANHO_22
			WHEN @I = 23 THEN TAMANHO_23
			WHEN @I = 24 THEN TAMANHO_24
			WHEN @I = 25 THEN TAMANHO_25
			WHEN @I = 26 THEN TAMANHO_26
			WHEN @I = 27 THEN TAMANHO_27
			WHEN @I = 28 THEN TAMANHO_28
			WHEN @I = 29 THEN TAMANHO_29
			WHEN @I = 30 THEN TAMANHO_30
			WHEN @I = 31 THEN TAMANHO_31
			WHEN @I = 32 THEN TAMANHO_32
			WHEN @I = 33 THEN TAMANHO_33
			WHEN @I = 34 THEN TAMANHO_34
			WHEN @I = 35 THEN TAMANHO_35
			WHEN @I = 36 THEN TAMANHO_36
			WHEN @I = 37 THEN TAMANHO_37
			WHEN @I = 38 THEN TAMANHO_38
			WHEN @I = 39 THEN TAMANHO_39
			WHEN @I = 40 THEN TAMANHO_40
			WHEN @I = 41 THEN TAMANHO_41
			WHEN @I = 42 THEN TAMANHO_42
			WHEN @I = 43 THEN TAMANHO_43
			WHEN @I = 44 THEN TAMANHO_44
			WHEN @I = 45 THEN TAMANHO_45
			WHEN @I = 46 THEN TAMANHO_46
			WHEN @I = 47 THEN TAMANHO_47
			WHEN @I = 48 THEN TAMANHO_48
		ELSE ''
		END
   	    FROM PRODUTOS_TAMANHOS
		WHERE GRADE = @GRADE

		IF CHARINDEX('.', @TAMANHO_LIDO, 1)=0
		BEGIN
			INSERT INTO @TAB VALUES (@I, @TAMANHO_LIDO)
		END
		SET @I = @I + 1
	END
	
	SELECT POSICAO, TAMANHO 
	FROM @TAB
END
