DECLARE 
@CTB_TIPO_OPERACAO	int,
@CLIFOR	char(15),
@INDICADOR_CFOP	int,
@ENTRADA_SAIDA	char(1),
@MATRIZ_FISCAL	char(25),
@FILIAL	varchar(25),
@EMISSAO_RECEBIMENTO	datetime,
@TRIBUT_ORIGEM	char(3),
@CODIGO_FISCAL_OPERACAO	char(4),
@REFERENCIA	varchar(50),
@NOME_CLIFOR	varchar(25),
@COD_FILHA	char(1),
@NATUREZA	varchar(15),
@COD_FILIAL	char(6)

SET @CTB_TIPO_OPERACAO = NULL
SET @CLIFOR = '000222'
SET @INDICADOR_CFOP = '11'
SET @ENTRADA_SAIDA = 'S'
SET @MATRIZ_FISCAL = 'SP SH LITORAL PLAZA'      
SET @FILIAL = 'SP SH LITORAL PLAZA'
SET @EMISSAO_RECEBIMENTO = GETDATE()
SET @TRIBUT_ORIGEM = '0'
SET @CODIGO_FISCAL_OPERACAO = '5152'
SET @REFERENCIA = 'F0000046'                                          
SET @NOME_CLIFOR = 'SP SH LITORAL PLAZA QS'
SET @COD_FILHA = 'P'
SET @NATUREZA = '120.01' 
SET @COD_FILIAL = '000222'

SELECT 
DBO.FX_ID_EXCECAO_IMPOSTO (
@CTB_TIPO_OPERACAO, 
@CLIFOR, 
@INDICADOR_CFOP,
'S',@FILIAL, 
@MATRIZ_FISCAL, 
GETDATE(), 
'0', 
@CODIGO_FISCAL_OPERACAO, 
@REFERENCIA, 
@NOME_CLIFOR, 
'P', 
@NATUREZA, 
@COD_FILIAL) AS EXCECAO_PESQUISADA



SELECT CHAVE_NFE ,FI.CTB_TIPO_OPERACAO, FI.INDICADOR_CFOP,
FL.CLIFOR, FL.FILIAL, FL.MATRIZ_FISCAL, F.NOME_CLIFOR, F.NATUREZA_SAIDA,FI.* 
FROM FATURAMENTO F
INNER JOIN FATURAMENTO_ITEM FI ON FI.FILIAL=F.FILIAL AND FI.NF_SAIDA=F.NF_SAIDA AND FI.SERIE_NF=F.SERIE_NF
INNER JOIN FILIAIS FL ON FL.FILIAL=F.FILIAL
WHERE F.CHAVE_NFE = '35260946377727012442550020000000181881321999'
