select *
from filiais where filial like '%PLAZA%'

SELECT * 
FROM TABELAS_PRECO 
WHERE TABELA LIKE '%PLAZA%'

--CODIGO_TAB_PRECO='D4'


SELECT * FROM PRODUTOS_PRECOS
WHERE CODIGO_TAB_PRECO = 'D4'
  

SELECT CODIGO_TAB_PRECO, COUNT(*) QT
FROM PRODUTOS_PRECOS
WHERE CODIGO_TAB_PRECO IN ('D1','D4')
GROUP BY CODIGO_TAB_PRECO

INSERT INTO PRODUTOS_PRECOS (
CODIGO_TAB_PRECO, PRODUTO, PRECO1, PRECO2,PRECO3,PRECO4, DATA_PARA_TRANSFERENCIA 
)
SELECT 'D4' AS CODIGO_TAB_PRECO, D1.PRODUTO, D1.PRECO1, D1.PRECO2,D1.PRECO3,D1.PRECO4, GETDATE() AS DATA_PARA_TRANSFERENCIA 
FROM PRODUTOS_PRECOS D1 
LEFT JOIN PRODUTOS_PRECOS D4 ON D4.CODIGO_TAB_PRECO='D4' AND D4.PRODUTO=D1.PRODUTO
WHERE D1.CODIGO_TAB_PRECO='D1'
AND D4.PRODUTO IS NULL

