
declare @descricao varchar(50)

set @descricao = '50% ALGODÃO 50% POLIÉSTER'

declare @nEmpresa int, @NOVO_CODIGO_1 VARCHAR(6), 
		@NOVO_CODIGO_2 VARCHAR(6), @NOVO_CODIGO_3 varchar(6)

set @nEmpresa = 1
SET @NOVO_CODIGO_1 = '' /* sequencial materiais_composicao*/
SET @NOVO_CODIGO_2 = '' /* sequencial CAEDU_LISTA_COMBO*/
EXEC LX_SEQUENCIAL 'MATERIAIS_COMPOSICAO.COMPOSICAO', @nEmpresa, @NOVO_CODIGO_1 OUTPUT  

EXEC LX_SEQUENCIAL 'CAEDU_LISTA_COMBO.CODIGO', @nEmpresa, @NOVO_CODIGO_2 OUTPUT 

select @NOVO_CODIGO_3 = right('000000' + convert(varchar,MAX(cast(codigo as int)) + 1),6)
from CGP_FICHA_TECNICA_ITENS 

--SELECT @NOVO_CODIGO_1, @NOVO_CODIGO_2, @NOVO_CODIGO_3

insert into CAEDU_LISTA_COMBO 
(codigo, descricao, id_dominio, desc_dominio, ERP_CUPS_DESCRICAO_IMPORTACAO)
values (@NOVO_CODIGO_2,@descricao,'005','COMPOSICAO',@descricao)

insert into MATERIAIS_COMPOSICAO 
(COMPOSICAO, DESC_COMPOSICAO, DATA_PARA_TRANSFERENCIA, INATIVA)
values (@NOVO_CODIGO_1, @descricao, GETDATE(), 0)

INSERT INTO CGP_FICHA_TECNICA_ITENS (CODIGO, DESCRICAO, CODIGO_FT, INATIVO)
values (@NOVO_CODIGO_3, @descricao, '0005', 0)

UPDATE CAEDU_LISTA_COMBO 
SET COMPOSICAO_LINX = @NOVO_CODIGO_1, COMPOSICAO_FT = @NOVO_CODIGO_3
WHERE CODIGO = @NOVO_CODIGO_2

SELECT * FROM CAEDU_LISTA_COMBO WHERE codigo = @NOVO_CODIGO_2

/*

select * from CAEDU_LISTA_COMBO 
where desc_dominio='COMPOSICAO' 
AND descricao LIKE '50%POLI%'

SELECT * FROM SEQUENCIAIS 
WHERE TABELA_COLUNA LIKE 'CAEDU_LISTA%'

select * 
from dbo.MATERIAIS_COMPOSICAO

SELECT * FROM SEQUENCIAIS 
WHERE TABELA_COLUNA LIKE 'MATERIAIS_COMPOSICAO%'

select * from CGP_FICHA_TECNICA_ITENS where CODIGO_FT = '0005'

insert into MATERIAIS_COMPOSICAO 
(COMPOSICAO, DESC_COMPOSICAO, DATA_PARA_TRANSFERENCIA, INATIVA)
select  '000'+convert(varchar,(ROW_NUMBER() OVER(ORDER BY CODIGO ASC))+132) AS COMPOSICAO, 
descricao AS DESC_COMPOSICAO, GETDATE() AS DATA_PARA_TRANSFERENCIA, CAST(0 AS BIT) AS INATIVA
from CAEDU_LISTA_COMBO a WHERE id_dominio= '005'


INSERT INTO CGP_FICHA_TECNICA_ITENS (CODIGO, DESCRICAO, CODIGO_FT, INATIVO)
select  '000'+convert(varchar,(ROW_NUMBER() OVER(ORDER BY CODIGO ASC))+354) AS COMPOSICAO, 
descricao AS DESC_COMPOSICAO, '0005' AS CODIGO_FT, CAST(0 AS BIT) AS INATIVO
from CAEDU_LISTA_COMBO a WHERE id_dominio= '005'

*/


