CREATE TABLE CAE_ESTADOS_IBGE (
    SIGLA CHAR(2) NOT NULL,
    CODIGO SMALLINT NOT NULL,
    NOME VARCHAR(30) NOT NULL);
GO

alter table CAE_ESTADOS_IBGE
add constraint PK_CAE_ESTADOS_IBGE
primary key (SIGLA);
GO

alter table CAE_ESTADOS_IBGE
add constraint UNQ_CAE_ESTADOS_IBGE_CODIGO
unique (CODIGO);
GO



INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (12,'AC','ACRE');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (27,'AL','ALAGOAS');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (13,'AM','AMAZONAS');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (16,'AP','AMAPA');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (29,'BA','BAHIA');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (23,'CE','CEARA');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (53,'DF','DISTRITO FEDERAL');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (32,'ES','ESPIRITO SANTO');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (52,'GO','GOIAS');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (21,'MA','MARANHAO');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (31,'MG','MINAS GERAIS');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (50,'MS','MATO GROSSO DO SUL');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (51,'MT','MATO GROSSO');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (15,'PA','PARA');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (25,'PB','PARAIBA');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (26,'PE','PERNAMBUCO');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (22,'PI','PIAUI');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (41,'PR','PARANA');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (33,'RJ','RIO DE JANEIRO');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (24,'RN','RIO GRANDE DO NORTE');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (11,'RO','RONDONIA');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (14,'RR','RORAIMA');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (43,'RS','RIO GRANDE DO SUL');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (42,'SC','SANTA CATARINA');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (28,'SE','SERGIPE');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (35,'SP','SAO PAULO');
INSERT INTO CAE_ESTADOS_IBGE (CODIGO,SIGLA,NOME) VALUES (17,'TO','TOCANTINS');



