/*
não faturados até 18/05...: 3084 - 2289 - 1971 - 1396 -312
sem box gerado até 18/05..:  289
com box gerado até 18/05..: 2795
lojas p/ faturar até 18/05:   99
*/

WITH SEMBOX (FILIAL,LOJADESTINO,CAIXA,DOCA,CODIGO_FILIAL,DATA,FATURADO,PEDIDO,PRODUTO,COR_PRODUTO,QTDE_EMBALADA)
AS
(
SELECT F.FILIAL, F.FILIAL AS LOJADESTINO,A.CAIXA,A.DOCA,A.CODIGO_FILIAL,A.DATA,A.FATURADO,
VE.PEDIDO,VE.PRODUTO,VE.COR_PRODUTO,VE.QTDE_EMBALADA
FROM PDA_WMS_TB_EMBARQUE A
INNER JOIN FILIAIS F ON F.COD_FILIAL=A.CODIGO_FILIAL
LEFT JOIN FATURAMENTO_PROD FP ON FP.CAIXA=A.CAIXA
LEFT JOIN VENDAS_PROD_EMBALADO VE ON VE.CAIXA=A.CAIXA
WHERE 1=1
AND FP.CAIXA IS NULL --AND VE.CAIXA IS not NULL
AND A.DATA>'20250101' AND A.DATA < CONVERT(varchar,GETDATE(),112)
)
select count(*) 
--into [ccp\paulo.devide].[TB_CAIXAS_A_FATURAR_20250519]
from sembox

--ALTER TABLE 
--[ccp\paulo.devide].[TB_CAIXAS_A_FATURAR_20250519]
--ADD PRODUTO_1 VARCHAR(8) NULL, COR_PRODUTO_1 VARCHAR(5), PACK_1 CHAR(1)
--GO

--ALTER TABLE [ccp\paulo.devide].[TB_CAIXAS_A_FATURAR_20250519]
--ADD ROWNUM INT IDENTITY(1,1)


