/* Homologacao */

create table DBO.TESTEPAI 
(
CODIGO INT NOT NULL,
DESCRICAO VARCHAR(50) NOT NULL
)
GO

ALTER TABLE DBO.TESTEPAI
ADD CONSTRAINT PK_TESTEPAI 
PRIMARY KEY (CODIGO)
GO

CREATE TABLE DBO.TESTEFILHA (
CODIGO INT NOT NULL,
SEQ INT NOT NULL,
QTD INT NOT NULL,
VALOR NUMERIC (10,2) NOT NULL 
)
GO

ALTER TABLE DBO.TESTEFILHA 
ADD CONSTRAINT PK_TESTEFILHA
PRIMARY KEY (CODIGO, SEQ)
GO

ALTER TABLE DBO.TESTEFILHA
ADD CONSTRAINT FK_TESTEFILHA_CODIGO
FOREIGN KEY (CODIGO) REFERENCES DBO.TESTEPAI (CODIGO)
GO



