
CREATE TABLE CAEDU_PDA_INVENTARIO
(ID_INVENTARIO INT NOT NULL, 
DESC_INVENTARIO VARCHAR(40) NOT NULL, 
DATA_INVENTARIO DATETIME NOT NULL, 
FILIAL VARCHAR(25) NOT NULL, 
DATA_INCLUSAO DATETIME NULL, 
DATA_ULTIMA_ATUALIZACAO DATETIME NULL)
GO

ALTER TABLE CAEDU_PDA_INVENTARIO
ADD PRIMARY KEY (ID_INVENTARIO)
GO

CREATE TABLE CAEDU_PDA_INVENTARIO_ITENS
(ID_INVENTARIO INT NOT NULL,
SEQUENCIA INT NOT NULL,
CODIGO_BARRA VARCHAR(15) NOT NULL,
CONTAGEM INT NOT NULL,
DATA_ULTIMA_ATUALIZACAO DATETIME NULL)
GO

ALTER TABLE CAEDU_PDA_INVENTARIO_ITENS
ADD PRIMARY KEY(ID_INVENTARIO, SEQUENCIA)
GO


CREATE TABLE CAEDU_PDA_INVENTARIO_ITENS_REJEITADOS
(ID_INVENTARIO INT NOT NULL,
SEQUENCIA INT NOT NULL,
CODIGO_BARRA VARCHAR(15) NOT NULL,
CONTAGEM INT NOT NULL,
DATA_ULTIMA_ATUALIZACAO DATETIME NULL)
GO

ALTER TABLE CAEDU_PDA_INVENTARIO_ITENS_REJEITADOS
ADD PRIMARY KEY(ID_INVENTARIO, SEQUENCIA)
GO

