/*
select * from USERS where inativo=0
--select * from USERS_CUBOS_PERMITIDOS
select * from USERS_GRUPO
select * from USERS_GRUPO_LISTA
select * from USERS_MATRIZ_CONTABIL
select * from USERS_MODULOS
select * from USERS_TRANSACOES
*/

/* USUARIOS CADASTRO */
select 
u.USUARIO,
u.NOME_COMPLETO,
u.DEPTO,
u.ACESSO_TOTAL,
u.ACESSO_ESP_1,
u.ACESSO_ESP_2,
u.INCLUIR,
u.ALTERAR,
u.EXCLUIR,
u.PESQUISAR,
u.PESQUISA_ESPECIAL,
u.IMPRIMIR,
u.CRIAR_RELATORIO,
u.NIVEL_ACESSO,
u.EMPRESA,
u.PERMITE_EXPORTAR,
u.PERMITE_EDITAR_LAYOUTS,
u.PERMITE_EDITAR_EVENTOS,
u.AUTENTICACAO_WINDOWS,
u.LX_SYSTEM_USER,
u.INATIVO,
u.USER_GUID
from USERS u
where u.INATIVO=0
order by u.usuario asc

/* USUARIOS VS MODULOS */
select 
u.USUARIO,
u.NOME_COMPLETO,
u.DEPTO,
um.MODULO,
um.ACESSO_MODULOS,
um.INCLUIR as MODULO_INCLUIR,
um.ALTERAR as MODULO_ALTERAR,
um.EXCLUIR as MODULO_EXCLUIR,
um.PESQUISAR as MODULO_PESQUISAR,
um.PESQUISA_ESPECIAL as MODULO_PESQUISA_ESPECIAL,
um.IMPRIMIR as MODULO_IMPRIMIR,
um.CRIAR_RELATORIO as MODULO_CRIAR_RELATORIO,
u.ACESSO_TOTAL,
u.ACESSO_ESP_1,
u.ACESSO_ESP_2,
u.INCLUIR,
u.ALTERAR,
u.EXCLUIR,
u.PESQUISAR,
u.PESQUISA_ESPECIAL,
u.IMPRIMIR,
u.CRIAR_RELATORIO,
u.NIVEL_ACESSO,
u.EMPRESA,
u.PERMITE_EXPORTAR,
u.PERMITE_EDITAR_LAYOUTS,
u.PERMITE_EDITAR_EVENTOS,
u.AUTENTICACAO_WINDOWS,
u.LX_SYSTEM_USER,
u.INATIVO,
u.USER_GUID
from USERS u
left join USERS_MODULOS um on um.USUARIO = u.USUARIO
where u.INATIVO=0
--and acesso_total=1
order by u.usuario asc, um.modulo asc

/* USUARIOS VS TRANSACOES */
select 
u.USUARIO,
u.NOME_COMPLETO,
u.DEPTO,
u.ACESSO_TOTAL,
u.ACESSO_ESP_1,
u.ACESSO_ESP_2,
u.INCLUIR,
u.ALTERAR,
u.EXCLUIR,
u.PESQUISAR,
u.PESQUISA_ESPECIAL,
u.IMPRIMIR,
u.CRIAR_RELATORIO,
u.NIVEL_ACESSO,
u.EMPRESA,
u.PERMITE_EXPORTAR,
u.PERMITE_EDITAR_LAYOUTS,
u.PERMITE_EDITAR_EVENTOS,
u.AUTENTICACAO_WINDOWS,
u.LX_SYSTEM_USER,
u.INATIVO,
u.USER_GUID, 
t.COD_TRANSACAO,
t.TITULO,
t.CONTROL_SISTEMA,
ut.ACESSO_BLOQUEADO as UT_ACESSO_BLOQUEADO,
ut.INCLUIR as UT_INCLUIR,
ut.ALTERAR as UT_ALTERAR,
ut.EXCLUIR as UT_EXCLUIR,
ut.PESQUISAR as UT_PESQUISAR,
ut.PESQUISA_ESPECIAL as UT_PESQUISA_ESPECIAL,
ut.IMPRIMIR as UT_IMPRIMIR,
ut.CRIAR_RELATORIO as UT_CRIAR_RELATORIO,
ut.ITEM_EXCLUIR as UT_ITEM_EXCLUIR,
ut.ITEM_INCLUIR as UT_ITEM_INCLUIR,
ut.CODIGO_QUERY as UT_CODIGO_QUERY,
ut.FILTRO_TRANSACAO as UT_FILTRO_TRANSACAO
from USERS u
left join USERS_TRANSACOES ut on ut.USUARIO = u.USUARIO
left join TRANSACOES t on t.COD_TRANSACAO = ut.COD_TRANSACAO
where u.INATIVO=0 
order by u.usuario asc, t.COD_TRANSACAO

/* CADASTRO DE TRANSACOES */
SELECT 
COD_TRANSACAO
,TRANSACAO
,TABELA_PAI
,VERSAO_LIBERADA
,TITULO
,CONTROL_SISTEMA
FROM TRANSACOES
ORDER BY COD_TRANSACAO ASC

/* CADASTRO DE MODULO*/
SELECT MODULO, CONTROL_MODULO, DESCRITIVO
FROM MODULOS
ORDER BY MODULO


