	IF (SELECT OBJECT_ID('TEMPDB..##NOTAS_PROCESSAR')) IS NOT NULL
		DROP TABLE TEMPDB..##NOTAS_PROCESSAR

	DECLARE @EMPRESA INT;
	DECLARE @FILIAL_ORIGEM VARCHAR(100);
	DECLARE @FILIAL_FILTRO VARCHAR(100);
	DECLARE @DATA_INICIAL SMALLDATETIME;
	DECLARE @DATA_FINAL SMALLDATETIME;
	DECLARE @VERIFICA_LOJA_ENTRADA INT;
	
	SET @EMPRESA = 1;
	SET @FILIAL_ORIGEM = NULL ;
	SET @FILIAL_FILTRO = NULL ;
	SET @DATA_INICIAL = '20190701' ;
	SET @DATA_FINAL = '20190722' ;
		
	/*#4# - VALIDA PARAMETRO VERIFICA_LOJA_ENTRADA*/
   SELECT @VERIFICA_LOJA_ENTRADA = CASE WHEN ISNULL(VALOR_ATUAL, '.F.') = '.T.'
										 THEN 1
										 ELSE 0
								   END
   FROM   PARAMETROS(NOLOCK)
   WHERE  PARAMETRO = 'VERIFICA_LOJA_ENTRADA';   
   SELECT @VERIFICA_LOJA_ENTRADA = ISNULL(@VERIFICA_LOJA_ENTRADA, 0);

	--FATURAMENTO
	--APENAS TRANSFERÊNCIAS QUE NÃO SEJAM PARA LOJAS
	SELECT DISTINCT INTEGRAR = CAST(0 AS BIT),
					TABELA = 'F',
					ORIGEM = F2.FILIAL,
					DESTINO = F.FILIAL,				
	                NUMERO_NF = FAT.NF_SAIDA,
	                SERIE_NF = FAT.SERIE_NF, 				               
	                EMISSAO = FAT.EMISSAO,
	                VALOR_TOTAL = FAT.VALOR_TOTAL,
	                CHAVE_NFE = FAT.CHAVE_NFE,
	                PROTOCOLO_AUTORIZACAO_NFE = FAT.PROTOCOLO_AUTORIZACAO_NFE,
	                DATA_AUTORIZACAO_NFE= FAT.DATA_AUTORIZACAO_NFE,
	                FIN_EMISSAO_NFE = FAT.FIN_EMISSAO_NFE,
	                TIPO_EMISSAO_NFE = FAT.TIPO_EMISSAO_NFE,
	                STATUS_NFE = FAT.STATUS_NFE,
	                MOTIVO =	CASE WHEN ISNULL(FAT.NOTA_CANCELADA,0) <> 0 THEN 'Nota fiscal de origem está cancelada' ELSE
	                			CASE WHEN (CES.NUMERO_MODELO_FISCAL = '55' AND FAT.STATUS_NFE <> 5) THEN 'Nota fiscal de origem é eletrônica e não está autorizada na SEFAZ.' ELSE
	                			CASE WHEN ISNULL(F.INDICA_FRANQUIA,0) <> 0 THEN 'Filial de destino está marcada como franquia.' ELSE
	                			CASE WHEN F.INDICA_BENEFICIADOR <> 0 THEN 'Filial de destino está marcada como beneficiador.'
	                			ELSE 'Integração não executada.' END END END END,
	                COD_TRANSACAO = FAT.COD_TRANSACAO, /*#2#*/
	                DT_ENT_CONFERIDA = LE.DATA_ENTRADA_CONFERIDA,
	                DT_ENT_EMISSAO = LE.EMISSAO
	INTO ##NOTAS_PROCESSAR
	FROM   FATURAMENTO FAT (NOLOCK) 
	        JOIN EMPRESA EMP (NOLOCK) 
	            ON EMP.EMPRESA = FAT.EMPRESA 
	        JOIN NATUREZAS_SAIDAS NS (NOLOCK) 
	            ON FAT.NATUREZA_SAIDA = NS.NATUREZA_SAIDA 
	        JOIN NATUREZAS_ENTRADAS NE (NOLOCK) 
	            ON ( NS.NATUREZA_ENTRADA_AUTOMATICA = NE.NATUREZA ) 
	        JOIN FILIAIS F (NOLOCK) 
	            ON FAT.NOME_CLIFOR = F.FILIAL 
	        JOIN FILIAIS F2 (NOLOCK) 
	            ON ( FAT.FILIAL = F2.FILIAL ) 
	        INNER JOIN SERIES_NF AS SN
	                ON SN.SERIE_NF = FAT.SERIE_NF 
	        INNER JOIN CTB_ESPECIE_SERIE CES
	                ON CES.ESPECIE_SERIE = SN.ESPECIE_SERIE
			LEFT JOIN (	SELECT 	FILIAL_ORIGEM,
            					NUMERO_NF_TRANSFERENCIA, 
		                        SERIE_NF_ENTRADA, 
								MAX(EMISSAO)                                                     AS EMISSAO,
								MAX(DATA_ENTRADA_CONFERIDA)										 AS DATA_ENTRADA_CONFERIDA,								
								MAX(CAST(ISNULL(( LOJA_ENTRADAS.ENTRADA_CONFERIDA ), 1) AS INT)) AS ENTRADA_CONFERIDA,
								ROMANEIO_NF_SAIDA
						FROM   LOJA_ENTRADAS (NOLOCK) 
						GROUP  BY	FILIAL_ORIGEM, 
									NUMERO_NF_TRANSFERENCIA, 
									SERIE_NF_ENTRADA,
									ROMANEIO_NF_SAIDA) LE 
                        ON FAT.FILIAL = LE.FILIAL_ORIGEM 
                           AND FAT.NF_SAIDA = LE.NUMERO_NF_TRANSFERENCIA 
                           AND FAT.SERIE_NF = LE.SERIE_NF_ENTRADA
	WHERE  FAT.EMPRESA = @EMPRESA 
	        AND FAT.NOTA_CANCELADA = 0 
	        AND ISNULL(F.MATRIZ_FISCAL, '') <> ISNULL(F2.MATRIZ_FISCAL, '') 
	        AND ( FAT.NOME_CLIFOR = @FILIAL_FILTRO 
	                OR @FILIAL_FILTRO IS NULL ) 
	        AND ( FAT.FILIAL = @FILIAL_ORIGEM 
	                OR @FILIAL_ORIGEM IS NULL ) 
	        AND FAT.EMISSAO BETWEEN @DATA_INICIAL AND @DATA_FINAL
	        AND NOT EXISTS (SELECT 1 
	                        FROM   ENTRADAS ENT (NOLOCK) 
	                        WHERE  ENT.NOME_CLIFOR = FAT.FILIAL 
	                                AND ENT.NF_ENTRADA = FAT.NF_SAIDA 
	                                AND ENT.SERIE_NF_ENTRADA = FAT.SERIE_NF) 
	        AND ISNULL(LE.NUMERO_NF_TRANSFERENCIA, LE.ROMANEIO_NF_SAIDA) IS NULL;

	--FATURAMENTO
	-- APENAS TRANSFERÊNCIAS QUE SEJAM PARA LOJAS
	INSERT INTO ##NOTAS_PROCESSAR
	SELECT DISTINCT INTEGRAR = CAST(0 AS BIT),
					TABELA = 'F',
					ORIGEM =F2.FILIAL,
					DESTINO = F.FILIAL,
	                NUMERO_NF = FAT.NF_SAIDA, 
	                SERIE_NF = FAT.SERIE_NF,                 
	                /*#3#*/
	                EMISSAO = FAT.EMISSAO,
	                /*EMISSAO = COALESCE(LE.DATA_ENTRADA_CONFERIDA, LE.EMISSAO, FAT.EMISSAO), */
	                VALOR_TOTAL = FAT.VALOR_TOTAL, 
	                CHAVE_NFE = FAT.CHAVE_NFE, 
	                PROTOCOLO_AUTORIZACAO_NFE = FAT.PROTOCOLO_AUTORIZACAO_NFE, 
	                DATA_AUTORIZACAO_NFE = FAT.DATA_AUTORIZACAO_NFE, 
	                FIN_EMISSAO_NFE = FAT.FIN_EMISSAO_NFE,
	                TIPO_EMISSAO_NFE = FAT.TIPO_EMISSAO_NFE,
	                STATUS_NFE = FAT.STATUS_NFE,
	                MOTIVO =	CASE WHEN FAT.NOTA_CANCELADA <> 0 THEN 'Nota fiscal de origem está cancelada' ELSE
	                			CASE WHEN (CES.NUMERO_MODELO_FISCAL = '55' AND FAT.STATUS_NFE <> 5) THEN 'Nota fiscal de origem é eletrônica e não está autorizada na SEFAZ.' ELSE
	                			CASE WHEN F.INDICA_FRANQUIA <> 0 THEN 'Filial de destino está marcada como franquia.' ELSE
	                			CASE WHEN F.INDICA_BENEFICIADOR <> 0 THEN 'Filial de destino está marcada como beneficiador.' ELSE
	                			CASE WHEN ISNULL(LE.ENTRADA_CONFERIDA,0) <> 1 AND @VERIFICA_LOJA_ENTRADA = 1 THEN 'Romaneio não foi conferido na loja.' /*#4#*/
	                			ELSE 'Integração não executada.' END END END END END,
					COD_TRANSACAO = FAT.COD_TRANSACAO, /*#2#*/
					DT_ENT_CONFERIDA = LE.DATA_ENTRADA_CONFERIDA,
	                DT_ENT_EMISSAO = LE.EMISSAO
	FROM   FATURAMENTO FAT (NOLOCK) 
	        JOIN EMPRESA EMP (NOLOCK) 
	            ON EMP.EMPRESA = FAT.EMPRESA 
	        JOIN NATUREZAS_SAIDAS NS (NOLOCK) 
	            ON FAT.NATUREZA_SAIDA = NS.NATUREZA_SAIDA 
	        JOIN NATUREZAS_ENTRADAS NE (NOLOCK) 
	            ON ( NS.NATUREZA_ENTRADA_AUTOMATICA = NE.NATUREZA ) 
	        JOIN FILIAIS F (NOLOCK) 
	            ON FAT.NOME_CLIFOR = F.FILIAL 
	        JOIN FILIAIS F2 (NOLOCK) 
	            ON ( FAT.FILIAL = F2.FILIAL ) 
	        INNER JOIN SERIES_NF AS SN
	                ON SN.SERIE_NF = FAT.SERIE_NF 
	        INNER JOIN CTB_ESPECIE_SERIE CES
	                ON CES.ESPECIE_SERIE = SN.ESPECIE_SERIE 
			LEFT JOIN (	SELECT 	FILIAL_ORIGEM,
            					NUMERO_NF_TRANSFERENCIA, 
		                        SERIE_NF_ENTRADA,		                         
								MAX(EMISSAO)                                                     AS EMISSAO,
								MAX(DATA_ENTRADA_CONFERIDA)										 AS DATA_ENTRADA_CONFERIDA,								
								MAX(CAST(ISNULL(( LOJA_ENTRADAS.ENTRADA_CONFERIDA ), 0 /*#4#*/) AS INT)) AS ENTRADA_CONFERIDA,
								ROMANEIO_NF_SAIDA
						FROM   LOJA_ENTRADAS (NOLOCK) 
						GROUP  BY	FILIAL_ORIGEM, 
									NUMERO_NF_TRANSFERENCIA, 
									SERIE_NF_ENTRADA,
									ROMANEIO_NF_SAIDA) LE 
                        ON FAT.FILIAL = LE.FILIAL_ORIGEM 
                           AND FAT.NF_SAIDA = LE.NUMERO_NF_TRANSFERENCIA 
                           AND FAT.SERIE_NF = LE.SERIE_NF_ENTRADA
	WHERE  FAT.EMPRESA = @EMPRESA 
	        AND FAT.NOTA_CANCELADA = 0 
	        AND ISNULL(F.MATRIZ_FISCAL, '') <> ISNULL(F2.MATRIZ_FISCAL, '') 
	        AND ( FAT.NOME_CLIFOR  = @FILIAL_FILTRO 
	                OR @FILIAL_FILTRO IS NULL ) 
	        AND ( FAT.FILIAL = @FILIAL_ORIGEM 
	                OR @FILIAL_ORIGEM IS NULL ) 
			/*#3#*/	               
			AND CAST(CONVERT(CHAR(8), FAT.EMISSAO, 112) AS DATETIME) BETWEEN @DATA_INICIAL AND @DATA_FINAL
	        /*AND CAST(CONVERT(CHAR(8),COALESCE(LE.DATA_ENTRADA_CONFERIDA, LE.EMISSAO, FAT.EMISSAO),112) AS DATETIME) BETWEEN @DATA_INICIAL AND @DATA_FINAL*/
	        AND NOT EXISTS (SELECT 1 
	                        FROM   ENTRADAS ENT (NOLOCK) 
	                        WHERE  ENT.NOME_CLIFOR = FAT.FILIAL 
	                                AND ENT.NF_ENTRADA = FAT.NF_SAIDA 
	                                AND ENT.SERIE_NF_ENTRADA = FAT.SERIE_NF)
			AND ISNULL(LE.NUMERO_NF_TRANSFERENCIA, LE.ROMANEIO_NF_SAIDA) IS NOT NULL;

	--LOJA_NOTA_FISCAL
	--APENAS TRANSFERENCIAS QUE NÃO SEJAM PARA LOJAS
	INSERT INTO ##NOTAS_PROCESSAR
	SELECT DISTINCT	INTEGRAR = CAST(0 AS BIT),
					TABELA = 'L',
					ORIGEM = F2.FILIAL,
					DESTINO = F.FILIAL,
	                NUMERO_NF = LJ.NF_NUMERO,
	                SERIE_NF = LJ.SERIE_NF,
	                EMISSAO  = LJ.EMISSAO,
	                VALOR_TOTAL = LJ.VALOR_TOTAL,
	                CHAVE_NFE = LJ.CHAVE_NFE, 
	                PROTOCOLO_AUTORIZACAO_NFE = LJ.PROTOCOLO_AUTORIZACAO_NFE, 
	                DATA_AUTORIZACAO_NFE = LJ.DATA_AUTORIZACAO_NFE, 
	                FIN_EMISSAO_NFE = LJ.FIN_EMISSAO_NFE,
	                TIPO_EMISSAO_NFE = LJ.TIPO_EMISSAO_NFE,
	                STATUS_NFE = LJ.STATUS_NFE,
	                MOTIVO =	CASE WHEN LJ.NOTA_CANCELADA <> 0 THEN 'Nota fiscal de origem está cancelada' ELSE
	                			CASE WHEN (CES.NUMERO_MODELO_FISCAL = '55' AND LJ.STATUS_NFE <> 5) THEN 'Nota fiscal de origem é eletrônica e não está autorizada na SEFAZ.' ELSE
	                			CASE WHEN F.INDICA_FRANQUIA <> 0 THEN 'Filial de destino está marcada como franquia.' ELSE
	                			CASE WHEN F.INDICA_BENEFICIADOR <> 0 THEN 'Filial de destino está marcada como beneficiador.'
	                			ELSE 'Integração não executada.' END END END END,
					COD_TRANSACAO = 'LOJA', /*#2#*/
	                DT_ENT_CONFERIDA = LE.DATA_ENTRADA_CONFERIDA,
	                DT_ENT_EMISSAO = LE.EMISSAO
	FROM   LOJA_NOTA_FISCAL LJ (NOLOCK) 
	JOIN EMPRESA E (NOLOCK) 
	    ON E.EMPRESA = LJ.EMPRESA 
	JOIN LOJAS_NATUREZA_OPERACAO LNO (NOLOCK) 
	    ON LJ.NATUREZA_OPERACAO_CODIGO = LNO.NATUREZA_OPERACAO_CODIGO 
	JOIN NATUREZAS_SAIDAS NS (NOLOCK) 
	    ON LNO.NATUREZA_SAIDA = NS.NATUREZA_SAIDA 
	JOIN NATUREZAS_ENTRADAS NE (NOLOCK) 
	    ON NS.NATUREZA_ENTRADA_AUTOMATICA = NE.NATUREZA 
	JOIN FILIAIS F (NOLOCK) 
	    ON LJ.COD_CLIFOR = F.COD_FILIAL 
	JOIN LOJAS_VAREJO LV (NOLOCK) 
	    ON LV.CODIGO_FILIAL = LJ.CODIGO_FILIAL 
	JOIN FILIAIS F2 (NOLOCK) 
	    ON LV.FILIAL = F2.FILIAL 
	INNER JOIN SERIES_NF AS SN
	        ON SN.SERIE_NF = LJ.SERIE_NF 
	INNER JOIN CTB_ESPECIE_SERIE CES
	        ON CES.ESPECIE_SERIE = SN.ESPECIE_SERIE            
	LEFT JOIN TRANSPORTADORAS TRANSP WITH (NOLOCK)
	        ON TRANSP.TRANSPORTADORA = LJ.TRANSPORTADORA 
	LEFT JOIN LOJA_ENTRADAS AS LE
	        ON LV.FILIAL = LE.FILIAL_ORIGEM                  
	            AND LJ.NF_NUMERO = ISNULL(LE.NUMERO_NF_TRANSFERENCIA, LE.ROMANEIO_NF_SAIDA)
	            AND LJ.SERIE_NF = LE.SERIE_NF_ENTRADA
	WHERE	LJ.EMPRESA = @EMPRESA 
	        AND LJ.NOTA_CANCELADA = 0 
	        AND ISNULL(F.MATRIZ_FISCAL, '') <> ISNULL(F2.MATRIZ_FISCAL, '') 
	        AND ( F.FILIAL = @FILIAL_FILTRO 
	                OR @FILIAL_FILTRO IS NULL ) 
	        AND ( F2.FILIAL = @FILIAL_ORIGEM 
	                OR @FILIAL_ORIGEM IS NULL ) 
	        AND LJ.EMISSAO BETWEEN @DATA_INICIAL AND @DATA_FINAL 
	        AND NOT EXISTS (SELECT 1 
	                        FROM   ENTRADAS E (NOLOCK) 
	                        WHERE  E.NOME_CLIFOR = F2.FILIAL 
	                                AND E.NF_ENTRADA = LJ.NF_NUMERO 
	                                AND E.SERIE_NF_ENTRADA = LJ.SERIE_NF) 
	        AND ISNULL(LE.NUMERO_NF_TRANSFERENCIA, LE.ROMANEIO_NF_SAIDA) IS NULL;

	--LOJA_NOTA_FISCAL
	--APENAS TRANSFERENCIAS QUE SEJAM PARA LOJAS
	INSERT INTO ##NOTAS_PROCESSAR
	SELECT DISTINCT INTEGRAR = CAST(0 AS BIT),
					TABELA = 'L',
					ORIGEM =F2.FILIAL,
					DESTINO = F.FILIAL,
	                NUMERO_NF = LJ.NF_NUMERO, 
	                SERIE_NF = LJ.SERIE_NF,
	                /*#3#*/
	                EMISSAO = LJ.EMISSAO,
	                /*EMISSAO = COALESCE(LE.DATA_ENTRADA_CONFERIDA, LE.EMISSAO, LJ.EMISSAO), */
	                VALOR_TOTAL = LJ.VALOR_TOTAL,
	                CHAVE_NFE = LJ.CHAVE_NFE, 
	                PROTOCOLO_AUTORIZACAO_NFE = LJ.PROTOCOLO_AUTORIZACAO_NFE, 
	                DATA_AUTORIZACAO_NFE = LJ.DATA_AUTORIZACAO_NFE, 
	                FIN_EMISSAO_NFE = LJ.FIN_EMISSAO_NFE,
	                TIPO_EMISSAO_NFE = LJ.TIPO_EMISSAO_NFE,
	                STATUS_NFE = LJ.STATUS_NFE,
	                MOTIVO =	CASE WHEN LJ.NOTA_CANCELADA <> 0 THEN 'Nota fiscal de origem está cancelada' ELSE
	                			CASE WHEN (CES.NUMERO_MODELO_FISCAL = '55' AND LJ.STATUS_NFE <> 5) THEN 'Nota fiscal de origem é eletrônica e não está autorizada na SEFAZ.' ELSE
	                			CASE WHEN F.INDICA_FRANQUIA <> 0 THEN 'Filial de destino está marcada como franquia.' ELSE
	                			CASE WHEN F.INDICA_BENEFICIADOR <> 0 THEN 'Filial de destino está marcada como beneficiador.' ELSE
	                			CASE WHEN ISNULL(LE.ENTRADA_CONFERIDA,0) <> 1 AND @VERIFICA_LOJA_ENTRADA = 1 THEN 'Romaneio não foi conferido na loja.' /*#4#*/
	                			ELSE 'Integração não executada.' END END END END END,
					COD_TRANSACAO = 'LOJA', /*#2#*/	                			
	                DT_ENT_CONFERIDA = LE.DATA_ENTRADA_CONFERIDA,
	                DT_ENT_EMISSAO = LE.EMISSAO
	FROM   LOJA_NOTA_FISCAL LJ (NOLOCK) 
	        JOIN EMPRESA E (NOLOCK) 
	            ON E.EMPRESA = LJ.EMPRESA 
	        JOIN LOJAS_NATUREZA_OPERACAO LNO (NOLOCK) 
	            ON LJ.NATUREZA_OPERACAO_CODIGO = LNO.NATUREZA_OPERACAO_CODIGO 
	        JOIN NATUREZAS_SAIDAS NS (NOLOCK) 
	            ON LNO.NATUREZA_SAIDA = NS.NATUREZA_SAIDA 
	        JOIN NATUREZAS_ENTRADAS NE (NOLOCK) 
	            ON NS.NATUREZA_ENTRADA_AUTOMATICA = NE.NATUREZA 
	        JOIN FILIAIS F (NOLOCK) 
	            ON LJ.COD_CLIFOR = F.COD_FILIAL 
	        JOIN LOJAS_VAREJO LV (NOLOCK) 
	            ON LV.CODIGO_FILIAL = LJ.CODIGO_FILIAL 
	        JOIN FILIAIS F2 (NOLOCK) 
	            ON LV.FILIAL = F2.FILIAL 
	        INNER JOIN SERIES_NF AS SN
	                ON SN.SERIE_NF = LJ.SERIE_NF
	        INNER JOIN CTB_ESPECIE_SERIE CES
	                ON CES.ESPECIE_SERIE = SN.ESPECIE_SERIE
	        LEFT JOIN TRANSPORTADORAS TRANSP WITH (NOLOCK)                  
	                ON TRANSP.TRANSPORTADORA = LJ.TRANSPORTADORA 
	        LEFT JOIN LOJA_ENTRADAS AS LE
	                ON LV.FILIAL = LE.FILIAL_ORIGEM 
	                    AND LJ.NF_NUMERO = ISNULL(LE.NUMERO_NF_TRANSFERENCIA, LE.ROMANEIO_NF_SAIDA)
	                    AND LJ.SERIE_NF = LE.SERIE_NF_ENTRADA
	WHERE  LJ.EMPRESA = @EMPRESA
        	AND LJ.NOTA_CANCELADA = 0
	        AND ISNULL(F.MATRIZ_FISCAL, '') <> ISNULL(F2.MATRIZ_FISCAL, '')
	        AND ( F.FILIAL = @FILIAL_FILTRO
	                OR @FILIAL_FILTRO IS NULL)
	        AND ( F2.FILIAL = @FILIAL_ORIGEM
	                OR @FILIAL_ORIGEM IS NULL)
			/*#3#*/	                
			AND LJ.EMISSAO BETWEEN @DATA_INICIAL AND @DATA_FINAL
	        /*AND COALESCE(LE.DATA_ENTRADA_CONFERIDA, LE.EMISSAO, LJ.EMISSAO) BETWEEN @DATA_INICIAL AND @DATA_FINAL*/
	        AND NOT EXISTS (SELECT 1
	                        FROM   ENTRADAS E (NOLOCK)
	                        WHERE  E.NOME_CLIFOR = F2.FILIAL
	                                AND E.NF_ENTRADA = LJ.NF_NUMERO
	                                AND E.SERIE_NF_ENTRADA = LJ.SERIE_NF)
	        AND ISNULL(LE.NUMERO_NF_TRANSFERENCIA, LE.ROMANEIO_NF_SAIDA) IS NOT NULL;
	        
	SELECT * FROM ##NOTAS_PROCESSAR ORDER BY EMISSAO;