select a.*, p.GRIFFE, p.LINHA, p.GRUPO_PRODUTO, p.SUBGRUPO_PRODUTO, p.GRADE, p.ERP_QTD_PACK as TAMANHO_PACK, p.DESC_PRODUTO
from CAEDU_RESERVA_AUTOMATICA_PACK_WMS a
inner join produtos p on p.PRODUTO = a.PRODUTO
where a.caixa not in (select caixa from FATURAMENTO_CAIXAS)
and FILIAL_ORIGEM = (SELECT VALOR_ATUAL FROM PARAMETROS WHERE PARAMETRO = 'PALMA_CD_ORIGEM_DISTRIB')
order by DISTRIBUICAO, FILIAL, a.PRODUTO
